updated on Tue Nov 22 22:01:18 UTC 2011

diff --git a/darwinia/PKGBUILD b/darwinia/PKGBUILD
--- a/darwinia/PKGBUILD
+++ b/darwinia/PKGBUILD
@@ -1,77 +1,72 @@
-# Maintainer: Gadget30000 <gadget3000@msn.com>
+# Maintainer: Gadget30000 <gadget3000 at msn dot com>
 pkgname=darwinia
-pkgver=1.3.0
+pkgver=1.43
 pkgrel=1
 pkgdesc="A virtual themepark, running entirely inside a computer network and populated by a sentient evolving life form called the Darwinians"
 arch=('i686' 'x86_64')
 url="http://www.introversion.co.uk/darwinia/"
 license=('custom')
+depends=('mesa' 'sdl' 'libvorbis')
+source=('darwinia.desktop')
+md5sums=('6bb7df553937b8d94f842d4ba1994ffe')
+
 if [ "${CARCH}" = "x86_64" ]; then
-depends=('lib32-gtk' 'lib32-mesa' 'lib32-libstdc++5')
-makedepends=('lib32-gcc-libs')
-elif [ "${CARCH}" = "i686" ]; then
-depends=('gtk' 'mesa' 'libstdc++5')
-makedepends=('gcc-libs')
+_carch=amd64
+_archive_md5="3e6f7a3a8e1131334d2e0371dd9f7258"
+_bin_postfix="_64"
+else
+_carch=i386
+_archive_md5="b29633364637e9ac0079068c7b57a861"
+_bin_postfix=
 fi
-source=('http://www.introversion.co.uk/darwinia/downloads/darwinia-full-1.3.0.sh'
-        'darwinia'
-        'darwinia.desktop')
-md5sums=('e8dbe3f3a2f58fd6890a022b66fc36ac'
-         '21f3357ac6ac2e2b3c42f1b2d0158c89'
-         'c55c7d8c962b30b8ef9a87c92c5749cd')
+
+_archive="darwinia_${pkgver}_${_carch}.tar.gz"
 
 build() {
-  cd "$srcdir"
-  install -d ${srcdir}/darwinia-full
-  chmod +x darwinia-full-1.3.0.sh
-  echo Extracting Darwinia
-  ./darwinia-full-1.3.0.sh --noexec --nox11 --target darwinia-full
-  echo Manually Moving Darwinia Files
-  cd ${srcdir}/darwinia-full
-  install -d ${pkgdir}/opt/darwinia/lib
-  install -D -m755 lib/darwinia.bin.x86 ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/patch.dat ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/language.dat ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/libSDL-1.2.so.0 ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/libogg.so.0 ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/libvorbis.so.0 ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/libvorbisfile.so.3 ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D lib/open-www.sh ${pkgdir}/opt/darwinia/lib/ || return 1
-  install -D darwinian.png ${pkgdir}/opt/darwinia/ || return 1
-  install -D -m775 bin/Linux/x86/darwinia ${pkgdir}/opt/darwinia/ || return 1
-  install -D LICENSE ${pkgdir}/opt/darwinia/ || return 1
-  install -D README ${pkgdir}/opt/darwinia/ || return 1  
+  cd ${srcdir}
+
+  if [ ! -f ${_darwiniaarchivelocation}${_archive} ]; then
+	  if [ ! -f ${_archive} ] && [ -n "${_humbleintbundlekey}" ]; then
+		rm -f ${_archive}* index.html\?key\=${_humbleintbundlekey}*
+		wget http://www.humblebundle.com/?key=${_humbleintbundlekey}
+		wget $(cat index.html\?key\=${_humbleintbundlekey} | grep "${_archive}" | cut -d "'" -f 10)
+		mv ${_archive}* ${_archive}
+	  elif [ -z "${_humbleintbundlekey}" ]; then
+		echo You can automate the download of the archive using the _humbleintbundlekey bash variable.
+		echo Just add \'export _humbleintbundlekey\=\<Your key here\>\' to \.bashrc
+		echo
+		echo Otherwise please just place ${_archive} into $(pwd)/
+		echo Press Enter to continue
+		read -a _unused
+	  fi
+  fi
+
+  if [ ! -f ${_darwiniaarchivelocation}${_archive} ]; then
+    echo "${_darwiniaarchivelocation}${_archive} not found!"
+    return 1
+  fi  
+
+  if ! echo "${_archive_md5}  ${_darwiniaarchivelocation}${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_darwiniaarchivelocation}${_archive}"
+    return 1
+  fi
+
+  install -d ${pkgdir}/usr/share/
+  tar xzf ${_darwiniaarchivelocation}${_archive} -C ${pkgdir}/usr/share/
   install -d ${pkgdir}/usr/bin
-  install -D ${srcdir}/darwinia ${pkgdir}/usr/bin/ || return 1
+  ln -s /usr/share/darwinia/darwinia.bin.x86${_bin_postfix} ${pkgdir}/usr/bin/darwinia
 
-  if [ -f /media/cd/gamefiles/main.dat ]; then
-     install -D /media/cd/gamefiles/main.dat ${pkgdir}/opt/darwinia/lib/ || return 1
-     install -D /media/cd/gamefiles/sounds.dat ${pkgdir}/opt/darwinia/lib/ || return 1
-  else
-     echo I can\'t find the Darwinia cd files.
-     echo Either type the location of the \'gamefiles\' directory or type m to do it manually later.
-     echo eg /mnt/cd/gamefiles
-     read -e ANSWER
-     if [ $ANSWER != m ];then
-        install -D ${ANSWER}/main.dat ${pkgdir}/opt/darwinia/lib/ || return 1
-        install -D ${ANSWER}/sounds.dat ${pkgdir}/opt/darwinia/lib/ || return 1
-     else
-        echo In which case you need to put main.dat and sounds.dat into /opt/darwinia/lib/ later.
-     fi
-  fi
+  #Copy Icon
+  install -d ${pkgdir}/usr/share/pixmaps/
+  install -D -m644 ${pkgdir}/usr/share/darwinia/darwinian.png ${pkgdir}/usr/share/pixmaps/ || return 1
 
-  echo Updating an Included Library File
-  if [ "${CARCH}" = "x86_64" ]; then
-      install -D /usr/lib32/libgcc_s.so.1 ${pkgdir}/opt/darwinia/lib/ || return 1
-  elif [ "${CARCH}" = "i686" ]; then
-      install -D /usr/lib/libgcc_s.so.1 ${pkgdir}/opt/darwinia/lib/ || return 1
-  fi
-
-  echo Installing Desktop File
+  #Copy Desktop File
   install -d ${pkgdir}/usr/share/applications
   cp ${srcdir}/darwinia.desktop ${pkgdir}/usr/share/applications/
 
-  echo Installing the License
+  #Copy License
   install -d ${pkgdir}/usr/share/licenses/${pkgname}
-  install -D -m644 ${srcdir}/darwinia-full/LICENSE ${pkgdir}/usr/share/licenses/${pkgname}/ || return 1
+  install -D -m644 ${pkgdir}/usr/share/darwinia/license.txt ${pkgdir}/usr/share/licenses/${pkgname}/ || return 1
+
+  chown -Rh root:root ${pkgdir}/usr/share/darwinia
 }
