updated on Thu Mar  7 04:09:02 UTC 2013

diff --git a/darwinia/PKGBUILD b/darwinia/PKGBUILD
--- a/darwinia/PKGBUILD
+++ b/darwinia/PKGBUILD
@@ -4,9 +4,9 @@
 pkgname=darwinia
 pkgver=1.43
 pkgrel=2
-pkgdesc="Save Darwinians from the Viral Infection that threatens their existance (game sold separately)"
+pkgdesc='Save Darwinians from the Viral Infection that threatens their existance (game sold separately)'
 arch=('i686' 'x86_64')
-url="http://www.introversion.co.uk/darwinia/"
+url='http://www.introversion.co.uk/darwinia/'
 license=('custom')
 depends=('glu' 'sdl' 'libvorbis')
 if [ "${CARCH}" = "x86_64" ]; then
@@ -32,7 +32,7 @@ md5sums=('bed5bb0f56b58ddc842122cee08c8c76' "${_gamepkgsum}")
 # To auto-search through a directory containing Humble Bundle downloads, you
 # could set:
 # DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
-DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; echo "Read this PKGBUILD for more info."; exit 1')
 PKGEXT='.pkg.tar'
 
 package() {
diff --git a/multiwinia/PKGBUILD b/multiwinia/PKGBUILD
--- a/multiwinia/PKGBUILD
+++ b/multiwinia/PKGBUILD
@@ -4,9 +4,9 @@
 pkgname=multiwinia
 pkgver=1.3.1
 pkgrel=3
-pkgdesc="Challenge your opponent to a game of stick-man slaughter (game sold separately)"
+pkgdesc='Challenge your opponent to a game of stick-man slaughter (game sold separately)'
 arch=('i686' 'x86_64')
-url="http://www.introversion.co.uk/multiwinia/"
+url='http://www.introversion.co.uk/multiwinia/'
 license=('custom')
 depends=('glu' 'openal' 'sdl' 'libvorbis' 'libpng12')
 if [ "${CARCH}" = "x86_64" ]; then
@@ -30,10 +30,10 @@ md5sums=('59653ec01acf2befc0211c4cd7ac13bc' "${_gamepkgsum}")
 # To auto-search through a directory containing Humble Bundle downloads, you
 # could set:
 # DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
-DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; echo "Read this PKGBUILD for more info."; exit 1')
 PKGEXT='.pkg.tar'
 
-build() {
+package() {
   cd "${srcdir}/${pkgname}"
 
   install -d "${pkgdir}/opt/${pkgname}/"
