updated on Wed Jan 16 17:15:58 UTC 2013

diff --git a/darwinia/PKGBUILD b/darwinia/PKGBUILD
--- a/darwinia/PKGBUILD
+++ b/darwinia/PKGBUILD
@@ -1,75 +1,54 @@
-# Maintainer: Gadget30000 <gadget3000 at msn dot com>
+# Contributor: Gadget30000 <gadget3000 at msn dot com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
+
 pkgname=darwinia
 pkgver=1.43
-pkgrel=1
-pkgdesc="A virtual themepark, running entirely inside a computer network and populated by a sentient evolving life form called the Darwinians"
+pkgrel=2
+pkgdesc="Save Darwinians from the Viral Infection that threatens their existance (game sold separately)"
 arch=('i686' 'x86_64')
 url="http://www.introversion.co.uk/darwinia/"
 license=('custom')
-depends=('mesa' 'sdl' 'libvorbis')
+depends=('glu' 'sdl' 'libvorbis')
 source=('darwinia.desktop')
-md5sums=('6bb7df553937b8d94f842d4ba1994ffe')
-
+md5sums=('bed5bb0f56b58ddc842122cee08c8c76')
 if [ "${CARCH}" = "x86_64" ]; then
-_carch=amd64
-_archive_md5="3e6f7a3a8e1131334d2e0371dd9f7258"
-_bin_postfix="_64"
+  source+=("hib://${pkgname}_${pkgver}_amd64.tar.gz")
+  md5sums+=('3e6f7a3a8e1131334d2e0371dd9f7258')
+  _bin_postfix='_64'
+  _extracted_folder="${pkgname}"
 else
-_carch=i386
-_archive_md5="b29633364637e9ac0079068c7b57a861"
-_bin_postfix=
+  source+=("hib://${pkgname}_${pkgver}_i386.tar.gz")
+  md5sums+=('b29633364637e9ac0079068c7b57a861')
+  _bin_postfix=
+  _extracted_folder='Darwinia'
 fi
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+PKGEXT='.pkg.tar'
 
-_archive="darwinia_${pkgver}_${_carch}.tar.gz"
+package() {
+  cd "${srcdir}/${_extracted_folder}"
 
-build() {
-  cd ${srcdir}
+  install -d "${pkgdir}/opt/${pkgname}/"
+  install -m755 -t "${pkgdir}/opt/${pkgname}/" darwinia.bin.x86${_bin_postfix}
+  install -m644 -t "${pkgdir}/opt/${pkgname}/" language.dat main.dat sounds.dat
 
-  if [ ! -f ${_darwiniaarchivelocation}${_archive} ]; then
-	  if [ ! -f ${_archive} ] && [ -n "${_humbleintbundlekey}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humbleintbundlekey}*
-		wget http://www.humblebundle.com/?key=${_humbleintbundlekey}
-		wget $(cat index.html\?key\=${_humbleintbundlekey} | grep "${_archive}" | cut -d "'" -f 10)
-		mv ${_archive}* ${_archive}
-	  elif [ -z "${_humbleintbundlekey}" ]; then
-		echo You can automate the download of the archive using the _humbleintbundlekey bash variable.
-		echo Just add \'export _humbleintbundlekey\=\<Your key here\>\' to \.bashrc
-		echo
-		echo Otherwise please just place ${_archive} into $(pwd)/
-		echo Press Enter to continue
-		read -a _unused
-	  fi
-  fi
+  install -d "${pkgdir}/usr/bin"
+  ln -s /opt/${pkgname}/darwinia.bin.x86${_bin_postfix} \
+      "${pkgdir}/usr/bin/darwinia"
+  install -Dm644 darwinian.png "${pkgdir}/usr/share/pixmaps/darwinian.png"
+  install -Dm644 license.txt \
+      "${pkgdir}/usr/share/licenses/${pkgname}/license.txt"
 
-  if [ ! -f ${_darwiniaarchivelocation}${_archive} ]; then
-    echo "${_darwiniaarchivelocation}${_archive} not found!"
-    return 1
-  fi  
-
-  if ! echo "${_archive_md5}  ${_darwiniaarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_darwiniaarchivelocation}${_archive}"
-    return 1
-  fi
-
-  install -d ${pkgdir}/usr/share/
-  tar xzf ${_darwiniaarchivelocation}${_archive} -C ${pkgdir}/usr/share/
-  if [ "${CARCH}" = "i686" ]; then
-    mv ${pkgdir}/usr/share/Darwinia ${pkgdir}/usr/share/darwinia
-  fi
-  install -d ${pkgdir}/usr/bin
-  ln -s /usr/share/darwinia/darwinia.bin.x86${_bin_postfix} ${pkgdir}/usr/bin/darwinia
-
-  #Copy Icon
-  install -d ${pkgdir}/usr/share/pixmaps/
-  install -D -m644 ${pkgdir}/usr/share/darwinia/darwinian.png ${pkgdir}/usr/share/pixmaps/ || return 1
-
-  #Copy Desktop File
-  install -d ${pkgdir}/usr/share/applications
-  cp ${srcdir}/darwinia.desktop ${pkgdir}/usr/share/applications/
-
-  #Copy License
-  install -d ${pkgdir}/usr/share/licenses/${pkgname}
-  install -D -m644 ${pkgdir}/usr/share/darwinia/license.txt ${pkgdir}/usr/share/licenses/${pkgname}/ || return 1
-
-  chown -Rh root:root ${pkgdir}/usr/share/darwinia
+  install -Dm644 "${srcdir}/darwinia.desktop" \
+      "${pkgdir}/usr/share/applications/darwinia.desktop"
 }
diff --git a/psychonauts/PKGBUILD b/psychonauts/PKGBUILD
--- a/psychonauts/PKGBUILD
+++ b/psychonauts/PKGBUILD
@@ -1,8 +1,8 @@
 # Maintainer: Eric Anderson <ejona86 at gmail dot com>
 
 pkgname=psychonauts
-pkgver=20120815
-_srcpkgver=08152012
+pkgver=20130104
+_srcpkgver=01042012
 pkgrel=1
 pkgdesc="A mind-bending platforming adventure (game sold separately)"
 arch=('i686' 'x86_64')
@@ -20,17 +20,22 @@ options=('!strip')
 _gamepkg="${pkgname}-linux-${_srcpkgver}-bin"
 source=("${pkgname}.desktop"
         "psychonauts.sh"
-        "${_gamepkg}")
+        "hib://${_gamepkg}")
 md5sums=('91be805610718903bea5c3a3d1d127cf'
          '6282a96e6c4c4f6f94f92d6f2dfdbefe'
-         'd0cf9a15a13a778e7ea67c5178b9c72d')
+         '506fdad8ce1610cc39bfad137543d714')
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 PKGEXT='.pkg.tar'
-
-if [ ! -f "${startdir}/${_gamepkg}" ]; then
-  warning ""
-  warning "Requires purchased game download placed at ${startdir}/${_gamepkg}"
-  warning ""
-fi
 
 build(){
     cd "${srcdir}"
@@ -38,10 +43,10 @@ build(){
 }
 
 package(){
-    cd "${srcdir}"
+    cd "${srcdir}/${pkgname}"
 
     mkdir -p "${pkgdir}/opt"
-    cp -Rl "${srcdir}/${pkgname}/data" "${pkgdir}/opt/"
+    cp -Rl data "${pkgdir}/opt/"
     mv "${pkgdir}/opt/data" "${pkgdir}/opt/${pkgname}"
 
     # Use system-provided libraries
@@ -51,17 +56,17 @@ package(){
     install -D -m644 "${srcdir}/${pkgname}.desktop" \
         "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 
-    install -D -m644 "${srcdir}/${pkgname}/data/Documents/EULAs/EULA.rtf" \
+    install -D -m644 data/Documents/EULAs/EULA.rtf \
         "${pkgdir}/usr/share/licenses/${pkgname}/EULA.rtf"
-    install -D -m644 "${srcdir}/${pkgname}/data/Documents/EULAs/Cider-EULA-de (German).rtf" \
+    install -D -m644 "data/Documents/EULAs/Cider-EULA-de (German).rtf" \
         "${pkgdir}/usr/share/licenses/${pkgname}/Cider-EULA-de (German).rtf"
-    install -D -m644 "${srcdir}/${pkgname}/data/Documents/EULAs/Cider-EULA-en (English).rtf" \
+    install -D -m644 "data/Documents/EULAs/Cider-EULA-en (English).rtf" \
         "${pkgdir}/usr/share/licenses/${pkgname}/Cider-EULA-en (English).rtf"
-    install -D -m644 "${srcdir}/${pkgname}/data/Documents/EULAs/Cider-EULA-es (Spanish).rtf" \
+    install -D -m644 "data/Documents/EULAs/Cider-EULA-es (Spanish).rtf" \
         "${pkgdir}/usr/share/licenses/${pkgname}/Cider-EULA-es (Spanish).rtf"
-    install -D -m644 "${srcdir}/${pkgname}/data/Documents/EULAs/Cider-EULA-fr (French).rtf" \
+    install -D -m644 "data/Documents/EULAs/Cider-EULA-fr (French).rtf" \
         "${pkgdir}/usr/share/licenses/${pkgname}/Cider-EULA-fr (French).rtf"
-    install -D -m644 "${srcdir}/${pkgname}/data/Documents/EULAs/Cider-EULA-it (Italian).rtf" \
+    install -D -m644 "data/Documents/EULAs/Cider-EULA-it (Italian).rtf" \
         "${pkgdir}/usr/share/licenses/${pkgname}/Cider-EULA-it (Italian).rtf"
 
     install -D -m755 "${srcdir}/psychonauts.sh" "${pkgdir}/usr/bin/${pkgname}"
diff --git a/vibed/vibed.install b/vibed/vibed.install
--- a/vibed/vibed.install
+++ b/vibed/vibed.install
@@ -4,56 +4,98 @@ GROUP_NAME=$USER_NAME
 USER_COMMENT="Vibe user"
 CONFIG_FILE="/etc/vibe/vibe.conf"
 SYMLINK_FILE="/usr/bin/vibe"
+BASE_DIR="/usr/share/vibed"
 
-pre_install() {
-    # mostly copied from setup_linux.sh
+# utility
+
+remove() {
+    if [[ $1 ]]
+    then
+	REINSTALL=$1
+    else
+        REINSTALL=false
+    fi
+
+    /usr/sbin/userdel $USER_NAME 2>/dev/null || true
+    /usr/sbin/groupdel $GROUP_NAME 2>/dev/null || true
+
+    if [ ! $REINSTALL ]
+    then
+        rm -f $CONFIG_FILE
+        rmdir -p $(dirname $CONFIG_FILE) 2>/dev/null || true
+    fi
+
+    rm -f $SYMLINK_FILE
+}
+
+install() {
+    if [[ $1 ]]
+    then
+	REINSTALL=$1
+    else
+        REINSTALL=false
+    fi
+
     set -e
 
-    echo "Checking for root priviledges..."
-    # root privileges required
-    [ "root" != "$USER" ] && exec sudo $0 "$@"
+    # force to be root
+    test "root" != "$USER" && echo '"root" privileges required...' && exec sudo "$@"
+    echo -en "\033[0A                              \015"
  
     # create a symlink to the vibe script
-    echo "Creating symlink in $SYMLINK_FILE..."
-    ln -sf /usr/share/vibed/bin/vibe $SYMLINK_FILE
+    ln -sf ${BASE_DIR}/bin/vibe $SYMLINK_FILE
 
     # creating group if he isn't already there
     if ! getent group $GROUP_NAME >/dev/null; then
-        echo "Creating group $GROUP_NAME..."
         /usr/sbin/groupadd -r $GROUP_NAME >/dev/null
     fi
 
     # creating user if he isn't already there
     if ! getent passwd $USER_NAME >/dev/null; then
-        echo "Creating user $USER_NAME..."
         /usr/sbin/useradd -r -g $GROUP_NAME -c "$USER_COMMENT" $USER_NAME >/dev/null
     fi
 
-    # create/overwrite configuration file
-    echo "Creating new config file in $CONFIG_FILE..."
-    USER_ID=$(getent passwd $USER_NAME | cut -d: -f3)
-    GROUP_ID=$(getent group $GROUP_NAME | cut -d: -f3)
-    mkdir -p $(dirname $CONFIG_FILE)
-    echo -e '{
-        "uid": '$USER_ID',
-        "gid": '$GROUP_ID'
-    }' >$CONFIG_FILE
+    if [ ! $REINSTALL ]
+    then
+	    # create/overwrite configuration file
+	    USER_ID=$(getent passwd $USER_NAME | cut -d: -f3)
+	    GROUP_ID=$(getent group $GROUP_NAME | cut -d: -f3)
+	    mkdir -p $(dirname $CONFIG_FILE)
+	    echo -e '{
+		"uid": '$USER_ID',
+		"gid": '$GROUP_ID'
+	    }' >$CONFIG_FILE
+    fi
 
-    # if everything went fine
-    echo "Setup finished successfully."
-    echo "You can now run 'vibe' from any vibe.d application directory to run an app (e.g. in examples/http_server/)."
+    # set files/folders permissions
+    chmod 0755 $(find $BASE_DIR/ -type d) $(dirname $CONFIG_FILE)
+    chmod 0644 $(find $BASE_DIR/ ! -type d) $CONFIG_FILE $MENU_FILE
+    chmod 0755 $SYMLINK_FILE
+
+    if [ ! $REINSTALL ]
+    then
+        # if everything went fine
+        echo "Setup finished successfully."
+        echo "You can now run 'vibe' from any vibe.d application directory to run an app (e.g. in examples/http_server/)."
+    fi
+}
+
+# installation stuff
+
+post_install() {
+    install
+}
+
+pre_upgrade() {
+    remove true
+    exit
+}
+
+post_upgrade() {
+    install true
 }
 
 pre_remove() {
-    # remove user, group and configuration file
-    echo "Removing user '$USER_NAME'..."
-    /usr/sbin/userdel $USER_NAME 2>/dev/null || true
-    echo "Removing group '$GROUP_NAME'..."
-    /usr/sbin/groupdel $GROUP_NAME 2>/dev/null || true
-    echo "Removing configuration file $CONFIG_FILE..."
-    rm -f $CONFIG_FILE
-    rmdir -p $(dirname $CONFIG_FILE) 2>/dev/null || true
-    echo "Removing symlink $SYMLINK_FILE..."
-    rm -f $SYMLINK_FILE
+    remove
     exit
 }
