updated on Wed Feb 23 01:08:52 PST 2011

diff --git a/generally/PKGBUILD b/generally/PKGBUILD
--- a/generally/PKGBUILD
+++ b/generally/PKGBUILD
@@ -3,8 +3,8 @@
 #Contributor: ezzetabi <ezzetabi at gawab dot com>
 
 pkgname=generally
-pkgver=1.05
-pkgrel=5
+pkgver=1.10
+pkgrel=1
 pkgdesc="GeneRally is a great, small racing game."
 arch=(i686 x86_64)
 url="http://generally.rscsites.org/"
@@ -13,38 +13,48 @@ makedepends=()
 depends=(wine)
 options=(!strip)
 install=
-source=(generally_res.c icons.tar.gz
-  http://generally.rscsites.org/grfiles/generally105.zip)
+source=(icons.tar.gz )
 noextract=(generally105.zip icons.tar.gz)
 
 build() {
+  cd "$startdir"
+
+  if [ ! -e source ] ;then
+    mkdir source
+    cd source
+    wget -O GeneRally_110.zip  'http://gene-rally.com/download/latest/'
+    wget -O vcredist_x86.exe -nd -c --read-timeout=300 --retry-connrefused --header 'Accept-Encoding: gzip,deflate' 'http://download.microsoft.com/download/5/B/C/5BC5DBB3-652D-4DCE-B14A-475AB85EEF6E/vcredist_x86.exe'
+
+    echo '9e0d0f462210e48b0938925fc2317ef6  GeneRally_110.zip' >md5
+    echo 'b88228d5fef4b6dc019d69d4471f23ec  vcredist_x86.exe' >>md5
+  fi
+  cd "$startdir"/source
+  md5sum --status -c md5 || ( error "Validation failed, please mark the package as out-of-date." && false )
+
   cd "$pkgdir"
   install -d -m 755 usr/share/generally usr/share/applications usr/bin \
-    usr/share/pixmaps || return 1
+    usr/share/pixmaps
 
   bsdtar xf "$srcdir"/icons.tar.gz
   ln -s /usr/share/icons/hicolor/48x48/apps/generally.png \
-    usr/share/pixmaps/generally.png || return 1
+    usr/share/pixmaps/generally.png
 
   cd "$pkgdir"/usr/share/generally
-  bsdtar xf  "$srcdir"/generally105.zip  || return 1
+  bsdtar xf  "$startdir"/source/GeneRally_110.zip
+  cp "$startdir"/source/vcredist_x86.exe .
 
   cd "$pkgdir"
   find usr/ -type f -exec chmod 644 "{}" \; || return 1
   find usr/ -type d -exec chmod 755 "{}" \; || return 1
-
-  cd "$srcdir"
-  gcc -W -Wall -pedantic -o "$pkgdir"/usr/bin/generally_res \
-    generally_res.c || return 1
-  strip "$pkgdir"/usr/bin/generally_res
-  chmod 755 "$pkgdir"/usr/bin/generally_res
 
   #Lets create support files.
 #############################################################################
   cd "$pkgdir"/usr/bin || return 1
   cat << EOF >generally
 #!/bin/bash
+set -e
 
+export WINEARCH=win32
 export WINEPREFIX="\$HOME"/.generally/winefs
 export WINEDLLOVERRIDES="mshtml="
 export XDG_DATA_HOME=/dev/null
@@ -53,28 +63,29 @@ export WINEDEBUG=-all
 echo Starting...
 
 if [ ! -d "\$HOME"/.generally ] ; then
-    mkdir -p "\$HOME"/.generally/Sounds || exit 1
-    mkdir -p "\$HOME"/.generally/winefs || exit 1
+    mkdir -p "\$HOME"/.generally/sounds
 
     cd "\$HOME"/.generally
 
-    ln -s -T /usr/share/generally/Lang Lang || exit 1
-    ln -s -T /usr/share/generally/Sounds/Default Sounds/Default || exit 1
-    ln -s -T /usr/share/generally/Sounds/Funny Sounds/Funny || exit 1
-    ln -s /usr/share/generally/GeneRally.exe GeneRally.exe || exit 1
-    ln -s /usr/share/generally/TrackEditor.exe TrackEditor.exe || exit 1
-    ln -s /usr/share/generally/font.bmp font.bmp || exit 1
-    ln -s /usr/share/generally/readme.txt readme.txt || exit 1
-    ln -s /usr/share/generally/trackeditor.cur trackeditor.cur || exit 1
-    ln -s /usr/share/generally/version.txt version.txt || exit 1
+    ln -s -T /usr/share/generally/lang lang
+    ln -s -T /usr/share/generally/sounds/Default sounds/Default
+    ln -s -T /usr/share/generally/sounds/Funny sounds/Funny
+    ln -s /usr/share/generally/GeneRally.exe GeneRally.exe
+    ln -s /usr/share/generally/TrackEditor.exe TrackEditor.exe
+    ln -s /usr/share/generally/font.bmp font.bmp
+    ln -s /usr/share/generally/readme.txt readme.txt
+    ln -s /usr/share/generally/trackeditor.cur trackeditor.cur
+    ln -s /usr/share/generally/version.txt version.txt
+    ln -s /usr/share/generally/SDL.dll SDL.dll
 
-    cp -ra /usr/share/generally/Drivers . || exit 1
-    cp -ra /usr/share/generally/Tracks . || exit 1
-    cp -ra /usr/share/generally/Cars . || exit 1
-    cp /usr/share/generally/gr.pal . || exit 1
-    cp /usr/share/generally/gr.ini . || exit 1
+    cp -ra /usr/share/generally/drivers .
+    cp -ra /usr/share/generally/tracks .
+    cp -ra /usr/share/generally/cars .
+    cp /usr/share/generally/gr.pal .
+    cp /usr/share/generally/gr.ini .
 
-    wine regedit /usr/share/generally/setaudio.reg || exit 1
+    wineboot -u
+    wine /usr/share/generally/vcredist_x86.exe -q
 fi
 
 cd "\$HOME"/.generally
@@ -85,37 +96,6 @@ echo Goodbye from GeneRally!
 exit 0
 EOF
   chmod 755 generally
-
-#############################################################################
-  cd "$pkgdir"/usr/bin || return 1
-  cat <<EOF >generally_track_ed
-#!/bin/bash
-export WINEPREFIX="\$HOME"/.generally/winefs
-export XDG_DATA_HOME=/dev/null
-export WINEDEBUG=-all
-
-if [ ! -d "\$HOME"/.generally/winefs ] ; then
-    echo Files not found, execute GeneRally once.
-    exit 1
-fi
-
-cd "\$HOME"/.generally
-wine ./TrackEditor.exe "\$@" &>/dev/null
-
-exit 0
-EOF
-  chmod 755 generally_track_ed
-
-#############################################################################
-  cd "$pkgdir"/usr/share/generally
-  cat <<EOF >setaudio.reg
-REGEDIT4
-
-[HKEY_CURRENT_USER\Software\Wine\DirectSound]
-"DefaultBitsPerSample"="16"
-"DefaultSampleRate"="22050"
-EOF
-  chmod 644 setaudio.reg
 
 #############################################################################
   cd "$pkgdir"/usr/share/applications
@@ -137,8 +117,5 @@ EOF
   return 0
 }
 
-
-md5sums=('c7cd53c3acf26c5560ddb92f5901f236'
-         'e7f687659a30c3e7d8ea7fb6c5909b7b'
-         '9f38044660bfffde2979654d6d639f3f')
+md5sums=('e7f687659a30c3e7d8ea7fb6c5909b7b')
 
