updated on Sun Nov 25 20:22:22 UTC 2012

diff --git a/aurvote/aurvote b/aurvote/aurvote
--- a/aurvote/aurvote
+++ b/aurvote/aurvote
@@ -20,19 +20,21 @@
 #
 
 NAME='aurvote'
-VERSION=1.3
+VERSION=1.5
 
 TMPDIR=${TMPDIR:-/tmp}
 AV_TMP="$TMPDIR/aurvote-$USER"
 
-CONFIGFILE=${XDG_HOME_CONFIG:-~/.config}/aurvote
+CONFIGFILE=${XDG_CONFIG_HOME:-~/.config}/aurvote
 
 AUR_URL="https://aur.archlinux.org"
+AUR_URL_LOGIN="$AUR_URL/login/"
 AUR_URL_PKG_INFO="$AUR_URL/rpc.php"
-AUR_URL_PKG_PAGE="$AUR_URL/packages.php?setlang=en&ID="
+AUR_URL_PKG_PAGE="$AUR_URL/packages/"
 AUR_DOMAIN="aur.archlinux.org"
 AUR_COOKIE="AURSID"
 AUR_COOKIE_VALUE=""
+AUR_SETLANG="?setlang=en"
 
 
 version() {
@@ -78,39 +80,23 @@ aur_login() {
     if [[ ! $user || ! $pass ]]; then
         error "$CONFIGFILE must have user name and password. Run:\n$NAME --configure"
     fi
-    curl $CURL_OPT -fs -c "$COOKIE_FILE" "${args[@]}" -d "user=$user" \
-         --data-urlencode "passwd=$pass" "$AUR_URL" \
-         -o "$AV_TMP/login" || error "Unable to access $AUR_URL"
-    err=$(sed -ne "s/.*span class='error'>\([^<]*\)<.*/\1/p" "$AV_TMP/login")
+    curl $CURL_OPT -L -fs -c "$COOKIE_FILE" "${args[@]}" -d "user=$user" \
+         --data-urlencode "passwd=$pass" "$AUR_URL_LOGIN" \
+         -o "$AV_TMP/login" || error "Unable to access $AUR_URL_LOGIN"
+    err=$(sed -ne 's/.*ul class="errorlist"><li>\([^<]*\)<.*/\1/p' "$AV_TMP/login")
     [[ $err ]] && error "$err"
 }
 
-aur_ids() {
-    local args=()
-    set -- "${pkgnames[@]}"
-    while [[ $1 ]]; do
-        args+=(--data-urlencode "arg[]=$1")
-        shift
-    done
-    curl $CURL_OPT -fs -G -d type=multiinfo "${args[@]}" \
-         "$AUR_URL_PKG_INFO" -o "$AV_TMP/info.$PID" ||
-             error "Unable to get IDs"
-    pkgnames=($(grep -o '"ID":"[0-9]\+","Name":"[^"]\+"' "$AV_TMP/info.$PID" |
-        sed 's/^"ID":"\([0-9]\+\)","Name":"\([^"]\+\)"$/\2\/\1/'))
-}
-
 aur_check_vote() {
-    local pkg pkgname pkgid
+    local pkg
     for pkg in "${pkgnames[@]}"; do
-        pkgname=${pkg%%/*}
-        pkgid=${pkg##*/}
         curl $CURL_OPT -fs -b "$COOKIE_FILE" \
-             "${AUR_URL_PKG_PAGE}${pkgid}" \
-             -o "$AV_TMP/$pkgname.$PID" ||
-                 error "Unable to get $pkgname page"
-        if grep -q "type='submit' class='button' name='do_UnVote'" "$AV_TMP/$pkgname.$PID"; then
+             "${AUR_URL_PKG_PAGE}${pkg}${AUR_SETLANG}" \
+             -o "$AV_TMP/$pkg.$PID" ||
+                 error "Unable to get $pkg page"
+        if sed '/<div id="news">/q' "$AV_TMP/$pkg.$PID" | grep -q /unvote/; then
             echo "already voted"
-        elif grep -q "type='submit' class='button' name='do_Vote'" "$AV_TMP/$pkgname.$PID"; then
+        elif sed '/<div id="news">/q' "$AV_TMP/$pkg.$PID" | grep -q /vote/; then
             echo "not voted"
         else
             echo "voted status not found"
@@ -120,24 +106,24 @@ aur_check_vote() {
 
 
 aur_vote() {
-    local vote pkg pkgname pkgid
-    (($1)) && vote="do_Vote" || vote="do_UnVote"
+    local pkg
+    (($1)) && vote="/vote/" || vote="/unvote/"
     for pkg in "${pkgnames[@]}"; do
-        pkgname=${pkg%%/*}
-        pkgid=${pkg##*/}
         curl $CURL_OPT -fs -b "$COOKIE_FILE" \
-             -d "token=$AUR_COOKIE_VALUE&IDs[${pkgid}]=1&ID=${pkgid}&${vote}=1" \
-             "${AUR_URL_PKG_PAGE}${pkgid}" -o /dev/null
+             "${AUR_URL_PKG_PAGE}${pkg}${vote}" -o /dev/null
         if (($?)); then
-            echo "Error: Can't (un)vote for $pkgname"
+            echo "Error: Can't (un)vote for $pkg"
         else
-            echo "$pkgname : vote changed"
+            echo "$pkg : vote changed"
         fi
     done
 }
 
 create_config_file() {
-    local ans
+    local ans configdir=${CONFIGFILE%/*}
+	if [[ ! -d $configdir ]]; then
+		mkdir -p "$configdir" || error "Unable to create $configdir"
+	fi
     if [[ -f "$CONFIGFILE" ]]; then
         read -p "$CONFIGFILE exists. Replace ? [y/N] " ans
         [[ $ans != 'Y' && $ans != 'y' ]] && return 0
@@ -165,7 +151,6 @@ umask 077
 [[ -d "$AV_TMP" && -w "$AV_TMP" ]] || error "Cannot access to $AV_TMP"
 PID=$$
 ACTION="vote"
-IDMODE=0
 pkgnames=()
 CURL_OPT=""
 PERSIST=0
@@ -182,8 +167,7 @@ while [[ $1 ]]; do
         --configure)  ACTION="configure";;
         --vote|-v)    ACTION="vote";;
         --unvote|-u)  ACTION="unvote";;
-        # IDMODE is designed to be used with yaourt: aur -c --id packagename/aurid
-        --id)         IDMODE=1;; 
+        --id)         ;; # deprecated
         --insecure)   CURL_OPT+=" --insecure";; 
         -k)           PERSIST=1; shift; COOKIE_FILE="$1";;
         --*|-*)       usage; exit 1;;
@@ -198,11 +182,10 @@ if [[ $ACTION = "configure" ]]; then
 fi
 
 COOKIE_FILE=${COOKIE_FILE:-"$AV_TMP/cookies"}
-
+pkgnames=("${pkgnames[@]%/*}") # compatibility with yaourt <= 1.2.1
 [[ ! $pkgnames ]] && usage && exit 1
  
 aur_login
-((! IDMODE)) && aur_ids
 
 case "$ACTION" in
     check)  aur_check_vote;;
diff --git a/freeipa/PKGBUILD b/freeipa/PKGBUILD
--- a/freeipa/PKGBUILD
+++ b/freeipa/PKGBUILD
@@ -1,68 +1,450 @@
-# Maintainer: François Steinmetz <francois.steinmetz@gmail.com>
+# Maintainer: Xiao-Long Chen <chenxiaolong@cxl.epac.to>
 
+# Quite possibly the uglyest PKGBUILD you'll ever see :P
+
+# NOTE: ntp, autofs, and ntp support is currently broken because the formats of
+# the /etc/conf.d/ configuration files in Arch Linux differ from the formats of
+# Fedora's /etc/sysconfig/ configuration files. Samba/Active Directory support
+# is probably broken too, since the AUR version installs to /opt/samba4.
+
+# Client only, for now
+build_server=false
+
+# SELinux support
+build_selinux=false
+
+# AUR workaround
 pkgname=freeipa
-pkgver=2.1.4
-pkgrel=5
-pkgdesc="FreeIPA (identity, policy, audit) is an integrated security information management solution."
-arch=('x86_64' 'i686')
-url="http://freeipa.org"
-license=('GPL3')
-depends=(
-  '389-ds-base'
-  'authconfig'
-  'python2-pyasn1'
-  'python-nss'
-  'python2'
-  'python2-krbv'
-  'python2-ldap'
-  'python2-netaddr'
-  'python2-kerberos'
-  'sssd'
-  'xmlrpc-c-svn'
-)
-makedepends=()
-backup=()
-source=("http://freeipa.org/downloads/src/$pkgname-$pkgver.tar.gz"
-        "missing-headers.patch"
-        "ipaserver-encodecontroltuples.patch"
-        "ipa-kpasswd.rcd"
-        "ipa-kpasswd.service")
-sha1sums=('0d0297d4861fb1eb681bf0972eea030e8503557f'
-          '33e020e509665e9c3a44b8ba66d18534fc42cc9a'
-          '862b4d6bf176261c5b34d2397ee834fcb01bed8b'
-          'adfcff9c82674ea8d0f819571fd6007b91ed8d56'
-          '965d92a7fca37303972d065cf7e5eedbba952331')
+
+pkgbase=freeipa
+: && pkgname=('freeipa-client' 'python2-freeipa')
+
+if [ "x${build_server}" == "xtrue" ]; then
+  pkgname+=('freeipa-server' 'freeipa-admintools')
+
+  if [ "x${build_selinux}" == "xtrue" ]; then
+    pkgname+=('freeipa-server-selinux')
+  fi
+fi
+
+pkgver=3.0.1
+pkgrel=2
+pkgdesc="The Identity, Policy, and Audit system"
+arch=('i686' 'x86_64')
+url="http://www.freeipa.org/"
+license=('GPL')
+
+# Client dependencies
+makedepends=('389-ds-base-updated'
+             #'libwbclient' # Samba4 version
+             'samba4'
+             'svrcore'
+             'systemd'
+             'talloc'
+             'tevent')
+
+# SELinux dependencies
+if [ "x${build_selinux}" == "xtrue" ]; then
+  makedepends+=('selinux-refpolicy-arch'
+                'selinux-usr-checkpolicy'
+                'selinux-usr-policycoreutils')
+fi
+
+# FreeIPA server dependencies
+if [ "x${build_server}" == "xtrue" ]; then
+  makedepends+=()
+fi
+
+# Other dependencies
+makedepends+=('curl'
+              'krb5'
+              'memcached'
+              'nspr'
+              'nss'
+              'openssl'
+              'openldap'
+              'popt'
+              'pylint'
+              'python2'
+              'python2-crypto'
+              'python2-distribute'
+              'python2-dnspython'
+              'python2-kerberos'
+              'python2-krbv'
+              'python2-ldap'
+              'python2-lxml'
+              'python2-netaddr'
+              'python2-nss'
+              'python2-polib'
+              'python2-pyasn1'
+              'python2-pyopenssl'
+              # Red Hat specific
+              #'python2-rhsm'
+              'sssd'
+              'xmlrpc-c')
+
+# Dependencies for "make check"
+checkdepends=('check')
+
+options=('!libtool')
+source=("http://www.freeipa.org/downloads/src/freeipa-${pkgver}.tar.gz"
+        'files.freeipa-server'
+        'files.freeipa-server-selinux'
+        'files.freeipa-admintools'
+        'files.freeipa-client'
+        'files.python2-freeipa'
+        '0001_Use_ArchLinux_Paths.patch'
+        '0002_Add_ArchLinux_Platform.patch'
+        '0003_Use_Python_2.patch'
+        '0004_NTP_Fixes.patch')
+sha512sums=('4a83b5e738ffc9d9c56622ca532f5672ec9abcd46180dea78bd4dcee2c3eac8a9aed07ea04674899462ae82fb11988aa28755dea1ec9955d480a5dbad03b95af'
+            '6a44b76f0767dc406b86af88817c7a05380df79e914998880daa1c6b3643698a46d1703d6fd4aee58b9e20cb6f05a96f18e7069e8eabb09d128cc786e91c8d24'
+            '5182d7a9d25f920c3591bf037dd7ad92bf912db55dc9ac5f1e3fc557c19658515a51270e396aa2614dd7f047b7351cfe281519dc3524f953b495cf9164f836a2'
+            'cf9b40b305a004342c40695b635a9eadead90c41197d24c3b96658dc5e992c1748ac3f0262e0c5353e7ddaa3fb2db96143fcd3a6ca7ab34cd737c0d52fad00d6'
+            'ae93857dc42f6afb3ec67623b14d3294ad3a21f2ad21e60e245f41ce9fc3ff927ea1820f0783f6f4a5c5bf87d05c3c590fbb441f8dd411bab88be0a29c759897'
+            '81bbcc2d567b6b154a1bb436c37ad0efb6e104aa9a651d24545eeb0f4889f15424aa805d2b7460faad2a8804fe2ec59fce64360cd9f61f0ac3f14fb5772c350b'
+            '8c83d37c8c1c6184f6eafd3f1ae09bf5fd999123e81cdd4b54f902d691b6d1a88ad9614521b411b2da00486978a7a01a2e0bd5156dd13b18afbd713416080a80'
+            'ba832413135fb1fad2c3fdcbef945e54c3004aa072eb2309ed5dafa5284644bd367b5814188dbb97bd3d995eedc955ee555464533038857e8862b472167586be'
+            'dd762c4355eac9afd36525ee203cd298cce476ef10f5e0bc75a6d4f994aab88cb5c7377dc58b07179f231ae02e03e1ba02295eb030bfd0dbb778899ef524a76f'
+            'ccc2c1f216ec85e85b9e17dffcc6fa88a31b3d3a319bdf9154705a7e619311ed3c9dc8e2b704d8a1366b79d92d660ad29a7c3554751f46b5a08c4e911a27fe8d')
 
 build() {
-  cd "$srcdir/$pkgname-$pkgver"
+  cd "${srcdir}/${pkgbase}-${pkgver}"
 
+  # Apply my patches
+  # 0001_Use_ArchLinux_Paths.patch
+  #   Change Fedora's paths to the equivalents in Arch Linux
+  patch -p1 -i "${srcdir}/0001_Use_ArchLinux_Paths.patch"
+  # 0002_Add_ArchLinux_Platform.patch
+  #   Add platform specific code for starting/stopping services, modifying
+  #   authentication (/etc/pam.d/) settings, SELinux settings, etc.
+  #   This patch contains code from Fedora and Ubuntu
+  patch -p1 -i "${srcdir}/0002_Add_ArchLinux_Platform.patch"
+  # 0003_Use_Python_2.patch
+  #   FreeIPA hasn't been ported to Python 3, so the code must be modified to
+  #   run /usr/bin/python2
+  patch -p1 -i "${srcdir}/0003_Use_Python_2.patch"
+  # 0004_NTP_Fixes.patch
+  #   Arch Linux's ntp does not accept the '-U' parameter and does not have a
+  #   /etc/sysconfig/ configuration files, so the relevant code must be removed
+  patch -p1 -i "${srcdir}/0004_NTP_Fixes.patch"
+
+  export SUPPORTED_PLATFORM=archlinux
   export PYTHON=python2
 
-  sed -i '1 s|\<python\>|python2|' \
-    makeapi \
-    install/tools/ipa* \
-    ipa-client/ipa-install/ipa-client-install
-  sed -i 's|\<python\>|python2|' \
-    Makefile \
-    ipapython/Makefile \
-    ipapython/py_default_encoding/Makefile
+  # Force regeneration of platform support
+  rm ipapython/services.py
 
-  patch -p1 < "$srcdir/ipaserver-encodecontroltuples.patch"
+  make version-update
 
-  patch -p2 < "$srcdir/missing-headers.patch"
+  pushd ipa-client
+  ../autogen.sh --prefix=/usr --sysconfdir=/etc
+  popd
 
-  make
+  if [ "x${build_server}" == "xtrue" ]; then
+    pushd daemons
+    ../autogen.sh --prefix=/usr --sysconfdir=/etc --with-openldap
+    popd
+
+    pushd install
+    ../autogen.sh --prefix=/usr --sysconfdir=/etc
+    popd
+
+    make IPA_VERSION_IS_GIT_SNAPSHOT=no ${MAKEFLAGS} all
+
+    if [ "x${build_selinux}" == "xtrue" ]; then
+      pushd selinux
+      make -j1 all
+      popd
+    fi
+  else
+    make IPA_VERSION_IS_GIT_SNAPSHOT=no ${MAKEFLAGS} client
+  fi
+
+  # Install to temporary directory #############################################
+
+  export SUPPORTED_PLATFORM=archlinux
+
+  # Force regeneration of platform support
+  rm ipapython/services.py
+
+  if [ "x${build_server}" == "xtrue" ]; then
+    make install DESTDIR="${srcdir}/install_temp"
+
+    if [ "x${build_selinux}" == "xtrue" ]; then
+      pushd selinux
+      make install DESTDIR="${srcdir}/install_temp"
+      popd
+    fi
+  else
+    make client-install DESTDIR="${srcdir}/install_temp"
+  fi
+
+  if [ "x${build_server}" == "xtrue" ]; then
+    # Some user-modifiable HTML files are provided. Move these to /etc and link
+    # back.
+    install -dm755 "${srcdir}/install_temp/etc/ipa/html/"
+    install -dm755 "${srcdir}/install_temp/var/cache/ipa/sysrestore/"
+    install -dm755 "${srcdir}/install_temp/var/cache/ipa/sysupgrade/"
+    install -dm755 "${srcdir}/install_temp/var/cache/ipa/pki-ca/publish/"
+    install -dm755 "${srcdir}/install_temp/usr/share/ipa/html/"
+    ln -s ../../../../etc/ipa/html/ffconfig.js \
+      "${srcdir}/install_temp/usr/share/ipa/html/ffconfig.js"
+    ln -s ../../../../etc/ipa/html/ffconfig_page.js \
+      "${srcdir}/install_temp/usr/share/ipa/html/ffconfig_page.js"
+    ln -s ../../../../etc/ipa/html/ssbrowser.html \
+      "${srcdir}/install_temp/usr/share/ipa/html/ssbrowser.html"
+    ln -s ../../../../etc/ipa/html/unauthorized.html \
+      "${srcdir}/install_temp/usr/share/ipa/html/unauthorized.html"
+    ln -s ../../../../etc/ipa/html/browserconfig.html \
+      "${srcdir}/install_temp/usr/share/ipa/html/browserconfig.html"
+    ln -s ../../../../etc/ipa/html/ipa_error.css \
+      "${srcdir}/install_temp/usr/share/ipa/html/ipa_error.css"
+
+    # So we can own our Apache configuration
+    install -dm755 "${srcdir}/install_temp/etc/httpd/conf/extra/"
+    touch "${srcdir}/install_temp/etc/httpd/conf/extra/ipa.conf"
+    touch "${srcdir}/install_temp/etc/httpd/conf/extra/ipa-pki-proxy.conf"
+    touch "${srcdir}/install_temp/etc/httpd/conf/extra/ipa-rewrite.conf"
+    install -dm755 "${srcdir}/install_temp/usr/share/ipa/html/"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/ca.crt"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/configure.jar"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/kerberosauth.xpi"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/krb.con"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/krb.js"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/krb5.ini"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/krbrealm.con"
+    touch "${srcdir}/install_temp/usr/share/ipa/html/preferences.html"
+
+    # systemd service
+    install -dm755 "${srcdir}/install_temp/usr/lib/systemd/system/"
+    install -m644 \
+      init/systemd/ipa.service \
+      init/systemd/ipa_memcached.service \
+      "${srcdir}/install_temp/usr/lib/systemd/system/"
+
+    # Configuration files
+    # Use /etc/conf.d ##########################################################
+    install -dm755 "${srcdir}/install_temp/etc/conf.d/"
+    install -m644 init/ipa_memcached.conf \
+      "${srcdir}/install_temp/etc/conf.d/"
+
+    # /run
+    install -dm755 "${srcdir}/install_temp/run/"
+    install -dm700 "${srcdir}/install_temp/run/ipa_memcached/"
+
+    # krb5 plugins
+    install -dm755 "${srcdir}/install_temp/usr/lib/krb5/plugins/libkrb5/"
+    touch "${srcdir}/install_temp/usr/lib/krb5/plugins/libkrb5/winbind_krb5_locator.so"
+
+    # systemd tmpfiles.d configuration
+    install -dm755 "${srcdir}/install_temp/etc/tmpfiles.d/"
+    install -m644 init/systemd/ipa.conf.tmpfiles \
+      "${srcdir}/install_temp/usr/lib/tmpfiles.d/ipa.conf"
+
+    # bash completion configuration files
+    install -dm755 "${srcdir}/install_temp/etc/bash_completion.d/"
+    install -m644 contrib/completion/ipa.bash_completion \
+      "${srcdir}/install_temp/etc/bash_completion.d/ipa"
+
+    # cron files
+    install -dm755 "${srcdir}/install_temp/etc/cron.d/"
+    install -m644 ipa-compliance.cron "${srcdir}/etc/cron.d/ipa-compliance"
+  fi
+
+  install -dm755 "${srcdir}/install_temp/var/lib/ipa-client/sysrestore/"
+
+  # /etc/ipa/ is needed for ipa-client-install
+  install -dm755 "${srcdir}/install_temp/etc/ipa/"
+
+  # Fix filenames
+  pushd "${srcdir}/install_temp/usr/lib/python2.7/site-packages/"
+  mv ipapython-${pkgver}*-py2.7.egg-info ipapython-${pkgver}-py2.7.egg-info
+  popd
 }
 
-package() {
-  cd "$srcdir/$pkgname-$pkgver"
+check() {
+  cd "${srcdir}/${pkgbase}-${pkgver}"
+  # No 'check' target yet
+#  make check
+}
 
-  make DESTDIR="$pkgdir/" install
+install_file() {
+  if [ -z "${1}" ]; then
+    error "No path specified!"
+    exit 1
+  fi
+  if [ ! -e "${srcdir}/install_temp/${1}" ]; then
+    error "${1} does not exist!"
+    exit 1
+  fi
+  if [ -d "${srcdir}/install_temp/${1}/" ]; then
+    if [ -d "${pkgdir}/${1}/" ]; then
+      error "Directory ${1} already exists!"
+      exit 1
+    fi
+  fi
+  if [ -f "${srcdir}/install_temp/${1}" ]; then
+    if [ -f "${pkgdir}/${1}" ]; then
+      error "File ${1} already exists!"
+      exit 1
+    fi
+  fi
+  if [ ! -d "${pkgdir}/$(dirname ${1})/" ]; then
+    install -dm755 "${pkgdir}/$(dirname ${1})/"
+  fi
 
-  rm -rf "$pkgdir/etc/rc.d/init.d"
-  cd "$srcdir"
-  install -Dm0644 ipa-kpasswd.service   "$pkgdir/lib/systemd/system/ipa-kpasswd.service"
-  install -Dm0755 ipa-kpasswd.rcd       "$pkgdir/etc/rc.d/ipa-kpasswd"
+  # Set permissions
+  if echo "${1}" | grep -q ':'; then
+    local FILE=${1#*:}
+    local PERM=${1%:*}
+    mv "${srcdir}/install_temp/${FILE}" "${pkgdir}/${FILE}"
+    chmod ${PERM} "${pkgdir}/${FILE}"
+  else
+    mv "${srcdir}/install_temp/${1}" "${pkgdir}/${1}"
+  fi
+}
+
+install_files() {
+  if [ ! -f "${srcdir}/files.${1}" ]; then
+    error "${srcdir}/files.${1} not found!"
+    exit 1
+  fi
+  while read FILE; do
+    if echo "${FILE}" | grep -q -e '#' -e '^[ \t]*$'; then
+      continue
+    fi
+    msg "Installing file: ${FILE}"
+    install_file ${FILE}
+  done < "${srcdir}/files.${1}"
+}
+
+if [ "x${build_server}" == "xtrue" ]; then
+
+package_freeipa-server() {
+  : && pkgdesc="The IPA authentication server"
+  depends=("freeipa-admintools=${pkgver}-${pkgrel}"
+           "freeipa-client=${pkgver}-${pkgrel}"
+           "python2-freeipa=${pkgver}-${pkgrel}"
+           '389-ds-base-updated'
+           'acl'
+           'apache'
+           'cyrus-sasl-gssapi'
+           'keyutils'
+           'krb5'
+           'memcached'
+           'mod_auth_kerb'
+           'mod_nss'
+           'mod_wsgi'
+           'nss'
+           'ntp'
+           'openldap'
+           'python2-dnspython'
+           'python2-krbv'
+           'python2-ldap'
+           'python2-memcached'
+           'python2-pyasn1'
+           'slapi-nis'
+           'systemd'
+           'tomcat7'
+           'zip')
+  optdepends=('python2-crypto: For Microsoft Active Directory trusts'
+              'samba4: For Microsoft Active Directory trusts'
+              'sssd: For Microsoft Active Directory trusts')
+  backup=('etc/ipa/html/browserconfig.html'
+          'etc/ipa/html/ffconfig.js'
+          'etc/ipa/html/ffconfig_page.js'
+          'etc/ipa/html/ipa_error.css'
+          'etc/ipa/html/ssbrowser.html'
+          'etc/ipa/html/unauthorized.html')
+  # Backup files created by this package
+  backup+=('etc/httpd/conf/extra/ipa-rewrite.conf'
+           'etc/httpd/conf/extra/ipa.conf'
+           'etc/httpd/conf/extra/ipa-pki-proxy.conf'
+           'usr/share/ipa/html/ca.crt')
+  install=install.freeipa-server
+
+  # SELinux dependencies
+  if [ "x${build_selinux}" == "xtrue" ]; then
+    depends+=("freeipa-server-selinux=${pkgver}-${pkgrel}"
+              'selinux-refpolicy-arch'
+              'selinux-usr-policycoreutils')
+  fi
+
+  # Conflicts with mod_ssl, but that is a part of the apache package
+  #conflicts=('mod_ssl')
+
+  install_files freeipa-server
+}
+
+if [ "x${build_selinux}" == "xtrue" ]; then
+
+package_freeipa-server-selinux() {
+  : && pkgdesc="SELinux rules for freeipa-server daemons"
+  depends=("freeipa-server=${pkgver}-${pkgrel}"
+           'selinux-usr-policycoreutils')
+  install=install.freeipa-server-selinux
+
+  install_files freeipa-server-selinux
+}
+
+
+fi
+
+package_freeipa-admintools() {
+  : && pkgdesc="IPA administrative tools"
+  depends=("freeipa-client=${pkgver}-${pkgrel}"
+           "python2-freeipa=${pkgver}-${pkgrel}"
+           'python2-krbv'
+           'python2-ldap')
+
+  install_files freeipa-admintools
+}
+
+fi
+
+package_freeipa-client() {
+  : && pkgdesc="IPA authentication for use on clients"
+  depends=("python2-freeipa=${pkgver}-${pkgrel}"
+           'autofs'
+           'bind'
+           'certmonger'
+           'curl'
+           'cyrus-sasl-gssapi'
+           'krb5'
+           'nfs-utils'
+           'nfsidmap'
+           'nss'
+           'ntp'
+           'oddjob'
+           'pam-krb5'
+           'python2-dnspython'
+           'python2-krbv'
+           'python2-ldap'
+           'sssd'
+           'wget'
+           'xmlrpc-c')
+
+  # authconfig is Fedora specific
+  #depends+=('authconfig')
+
+  install_files freeipa-client
+}
+
+package_python2-freeipa() {
+  : && pkgdesc="Python 2 libraries used by IPA"
+  depends=('gnupg'
+           'python2-kerberos'
+           'python2-lxml'
+           'python2-netaddr'
+           'python2-nss'
+           'python2-pyopenssl'
+           'sssd')
+  # Backup files created by this package
+  backup=('etc/ipa/default.conf'
+          'etc/ipa/ca.crt')
+
+  install_files python2-freeipa
 }
 
 # vim:set ts=2 sw=2 et:
diff --git a/kfilebox/kfilebox.install b/kfilebox/kfilebox.install
--- a/kfilebox/kfilebox.install
+++ b/kfilebox/kfilebox.install
@@ -1,5 +1,8 @@
 post_install() {
-	kbuildsycoca4
+	kbuildsycoca4 > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+	   echo "kbuildsycoca4 failed!"
+	fi
 }
 
 post_upgrade() {
diff --git a/linux-eee-ck/PKGBUILD b/linux-eee-ck/PKGBUILD
--- a/linux-eee-ck/PKGBUILD
+++ b/linux-eee-ck/PKGBUILD
@@ -3,113 +3,134 @@
 # Based on kernel-eee PKGBUILD by Dan McGee <dan@archlinux.org>
 
 # AUR workaround
-pkgname="linux-eee-ck"
+pkgname=linux-eee-ck
 
-true && pkgname=("linux-eee-ck" "linux-eee-ck-headers")
-_kernver=3.6
+true && pkgname=(linux-eee-ck linux-eee-ck-headers)
 _ckver=ck1
-pkgver=${_kernver}.3
-pkgrel=1
-bfsver=0.425
-pkgdesc="The Linux Kernel and modules for the Asus Eee PC 701, with Brain Fuck Scheduler v$bfsver and all the goodies in the $_ckver patchset."
+_srcname=linux-3.6
+pkgver=3.6.7
+pkgrel=2
+_bfsver=0.425
 arch=('i686')
 license=('GPL2')
+options=('!strip')
 url="http://www.kernel.org"
-depends=('coreutils' 'module-init-tools')
-optdepends=('crda: for wireless regulatory domain support'
-            'iw: for wireless configuration support')
-replaces=('linux-uvc-eee-svn' 'madwifi-eee-svn')
-install=linux-eee-ck.install
-source=(http://www.kernel.org/pub/linux/kernel/v3.x/linux-$_kernver.tar.xz
-	http://www.kernel.org/pub/linux/kernel/v3.x/patch-$pkgver.xz
-        http://ck.kolivas.org/patches/3.0/$_kernver/$_kernver-$_ckver/patch-$_kernver-$_ckver.bz2
-        change-default-console-loglevel.patch
-	module-init-wait-3.6.patch
-	module-symbol-waiting-3.6.patch
-        61-eee-ssd.rules
-        kernelconfig)
+source=("http://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
+"http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
+"http://ck.kolivas.org/patches/3.0/3.6/3.6-${_ckver}/patch-3.6-${_ckver}.bz2"
+        'change-default-console-loglevel.patch'
+	'module-init-wait-3.6.patch'
+	'module-symbol-waiting-3.6.patch'
+	'irq_cfg_pointer-3.6.6.patch'
+        '61-eee-ssd.rules'
+        'kernelconfig')
 
 md5sums=('1a1760420eac802c541a20ab51a093d1'
-	 '96701113d37ef4f9b785206ab8bcc71e'
+	 '134936c362d8812b5cafcf3c67afdce0'
 	 '43068822b9292432617b81d10ca757d3'
          '9d3c56a4b999c8bfbd4018089a62f662'
 	 '3b8568f67c0a9a9d809273710f86001d'
 	 'd9ecff2d89c19218cdffca1838851608'
-         '73a20e8bf2bb29ba342f43460c6291cb'
-	 '2c74689dc09cc5fffdfd4d23237153e1')
+         '426c26705da667fea6dae34e8ef94185'
+         '6100b3e13c4c24ce3c887a1ae36ab7f1'
+	 'c3f906d97890ea387ec48e11b2f716dc')
 
 build() {
   # get into the linux source directory and start some magic
-  cd $srcdir/linux-$_kernver
+  cd $srcdir/$_srcname
 
   # add upstream patch
   patch -p1 -i "$srcdir/patch-$pkgver"
-
-  # apply ck patch
-  echo "=> Applying $_ckver patchset..."
-  patch -Np1 -i ../patch-$_kernver-$_ckver
-
   # set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
   # remove this when a Kconfig knob is made available by upstream
   # (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
-  echo "=> Applying default console loglevel patch..." 
   patch -Np1 -i ../change-default-console-loglevel.patch
 
+  # fix module initialisation
   patch -Np1 -i ../module-init-wait-3.6.patch
   patch -Np1 -i ../module-symbol-waiting-3.6.patch
+  
+  # fix FS#32615 - Check for valid irq_cfg pointer in smp_irq_move_cleanup_interrupt
+  patch -Np1 -i ../irq_cfg_pointer-3.6.6.patch
+
+  # apply ck patch
+  echo "=> Applying $_ckver patchset..."
+  patch -Np1 -i ../patch-3.6-$_ckver
+
+  ### Clean tree and copy ARCH config over
+  msg "Running make mrproper to clean source tree"
+  make mrproper
+  cp ../kernelconfig ./.config
+
+  # set extraversion to pkgrel
+  sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
 
   # don't run depmod on 'make install'. We'll do this ourselves in packaging
   sed -i '2iexit 0' scripts/depmod.sh
 
-  # load configuration
-  cp ../kernelconfig ./.config
-  make silentoldconfig
+  msg "Running make prepare for you to enable patched options of your choosing"
+  make prepare
 
   # to modify kernel settings, uncomment the following line
   # make menuconfig
 
   # build!
-  make ${MAKEFLAGS} bzImage modules || return 1
+  make ${MAKEFLAGS} LOCALVERSION= bzImage modules || return 1
 }
 
 package_linux-eee-ck() {
+  _Kpkgdesc='The Linux Kernel and modules for the Asus Eee PC 701, with Brain Fuck Scheduler v${_bfsver} and all the goodies in the ${_ckver} patchset.'
+  pkgdesc="${_Kpkgdesc}"
+  
+  provides=("linux-eee-ck=${pkgver}")
+  depends=('coreutils' 'module-init-tools')
+  optdepends=('crda: for wireless regulatory domain support'
+            'iw: for wireless configuration support')
+  replaces=('linux-uvc-eee-svn' 'madwifi-eee-svn')
+  install='linux-eee-ck.install'
+
+  KARCH=x86
+
   # install our modules
-  cd $srcdir/linux-$_kernver
+  cd $srcdir/$_srcname
+
+  # get kernel version
+  _kernver="$(make LOCALVERSION= kernelrelease)"
+
   mkdir -p $pkgdir/{lib/modules,boot}
-  make INSTALL_MOD_PATH=$pkgdir modules_install || return 1
+  make LOCALVERSION= INSTALL_MOD_PATH=$pkgdir modules_install || return 1
 
   # remove the junk symlinks
-  cd $srcdir/linux-$_kernver
-  rm $pkgdir/lib/modules/$pkgver-${_ckver}eee/{build,source}
+  cd $srcdir/$_srcname
+  rm $pkgdir/lib/modules/$_kernver/{build,source}
+
   # install the kernel
   cp arch/x86/boot/bzImage $pkgdir/boot/vmlinuz-eee-ck
-  # install a helper file for all install scripts
-  mkdir -p $pkgdir/usr/share/linux-eee-ck/
-  echo "KERNEL_VERSION='${pkgver}-${_ckver}eee'" > $pkgdir/usr/share/linux-eee-ck/currver
 
-  # udev rules for SSD drives :: not required/helpful for 700
+  # udev rules for SSD drives/SD Cards, they is not rotational
   mkdir -p $pkgdir/lib/udev/rules.d/
   install -m644 $srcdir/61-eee-ssd.rules $pkgdir/lib/udev/rules.d/
 
   # gzip -9 all modules
-  find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
+  find "$pkgdir" -name '*.ko' -exec gzip -9 {} \;
   # Now we call depmod...
-  depmod -b "$pkgdir" -F System.map "${pkgver}-${_ckver}eee"
+  depmod -b "$pkgdir" -F System.map "$_kernver"
 
   # move module tree /lib -> /usr/lib
   mv "$pkgdir/lib" "$pkgdir/usr"
 }
 
 package_linux-eee-ck-headers() {
-  KARCH=x86
+  _Hpkgdesc='Header files and scripts to build modules for linux-ck.'
+  pkgdesc="${_Hpkgdesc}"
+  depends=('linux-eee-ck') # added to keep kernel and headers packages matched
+  replaces=('kernel26-ck-headers')
 
-  # AUR workaround
-  true && pkgdesc='Header files and scripts for building modules for linux-eee-ck'
+  mkdir -p ${pkgdir}/lib/modules/${_kernver}
+  cd ${pkgdir}/lib/modules/${_kernver}
+  ln -sf ../../../usr/src/${_kernver} build
 
-  mkdir -p ${pkgdir}/lib/modules/${pkgver}-${_ckver}eee
-  cd ${pkgdir}/lib/modules/${pkgver}-${_ckver}eee
-  ln -sf ../../../usr/src/linux-${_kernver} build
-  cd ${srcdir}/linux-$_kernver
+  cd ${srcdir}/$_srcname
   install -D -m644 Makefile \
     ${pkgdir}/usr/src/linux-${_kernver}/Makefile
   install -D -m644 kernel/Makefile \
@@ -161,17 +182,20 @@ package_linux-eee-ck-headers() {
   # add wireless headers
   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/net/mac80211/
   cp net/mac80211/*.h ${pkgdir}/usr/src/linux-${_kernver}/net/mac80211/
+
   # add dvb headers for external modules
   # in reference to:
   # http://bugs.archlinux.org/task/9912
   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-core
   cp drivers/media/dvb/dvb-core/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-core/
+
   # add dvb headers for http://mcentral.de/hg/~mrec/em28xx-new
   # in reference to:
   # http://bugs.archlinux.org/task/13146
   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
   cp drivers/media/dvb/frontends/lgdt330x.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
   cp drivers/media/video/msp3400-driver.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
+
   # add dvb headers  
   # in reference to:
   # http://bugs.archlinux.org/task/20402
@@ -181,6 +205,7 @@ package_linux-eee-ck-headers() {
   cp drivers/media/dvb/frontends/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/common/tuners
   cp drivers/media/common/tuners/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/common/tuners/
+
   # add xfs and shmem for aufs building
   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/fs/xfs
   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/mm
@@ -193,6 +218,7 @@ package_linux-eee-ck-headers() {
 
   chown -R root.root ${pkgdir}/usr/src/linux-${_kernver}
   find ${pkgdir}/usr/src/linux-${_kernver} -type d -exec chmod 755 {} \;
+
   # strip scripts directory
   find ${pkgdir}/usr/src/linux-${_kernver}/scripts  -type f -perm -u+w 2>/dev/null | while read binary ; do
   case "$(file -bi "$binary")" in
@@ -207,3 +233,6 @@ package_linux-eee-ck-headers() {
   # remove unneeded architectures
   rm -rf ${pkgdir}/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
 }
+
+# Global pkgdesc and depends are here so that they will be picked up by AUR
+pkgdesc='Linux Kernel and modules with the ck1 patchset featuring the Brain Fuck Scheduler v0.425.'
diff --git a/munge/munge.install b/munge/munge.install
--- a/munge/munge.install
+++ b/munge/munge.install
@@ -16,14 +16,18 @@ post_install() {
     /bin/dd if=/dev/urandom bs=1 count=1024 >/etc/munge/munge.key 2>/dev/null
     /bin/chmod 0400 /etc/munge/munge.key
   else
-    echo "Warning: did not create /etc/munge/munge.key since /dev/urandom is not found"
+    if [ -c /dev/urandom ]; then
+        echo "info: no munge key is generated since /etc/munge/munge.key already exists"
+    else
+        echo "Warning: did not create /etc/munge/munge.key since /dev/urandom is not found"
+    fi
   fi
 
 # set permissions
   /bin/chown munge.munge -R /etc/munge
   /bin/chown munge.munge -R /var/log/munge
   /bin/chown munge.munge -R /var/lib/munge
-  /bin/chown munge.munge -R /var/run/munge
+  /bin/chown munge.munge -R /run/munge
 }
 
 post_upgrade() {
@@ -31,9 +35,23 @@ post_upgrade() {
   /bin/chown munge.munge -R /etc/munge
   /bin/chown munge.munge -R /var/log/munge
   /bin/chown munge.munge -R /var/lib/munge
-  /bin/chown munge.munge -R /var/run/munge
+  /bin/chown munge.munge -R /run/munge
   if [ -e /etc/munge/munge.key ]; then
     /bin/chmod 0400 /etc/munge/munge.key
+  fi
+}
+
+pre_remove() {
+  which systemctl >& /dev/null
+  if [ $? -eq 0 ]; then
+     echo "Stopping munge using SystemD"
+     systemctl stop munge
+
+     echo "Disabling SystemD related file(s)"
+     systemctl disable munged.service
+  else
+     echo "Stopping munge"
+     /etc/rc.d/munge stop
   fi
 }
 
@@ -41,6 +59,10 @@ post_upgrade() {
 post_remove() {
   echo "Removing munge system user/group "
   userdel munge
+
+  # remove link created by systemctl
+  # not the cleanest way - todo: find a better way to do this!
+#  rm -f /etc/systemd/system/multi-user.target.wants/munged.service
 }
 
 # vim:set ts=2 sw=2 et:
diff --git a/psmouse-alps-driver/psmouse.install b/psmouse-alps-driver/psmouse.install
--- a/psmouse-alps-driver/psmouse.install
+++ b/psmouse-alps-driver/psmouse.install
@@ -1,34 +1,44 @@
-generic() {
-    echo " > Running depmod now..."
-    depmod -a
-}
+DKMS=`which dkms`
+DEPMOD=`which depmod`
+MODPROBE=`which modprobe`
+RMMOD=`which rmmod`
+MNAME="psmouse"
+MVER="alps-dst-1.1"
 
-unload() {
-    lsmod | grep psmouse > /dev/null
-    if [ "$?" = "0" ]; then
-        rmmod psmouse
+post_install() {
+    echo "Running dkms for install..."
+    ${DKMS} add -m ${MNAME} -v ${MVER} &&\
+    ${DKMS} build -m ${MNAME} -v ${MVER} &&\
+    ${DKMS} install -m ${MNAME} -v ${MVER}
+
+    if [ "$?" == "0" ]; then
+        ${RMMOD} ${MNAME}
+        ${MODPROBE} ${MNAME}
+        ${DEPMOD} -a
+    else
+        echo "An error was ocurred, please report the bug!."
+        return 2
     fi
 }
 
-post_install() {
-    generic
-    echo " > Reloading psmouse module... Do not panic if your mouse pointer does"
-    echo "   not move for a moment!"
-    echo "   Please note that you may REBOOT your system to get it works!"
-    unload
-    sleep 0.5
-    modprobe psmouse
+pre_remove() {
+    #Sadly stolen(and modified) from dkms-alx package
+
+    echo "Running dkms for remove/upgrade..."
+    line=`$DKMS status -m ${MNAME}`
+    if echo "$line" | grep -E 'added|built|installed'; then
+            version=`echo "$line" | sed "s/${MNAME},\([^,]*\)[,:].*/\1/;t;d"`
+            ${DKMS} remove -m ${MNAME} -v ${MVER} --all
+    fi
+
+    ${RMMOD} ${MNAME}
+    ${DEPMOD} -a
+}
+
+pre_upgrade() {
+    pre_remove
 }
 
 post_upgrade() {
-  post_install
+    post_install
 }
-
-post_remove() {
-    generic
-    echo " > Unloading memory resident module..."
-    unload
-    echo "  Module unloaded!."
-
-}
-
diff --git a/systemd-git/systemd.install b/systemd-git/systemd.install
--- a/systemd-git/systemd.install
+++ b/systemd-git/systemd.install
@@ -4,13 +4,29 @@ sd_booted() {
   [ -e sys/fs/cgroup/systemd ]
 }
 
-machine_id_setup() {
-  if [ ! -f etc/machine-id ]; then
-    systemd-machine-id-setup
+add_privs() {
+  if ! setcap "$2" "$1" 2>/dev/null; then
+    echo "==> Warning: setcap failed, falling back to setuid root on /$1"
+    chmod u+s "$1"
+  fi
+}
+
+post_common() {
+  systemd-machine-id-setup
+
+  add_privs usr/bin/systemd-detect-virt 'cap_dac_override,cap_sys_ptrace+ep'
+
+  udevadm hwdb --update
+  journalctl --update-catalog
+
+  if sd_booted; then
+    systemctl --system daemon-reexec
   fi
 }
 
 post_install() {
+  post_common
+
   # enable getty@tty1 by default, but don't track the file
   systemctl enable getty@.service
 
@@ -19,12 +35,7 @@ post_install() {
 }
 
 post_upgrade() {
-  machine_id_setup
-
-  if sd_booted; then
-    systemctl daemon-reload
-    systemctl daemon-reexec
-  fi
+  post_common
 }
 
 # vim:set ts=2 sw=2 et:
diff --git a/xe-guest-utilities/xe-guest-utilities-archlinux.patch b/xe-guest-utilities/xe-guest-utilities-archlinux.patch
--- a/xe-guest-utilities/xe-guest-utilities-archlinux.patch
+++ b/xe-guest-utilities/xe-guest-utilities-archlinux.patch
@@ -1,6 +1,6 @@
-diff -uNr src.orig//etc/init.d/xe-linux-distribution src/etc/init.d/xe-linux-distribution
---- src.orig//etc/init.d/xe-linux-distribution	2010-05-20 13:19:02.000000000 +0200
-+++ src/etc/init.d/xe-linux-distribution	2010-10-04 14:45:11.000000000 +0200
+diff -uNr src.orig/etc/init.d/xe-linux-distribution src/etc/init.d/xe-linux-distribution
+--- src.orig/etc/init.d/xe-linux-distribution	2012-09-25 12:45:14.000000000 +0200
++++ src/etc/init.d/xe-linux-distribution	2012-11-21 14:03:04.000000000 +0100
 @@ -18,24 +18,8 @@
  LANG="C"
  export LANG
@@ -100,21 +100,138 @@ diff -uNr src.orig//etc/init.d/xe-linux-distribution src/etc/init.d/xe-linux-dis
 +    fi
  }
  
- # fail silently if not running xen
-@@ -91,7 +99,7 @@
-   stop)
- 	stop
+ status()
+@@ -99,7 +107,7 @@
+   status)
+ 	status
  	;;
 -  force-reload|restart)
 +  restart)
  	stop
  	start
  	;;
-diff -uNr src.orig//usr/sbin/xe-linux-distribution src/usr/sbin/xe-linux-distribution
---- src.orig//usr/sbin/xe-linux-distribution	2010-05-20 13:19:02.000000000 +0200
-+++ src/usr/sbin/xe-linux-distribution	2010-10-04 14:44:37.000000000 +0200
-@@ -51,6 +51,22 @@
-     return 0
+diff -uNr src.orig/etc/init.d/xe-linux-distribution.orig src/etc/init.d/xe-linux-distribution.orig
+--- src.orig/etc/init.d/xe-linux-distribution.orig	1970-01-01 01:00:00.000000000 +0100
++++ src/etc/init.d/xe-linux-distribution.orig	2012-09-25 12:45:14.000000000 +0200
+@@ -0,0 +1,113 @@
++#!/bin/bash
++#
++# xe-linux-distribution	Write Linux distribution information to XenStore.
++#
++# chkconfig: 2345 14 86
++# description: Writes Linux distribution version information to XenStore.
++#
++### BEGIN INIT INFO
++# Provides:          XenServer Virtual Machine Tools
++# Required-Start:    $local_fs
++# Required-Stop:     $local_fs
++# Default-Start:     2 3 4 5
++# Default-Stop:      0 1 6
++# Short-Description: XenServer Virtual Machine daemon providing host integration services
++# Description:       Writes Linux distribution version information to XenStore.
++### END INIT INFO
++
++LANG="C"
++export LANG
++
++if [ -f /etc/init.d/functions ] ; then
++. /etc/init.d/functions
++else
++action()
++{
++    descr=$1 ; shift
++    cmd=$@
++    echo -n "$descr "
++    $cmd
++    ret=$?
++    if [ $ret -eq 0 ] ; then
++	echo "OK"
++    else
++	echo "Failed"
++    fi
++    return $ret
++}
++fi
++
++XE_LINUX_DISTRIBUTION=/usr/sbin/xe-linux-distribution
++XE_LINUX_DISTRIBUTION_CACHE=/var/cache/xe-linux-distribution
++XE_DAEMON=/usr/sbin/xe-daemon
++XE_DAEMON_PIDFILE=/var/run/xe-daemon.pid
++
++if [ ! -x "${XE_LINUX_DISTRIBUTION}" ] ; then
++    exit 0
++fi
++
++start()
++{
++    if [ ! -e /proc/xen/xenbus ] ; then
++	if [ ! -d /proc/xen ] ; then
++	    action $"Mounting xenfs on /proc/xen:" /bin/false
++	    echo "Could not find /proc/xen directory."
++	    echo "You need a post 2.6.29-rc1 kernel with CONFIG_XEN_COMPAT_XENFS=y and CONFIG_XENFS=y|m"
++	    exit 1
++	else 
++	    # This is needed post 2.6.29-rc1 when /proc/xen support was pushed upstream as a xen filesystem
++	    action $"Mounting xenfs on /proc/xen:" mount -t xenfs none /proc/xen
++	fi
++    fi
++
++    if [ -e /proc/xen/capabilities ] && grep -q control_d /proc/xen/capabilities ; then
++	# Do not want daemon in domain 0
++	exit 0
++    fi
++
++    action $"Detecting Linux distribution version:" \
++	${XE_LINUX_DISTRIBUTION} ${XE_LINUX_DISTRIBUTION_CACHE}
++
++    action $"Starting xe daemon: " /bin/true
++    mkdir -p $(dirname ${XE_DAEMON_PIDFILE})
++    # This is equivalent to daemon() in C
++    ( exec &>/dev/null ; ${XE_DAEMON} -p ${XE_DAEMON_PIDFILE} & )
++}
++
++stop()
++{
++    action $"Stopping xe daemon: "   kill -TERM $(cat ${XE_DAEMON_PIDFILE})
++}
++
++status()
++{
++    cat ${XE_LINUX_DISTRIBUTION_CACHE}
++}
++
++# fail silently if not running xen
++if [ ! -d /proc/xen ]; then
++   exit
++fi
++
++case "$1" in
++  start)
++        start
++        ;;
++  stop)
++	stop
++	;;
++  status)
++	status
++	;;
++  force-reload|restart)
++	stop
++	start
++	;;
++  *)
++        # do not advertise unreasonable commands that there is no reason
++        # to use with this device
++        echo $"Usage: $0 start|restart|status"
++        exit 1
++esac
++
++exit $?
+diff -uNr src.orig/usr/sbin/xe-linux-distribution src/usr/sbin/xe-linux-distribution
+--- src.orig/usr/sbin/xe-linux-distribution	2012-09-25 12:45:14.000000000 +0200
++++ src/usr/sbin/xe-linux-distribution	2012-11-21 14:02:31.000000000 +0100
+@@ -254,6 +254,21 @@
+     write_to_output "${distro}" "${major}" "${minor}" "${description}"
  }
  
 +identify_archlinux()
@@ -122,21 +239,20 @@ diff -uNr src.orig//usr/sbin/xe-linux-distribution src/usr/sbin/xe-linux-distrib
 +    local archlinux_version="$1"
 +    local major
 +    local minor
-+    
++
 +    if [ ! -f "${archlinux_version}" ] ; then
-+	return 1
++        return 1
 +    fi
 +
 +    eval $(LC_ALL=C pacman -Qi initscripts |grep Version |sed "s/^.*: //" | \
-+	    awk -F. '{print "major="$1 ; print "minor="$2 ; exit 0 }' )
++        awk -F. '{print "major="$1 ; print "minor="$2 ; exit 0 }' )
 +    write_to_output "archlinux" "${major}" "${minor}" "Arch Linux ${major}.${minor}"
-+    
 +}
 +
- identify_debian()
- {
-     local debian_version="$1"
-@@ -258,6 +274,7 @@
+ if [ $# -eq 1 ] ; then
+     exec 1>"$1"
+ fi
+@@ -265,6 +280,7 @@
      identify_sles   /etc/SuSE-release   && exit 0
      identify_lsb    lsb_release         && exit 0
      identify_debian /etc/debian_version && exit 0
