updated on Wed Jan  8 00:39:02 UTC 2014

diff --git a/realvnc/install.diff b/realvnc/install.diff
--- a/realvnc/install.diff
+++ b/realvnc/install.diff
@@ -1,18 +1,21 @@
---- vncinstall	2013-03-04 13:51:13.000000000 +0100
-+++ vncinstall.arch	2013-06-07 16:39:38.575319421 +0200
-@@ -8,71 +8,13 @@
- # vncserver configuration files and a default xstartup.
+--- vncinstall	2013-12-06 15:36:06.000000000 +0100
++++ vncinstall.arch	2014-01-07 23:41:08.790064006 +0100
+@@ -9,49 +9,11 @@
  #
  
--# Set up defaults and platform-specific overrides
+ # Set up defaults and platform-specific overrides
 -dst=/usr/local/bin
 -lib=/usr/local/lib
+-mandst=/usr/local/man
+-cupsdst=/usr/lib/cups
+-share=/usr/share
 -
 -SYSNAME=`uname -s`
 -case "$SYSNAME" in
 -    Linux)
 -        dst=/usr/bin
 -        lib=/usr/lib
+-        mandst=/usr/share/man
 -        ;;
 -    SunOS)
 -        ;;
@@ -20,13 +23,18 @@
 -        ;;
 -    AIX)
 -        ;;
+-    FreeBSD)
+-        cupsdst=/usr/local/libexec/cups
+-        lib=/usr/local/libexec
+-        share=/usr/local/share
+-        ;;
 -    *)
 -        echo "Unknown platform"
 -        exit 1
 -        ;;
 -esac
 -
--if [ $# -gt 4 ]; then 
+-if [ $# -gt 4 ]; then
 -    echo "usage: $0 [<installation-directory> [<man-page-directory> [<cups-directory] ] ]"
 -    exit 1
 -fi
@@ -35,84 +43,45 @@
 -if [ $# -gt 0 ]; then
 -    dst=$1
 -    shift
+-    if [ "`basename $dst`" = bin ] && [ "$mandst" '!=' /usr/share/man ]; then
+-        $mandst=`dirname "$dst"`/man
+-    fi
 -fi
-+pkgdir="$1"
++dst=$1/usr/bin
++lib=$1/usr/lib
++mandst=$1/usr/share/man
++cupsdst=$1/usr/lib/cups
++share=$1/usr/share
  
--# Check installation directory exists
--if [ ! -d $dst ]; then
--  echo "Installation directory $dst does not exist."
--  exit 1
--fi
--
+ # Check installation directory exists
+ if [ '!' -d "$dst" ]; then
+@@ -59,24 +21,6 @@
+     exit 1
+ fi
+ 
 -# Man page directories
 -if [ $# -gt 0 ]; then
--    mandst="$1/man1"
+-    mandst="$1"
 -    shift
--else
--    if [ "`basename $dst`" = bin ]; then
--        mandst="`dirname $dst`/man/man1"
--        if [ ! -d "$mandst" -a "$dst" = /usr/bin ]; then
--            mandst=/usr/share/man/man1
--        fi
--    fi
 -fi
--if [ "$mandst" != "" ]; then
--    if [ ! -d "$mandst" -o ! -w "$mandst" ]; then
--        echo "Can't install manual pages to $mandst"
--        mandst=""
--    fi
+-if [ '!' -d "$mandst" ] || [ '!' -w "$mandst" ]; then
+-    echo "Can't install manual pages to $mandst"
+-    mandst=""
+-else
+-    mandst="$mandst"/man1
 -fi
 -
 -# CUPS directory
 -if [ $# -gt 0 ]; then
--    cupsdst=$1
+-    cupsdst="$1"
 -    shift
--else
--    cupsdst=/usr/lib/cups
 -fi
-+# Set up defaults and platform-specific overrides
-+dst=$pkgdir/usr/bin
-+lib=$pkgdir/usr/lib
-+mandst=$pkgdir/usr/share/man/man1
-+cupsdst=$pkgdir/usr/lib/cups
- 
+-
  # Copy files
  for f in vncviewer vncaddrbook vncserver-x11 vncserver-x11-core Xvnc Xvnc-core \
-@@ -139,21 +81,21 @@
- done
+          vncserverui vncserver-virtual vncserver-virtuald \
+@@ -170,4 +114,3 @@
+ chown root "$cups_vnc"
+ chmod 0700 "$cups_vnc"
  
- # Create fonts directory if it doesn't exist
--if [ ! -d /usr/share/vnc ]; then
--  mkdir -p /usr/share/vnc
--  chmod 0755 /usr/share/vnc
-+if [ ! -d $pkgdir/usr/share/vnc ]; then
-+  mkdir -p $pkgdir/usr/share/vnc
-+  chmod 0755 $pkgdir/usr/share/vnc
- fi
- 
--if [ ! -d /usr/share/vnc/fonts ]; then
--  mkdir -p /usr/share/vnc/fonts
--  chmod 0755 /usr/share/vnc/fonts
-+if [ ! -d $pkgdir/usr/share/vnc/fonts ]; then
-+  mkdir -p $pkgdir/usr/share/vnc/fonts
-+  chmod 0755 $pkgdir/usr/share/vnc/fonts
- fi
- 
--cp -f fonts/* /usr/share/vnc/fonts
--chmod 0444 /usr/share/vnc/fonts/*
-+cp -f fonts/* $pkgdir/usr/share/vnc/fonts
-+chmod 0444 $pkgdir/usr/share/vnc/fonts/*
- 
--cp -f rgb.txt /usr/share/vnc
--chmod 0444 /usr/share/vnc/rgb.txt
-+cp -f rgb.txt $pkgdir/usr/share/vnc
-+chmod 0444 $pkgdir/usr/share/vnc/rgb.txt
- 
- setuid="Xvnc vncserver-x11"
- for i in $setuid; do
-@@ -167,4 +109,4 @@
- chown root $cups_vnc
- chmod 0700 $cups_vnc
- 
--$dst/vncinitconfig --install-defaults
-+#$dst/vncinitconfig --install-defaults
+-"$dst"/vncinitconfig -install-defaults
diff --git a/tunlr/tunlr b/tunlr/tunlr
--- a/tunlr/tunlr
+++ b/tunlr/tunlr
@@ -1,49 +1,35 @@
 #!/bin/bash
 
-# tunlr 0.1.8 - watch netflix, mtu, cbs, hulu & more outside the u.s.
+# tunlr 0.1.9 - watch netflix, mtu, cbs, hulu & more outside the u.s.
 # for more information about tunlr please visit <http://tunlr.net/>
 #
 # Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
 # License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
 
-LOG=$(mktemp /tmp/tunlr_errors.XXXXXXXXXX)
 RSLV=/etc/resolv.conf
+NLL=/dev/null
 QUERY='http://tunlr.net/tunapi.php?action=getdns&version=1&format=json'
 IPV4='\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'
-
-err() {
-	echo "failed"
-	cat $LOG
-	rm $LOG
-	exit 1
-}
-
-exit_with() {
-	if [ -f $LOG ] && [ -O $LOG ]
-	then
-		rm $LOG
-	fi
-
-	exit $1
-}
 
 if [ $UID != 0 ] && [[ "$1" =~ start|stop ]]
 then
 	echo "you must be root to run 'tunlr $1'" 1>&2
-	exit_with 1
+	exit 1
 fi
 
+err() { echo "failed"; exit 1; }
+
 case "$1" in
-	start)
-		echo -n "activating tunlr IPs... "
+
+	start)	echo -n "activating tunlr service... "
 
 		# DNS IP query
-		L1=$(wget -q -O - $QUERY | grep -Eo "$IPV4")
+		L1=$(wget -q -O - "$QUERY" | grep -Eo "$IPV4")
 
 		if [ -z "$L1" ]
 		then
-			echo -e "failed\nDNS IP query failed - no IPs received"
-			exit_with 1
+			echo -e "failed\nDNS address query failed - no IP address received"
+			exit 1
 		else
 			L2=$(echo "$L1" | sed 's/ /\n/g' | sed 's/^/nameserver /g')
 			L3=$(echo $L1 | sed -e 's/ / and /g')
@@ -52,32 +38,31 @@ case "$1" in
 		if [ -f $RSLV.bak ]
 		then
 			echo -e "failed\n$RSLV.bak does already exist - nothing will be changed"
-			exit_with 1
+			exit 1
 		else
-			cp $RSLV $RSLV.bak 2>$LOG || err
+			cp $RSLV $RSLV.bak 2>$NLL || err
 		fi
 
-		echo -e "#TUNLR DNS\n$L2" >$RSLV 2>$LOG
+		echo -e "#TUNLR DNS\n$L2" >$RSLV 2>$NLL
 		cat $RSLV.bak >>$RSLV
-		echo -e "ok\n($L3) have been added to $RSLV\nrestart your web browser to apply the changes"
+		echo -e "ok\n$L3 have been added to $RSLV\nrestart your web browser to apply the changes"
 		;;
 
-	stop)
-		echo -n "deactivating tunlr IPs... "
+	stop)	echo -n "deactivating tunlr service... "
 
 		if [ -f $RSLV.bak ]
 		then
-			cp $RSLV.bak $RSLV 2>$LOG || err
-			rm $RSLV.bak 2>$LOG || err
+			cp $RSLV.bak $RSLV 2>$NLL || err
+			rm $RSLV.bak 2>$NLL || err
 			echo -e "ok\nrestart your web browser to apply the changes"
 		else
 			echo -e "failed\n$RSLV.bak does not exist - unable to restore DNS config"
-			exit_with 1
+			exit 1
 		fi
 		;;
 
-	*)
-		echo "usage: $0 {start|stop}"
+	*)	echo "usage: $0 {start|stop}" ;;
+
 esac
 
-exit_with 0
+exit 0
