updated on Thu Jun 21 04:00:13 UTC 2012

diff --git a/sickbeard-git/sickbeard.init b/sickbeard-git/sickbeard.init
--- a/sickbeard-git/sickbeard.init
+++ b/sickbeard-git/sickbeard.init
@@ -4,24 +4,20 @@
 . /etc/rc.d/functions
 . /etc/conf.d/sickbeard
 
+SB_PIDFILE="/opt/sickbeard/sickbeard/sickbeard.pid"
+
 case "$1" in
   start)
     stat_busy "Starting Sick Beard"
 
-    if [ -f /var/run/daemons/sickbeard ]; then
-      echo -n "Sick Beard is already running as a daemon! If you are certain it is not running, remove /var/run/daemons/sickbeard."
+    if [ -f /run/daemons/sickbeard ]; then
+      echo "Sick Beard is already running as a daemon! If you are certain it is not, remove /run/daemons/sickbeard."
+      stat_fail
+    elif [ -f $SB_PIDFILE ]; then
+      echo "Sick Beard may already be running. If you are certain it is not, remove $SB_PIDFILE."
       stat_fail
     else
-      SB_ARGS="-q -d"
-
-      if [ "$SB_DATA" ]; then
-        SB_ARGS+=" --data \"$SB_DATA\""
-      fi
-
-      if [ "$SB_CONF" ]; then
-        SB_ARGS+=" --config \"$SB_CONF\""
-      fi
-
+      SB_ARGS+=" --pidfile $SB_PIDFILE"
       if [ ! "$SB_USER" ]; then
         /usr/bin/sickbeard $SB_ARGS
         RC=$?
@@ -41,37 +37,23 @@ case "$1" in
   stop)
     stat_busy "Stopping Sick Beard"
 
-    SB_PORT=$(grep -i web_port "$SB_CONF" | sed -e 's/.*=\s*//')
-    SB_PROTOCOL=$(grep -i 'enable_https\s*=\s*1' "$SB_CONF")
-    SB_WEBROOT=$(grep -i web_root "$SB_CONF" | sed -e 's/.*=\s*//' -e 's/"//g')
-    SB_USERNAME=$(grep -i web_username "$SB_CONF" | sed -e 's/.*=\s*//' -e 's/"//g')
-    SB_PASSWORD=$(grep -i web_password "$SB_CONF" | sed -e 's/.*=\s*//' -e 's/"//g')
-
-    if [ "$SB_PROTOCOL" ]; then
-      SB_URL="https://"
+    if [ ! -f $SB_PIDFILE ]; then
+      echo "The pid file is missing. Check that Sick Beard is actually running."
+      RC=1
     else
-      SB_URL="http://"
+      SB_PID=$(cat $SB_PIDFILE)
+      kill $SB_PID
+      RC=$?
     fi
 
-    if [ "$SB_USERNAME" ]; then
-      SB_URL+="$SB_USERNAME"
-
-      if [ "$SB_PASSWORD" ]; then
-        SB_URL+=":$SB_PASSWORD"
-      fi
-
-      SB_URL+="@"
-    fi
-
-    SB_URL+="localhost:$SB_PORT/$SB_WEBROOT/home/shutdown/"
-
-    wget -q --delete-after --no-check-certificate "$SB_URL" &>/dev/null
-
-    if [ $? -gt 0 ]; then
-      echo "The shutdown failed. Check that Sick Beard is actually running and that the proper values are in /etc/conf.d/sickbeard."
-      echo "You may also have issues if you haven't restarted Sick Beard after changing something like the web protocol."
+    if [ $RC -gt 0 ]; then
+      echo "The shutdown failed. Check that Sick Beard is actually running."
       stat_fail
     else
+      while [ -f $SB_PIDFILE ]; do
+        sleep 1
+      done
+
       rm_daemon sickbeard
       stat_done
     fi
@@ -81,8 +63,13 @@ case "$1" in
     sleep 1
     "$0" start
     ;;
+  status)
+    stat_busy "Sick Beard daemon status:";
+    ck_status $daemon_name
+    ;;
+
   *)
-    echo "usage: $0 {start|stop|restart}"
+    echo "usage: $0 {start|stop|restart|status}"
 esac
 exit 0
 
