updated on Sun Jun  3 02:06:17 UTC 2012

diff --git a/sickbeard-git/sickbeard.init b/sickbeard-git/sickbeard.init
--- a/sickbeard-git/sickbeard.init
+++ b/sickbeard-git/sickbeard.init
@@ -6,14 +6,31 @@
 
 case "$1" in
   start)
-    stat_busy "Starting Sick-Beard"
+    stat_busy "Starting Sick Beard"
 
     if [ -f /var/run/daemons/sickbeard ]; then
-      echo -n "Sickbeard is already running as a daemon! If you are certain it is not running, remove /var/run/daemons/sickbeard."
+      echo -n "Sick Beard is already running as a daemon! If you are certain it is not running, remove /var/run/daemons/sickbeard."
       stat_fail
     else
-      su - $SB_USER -c "$SB_PYTHON $SB_BIN -q -d --data $SB_DATA --config $SB_CONF --port $SB_PORT" -s /bin/sh
-      if [ $? -gt 0 ]; then
+      SB_ARGS="-q -d"
+
+      if [ "$SB_DATA" ]; then
+        SB_ARGS+=" --data \"$SB_DATA\""
+      fi
+
+      if [ "$SB_CONF" ]; then
+        SB_ARGS+=" --config \"$SB_CONF\""
+      fi
+
+      if [ ! "$SB_USER" ]; then
+        /usr/bin/sickbeard $SB_ARGS
+        RC=$?
+      else
+        su - $SB_USER -c "/usr/bin/sickbeard $SB_ARGS" -s /bin/sh
+        RC=$?
+      fi
+
+      if [ $RC -gt 0 ]; then
         stat_fail
       else
         add_daemon sickbeard
@@ -22,11 +39,30 @@ case "$1" in
     fi
     ;;
   stop)
-    stat_busy "Stopping Sick-Beard"
+    stat_busy "Stopping Sick Beard"
 
- 
-    wget -q --delete-after $SB_PROTOCOL://localhost:$SB_PORT$SB_WEBROOT/home/shutdown/ &> /dev/null
-    if [ "${?}" -gt 0 ]; then
+    if [ ! "$SB_PORT" ]; then
+      SB_PORT="8081"
+    fi
+
+    if [ ! "$SB_PROTOCOL" ]; then
+      SB_PROTOCOL="http"
+    fi
+
+    if [ ! "$SB_WEBROOT" ]; then
+      SB_WEBROOT="/"
+    fi
+
+    if [ "$SB_USPW" ]; then
+      wget -q --delete-after $SB_PROTOCOL://$SB_USPW@localhost:$SB_PORT$SB_WEBROOT/home/shutdown/ &> /dev/null
+      RC=$?
+    else
+      wget -q --delete-after $SB_PROTOCOL://localhost:$SB_PORT$SB_WEBROOT/home/shutdown/ &>/dev/null
+      RC=$?
+    fi
+
+    if [ "$RC" -gt 0 ]; then
+      echo "The shutdown failed. Check that Sick Beard is actually running and that the proper values are in /etc/conf.d/sickbeard."
       stat_fail
     else
       rm_daemon sickbeard
@@ -34,11 +70,12 @@ case "$1" in
     fi
     ;;
   restart)
-    "${0}" stop
+    "$0" stop
     sleep 1
-    "${0}" start
+    "$0" start
     ;;
   *)
-    echo "usage: ${0} {start|stop|restart}"
+    echo "usage: $0 {start|stop|restart}"
 esac
 exit 0
+
