updated on Tue Apr  9 12:00:05 UTC 2013

diff --git a/nexus/nexus b/nexus/nexus
--- a/nexus/nexus
+++ b/nexus/nexus
@@ -1,11 +1,4 @@
 #! /bin/sh
-#
-# The following changes are made for the ArchLinux nexus package
-# Contributor: Markus M. May <mmay AT javafreedom DOT org>
-#
-export NEXUS_HOME=${NEXUS_HOME:=/opt/nexus}
-export NEXUS_RUN_DIR=${NEXUS_RUN_DIR:=/var/run/nexus}
-export PLEXUS_NEXUS_WORK=${PLEXUS_NEXUS_WORK:=/var/lib/nexus}
 
 #
 # Copyright (c) 1999, 2006 Tanuki Software Inc.
@@ -13,23 +6,27 @@ export PLEXUS_NEXUS_WORK=${PLEXUS_NEXUS_WORK:=/var/lib/nexus}
 # Java Service Wrapper sh script.  Suitable for starting and stopping
 #  wrapped Java applications on UNIX platforms.
 #
+
 #-----------------------------------------------------------------------------
 # These settings can be modified to fit the needs of your application
 
-# Default values for the Application variables, below. 
-# 
-# NOTE: The build for specific applications may override this during the resource-copying
-# phase, to fill in a concrete name and avoid the use of the defaults specified here.
-DEF_APP_NAME="testwrapper"
-DEF_APP_LONG_NAME="Test Wrapper Sample Application"
+# Set this to the root of the Nexus installation
+export NEXUS_HOME=${NEXUS_HOME:=/opt/nexus}
+export NEXUS_RUN_DIR=${NEXUS_RUN_DIR:=/opt/nexus/run}
+
+
+# If specified, the Wrapper will be run as the specified user.
+
+# IMPORTANT - Make sure that the user has the required privileges to write into the Nexus installation directory.
+
+# NOTE - This will set the user which is used to run the Wrapper as well as
+#  the JVM and is not useful in situations where a privileged resource or
+#  port needs to be allocated prior to the user being changed.
+RUN_AS_USER=nexus
 
 # Application
 APP_NAME="nexus"
 APP_LONG_NAME="Nexus OSS"
-
-# Wrapper
-WRAPPER_CMD="$NEXUS_HOME/bin/wrapper"
-WRAPPER_CONF="$NEXUS_HOME/conf/wrapper.conf"
 
 # Priority at which to run the wrapper.  See "man nice" for valid priorities.
 #  nice is only used if a priority is specified.
@@ -42,16 +39,6 @@ PIDDIR="$NEXUS_RUN_DIR"
 #  When launched with the 'start' command, it will also ignore all INT and
 #  TERM signals.
 #IGNORE_SIGNALS=true
-
-# If specified, the Wrapper will be run as the specified user.
-# IMPORTANT - Make sure that the user has the required privileges to write
-#  the PID file and wrapper.log files.  Failure to be able to write the log
-#  file will cause the Wrapper to exit without any way to write out an error
-#  message.
-# NOTE - This will set the user which is used to run the Wrapper as well as
-#  the JVM and is not useful in situations where a privileged resource or
-#  port needs to be allocated prior to the user being changed.
-RUN_AS_USER=nexus
 
 # The following two lines are used by the chkconfig command. Change as is
 #  appropriate for your application.  They should remain commented.
@@ -111,33 +98,6 @@ done
 cd "`dirname "$REALPATH"`"
 REALDIR=`pwd`
 
-# If the PIDDIR is relative, set its value relative to the full REALPATH to avoid problems if
-#  the working directory is later changed.
-FIRST_CHAR=`echo $PIDDIR | cut -c1,1`
-if [ "$FIRST_CHAR" != "/" ]
-then
-    PIDDIR=$REALDIR/$PIDDIR
-fi
-# Same test for WRAPPER_CMD
-FIRST_CHAR=`echo $WRAPPER_CMD | cut -c1,1`
-if [ "$FIRST_CHAR" != "/" ]
-then
-    WRAPPER_CMD=$REALDIR/$WRAPPER_CMD
-fi
-# Same test for WRAPPER_CONF
-FIRST_CHAR=`echo $WRAPPER_CONF | cut -c1,1`
-if [ "$FIRST_CHAR" != "/" ]
-then
-    WRAPPER_CONF=$REALDIR/$WRAPPER_CONF
-fi
-
-# Process ID
-ANCHORFILE="$PIDDIR/$APP_NAME.anchor"
-PIDFILE="$PIDDIR/$APP_NAME.pid"
-LOCKDIR="/var/lock/subsys"
-LOCKFILE="$LOCKDIR/$APP_NAME"
-pid=""
-
 # Resolve the location of the 'ps' command
 PSEXE="/usr/bin/ps"
 if [ ! -x "$PSEXE" ]
@@ -156,6 +116,7 @@ DIST_OS=`uname -s | tr [:upper:] [:lower:] | tr -d [:blank:]`
 case "$DIST_OS" in
     'sunos')
         DIST_OS="solaris"
+        PSEXE="/usr/ucb/ps"
         ;;
     'hp-ux' | 'hp-ux64')
         DIST_OS="hpux"
@@ -169,20 +130,29 @@ case "$DIST_OS" in
 esac
 
 # Resolve the architecture
-DIST_ARCH=`uname -p | tr [:upper:] [:lower:] | tr -d [:blank:]`
+DIST_ARCH=`uname -m | tr [:upper:] [:lower:] | tr -d [:blank:]`
+DIST_BITS=32
 if [ "$DIST_ARCH" = "unknown" ]
 then
     DIST_ARCH=`uname -m | tr [:upper:] [:lower:] | tr -d [:blank:]`
 fi
 case "$DIST_ARCH" in
-    'amd64' | 'athlon' | 'ia32' | 'ia64' | 'i386' | 'i486' | 'i586' | 'i686' | 'x86_64')
+    'athlon' | 'ia32' | 'i386' | 'i486' | 'i586' | 'i686')
         DIST_ARCH="x86"
+        ;;
+    'amd64' | 'x86_64' | 'ia64')
+        DIST_ARCH="x86"
+        DIST_BITS=64
         ;;
     'ip27')
         DIST_ARCH="mips"
         ;;
-    'power' | 'powerpc' | 'power_pc' | 'ppc64')
+    'power' | 'powerpc' | 'power_pc')
         DIST_ARCH="ppc"
+        ;;
+    'ppc64')
+        DIST_ARCH="ppc"
+        DIST_BITS=64
         ;;
     'pa_risc' | 'pa-risc')
         DIST_ARCH="parisc"
@@ -195,6 +165,16 @@ case "$DIST_ARCH" in
         ;;
 esac
 
+# Extra architecture detection
+case "$DIST_OS" in
+    'macosx')
+        if [ `sysctl hw.cpu64bit_capable | awk '{ print $2 }'` = '1' ]; then
+            DIST_BITS=64
+        fi
+        DIST_ARCH='universal'
+        ;;
+esac
+
 outputFile() {
     if [ -f "$1" ]
     then
@@ -204,63 +184,41 @@ outputFile() {
     fi
 }
 
-# Decide on the wrapper binary to use.
-# If a 32-bit wrapper binary exists then it will work on 32 or 64 bit
-#  platforms, if the 64-bit binary exists then the distribution most
-#  likely wants to use long names.  Otherwise, look for the default.
-# For macosx, we also want to look for universal binaries.
-WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-if [ -x "$WRAPPER_TEST_CMD" ]
+# Test if NEXUS_HOME is relative (does not start with /). If relative it should be relative to this script location
+FIRST_CHAR=`echo $NEXUS_HOME | cut -c1,1`
+if [ "$FIRST_CHAR" != "/" ]
 then
-    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-else
-    if [ "$DIST_OS" = "macosx" ]
-    then
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-32"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-            if [ -x "$WRAPPER_TEST_CMD" ]
-            then
-                WRAPPER_CMD="$WRAPPER_TEST_CMD"
-            else
-                WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-universal-64"
-                if [ -x "$WRAPPER_TEST_CMD" ]
-                then
-                    WRAPPER_CMD="$WRAPPER_TEST_CMD"
-                else
-                    if [ ! -x "$WRAPPER_CMD" ]
-                    then
-                        echo "Unable to locate any of the following binaries:"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-32"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                        outputFile "$WRAPPER_CMD-$DIST_OS-universal-64"
-                        outputFile "$WRAPPER_CMD"
-                        exit 1
-                    fi
-                fi
-            fi
-        fi
-    else
-        WRAPPER_TEST_CMD="$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-        if [ -x "$WRAPPER_TEST_CMD" ]
-        then
-            WRAPPER_CMD="$WRAPPER_TEST_CMD"
-        else
-            if [ ! -x "$WRAPPER_CMD" ]
-            then
-                echo "Unable to locate any of the following binaries:"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-32"
-                outputFile "$WRAPPER_CMD-$DIST_OS-$DIST_ARCH-64"
-                outputFile "$WRAPPER_CMD"
-                exit 1
-            fi
-        fi
-    fi
+    NEXUS_HOME=$REALDIR/$NEXUS_HOME
 fi
+
+# Default PIDDIR to os/arch/bits directory
+if [ "X$PIDDIR" = "X" ]
+then
+    PIDDIR="bin/jsw/$DIST_OS-$DIST_ARCH-$DIST_BITS"
+fi
+
+# If the PIDDIR is relative, set its value relative to the full NEXUS_HOME to avoid problems if
+#  the working directory is later changed.
+FIRST_CHAR=`echo $PIDDIR | cut -c1,1`
+if [ "$FIRST_CHAR" != "/" ]
+then
+    PIDDIR=$NEXUS_HOME/$PIDDIR
+fi
+
+# Process ID
+ANCHORFILE="$PIDDIR/$APP_NAME.anchor"
+PIDFILE="$PIDDIR/$APP_NAME.pid"
+LOCKDIR="/var/lock/subsys"
+LOCKFILE="$LOCKDIR/$APP_NAME"
+pid=""
+
+WRAPPER_CMD="$NEXUS_HOME/bin/jsw/$DIST_OS-$DIST_ARCH-$DIST_BITS/wrapper"
+if [ ! -x "$WRAPPER_CMD" ]; then
+    echo "Missing platform binary: $WRAPPER_CMD"
+    exit 1
+fi
+
+WRAPPER_CONF="$NEXUS_HOME/bin/jsw/conf/wrapper.conf"
 
 # Build the nice clause
 if [ "X$PRIORITY" = "X" ]
@@ -294,68 +252,77 @@ checkUser() {
     # $1 touchLock flag
     # $2 command
 
+    # Resolve the location of the 'id' command
+    IDEXE="/usr/xpg4/bin/id"
+    if [ ! -x "$IDEXE" ]
+    then
+        IDEXE="/usr/bin/id"
+        if [ ! -x "$IDEXE" ]
+        then
+            echo "Unable to locate 'id'."
+            echo "Please report this message along with the location of the command on your system."
+            exit 1
+        fi
+    fi
+
     # Check the configured user.  If necessary rerun this script as the desired user.
     if [ "X$RUN_AS_USER" != "X" ]
     then
-        # Resolve the location of the 'id' command
-        IDEXE="/usr/xpg4/bin/id"
-        if [ ! -x "$IDEXE" ]
+        if [ "`$IDEXE -u -n`" != "$RUN_AS_USER" ]
         then
-            IDEXE="/usr/bin/id"
-            if [ ! -x "$IDEXE" ]
+            # If LOCKPROP and $RUN_AS_USER are defined then the new user will most likely not be
+            # able to create the lock file.  The Wrapper will be able to update this file once it
+            # is created but will not be able to delete it on shutdown.  If $2 is defined then
+            # the lock file should be created for the current command
+            if [ "X$LOCKPROP" != "X" ]
             then
-                echo "Unable to locate 'id'."
-                echo "Please report this message along with the location of the command on your system."
-                exit 1
+                if [ "X$1" != "X" ]
+                then
+                    # Resolve the primary group 
+                    RUN_AS_GROUP=`groups $RUN_AS_USER | awk '{print $3}' | tail -1`
+                    if [ "X$RUN_AS_GROUP" = "X" ]
+                    then
+                        RUN_AS_GROUP=$RUN_AS_USER
+                    fi
+                    touch $LOCKFILE
+                    chown $RUN_AS_USER:$RUN_AS_GROUP $LOCKFILE
+                fi
             fi
-        fi
     
-        if [ "`$IDEXE -u -n`" = "$RUN_AS_USER" ]
-        then
-            # Already running as the configured user.  Avoid password prompts by not calling su.
-            RUN_AS_USER=""
+            # Still want to change users, recurse.  This means that the user will only be
+            #  prompted for a password once. Variables shifted by 1
+            su -m $RUN_AS_USER -c "\"$REALPATH\" $2"
+    
+            # Now that we are the original user again, we may need to clean up the lock file.
+            if [ "X$LOCKPROP" != "X" ]
+            then
+                getpid
+                if [ "X$pid" = "X" ]
+                then
+                    # Wrapper is not running so make sure the lock file is deleted.
+                    if [ -f "$LOCKFILE" ]
+                    then
+                        rm "$LOCKFILE"
+                    fi
+                fi
+            fi
+    
+            exit 0
         fi
     fi
-    if [ "X$RUN_AS_USER" != "X" ]
+
+    # Check that script is not run as root
+    LUID=`$IDEXE -u`
+    if [ $LUID -eq 0 ]
     then
-        # If LOCKPROP and $RUN_AS_USER are defined then the new user will most likely not be
-        # able to create the lock file.  The Wrapper will be able to update this file once it
-        # is created but will not be able to delete it on shutdown.  If $2 is defined then
-        # the lock file should be created for the current command
-        if [ "X$LOCKPROP" != "X" ]
+        echo "****************************************"
+        echo "WARNING - NOT RECOMMENDED TO RUN AS ROOT"
+        echo "****************************************"
+        if [ ! "`$IDEXE -u -n`" = "$RUN_AS_USER" ]
         then
-            if [ "X$1" != "X" ]
-            then
-                # Resolve the primary group 
-                RUN_AS_GROUP=`groups $RUN_AS_USER | awk '{print $3}' | tail -1`
-                if [ "X$RUN_AS_GROUP" = "X" ]
-                then
-                    RUN_AS_GROUP=$RUN_AS_USER
-                fi
-                touch $LOCKFILE
-                chown $RUN_AS_USER:$RUN_AS_GROUP $LOCKFILE
-            fi
+            echo "If you insist running as root, then set the environment variable RUN_AS_USER=root before running this script."
+            exit 1
         fi
-
-        # Still want to change users, recurse.  This means that the user will only be
-        #  prompted for a password once. Variables shifted by 1
-        su -m $RUN_AS_USER -c "\"$REALPATH\" $2"
-
-        # Now that we are the original user again, we may need to clean up the lock file.
-        if [ "X$LOCKPROP" != "X" ]
-        then
-            getpid
-            if [ "X$pid" = "X" ]
-            then
-                # Wrapper is not running so make sure the lock file is deleted.
-                if [ -f "$LOCKFILE" ]
-                then
-                    rm "$LOCKFILE"
-                fi
-            fi
-        fi
-
-        exit 0
     fi
 }
 
@@ -372,7 +339,17 @@ getpid() {
                 #  common is during system startup after an unclean shutdown.
                 # The ps statement below looks for the specific wrapper command running as
                 #  the pid.  If it is not found then the pid file is considered to be stale.
-                pidtest=`$PSEXE -p $pid -o args | grep "$WRAPPER_CMD" | tail -1`
+                case "$DIST_OS" in
+                    'macosx')
+                        pidtest=`$PSEXE -ww -p $pid -o command | grep "wrapper.pidfile" | tail -1`
+                        ;;
+                    'solaris')
+                        pidtest=`$PSEXE ww $pid | grep "wrapper.pidfile" | tail -1`
+                        ;;
+                    *)
+                        pidtest=`$PSEXE -p $pid -o args | grep "wrapper.pidfile" | tail -1`
+                        ;;
+                esac
                 if [ "X$pidtest" = "X" ]
                 then
                     # This is a stale pid file.
@@ -389,7 +366,12 @@ getpid() {
 }
 
 testpid() {
-    pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+    if [ "$DIST_OS" = "solaris" ]
+    then
+        pid=`$PSEXE ww $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+    else
+        pid=`$PSEXE -p $pid | grep $pid | grep -v grep | awk '{print $1}' | tail -1`
+    fi
     if [ "X$pid" = "X" ]
     then
         # Process is gone so remove the pid file.
