updated on Fri Feb 21 00:26:46 UTC 2014

diff --git a/pebble-sdk/PKGBUILD b/pebble-sdk/PKGBUILD
--- a/pebble-sdk/PKGBUILD
+++ b/pebble-sdk/PKGBUILD
@@ -1,24 +1,61 @@
-# Maintainer: Gianguido aka @PeppeLaKappa (gianguidorama[at]gmail[dot]com
+# Maintainer: Florian Bruhin (The Compiler) <archlinux.org@the-compiler.org>
+
 pkgname=pebble-sdk
-pkgver=1.12
-pkgrel=2
+pkgver=2.0.0
+pkgrel=1
 pkgdesc="Pebble SDK, used to develop applications and watchfaces for the Pebble Smartwatch."
-url="https://account.getpebble.com/sdk_releases"
-arch=('x86_64' 'i686')
-license=('GPLv3')
-depends=('libmpc' 'python-pip' 'wget' 'lib32-libmpc')
-options=('!strip')
-source=("http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk/arm-cs-tools-ubuntu-12.04-2012-12-22.tar.bz2")
-sha256sums=('118fcdc3bebaabc27705bc9c9ca16f3f91daf9579ca52503f0cb07ac2d970eb7')
+url="https://developer.getpebble.com/2/getting-started/"
+arch=('i386' 'x86_64')
+license=('MIT')
+depends=('arm-none-eabi-gcc' 'python2-pillow' 'python2-autobahn'
+         'python2-pyserial' 'python2-sh' 'twisted' 'python2-freetype-py'
+         'python2-websocket-client-pebble')
+source=('python-waf.patch')
+_sdk_sha1sum='e06d77d26c8adb20760217b7f68944a5b72bd223'
+sha1sums=('cd95ccc69820eee60e8e6ff9d85d6edeb7c3b6a8')
+options=('staticlibs' '!strip')
+
+prepare() {
+  if [[ -r "$startdir/PebbleSDK-${pkgver//_/-}.tar.gz" ]]; then
+    cd "$startdir"
+  else
+    echo "Please download the Pebble SDK from:"
+    echo "https://developer.getpebble.com/2/download/PebbleSDK-${pkgver//_/-}.tar.gz"
+    echo "(be sure to be logged in with a Pebble developer account)"
+    echo "Then place it in /tmp and press Enter."
+    read _
+    cd /tmp
+    if [[ ! -r "PebbleSDK-${pkgver//_/-}.tar.gz" ]]; then
+      echo "Error: PebbleSDK-${pkgver//_/-}.tar.gz does not exist in /tmp!"
+      exit 1
+    fi
+  fi
+  echo -e "$_sdk_sha1sum\tPebbleSDK-${pkgver//_/-}.tar.gz" > "$srcdir/SHA1SUMS"
+  sha1sum --quiet -c "$srcdir/SHA1SUMS"
+  msg "Extracting sources..."
+  tar -zxf "PebbleSDK-${pkgver//_/-}.tar.gz" -C "$srcdir"
+  cd "$srcdir/PebbleSDK-${pkgver//_/-}"
+  msg "Patching shebangs..."
+  find . -type f \( -path ./bin/pebble -o -path ./Pebble/waf -o \
+                    -name '*.py' \) -exec \
+    sed -i '1s|^#!/usr/bin/env python$|#!/usr/bin/python2|' {} \;
+}
 
 package() {
-  echo "Download the Pebble SDK from https://account.getpebble.com/sdk_releases and place it into /tmp (be sure to be logged into a Pebble account), then press Enter"
-  read A
-  tar -zxf /tmp/PebbleSDK-1.12.tar.gz -C $srcdir
-  mkdir $pkgdir/opt
-  mv $srcdir/arm-cs-tools $pkgdir/opt/arm-cs-tools
-  mv $srcdir/PebbleSDK-1.12 $pkgdir/opt
-  echo "Now add /opt/arm-cs-tools/bin to your PATH"
+  install -dm755 "$pkgdir/opt/pebble"
+  install -dm755 "$pkgdir/usr/bin"
+  cd "$srcdir/PebbleSDK-${pkgver//_/-}"
+  cp -R * "$pkgdir/opt/pebble"
+  rm -r "$pkgdir/opt/pebble/bin"
+  ln -s "/opt/pebble/tools/pebble.py" "$pkgdir/usr/bin/pebble"
+  # Unpack waf and fix python files
+  cd "$pkgdir/opt/pebble/Pebble/"
+  ./waf 2>/dev/null || true
+  cd .waf*
+  msg "Patching waf..."
+  find . -type f -name '*.py' -exec \
+    sed -i '1s|^#! /usr/bin/env python$|#!/usr/bin/python2|' {} \;
+  patch -p0 -i "$srcdir/python-waf.patch"
 }
 
 # vim:set ts=2 sw=2 et:
