updated on Tue Nov  4 00:00:23 UTC 2014

diff --git a/mdcharm/PKGBUILD b/mdcharm/PKGBUILD
--- a/mdcharm/PKGBUILD
+++ b/mdcharm/PKGBUILD
@@ -1,22 +1,46 @@
-#Maintainer: proudzhu <proudzhu.fdu at gmail.com>
+#Maintainer: Daniel Nagy <danielnagy at gmx de>
+
+# mdcharm is currently unmaintained. See https://github.com/zhangshine/MdCharm/issues/4
 
 pkgname=mdcharm
-pkgver=1.1.6
-pkgrel=3
+pkgver=1.2.0
+pkgrel=1
 pkgdesc="A wiki editor, currently it supports markdown(markdown extra) and Multi-Markdown."
 arch=('i686' 'x86_64')
 url="http://www.mdcharm.com/"
 license=('custom')
-source=("http://www.mdcharm.com/release/${pkgver}/${pkgname}_${pkgver}_i386.deb")
-md5sums=('f2b6820ebf5a45caaa5632614906c799')
+source=("https://github.com/zhangshine/MdCharm/archive/$pkgver.tar.gz")
+sha1sums=('6179ebd14b862fdd6ae160e3bf5f1ab95cd59d48')
+depends=('qtwebkit' 'hunspell' 'zlib' 'gcc-libs' "python2" )
 
-if [[ $CARCH == x86_64 ]]; then
-  depends=('lib32-qtwebkit' 'lib32-hunspell' 'lib32-zlib' 'lib32-gcc-libs' )
-else
-  depends=('qtwebkit' 'hunspell' 'zlib' 'gcc-libs' )
-fi
+prepare() {
+  # some sed hassle...
+  sed -i -e "s,python ../../src/MdCharm/,python2 $srcdir/MdCharm-$pkgver/src/MdCharm/,g" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/MdCharm.pro
+  sed -i -e "s,../../src/MdCharm/,$srcdir/MdCharm-$pkgver/src/MdCharm/,g" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "s,../../src/res/,$srcdir/MdCharm-$pkgver/src/res/,g" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "s,revision_output = .*,revision_output = None; revision = \"$pkgver\",g" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "s,tag_output = .*,tag_output = None; tag = \"$pkgver\",g" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "17d" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "17d" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "20d" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+  sed -i -e "20d" \
+      $srcdir/MdCharm-$pkgver/src/MdCharm/version_h.py
+}
 
 package() {
-    cd "${srcdir}"
-    tar azxvf data.tar.gz -C "${pkgdir}"
+    #cd "${srcdir}/MdCharm-$pkgver/src/"
+    mkdir -p $srcdir/build
+    cd $srcdir/build
+    qmake $srcdir/MdCharm-$pkgver/src/
+    export PYTHON=python2
+    make || true # first run might fail
+    make -j1
 }
