updated on Tue Jul  1 00:02:50 UTC 2014

diff --git a/irssi-git/html2text.patch b/irssi-git/html2text.patch
--- a/irssi-git/html2text.patch
+++ b/irssi-git/html2text.patch
@@ -1,16 +1,13 @@
---- irssi/autogen.sh	2014-03-10 14:15:44.442645418 -0400
-+++ autogen.sh	2014-03-10 14:51:35.690269902 -0400
-@@ -40,9 +40,11 @@
+--- a/autogen.sh	2014-06-30 01:32:51.536139439 -0400
++++ b/autogen.sh	2014-06-30 01:32:34.645970961 -0400
+@@ -31,6 +31,10 @@
    lynx -dump -nolist docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
  elif type elinks >/dev/null 2>&1 ; then
    elinks -dump docs/faq.html|perl -pe 's/^ *//; if ($_ eq "\n" && $state eq "Q") { $_ = ""; } elsif (/^([QA]):/) { $state = $1 } elsif ($_ ne "\n") { $_ = "   $_"; };' > docs/faq.txt
 +elif type html2text >/dev/null 2>&1 ; then
 +  html2text docs/faq.html > docs/faq.txt
- else
--  echo "**Error**: No lynx or links present"
--  exit 1
 +  echo "**Error**: No lynx, elinks, or html2text present"
 +  echo "But since you aren't dumb, we'll move on anyway..."
- fi
- 
- if test x$NOCONFIGURE = x && test -z "$*"; then
+ else
+   echo "**Error**: No lynx or elinks present"
+   exit 1
