updated on Wed Jul 27 17:31:02 UTC 2011

diff --git a/vvvvvv/PKGBUILD b/vvvvvv/PKGBUILD
--- a/vvvvvv/PKGBUILD
+++ b/vvvvvv/PKGBUILD
@@ -3,22 +3,41 @@
 
 pkgname=vvvvvv
 pkgver=2.0
-pkgrel=3
+_build=3
+pkgrel=4
 pkgdesc="A retro styled 2D platformer"
 arch=('i686' 'x86_64')
 url="http://thelettervsixtim.es/"
 license=('unknown')
-depends=('libjpeg6' 'libtiff4' 'slang' 'libcaca' 'aalib')
+depends=('libjpeg6' 'libtiff4' 'slang' 'libcaca' 'aalib' 'esound' 'libmikmod' 'audiofile' 'sdl' 'sdl_image' 'sdl_mixer' 'libogg' 'smpeg' 'libvorbis')
 source=('vvvvvv.desktop')
 sha256sums=('a5eea031606f206b14f752eee7079fb18b6462fd751087d4641ca1831beb867f')
 
+_archive="VVVVVV_${pkgver}_Linux${_build}.tar.gz"
+_archive_md5="8eea8661a21058698d9bbffcd1ee1c65"
+
 build() {
   cd $srcdir
-  echo Please place VVVVVV_${pkgver}_Linux2.tar.gz into $(pwd)
+  
+  if [ ! -f ${_archive} ]; then
+  echo Please place ${_archive} into $(pwd)
   echo Press Enter to continue
   read -a _unused
+  fi
+
+  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_archive}"
+    return 1
+  fi
+
   install -d ${pkgdir}/opt/
-  tar xzf VVVVVV_2.0_Linux2.tar.gz -C ${pkgdir}/opt/
+  tar xzf ${_archive} -C ${pkgdir}/opt/
+  rm -fr ${pkgdir}/opt/VVVVVV/LIB{32,64}
+  if [ "$CARCH" = "x86_64" ]; then
+    rm -fr ${pkgdir}/opt/VVVVVV/VVVVVV_32
+  else
+    rm -fr ${pkgdir}/opt/VVVVVV/VVVVVV_64
+  fi
   install -d ${pkgdir}/usr/bin
   ln -s /opt/VVVVVV/VVVVVV ${pkgdir}/usr/bin/vvvvvv
   
