updated on Mon Jan  7 07:00:02 UTC 2013

diff --git a/vvvvvv/PKGBUILD b/vvvvvv/PKGBUILD
--- a/vvvvvv/PKGBUILD
+++ b/vvvvvv/PKGBUILD
@@ -1,75 +1,59 @@
-# Maintainer: gadget3000 <gadget3000 at msn dot com>
+# Contributor: gadget3000 <gadget3000 at msn dot com>
 # Contributor: mikers <mikeonthecomputer at gmail dot com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
 
 pkgname=vvvvvv
 pkgver=2.01
-_build=
-pkgrel=2
-pkgdesc="A retro styled 2D platformer"
+pkgrel=3
+pkgdesc="A retro styled 2D platformer (game sold separately)"
 arch=('i686' 'x86_64')
 url="http://thelettervsixtim.es/"
 groups=('humblebundle3' 'humblebundle4' 'humblebundles')
-license=('unknown')
+license=('custom')
 depends=('sdl_image' 'sdl_mixer' 'gcc-libs')
-source=('vvvvvv.desktop')
-sha256sums=('a5eea031606f206b14f752eee7079fb18b6462fd751087d4641ca1831beb867f')
+source=("hib://VVVVVV_${pkgver}_Linux.tar.gz" "${pkgname}.desktop")
+md5sums=(
+    '54d3679da69d92adb65fe9633f3c67d7'
+    'f3f06f16bf7f3280279e2d3da425a5d2')
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+PKGEXT='.pkg.tar'
 
-_archive="VVVVVV_${pkgver}_Linux${_build}.tar.gz"
-_archive_md5="54d3679da69d92adb65fe9633f3c67d7"
+package() {
+  cd "${srcdir}/VVVVVV"
 
-build() {
-  cd $srcdir
-  
-  if [ ! -f ${_vvvvvvarchivelocation}${_archive} ]; then
-	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-		wget http://www.humblebundle.com/?key=${_humblebundle3key}
-		wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-		mv ${_archive}* ${_archive}
-          elif [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-                rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-                wget http://www.humblebundle.com/?key=${_humblebundle4key}
-                wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-                mv ${_archive}* ${_archive}
-	  elif [ -z "${_humblebundle3key}" ] && [ -z "${_humblebundle4key}" ]; then
-		echo You can now automate the download of the archive using the _humblebundle3key or _humblebundle4key bash variables.
-		echo Just add \'export _humblebundle3key\=\<Your key here\>\' and/or
-		echo \'export _humblebundle4key\=\<Your key here\>\' to \.bashrc
-		echo
-		echo Otherwise please just place ${_archive} into $(pwd)/
-		echo Press Enter to continue
-		read -a _unused
-	  fi
-  fi
-
-  if [ ! -f ${_vvvvvvarchivelocation}${_archive} ]; then
-    echo "${_vvvvvvarchivelocation}${_archive} not found!"
-    return 1
-  fi  
-
-  if ! echo "${_archive_md5}  ${_vvvvvvarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_vvvvvvarchivelocation}${_archive}"
-    return 1
-  fi
-
-  install -d ${pkgdir}/usr/share/
-  tar xzf ${_vvvvvvarchivelocation}${_archive} -C ${pkgdir}/usr/share/
-  rm -fr ${pkgdir}/usr/share/VVVVVV/LIB{32,64}
-  if [ "$CARCH" = "x86_64" ]; then
-    rm -fr ${pkgdir}/usr/share/VVVVVV/VVVVVV_32
+  install -d "${pkgdir}/opt/${pkgname}"
+  install -m755 VVVVVV "${pkgdir}/opt/${pkgname}/VVVVVV"
+  if [ "${CARCH}" = "x86_64" ]; then
+    install -m755 VVVVVV_64 "${pkgdir}/opt/${pkgname}/VVVVVV_64"
   else
-    rm -fr ${pkgdir}/usr/share/VVVVVV/VVVVVV_64
+    install -m755 VVVVVV_32 "${pkgdir}/opt/${pkgname}/VVVVVV_32"
   fi
-  install -d ${pkgdir}/usr/bin
-  ln -s /usr/share/VVVVVV/VVVVVV ${pkgdir}/usr/bin/vvvvvv
-  
-  # Install the icon file
-  install -D -m 644 ${pkgdir}/usr/share/VVVVVV/data/icons/32_2.png \
-      ${pkgdir}/usr/share/pixmaps/vvvvvv_icon.png
+  install -d "${pkgdir}/opt/${pkgname}/data"
+  install -m644 -t "${pkgdir}/opt/${pkgname}/data" data/vvvvvvmusic.vvv
+  install -d "${pkgdir}/opt/${pkgname}/data/graphics"
+  install -m644 -t "${pkgdir}/opt/${pkgname}/data/graphics" data/graphics/*.png
+  install -d "${pkgdir}/opt/${pkgname}/data/icons"
+  install -m644 -t "${pkgdir}/opt/${pkgname}/data/icons" data/icons/*.png
+  install -d "${pkgdir}/opt/${pkgname}/data/levels"
+  install -m644 -t "${pkgdir}/opt/${pkgname}/data/levels" data/levels/*.vvvvvv
+  install -d "${pkgdir}/opt/${pkgname}/data/sounds"
+  install -m644 -t "${pkgdir}/opt/${pkgname}/data/sounds" data/sounds/*.wav
 
-  # Install desktop file
-  install -D -m 644 ${srcdir}/vvvvvv.desktop \
-      ${pkgdir}/usr/share/applications/vvvvvv.desktop
+  install -d "${pkgdir}/usr/bin"
+  ln -s "/opt/${pkgname}/VVVVVV" "${pkgdir}/usr/bin/${pkgname}"
 
-  chown -Rh root:root ${pkgdir}/usr/share/VVVVVV
+  install -D -m644 "data/icons/32_2.png" \
+      "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
+  install -D -m644 "${srcdir}/${pkgname}.desktop" \
+      "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 }
