updated on Sat Jul 30 18:31:36 UTC 2011

diff --git a/pacaur/pacaur b/pacaur/pacaur
--- a/pacaur/pacaur
+++ b/pacaur/pacaur
@@ -5,7 +5,7 @@
 #
 
 name="pacaur"
-version="2.2.0"
+version="2.2.1"
 
 #
 # Default config
@@ -13,7 +13,8 @@ version="2.2.0"
 
 # tmpdir
 tmpDir="${TMPDIR:-/tmp}/${name}tmp-$USER"
-[[ -d "$tmpDir" ]] && rm -rf "$tmpDir" &>/dev/null && mkdir -p "$tmpDir"
+[[ -d "$tmpDir" ]] && rm -rf "$tmpDir" &>/dev/null
+mkdir -p "$tmpDir"
 
 buildDir="$tmpDir"              # build directory
 editor=${EDITOR:-vi}            # PKGBUILD editor
@@ -145,6 +146,8 @@ UpgradeAur() {
         exit   
     fi
 
+    [[ $operation ]] && pkgs=(${aurpkgs[@]})
+
     timeout ${aurpkgs[@]}
 }
 
@@ -174,7 +177,7 @@ CleanUp() {
         if [[ $count -ne 1 ]]; then
             # hack for cvs protected files
             chmod -R 755 $buildDir/* &>/dev/null
-            rm -r $buildDir/* &>/dev/null && success "Build directory ${colorW}$buildDir${reset} cleaned" || warn "Could not clean build directory ${colorW}$buildDir${reset}"
+            rm -r $buildDir/* &>/dev/null && success "Build directory cleaned" || warn "Could not clean build directory"
         fi
     fi
 }
@@ -204,7 +207,6 @@ MakePkgs() {
     # set architecture variables
     if [[ ! $confSourced ]]; then
         source /etc/makepkg.conf
-        source /etc/abs.conf
         export PACMAN=$pacmanBin
         confSourced=true
     fi
@@ -225,8 +227,10 @@ MakePkgs() {
                     for j in ${pkgs[@]}; do
                         [[ $j = $i ]] && isexpl=true
                     done
-                    [[ $isexpl != true ]] && runasroot $pacmanBin -D --asdeps $i ${pacopts[@]} &>/dev/null
+                    [[ $isexpl != true ]] && runasroot $pacmanBin -D $i --asdeps ${pacopts[@]} &>/dev/null
                 fi
+                [[ " ${pacopts[@]} " =~ " --asdeps " ]] && runasroot $pacmanBin -D $i --asdeps ${pacopts[@]} &>/dev/null
+                [[ " ${pacopts[@]} " =~ " --asexplicit " ]] && runasroot $pacmanBin -D $i --asexplicit ${pacopts[@]} &>/dev/null
             else
                 makepkg -sf ${makeopts[@]} --noconfirm
             fi
@@ -329,7 +333,7 @@ IgnoreChecks() {
 
 GetIgnoredPkgs() {
     ignoredpkgs+=( $(grep '^ *IgnorePkg' '/etc/pacman.conf' | cut -d '=' -f 2-) )
-    ignoredpkgs+=( $(grep '^ *IgnorePkg' "$HOME/.config/cower/config" | cut -d '=' -f 2-) )
+    [[ -e "$HOME/.config/cower/config" ]] && ignoredpkgs+=( $(grep '^ *IgnorePkg' "$HOME/.config/cower/config" | cut -d '=' -f 2-) )
     ignoredpkgs=(${ignoredpkgs[@]//,/ })
 }
 
@@ -422,8 +426,8 @@ usage() {
     echo "   -u, --update    update AUR package(s)"
     echo ""
     echo "options:"
-    echo "   -f, --force     force operation -- can be combined with the -d, -m, -y, -abs flags"
-    echo "   -e, --edit      edit target PKGBUILD -- can be combined with the -d, -b, -m, -y, -u, -abs flags"
+    echo "   -f, --force     force operation -- can be combined with the -d, -m, -y flags"
+    echo "   -e, --edit      edit target PKGBUILD -- can be combined with the -d, -m, -y, -u flags"
     echo "   -c, --clean     clean target(s) build files -- pass twice to clean the entire build directory"
     echo ""
     echo "pacman options:"
