updated on Thu Dec 20 14:00:03 UTC 2012

diff --git a/torchlight-hib/PKGBUILD b/torchlight-hib/PKGBUILD
--- a/torchlight-hib/PKGBUILD
+++ b/torchlight-hib/PKGBUILD
@@ -11,30 +11,31 @@ license=('custom:commercial')
 depends=('libgl' 'mesa' 'freeglut' 'libxrandr' 'expat' 'libxaw' 'libxft'
          'libxinerama' 'freeimage' 'util-linux' 'zziplib' 'pcre' 'libtxc_dxtn')
 source=('torchlight-hib.desktop')
-md5sums=('4b14ae135bb86f490493729901412a10')
-options=("!upx")
+md5sums=('36903fc0f19910870440b68ac4cd22a4')
+options=('!strip' '!upx')
 PKGEXT='.pkg.tar'
 
-_gamepkg="Torchlight-${_hibver}.sh"
+_installer="Torchlight-${_hibver}.sh"
+_installer_md5='eff02cb27a818b4d29e399bc8a293d7f'
 
 
 package() {
   cd $srcdir
 
   # Get installer
-  _get_humblebundle_source "${_gamepkg}" || {
+  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
     error "Unable to find the game archive. Please download it from your Humble
            Bundle page, and place it into one of the above locations."
     exit 1; }
 
-  # Execute installer
+  # Execute installer (it validates its own checksum)
   msg "Starting setup..."
   [[ -d "./temp" ]] && rm -r "./temp"
-  sh "./${_gamepkg}" --unattended --no-register --packager pacman \
-                     --keep --overwrite --accept-license \
-                     --target  "${srcdir}/temp" \
-                     --bindir  "${srcdir}/bin" \
-                     --datadir "${pkgdir}/opt"
+  sh "./${_installer}" --unattended --no-register --packager pacman \
+                       --keep --overwrite --accept-license \
+                       --target  "${srcdir}/temp" \
+                       --bindir  "${srcdir}/bin" \
+                       --datadir "${pkgdir}/opt"
 
   # Remove bundled libraries & helper binaries (use system packages instead)
   rm -rf "${pkgdir}/opt/Torchlight/xdg-"*
@@ -51,10 +52,7 @@ package() {
                  "${pkgdir}/usr/share/pixmaps/torchlight.png"
 
   # Install launcher symlink
-  case $CARCH in
-      i686) _arch=x86;;
-      x86_64) _arch=x86_64;;
-  esac
+  case $CARCH in i686) _arch=x86;; x86_64) _arch=x86_64;; esac
   chmod 755 "${pkgdir}/opt/Torchlight/Torchlight.bin.${_arch}"
   install -d "${pkgdir}/usr/bin"
   ln -s "/opt/Torchlight/Torchlight.bin.${_arch}" "${pkgdir}/usr/bin/torchlight"
@@ -64,23 +62,21 @@ package() {
 }
 
 
-# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
-_get_humblebundle_source() {
-  _get_local_source "$1" || return 1;
-  # TODO: Implement automatic downloading from Humble Bundle site
-}
+###### HELPER FUNCTIONS ######
 
-# Locate a file or folder provided by the user, and symlink it into $srcdir
+# Locates a file or folder provided by the user, and symlinks it into $srcdir
 _get_local_source() {
-  msg "Looking for '$1'..."
+  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
   declare -A _search=(['build dir']="$startdir"
                       ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
   for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
+    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
+    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
+      echo "NOT FOUND"
+    elif [ "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != "$3" ]; then
+      echo "CHECKSUM FAILED";
+    else
       echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-    echo "NOT FOUND"
   done
   if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
