updated on Tue Dec  9 00:00:08 UTC 2014

diff --git a/tlsdate/tlsdate.install b/tlsdate/tlsdate.install
--- a/tlsdate/tlsdate.install
+++ b/tlsdate/tlsdate.install
@@ -1,14 +1,23 @@
 post_install() {
-    useradd -U -r -M -d /var/cache/tlsdated -s /bin/false tlsdate &>/dev/null
-    mkdir var/cache/tlsdated && chown tlsdate:tlsdate var/cache/tlsdated
+    getent passwd tlsdate &>/dev/null || {
+        echo -n ">>> Creating tlsdate system user... "
+        useradd --system --no-create-home \
+                --user-group \
+                --home /var/cache/tlsdated \
+                tlsdate &&
+        echo "ok" || echo "fail"
+    }
+    chown -R tlsdate:tlsdate /var/cache/tlsdated
 }
 
 post_upgrade() {
-    getent passwd tlsdate |grep -q ':/home/tlsdate:' &&
-        usermod -d /var/cache/tlsdated tlsdate
+    chown -R tlsdate:tlsdate /var/cache/tlsdated
 }
 
 pre_remove() {
-    userdel  tlsdate &>/dev/null
-    groupdel tlsdate &>/dev/null
+    getent passwd tlsdate &>/dev/null && {
+        echo -n ">>> Removing tlsdate system user... "
+        userdel tlsdate
+        echo "ok"
+    }
 }
