updated on Wed May  1 08:00:34 UTC 2013

diff --git a/netbeans-php-nightly/PKGBUILD b/netbeans-php-nightly/PKGBUILD
--- a/netbeans-php-nightly/PKGBUILD
+++ b/netbeans-php-nightly/PKGBUILD
@@ -2,7 +2,7 @@
 
 pkgname=netbeans-php-nightly
 pkgver=latest
-pkgrel=1
+pkgrel=2
 pkgdesc="Netbeans IDE for PHP"
 license=('CDDL')
 arch=('any')
@@ -19,47 +19,11 @@ source=('netbeans.desktop')
 md5sums=('4365b0af18717c031c38f422d0ad5466')
 
 
-#extracted from download_sources()
-_download() {
-	local file=$(get_filepath "$1" || true)
-	if [[ -n "$file" ]]; then
-		msg2 "$(gettext "Found %s")" "${file##*/}"
-		rm -f "$srcdir/${file##*/}"
-		ln -s "$file" "$srcdir/"
-		return
-	fi
-
-	local file=$(get_filename "$1")
-	local url=$(get_url "$1")
-
-	# if we get here, check to make sure it was a URL, else fail
-	if [[ $file = $url ]]; then
-		error "$(gettext "%s was not found in the build directory and is not a URL.")" "$file"
-		exit 1 # $E_MISSING_FILE
-	fi
-
-	# find the client we should use for this URL
-	local dlclient
-	dlclient=$(get_downloadclient "$url") || exit $?
-
-	msg2 "$(gettext "Downloading %s...")" "$file"
-	local ret=0
-	download_file "$dlclient" "$url" "$file" || ret=$?
-	if (( ret )); then
-		error "$(gettext "Failure while downloading %s")" "$file"
-		plain "$(gettext "Aborting...")"
-		exit 1
-	fi
-
-	rm -f "$srcdir/$file"
-	ln -s "$SRCDEST/$file" "$srcdir/"
-}
-
 build() {
 	cd "${SRCDEST}"
 
-	_download "${_webroot}/js/build_info.js"
-	_download "${_webroot}/js/files.js"
+	download_file "${_webroot}/js/build_info.js"
+	download_file "${_webroot}/js/files.js"
 
 	_zipname=`grep -e '^build_info\.ZIP_FILES_PREFIX\s' build_info.js \
 			| awk 'BEGIN {FPAT="\".+\""} {gsub(/\"/, "", $NF); print}'`
@@ -67,27 +31,22 @@ build() {
 	_md5=`grep "zip/${_file}" files.js \
 		| awk 'BEGIN {FPAT="\"[0-9a-z]+\""} {gsub(/\"/, "", $NF); print}'`
 
-	_download "${_webroot}/zip/${_file}"
+	download_file "${_webroot}/zip/${_file}"
 
 	cd "${srcdir}"
 
+	msg "$(gettext "Validating source files with %s...")" "md5sums"
+	file="$(get_filename "${_file}")"
+	printf "%s" "    $file ... " >&2
 	local realsum="$(openssl dgst -md5 "${_file}")"
 	if [ "${_md5}" != "${realsum##* }" ]; then
-		error "Invalid checksum of .zip file"
+		printf -- "$(gettext "FAILED")\n" >&2
 		return 1
+	else
+		printf -- "$(gettext "Passed")\n" >&2
 	fi
 
-	local ret=0
-	msg2 "$(gettext "Extracting %s with %s")" "${_file}" "bsdtar"
-	bsdtar -xf "${_file}" || ret=$?
-	if (( ret )); then
-		error "$(gettext "Failed to extract %s")" "${_file}"
-		plain "$(gettext "Aborting...")"
-		exit 1
-	fi
-	if (( EUID == 0 )); then
-		chown -R 0:0 "$srcdir"
-	fi
+	extract_file "${_file}"
 
 	msg2 "cleanup OS specific files"
 	rm $(find -name '*\.exe' -or -name '*\.bat')
