updated on Fri Nov 15 00:18:23 UTC 2013

diff --git a/cqrlog/PKGBUILD b/cqrlog/PKGBUILD
--- a/cqrlog/PKGBUILD
+++ b/cqrlog/PKGBUILD
@@ -2,7 +2,7 @@
 # Maintainer : vic.pozd <vic.pozd at gmail.com>
 
 pkgname=cqrlog
-pkgver=1.6.0
+pkgver=1.6.1
 pkgrel=1
 pkgdesc="An advanced ham radio logger based on MySQL database ( MariaDB replaces MySQL in repositories ). (Binary Version)"
 arch=('i686' 'x86_64')
@@ -23,11 +23,11 @@ depends=('mariadb' 'libmariadbclient' 'mariadb-clients' 'hamlib' 'trustedqsl' 'x
 
 if [ "$CARCH" = "i686" ]; then
     _arch='i386'
-    md5sums=('398d9f629f9c5bf2cd5a8eaa13503b95')
+    md5sums=('5cf16dde176799234d1ead40b3effcbc')
 
   elif [ "$CARCH" = "x86_64" ]; then
     _arch='amd64'
-    md5sums=('b192e06a934434b89471e70002df9542')
+    md5sums=('15ec89fedfd45cb52aeeeffbc2557e14')
 fi
 
 _pkg="${pkgname//_/-}_${pkgver//_/-}_${_arch}"
@@ -35,13 +35,14 @@ source=(${url}/files/${pkgname//_/-}_${pkgver}/${_pkg}.tar.gz)
 
 
 package() {
-    if [ "$CARCH" = "i686" ]; then 
-        cd "$srcdir/$pkgname-$pkgver"
-    elif [ "$CARCH" = "x86_64" ]; then
-        cd "$srcdir/${pkgname}_${pkgver}_${_arch}"
-    else 
-        echo "Error 13"
-        exit 13
-    fi
+#    if [ "$CARCH" = "i686" ]; then 
+#        cd "$srcdir/$pkgname-$pkgver"
+#    elif [ "$CARCH" = "x86_64" ]; then
+#        cd "$srcdir/${pkgname}_${pkgver}_${_arch}"
+#    else 
+#        echo "Error 13"
+#        exit 13
+#    fi
+    cd "$srcdir/${pkgname//_/-}_${pkgver//_/-}_${_arch}"
     cp -rfv ./* $pkgdir
 }
