updated on Wed Sep 11 18:00:45 UTC 2013

diff --git a/cqrlog/PKGBUILD b/cqrlog/PKGBUILD
--- a/cqrlog/PKGBUILD
+++ b/cqrlog/PKGBUILD
@@ -2,7 +2,7 @@
 # Maintainer : vic.pozd <vic.pozd at gmail.com>
 
 pkgname=cqrlog
-pkgver=1.5.8
+pkgver=1.6.0
 pkgrel=1
 pkgdesc="An advanced ham radio logger based on MySQL database ( MariaDB replaces MySQL in repositories ). (Binary Version)"
 arch=('i686' 'x86_64')
@@ -23,11 +23,11 @@ depends=('mariadb' 'libmariadbclient' 'mariadb-clients' 'hamlib' 'trustedqsl' 'x
 
 if [ "$CARCH" = "i686" ]; then
     _arch='i386'
-    md5sums=('e9427bfe3c4db61d91155226ea641fb7')
+    md5sums=('398d9f629f9c5bf2cd5a8eaa13503b95')
 
   elif [ "$CARCH" = "x86_64" ]; then
     _arch='amd64'
-    md5sums=('9e1eb64ba3c1135c9ee42d69fd7543d9')
+    md5sums=('b192e06a934434b89471e70002df9542')
 fi
 
 _pkg="${pkgname//_/-}_${pkgver//_/-}_${_arch}"
@@ -35,6 +35,13 @@ source=(${url}/files/${pkgname//_/-}_${pkgver}/${_pkg}.tar.gz)
 
 
 package() {
-    cd "$srcdir/${pkgname}_${pkgver}_${_arch}"
+    if [ "$CARCH" = "i686" ]; then 
+        cd "$srcdir/$pkgname-$pkgver"
+    elif [ "$CARCH" = "x86_64" ]; then
+        cd "$srcdir/${pkgname}_${pkgver}_${_arch}"
+    else 
+        echo "Error 13"
+        exit 13
+    fi
     cp -rfv ./* $pkgdir
 }
