updated on Fri Apr 22 02:00:50 PDT 2011

diff --git a/trine/PKGBUILD b/trine/PKGBUILD
--- a/trine/PKGBUILD
+++ b/trine/PKGBUILD
@@ -1,84 +1,160 @@
-# Maintainer: jimmy-6 <jakub.jarozek {at} gmail.com>
-# PKGBUILD based on Braid package: https://aur.archlinux.org/packages.php?ID=44429
+# Maintainer & contributor: jimmy-6 <jakub.jarozek {at} gmail.com>
+# Contributor: Babets http://aur.archlinux.org/account.php?Action=AccountInfo&ID=6996
 
 pkgname=trine
-_gamepkg32="Trine.32.run"
-_gamepkg64="Trine.64.run"
 pkgver=1.0.8
-pkgrel=2
+pkgrel=3
 pkgdesc="A physics-based fantasy action game with three playable characters and co-op mode (requires copy of the full game)"
 url="http://trine-thegame.com"
 license=('custom: "commercial"')
 arch=('i686' 'x86_64')
-depends=('mesa' 'libglade' 'libx86')
+depends=('glew' 'libglade' 'nvidia-cg-toolkit' 'openal' 'sdl_image' 'sdl_ttf')
 makedepends=('unzip')
 source=('trine.sh' 'trine-launcher.sh' 'trine.desktop')
-md5sums=('d0f5a14d6a206ef2a267a9548ae99812'
-         'd2ced147e030537339abbaecc0a37ba7'
-         'e35ad9721beb0d5a31003bfacf1ff743')
+install=trine.install
+md5sums=('8c89fe9d00179cfc87754b81e4727a1c'
+         '48c87587ab205c3ebd893fdf219e3241'
+         'c037b9c266c415f2d852eac760fb1e0e')
+
+_gameinst32="Trine-1.32.run"
+_gameinst64="Trine-1.64.run"
+
+[ "${CARCH}" == "i686" ] && _libdir="lib32"
+[ "${CARCH}" == "x86_64" ] && _libdir="lib64"
+
+# uncomment this line if you want uncompressed package
+# PKGEXT=".tar"
 
 build() {
   cd ${srcdir}
+
+  if [[ "${_trine_installer_path}" == "" ]]; then
+    _trine_installer_path=$(readlink -f ".." )
+  fi
+  
+  install -d ${pkgdir}/opt/${pkgname}
   
   msg "You need a full copy of this game in order to install it"
-  msg "Searching for ${_gamepkg32} or ${_gamepkg64} in dir: $(readlink -f `pwd`/..)"
-  if [[ -f "../${_gamepkg32}" ]]; then
+
+  # 32 and 64 bit installers contain files for both architectures
+  # so it doesn't matter which one is used
+  msg "Looking for ${_gameinst64} in: ${_trine_installer_path}"
+  if [[ -f "${_trine_installer_path}/${_gameinst64}" ]]; then
     msg "Found game package, installing..."
-    ln -fs "../${_gamepkg32}" .
-    unzip ${_gamepkg32} || true
-  elif [[ -f "../${_gamepkg64}" ]]; then
-    msg "Found game package, installing..."
-    ln -fs "../${_gamepkg64}" .
-    unzip ${_gamepkg64} || true
-  else
-    error "Game package not found, please type absolute path to ${_gamepkg32} or ${_gamepkg64}:"
-    read pkgpath
-    if [[ -f "${pkgpath}/${_gamepkg32}" ]]; then
-      msg "Found game package, installing..."
-      ln -fs "${pkgpath}/${_gamepkg32}" .
-      unzip ${_gamepkg32} || true
-    elif [[ -f "${pkgpath}/${_gamepkg64}" ]]; then
-      msg "Found game package, installing..."
-      ln -fs "${pkgpath}/${_gamepkg64}" .
-      unzip ${_gamepkg64} || true
-    else
-      error "Unable to find game package."
-      return 1
-    fi
+    unzip -o "${_trine_installer_path}/${_gameinst64}" -d ${pkgdir}/opt/${pkgname} || true
+    return 0
   fi
+  msg "Looking for ${_gameinst32} in: ${_trine_installer_path}"
+  if [[ -f "${_trine_installer_path}/${_gameinst32}" ]]; then
+    msg "Found game package, installing..."
+    unzip -o "${_trine_installer_path}/${_gameinst32}" -d ${pkgdir}/opt/${pkgname} || true
+    return 0
+  fi
+
+  error "Game installer not found!"
+  msg "Please place it in the '${_trine_installer_path}' directory"
+  msg "Or set the '_trine_installer_path' variable to point to correct directory."
+  
+  return 1
 }
 
-package(){
-
-  # directories
-  mkdir -p ${pkgdir}/opt/Trine
-  cd ${srcdir}
-  cp -r binds config data dev profiles ${pkgdir}/opt/Trine/
-  #ensure proper permissions
-  find ${pkgdir}/opt/Trine -type d -exec chmod 755 {} \;
-  find ${pkgdir}/opt/Trine -type f -exec chmod 644 {} \;
-
-  # other data files
-  install -Dm644 data1.fbz data4.fbz trine-launcher.glade trine-logo.png Trine.xpm \
-                 Trine_Manual_linux.pdf Trine_updates.txt ${pkgdir}/opt/Trine/
-  
-  # startup scripts
+package() {
+  # install startup scripts
   install -Dm755 ${srcdir}/trine.sh ${pkgdir}/usr/bin/trine
   install -Dm755 ${srcdir}/trine-launcher.sh ${pkgdir}/usr/bin/trine-launcher
 
-  # execs and libs
-  if [ "${CARCH}" == "x86_64" ]; then
-    cp -r lib64 ${pkgdir}/opt/Trine/
-    chmod -R 755 ${pkgdir}/opt/Trine/lib64
-    install -Dm755 ${srcdir}/trine-bin64 ${pkgdir}/opt/Trine/trine-bin
-    install -Dm755 ${srcdir}/trine-launcher64 ${pkgdir}/opt/Trine/trine-launcher
-  else
-    cp -r lib32 ${pkgdir}/opt/Trine/
-    chmod -R 755 ${pkgdir}/opt/Trine/lib32
-    install -Dm755 ${srcdir}/trine-bin32 ${pkgdir}/opt/Trine/trine-bin
-    install -Dm755 ${srcdir}/trine-launcher32 ${pkgdir}/opt/Trine/trine-launcher
-  fi
-  
-  # desktop icon
+  # install desktop entry
   install -Dm644 ${srcdir}/trine.desktop ${pkgdir}/usr/share/applications/trine.desktop
+
+  # binaries
+  cd "${pkgdir}/opt/${pkgname}"
+  if [[ "${CARCH}" == "x86_64" ]]; then
+    rm -rf lib32 trine-bin32 trine-launcher32
+    mv trine-bin{64,}
+    mv trine-launcher{64,}
+  elif [[ "${CARCH}" == "i686" ]]; then
+    rm -rf lib64 trine-bin64 trine-launcher64
+    mv trine-bin{32,}
+    mv trine-launcher{32,}
+  fi
+
+  #fix file permissions
+  chmod 644 "${pkgdir}/opt/${pkgname}/Trine_Manual_linux.pdf" \
+    "${pkgdir}/opt/${pkgname}/data/video/cinematic/trineroom_thief.ogg"
+
+  #remove bundled libs
+  cd "${pkgdir}/opt/${pkgname}/${_libdir}"
+  rm -f libCgGL.so \
+    libCg.so \
+    libdirect-1.0.so.0 \
+    libdirectfb-1.0.so.0 \
+    libexpat.so.1 \
+    libFLAC.so.8 \
+    libfusion-1.0.so.0 \
+    libgcc_s.so.1 \
+    libgdbm.so.3 \
+    libGLEW.so.1.5 \
+    libgmodule-2.0.so.0 \
+    libgomp.so.1 \
+    libICE.so.6 \
+    libjpeg.so.62 \
+    libmikmod.so.2 \
+    libm.so.6 \
+    libogg.so.0 \
+    libopenal.so.1 \
+    libpcre.so.3 \
+    libpng12.so.0 \
+    librt.so.1 \
+    libSDL-1.2.so.0 \
+    libSDL_image-1.2.so.0 \
+    libSDL_sound-1.0.so.1 \
+    libSDL_ttf-2.0.so.0 \
+    libselinux.so.1 \
+    libsmpeg-0.4.so.0 \
+    libSM.so.6 \
+    libspeex.so.1 \
+    libstdc++.so.6 \
+    libtiff.so.4 \
+    libvga.so.1 \
+    libvorbisfile.so.3 \
+    libvorbis.so.0 \
+    libX11.so.6 \
+    libx86.so.1 \
+    libXau.so.6 \
+    libxcb-render.so.0 \
+    libxcb-render-util.so.0 \
+    libxcb.so.1 \
+    libxcb-xlib.so.0 \
+    libXcomposite.so.1 \
+    libXcursor.so.1 \
+    libXdamage.so.1 \
+    libXdmcp.so.6 \
+    libXext.so.6 \
+    libXfixes.so.3 \
+    libXinerama.so.1 \
+    libXi.so.6 \
+    libXmu.so.6 \
+    libXrender.so.1 \
+    libXt.so.6 \
+    libz.so.1
+
+
+#     libavformat.so.52 \
+#     libboost_filesystem.so.1.35.0 \
+#     libboost_regex.so.1.35.0 \
+#     libboost_system.so.1.35.0 \
+#     libboost_thread-mt.so.1.35.0 \
+#     libcv.so.1 \
+#     libcxcore.so.1 \
+#     libNxCharacter.so \
+#     libNxCooking.so \
+#     libPhysXCore.so \
+#     libPhysXLoader.so.1 \
+#     libavcodec.so.5{2,1} \
+#     libavutil.so.{50,49} \
+#     libswscale.so.0 \
+#     libicudata.so.38 \
+#     libicui18n.so.38 \
+#     libicuuc.so.38 \
+
 }
