updated on Sat Feb 16 20:14:20 UTC 2013

diff --git a/trine/PKGBUILD b/trine/PKGBUILD
--- a/trine/PKGBUILD
+++ b/trine/PKGBUILD
@@ -1,136 +1,115 @@
-# Maintainer: Xiao-Long Chen <chenxiaolong@cxl.epac.to>
+# Contributor: Xiao-Long Chen <chenxiaolong@cxl.epac.to>
 # Contributor: jimmy-6 <jakub.jarozek {at} gmail.com>
 # Contributor: Babets http://aur.archlinux.org/account.php?Action=AccountInfo&ID=6996
+# Maintainer: Eric Anderson <ejona86@gmail.com>
 
 pkgname=trine
 pkgver=1.0.8_update4
-pkgrel=3
-pkgdesc="A physics-based fantasy action game with three playable characters and co-op mode (requires copy of the full game)"
+pkgrel=4
+pkgdesc="A physics-based fantasy action game with three playable characters and co-op mode (game sold separately)"
 url="http://trine-thegame.com"
 license=('custom: "commercial"')
 arch=('i686' 'x86_64')
-depends=('libglade' 'nvidia-cg-toolkit' 'openal' 'sdl_image' 'sdl_ttf' 'libvorbis' 'libx86' 'libxmu' 'libpng12' 'libtxc_dxtn')
+depends=('glu' 'libglade' 'libvorbis' 'libxmu' 'nvidia-cg-toolkit' 'openal'
+         'sdl_image' 'sdl_ttf')
+optdepends=('libtxc_dxtn: texture decoding for open source ATI and Intel drivers')
 makedepends=('unzip')
-source=('trine.sh' 'trine-launcher.sh' 'trine.desktop')
-install=trine.install
-sha512sums=('843629d13ae5ec00e0e195a126fb28783001d59cc81e07bfb636b5136e5892fedd38d3f1e0f0b3b0c8050c4f7b0a74e47e6aaa8f54ccb8e84333f5f3e6048648'
-            '5ffc9d563a39e6c9c89845eea4ebacaea678d2912c94823f88db8a78f86cea97a291caec3b2fd1c478a6b66fa221b43110995b83af5c6e71d22d6c3a6f4f797d'
-            '0b1c010c27e89837ef23af33161d4e2e91ee64efd20ff6196bf5b25c87c48a60ba0f44a2273a3f1170120247e88178cf72436f547a1bd403d370ff6ba786f6cb')
-
-_gameinstallers=('TrineUpdate4.32.run' 'TrineUpdate4.64.run')
-
+# The 32 bit and 64 bit binaries are identitical when unzipped, so it doesn't
+# matter which you use.
+if [ "${CARCH}" = "x86_64" ]; then
+  _gamepkg='TrineUpdate4.64.run'
+  _gamepkgsum='9ca9a755f3586aeda47d650808129948'
+  _archbits=64
+  _rmarchbits=32
+else
+  _gamepkg='TrineUpdate4.32.run'
+  _gamepkgsum='7c84061f9f74052a45d15c35df18d143'
+  _archbits=32
+  _rmarchbits=64
+fi
+source=("${pkgname}.desktop" "hib://${_gamepkg}")
+md5sums=('1c9f699d983521866f936feac81e86c9' "${_gamepkgsum}")
+install="${pkgname}.install"
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download the file manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf"; echo "Read this PKGBUILD for more info."; exit 1')
 PKGEXT=".pkg.tar"
 
-package() {
+build() {
   cd "${srcdir}"
+  unzip "${_gamepkg}" -d "${pkgname}-${pkgver}" || true
+}
 
-  if [[ "${_trineinst}" == "" ]]; then
-    _trineinst="$(readlink -f "..")"
-  fi
-  
-  install -dm755 "${pkgdir}/opt/${pkgname}"
-  
-  msg "You need a full copy of this game in order to install it"
+package() {
+  cd "${srcdir}/${pkgname}-${pkgver}"
 
-  for i in ${_gameinstallers[@]}; do
-    msg "Looking for ${i} in ${_trineinst}"
-    if [ -f "${_trineinst}/${i}" ]; then
-      msg "Found installer: ${i}"
-      #Header contains executable code, so while the file can be unzipped, it will return with an error code 1, hence the "|| true"
-      unzip -o "${_trineinst}/${i}" -d "${pkgdir}/opt/${pkgname}" || true
-      FOUND=true
-      break
-    fi
-  done
+  install -dm755 "${pkgdir}/opt/"
+  cp -Rl . "${pkgdir}/opt/${pkgname}/"
+  chmod 644 "${pkgdir}/opt/${pkgname}/Trine_Manual_linux.pdf" \
+      "${pkgdir}/opt/${pkgname}/data/video/cinematic/trineroom_thief.ogg"
 
-  if [ -z "${FOUND}" ]; then
-    error "Game installer was not found!"
-    msg "Please copy or symlink the installer to: ${_trineinst}"
-    msg "or set the '_trineinst' variable to directory of the installer."
-    return 1
-  fi
-  
-  # install launcher scripts
-  install -Dm755 ${srcdir}/trine.sh ${pkgdir}/usr/bin/trine
-  install -Dm755 ${srcdir}/trine-launcher.sh ${pkgdir}/usr/bin/trine-launcher
-
-  # install desktop entry
-  install -Dm644 ${srcdir}/trine.desktop ${pkgdir}/usr/share/applications/trine.desktop
-
-  # binaries
+  # Cleanup install dir
   cd "${pkgdir}/opt/${pkgname}"
-  if [[ "${CARCH}" == "x86_64" ]]; then
-    rm -rf lib32 trine-bin32 trine-launcher32
-    mv trine-bin{64,}
-    mv trine-launcher{64,}
-  elif [[ "${CARCH}" == "i686" ]]; then
-    rm -rf lib64 trine-bin64 trine-launcher64
-    mv trine-bin{32,}
-    mv trine-launcher{32,}
+  rm removeShortcuts.sh createShortcuts.sh
+  rm -r lib${_rmarchbits} trine-bin${_rmarchbits} trine-launcher${_rmarchbits}
+  mv trine-bin${_archbits} trine-bin
+  mv trine-launcher${_archbits} trine-launcher
+
+  cd "${pkgdir}/opt/${pkgname}/lib${_archbits}"
+  # Process libraries that are in only one architecture
+  if [ "${CARCH}" = "i686" ]; then
+    # In general, all of these are provided by the OS and need to be
+    # dependencies. Exceptions:
+    #   libgdbm.so.3, libselinux.so.1, libxcb-render-util.so.0 aren't linked by
+    #   anything, so they aren't necessary
+    #
+    #   libxcb-xlib.so.0 is an old dependency of libX11. It isn't needed when
+    #   using the system's newer libXll
+    #
+    #   libx86.so.1 is only used by libvga.so.1, which will be removed
+    rm libexpat.so.1 libFLAC.so.8 libgcc_s.so.1 libgdbm.so.3 \
+        libgmodule-2.0.so.0 libgomp.so.1 libICE.so.6 libmikmod.so.2 libm.so.6 \
+        libpcre.so.3 librt.so.1 libSDL_sound-1.0.so.1 libselinux.so.1 \
+        libsmpeg-0.4.so.0 libSM.so.6 libspeex.so.1 libX11.so.6 libx86.so.1 \
+        libXau.so.6 libxcb-render.so.0 libxcb-render-util.so.0 libxcb.so.1 \
+        libxcb-xlib.so.0 libXcomposite.so.1 libXcursor.so.1 libXdamage.so.1 \
+        libXdmcp.so.6 libXext.so.6 libXfixes.so.3 libXinerama.so.1 libXi.so.6 \
+        libXmu.so.6 libXrender.so.1 libXt.so.6 libz.so.1
+  else
+    # libswscale.so.0 is used for 64 bit
+    true # nothing to do
   fi
+  # In general, all of these are provided by the OS and need to be dependencies.
+  # Exceptions:
+  #   libNxCharacter.so isn't linked by anything, so it isn't necessary
+  #
+  #   libdirect-1.0.so.0, libdirectfb-1.0.so.0, libfusion-1.0.so.0, libvga.so.1
+  #   are optional dependencies of libSDL-1.2.so.0. They aren't needed when
+  #   using the systems's libSDL, which doesn't depend on them.
+  #
+  #   libpng12.so.0, libtiff.so.4 are old dependencies of libSDL_image-1.2.so.0.
+  #   They aren't needed when using the system's newer libSDL_image
+  #
+  # libPhysXCore.so, libNxCooking.so appear to be unused when using ldd, but
+  # actually libPhysXLoader.so.1 dlopens them, so they shouldn't be removed.
+  rm libCg.so libCgGL.so libSDL-1.2.so.0 libSDL_image-1.2.so.0 \
+      libSDL_ttf-2.0.so.0 libdirect-1.0.so.0 libdirectfb-1.0.so.0 \
+      libfusion-1.0.so.0 libjpeg.so.62 libNxCharacter.so libogg.so.0 \
+      libopenal.so.1 libpng12.so.0 libstdc++.so.6 libtiff.so.4 libvga.so.1 \
+      libvorbis.so.0 libvorbisfile.so.3
 
-  #fix file permissions
-  chmod 644 "${pkgdir}/opt/${pkgname}/Trine_Manual_linux.pdf" "${pkgdir}/opt/${pkgname}/data/video/cinematic/trineroom_thief.ogg"
+  install -dm755 "${pkgdir}/usr/bin/"
+  ln -s /opt/trine/trine-bin "${pkgdir}/usr/bin/trine"
+  ln -s /opt/trine/trine-launcher "${pkgdir}/usr/bin/trine-launcher"
 
-  #remove unneeded files
-  cd "${pkgdir}/opt/${pkgname}/"
-  rm {remove,create}Shortcuts.sh
-
-  cd "${pkgdir}/opt/${pkgname}/lib"*
-  #Need to keep the following non-system libraries:
-  KEEP=(
-    ## trine-bin
-    #32bit
-    'libavcodec.so.51'
-    'libavformat.so.52'
-    'libavutil.so.49'
-    'libcv.so.1'
-    'libcxcore.so.1'
-    'libboost_thread-mt.so.1.35.0'
-    'libSDL_image-1.2.so.0'
-    'libjpeg.so.62'
-    'libtiff.so.4'
-    'libSDL_ttf-2.0.so.0'
-    'libPhysXLoader.so.1'
-    'libGLEW.so.1.5'
-    'libCg.so'
-    'libCgGL.so'
-    #64bit
-    'libavcodec.so.52'
-    'libavformat.so.52'
-    'libavutil.so.50'
-    'libswscale.so.0'
-    #'libcv.so.1' -> repeated
-    #'libcxcore.so.1 -> repeated
-    #'libboost_thread-mt.so.1.35.0' -> repeated
-    #'libPhysXLoader.so.1 -> repeated
-    #'libGLEW.so.1.5 -> repeated
-
-    ## trine-launcher
-    #32bit
-    'libboost_regex.so.1.35.0'
-    'libicudata.so.38'
-    'libicui18n.so.38'
-    'libicuuc.so.38'
-    'libboost_filesystem.so.1.35.0'
-    'libboost_system.so.1.35.0'
-    #64bit
-    #'libboost_regex.so.1.35.0' -> repeated
-    #'libicudata.so.38' -> repeated
-    #'libicui18n.so.38' -> repeated
-    #'libicuuc.so.38' -> repeated
-    #'libboost_filesystem.so.1.35.0' -> repeated
-    #'libboost_system.so.1.35.0' -> repeated
-
-    ## Game crashes without 'libPhysXCore.so' - Thanks to Dayita for finding this!
-    'libPhysXCore.so'
-    ## And also crashes without 'libNxCooking.so' - Thanks to PostBlue for finding this!
-    'libNxCooking.so'
-  )
-  #Remove the rest
-  for i in *; do
-    if [[ ! "${KEEP[@]}" =~ "${i}" ]]; then
-      rm "${i}"
-    fi
-  done
+  install -Dm644 "${srcdir}/trine.desktop" \
+      "${pkgdir}/usr/share/applications/trine.desktop"
 }
