updated on Tue Aug 16 05:30:59 UTC 2011

diff --git a/linux-ice/PKGBUILD b/linux-ice/PKGBUILD
--- a/linux-ice/PKGBUILD
+++ b/linux-ice/PKGBUILD
@@ -11,7 +11,7 @@ _kernelname=${pkgname#linux}
 _basekernel=3.0
 _minor_patch=1
 pkgver=${_basekernel}
-pkgrel=2
+pkgrel=3
 install=$pkgname.install
 provides=('kernel26-ice')
 conflicts=('kernel26-ice')
@@ -39,7 +39,7 @@ enable_reiser4=${enable_reiser4:-0}
 ### Files / Versions
 file_reiser4="reiser4-for-2.6.38.patch.bz2"
 file_toi="current-tuxonice-for-3.0.patch.bz2"
-file_bfs="2.6.38.3-sched-bfs-401.patch"
+file_bfs="3.0-sched-bfs-406.patch"
 ###
 
 options=(!strip)
@@ -47,7 +47,7 @@ source=(http://kernel.org/pub/linux/kernel/v3.0/linux-${_basekernel}.tar.bz2
         http://www.kernel.org/pub/linux/kernel/v3.0/patch-${_basekernel}.${_minor_patch}.bz2
         # http://www.kernel.org/pub/linux/kernel/people/edward/reiser4/reiser4-for-2.6/${file_reiser4}
         http://www.tuxonice.net/files/${file_toi}
-        # http://ck.kolivas.org/patches/bfs/${_basekernel}/${file_bfs}
+        http://ck.kolivas.org/patches/bfs/3.0.0/${file_bfs}
         # the main kernel config files
         config config.x86_64
         # standard config files for mkinitcpio ramdisk
@@ -56,6 +56,7 @@ source=(http://kernel.org/pub/linux/kernel/v3.0/linux-${_basekernel}.tar.bz2
 md5sums=('398e95866794def22b12dfbc15ce89c0'
          'ac49f7907f1fc85fbab92d0f1aa1552a'
          'afbd01926c57fc5b82ee6034dc9311e5'
+         '0399ec35c4c0998ce423e656094b91ac'
          'c466c85e967fe004455aacd26b89e1fb'
          'e932681c602ba4ddfbbb0fa96c5a7bc5'
          '1d27835b55d02f8cc66507a5ae1a6885'
@@ -94,9 +95,8 @@ build() {
 
   if [ "${bfs_scheduler}" = "1" ]; then
     # applying BFS scheduler patch
-    echo "BFS scheduler patch not available yet, sorry"
-    # echo "Applying BFS scheduler patch"
-    # patch -Np1 -i ${srcdir}/${file_bfs} || { echo "Failed BFS"; return 1 ; }
+     echo "Applying BFS scheduler patch"
+     patch -Np1 -i ${srcdir}/${file_bfs} || { echo "Failed BFS"; return 1 ; }
   fi
 
   # remove extraversion
