updated on Sun Oct  5 00:00:41 UTC 2014

diff --git a/plan9port-hg/PKGBUILD b/plan9port-hg/PKGBUILD
--- a/plan9port-hg/PKGBUILD
+++ b/plan9port-hg/PKGBUILD
@@ -1,44 +1,72 @@
 # Maintainer: Andrew Antle <andrew dot antle at gmail dot com>
 # Contributor: Calvin McAnarney <csm@gmx.us>
 # Contributor: Julien Pecqueur <jpec@julienpecqueur.com>
+# Contributor: Sergiusz Urbaniak <sergiusz.urbaniak@gmail.com>
 
 pkgname=plan9port-hg
-pkgver=3225
+pkgver=r3500.06ddd98c468a
 pkgrel=1
 pkgdesc="port of many Plan 9 programs to Unix-like operating systems"
 arch=('i686' 'x86_64')
 url="http://swtch.com/plan9port/"
 license=('custom')
-depends=('x-server')
+depends=('xorg-server' 'libxt' 'libxext' 'fuse')
+optdepends=('python2: for the codereview script')
 makedepends=('mercurial')
-options=(!zipman)
 provides=('plan9')
+install='plan9.install'
 conflicts=('9base' 'plan9port')
-source=('plan9.sh')
-md5sums=('9695eb15a247e23140e8a35ff52a5c20')
+options=('!zipman' 'staticlibs')
+source=('hg+http://code.swtch.com/plan9port'
+        'plan9.sh')
+md5sums=('SKIP'
+         'c884c3c90a107f1a178718c304c67d30')
 
+package() {
+  cd "$srcdir/plan9port"
 
-_hgroot="http://code.swtch.com"
-_hgrepo="plan9port"
+  # Try the gentoo way for fixing hardcoded paths
+  PLAN9=/usr/lib/plan9
+  grep --null -l -r '/usr/local/plan9' | xargs --null sed -i "s!/usr/local/plan9!${PLAN9}!g"
 
-build() {
-  rm -rf "$srcdir/$_hgrepo-build"
-  cp -r "$srcdir/$_hgrepo" "$srcdir/$_hgrepo-build"
-  cd "$srcdir/$_hgrepo-build"
+  d=usr/lib
 
-  ./INSTALL
+  ./INSTALL -b
+  install -Dm755 ../../plan9.sh "$pkgdir/etc/profile.d/plan9.sh"
+  install -d "$pkgdir/$d"
+  install -d "$pkgdir/usr/share/doc/$pkgname"
+  cp -r "$srcdir/plan9port" "$pkgdir/$d/plan9"
+  cd "$pkgdir/$d/plan9"
+  ./INSTALL -c -r "$pkgdir/$d/plan9"
+  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
 
-  xargs -a lib/moveplan9.files -d\\n sed -i "s#$startdir/src/plan9port-build#/opt/plan9#"
-  rm install.{log,sum}
-  rm -r .hg{,ignore,tags} .cvsignore
+  # Clean up
+  rm -rf .hg/
+  rm -f .hgignore .hgtags
+  find . -name '.cvsignore' -print0 |xargs -0 rm -f
+  rm -f config install.log install.sum install.txt configure Makefile INSTALL \
+    LICENSE
 
-  mkdir $pkgdir/opt
-  cp -r $srcdir/$_hgrepo-build $pkgdir/opt/plan9
-  mkdir -p $pkgdir/etc/profile.d
-  cp $srcdir/plan9.sh $pkgdir/etc/profile.d/
+  # Fix python scripts
+  find "$pkgdir" -name '*.py' -print0 |xargs -0 \
+    sed -i -e 's,^#!/usr/bin/env python$,#!/usr/bin/python2,' \
+    -e 's,^#!/usr/bin/python$,#!/usr/bin/python2,'
 
-  install -m644 -D LICENSE $pkgdir/usr/share/licenses/$pkgname/LICENSE
-  install -m644 -D README $pkgdir/usr/share/doc/$pkgname/README
-  install -m644 -D CHANGES $pkgdir/usr/share/doc/$pkgname/CHANGES
-  install -m644 -D CONTRIBUTORS $pkgdir/usr/share/doc/$pkgname/CONTRIBUTORS
+  # Package text files
+  for i in CHANGES CONTRIBUTORS README TODO; do
+    install -m644 $i "$pkgdir/usr/share/doc/$pkgname"
+    rm -f $i
+  done
+
+  # Decompress the plan9 man pages
+  for i in `find $pkgdir/$d/plan9/man -type f`; do
+    if [ ${i##*.} = "gz" ]; then
+      gunzip "$i"
+    fi
+  done
+
+  # Once more
+  grep --null -l -r "$pkgdir$PLAN9" | xargs --null sed -i "s!$pkgdir$PLAN9!${PLAN9}!g" || true
+  grep --null -l -r "/build/plan9port/pkg/plan9port/$PLAN9" | xargs --null sed -i "s!/build/plan9port/pkg/plan9port/$PLAN9!${PLAN9}!g" || true
 }
+
