updated on Fri Aug 23 00:08:47 UTC 2013

diff --git a/libretro-bsnes-git/PKGBUILD b/libretro-bsnes-git/PKGBUILD
--- a/libretro-bsnes-git/PKGBUILD
+++ b/libretro-bsnes-git/PKGBUILD
@@ -2,7 +2,7 @@
 
 pkgname=libretro-bsnes-git
 _gitname=bsnes
-pkgver=367.fe8bd6b
+pkgver=382.2b89497
 pkgrel=1
 pkgdesc="libretro implementation of bSNES. (Super Nintendo Entertainment System)"
 arch=('i686' 'x86_64' 'arm' 'armv6h')
@@ -22,25 +22,20 @@ build() {
   git clone . perf
   git clone . balanced
    
-if [ -z "${CC}" ]; then
-CC=gcc
-fi
-
 echo "=== Building bSNES performance ==="
-  cd "perf/higan"
-  make compiler="${CC}" ui=target-libretro profile=performance || die "Failed to build bSNES performance core"
+  cd "perf"
+  make ui=target-libretro profile=performance || die "Failed to build bSNES performance core"
   cp -f "out/bsnes_libretro.so" "${srcdir}/${_gitname}/libretro-bsnes-performance.so"
   cd "${srcdir}/${_gitname}"
 
 echo "=== Building bSNES balanced ==="
-  cd "balanced/higan"
-  make compiler="${CC}" ui=target-libretro profile=balanced || die "Failed to build bSNES compatibility core"
+  cd "balanced"
+  make ui=target-libretro profile=balanced || die "Failed to build bSNES compatibility core"
   cp -f "out/bsnes_libretro.so" "${srcdir}/${_gitname}/libretro-bsnes-balanced.so"
   cd "${srcdir}/${_gitname}"
 
 echo "=== Building bSNES accuracy ==="
-  cd "higan"
-  make compiler="${CC}" ui=target-libretro profile=accuracy || die "Failed to build bSNES accuracy core"
+  make ui=target-libretro profile=accuracy || die "Failed to build bSNES accuracy core"
   cp -f "out/bsnes_libretro.so" "${srcdir}/${_gitname}/libretro-bsnes-accuracy.so"
   cd "${srcdir}/${_gitname}"
 }
