updated on Sat Apr 28 15:00:16 UTC 2012

diff --git a/libretro-bsnes-git/PKGBUILD b/libretro-bsnes-git/PKGBUILD
--- a/libretro-bsnes-git/PKGBUILD
+++ b/libretro-bsnes-git/PKGBUILD
@@ -1,82 +1,83 @@
 # Maintainer: almostalive <almostalive2003 at gmail dot com>
 
 pkgname=libretro-bsnes-git
-pkgver=20120416
+pkgver=20120428
 pkgrel=1
 pkgdesc="libretro implementation of bsnes."
 arch=('i686' 'x86_64')
-url="https://github.com/Themaister/bsnes-libretro"
+url="http://gitorious.org/bsnes"
 license=('custom')
 makedepends=('git')
 conflicts=('libretro-super-git')
-source=('remove-O3.patch')
-md5sums=('855f94434659f9dd4c4efde6375b5136')
-
-_gitroot="git://github.com/Themaister/bsnes-libretro.git"
-_gitname="bsnes-libretro"
+source=('fixpref.patch')
+md5sums=('826df8081f76c587c32aa5d7099a2841')
 
 build() 
 {
    cd $srcdir
 
-   echo "=== Fetching libretro/bSNES ==="
-   if [ -d libretro-bsnes ]; then
-      cd libretro-bsnes
+ echo "=== Fetching libretro/bSNES ==="
+   if [ -d "libretro-bsnes" ]; then
+cd "libretro-bsnes"
       git pull
       cd ..
    else
-      git clone git://github.com/Themaister/bsnes-libretro.git libretro-bsnes
+git clone git://gitorious.org/bsnes/bsnes.git --branch libretro "libretro-bsnes"
    fi
 
-   if [ -d libretro-bsnes ]; then
-      cd libretro-bsnes
+if [ -d "libretro-bsnes" ]; then
+cd "libretro-bsnes"
 
       if [ -d "perf" ]; then
-         cd perf
+cd perf
          git pull ..
          cd ..
       else
-         git clone . perf
+git clone . perf
       fi
 
-      if [ -d "compat" ]; then
-         cd perf
+if [ -d "compat" ]; then
+cd perf
          git pull ..
          cd ..
       else
-         git clone . compat
+git clone . compat
       fi
 
-      cd ..
+cd ..
    fi
 
-   if [ -d "libretro-bsnes/perf" ]; then
-      echo "=== Building bSNES performance ==="
-      cd libretro-bsnes/perf
-      #patch  -p1 -i $srcdir/remove-O3.patch
-      make profile=performance -j4 || die "Failed to build bSNES performance core"
-      cp -f out/libretro.so ../libretro-bsnes-performance.so
-      cd ../..
+if [ -z "$CC" ]; then
+CC=gcc
+   fi
+
+if [ -d "libretro-bsnes/perf" ]; then
+echo "=== Building bSNES performance ==="
+      cd libretro-bsnes/perf/bsnes
+      patch -p1 -i $srcdir/fixpref.patch Makefile
+      make compiler="$CC" ui=target-libretro profile=performance -j4 || die "Failed to build bSNES performance core"
+      cp -f out/libretro.so ../../libretro-bsnes-performance.so
+      cd ../../..
    else
-      echo "bSNES performance not fetched, skipping ..."
+echo "bSNES performance not fetched, skipping ..."
    fi
 
-   if [ -d "libretro-bsnes/compat" ]; then
-      echo "=== Building bSNES compatibility ==="
-      cd libretro-bsnes/compat
-      make profile=compatibility -j4 || die "Failed to build bSNES compatibility core"
-      cp -f out/libretro.so ../libretro-bsnes-compat.so
-      cd ../..
+if [ -d "libretro-bsnes/compat" ]; then
+echo "=== Building bSNES compatibility ==="
+      cd libretro-bsnes/compat/bsnes
+      make compiler="$CC" ui=target-libretro profile=compatibility -j4 || die "Failed to build bSNES compatibility core"
+      cp -f out/libretro.so ../../libretro-bsnes-compat.so
+      cd ../../..
    else
-      echo "bSNES compat not fetched, skipping ..."
+echo "bSNES compat not fetched, skipping ..."
    fi
 
-   if [ -d "libretro-bsnes" ]; then
-      echo "=== Building bSNES accuracy ==="
-      cd libretro-bsnes
-      make profile=accuracy -j4 || die "Failed to build bSNES accuracy core"
-      cp -f out/libretro.so libretro-bsnes-accuracy.so
-      cd ..
+if [ -d "libretro-bsnes" ]; then
+echo "=== Building bSNES accuracy ==="
+      cd libretro-bsnes/bsnes
+      make compiler="$CC" ui=target-libretro profile=accuracy -j4 || die "Failed to build bSNES accuracy core"
+      cp -f out/libretro.so ../libretro-bsnes-accuracy.so
+      cd ../..
    fi
 }
 
