updated on Tue May 21 02:14:24 UTC 2013

diff --git a/libretro-bsnes-git/PKGBUILD b/libretro-bsnes-git/PKGBUILD
--- a/libretro-bsnes-git/PKGBUILD
+++ b/libretro-bsnes-git/PKGBUILD
@@ -2,9 +2,9 @@
 
 pkgname=libretro-bsnes-git
 _gitname=bsnes
-pkgver=2013.03.16_7a72d4a
+pkgver=2013.05.19_3d1e4f6
 pkgrel=1
-pkgdesc="libretro implementation of bsnes. (Super Nintendo Entertainment System)"
+pkgdesc="libretro implementation of bSNES. (Super Nintendo Entertainment System)"
 arch=('i686' 'x86_64' 'arm' 'armv6h')
 url="http://gitorious.org/bsnes"
 license=('custom')
@@ -20,37 +20,37 @@ pkgver() {
 
 build() {
   cd $_gitname
-   git clone . perf
-   git clone . balanced
-    cd $srcdir/$_gitname
+  git clone . perf
+  git clone . balanced
+  cd $srcdir/$_gitname
    
 if [ -z "$CC" ]; then
 CC=gcc
-   fi
+fi
 
-      cd $srcdir/$_gitname/perf/higan
-      make compiler="$CC" ui=target-libretro profile=performance -j4 || die "Failed to build bSNES performance core"
-      cp -f out/libretro.so $srcdir/$_gitname/libretro-bsnes-performance.so
-      cd $srcdir/$_gitname
+  cd $srcdir/$_gitname/perf/higan
+  make compiler="$CC" ui=target-libretro profile=performance -j4 || die "Failed to build bSNES performance core"
+  cp -f out/bsnes_libretro.so $srcdir/$_gitname/libretro-bsnes-performance.so
+  cd $srcdir/$_gitname
 
 echo "=== Building bSNES balanced ==="
-      cd $srcdir/$_gitname/balanced/higan
-      make compiler="$CC" ui=target-libretro profile=balanced -j4 || die "Failed to build bSNES compatibility core"
-      cp -f out/libretro.so $srcdir/$_gitname/libretro-bsnes-balanced.so
-      cd $srcdir/$_gitname
+  cd $srcdir/$_gitname/balanced/higan
+  make compiler="$CC" ui=target-libretro profile=balanced -j4 || die "Failed to build bSNES compatibility core"
+  cp -f out/bsnes_libretro.so $srcdir/$_gitname/libretro-bsnes-balanced.so
+  cd $srcdir/$_gitname
 
 echo "=== Building bSNES accuracy ==="
-      cd $srcdir/$_gitname/higan
-      make compiler="$CC" ui=target-libretro profile=accuracy -j4 || die "Failed to build bSNES accuracy core"
-      cp -f out/libretro.so $srcdir/$_gitname/libretro-bsnes-accuracy.so
-      cd $srcdir/$_gitname
+  cd $srcdir/$_gitname/higan
+  make compiler="$CC" ui=target-libretro profile=accuracy -j4 || die "Failed to build bSNES accuracy core"
+  cp -f out/bsnes_libretro.so $srcdir/$_gitname/libretro-bsnes-accuracy.so
+  cd $srcdir/$_gitname
 
 }
 
 package()
 {
-   mkdir -p $pkgdir/usr/lib/libretro
-   install -v -m644 $_gitname/libretro-bsnes-performance.so $pkgdir/usr/lib/libretro/libretro-bsnes-performance.so
-   install -v -m644 $_gitname/libretro-bsnes-balanced.so $pkgdir/usr/lib/libretro/libretro-bsnes-balanced.so
-   install -v -m644 $_gitname/libretro-bsnes-accuracy.so $pkgdir/usr/lib/libretro/libretro-bsnes-accuracy.so
+  mkdir -p $pkgdir/usr/lib/libretro
+  install -v -m644 $_gitname/libretro-bsnes-performance.so $pkgdir/usr/lib/libretro/libretro-bsnes-performance.so
+  install -v -m644 $_gitname/libretro-bsnes-balanced.so $pkgdir/usr/lib/libretro/libretro-bsnes-balanced.so
+  install -v -m644 $_gitname/libretro-bsnes-accuracy.so $pkgdir/usr/lib/libretro/libretro-bsnes-accuracy.so
 }
