updated on Mon Aug 19 02:21:28 UTC 2013

diff --git a/libretro-bsnes-git/PKGBUILD b/libretro-bsnes-git/PKGBUILD
--- a/libretro-bsnes-git/PKGBUILD
+++ b/libretro-bsnes-git/PKGBUILD
@@ -1,55 +1,52 @@
-# Maintainer: almostalive <almostalive2003 at lavabit dot com>
+# Maintainer: almostalive <almostalive2003 at gmail dot com>
 
 pkgname=libretro-bsnes-git
 _gitname=bsnes
-pkgver=2013.06.03_e6e5bf4
+pkgver=367.fe8bd6b
 pkgrel=1
 pkgdesc="libretro implementation of bSNES. (Super Nintendo Entertainment System)"
 arch=('i686' 'x86_64' 'arm' 'armv6h')
 url="http://gitorious.org/bsnes"
-license=('custom')
+license=('GPL3')
 makedepends=('git')
-source=('git://gitorious.org/bsnes/bsnes.git#branch=libretro')
+source=("${_gitname}::git://gitorious.org/bsnes/${_gitname}.git#branch=libretro")
 md5sums=('SKIP')
 
 pkgver() {
-  cd $_gitname
-  echo "$(git log -1 --format="%cd" --date=short | sed 's|-|.|g')_$(git describe --always | sed 's/-/_/g')"
+  cd "${_gitname}"
+  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
 }
 
 build() {
-  cd $_gitname
+  cd "${_gitname}"
   git clone . perf
   git clone . balanced
-  cd $srcdir/$_gitname
    
-if [ -z "$CC" ]; then
+if [ -z "${CC}" ]; then
 CC=gcc
 fi
 
-  cd $srcdir/$_gitname/perf/higan
-  make compiler="$CC" ui=target-libretro profile=performance -j4 || die "Failed to build bSNES performance core"
-  cp -f out/bsnes_libretro.so $srcdir/$_gitname/libretro-bsnes-performance.so
-  cd $srcdir/$_gitname
+echo "=== Building bSNES performance ==="
+  cd "perf/higan"
+  make compiler="${CC}" ui=target-libretro profile=performance || die "Failed to build bSNES performance core"
+  cp -f "out/bsnes_libretro.so" "${srcdir}/${_gitname}/libretro-bsnes-performance.so"
+  cd "${srcdir}/${_gitname}"
 
 echo "=== Building bSNES balanced ==="
-  cd $srcdir/$_gitname/balanced/higan
-  make compiler="$CC" ui=target-libretro profile=balanced -j4 || die "Failed to build bSNES compatibility core"
-  cp -f out/bsnes_libretro.so $srcdir/$_gitname/libretro-bsnes-balanced.so
-  cd $srcdir/$_gitname
+  cd "balanced/higan"
+  make compiler="${CC}" ui=target-libretro profile=balanced || die "Failed to build bSNES compatibility core"
+  cp -f "out/bsnes_libretro.so" "${srcdir}/${_gitname}/libretro-bsnes-balanced.so"
+  cd "${srcdir}/${_gitname}"
 
 echo "=== Building bSNES accuracy ==="
-  cd $srcdir/$_gitname/higan
-  make compiler="$CC" ui=target-libretro profile=accuracy -j4 || die "Failed to build bSNES accuracy core"
-  cp -f out/bsnes_libretro.so $srcdir/$_gitname/libretro-bsnes-accuracy.so
-  cd $srcdir/$_gitname
-
+  cd "higan"
+  make compiler="${CC}" ui=target-libretro profile=accuracy || die "Failed to build bSNES accuracy core"
+  cp -f "out/bsnes_libretro.so" "${srcdir}/${_gitname}/libretro-bsnes-accuracy.so"
+  cd "${srcdir}/${_gitname}"
 }
 
-package()
-{
-  mkdir -p $pkgdir/usr/lib/libretro
-  install -v -m644 $_gitname/libretro-bsnes-performance.so $pkgdir/usr/lib/libretro/libretro-bsnes-performance.so
-  install -v -m644 $_gitname/libretro-bsnes-balanced.so $pkgdir/usr/lib/libretro/libretro-bsnes-balanced.so
-  install -v -m644 $_gitname/libretro-bsnes-accuracy.so $pkgdir/usr/lib/libretro/libretro-bsnes-accuracy.so
+package() {
+  install -Dm644 "${_gitname}/libretro-bsnes-performance.so" "${pkgdir}/usr/lib/libretro/libretro-bsnes-performance.so"
+  install -Dm644 "${_gitname}/libretro-bsnes-balanced.so" "${pkgdir}/usr/lib/libretro/libretro-bsnes-balanced.so"
+  install -Dm644 "${_gitname}/libretro-bsnes-accuracy.so" "${pkgdir}/usr/lib/libretro/libretro-bsnes-accuracy.so"
 }
