updated on Thu Feb  9 01:10:04 UTC 2012

diff --git a/openvswitch/openvswitch.install b/openvswitch/openvswitch.install
--- a/openvswitch/openvswitch.install
+++ b/openvswitch/openvswitch.install
@@ -1,3 +1,16 @@
+ovs_dkms() {
+  echo "==> Building kernel modules with dkms"
+  dkms add -m openvswitch -v ${1%-*}
+  dkms build -m openvswitch -v ${1%-*}
+  dkms install -m openvswitch -v ${1%-*}
+  echo
+  echo " -> WARNING: If you will use the bridged compatibility don't forget to blacklist the 'bridge' module!"
+  echo " -> To build the modules for other kernels, use 'dkms install -m openvswitch -v ${1%-*}'"
+  echo "    For more information refer to:"
+  echo "    http://openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=blob;f=INSTALL.bridge;hb=HEAD"
+  echo "==> Done"
+}
+
 
 pre_install() {
   groupadd -r ovs
@@ -8,16 +21,26 @@ post_install() {
     ovsdb-tool create /etc/openvswitch/ovs-vswitchd.conf.db /usr/share/openvswitch/vswitch.ovsschema
   fi
 
-  dkms add -m openvswitch -v ${1%-*}
-  dkms build -m openvswitch -v ${1%-*}
+  ovs_dkms $1
 }
 
+pre_upgrade() {
+  echo "==> Removing a possible previous version of openvswitch kernel modules"
+  echo "    If this fails then that's ok"
+  dkms remove -m openvswitch -v ${2%-*} --all || true
+}
+
+post_upgrade() {
+  ovs_dkms $1
+}
+
+
 pre_remove() {
-  dkms remove -m openvswitch -v ${1%-*} --all
+  dkms remove -m openvswitch -v ${1%-*} --all || true
 }
 
 post_remove() {
-  groupdel ovs
+  groupdel ovs || true
 }
 
 # vim:set ts=2 sw=2 et:
