updated on Sat Jun  9 13:00:14 UTC 2012

diff --git a/openvswitch/openvswitch.install b/openvswitch/openvswitch.install
--- a/openvswitch/openvswitch.install
+++ b/openvswitch/openvswitch.install
@@ -1,16 +1,21 @@
 ovs_dkms() {
-  set -v
-  echo "==> Building kernel modules with dkms"
-  dkms add -m openvswitch -v ${1%-*}
-  dkms build -m openvswitch -v ${1%-*}
-  dkms install -m openvswitch -v ${1%-*}
-  echo
-  echo " -> WARNING: If you will use the bridged compatibility don't forget to blacklist the 'bridge' module!"
-  echo " -> To build the modules for other kernels, use 'dkms install -m openvswitch -v ${1%-*}'"
-  echo "    For more information refer to:"
-  echo "    http://openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=blob;f=INSTALL.bridge;hb=HEAD"
-  echo "==> Done"
-  set +v
+  echo ""
+  echo "********************************"
+  echo "*** ATTENTION RE OPENVSWITCH ***"
+  echo "********************************"
+  echo "The openvswitch modules are a part of the Linux kernel since kernel version 3.3. This means it"
+  echo "is no longer necessary to use dkms in order to build the kernel module."
+  echo "Consequently the openvswitch kernel modules will no longer be built after install/upgrade."
+  echo ""
+  echo "HOWEVER: you can still choose to install the module version that is supplied by this version"
+  echo "of the openvswitch package. To build those you can now use the init script."
+  echo "Refer to '/etc/rc.d/openvswitch help' for info."
+  echo "If you need brcompat also please see the new file /etc/conf.d/openvswitch."
+  echo ""
+  echo "WARNING: any openvswitch module that has been built by dkms will still be removed"
+  echo "when the package is removed."
+  echo "********************************"
+  echo ""
 }
 
 
@@ -28,22 +33,28 @@ post_install() {
 
 pre_upgrade() {
   if [[ -n $2 ]]; then
-    echo "==> Pre_upgrade: removing a possible previous version of openvswitch kernel modules"
-    echo "    If this fails then that's ok"
-    set -v
-    dkms remove --all openvswitch/${2%-*} || true
-    set +v
+    if [[ -x /usr/sbin/dkms ]]; then
+      echo "==> Pre_upgrade: removing a possible previous version of openvswitch kernel modules if"
+      echo "    built by DKMS. If this fails then that's ok."
+      set -v
+      dkms remove --all openvswitch/${2%-*} || true
+      set +v
+    else
+      return 0
+    fi
   fi
 }
 
 post_upgrade() {
   if [[ -n $2 ]]; then
-    echo "==> post_upgrade: removing a possible previous version of openvswitch kernel modules"
-    echo "    If this fails then that's ok"
-    set -v
-    dkms remove --all openvswitch/${2%-*} || true
-    set +v
-    echo
+    if [[ -x /usr/sbin/dkms ]]; then
+      echo "==> Post_upgrade: removing a possible previous version of openvswitch kernel modules if"
+      echo "    built by DKMS. If this fails then that's ok."
+      set -v
+      dkms remove --all openvswitch/${2%-*} || true
+      set +v
+      echo
+    fi
   fi
   ovs_dkms $1
 }
@@ -51,7 +62,7 @@ post_upgrade() {
 
 pre_remove() {
   set -v
-  dkms remove --all openvswitch/${1%-*} --all || true
+  [[ -x /usr/sbin/dkms ]] && dkms remove --all openvswitch/${1%-*} --all || true
   set +v
 }
 
diff --git a/supermeatboy/PKGBUILD b/supermeatboy/PKGBUILD
--- a/supermeatboy/PKGBUILD
+++ b/supermeatboy/PKGBUILD
@@ -1,66 +1,65 @@
-# Maintainer: Yochai Gal <yochaigal@gmail.com>
+# Maintainer: zendeavor <j.s.mcgee115@gmail.com>
+# Contributor: Yochai Gal <yochaigal@gmail.com>
+
 pkgname=supermeatboy
 pkgver=20120607
 _pkgver=06072012
-pkgrel=4
-pkgdesc="Super Meat Boy is a tough as nails platformer where you play as an animated cube of meat."
-arch=('i686' 'x86_64')
+pkgrel=7
+pkgdesc="Super Meat Boy is a game where you play as a boy without skin whose girlfriend who is made of bandages gets kidnapped by a fetus in a tuxedo wearing a top hat and a monocle."
 url="http://www.supermeatboy.com/"
 license=('custom')
+arch=('i686' 'x86_64')
+groups=("humble-indie-bundleV" "humble-indie-bundle4" "games")
 depends=('openal' 'sdl')
-makedepends=('unzip' 'tar')
-source=('supermeatboy.desktop')
-md5sums=('ceda8cdca2aaff63a9cae2ef7d7cf0d4')
-PKGEXT='.pkg.tar'
+makedepends=('unzip' 'curl')
+source=("${pkgname}-linux-${_pkgver}-bin"  "supermeatboy.desktop" "supermeatboy.sh")
+md5sums=("90a563ff103b4610b41af5fd2bccb21a"
+        "ceda8cdca2aaff63a9cae2ef7d7cf0d4"
+        "c59565efc66ed594b40da786c7c58609")
+PKGEXT=".pkg.tar"
 
-_archive_md5="90a563ff103b4610b41af5fd2bccb21a"
-_archive="supermeatboy-linux-${_pkgver}-bin"
+_humblebundle() {
+  _archive="${source[0]%%:*}"
+  for group in "${groups[@]}"; do
+              
+    case "${group}" in 
+      "humble-indie-bundle"*) _key="_humblebundle${group:19}key" ;;
+      *) continue ;;
+    esac
 
-build() {
-  cd ${srcdir}
-
-if [ ! -f ${smbarchivelocation}${_archive} ]; then
-    if [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-    rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-    wget http://www.humblebundle.com/?key=${_humblebundle4key}
-    wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-    mv ${_archive}* ${_archive}
-          elif [ ! -f ${_archive} ] && [ -n "${_humblebundleVkey}" ]; then
-                rm -f ${_archive}* index.html\?key\=${_humblebundleVkey}*
-                wget http://www.humblebundle.com/?key=${_humblebundleVkey}
-                wget $(cat index.html\?key\=${_humblebundleVkey} | grep "${_archive}" | cut -d "'" -f 10)
-                mv ${_archive}* ${_archive}
-    elif [ -z "${_humblebundle4key}" ] && [ -z "${_humblebundleVkey}" ]; then
-    echo You can now automate the download of the archive using the _humblebundle4key or _humblebundleVkey bash variables.
-    echo Just add \'export _humblebundle4key\=\<Your key here\>\' and/or
-    echo \'export _humblebundleVkey\=\<Your key here\>\' to \.bashrc
-    echo
-    echo Otherwise please just place ${_archive} into $(pwd)/
-    echo Press Enter to continue
-    read -a _unused
-    fi
-fi
-
-
-  if [ ! -f ${_smbarchivelocation}${_archive} ]; then
-    echo "${_smbarchivelocation}${_archive} not found!"
-    return 1
-  fi  
-
-  if ! echo "${_archive_md5}  ${_smbarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_smbarchivelocation}${_archive}"
-    return 1
+  if [[ -n "${!_key}" ]]; then
+    _uri="$(curl -s http://www.humblebundle.com/downloads?key="${!_key}" \
+      | grep "${_archive}")"
+    _uri="${_uri##*data-web\=\'}"
+    _uri="${_uri%%\'*}"
+    source[0]="${_archive}::${_uri}"
+    break
+  else
+    warning "Please export _humblebundle4key or _humblebundleVkey for downloading"
+    echo "Alternatively, place the download into ${startdir} and retry"
   fi
 
-  rm -Rf ${srcdir}/smb/
-  unzip -d ${srcdir}/smb/ ${_smbarchivelocation}${_archive} || true
+  done
 
-  mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/share/applications/ \
-    ${pkgdir}/usr/bin/
-  cp -Tr ${srcdir}/smb/data ${pkgdir}/opt/supermeatboy/
-  ln -s /opt/supermeatboy/SuperMeatBoy ${pkgdir}/usr/bin/supermeatboy
-  cp ${srcdir}/supermeatboy.desktop ${pkgdir}/usr/share/applications/
-  chmod a+r ${pkgdir}/usr/share/applications/supermeatboy.desktop
+  if [[ -z "${!_key}" && -f "${startdir}/${_archive}" ]]; then
+    error "Failed to download \"${_archive}\"."
+    exit 1
+  fi
+  unset _archive _key _uri 
 }
 
-# vim: sts=2 ts=2 sw=2 et
+package() {
+  mkdir -p "${pkgdir}"/opt/supermeatboy
+  unzip -u "${source[0]%%:*}" -d "${pkgdir}"/opt/supermeatboy || true
+  find "${pkgdir}" -type f -exec chmod 644 {} +
+  install -Dm644 supermeatboy.desktop "${pkgdir}"/usr/share/applications/supermeatboy.desktop
+  install -Dm755 supermeatboy.sh "${pkgdir}"/usr/bin/supermeatboy
+  chmod 755 "${pkgdir}"/opt/supermeatboy/data/SuperMeatBoy \
+    "${pkgdir}"/opt/supermeatboy/data/amd64/SuperMeatBoy-amd64 \
+    "${pkgdir}"/opt/supermeatboy/data/x86/SuperMeatBoy-x86
+}
+
+_humblebundle
+
+# vim: ft=PKGBUILD sts=2 ts=2 sw=2 et
+
