updated on Wed Mar 23 08:01:10 PDT 2011

diff --git a/spinach/spinach b/spinach/spinach
--- a/spinach/spinach
+++ b/spinach/spinach
@@ -1,6 +1,6 @@
 #!/bin/bash
 UA="Spinach"
-VE="0.3.8"
+VE="0.3.9"
 ssl='';col='';nc=''
 AURURL="http%s://aur.archlinux.org"
 AURPC="$AURURL/rpc.php?type=%s&arg=%s"
@@ -214,18 +214,23 @@ aur_run_install() {
 	if [ "$response" == "y" ]; then
 		makepkg -src
 		#install
-		pkg=*.pkg.tar.xz
 		[ -n "$1" ] && asdep="--asdeps" || asdep=""
-		pacman_run $asdep -U $pkg
+		#ask if the user wants try again on fail
+		while true; do
+			if ! pacman_run $asdep '-U *.pkg.tar.xz'; then
+				ask_yes_no "Try again?"
+				[ "$response" == "n" ] && break
+			fi
+		done
 		#copy to cache
-		mv $pkg "../../cache" &>/dev/null
+		mv *.pkg.tar.xz "../../cache" &>/dev/null
 	fi
 	#clean
 	rm -rf "$pwd/" &>/dev/null
 }
 aur_create_tmp() {
 	if [ -z "$SPINTMPDIR" ]; then
-		[ -n "$TMPDIR" ] && SPINTMPDIR="$TMPDIR" && SPINTMPDIR="/tmp"
+		[ -n "$TMPDIR" ] && SPINTMPDIR="$TMPDIR" || SPINTMPDIR="/tmp"
 	fi
 	tmp="$SPINTMPDIR/spinach"
 	if ! mkdir -p "$tmp" "$tmp/cache" "$tmp/build" &>/dev/null; then
@@ -261,10 +266,10 @@ ask_yes_no() {
 }
 pacman_run() {
 	if type sudo &>/dev/null; then
-		aur_message "Running" "sudo pacman $@"
+		aur_message "Running" "sudo pacman "$@
 		sudo pacman $@
 	else
-		aur_message "Running" "su -c 'pacman $@"
+		aur_message "Running" "su -c pacman "$@
 		su -c "pacman $@"
 	fi
 	
