updated on Sun Mar 20 00:00:50 PDT 2011

diff --git a/spinach/spinach b/spinach/spinach
--- a/spinach/spinach
+++ b/spinach/spinach
@@ -1,5 +1,5 @@
 #!/bin/bash
-UA="Spinach/0.2.6"
+UA="Spinach/0.2.7"
 ssl='';col='';nc=''
 AURURL="http%s://aur.archlinux.org"
 AURPC="$AURURL/rpc.php?type=%s&arg=%s"
@@ -141,6 +141,45 @@ aur_download_updates() {
 		aur_download "$i"
 	done
 }
+aur_auto_install() {
+	if [ -z "$EDITOR" ]; then
+		echo -e "${col}Error:${nc} set \$EDITOR (e.g. EDITOR=vim spinach -a)"
+		return 1
+	fi
+	
+	tmp="$(mktemp -d --suffix=_spinach)"
+	trap "rm -rf \"$tmp\"" 2 15
+	
+	cd "$tmp"
+	aur_download_updates
+
+	for i in */; do
+		if [ -e "$i/PKGBUILD" ]; then
+			cd "$i"
+			echo -n "y/n: View ${i:0:-1}? "
+			read response
+			
+			if [ "$response" == "y" ]; then
+				$EDITOR PKGBUILD
+				
+				if [ -e *.install ]; then
+					$EDITOR *.install
+				fi
+				
+				echo -n "y/n: Install? "
+				read response
+
+				if [ "$response" == "y" ]; then
+					makepkg -sirc
+				fi
+			fi
+			
+			cd ..
+		fi
+	done
+	
+	rm -r "$tmp" &>/dev/null
+}
 aur_spinach_help() {
 	echo -e "${col}Usage${nc}: spinach [options] [operations] [package]
 	Options:
@@ -154,7 +193,8 @@ aur_spinach_help() {
 	-i	Print info for a package
 	-s	Search for a package
 	-u	List out-of-date packages
-	-du	Download all updates"
+	-du	Download all updates
+	-a	Auto upgrade (need \$EDITOR)"
 }
 blank_arg() {
 	if [ -z "$1" ]; then
@@ -167,6 +207,7 @@ while [ -n "$1" ]; do
 	case "$1" in
 		"-u") aur_update;;
 		"-du") aur_download_updates;;
+		"-a") aur_auto_install;;
 		"-i") shift; blank_arg "$1"; aur_info "$1";;
 		"-s") shift; blank_arg "$1"; aur_search "$1";;
 		"-d") shift; blank_arg "$1"; aur_download "$1";;
