updated on Sat Jun  8 22:21:34 UTC 2013

diff --git a/rochard-hib/PKGBUILD b/rochard-hib/PKGBUILD
--- a/rochard-hib/PKGBUILD
+++ b/rochard-hib/PKGBUILD
@@ -8,40 +8,28 @@ pkgdesc='A science fiction platformer game (Humble Bundle version)'
 url='http://www.rochardthegame.com'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
-depends=('mesa' 'libxext' 'libxdmcp')
-source=('rochard-hib.desktop'
-        'rochard.png::http://www.humblebundle.com/static/hashed/8975a4ad5f062b8981f21097c18b789cdd74da05.png')
-md5sums=('78d57546174aedb43d0d7cbcbaf8e073'
-         'ea3e77cba6897af7a7228421ddebc2b8')
+depends=('mesa' 'libgl' 'glu' 'libxext' 'libxdmcp')
 options=("!upx")
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 case $CARCH in
-    i686)   _arch=32; _archive_md5='34cd4c1ecd1fa28b7a4929e13debe8ec'
-                      _archive_subdir="Rochard_x86" ;;
-    x86_64) _arch=64; _archive_md5='bc1497f4f04ddb2dbfc6153aaa0d31aa'
-                      _archive_subdir="Rochard_x64" ;;
+    i686)   _arch=32; _archive_md5='34cd4c1ecd1fa28b7a4929e13debe8ec' ;;
+    x86_64) _arch=64; _archive_md5='bc1497f4f04ddb2dbfc6153aaa0d31aa' ;;
 esac
-_archive="rochard-linux-${_hibver}-${_arch}bit.tar.gz"
+source=("hib://rochard-linux-${_hibver}-${_arch}bit.tar.gz"
+        'rochard.png::http://www.humblebundle.com/static/hashed/8975a4ad5f062b8981f21097c18b789cdd74da05.png'
+        'rochard-hib.desktop')
+md5sums=("$_archive_md5"
+         'ea3e77cba6897af7a7228421ddebc2b8'
+         '78d57546174aedb43d0d7cbcbaf8e073')
 
 package() {
-
-  # Get game archive
-  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
-
-  msg "Starting setup..."
   cd $srcdir
-  
-  # Unpack game archive
-  [[ -d ${_archive_subdir} ]] && rm -r ${_archive_subdir}
-  tar -xvf "${_archive}"
 
   # Install game files
-  install -d "${pkgdir}/opt/Rochard"
-  cp -r ${_archive_subdir}/* "${pkgdir}/opt/Rochard"
+  install -d "${pkgdir}/opt/"
+  mv -T Rochard_x$_arch "${pkgdir}/opt/Rochard"
 
   # Install launcher script
   echo -e "#!/bin/sh\ncd /opt/Rochard && ./Rochard" > "launcher.sh"
@@ -54,24 +42,4 @@ package() {
   # Install desktop entry
   install -Dm644 "${pkgname}.desktop" \
                  "${pkgdir}/usr/share/applications/${pkgname}.desktop"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
diff --git a/snapshot-hib/PKGBUILD b/snapshot-hib/PKGBUILD
--- a/snapshot-hib/PKGBUILD
+++ b/snapshot-hib/PKGBUILD
@@ -4,45 +4,38 @@ pkgname=snapshot-hib
 pkgver=1.28_20121219
 _hibver=v28
 pkgrel=1
-pkgdesc='A physics-based platformer puzzle game (Humble Bundle version)'
+pkgdesc='A platformer puzzle game (Humble Bundle version)'
 url='http://www.retroaffect.com/games/1/snapshot/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
-depends=('libgl' 'glu' 'sdl' 'openal' 'libogg' 'libvorbis')
+depends=('glu' 'sdl' 'openal' 'libvorbis')
 source=('snapshot-hib.desktop')
 md5sums=('b8020b21e46d0d57f9fedfcaa436ca82')
 options=('!strip' '!upx')
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 case $CARCH in
     i686)   _arch=x86; _archive_md5='8c893e6152d86801768de5d222b5150e' ;;
     x86_64) _arch=x64; _archive_md5='a9e6bb953e5d443fdb63901d89f65e78' ;;
 esac
-_archive="Snapshot-linux-${_hibver}-${_arch}.tar.gz"
-
+source=("hib://Snapshot-linux-${_hibver}-${_arch}.tar.gz"
+        'snapshot-hib.desktop')
+md5sums=("$_archive_md5"
+         '6df7363660caff44e3f2bfd946d12b34')
 
 package() {
   cd $srcdir
 
-  # Get archive
-  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
-  
-  # Extract archive
-  msg "Starting setup..."
-  tar -xzf "${_archive}"
-  
   # Fix permissions
   find "${srcdir}/resources" -type f -exec chmod 644 {} \;
   find "${srcdir}/resources" -type d -exec chmod 755 {} \;
-  
+
   # Install game files
   install -d "${pkgdir}/opt/Snapshot/"
   cp -r "${srcdir}/"{resources,snapshot.bin,snapshot,liblua5.1.so.0} \
         "${pkgdir}/opt/Snapshot/"
-  
+
   # Install desktop entry
   install -Dm644 "${pkgname}.desktop" \
                  "${pkgdir}/usr/share/applications/${pkgname}.desktop"
@@ -54,24 +47,4 @@ package() {
   # Install launch script
   install -d "${pkgdir}/usr/bin"
   ln -s "/opt/Snapshot/snapshot" "${pkgdir}/usr/bin/snapshot"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
diff --git a/spaz-hib/PKGBUILD b/spaz-hib/PKGBUILD
--- a/spaz-hib/PKGBUILD
+++ b/spaz-hib/PKGBUILD
@@ -19,31 +19,24 @@ else
 fi
 options=('!strip' '!upx')
 PKGEXT='.pkg.tar'
-source=('spaz-hib.desktop')
-md5sums=('544fa2a99bc3d4733909e18f2df6515d')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
-_archive="spaz-linux-humblebundle-${_hibver}-bin"
-_archive_md5='9b2f28009949f2dff9f3a737e46fabfd'
+_installer="spaz-linux-humblebundle-${_hibver}-bin"
+source=("hib://${_installer}"
+        'spaz-hib.desktop')
+md5sums=('9b2f28009949f2dff9f3a737e46fabfd'
+         '544fa2a99bc3d4733909e18f2df6515d')
 
 package() {
   cd $srcdir
 
-  # Get installer
-  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
-
-  # Extract the installer
-  unzip -o "${_archive}" || true
-
   # Remove bundled libraries (to force usage of system libs instead)
-  rm -f $srcdir/data/libSDL-1.2.so.0
-  rm -f $srcdir/data/libopenal.so
+  rm -f data/libSDL-1.2.so.0
+  rm -f data/libopenal.so
 
   # Install game files
   install -d "${pkgdir}/opt/SPAZ"
-  cp -r "$srcdir/data/"* "${pkgdir}/opt/SPAZ/"
+  cp -r data/* "${pkgdir}/opt/SPAZ/"
 
   # Install desktop entry
   install -Dm644 "$pkgname.desktop" \
@@ -56,24 +49,4 @@ package() {
   install -d "$pkgdir/usr/bin"
   echo -e "#!/bin/sh\ncd /opt/SPAZ && ./SPAZ" > "$pkgdir/usr/bin/spaz"
   chmod 755 "$pkgdir/usr/bin/spaz"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
