updated on Mon Aug 20 08:07:14 UTC 2012

diff --git a/linux-uksm-ck/PKGBUILD b/linux-uksm-ck/PKGBUILD
--- a/linux-uksm-ck/PKGBUILD
+++ b/linux-uksm-ck/PKGBUILD
@@ -1,80 +1,90 @@
 # Maintainer: Figo.zhang <figo1802@gmail.com>
 # Maintainer: Lawliet <yanzilme@gmail.com>
 
+### PATCH AND BUILD OPTIONS
+_makenconfig="n"	# tweak kernel options prior to a build via nconfig
+_makemenuconfig="n"	# make menuconfig before compilation starts
+_localmodcfg="n"	# compile ONLY probed modules
 _use_current="n"	# use the current kernel's .config file
+_BFQ_enable_="y"	# enable BFQ as the default I/O scheduler
+MAKEFLAGS=""		# add your custom make flag here, such as -j 4
+
+### DOCS
+# DETAILS FOR _localmodcfg="y"
+# As of mainline 2.6.32, running with this option will only build the modules that you currently have
+# probed in your system VASTLY reducing the number of modules built and the build time to do it.
+#
+# WARNING - make CERTAIN that all modules are modprobed BEFORE you begin making the pkg!
+#
+# To keep track of which modules are needed for your specific system/hardware, give my module_db script
+# a try: http://aur.archlinux.org/packages.php?ID=41689  Note that if you use my script, this PKGBUILD 
+# will auto run the 'sudo modprobed_db reload' for you to probe all the modules you have logged!
+#
+# More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed_db
+
+# DETAILS FOR _use_current="y"
+# Enabling this option will use the .config of the RUNNING kernel rather than the ARCH defaults.
+# Useful when the package gets updated and you already went through the trouble of customizing your
+# config options.  NOT recommended when a new kernel is released, but again, convenient for package bumps.
+
+# DETAILS FOR _BFQ_enable="y"
+# Alternative I/O scheduler by Paolo.  For more, see: http://algo.ing.unimo.it/people/paolo/disk_sched/
 
 pkgname=linux-uksm-ck
 true && pkgname=(linux-uksm-ck linux-uksm-ck-headers)
 _kernelname=-uksm-ck
-_basekernel=3.4
-pkgver=${_basekernel}.9
+_srcname=linux-3.5
+pkgver=3.5.2
 pkgrel=1
 arch=('i686' 'x86_64')
 url="http://kerneldedup.org/"
 license=('GPL2')
 options=('!strip')
-_ckpatchversion=3
-_ckpatchname="patch-${_basekernel}.6+-ck${_ckpatchversion}"
-_uksmname="v3.4.ge.6"
+_ckpatchversion=1
+_ckpatchname="patch-3.5-ck${_ckpatchversion}"
+_uksmname="v3.5"
 _uksmvernel="0.1.2"
-_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.4.0-v4"
+_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.5.0-v4"
 source=(
-      "http://www.kernel.org/pub/linux/kernel/v3.x/linux-${_basekernel}.tar.xz"
-      "http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
-      ##"http://ck.kolivas.org/patches/3.0/3.4/${_basekernel}-ck${_ckpatchversion}/${_ckpatchname}.bz2"
-      "http://dl.dropbox.com/u/20066450/Linux/kernel/ck-patch/patch-${_basekernel}.6+-ck${_ckpatchversion}"
-      'linux-uksm-ck.preset'
-      'config'
-      'config.x86_64'
-      'change-default-console-loglevel.patch'
-      'i915-fix-ghost-tv-output.patch'
-      'fix-acerhdf-1810T-bios.patch'
-      "http://kerneldedup.org/download/uksm/${_uksmvernel}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
-      "${_bfqpath}/0001-block-cgroups-kconfig-build-bits-for-BFQ-v4-3.4.patch"
-      "${_bfqpath}/0002-block-introduce-the-BFQ-v4-I-O-sched-for-3.4.patch"
-      '3.4.4-fix-backlight-regression.patch'
-       )
-
-sha256sums=(
-          'ff3dee6a855873d12487a6f4070ec2f7996d073019171361c955639664baa0c6'
-          '24b9286b0913d60b5c10a9e0b896b25dc5b302334cc62b18f8b28316127f2844'
-          '406e3cb78be6aca24c131e24663656b34b849f0db9ee567adecaf9b8b3e67628'
-          '944d1ff66fd337c750b17773d4dd03a72efa048714e19477f178300ebbce7ca8'
-          '1bd0c5b91ae0300c26ee6c80a0270195810555cfff57bcad3a9cf84b8558bd26'
-          '2519f7c6e773d4704f6faec9aeecdbe945df3478d890646cc267791663eacc0e'
-          'b9d79ca33b0b51ff4f6976b7cd6dbb0b624ebf4fbf440222217f8ffc50445de4'
-          '9ccadbe3eb30bb283af3eb869c3a4bdb764628854811cc616a2e02e9ef398705'
-          'f77e1a1f2d955f0499dc2957d1d65a3eb931212a13948b33916332296d0e4a7a'
-          '6ff949b23a64d046ad77a12e2d9d8a1b246838b69625dcfa744668f5cd287d3c'
-          '83e4a26a048bc4fc54fb4da8d3c1ea8a7997a9238c8dce1cef567ee35c0b3940'
-          '67160fbcdb37955c957349dd88760a36b23929dcb28d61b91509d1315e158acb'
-          '04d3a4d636950ea8906843274cc6b7b4f745dc65e10f4a9f213dcb5ac9b9f8a8'
-           )
-
-build() {
-	cd "${srcdir}/linux-${_basekernel}"
-
-	msg "Patching with upstream patch ${_basekernel} to ${_basekernel}.3"
-	patch -p1 -i "${srcdir}/patch-${pkgver}"
-	
-	msg "Patching with i915-fix-ghost-tv-output.patch"
-	patch -Np1 -i "${srcdir}/i915-fix-ghost-tv-output.patch"
-	
-	msg "Patching with 3.4.4-fix-backlight-regression.patch"
-	# Fix backlight control on some laptops:
-        # https://bugzilla.kernel.org/show_bug.cgi?id=43168
-        patch -Np1 -i "${srcdir}/3.4.4-fix-backlight-regression.patch"
+        "http://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
+        "http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
+        "http://ck.kolivas.org/patches/3.0/3.5/3.5-ck${_ckpatchversion}/${_ckpatchname}.bz2"
+        "http://kerneldedup.org/download/uksm/${_uksmvernel}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
+        'linux-uksm-ck.preset'
+        'config' 'config.x86_64'
+        'change-default-console-loglevel.patch'
+        "${_bfqpath}/0001-block-cgroups-kconfig-build-bits-for-BFQ-v4-3.5.patch"
+        "${_bfqpath}/0002-block-introduce-the-BFQ-v4-I-O-sched-for-3.5.patch")
         
-	msg "Patching with fix-acerhdf-1810T-bios.patch"
-	patch -Np1 -i "${srcdir}/fix-acerhdf-1810T-bios.patch"
+sha256sums=(
+            'b985ce383f0cfd940d988d4c99a84899028327aca8c29b420678241f26fdb342'
+            '6a05003eb6bc8b899ecece926de3733494d56b352e485933e21809177107d45c'
+            '501feba92335a4444e8c418e8e8d11783fe6c2ffa1b3b957d58696f92bb53b94'
+            '6401a77edebebaebcf4367c47550b82ea2140161aced0ecc5d7c0705d4070fc9'
+            '944d1ff66fd337c750b17773d4dd03a72efa048714e19477f178300ebbce7ca8'
+            'fb7eee4bea9f90308a240fcdd76c479816c0cc24433a59631ace9dca5f5b71de'
+            'c0536955786441518a1c70101fce46e3d8dcad8127ae4576b4e09efbc63f5c5b'
+            'b9d79ca33b0b51ff4f6976b7cd6dbb0b624ebf4fbf440222217f8ffc50445de4'
+            'c59574d6130f36696ecfce2cfa3fe326a80996e263ac8463f9528ffe15aee343'
+            '76376d8478834d86fb3ee6db37882e5863b3984d74d5d029d48eb9e3437a120c'
+            )
+            
+build() {
+	cd "${srcdir}/${_srcname}"
 
-	msg "Patching with change-default-console-loglevel.patch"
+	# add upstream patch
+	patch -p1 -i "${srcdir}/patch-${pkgver}"
+
+	# set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
+	# remove this when a Kconfig knob is made available by upstream
+	# (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
 	patch -Np1 -i "${srcdir}/change-default-console-loglevel.patch"
 
 	### Patch source with ck patchset with BFS
-        sed -i -re "s/^(.EXTRAVERSION).*$/\1 = /" "${srcdir}/${_ckpatchname}"
-        msg "Patching source with ck3 including bfs v0.424"
-        patch -Np1 -i "${srcdir}/${_ckpatchname}"
+	# Fix double name in EXTRAVERSION
+	sed -i -re "s/^(.EXTRAVERSION).*$/\1 = /" "${srcdir}/${_ckpatchname}"
+	msg "Patching source with ck1 including bfs v0.424"
+	patch -Np1 -i "${srcdir}/${_ckpatchname}"
 
 	### Patch with BFQ IO Scheduler
 	msg "Patching source with BFQ patches"
@@ -84,8 +94,8 @@ build() {
 
 	### Patch source with UKSM
 	msg "Patching with UKSM"
-		patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
-	        
+	patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
+
 	### Clean tree and copy ARCH config over
 	msg "Running make mrproper to clean source tree"
 	make mrproper
@@ -113,114 +123,142 @@ build() {
 
 	if [ "${_kernelname}" != "" ]; then
 		sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
+	 	sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
 	fi
 
-        ### BFQ to be compiled in but not enabled
+	### BFQ to be compiled in but not enabled
 	sed -i -e s'/CONFIG_CFQ_GROUP_IOSCHED=y/CONFIG_CFQ_GROUP_IOSCHED=y\nCONFIG_IOSCHED_BFQ=y\nCONFIG_CGROUP_BFQIO=y/' \
 		-i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
 
 	### Optionally enable BFQ as the default io scheduler
-#	if [ $_BFQ_enable_ = "y" ]; then
+	if [ $_BFQ_enable_ = "y" ]; then
 		sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
-			-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
-#	fi
+		-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	fi
 
 	# set extraversion to pkgrel
 	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
 
-        # don't run depmod on 'make install'. We'll do this ourselves in packaging
-        sed -i '2iexit 0' scripts/depmod.sh
+	# don't run depmod on 'make install'. We'll do this ourselves in packaging
+	sed -i '2iexit 0' scripts/depmod.sh
 
 	# get kernel version
+	msg "Running make prepare for you to enable patched options of your choosing"
 	make prepare
 
+	### Optionally load needed modules for the make localmodconfig
+	# See http://aur.archlinux.org/packages.php?ID=41689
+	if [ $_localmodcfg = "y" ]; then
+		msg "If you have modprobe_db installed, running it in recall mode now"
+		if [ -e /usr/bin/modprobed_db ]; then
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
+			sudo /usr/bin/modprobed_db recall
+		fi
+		msg "Running Steven Rostedt's make localmodconfig now"
+		make localmodconfig
+	fi
+
+	if [ $_makenconfig = "y" ]; then
+		msg "Running make nconfig"
+		make nconfig
+	fi
+
+	if [ $_makemenuconfig = "y" ]; then
+		msg "Running make menuconfig"
+		make menuconfig
+	fi
+
 	msg "Running make bzImage and modules"
-	make ${MAKEFLAGS} bzImage modules
+	make ${MAKEFLAGS} LOCALVERSION= bzImage modules
 }
 
 package_linux-uksm-ck() {
-	_Kpkgdesc='Linux Kernel and modules with the ck1 patchset featuring the Brain Fuck Scheduler v0.424.'
-	pkgdesc="${_Kpkgdesc}"
-	depends=('coreutils' 'linux-firmware' 'mkinitcpio>=0.7')
-	optdepends=('crda: to set the correct wireless channels of your country' 'lirc-ck: Linux Infrared Remote Control kernel modules for linux-uksm-ck' 'nvidia-ck: nVidia drivers for linux-uksm-ck' 'nvidia-beta-ck: nVidia beta drivers for linux-uksm-ck' 'modprobed_db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig')
-	provides=("linux-uksm-ck=${pkgver}")
-	conflicts=('kernel26-uksm')
-	replaces=('kernel26-uksm')
-	backup=("etc/mkinitcpio.d/linux-uksm-ck.preset")
-	install=linux-uksm-ck.install
+_Kpkgdesc='Linux Kernel and modules with the ck1 patchset featuring the Brain Fuck Scheduler v0.424.'
+pkgdesc="${_Kpkgdesc}"
+depends=('coreutils' 'linux-firmware' 'mkinitcpio>=0.7')
+optdepends=('crda: to set the correct wireless channels of your country' 'nvidia-uksm-ck: nVidia drivers for linux-uksm-ck' 'modprobed_db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig')
+provides=("linux-uksm-ck=${pkgver}")
+conflicts=('kernel26-uksm')
+replaces=('kernel26-uksm')
+backup=("etc/mkinitcpio.d/linux-uksm-ck.preset")
+install=linux-uksm-ck.install
+#groups=('ck-generic')
 
-	cd "${srcdir}/linux-${_basekernel}"
+cd "${srcdir}/${_srcname}"
 
-	KARCH=x86
+KARCH=x86
 
-	# get kernel version
-	_kernver="$(make kernelrelease)"
+# get kernel version
+_kernver="$(make LOCALVERSION= kernelrelease)"
+_basekernel=${_kernver%%-*}
+_basekernel=${_basekernel%.*}
 
-	mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot}
-	make INSTALL_MOD_PATH="${pkgdir}" modules_install
-	cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-linux-uksm-ck"
+mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot}
+make LOCALVERSION= INSTALL_MOD_PATH="${pkgdir}" modules_install
+cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-linux-uksm-ck"
 
-	# add vmlinux
-	install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
+# add vmlinux
+install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
 
-	# install fallback mkinitcpio.conf file and preset file for kernel
-	install -D -m644 "${srcdir}/linux-uksm-ck.preset" "${pkgdir}/etc/mkinitcpio.d/linux-uksm-ck.preset"
+# install fallback mkinitcpio.conf file and preset file for kernel
+install -D -m644 "${srcdir}/linux-uksm-ck.preset" "${pkgdir}/etc/mkinitcpio.d/linux-uksm-ck.preset"
 
-	# set correct depmod command for install
-	sed \
-		-e  "s/KERNEL_NAME=.*/KERNEL_NAME=-uksm-ck/g" \
-		-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
-		-i "${startdir}/linux-uksm-ck.install"
-	sed \
-		-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-linux-uksm-ck\"|g" \
-		-e "s|default_image=.*|default_image=\"/boot/initramfs-linux-uksm-ck.img\"|g" \
-		-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-linux-uksm-ck-fallback.img\"|g" \
-		-i "${pkgdir}/etc/mkinitcpio.d/linux-uksm-ck.preset"
+# set correct depmod command for install
+sed \
+	-e  "s/KERNEL_NAME=.*/KERNEL_NAME=-uksm-ck/g" \
+	-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
+	-i "${startdir}/linux-uksm-ck.install"
+sed \
+	-e "1s|'linux.*'|'linux-uksm-ck'|" \
+	-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-linux-uksm-ck\"|" \
+	-e "s|default_image=.*|default_image=\"/boot/initramfs-linux-uksm-ck.img\"|" \
+	-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-linux-uksm-ck-fallback.img\"|" \
+	-i "${pkgdir}/etc/mkinitcpio.d/linux-uksm-ck.preset"
 
-	# remove build and source links
-	rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
-	# remove the firmware
-	rm -rf "${pkgdir}/lib/firmware"
-	# gzip -9 all modules to save 100MB of space
-	find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
-	# make room for external modules
-	ln -s "../extramodules-${_basekernel}${_kernelname:uksm-ck}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
-	# add real version for building modules and running depmod from post_install/upgrade
-	mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:uksm-ck}"
-	echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:uksm-ck}/version"
+# remove build and source links
+rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
+# remove the firmware
+rm -rf "${pkgdir}/lib/firmware"
+# gzip -9 all modules to save 100MB of space
+find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
+# make room for external modules
+ln -s "../extramodules-${_basekernel}${_kernelname:ck}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
+# add real version for building modules and running depmod from post_install/upgrade
+mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:ck}"
+echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:ck}/version"
 
-        # move module tree /lib -> /usr/lib
-        mv "$pkgdir/lib" "$pkgdir/usr"
+# move module tree /lib -> /usr/lib
+mv "$pkgdir/lib" "$pkgdir/usr"
 
-        # Now we call depmod...
-        depmod -b "$pkgdir" -F System.map "$_kernver"
+# Now we call depmod...
+depmod -b "$pkgdir" -F System.map "$_kernver"
 }
 
 package_linux-uksm-ck-headers() {
-	_Hpkgdesc='Header files and scripts to build modules for linux-uksm-ck.'
-	pkgdesc="${_Hpkgdesc}"
-	provides=("linux-uksm-ck-headers=${pkgver}")
-	conflicts=('kernel26-uksm-headers')
-	replaces=('kernel26-uksm-headers')
+_Hpkgdesc='Header files and scripts to build modules for linux-uksm-ck.'
+pkgdesc="${_Hpkgdesc}"
+provides=("linux-uksm-ck-headers=${pkgver}")
+conflicts=('kernel26-uksm-headers')
+replaces=('kernel26-uksm-headers')
 
-        install -dm755 "${pkgdir}/usr/lib/modules/${_kernver}"
+install -dm755 "${pkgdir}/usr/lib/modules/${_kernver}"
 
-        cd "${pkgdir}/usr/lib/modules/${_kernver}"
-        ln -sf ../../../src/linux-${_kernver} build
+cd "${pkgdir}/usr/lib/modules/${_kernver}"
+ln -sf ../../../src/linux-${_kernver} build
 
-	cd "${srcdir}/linux-${_basekernel}"
-	install -D -m644 Makefile \
-		"${pkgdir}/usr/src/linux-${_kernver}/Makefile"
-	install -D -m644 kernel/Makefile \
-		"${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
-	install -D -m644 .config \
-		"${pkgdir}/usr/src/linux-${_kernver}/.config"
+cd "${srcdir}/${_srcname}"
+install -D -m644 Makefile \
+	"${pkgdir}/usr/src/linux-${_kernver}/Makefile"
+install -D -m644 kernel/Makefile \
+	"${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
+install -D -m644 .config \
+	"${pkgdir}/usr/src/linux-${_kernver}/.config"
 
-	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
+mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
 
-	for i in acpi asm-generic config crypto drm generated linux math-emu \
-		media net pcmcia scsi sound trace video xen; do
-		cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
+for i in acpi asm-generic config crypto drm generated linux math-emu \
+	media net pcmcia scsi sound trace video xen; do
+cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
 	done
 
 	# copy arch includes for external modules
@@ -234,7 +272,7 @@ package_linux-uksm-ck-headers() {
 	# fix permissions on scripts dir
 	chmod og-w -R "${pkgdir}/usr/src/linux-${_kernver}/scripts"
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/.tmp_versions"
-	
+
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/kernel"
 
 	cp arch/${KARCH}/Makefile "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/"
@@ -250,14 +288,14 @@ package_linux-uksm-ck-headers() {
 
 	cp drivers/media/video/*.h  "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/"
 
-	for i in bt8xx cpia2 cx25840 cx88 em28xx et61x251 pwc saa7134 sn9c102; do
+	for i in bt8xx cpia2 cx25840 cx88 em28xx pwc saa7134 sn9c102; do
 		mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/${i}"
 		cp -a drivers/media/video/${i}/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/${i}"
 	done
 
 	# add docbook makefile
 	install -D -m644 Documentation/DocBook/Makefile \
-	"${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
+		"${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
 
 	# add dm headers
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/md"
@@ -322,10 +360,10 @@ package_linux-uksm-ck-headers() {
 		*application/x-executable*) # Binaries
 			/usr/bin/strip ${STRIP_BINARIES} "${binary}";;
 	esac
-	done
+done
 
-	# remove unneeded architectures
-	rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
+# remove unneeded architectures
+rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
 }
 # Global pkgdesc and depends are here so that they will be picked up by AUR
-pkgdesc='Linux kernel and modules with the UKSM, BFS, BFQ patchset.'
+pkgdesc=' Linux kernel and modules with the UKSM, BFS, BFQ patchset.'
diff --git a/linux-uksm/PKGBUILD b/linux-uksm/PKGBUILD
--- a/linux-uksm/PKGBUILD
+++ b/linux-uksm/PKGBUILD
@@ -1,74 +1,80 @@
 # Maintainer: Figo.zhang <figo1802@gmail.com>
 # Maintainer: Lawliet <yanzilme@gmail.com>
 
+### PATCH AND BUILD OPTIONS
+_makenconfig="n"	# tweak kernel options prior to a build via nconfig
+_makemenuconfig="n"	# make menuconfig before compilation starts
+_localmodcfg="n"	# compile ONLY probed modules
 _use_current="n"	# use the current kernel's .config file
+MAKEFLAGS=""		# add your custom make flag here, such as -j 4
+
+### DOCS
+# DETAILS FOR _localmodcfg="y"
+# As of mainline 2.6.32, running with this option will only build the modules that you currently have
+# probed in your system VASTLY reducing the number of modules built and the build time to do it.
+#
+# WARNING - make CERTAIN that all modules are modprobed BEFORE you begin making the pkg!
+#
+# To keep track of which modules are needed for your specific system/hardware, give my module_db script
+# a try: http://aur.archlinux.org/packages.php?ID=41689  Note that if you use my script, this PKGBUILD 
+# will auto run the 'sudo modprobed_db reload' for you to probe all the modules you have logged!
+#
+# More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed_db
+
+# DETAILS FOR _use_current="y"
+# Enabling this option will use the .config of the RUNNING kernel rather than the ARCH defaults.
+# Useful when the package gets updated and you already went through the trouble of customizing your
+# config options.  NOT recommended when a new kernel is released, but again, convenient for package bumps.
+
+# DETAILS FOR _BFQ_enable="y"
+# Alternative I/O scheduler by Paolo.  For more, see: http://algo.ing.unimo.it/people/paolo/disk_sched/
 
 pkgname=linux-uksm
 true && pkgname=(linux-uksm linux-uksm-headers)
 _kernelname=-uksm
-_basekernel=3.4
-pkgver=${_basekernel}.9
+_srcname=linux-3.5
+pkgver=3.5.2
 pkgrel=1
 arch=('i686' 'x86_64')
 url="http://kerneldedup.org/"
 license=('GPL2')
 options=('!strip')
-_ckpatchversion=1
-_ckpatchname="patch-${_basekernel}${_ckpatchversion}"
-_uksmname="v3.4.ge.6"
+_uksmname="v3.5"
 _uksmvernel="0.1.2"
 source=(
-      "http://www.kernel.org/pub/linux/kernel/v3.x/linux-${_basekernel}.tar.xz"
-      "http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
-      'linux-uksm.preset'
-      'config'
-      'config.x86_64'
-      'change-default-console-loglevel.patch'
-      'i915-fix-ghost-tv-output.patch'
-      'fix-acerhdf-1810T-bios.patch'
-      "http://kerneldedup.org/download/uksm/${_uksmvernel}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
-      '3.4.4-fix-backlight-regression.patch'
-       )
+"http://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
+"http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
+"http://kerneldedup.org/download/uksm/${_uksmvernel}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
+'linux-uksm.preset'
+'config' 'config.x86_64'
+'change-default-console-loglevel.patch'
+)
 
 sha256sums=(
-          'ff3dee6a855873d12487a6f4070ec2f7996d073019171361c955639664baa0c6'
-          '24b9286b0913d60b5c10a9e0b896b25dc5b302334cc62b18f8b28316127f2844'
-          '28a956ae3f2a080f7fed0d043b3d2351494feda2128c4cd5ff64964c5c008032'
-          'f9a04c0ebf2c2d8117919983f8ff99ce03c895f5ff87ee17734615ae54ee3fc4'
-          '4287613886a3f1dd23a73892c6f971b4b49c191c55ab2a5242fa6b2385d31a43'
-          'b9d79ca33b0b51ff4f6976b7cd6dbb0b624ebf4fbf440222217f8ffc50445de4'
-          '9ccadbe3eb30bb283af3eb869c3a4bdb764628854811cc616a2e02e9ef398705'
-          'f77e1a1f2d955f0499dc2957d1d65a3eb931212a13948b33916332296d0e4a7a'
-          '6ff949b23a64d046ad77a12e2d9d8a1b246838b69625dcfa744668f5cd287d3c'
-          '04d3a4d636950ea8906843274cc6b7b4f745dc65e10f4a9f213dcb5ac9b9f8a8'
-           )
-
+            'b985ce383f0cfd940d988d4c99a84899028327aca8c29b420678241f26fdb342'
+            '6a05003eb6bc8b899ecece926de3733494d56b352e485933e21809177107d45c'
+            '6401a77edebebaebcf4367c47550b82ea2140161aced0ecc5d7c0705d4070fc9'
+            '28a956ae3f2a080f7fed0d043b3d2351494feda2128c4cd5ff64964c5c008032'
+            'c6e08e0f80de96a13ff843b02564873c55e65824b889d2fd7bbf4b09615ecc1d'
+            'b082f65640db76fb22fa76956ee94f965b4ee3f0a9702b0c5f86e3b3f708d340'
+            'b9d79ca33b0b51ff4f6976b7cd6dbb0b624ebf4fbf440222217f8ffc50445de4'
+            )
+            
 build() {
-	cd "${srcdir}/linux-${_basekernel}"
+	cd "${srcdir}/${_srcname}"
 
-	msg "Patching with upstream patch ${_basekernel}.2 to ${_basekernel}.3"
+	# add upstream patch
 	patch -p1 -i "${srcdir}/patch-${pkgver}"
-	
-	msg "Patching with i915-fix-ghost-tv-output.patch"
-	patch -Np1 -i "${srcdir}/i915-fix-ghost-tv-output.patch"
-	
-	msg "Patching with 3.4.4-fix-backlight-regression.patch"
-	# Fix backlight control on some laptops:
-        # https://bugzilla.kernel.org/show_bug.cgi?id=43168
-        patch -Np1 -i "${srcdir}/3.4.4-fix-backlight-regression.patch"
-        
-	msg "Patching with fix-acerhdf-1810T-bios.patch"
-	patch -Np1 -i "${srcdir}/fix-acerhdf-1810T-bios.patch"
 
-	msg "Patching with change-default-console-loglevel.patch"
+	# set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
+	# remove this when a Kconfig knob is made available by upstream
+	# (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
 	patch -Np1 -i "${srcdir}/change-default-console-loglevel.patch"
-
-
 
 	### Patch source with UKSM
 	msg "Patching with UKSM"
-		patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
-	
+	patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
+
 	### Clean tree and copy ARCH config over
 	msg "Running make mrproper to clean source tree"
 	make mrproper
@@ -96,105 +102,136 @@ build() {
 
 	if [ "${_kernelname}" != "" ]; then
 		sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
+	 	sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
 	fi
 
+	### BFQ to be compiled in but not enabled
+	sed -i -e s'/CONFIG_CFQ_GROUP_IOSCHED=y/CONFIG_CFQ_GROUP_IOSCHED=y\nCONFIG_IOSCHED_BFQ=y\nCONFIG_CGROUP_BFQIO=y/' \
+		-i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
 
 	# set extraversion to pkgrel
 	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
-	
-        # don't run depmod on 'make install'. We'll do this ourselves in packaging
-        sed -i '2iexit 0' scripts/depmod.sh
+
+	# don't run depmod on 'make install'. We'll do this ourselves in packaging
+	sed -i '2iexit 0' scripts/depmod.sh
 
 	# get kernel version
+	msg "Running make prepare for you to enable patched options of your choosing"
 	make prepare
 
+	### Optionally load needed modules for the make localmodconfig
+	# See http://aur.archlinux.org/packages.php?ID=41689
+	if [ $_localmodcfg = "y" ]; then
+		msg "If you have modprobe_db installed, running it in recall mode now"
+		if [ -e /usr/bin/modprobed_db ]; then
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
+			sudo /usr/bin/modprobed_db recall
+		fi
+		msg "Running Steven Rostedt's make localmodconfig now"
+		make localmodconfig
+	fi
+
+	if [ $_makenconfig = "y" ]; then
+		msg "Running make nconfig"
+		make nconfig
+	fi
+
+	if [ $_makemenuconfig = "y" ]; then
+		msg "Running make menuconfig"
+		make menuconfig
+	fi
+
 	msg "Running make bzImage and modules"
-	make ${MAKEFLAGS} bzImage modules
+	make ${MAKEFLAGS} LOCALVERSION= bzImage modules
 }
 
 package_linux-uksm() {
-	_Kpkgdesc='Linux kernel and modules with the UKSM patchset and default enable pae.'
-	pkgdesc="${_Kpkgdesc}"
-	depends=('coreutils' 'linux-firmware' 'mkinitcpio>=0.7')
-	optdepends=('crda: to set the correct wireless channels of your country' 'lirc: Linux Infrared Remote Control kernel modules for linux-uksm' 'modprobed_db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig')
-	provides=("linux-uksm=${pkgver}")
-	conflicts=('kernel26-uksm')
-	replaces=('kernel26-uksm')
-	backup=("etc/mkinitcpio.d/linux-uksm.preset")
-	install=linux-uksm.install
+_Kpkgdesc='Linux Kernel and modules with the ck1 patchset featuring the Brain Fuck Scheduler v0.424.'
+pkgdesc="${_Kpkgdesc}"
+depends=('coreutils' 'linux-firmware' 'mkinitcpio>=0.7')
+optdepends=('crda: to set the correct wireless channels of your country' 'nvidia-uksm: nVidia drivers for linux-uksm' 'modprobed_db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig')
+provides=("linux-uksm=${pkgver}")
+conflicts=('kernel26-uksm')
+replaces=('kernel26-uksm')
+backup=("etc/mkinitcpio.d/linux-uksm.preset")
+install=linux-uksm.install
+#groups=('ck-generic')
 
-	cd "${srcdir}/linux-${_basekernel}"
+cd "${srcdir}/${_srcname}"
 
-	KARCH=x86
+KARCH=x86
 
-	# get kernel version
-	_kernver="$(make kernelrelease)"
+# get kernel version
+_kernver="$(make LOCALVERSION= kernelrelease)"
+_basekernel=${_kernver%%-*}
+_basekernel=${_basekernel%.*}
 
-	mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot}
-	make INSTALL_MOD_PATH="${pkgdir}" modules_install
-	cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-linux-uksm"
+mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot}
+make LOCALVERSION= INSTALL_MOD_PATH="${pkgdir}" modules_install
+cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-linux-uksm"
 
-	# add vmlinux
-	install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
+# add vmlinux
+install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
 
-	# install fallback mkinitcpio.conf file and preset file for kernel
-	install -D -m644 "${srcdir}/linux-uksm.preset" "${pkgdir}/etc/mkinitcpio.d/linux-uksm.preset"
+# install fallback mkinitcpio.conf file and preset file for kernel
+install -D -m644 "${srcdir}/linux-uksm.preset" "${pkgdir}/etc/mkinitcpio.d/linux-uksm.preset"
 
-	# set correct depmod command for install
-	sed \
-		-e  "s/KERNEL_NAME=.*/KERNEL_NAME=-uksm/g" \
-		-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
-		-i "${startdir}/linux-uksm.install"
-	sed \
-		-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-linux-uksm\"|g" \
-		-e "s|default_image=.*|default_image=\"/boot/initramfs-linux-uksm.img\"|g" \
-		-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-linux-uksm-fallback.img\"|g" \
-		-i "${pkgdir}/etc/mkinitcpio.d/linux-uksm.preset"
+# set correct depmod command for install
+sed \
+	-e  "s/KERNEL_NAME=.*/KERNEL_NAME=-uksm/g" \
+	-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
+	-i "${startdir}/linux-uksm.install"
+sed \
+	-e "1s|'linux.*'|'linux-uksm'|" \
+	-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-linux-uksm\"|" \
+	-e "s|default_image=.*|default_image=\"/boot/initramfs-linux-uksm.img\"|" \
+	-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-linux-uksm-fallback.img\"|" \
+	-i "${pkgdir}/etc/mkinitcpio.d/linux-uksm.preset"
 
-	# remove build and source links
-	rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
-	# remove the firmware
-	rm -rf "${pkgdir}/lib/firmware"
-	# gzip -9 all modules to save 100MB of space
-	find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
-	# make room for external modules
-	ln -s "../extramodules-${_basekernel}${_kernelname:uksm}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
-	# add real version for building modules and running depmod from post_install/upgrade
-	mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:uksm}"
-	echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:uksm}/version"
+# remove build and source links
+rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
+# remove the firmware
+rm -rf "${pkgdir}/lib/firmware"
+# gzip -9 all modules to save 100MB of space
+find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
+# make room for external modules
+ln -s "../extramodules-${_basekernel}${_kernelname:ck}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
+# add real version for building modules and running depmod from post_install/upgrade
+mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:ck}"
+echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:ck}/version"
 
-        # move module tree /lib -> /usr/lib
-        mv "$pkgdir/lib" "$pkgdir/usr"
+# move module tree /lib -> /usr/lib
+mv "$pkgdir/lib" "$pkgdir/usr"
 
-        # Now we call depmod...
-        depmod -b "$pkgdir" -F System.map "$_kernver"
+# Now we call depmod...
+depmod -b "$pkgdir" -F System.map "$_kernver"
 }
 
 package_linux-uksm-headers() {
-	_Hpkgdesc='Header files and scripts to build modules for linux-uksm.'
-	pkgdesc="${_Hpkgdesc}"
-	provides=("linux-uksm-headers=${pkgver}")
-	conflicts=('kernel26-uksm-headers')
-	replaces=('kernel26-uksm-headers')
+_Hpkgdesc='Header files and scripts to build modules for linux-uksm.'
+pkgdesc="${_Hpkgdesc}"
+provides=("linux-uksm-headers=${pkgver}")
+conflicts=('kernel26-uksm-headers')
+replaces=('kernel26-uksm-headers')
 
-        install -dm755 "${pkgdir}/usr/lib/modules/${_kernver}"
+install -dm755 "${pkgdir}/usr/lib/modules/${_kernver}"
 
-        cd "${pkgdir}/usr/lib/modules/${_kernver}"
-        ln -sf ../../../src/linux-${_kernver} build
+cd "${pkgdir}/usr/lib/modules/${_kernver}"
+ln -sf ../../../src/linux-${_kernver} build
 
-	cd "${srcdir}/linux-${_basekernel}"
-	install -D -m644 Makefile \
-		"${pkgdir}/usr/src/linux-${_kernver}/Makefile"
-	install -D -m644 kernel/Makefile \
-		"${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
-	install -D -m644 .config \
-		"${pkgdir}/usr/src/linux-${_kernver}/.config"
+cd "${srcdir}/${_srcname}"
+install -D -m644 Makefile \
+	"${pkgdir}/usr/src/linux-${_kernver}/Makefile"
+install -D -m644 kernel/Makefile \
+	"${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
+install -D -m644 .config \
+	"${pkgdir}/usr/src/linux-${_kernver}/.config"
 
-	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
+mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
 
-	for i in acpi asm-generic config crypto drm generated linux math-emu \
-		media net pcmcia scsi sound trace video xen; do
-		cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
+for i in acpi asm-generic config crypto drm generated linux math-emu \
+	media net pcmcia scsi sound trace video xen; do
+cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
 	done
 
 	# copy arch includes for external modules
@@ -208,7 +245,7 @@ package_linux-uksm-headers() {
 	# fix permissions on scripts dir
 	chmod og-w -R "${pkgdir}/usr/src/linux-${_kernver}/scripts"
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/.tmp_versions"
-	
+
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/kernel"
 
 	cp arch/${KARCH}/Makefile "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/"
@@ -224,14 +261,14 @@ package_linux-uksm-headers() {
 
 	cp drivers/media/video/*.h  "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/"
 
-	for i in bt8xx cpia2 cx25840 cx88 em28xx et61x251 pwc saa7134 sn9c102; do
+	for i in bt8xx cpia2 cx25840 cx88 em28xx pwc saa7134 sn9c102; do
 		mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/${i}"
 		cp -a drivers/media/video/${i}/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/${i}"
 	done
 
 	# add docbook makefile
 	install -D -m644 Documentation/DocBook/Makefile \
-	"${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
+		"${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
 
 	# add dm headers
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/md"
@@ -296,10 +333,10 @@ package_linux-uksm-headers() {
 		*application/x-executable*) # Binaries
 			/usr/bin/strip ${STRIP_BINARIES} "${binary}";;
 	esac
-	done
+done
 
-	# remove unneeded architectures
-	rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
+# remove unneeded architectures
+rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
 }
 # Global pkgdesc and depends are here so that they will be picked up by AUR
-pkgdesc='Linux kernel and modules with the UKSM patchset.'
+pkgdesc='Linux kernel and modules with the UKSM patch.'
