updated on Fri Aug 22 00:00:08 UTC 2014

diff --git a/mediabrowser-server/mediabrowser-server.install b/mediabrowser-server/mediabrowser-server.install
--- a/mediabrowser-server/mediabrowser-server.install
+++ b/mediabrowser-server/mediabrowser-server.install
@@ -1,58 +1,85 @@
 #! /bin/bash
 
 post_install() {
+  if [ -d /var/opt/mediabrowser-server ]; then
+    mv /var/opt/mediabrowser-server /tmp/mediabrowser
+  fi
+  getent group mediabrowser >/dev/null || groupadd mediabrowser
+  getent passwd mediabrowser >/dev/null || useradd -c 'Media Browser Server' -g mediabrowser -b /var/opt -m -s /bin/false mediabrowser
+  if [ -d /tmp/mediabrowser ]; then
+    mv /tmp/mediabrowser/* /var/opt/mediabrowser/
+    rmdir /tmp/mediabrowser
+  fi
+  if [ ! $? -eq 0 ]
+    then
+    echo "WARNING COULDN'T CREATE MEDIABROWSER USERID, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+      exit 1
+  fi
+  
+  systemctl --system daemon-reload
+  echo "Starting mediabrowser-server..."
+  systemctl start mediabrowser 
+  cat << "EOM"
+  ####
+  #  Installation completed:
+  #  This update brings a bunch of changes to the way that the
+  #  server will be administered. 
+  #    - The mediabrowser server no longer runs as root.
+  #      Instead it runs as the mediabrowser user.
+  #    - As the server no longer runs as root, permission will
+  #      need to be granted to the mediabrowser user to access
+  #      your media library.
+  #    - The name of the system service has changed to mediabrowser.
+  #    - 
+  ####
+EOM
 
-cat << EOF
+}
 
-To run the Media Browser 3 server, use systemctl to start the
-mediabrowser-server service.
-
-    sudo systemctl start mediabrowser-server
-
-To start MB3's server at boot, use systemctl.
-
-    sudo systemctl enable mediabrowser-server
-
-MB3 uses a web browser for all of its configuration.  To access the MB3
-configuration page, the address is http://localhost:8096/mediabrowser.
-
-For headless setups, MB3 should run very similarly.  The only major difference
-is that configuration is remotely done using the following url:
-
-http://servername:8096/mediabrowser.
-
-EOF
-
+pre_install() {
+  if [ $(systemctl is-active mediabrowser-server) == "active" ]; then
+    echo "Stopping mediabrowser-server before starting..."
+    systemctl stop mediabrowser-server
+  fi;
 }
 
 pre_upgrade() {
-    if [[ $(systemctl is-active mediabrowser-server) == active ]]; then
-        echo "Stopping the MediaBrowser server..."
-        systemctl stop mediabrowser-server
-    fi
-}
-
-post_upgrade() {
-    if [[ $(systemctl is-enabled mediabrowser-server) == enabled ]]; then
-        echo "MediaBrowser is enabled on this system. Will start the server."
-        echo "Starting the MediaBrowser server..."
-        systemctl daemon-reload
-        systemctl start mediabrowser-server
-    else
-        echo "MediaBrowser is not enabled on this system. Will not start the server."
-        systemctl daemon-reload
-    fi
+  pre_install;
 }
 
 pre_remove() {
-    if [[ $(systemctl is-active mediabrowser-server) == active ]]; then
-        echo "Stopping MediaBrowser..."
-        systemctl stop mediabrowser-server
-    fi
+  pre_install;
 }
 
-post_remove() {
-    echo ""
-    echo "Please remove /var/opt/mediabrowser-server to delete the MediaBrowser database and cache."
-    echo ""
+post_upgrade() {
+  if [ -d /var/opt/mediabrowser-server ]; then
+    mv /var/opt/mediabrowser-server /tmp/mediabrowser
+  fi
+  getent group mediabrowser >/dev/null || groupadd mediabrowser
+  getent passwd mediabrowser >/dev/null || useradd -c 'Media Browser Server' -g mediabrowser -b /var/opt -m -s /bin/false mediabrowser
+  if [ -d /tmp/mediabrowser ]; then
+    mv /tmp/mediabrowser/* /var/opt/mediabrowser/
+    rmdir /tmp/mediabrowser
+  fi
+  systemctl --system daemon-reload
+  echo "Fixing file permissions for install."
+  chown -R mediabrowser /var/opt/mediabrowser
+  chown -R mediabrowser /opt/mediabrowser-server
+  echo "Starting mediabrowser-server..."
+  systemctl start mediabrowser
+  cat << "EOM"
+  ####
+  #  Installation completed:
+  #  This update brings a bunch of changes to the way that the
+  #  server will be administered. 
+  #    - The mediabrowser server no longer runs as root.
+  #      Instead it runs as the mediabrowser user.
+  #    - As the server no longer runs as root, permission will
+  #      need to be granted to the mediabrowser user to access
+  #      your media library.
+  #    - The name of the system service has changed to mediabrowser.
+  #  
+  #  Hopefully, these changes will make the system a bit more secure. :)
+  ####
+EOM
 }
