updated on Mon Aug 20 14:00:53 UTC 2012

diff --git a/bittripbeat/PKGBUILD b/bittripbeat/PKGBUILD
--- a/bittripbeat/PKGBUILD
+++ b/bittripbeat/PKGBUILD
@@ -1,7 +1,8 @@
 # Maintainer: Zachary A. Jones <JazzplayerL9@gmail.com>
 pkgname=bittripbeat
 pkgver=1.0_4
-pkgrel=1
+_pkgver=1.0
+pkgrel=2
 pkgdesc="Rhythm-based pong-style platformer"
 arch=('i686' 'x86_64')
 url="http://bittripgame.com/bittrip-beat.html"
@@ -25,7 +26,7 @@ _archive="${_archive_name}_${pkgver//_/-}_${_archive_arch}.tar.gz"
 build() {
   cd ${srcdir}
 
-  if [ ! -f ${_btrarchivelocation}${_archive} ]; then
+  if [ ! -f ${_btbarchivelocation}${_archive} ]; then
 	  if [ ! -f ${_archive} ] && [ -n "${_humbleand3bundlekey}" ]; then
 		rm -f ${_archive}* downloads\?key\=${_humbleand3bundlekey}*
 		wget http://www.humblebundle.com/downloads?key=${_humbleand3bundlekey}
@@ -41,21 +42,21 @@ build() {
 	  fi
   fi
 
-  if [ ! -f ${_btrarchivelocation}${_archive} ]; then
-    echo "${_btrarchivelocation}${_archive} not found!"
+  if [ ! -f ${_btbarchivelocation}${_archive} ]; then
+    echo "${_btbarchivelocation}${_archive} not found!"
     return 1
   fi
 
-  if ! echo "${_archive_md5}  ${_btrarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_btrarchivelocation}${_archive}"
+  if ! echo "${_archive_md5}  ${_btbarchivelocation}${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_btbarchivelocation}${_archive}"
     return 1
   fi
 
-  bsdtar -xf ${_btrarchivelocation}${_archive}
+  bsdtar -xf ${_btbarchivelocation}${_archive}
 
   mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/bin/ \
     ${pkgdir}/usr/share/applications
-  cp -r ${srcdir}/${_archive_name}-${pkgver}/${_archive_name}/ ${pkgdir}/opt/
+  cp -r ${srcdir}/${_archive_name}-${_pkgver}/${_archive_name}/ ${pkgdir}/opt/
   cp ${srcdir}/${pkgname}.desktop ${pkgdir}/usr/share/applications/
   cp ${srcdir}/${pkgname}.sh ${pkgdir}/opt/${_archive_name}/
   ln -s /opt/${_archive_name}/${pkgname}.sh \
