updated on Wed Jul 17 22:18:13 UTC 2013

diff --git a/splice-hib/PKGBUILD b/splice-hib/PKGBUILD
--- a/splice-hib/PKGBUILD
+++ b/splice-hib/PKGBUILD
@@ -1,77 +1,58 @@
+# Maintainer: Claudio Kozicky <claudiokozicky@gmail.com>
 # Contributor: Ben R. <thebenj88 *AT* gmail *DOT* com>
 
 pkgname=splice-hib
 pkgver=1.0
-pkgrel=4
-pkgdesc='A unique puzzle game involving DNA-strand manipulation (Humble Bundle version)'
-url='http://www.cipherprime.com'
-arch=('i686' 'x86_64')
-license=('custom:commercial')
-depends=('libgl' 'mesa' 'mono')
-optdepends=('catalyst: AMD Proprietary 3D driver'
-			'nvidia: NVIDIA Proprietary 3D driver')
-install="${pkgname}.install"
-PKGEXT='.pkg.tar'
-_gamepkg="splice-linux-1353389454.tar.gz"
-if [[ $CARCH == x86_64 ]]; then
-	_arch="x86_64"
-	_badarch="x86"
-else
-	_arch="x86"
-	_badarch="x86_64"
-fi
+_pkgver=1353389454
+pkgrel=5
+pkgdesc="A unique puzzle game involving DNA strand manipulation."
+arch=(i686 x86_64)
+url="http://www.cipherprime.com/games/splice"
+license=(custom)
+depends=(glu libxcursor libxext)
+options=(!strip)
+install=$pkgname.install
+source=(hib://splice-linux-$_pkgver.tar.gz
+        $pkgname.desktop
+        $pkgname.png)
+md5sums=(a62a60160e890b8324146d5f12ca2efb
+         666994e07c9e19f8c72a4986e1a0f888
+         383365ad827ff3c23b9a4bb1b194876d)
+DLAGENTS+=('hib::/usr/bin/echo Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf.; exit 1')
+PKGEXT=.pkg.tar
 
-package() {
-	# Get installer
-	_get_humblebundle_source "${_gamepkg}" || {
-		error "Unable to find the game archive. Please download it from your Humble
-			Bundle page, and place it into one of the above locations."
-		exit 1;
-	}
-    msg "Extract files"
-	cd ${srcdir}
-	bsdtar -xf ${srcdir}/${_gamepkg}
-
-	msg "Create directory for binary"
-	mkdir -p ${pkgdir}/usr/bin
-	mkdir ${pkgdir}/opt
-
-	msg "Install tar.gz contents into package directory"
-	mv -v ${srcdir}/Linux/ ${pkgdir}/opt/${pkgname}
-
-	msg "Set owner and permissions"
-	chown root:games ${pkgdir}/opt/${pkgname} -R
-	find ${pkgdir}/opt/${pkgname} -type f -print0 | xargs -0 chmod 644
-	find ${pkgdir}/opt/${pkgname} -type d -print0 | xargs -0 chmod 755
-	chmod 755 ${pkgdir}/opt/${pkgname}/Splice.$_arch
-
-	msg "Link binary to /usr/bin"
-	ln -s /opt/${pkgname}/Splice.$_arch ${pkgdir}/usr/bin/${pkgname}
-	
-	msg "Removing unneeded binary"
-	rm ${pkgdir}/opt/${pkgname}/Splice.$_badarch
-	rm -rf ${pkgdir}/opt/${pkgname}/Splice_Data/Mono/$_badarch
-}
-  
-# Thanks again to smls for the following two functions, these saved me
-# a lot of time.
-
-# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
-_get_humblebundle_source() {
-  _get_local_source "$1" || return 1;
+prepare()
+{
+    # cleanup
+    [ $CARCH = i686 ] \
+        && rm -r "$srcdir"/Linux/Splice_Data/Mono/x86_64 \
+        || true
+    [ $CARCH = x86_64 ] \
+        && rm -r "$srcdir"/Linux/Splice_Data/Mono/x86 \
+        || true
 }
 
-# Locate a file or folder provided by the user, and symlink it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-    echo "NOT FOUND"
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
+package()
+{
+    cd "$srcdir"/Linux
+
+    # data
+    find Splice_Data -type f -exec install -Dm644 {} "$pkgdir"/opt/$pkgname/{} \;
+    install -m755 Splice.${CARCH//i686/x86} "$pkgdir"/opt/$pkgname
+
+    # launcher
+    install -d "$pkgdir"/usr/bin
+    ln -s /opt/$pkgname/Splice.${CARCH//i686/x86} "$pkgdir"/usr/bin/$pkgname
+
+    # doc
+    install -m644 -t "$pkgdir"/opt/$pkgname README{,\~}
+    install -d "$pkgdir"/usr/share/doc/$pkgname
+    ln -s /opt/$pkgname/README "$pkgdir"/usr/share/doc/$pkgname
+
+    # desktop integration
+    cd ..
+    install -Dm644 $pkgname.desktop "$pkgdir"/usr/share/applications/$pkgname.desktop
+    install -Dm644 $pkgname.png "$pkgdir"/usr/share/pixmaps/$pkgname.png
 }
+
+# vim:et:sw=4:sts=4
