updated on Sat Nov  9 00:35:15 UTC 2013

diff --git a/mingw-w64-tcl/PKGBUILD b/mingw-w64-tcl/PKGBUILD
--- a/mingw-w64-tcl/PKGBUILD
+++ b/mingw-w64-tcl/PKGBUILD
@@ -1,10 +1,11 @@
+# Maintainer: ant32 <antreimer@gmail.com>
 # Maintainer: Filip Brcic <brcha@gna.org>
 
 pkgname=mingw-w64-tcl
 _majorver1=8
-_majorver2=5
+_majorver2=6
 _majorver="${_majorver1}.${_majorver2}"
-pkgver="${_majorver}.11"
+pkgver="${_majorver}.1"
 pkgrel=1
 pkgdesc="MinGW Windows Tool Command Language, pronounced tickle (mingw-w64)"
 arch=('any')
@@ -14,96 +15,108 @@ options=('staticlibs' '!strip' 'staticlibs')
 license=('custom')
 url="http://tcl.sourceforge.net/"
 source=("http://downloads.sourceforge.net/sourceforge/tcl/tcl${pkgver}-src.tar.gz"
-        "tcl-8.5.1-autopath.patch"
-	"tcl-8.5.10-conf.patch"
-	"tcl-8.5.9-hidden.patch"
-	"tcl-8.5.6-mingw32.patch"
-	"tcl-nativetclsh.patch"
+        "tcl-8.5.14-autopath.patch"
+	"tcl-8.5.14-conf.patch"
+	"tcl-8.5.14-hidden.patch"
+	"tcl-8.6.1-mingwexcept.patch"
 	"tcl-mingw-w64-compatibility.patch")
-md5sums=('b01a9691c83990b3db0ce62d1012ca67'
-         '1d649acd200ffdf27fcae441fceef833'
-         '74a0e9236e5f9ed9e6a908bb90d34afd'
-         'aead35e4382da6f755d798eb232092cc'
-         '970896456778854b20dbfbc3855637cb'
-         '39619a7718b27b860112241e70f3485c'
-         '0be352d07a6f305618feee7bd79041f4')
+sha256sums=('16ee769248e64ba1cae6b4834fcc4e4edd7470d881410e8d58f7dd1434343514'
+            '3cb435f768052acabe5b1fbef5ae9a8d0967b0f86f7695fb4bae8953ee470357'
+            '970a37e5496e7ad9e7cbb3dfba3f3a40630da67f14abd819df82af53faabdf25'
+            'a809617939336a0068c5dd567f2c25489b2824ca25ad20f9cbf4e74c81396d2e'
+            '77b7509f3677fe659a70994f664444c1f0e99899bd3e73cba71caa4ccb24ebd4'
+            '866fe923b7d43339bea8a8484299ba71ebdb3a7213508809f2adae4eff60a382')
 
 _architectures="i686-w64-mingw32 x86_64-w64-mingw32"
 
-build() {
+prepare() {
   cd "${srcdir}/tcl${pkgver}"
 
-  patch -Np1 -i ${srcdir}/tcl-8.5.1-autopath.patch
-  patch -Np1 -i ${srcdir}/tcl-8.5.10-conf.patch
-  patch -Np1 -i ${srcdir}/tcl-8.5.9-hidden.patch
-  patch -Np0 -i ${srcdir}/tcl-8.5.6-mingw32.patch
-  patch -Np0 -i ${srcdir}/tcl-nativetclsh.patch
-  patch -Np0 -i ${srcdir}/tcl-mingw-w64-compatibility.patch
+  patch -Np1 -i "${srcdir}/tcl-8.5.14-autopath.patch"
+  patch -Np1 -i "${srcdir}/tcl-8.5.14-conf.patch"
+  patch -Np1 -i "${srcdir}/tcl-8.5.14-hidden.patch"
+  patch -Np1 -i "${srcdir}/tcl-8.6.1-mingwexcept.patch"
+  patch -Np0 -i "${srcdir}/tcl-mingw-w64-compatibility.patch"
 
+}
+
+build() {
   unset LDFLAGS
   unset CFLAGS
 
-  pushd win
+  cd "${srcdir}/tcl${pkgver}/win"
   autoconf
+  cd "${srcdir}"
+  
+  # out of source building failed for me. Did not try fixing it.
+  cp -R tcl${pkgver} tcl${pkgver}-i686-w64-mingw32
+  mv tcl${pkgver} tcl${pkgver}-x86_64-w64-mingw32
 
-  _arch="i686-w64-mingw32" # doesn't compile on 64bit arch, but keep pkgbuild with _arch for the future
+  for _arch in ${_architectures}; do
+    pushd tcl${pkgver}-${_arch}/win
+    [ "${_arch}" = 'x86_64-w64-mingw32' ] && enable64bit='--enable-64bit'
+    ./configure \
+      --prefix=/usr/${_arch} \
+      --host=${_arch} \
+      --disable-threads \
+      --enable-shared \
+      $enable64bit
+    make -j1 TCL_LIBRARY=/usr/${_arch}/share/tcl${_majorver}
 
-  ./configure \
-    --prefix=/usr/${_arch} \
-    --host=${_arch} \
-    --disable-threads \
-    --enable-shared
-  make -j1 TCL_LIBRARY=/usr/${_arch}/share/tcl${_majorver}
-
-  popd # win
+    popd
+  done
 }
 
 package() {
-  cd "${srcdir}/tcl${pkgver}"
+  cd "${srcdir}"
 
-  _arch="i686-w64-mingw32" # doesn't compile on 64bit arch, but keep pkgbuild with _arch for the future
+  for _arch in ${_architectures}; do
+    pushd tcl${pkgver}-${_arch}
+    
+    make install -j1 -C win INSTALL_ROOT="${pkgdir}" TCL_LIBRARY=/usr/${_arch}/share/tcl${_majorver}
 
-  make install -j1 -C win INSTALL_ROOT=${pkgdir} TCL_LIBRARY=/usr/${_arch}/share/tcl${_majorver}
+    ln -s tclsh${_majorver1}${_majorver2}.exe "${pkgdir}/usr/${_arch}/bin/tclsh.exe"
 
-  ln -s tclsh${_majorver1}${_majorver2}.exe ${pkgdir}/usr/${_arch}/bin/tclsh.exe
+    mv "${pkgdir}/usr/${_arch}/lib/libtcl${_majorver1}${_majorver2}.a" "${pkgdir}/usr/${_arch}/lib/libtcl${_majorver1}${_majorver2}.dll.a"
+    mv "${pkgdir}/usr/${_arch}/lib/libtclstub${_majorver1}${_majorver2}.a" "${pkgdir}/usr/${_arch}/lib/libtclstub${_majorver1}${_majorver2}.dll.a"
+    
+    # for linking with -libtcl
+    ln -s libtcl${_majorver1}${_majorver2}.dll.a "${pkgdir}/usr/${_arch}/lib/libtcl.dll.a"
 
-  mv ${pkgdir}/usr/${_arch}/lib/libtcl${_majorver1}${_majorver2}.a ${pkgdir}/usr/${_arch}/lib/libtcl${_majorver1}${_majorver2}.dll.a
-  mv ${pkgdir}/usr/${_arch}/lib/libtclstub${_majorver1}${_majorver2}.a ${pkgdir}/usr/${_arch}/lib/libtclstub${_majorver1}${_majorver2}.dll.a
-  
-  # for linking with -libtcl
-  ln -s libtcl${_majorver1}${_majorver2}.dll.a ${pkgdir}/usr/${_arch}/lib/libtcl.dll.a
+    ln -s ../share/tcl${_majorver} "${pkgdir}/usr/${_arch}/lib/tcl${_majorver}"
 
-  ln -s ../share/tcl${_majorver} ${pkgdir}/usr/${_arch}/lib/tcl${_majorver}
+    # postgresql and maybe other packages too need tclConfig.sh
+    # paths don't look at /usr/lib for efficiency, so we symlink into tcl8.5 for now
+    ln -s /usr/${_arch}/lib/tclConfig.sh "${pkgdir}/usr/${_arch}/lib/tcl${_majorver}/tclConfig.sh"
 
-  # postgresql and maybe other packages too need tclConfig.sh
-  # paths don't look at /usr/lib for efficiency, so we symlink into tcl8.5 for now
-  ln -s /usr/${_arch}/lib/tclConfig.sh ${pkgdir}/usr/${_arch}/lib/tcl${_majorver}/tclConfig.sh
+    mkdir -p "${pkgdir}/usr/${_arch}/include/tcl-private/"{generic,win}
+    find generic win -name "*.h" -exec cp -p '{}' "${pkgdir}"/usr/${_arch}/include/tcl-private/'{}' ';'
+    ( cd "${pkgdir}/usr/${_arch}/include"
+      for i in *.h ; do
+	[ -f "${pkgdir}/usr/${_arch}/include/tcl-private/generic/$i" ] && ln -sf ../../$i "${pkgdir}/usr/${_arch}/include/tcl-private/generic" ;
+      done
+    ) || true
 
-  mkdir -p ${pkgdir}/usr/${_arch}/include/tcl-private/{generic,win}
-  find generic win -name "*.h" -exec cp -p '{}' ${pkgdir}/usr/${_arch}/include/tcl-private/'{}' ';'
-  ( cd ${pkgdir}/usr/${_arch}/include
-    for i in *.h ; do
-      [ -f ${pkgdir}/usr/${_arch}/include/tcl-private/generic/$i ] && ln -sf ../../$i ${pkgdir}/usr/${_arch}/include/tcl-private/generic ;
-    done
-  ) || true
+    # fix executable bits
+    chmod a-x "${pkgdir}/usr/${_arch}/share/tcl${_majorver}/encoding/"*.enc
+    chmod a-x "${pkgdir}/usr/${_arch}/lib/"*/pkgIndex.tcl
 
-  # fix executable bits
-  chmod a-x ${pkgdir}/usr/${_arch}/share/tcl${_majorver}/encoding/*.enc
-  chmod a-x ${pkgdir}/usr/${_arch}/lib/*/pkgIndex.tcl
+    # remove buildroot traces
+    sed -i -e "s|$PWD/win|/usr/${_arch}/lib|; s|$PWD|/usr/${_arch}/include/tcl-private|" "${pkgdir}//usr/${_arch}/lib/tclConfig.sh"
+    rm -rf "${pkgdir}/usr/${_arch}/share/tcl${_majorver}/tclAppInit.c"
+    rm -rf "${pkgdir}/usr/${_arch}/share/tcl${_majorver}/ldAix"
 
-  # remove buildroot traces
-  sed -i -e "s|$PWD/win|/usr/${_arch}/lib|; s|$PWD|/usr/${_arch}/include/tcl-private|" ${pkgdir}//usr/${_arch}/lib/tclConfig.sh
-  rm -rf ${pkgdir}/usr/${_arch}/share/tcl${_majorver}/tclAppInit.c
-  rm -rf ${pkgdir}/usr/${_arch}/share/tcl${_majorver}/ldAix
+    # move windows packages to where tcl85.dll will find them
+    mv "${pkgdir}/usr/${_arch}/lib/dde"* "${pkgdir}/usr/${_arch}/lib/tcl${_majorver}/"
+    mv "${pkgdir}/usr/${_arch}/lib/reg"* "${pkgdir}/usr/${_arch}/lib/tcl${_majorver}/"
 
-  # move windows packages to where tcl85.dll will find them
-  mv ${pkgdir}//usr/${_arch}/lib/dde* ${pkgdir}//usr/${_arch}/lib/tcl${_majorver}/
-  mv ${pkgdir}//usr/${_arch}/lib/reg* ${pkgdir}//usr/${_arch}/lib/tcl${_majorver}/
+    # Strip
+    ${_arch}-strip --strip-all "${pkgdir}/usr/${_arch}/bin/"*.exe
+    ${_arch}-strip --strip-unneeded "${pkgdir}/usr/${_arch}/bin/"*.dll
+    ${_arch}-strip --strip-debug "${pkgdir}/usr/${_arch}/lib/"*.a
 
-  # Strip
-  ${_arch}-strip --strip-all ${pkgdir}/usr/${_arch}/bin/*.exe
-  ${_arch}-strip --strip-unneeded ${pkgdir}/usr/${_arch}/bin/*.dll
-  ${_arch}-strip --strip-debug ${pkgdir}/usr/${_arch}/lib/*.a
+    popd
+  done
 }
 
 # vim:set ts=2 sw=2 et:
