updated on Wed Jul  4 14:00:24 UTC 2012

diff --git a/tunlr/tunlr b/tunlr/tunlr
--- a/tunlr/tunlr
+++ b/tunlr/tunlr
@@ -1,68 +1,93 @@
 #!/bin/bash
 
-# tunlr 0.1.2 - watch netflix, mtv, cbs, hulu and more outside the u.s.
+# tunlr 0.1.3 - watch netflix, mtv, cbs, hulu and more outside the u.s.
 # for more information please visit <http://tunlr.net/>
 #
 # Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
 # License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
 
-log=/tmp/tunlr-errors
-rslv=/etc/resolv.conf
-conf=/etc/tunlr/tunlr_dns
+LOG=$(mktemp)
+RSLV=/etc/resolv.conf
+CONF=/etc/tunlr/tunlr_dns
+IP='\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'
 
-if [ $UID != 0 ] && [ "$1" == "start" -o "$1" == "stop" -o "$1" == "update" ]; then
-	echo "you must be root to run 'tunlr $1'"; exit 1
+if [ $UID != 0 ] && [[ "$1" =~ start|stop|update ]]
+then
+   echo "you must be root to run 'tunlr $1'" 1>&2
+   exit 1
 fi
 
-err() { echo "failed"; cat $log; exit 1; }
+err() {
+   echo "failed"
+   cat $LOG
+   exit 1
+}
 
 case "$1" in
-start)
-	echo -n "starting tunlr... "
-	if [ -f $rslv.bak ]; then
-		echo -e "failed\n$rslv.bak does already exist - nothing will be changed"
-		exit 1
-	else
-		cp $rslv $rslv.bak 2>$log || err
-	fi
-	cat $conf $rslv.bak >$rslv 2>$log || err
-	echo -e "ok\nrestart your web browser to apply the changes"
-	;;
-stop)
-	echo -n "stopping tunlr... "
-	if [ -f $rslv.bak ]; then
-		cp $rslv.bak $rslv 2>$log || err
-		rm $rslv.bak 2>$log || err
-		echo -e "ok\nrestart your web browser to apply the changes"
-	else
-		echo -e "failed\n$rslv.bak does not exist - unable to restore DNS config"
-		exit 1
-	fi
-	;;
-update)
-	echo -n "updating tunlr dns server... "
-	cp $conf $conf.bak &>/dev/null
-	> $conf
-	if ping -q -c 1 tunlr.net &>/dev/null; then
-		for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>' | uniq); do
-			echo "nameserver $srv" >>$conf
-		done
-	else
-		echo -e "failed\ntunlr.net seems to be down - please try again later"
-		exit 1
-	fi
-	if [ -s $conf ]; then
-		echo "ok"
-		echo "updated $conf:"
-		cat $conf
-		rm $conf.bak &>/dev/null
-	else
-		echo -e "failed\nrestoring old config file"
-		mv $conf.bak $conf
-	fi
-	;;
-*)
-	echo "usage: $0 {start|stop|(update)}"
-	;;
+   start)
+      echo -n "starting tunlr... "
+
+      if [ -f $RSLV.bak ]
+      then
+         echo -e "failed\n$RSLV.bak does already exist - nothing will be changed"
+         exit 1
+      else
+         cp $RSLV $RSLV.bak 2>$LOG || err
+      fi
+
+      cat $CONF $RSLV.bak >$RSLV 2>$LOG || err
+      echo -e "ok\nrestart your web browser to apply the changes"
+      ;;
+
+   stop)
+      echo -n "stopping tunlr... "
+
+      if [ -f $RSLV.bak ]
+      then
+         cp $RSLV.bak $RSLV 2>$LOG || err
+         rm $RSLV.bak 2>$LOG || err
+         echo -e "ok\nrestart your web browser to apply the changes"
+      else
+         echo -e "failed\n$RSLV.bak does not exist - unable to restore DNS config"
+         exit 1
+      fi
+      ;;
+
+   update)
+      echo -n "updating tunlr dns server... "
+      cp $CONF $CONF.bak &>/dev/null
+      > $CONF
+
+      if ping -q -c 1 tunlr.net &>/dev/null
+      then
+         for SRV in $(wget -q -O - http://tunlr.net/get-started/ | grep -Eo $IP | uniq)
+         do
+            echo "nameserver $SRV" >>$CONF
+         done
+      else
+         echo -e "failed\ntunlr.net seems to be down - please try again later"
+         exit 1
+      fi
+
+      if [ -s $CONF ]
+      then
+         echo "ok"
+         echo "updated $CONF:"
+         cat $CONF
+         rm $CONF.bak &>/dev/null
+      else
+         echo -e "failed\nrestoring old configuration file"
+         mv $CONF.bak $CONF
+      fi
+      ;;
+
+   *)
+      echo "usage: $0 {start|stop|update}"
 esac
+
+if [ -f $LOG ] && [ -O $LOG ]
+then
+   rm $LOG
+fi
+
 exit 0
