updated on Wed Apr 11 16:00:14 UTC 2012

diff --git a/tunlr/tunlr b/tunlr/tunlr
--- a/tunlr/tunlr
+++ b/tunlr/tunlr
@@ -1,53 +1,80 @@
 #!/bin/bash
 
-# tunlr - watch netflix, mtv, cbs, hulu and more outside the u.s.
+# tunlr 0.0.4 - watch netflix, mtv, cbs, hulu and more outside the u.s.
 # for more information please visit <http://tunlr.net/>
 #
-# copyright: (c) 2012 edloaa <edloaa at googlemail dot com>
-# license: gpl-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
+# Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
+# License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
 
 if [ $UID != 0 ]; then
 	echo "you must be root to run tunlr"
 	exit 1
 fi
 
+log=/tmp/tunlr-errors
+rslv=/etc/resolv.conf
+conf=/etc/tunlr/tunlr_dns
+
+err()
+{
+	echo "failed"
+	cat $log
+	exit 1
+}
+
 case "$1" in
 	start)
-		echo "starting tunlr"
-		if [ ! -f /etc/resolv.conf.bak ]; then
-			cp /etc/resolv.conf /etc/resolv.conf.bak
+		echo -n "starting tunlr... "
+		if [ ! -f $rslv.bak ]; then
+			cp $rslv $rslv.bak 2>$log || err
 		fi
-		cat /etc/tunlr/tunlr_dns > /etc/resolv.conf
-		cat /etc/resolv.conf.bak >> /etc/resolv.conf
+		cat $conf $rslv.bak >$rslv 2>$log || err
+		echo "ok"
 		echo "restart your web browser to apply the changes"
 		;;
 
 	stop)
-		echo "stopping tunlr"
-		if [ ! -f /etc/resolv.conf.bak ]; then
-			echo "/etc/resolv.conf.bak does not exsist. unable to restore DNS config"
+		echo -n "stopping tunlr... "
+		if [ -f $rslv.bak ]; then
+			cp $rslv.bak $rslv 2>$log || err
+			rm $rslv.bak 2>$log || err
+			echo "ok"
+			echo "restart your web browser to apply the changes"
+		else
+			echo "failed"
+			echo "$rslv.bak does not exsist. unable to restore DNS config"
 			exit 1
 		fi
-		cp /etc/resolv.conf.bak /etc/resolv.conf
-		rm /etc/resolv.conf.bak
-		echo "restart your web browser to apply the changes"
 		;;
 
 	update)
-		echo "updating tunlr dns server"
-		if [ $(ping -q -c 1 tunlr.net &>/dev/null; echo $?) -ne 0 ]; then
+		echo -n "updating tunlr dns server... "
+		cp $conf $conf.bak >/dev/null 2>&1
+		> $conf
+		if [ $(ping -q -c 1 tunlr.net >/dev/null 2>&1; echo $?) -eq 0 ]; then
+			for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'); do
+				echo "nameserver $srv" >>$conf
+			done
+		else
+			echo "failed"
 			echo "tunlr.net seems to be down. please try again later"
 			exit 1
 		fi
-		rm /etc/tunlr/tunlr_dns
-		for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'); do
-			echo "adding $srv"
-			echo "nameserver $srv" >> /etc/tunlr/tunlr_dns
-		done
+		if [ -f $conf ] && [ -s $conf ]; then 
+			echo "ok"
+			echo "$conf:"
+			cat $conf
+			rm $conf.bak >/dev/null 2>&1
+		else
+			echo "failed"
+			echo "restoring old config file"
+			mv $conf.bak $conf
+		fi
 		;;
 
 	*)
 		echo "usage: $0 {start|stop|update}"
 		;;
+
 esac
 exit 0
