updated on Thu May  3 17:08:00 UTC 2012

diff --git a/tunlr/tunlr b/tunlr/tunlr
--- a/tunlr/tunlr
+++ b/tunlr/tunlr
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# tunlr 0.1.1 - watch netflix, mtv, cbs, hulu and more outside the u.s.
+# tunlr 0.1.2 - watch netflix, mtv, cbs, hulu and more outside the u.s.
 # for more information please visit <http://tunlr.net/>
 #
 # Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
@@ -10,35 +10,32 @@ log=/tmp/tunlr-errors
 rslv=/etc/resolv.conf
 conf=/etc/tunlr/tunlr_dns
 
-[ $UID != 0 ] && [ "$1" == "start" -o "$1" == "stop" -o "$1" == "update" ] && {
-	echo "you must be root to run 'tunlr $1'"
-	exit 1
-}
+if [ $UID != 0 ] && [ "$1" == "start" -o "$1" == "stop" -o "$1" == "update" ]; then
+	echo "you must be root to run 'tunlr $1'"; exit 1
+fi
 
-err() {
-	echo "failed"
-	cat $log
-	exit 1
-}
+err() { echo "failed"; cat $log; exit 1; }
 
 case "$1" in
 start)
 	echo -n "starting tunlr... "
-	[ ! -f $rslv.bak ] && { cp $rslv $rslv.bak 2>$log || err; }
+	if [ -f $rslv.bak ]; then
+		echo -e "failed\n$rslv.bak does already exist - nothing will be changed"
+		exit 1
+	else
+		cp $rslv $rslv.bak 2>$log || err
+	fi
 	cat $conf $rslv.bak >$rslv 2>$log || err
-	echo "ok"
-	echo "restart your web browser to apply the changes"
+	echo -e "ok\nrestart your web browser to apply the changes"
 	;;
 stop)
 	echo -n "stopping tunlr... "
 	if [ -f $rslv.bak ]; then
 		cp $rslv.bak $rslv 2>$log || err
 		rm $rslv.bak 2>$log || err
-		echo "ok"
-		echo "restart your web browser to apply the changes"
+		echo -e "ok\nrestart your web browser to apply the changes"
 	else
-		echo "failed"
-		echo "$rslv.bak does not exsist. unable to restore DNS config"
+		echo -e "failed\n$rslv.bak does not exist - unable to restore DNS config"
 		exit 1
 	fi
 	;;
@@ -47,27 +44,25 @@ update)
 	cp $conf $conf.bak &>/dev/null
 	> $conf
 	if ping -q -c 1 tunlr.net &>/dev/null; then
-		for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'); do
-				echo "nameserver $srv" >>$conf
+		for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>' | uniq); do
+			echo "nameserver $srv" >>$conf
 		done
 	else
-		echo "failed"
-		echo "tunlr.net seems to be down. please try again later"
+		echo -e "failed\ntunlr.net seems to be down - please try again later"
 		exit 1
 	fi
-	if [ -f $conf ] && [ -s $conf ]; then 
+	if [ -s $conf ]; then
 		echo "ok"
-		echo "$conf:"
+		echo "updated $conf:"
 		cat $conf
 		rm $conf.bak &>/dev/null
 	else
-		echo "failed"
-		echo "restoring old config file"
+		echo -e "failed\nrestoring old config file"
 		mv $conf.bak $conf
 	fi
 	;;
 *)
-	echo "usage: $0 {start|stop|update}"
+	echo "usage: $0 {start|stop|(update)}"
 	;;
 esac
 exit 0
