updated on Wed Apr 24 08:13:21 UTC 2013

diff --git a/cjdns-git/PKGBUILD b/cjdns-git/PKGBUILD
--- a/cjdns-git/PKGBUILD
+++ b/cjdns-git/PKGBUILD
@@ -2,7 +2,7 @@
 # Maintainer: Prurigro
 
 pkgname=cjdns-git
-pkgver=130221
+pkgver=130424
 pkgrel=1
 pkgdesc="A routing engine designed for security, scalability, speed and ease of use."
 url="https://github.com/cjdelisle/cjdns"
@@ -36,8 +36,18 @@ build() {
     fi
 
     pushd "$srcdir"/cjdns
-        # BUILD CJDNS
-        ./do
+        # BUILD CJDNS (Building manually for the time being to disable the debug flag -g because it causes the build to fail with gcc 4.8.0)
+        #./do
+        mkdir build
+        pushd build
+            NO_DEBUG=1 cmake ..
+            make
+            make test
+            [ ! -f ../cjdroute ] || rm ../cjdroute || exit 1;
+            [ ! -f ../cjdns ] || rm ../cjdns || exit 1;
+            cp admin/angel/cjdroute2 ../cjdroute || exit 1;
+            cp admin/angel/cjdns ../ || exit 1;
+        popd
 
         # PATCH 'cjdnslog' IF NOT FIXED UPSTREAM
         if [ $(grep -c python2 contrib/python/cjdnslog) = 0 ]; then
