updated on Wed Aug 31 13:07:51 UTC 2011

diff --git a/nottetris2/PKGBUILD b/nottetris2/PKGBUILD
--- a/nottetris2/PKGBUILD
+++ b/nottetris2/PKGBUILD
@@ -2,36 +2,50 @@
 
 pkgname=nottetris2
 pkgver=1
-pkgrel=2
+pkgrel=3
 pkgdesc="Basically it's a little like tetris except with a twist."
 arch=('any')
-url="http://stabyourself.net/"
-license=('CUSTOM')
+url="http://stabyourself.net/nottetris2/"
+license=('CUSTOM: Freeware')
 depends=('love')
-makedepends=()
-replaces=()
-#source=(http://stabyourself.net/dl.php?file=${pkgname}/${pkgname}-linux.zip ${pkgname} ${pkgname}.desktop )
-source=(http://ompldr.org/vYTRreQ/${pkgname}-linux.zip ${pkgname} ${pkgname}.desktop )
-md5sums=('28819e89a05318c8d69c0afef5bc96d9'
-         'f806a800bc24afbd7a4d2d0b395c342b'
-         'cbf0014e3832fca4a007c8255555b3be')
+makedepends=('unzip')
+source=(${pkgname}.sh ${pkgname}.desktop)
+_gamepkg="${pkgname}-linux.zip"
 
-build() {
-  cd ${srcdir}
-  true
+md5sums=('9083928b68efb15eaa72475abf9dafbe'
+         '1b04f1d2edc1bbaafd3ebb350ff57895')
+
+build(){
+  cd $srcdir
+  msg "You need a full copy of this game in order to install it"
+  msg "Searching for \"${_gamepkg}\" in dir: $(readlink -f `pwd`/..)"
+    pkgpath=$startdir
+    if [[ ! -f "$startdir/${_gamepkg}" ]]; then
+       error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
+       read pkgpath
+       if [[ ! -f "${pkgpath}/${_gamepkg}" ]]; then
+           error "Unable to find game package." && return 1
+       fi
+    fi
+  msg "Found game package, installing..."
+
+  ln -fs ${pkgpath}/${_gamepkg} . || return 1
+  unzip ${srcdir}/${_gamepkg} -d  $srcdir/${pkgname} || return 1
+
 }
 package() {
+    cd $srcdir
+
     # Install Data
-    install -D -m755 ${srcdir}/"Not Tetris 2.love" $pkgdir/opt/${pkgname}/${pkgname}.love
-    install -D -m644 ${srcdir}/"Not Readme".txt $pkgdir/opt/${pkgname}/"Not Readme".txt
+    install -D -m755 "${srcdir}/${pkgname}/Not Tetris 2.love" "${pkgdir}/usr/share/games/${pkgname}/${pkgname}.love"
+    install -D -m644 "${srcdir}/${pkgname}/Not Readme.txt" "$pkgdir/usr/share/games/${pkgname}/readme"
 
     # Install Launcher
-    install -D -m755 ${srcdir}/${pkgname} $pkgdir/usr/bin/${pkgname}
+    install -D -m755 "${srcdir}/${pkgname}.sh" "${pkgdir}/usr/bin/${pkgname}"
 
     # Install Desktop
-    install -D -m644 ${srcdir}/${pkgname}.desktop \
-        ${pkgdir}/usr/share/applications/${pkgname}.desktop
-
+    install -D -m644 "${srcdir}/${pkgname}.desktop" \
+        "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 
 }
 # vim:set ts=2 sw=2 et:
