updated on Tue Jul 19 11:31:00 UTC 2011

diff --git a/boh/PKGBUILD b/boh/PKGBUILD
--- a/boh/PKGBUILD
+++ b/boh/PKGBUILD
@@ -2,15 +2,16 @@
 pkgname=boh
 pkgver=20101208
 _build=1906
-pkgrel=1
+pkgrel=2
 pkgdesc="A world of claustrophobic, mysterious, puzzle-riddled, dangerous mazes where, surrounded by countless enemies, (requires copy of the full game)"
 url="http://www.gameolith.com/game/boh/"
 license=('custom: "commercial"')
 arch=('i686' 'x86_64')
 makedepends=()
-source=("${pkgname}_${pkgver}.${_build}_i386.deb" "boh.sh")
-md5sums=('ec8c67897828a78e4755cdbbb67d7449'
-         '3e5d79c3442c2eb5e75e5582bab49cbc')
+source=("boh.sh")
+md5sums=('3e5d79c3442c2eb5e75e5582bab49cbc')
+
+_gamepkg="${pkgname}_${pkgver}.${_build}_i386.deb"
 
 depends=('libglade' 'mesa' 'sdl_net')
 _depends64=('lib32-libglade' 'lib32-mesa' 'lib32-sdl_net')
@@ -20,7 +21,23 @@ if [[ $CARCH == x86_64 ]]; then
 fi
 
 build() {
-  cd ${srcdir}
+
+   cd ${srcdir}
+   msg "You need a full copy of this game in order to install it"
+   msg "Searching for ${_gamepkg} in dir: \"$startdir\""
+   pkgpath=$startdir
+   if [[ ! -f "$startdir/${_gamepkg}" ]]; then
+       error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
+       read pkgpath
+       if [[ ! -f "${pkgpath}/${_gamepkg}" ]]; then
+           error "Unable to find game package." && return 1
+       fi
+    fi
+    msg "Found game package, installing..."
+
+    ln -fs ${pkgpath}/${_gamepkg} . || return 1
+    #tar xvf ${pkgpath}/${_gamepkg} || return 1
+
   ar x ${pkgname}_${pkgver}.${_build}_i386.deb
   tar -zxf data.tar.gz
   mkdir -p ${pkgdir}/
@@ -32,7 +49,10 @@ package(){
   cd ${srcdir}
   install -Dm 755 ${srcdir}/boh.sh ${pkgdir}/usr/bin/boh
 
+  # Install license
+  install -D -m644 ${srcdir}/opt/BOH/licenses/README ${pkgdir}/usr/share/licenses/${pkgname}/readme.txt
+
   # Make save game Directory with user group permissions (config)
-      install -d -m775 -g users ${pkgdir}/opt/BOH/
+  install -d -m775 -g users ${pkgdir}/opt/BOH/
 
 }
