updated on Sat Dec 24 11:00:51 UTC 2011

diff --git a/linux-ck/PKGBUILD b/linux-ck/PKGBUILD
--- a/linux-ck/PKGBUILD
+++ b/linux-ck/PKGBUILD
@@ -1,22 +1,16 @@
 # Contributor: graysky <graysky AT archlinux DOT us>
 # Contributor: Tobias Powalowski <tpowa@archlinux.org>
 # Contributor: Thomas Baechler <thomas@archlinux.org>
-###########################################################################################################
-#                                          Patch and Build Options
-###########################################################################################################
-#
-## Note all kernels get the ck patch set with BFS so there is no option to enable/disable it!
-#
-_usearchlogo="n"  # use the blue Arch logo rather than default tux logo when booting
-_makenconfig="n"	# select additional kernel options prior to a build via nconfig
-_localmodcfg="n"	# compile ONLY probed modules - see notes below!
-_localyescfg="n"	# convert all modules to core - see notes below!
-_use_current="n"	# use the current kernel's .config file - see notes below!
+
+## PATCH AND BUILD OPTIONS
+_usearchlogo="n"  # use the blue Arch logo when booting
+_makenconfig="n"	# tweak kernel options prior to a build via nconfig
+_localmodcfg="n"	# compile ONLY probed modules
+_use_current="n"	# use the current kernel's .config file
 _BFQ_enable_="n"	# enable BFQ as the default I/O scheduler
-###########################################################################################################
-#                                        More Details and References
-###########################################################################################################
-## LOCALMODCONFIG OPTION
+
+## DETAILS FOR _localmodcfg="y"
+#
 #  As of mainline 2.6.32, running with this option will only build the modules that you currently have
 #  probed in your system VASTLY reducing the number of modules built and the build time to do it.
 #
@@ -25,21 +19,16 @@ _BFQ_enable_="n"	# enable BFQ as the default I/O scheduler
 #  To keep track of which modules are needed for your specific system/hardware, give my module_db script
 #  a try: http://aur.archlinux.org/packages.php?ID=41689  Note that if you use my script, this PKGBUILD 
 #  will auto run the reload_data base for you to probe all the modules you have logged!
+#
 #  More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed_db
-#
-## LOCALYESCONFIG OPTION
-#  This adds the option localyesconfig to make. This is similar to localmodconfig, but after it removes
-#  unnecessary modules it runs "sed -i s/=m/=y/" on the .config file. It then runs "make silentoldconfig"
-#  to fix any holes that were created by the conversion of modules to core.
-#
-## USE CURRENT KERNEL'S .CONFIG
+
+## DETAILS FOR _use_current="y"
 #  Enabling this option will use the .config of the RUNNING kernel rather than the ARCH defaults.
 #  Useful when the package gets updated and you already went through the trouble of customizing your
 #  config options.  NOT recommended when a new kernel is released, but again, convenient for package bumps.
-#
-## BFQ
+
+## DETAILS FOR _BFQ_enable="y"
 #  Alternative I/O scheduler by Paolo.  For more, see: http://algo.ing.unimo.it/people/paolo/disk_sched/
-###########################################################################################################
 
 pkgname=linux-ck
 true && pkgname=(linux-ck linux-ck-headers)
@@ -172,8 +161,10 @@ build() {
 		-i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
 
 	### Optionally enable BFQ as the default io scheduler
-	[[ $_BFQ_enable_ = "y" ]] && sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
+	if [ $_BFQ_enable_ = "y" ]; then
+		sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
 		-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	fi
 
 	# set extraversion to pkgrel
 	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
@@ -187,16 +178,11 @@ build() {
 	if [ $_localmodcfg = "y" ]; then
 		msg "If you have modprobe_db installed, running reload_database now"
 		if [ -e /usr/bin/reload_database ]; then
-			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
 			sudo /usr/bin/reload_database
 		fi
 		msg "Running Steven Rostedt's make localmodconfig now"
 		make localmodconfig
-	fi
-
-	if [ $_localyescfg = "y" ]; then
-		msg "Running make localyesconfig"
-		make localyesconfig
 	fi
 
 	if [ $_makenconfig = "y" ]; then
