updated on Tue Feb 26 00:05:41 UTC 2013

diff --git a/haxe2/PKGBUILD b/haxe2/PKGBUILD
--- a/haxe2/PKGBUILD
+++ b/haxe2/PKGBUILD
@@ -3,35 +3,39 @@
 # Contributor: Patrick Hof <courts@offensivethinking.org>
 # Contributor: Michael Fellinger <mf@rubyists.com>
 
-pkgname=haxe
-pkgver=3.00.rc1
-pkgrel=2
+pkgname=haxe2
+pkgver=2.10
+pkgrel=1
 pkgdesc="A multiplatform open source programming language"
 arch=('i686' 'x86_64')
 url='http://haxe.org/'
 license=('GPL2')
 groups=('devel')
-depends=('neko>=2.0.0' 'sh')
-makedepends=('subversion' 'ocaml>=4.00.0' 'zlib' 'neko>=2.0.0')
+depends=('neko>=1.8.2')
+makedepends=('subversion' 'ocaml>=4.00.0' 'zlib' 'neko>=1.8.2')
 provides=('haxe')
 options=('!strip' 'emptydirs' '!makeflags')
 install=haxe.install
 source=('haxeserver'
         'haxe.sh'
-        'haxe.csh')
+        'haxe.csh'
+        'extlib.patch')
+	
 md5sums=('27d7af131da515355cca04b8b404feaa'
          '79cbf6ebdb3d56e980d1a17fa9cb3b2d'
-         '5e0e656293e92a6437d76f2f406438b5')
+         '5e0e656293e92a6437d76f2f406438b5'
+         'ae26bfc2ba01b870ba6ad2b3183b37af')
 
 
-_tag="http://haxe.googlecode.com/svn/tags/v${pkgver//./-}"
+#_tag="http://haxe.googlecode.com/svn/tags/v${pkgver/./-}"
+_tag="http://haxe.googlecode.com/svn/branches/v${pkgver/./-}-fix"
 _buildroot="$srcdir/$pkgname"
 
 build() {
   cd "$srcdir"
   msg "Connecting to SVN server...."
   if [[ -d "$pkgname/.svn" ]]; then
-    (cd "$pkgname" && svn up )
+    (cd "$pkgname" && svn revert libs/extlib/extHashtbl.mli && svn up)
   else
     svn co "$_tag" --config-dir ./ "$pkgname"
   fi
@@ -43,25 +47,34 @@ build() {
   #
   # BUILD HERE
   #
-  msg "Cleaning up..."
+
+  # clean up first
+  patch -p1 < "$srcdir"/extlib.patch
   make clean > /dev/null
+  for i in haxe{lib,doc}; do
+   [ -f "$_buildroot/std/tools/$i/$i" ] && rm "$_buildroot/std/tools/$i/$i"
+  done
+  
+  make || return 1
   msg2 "done."
-  msg "Building libs..." && make libs || return 1
-  msg2 "done."
-  msg "Building haxe..." && make haxe || return 1
-  msg2 "done."
-  msg "Building tools..." && make tools || return 1  
-  msg2 "done."  
+
   msg "Generating api docs..."  
-  cd $_buildroot/doc 
-  rm -rf content *.xml
-  env HAXE_LIBRARY_PATH=$_buildroot/std $_buildroot/haxe all.hxml  
-  [ ! \( -f flash8.xml -a -f flash9.xml -a -f neko.xml -a -f js.xml -a -f php.xml -a -f cpp.xml \) ] && return 1
-  $_buildroot/std/tools/haxedoc/haxedoc -v "flash8.xml;flash8;flash" "neko.xml;neko" "js.xml;js" "flash9.xml;flash" "php.xml;php" "cpp.xml;cpp"
-  _res=$?
-  if [ $_res -eq 0 ]; then _msg="done."; else _msg="failed."; fi
-  echo && msg2 $_msg; 
-  return $_res
+  cd doc && env HAXE_LIBRARY_PATH=$_buildroot/std $_buildroot/haxe all.hxml
+  if [ -f flash8.xml -a -f flash9.xml -a -f neko.xml -a -f js.xml -a \
+       -f php.xml -a -f cpp.xml -a -f cs.xml -a -f java.xml ]; then 
+    $_buildroot/std/tools/haxedoc/haxedoc -v \
+      "flash8.xml;flash8;flash" "neko.xml;neko" "js.xml;js" \
+      "flash9.xml;flash" "php.xml;php" "cpp.xml;cpp" \
+      "cs.xml;cs" "java.xml;java"
+    if [ $? -eq 0 ]; then
+      echo 
+      msg2 "done."
+    else
+      echo 
+      msg2 "failed." 
+      return 1
+    fi
+  fi
 }
 
 package() {
