updated on Sat Aug 13 09:31:00 UTC 2011

diff --git a/hammerfight/PKGBUILD b/hammerfight/PKGBUILD
--- a/hammerfight/PKGBUILD
+++ b/hammerfight/PKGBUILD
@@ -1,8 +1,8 @@
 # Maintainer: Gadget3000 <gadget3000 at msn dot com>
 
 pkgname=hammerfight
-pkgver=20111707
-pkgrel=5
+pkgver=20110812
+pkgrel=1
 pkgdesc="A 2D physics-based video game in which you swing large melee weapons to destroy enemies"
 arch=('i686' 'x86_64')
 url="http://www.koshutin.com/"
@@ -12,49 +12,62 @@ makedepends=('unzip' 'imagemagick')
 source=(hammerfight.desktop)
 md5sums=('e23ba95fa5623d37bdd0f3b520e36343')
 install=('hammerfight.install')
-if [ "$CARCH" = "x86_64" ]; then
-	depends=('lib32-openal' 'lib32-gcc-libs' 'lib32-sdl' 'hicolor-icon-theme')
-else
-	depends=('openal' 'gcc-libs' 'sdl' 'hicolor-icon-theme')
-fi
+depends=('openal' 'gcc-libs' 'sdl' 'hicolor-icon-theme')
 
-_archive="hf-linux-07172011-bin"
-_archive_md5="4b979c6d0741aa0626018cf451309c25"
+_archive="hf-linux-08122011-bin"
+_archive_md5="73b3824c3a199a646f19d5a952fc1c44"
 
 build() {
   install -Dd ${srcdir}/extractedInstaller
   cd $srcdir
 
-  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-	rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-        wget http://www.humblebundle.com/?key=${_humblebundle3key}
-        wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-        mv ${_archive}* ${_archive}
-  elif [ -z "${_humblebundle3key}" ]; then
-        echo You can now automate the download of the archive using the _humblebundle3key bash variable.
-        echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
-        echo
-        echo Otherwise please just place ${_archive} into $(pwd)/
-        echo Press Enter to continue
-        read -a _unused
+  if [ ! -f ${_hammerfightarchivelocation}${_archive} ]; then
+	  if [ -n "${_hammerfightarchivelocation}" ] && [ $(echo ${_hammerfightarchivelocation} | rev | cut -c 1) != "/" ]; then
+		echo _hammerfightarchivelocation must end in /
+		return 1
+	  fi
+	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
+		rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
+        	wget http://www.humblebundle.com/?key=${_humblebundle3key}
+	        wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
+	        mv ${_archive}* ${_archive}
+	  elif [ -z "${_humblebundle3key}" ]; then
+	        echo You can now automate the download of the archive using the _humblebundle3key bash variable.
+	        echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
+	        echo
+	        echo Otherwise please just place ${_archive} into $(pwd)/
+	        echo Press Enter to continue
+	        read -a _unused
+	  fi
   fi
 
-  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_archive}"
+  if [ ! -f ${_hammerfightarchivelocation}${_archive} ]; then
+    echo "${_hammerfightarchivelocation}${_archive} not found!"
+    return 1
+  fi
+
+  if ! echo "${_archive_md5}  ${_hammerfightarchivelocation}${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_hammerfightarchivelocation}${_archive}"
     return 1
   fi
 
   install -Dd ${pkgdir}/opt/
-  unzip -qqo hf-linux-07172011-bin -x guis/* meta/* scripts/* -d ${srcdir}/extractedInstaller/ && msg Finished Extracting
+  unzip -qqo ${_hammerfightarchivelocation}${_archive} -x guis/* meta/* scripts/* -d ${srcdir}/extractedInstaller/ && msg Finished Extracting
   install -Dd ${pkgdir}/opt/hammerfight
   mv ${srcdir}/extractedInstaller/data/* ${pkgdir}/opt/hammerfight/
 
-  rm -r ${pkgdir}/opt/hammerfight/lib*
+  rm -r ${pkgdir}/opt/hammerfight/{amd64,x86}
 
   install -Dd ${pkgdir}/usr/bin
   echo \#\!/bin/bash > ${pkgdir}/usr/bin/hammerfight
   echo /opt/hammerfight/Hammerfight >> ${pkgdir}/usr/bin/hammerfight
   chmod +x ${pkgdir}/usr/bin/hammerfight
+
+  if [ "$CARCH" = "x86_64" ]; then
+	rm -rf ${pkgdir}/opt/hammerfight/Hammerfight-x86
+  else
+	rm -rf ${pkgdir}/opt/hammerfight/Hammerfight-amd64
+  fi
 
   for i in 16x16 22x22 32x32 48x48 64x64 128x128; do
     mkdir -p ${pkgdir}/usr/share/icons/hicolor/${i}/apps
