updated on Thu Jul 28 08:01:06 UTC 2011

diff --git a/hammerfight/PKGBUILD b/hammerfight/PKGBUILD
--- a/hammerfight/PKGBUILD
+++ b/hammerfight/PKGBUILD
@@ -2,28 +2,42 @@
 
 pkgname=hammerfight
 pkgver=20111707
-pkgrel=1
+pkgrel=2
 pkgdesc="A 2D physics-based video game in which you swing large melee weapons to destroy enemies"
 arch=('i686' 'x86_64')
 url="http://www.koshutin.com/"
 license=('unknown')
+groups=('humblebundle3' 'humblebundles')
 makedepends=('unzip')
-#source=(hf-linux-07172011-bin)
-#noextract=()
-md5sums=('4b979c6d0741aa0626018cf451309c25') #generate with 'makepkg -g'
+source=(hammerfight.desktop)
+md5sums=('195982a823b269ddca43452314dba501')
+
+_archive="hf-linux-07172011-bin"
+_archive_md5="4b979c6d0741aa0626018cf451309c25"
 
 build() {
   install -Dd ${srcdir}/extractedInstaller
   cd $srcdir
-  echo Please place hf-linux-07172011-bin into $(pwd)
-  echo Press Enter to continue
-  read -a _unused
+
+  if [ ! -f ${_archive} ]; then
+	  echo Please place hf-linux-07172011-bin into $(pwd)
+	  echo Press Enter to continue
+	  read -a _unused
+  fi
+
+  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_archive}"
+    return 1
+  fi
+
   install -Dd ${pkgdir}/opt/
   unzip -qqo hf-linux-07172011-bin -x guis/* meta/* scripts/* -d ${srcdir}/extractedInstaller/ && msg Finished Extracting
   install -Dd ${pkgdir}/opt/hammerfight
   mv ${srcdir}/extractedInstaller/data/* ${pkgdir}/opt/hammerfight/
   install -Dd ${pkgdir}/usr/bin
-  echo \#\!/bin/bash > ${pkgdir}/usr/bin/Hammerfight
-  echo /opt/hammerfight/Hammerfight >> ${pkgdir}/usr/bin/Hammerfight
-  chmod +x ${pkgdir}/usr/bin/Hammerfight
+  echo \#\!/bin/bash > ${pkgdir}/usr/bin/hammerfight
+  echo /opt/hammerfight/Hammerfight >> ${pkgdir}/usr/bin/hammerfight
+  chmod +x ${pkgdir}/usr/bin/hammerfight
+
+  install -D ${srcdir}/hammerfight.desktop ${pkgdir}/usr/share/applications/hammerfight.desktop
 }
