updated on Tue Jan 22 01:24:58 UTC 2013

diff --git a/hammerfight/PKGBUILD b/hammerfight/PKGBUILD
--- a/hammerfight/PKGBUILD
+++ b/hammerfight/PKGBUILD
@@ -1,87 +1,50 @@
-# Maintainer: Gadget3000 <gadget3000 at msn dot com>
+# Contributor: Gadget3000 <gadget3000 at msn dot com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
 
 pkgname=hammerfight
 pkgver=1.004
 pkgrel=1
 epoch=1
-pkgdesc="A 2D physics-based video game in which you swing large melee weapons to destroy enemies"
+pkgdesc="A 2D physics-based video game in which you swing large melee weapons to destroy enemies (game sold separately)"
 arch=('i686' 'x86_64')
 url="http://www.koshutin.com/"
-license=('unknown')
+license=('custom')
 groups=('humblebundle3' 'humblebundle4' 'humblebundles')
-makedepends=('imagemagick')
-source=(hammerfight.desktop)
-md5sums=('e23ba95fa5623d37bdd0f3b520e36343')
-install='hammerfight.install'
-depends=('openal' 'gcc-libs' 'sdl' 'hicolor-icon-theme')
-
-_archive="hammerfight_1.004_all.tar.gz"
-_archive_md5="cc3fd17aa5849b0de3f0aa967ea8afe2"
+source=('hammerfight.desktop' "hib://${pkgname}_${pkgver}_all.tar.gz")
+md5sums=('8233b9a99ef7bfe02e358b8c9bb827b4' 'cc3fd17aa5849b0de3f0aa967ea8afe2')
+depends=('openal' 'gcc-libs' 'sdl')
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+PKGEXT='.pkg.tar'
 
 build() {
-  install -Dd ${srcdir}/extractedInstaller
-  cd $srcdir
+  cd "${srcdir}/${pkgname}"
 
-  if [ ! -f ${_hammerfightarchivelocation}${_archive} ]; then
-	  if [ -n "${_hammerfightarchivelocation}" ] && [ $(echo ${_hammerfightarchivelocation} | rev | cut -c 1) != "/" ]; then
-		echo _hammerfightarchivelocation must end in /
-		return 1
-	  fi
-	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-        	wget http://www.humblebundle.com/?key=${_humblebundle3key}
-	        wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-	        mv ${_archive}* ${_archive}
-          elif [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-                rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-                wget http://www.humblebundle.com/?key=${_humblebundle4key}
-                wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-                mv ${_archive}* ${_archive}
-	  elif [ -z "${_humblebundle3key}" ] && [ -z "${_humblebundle4key}" ]; then
-		echo You can now automate the download of the archive using the _humblebundle3key or _humblebundle4key bash variables.
-		echo Just add \'export _humblebundle3key\=\<Your key here\>\' and/or
-		echo \'export _humblebundle4key\=\<Your key here\>\' to \.bashrc
-		echo
-	        echo Otherwise please just place ${_archive} into $(pwd)/
-	        echo Press Enter to continue
-	        read -a _unused
-	  fi
-  fi
-
-  if [ ! -f ${_hammerfightarchivelocation}${_archive} ]; then
-    echo "${_hammerfightarchivelocation}${_archive} not found!"
-    return 1
-  fi
-
-  if ! echo "${_archive_md5}  ${_hammerfightarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_hammerfightarchivelocation}${_archive}"
-    return 1
-  fi
-
-  install -Dd ${pkgdir}/opt/
-  tar xvf ${_hammerfightarchivelocation}${_archive} -C ${srcdir}/extractedInstaller/ && msg Finished Extracting
-  install -Dd ${pkgdir}/opt/hammerfight
-  mv ${srcdir}/extractedInstaller/hammerfight/* ${pkgdir}/opt/hammerfight/
-
-  rm -rf ${pkgdir}/opt/hammerfight/{amd64,x86}
-
-  install -Dd ${pkgdir}/usr/bin
-  echo \#\!/bin/bash > ${pkgdir}/usr/bin/hammerfight
-  echo /opt/hammerfight/Hammerfight >> ${pkgdir}/usr/bin/hammerfight
-  chmod +x ${pkgdir}/usr/bin/hammerfight
-
+  install -d "${pkgdir}/opt/hammerfight/"
+  cp -Rl . "${pkgdir}/opt/hammerfight/"
   if [ "$CARCH" = "x86_64" ]; then
-	rm -rf ${pkgdir}/opt/hammerfight/Hammerfight-x86
+    rm "${pkgdir}/opt/hammerfight/Hammerfight-x86"
   else
-	rm -rf ${pkgdir}/opt/hammerfight/Hammerfight-amd64
+    rm "${pkgdir}/opt/hammerfight/Hammerfight-amd64"
   fi
 
-  for i in 16x16 22x22 32x32 48x48 64x64 128x128; do
-    mkdir -p ${pkgdir}/usr/share/icons/hicolor/${i}/apps
-    convert -resize ${i} \
-	${pkgdir}/opt/hammerfight/hammerfight.png \
-	${pkgdir}/usr/share/icons/hicolor/${i}/apps/hammerfight.png
-  done
+  # Use system-provided libraries
+  rm -rf "${pkgdir}"/opt/hammerfight/{amd64,x86}
+  rm "${pkgdir}/opt/hammerfight/xdg-open"
 
-  install -D ${srcdir}/hammerfight.desktop ${pkgdir}/usr/share/applications/hammerfight.desktop
+  install -d "${pkgdir}/usr/bin"
+  ln -s /opt/hammerfight/Hammerfight "${pkgdir}/usr/bin/hammerfight"
+
+  install -Dm644 hammerfight.png "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
+  install -Dm644 "${srcdir}/hammerfight.desktop" \
+      "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 }
diff --git a/libretro-bsnes-git/PKGBUILD b/libretro-bsnes-git/PKGBUILD
--- a/libretro-bsnes-git/PKGBUILD
+++ b/libretro-bsnes-git/PKGBUILD
@@ -4,7 +4,7 @@ pkgname=libretro-bsnes-git
 pkgver=20120515
 pkgrel=1
 pkgdesc="libretro implementation of bsnes."
-arch=('i686' 'x86_64')
+arch=('i686' 'x86_64' 'arm' 'armv6h')
 url="http://gitorious.org/bsnes"
 license=('custom')
 makedepends=('git')
@@ -34,12 +34,12 @@ cd perf
 git clone . perf
       fi
 
-if [ -d "compat" ]; then
+if [ -d "balanced" ]; then
 cd perf
          git pull ..
          cd ..
       else
-git clone . compat
+git clone . balanced
       fi
 
 cd ..
@@ -51,7 +51,7 @@ CC=gcc
 
 if [ -d "libretro-bsnes/perf" ]; then
 echo "=== Building bSNES performance ==="
-      cd libretro-bsnes/perf/bsnes
+      cd libretro-bsnes/perf/higan
       make compiler="$CC" ui=target-libretro profile=performance -j4 || die "Failed to build bSNES performance core"
       cp -f out/libretro.so ../../libretro-bsnes-performance.so
       cd ../../..
@@ -59,11 +59,11 @@ echo "=== Building bSNES performance ==="
 echo "bSNES performance not fetched, skipping ..."
    fi
 
-if [ -d "libretro-bsnes/compat" ]; then
-echo "=== Building bSNES compatibility ==="
-      cd libretro-bsnes/compat/bsnes
-      make compiler="$CC" ui=target-libretro profile=compatibility -j4 || die "Failed to build bSNES compatibility core"
-      cp -f out/libretro.so ../../libretro-bsnes-compat.so
+if [ -d "libretro-bsnes/balanced" ]; then
+echo "=== Building bSNES balanced ==="
+      cd libretro-bsnes/balanced/higan
+      make compiler="$CC" ui=target-libretro profile=balanced -j4 || die "Failed to build bSNES compatibility core"
+      cp -f out/libretro.so ../../libretro-bsnes-balanced.so
       cd ../../..
    else
 echo "bSNES compat not fetched, skipping ..."
@@ -71,7 +71,7 @@ echo "bSNES compat not fetched, skipping ..."
 
 if [ -d "libretro-bsnes" ]; then
 echo "=== Building bSNES accuracy ==="
-      cd libretro-bsnes/bsnes
+      cd libretro-bsnes/higan
       make compiler="$CC" ui=target-libretro profile=accuracy -j4 || die "Failed to build bSNES accuracy core"
       cp -f out/libretro.so ../libretro-bsnes-accuracy.so
       cd ../..
@@ -81,8 +81,8 @@ echo "=== Building bSNES accuracy ==="
 package()
 {
    mkdir -p $pkgdir/usr/lib/libretro
-   install -m755 $srcdir/libretro-bsnes/libretro-bsnes-performance.so $pkgdir/usr/lib/libretro/libretro-bsnes-performance.so
-   install -m755 $srcdir/libretro-bsnes/libretro-bsnes-compat.so $pkgdir/usr/lib/libretro/libretro-bsnes-compat.so
-   install -m755 $srcdir/libretro-bsnes/libretro-bsnes-accuracy.so $pkgdir/usr/lib/libretro/libretro-bsnes-accuracy.so
+   install -v -m644 $srcdir/libretro-bsnes/libretro-bsnes-performance.so $pkgdir/usr/lib/libretro/libretro-bsnes-performance.so
+   install -v -m644 $srcdir/libretro-bsnes/libretro-bsnes-balanced.so $pkgdir/usr/lib/libretro/libretro-bsnes-balanced.so
+   install -v -m644 $srcdir/libretro-bsnes/libretro-bsnes-accuracy.so $pkgdir/usr/lib/libretro/libretro-bsnes-accuracy.so
 }
 
diff --git a/multiwinia/PKGBUILD b/multiwinia/PKGBUILD
--- a/multiwinia/PKGBUILD
+++ b/multiwinia/PKGBUILD
@@ -1,79 +1,55 @@
-# Maintainer: Gadget30000 <gadget3000 at msn dot com>
+# Contributor: Gadget30000 <gadget3000 at msn dot com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
+
 pkgname=multiwinia
 pkgver=1.3.1
-pkgrel=2
-pkgdesc="Battle to save Darwinias innocent inhabitants, the Darwinians, from an evil viral infection"
+pkgrel=3
+pkgdesc="Challenge your opponent to a game of stick-man slaughter (game sold separately)"
 arch=('i686' 'x86_64')
 url="http://www.introversion.co.uk/multiwinia/"
-groups=('humbleintbundle' 'humblebundles')
 license=('custom')
-depends=('mesa' 'openal' 'sdl' 'libvorbis' 'libpng12')
-source=('multiwinia.desktop')
-md5sums=('8132259414180ad994c27cd2770ffc67')
-
+depends=('glu' 'openal' 'sdl' 'libvorbis' 'libpng12')
 if [ "${CARCH}" = "x86_64" ]; then
-_carch=amd64
-_archive_md5="5eaba188f84ad985fe9b5d36e3bf85a3"
-_bin_postfix="_64"
+  _gamepkg="hib://${pkgname}_${pkgver}-1_amd64.tar.gz"
+  _gamepkgsum='5eaba188f84ad985fe9b5d36e3bf85a3'
+  _bin_postfix='_64'
 else
-_carch=i386
-_archive_md5="bbc7d907431f15065a0f38f6623c4217"
-_bin_postfix=
+  _gamepkg="hib://${pkgname}_${pkgver}-1_i386.tar.gz"
+  _gamepkgsum='bbc7d907431f15065a0f38f6623c4217'
+  _bin_postfix=
 fi
-
-_archive="multiwinia_${pkgver}-1_${_carch}.tar.gz"
+source=("${pkgname}.desktop" "${_gamepkg}")
+md5sums=('59653ec01acf2befc0211c4cd7ac13bc' "${_gamepkgsum}")
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+PKGEXT='.pkg.tar'
 
 build() {
-  cd ${srcdir}
+  cd "${srcdir}/${pkgname}"
 
-  if [ ! -f ${_multiwiniaarchivelocation}${_archive} ]; then
-	  if [ ! -f ${_archive} ] && [ -n "${_humbleintbundlekey}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humbleintbundlekey}*
-		wget http://www.humblebundle.com/?key=${_humbleintbundlekey}
-		wget $(cat index.html\?key\=${_humbleintbundlekey} | grep "${_archive}" | cut -d "'" -f 10)
-		mv ${_archive}* ${_archive}
-	  elif [ -z "${_humbleintbundlekey}" ]; then
-		echo You can automate the download of the archive using the _humbleintbundlekey bash variable.
-		echo Just add \'export _humbleintbundlekey\=\<Your key here\>\' to \.bashrc
-		echo
-		echo Otherwise please just place ${_archive} into $(pwd)/
-		echo Press Enter to continue
-		read -a _unused
-	  fi
-  fi
+  install -d "${pkgdir}/opt/${pkgname}/"
+  install -m755 -t "${pkgdir}/opt/${pkgname}/" multiwinia.bin.x86${_bin_postfix}
+  install -m644 -t "${pkgdir}/opt/${pkgname}/" \
+      init.dat language.dat main.dat menusounds.dat sounds.dat sounds2.dat
 
-  if [ ! -f ${_multiwiniaarchivelocation}${_archive} ]; then
-    echo "${_multiwiniaarchivelocation}${_archive} not found!"
-    return 1
-  fi  
+  install -d "${pkgdir}/opt/${pkgname}/docs/"
+  install -m644 -t "${pkgdir}/opt/${pkgname}/docs/" \
+      docs/readme.txt docs/manual.pdf
 
-  if ! echo "${_archive_md5}  ${_multiwiniaarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_multiwiniaarchivelocation}${_archive}"
-    return 1
-  fi
+  install -d "${pkgdir}/usr/bin/"
+  ln -s /opt/${pkgname}/multiwinia.bin.x86${_bin_postfix} \
+      "${pkgdir}/usr/bin/${pkgname}"
 
-  install -d ${pkgdir}/usr/share/
-  tar xzf ${_multiwiniaarchivelocation}${_archive} -C ${pkgdir}/usr/share/
-  install -d ${pkgdir}/usr/bin
-  ln -s /usr/share/multiwinia/multiwinia.bin.x86${_bin_postfix} ${pkgdir}/usr/bin/multiwinia
-
-  #Copy Icon
-  install -d ${pkgdir}/usr/share/pixmaps/
-  install -D -m644 ${pkgdir}/usr/share/multiwinia/multiwinia.png ${pkgdir}/usr/share/pixmaps/ || return 1
-
-  #Copy Desktop File
-  install -d ${pkgdir}/usr/share/applications
-  cp ${srcdir}/multiwinia.desktop ${pkgdir}/usr/share/applications/
-
-#  echo Installing the License
-#  install -d ${pkgdir}/usr/share/licenses/${pkgname}
-#  install -D -m644 ${pkgdir}/usr/share/multiwinia/license.txt ${pkgdir}/usr/share/licenses/${pkgname}/ || return 1
-
-  if [ "${CARCH}" = "x86_64" ]; then
-      rm -rf ${pkgdir}/usr/share/multiwinia/lib64
-  else
-      rm -rf ${pkgdir}/usr/share/multiwinia/lib32
-  fi
-
-  chown -Rh root:root ${pkgdir}/usr/share/multiwinia
+  install -Dm644 ${pkgname}.png "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
+  install -Dm644 "${srcdir}/${pkgname}.desktop" \
+      "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 }
diff --git a/xivo-client-qt-skaro-git/PKGBUILD b/xivo-client-qt-skaro-git/PKGBUILD
--- a/xivo-client-qt-skaro-git/PKGBUILD
+++ b/xivo-client-qt-skaro-git/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: Benoit Stahl <stahlbenoit@gmail.com>
 
 pkgname='xivo-client-qt-skaro-git'
-pkgver=20120623
+pkgver=20130119
 pkgrel=1
 pkgdesc="XiVO client QT"
 arch=('i686' 'x86_64')
@@ -34,52 +34,51 @@ build() {
 
 package() {
 
-	mkdir -p ${pkgdir}/opt/xivo-client/plugins
+	mkdir -p ${pkgdir}/opt/xivoclient/plugins
 	mkdir -p ${pkgdir}/usr/bin
 	mkdir -p ${pkgdir}/usr/share/icons/xivoclient
-	install -D -m 755 -o root -g root ${srcdir}/${_gitname}/bin/xivoclient ${pkgdir}/opt/xivo-client/
-	install -D -m 755 -o root -g root ${srcdir}/${_gitname}/bin/libxivoclient* ${pkgdir}/opt/xivo-client/
-	install -D -m 755 -o root -g root ${srcdir}/${_gitname}/bin/plugins/* ${pkgdir}/opt/xivo-client/plugins/
-	install -D -m 655 -o root -g root ${srcdir}/${_gitname}/cross/resources/xivoclient.png ${pkgdir}/usr/share/icons/xivoclient.png
-	install -D -m 655 -o root -g root ${srcdir}/${_gitname}/cross/resources/xivoclient.desktop ${pkgdir}/usr/share/applications/xivoclient.desktop
-
-echo '#!/bin/bash
+	install -D -m 755 -o root -g root ${srcdir}/${_gitname}/bin/xivoclient ${pkgdir}/opt/xivoclient/
+	install -D -m 755 -o root -g root ${srcdir}/${_gitname}/bin/libxivoclient* ${pkgdir}/opt/xivoclient/
+	install -D -m 755 -o root -g root ${srcdir}/${_gitname}/bin/plugins/* ${pkgdir}/opt/xivoclient/plugins/
+	install -D -m 655 -o root -g root ${srcdir}/${_gitname}/packaging/resources/xivoclient.png ${pkgdir}/usr/share/icons/xivoclient.png
+	install -D -m 655 -o root -g root ${srcdir}/${_gitname}/packaging/resources/xivoclient.desktop ${pkgdir}/usr/share/applications/xivoclient.desktop
+	
+		cat >${pkgdir}/usr/bin/xivoclient <<EOF
+#!/bin/bash
 
 DEBUG="no"
 
 while getopts ":dh" opt; do
-  case $opt in
+  case \$opt in
       d)
           DEBUG="yes"
           ;;
       h)
-          echo "Usage : $0 [-dh] [profile]"
-          echo
-          echo "-d : Enable debug output"
-          echo "-h : Help"
-          echo "profile : Configuration profile"
-          echo
-          exit 0
-          ;;
-      \?)
-          echo "Invalid option: -$OPTARG" >&2
-          ;;
+         echo "Usage : \$0 [-dh] [profile]"
+         echo
+         echo "-d : Enable debug output"
+         echo "-h : Help"
+         echo "profile : Configuration profile"
+         echo
+         exit 0
+         ;;
+     \?)
+         echo "Invalid option: -\$OPTARG" >&2
+         ;;
   esac
 done
 
-shift $(( OPTIND-1 ))
+shift \$(( OPTIND-1 ))
 
-cd /opt/xivo-client
+cd /opt/xivoclient
 
-if [ "$DEBUG" = "yes" ]
+if [ "\$DEBUG" = "yes" ]
 then
-    LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH" ./xivoclient $@
+    LD_LIBRARY_PATH=".:\$LD_LIBRARY_PATH" ./xivoclient \$@
 else
-    LD_LIBRARY_PATH=".:$LD_LIBRARY_PATH" ./xivoclient $@ >& /dev/null
-fi' > ${srcdir}/${_gitname}/cross/resources/xivoclient
-
- install -D -m 655 -o root -g root ${srcdir}/${_gitname}/cross/resources/xivoclient ${pkgdir}/usr/bin
-	
-
-
+    LD_LIBRARY_PATH=".:\$LD_LIBRARY_PATH" ./xivoclient \$@ >& /dev/null
+fi	
+EOF
+	chmod 775 ${pkgdir}/usr/bin/xivoclient 
 }
+
