updated on Tue Jul 30 18:00:37 UTC 2013

diff --git a/jamestown/PKGBUILD b/jamestown/PKGBUILD
--- a/jamestown/PKGBUILD
+++ b/jamestown/PKGBUILD
@@ -1,72 +1,57 @@
-# Maintainer: Yann Kaiser <kaiser.yann@gmail.com>
+# Maintainer: Claudio Kozicky <claudiokozicky@gmail.com>
+# Contributor: Yann Kaiser <kaiser.yann@gmail.com>
+
 pkgname=jamestown
-pkgver=1.0.1
+pkgver=1.0.1.164
 _pkgver=1_0_1
 _timestamp=1324610248
 pkgrel=1
 pkgdesc="A neo-classical top-down shooter for up to four players set on 17th-century British Colonial Mars."
-arch=('i686' 'x86_64')
+arch=(i686 x86_64)
 url="http://www.finalformgames.com/jamestown/"
-license=('custom')
-depends=('libgl' 'openal' 'sdl' 'libxext' 'libx11' 'libxcb' 'libxau' 'libxdmcp')
-makedepends=()
-source=('jamestown.desktop')
-md5sums=('8769d7f0e88d26c87d64dcdaaeb0d64a')
+license=(custom)
+depends=(libgl openal sdl)
+source=(hib://jtownlinux_"$_pkgver"_$_timestamp.zip
+        jamestown.desktop)
+md5sums=(cc8ae55f3231ff7659c3e2ffbb524b7b
+         9ea819a8c77b79088a5b983886d7056d)
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+PKGEXT=.pkg.tar
 
-_archive_name="jtownlinux"
-_archive_md5="cc8ae55f3231ff7659c3e2ffbb524b7b"
+prepare()
+{
+    # extract data dir from installer
+    cd $srcdir
+    bsdtar -xf JamestownInstaller_"$_pkgver"-bin data
 
-_archive="${_archive_name}_${_pkgver}_${_timestamp}.zip"
-
-build() {
-  cd ${srcdir}
-
-  if [ ! -f ${_jtarchivelocation}${_archive} ]; then
-	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-		wget http://www.humblebundle.com/?key=${_humblebundle4key}
-		wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-		mv ${_archive}* ${_archive}
-	  elif [ -z "${_humblebundle4key}" ]; then
-		echo You can automate the download of the archive using the _humblebundle4key bash variable.
-		echo Just add \'export _humblebundle4key\=\<Your key here\>\' to \.bashrc
-		echo
-		echo Otherwise please just place ${_archive} into $(pwd)/
-		echo Press Enter to continue
-		read -a _unused
-	  fi
-  fi
-  #'
-
-  if [ ! -f ${_jtarchivelocation}${_archive} ]; then
-    echo "${_jtarchivelocation}${_archive} not found!"
-    return 1
-  fi  
-
-  if ! echo "${_archive_md5}  ${_jtarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_jtarchivelocation}${_archive}"
-    return 1
-  fi
-
-  bsdtar -xf ${_jtarchivelocation}${_archive}
-  rm -rf jamestown
-  unzip -d jamestown JamestownInstaller_${_pkgver}-bin || true
-
-  cd ${srcdir}/jamestown/data/
-
-  if test "${CARCH}" == "x86_64"; then
-    rm -R x86 Jamestown-x86
-  else
-    rm -R amd64 Jamestown-amd64
-  fi
-  sed -i -e "2aJAMESTOWN_ARCH=${CARCH}" Jamestown
-
-  mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/bin/ \
-    ${pkgdir}/usr/share/applications
-  cp -r . ${pkgdir}/opt/jamestown
-  cp ${srcdir}/jamestown.desktop ${pkgdir}/usr/share/applications/
-  chmod a+r ${pkgdir}/usr/share/applications/jamestown.desktop
-  ln -s /opt/jamestown/Jamestown ${pkgdir}/usr/bin/jamestown
+    # cleanup
+    cd data
+    rm -r x86 amd64 Distribution.txt LICENSES.TXT README-linux.txt
+    [ $CARCH = x86_64 ] \
+        && rm Jamestown-x86 \
+        || rm Jamestown-amd64
 }
 
-# vim: et ts=2 sw=2 sts=2
+package()
+{
+    # data
+    cd "$srcdir"/data
+    find Archives -type f -exec install -Dm644 {} "$pkgdir"/opt/$pkgname/{} \;
+    install -m755 -t "$pkgdir"/opt/$pkgname Jamestown Jamestown-*
+
+    # doc
+    install -Dm644 README-linux-generic.txt "$pkgdir"/usr/share/doc/$pkgname/README
+
+    # legal
+    install -Dm644 Jamestown_EULA.txt "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
+
+    # launcher
+    install -d "$pkgdir"/usr/bin
+    ln -s /opt/$pkgname/Jamestown "$pkgdir"/usr/bin/$pkgname
+
+    # desktop integration
+    install -Dm644 $pkgname.png "$pkgdir"/usr/share/pixmaps/$pkgname.png
+    install -Dm644 ../$pkgname.desktop "$pkgdir"/usr/share/applications/$pkgname.desktop
+}
+
+# vim:et:sw=4:sts=4
