updated on Wed Jun 27 06:00:14 UTC 2012

diff --git a/aurupload/aurupload b/aurupload/aurupload
--- a/aurupload/aurupload
+++ b/aurupload/aurupload
@@ -75,9 +75,25 @@ fi
 
 echo "Done, sessionid is $sessid"
 
+echo "Requesting upload token..."
+
+response=`curl -sSi -H 'Expect: ' -b $sessid https://aur.archlinux.org/pkgsubmit.php`
+token=`echo "$response" | grep 'input.type..hidden..name..token..value' | cut -d\' -f6`
+
+if [ $verbose -gt 0 ]; then
+  echo "$response"
+fi
+
+if [ -z "$token" ]; then
+  echo "Could not get the token." >&2
+  exit 1
+fi
+
+echo "Done, token is $token"
+
 echo "Uploading file..."
 
-response=`curl -sSi -H 'Expect: ' -F pkgsubmit=1 -F category=$category -F pfile=@$filename -b $sessid https://aur.archlinux.org/pkgsubmit.php`
+response=`curl -sSi -H 'Expect: ' -F token="$token" -F pkgsubmit=1 -F category=$category -F pfile=@$filename -b $sessid https://aur.archlinux.org/pkgsubmit.php`
 error=`echo "$response" | grep 'class="pkgoutput"' | sed 's/\s*<[^>]*>//g'`
 package=`echo "$response" | awk '/^Location: / {print $2}'`
 
