updated on Sat Jan 17 00:00:24 UTC 2015

diff --git a/openh264-git/PKGBUILD b/openh264-git/PKGBUILD
--- a/openh264-git/PKGBUILD
+++ b/openh264-git/PKGBUILD
@@ -1,41 +1,93 @@
-# Maintainer: Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
+# Maintainer: Buck 'apitofme' Rodgers <gbuck2550 at gmail dot moc>
+# Contributor: Bartłomiej Piotrowski <bpiotrowski at archlinux dot org>
+
+# ---- Note: ----
+# Until I have arranged suitable contact details please report any issues
+# in the comments section for this package's AUR page!
+# -- Thanks --
 
 pkgname=openh264-git
-pkgver=20131227.71e4821
+pkgver=1.3
 pkgrel=1
-pkgdesc='Open Source H.264 Codec'
+pkgdesc="A free, open-source codec library for H.264 encoding and decoding"
 arch=('i686' 'x86_64')
-url='http://www.openh264.org/'
+url="http://www.openh264.org/"
 license=('BSD')
-depends=('gcc-libs')
-makedepends=('git' 'nasm')
-options=('staticlibs')
-source=(git://github.com/cisco/openh264.git)
-md5sums=('SKIP')
+depends=('gcc-libs-multilib')
+makedepends=('git' 'yasm')
+# Note: official src dep is 'nasm', however 'yasm' provides this also!
+provides=("$_pkgname")
+source=('https://github.com/cisco/openh264.git')
+sha256sums=('2d1e4387e694f545637115c7f10561b8b0d0e6237e4b66617d4a9986c15d27d0')
+
+_name=openh264
+_release=1.3
+_branch="${_name}v$_release"
 
 pkgver() {
-  cd openh264
-  echo $(git log -1 --format="%cd" --date=short | sed 's|-||g').$(git rev-parse --short HEAD)
+  cd "$srcdir/$_branch"
+
+  printf "$(grep -i -m1 'version' Makefile | cut -d "=" -f2).r%s.%s" \
+    "$(git rev-list --count HEAD)" \
+    "$(git rev-parse --short HEAD)"
+}
+
+prepare() {
+  cd "$srcdir"
+
+  if [ -d "$_branch" ]; then
+    msg 'Updating source from GitHub...'
+    cd "$_branch" && git pull origin
+    cd ..
+  else
+    msg 'Downloading source from GitHub...'
+    git clone -b "$_branch" --depth 1 "$source" "$_branch"
+  fi
+
+  if [ ! -d "$_branch" ]; then
+    error 'Checkout failed or server timeout!'
+    exit 1
+  fi
+
+  # TODO -- check if a clean is required first!
 }
 
 build() {
-  cd openh264
+  cd "$srcdir/$_branch"
 
-  if [[ $CARCH == x86_64 ]]; then
+  msg 'Starting make...'
+  if [ "x86_64" == "$CARCH" ]; then
+    msg 'Building for 64bit architecture...'
     make all ENABLE64BIT=Yes
   else
+    msg 'Building for 32bit architecture...'
     make all
   fi
+
+# TODO -- figure out how to build the docs! (doxygen?)
+
+  msg 'Build finished!'
+}
+
+check() {
+  msg 'Not yet implemented!'
+# TODO -- run the built in tests from the source
+#  cd "${srcdir}/${_branch}/autotest"
+#  bash ./perfomanceTest/run_perfTest.sh
+#  bash ./unitTest/run_unitTest.sh
+# FIXME -- tried the above but got an error!
 }
 
 package() {
-  cd openh264
+  cd "${srcdir}/${_branch}"
 
   install -Dm755 h264dec "$pkgdir"/usr/bin/h264dec
   install -Dm755 h264enc "$pkgdir"/usr/bin/h264enc
   install -Dm644 LICENSE "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
 
-  for lib in *.a; do
-    install -Dm644 $lib "$pkgdir"/usr/lib/$lib
-  done
+  make DESTDIR="${pkgdir}" install
+
+  mv -v "${pkgdir}/usr/local/lib" "${pkgdir}/usr/"
+  mv -v "${pkgdir}/usr/local/include" "${pkgdir}/usr/"
+  rm -rv "${pkgdir}/usr/local"
 }
