updated on Sun Jul  6 00:05:26 UTC 2014

diff --git a/voxatron/PKGBUILD b/voxatron/PKGBUILD
--- a/voxatron/PKGBUILD
+++ b/voxatron/PKGBUILD
@@ -1,8 +1,9 @@
 # Contributor: Marcel Pfeiffer <pfeiffer.marcel at gmx dot de>
 # Contributor: Zachary A. Jones <JazzplayerL9@gmail.com>
+# Maintaner: Jose Riha <jose1711 gmail com>
 
 pkgname=voxatron
-pkgver=0.2.9
+pkgver=0.2.12
 pkgrel=1
 pkgdesc="Voxatron is an action/adventure game set in a world completely made of tiny cubes that can be blasted to smithereens"
 url="http://www.lexaloffle.com/voxatron.php"
@@ -19,35 +20,35 @@ case $CARCH in
         optdepends=('lib32-alsa-lib: sound support' 'lib32-libpulse: sound suport')
     ;;
 esac
-makedepends=('curl')
+#makedepends=('curl')
 options=(!strip)
 
 _gamepkg="${pkgname}_${pkgver}_i386.tar.gz"
-source=("${_gamepkg}::https://www.humblebundle.com/login"
-        "${_gamepkg}::http://www.humblebundle.com/downloads?key=${_humblevoxatronkey}"
+source=("hib://${_gamepkg}"
         "$pkgname.desktop"
 	"vox-exec")
 
-_char=\'
-DLAGENTS=('https::/bin/echo %o > /tmp/arch && sed -i "s/.part//" /tmp/arch && /usr/bin/curl -s --cookie-jar /tmp/cjar --output /dev/null %u && cp /tmp/cjar ./ && /usr/bin/curl -sL --cookie /tmp/cjar --cookie-jar /tmp/cjar --data "username=$_humbleemail" --data "password=$_humblepassword" %u | grep -f /tmp/arch |grep -o -E "data-web=[^ ]+"| sed -e "s/data-web=\([^ ]*\)/\1/" > /tmp/url && sed -i "s/$_char//g" /tmp/url && /usr/bin/curl --cookie /tmp/cjar --cookie-jar /tmp/cjar -fLC -  --retry 3 --retry-delay 3 -o %o "$(</tmp/url)" && rm -f /tmp/{arch,url} || return 0'
-          "http::/usr/bin/curl -sL %u | grep voxatron_${pkgver}_ | sed \"s/.*data-web='/url=/\" | sed \"s/' data-bt.*//\" | grep .tar.gz > /tmp/url && /usr/bin/curl -fLC -  --retry 3 --retry-delay 3 -o %o -K /tmp/url && rm /tmp/url")
-
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+#_char=\'
+#DLAGENTS=('https::/bin/echo %o > /tmp/arch && sed -i "s/.part//" /tmp/arch && /usr/bin/curl -s --cookie-jar /tmp/cjar --output /dev/null %u && cp /tmp/cjar ./ && /usr/bin/curl -sL --cookie /tmp/cjar --cookie-jar /tmp/cjar --data "username=$_humbleemail" --data "password=$_humblepassword" %u | grep -f /tmp/arch |grep -o -E "data-web=[^ ]+"| sed -e "s/data-web=\([^ ]*\)/\1/" > /tmp/url && sed -i "s/$_char//g" /tmp/url && /usr/bin/curl --cookie /tmp/cjar --cookie-jar /tmp/cjar -fLC -  --retry 3 --retry-delay 3 -o %o "$(</tmp/url)" && rm -f /tmp/{arch,url} || return 0'
+          #"http::/usr/bin/curl -sL %u | grep voxatron_${pkgver}_ | sed \"s/.*data-web='/url=/\" | sed \"s/' data-bt.*//\" | grep .tar.gz > /tmp/url && /usr/bin/curl -fLC -  --retry 3 --retry-delay 3 -o %o -K /tmp/url && rm /tmp/url")
+#
 #curl reference for update use:
 #curl -sL http://www.humblebundle.com/downloads?key=${_humblevoxatronkey} | grep voxatron_${pkgver}_ | sed -e \"s/.*data-web='/url=/\" | sed -e \"s/' data-bt.*//\" | grep .tar.gz > weblinks.txt
 
-if [[ ! -f $SRCDEST/${source[0]%%:*} ]]; then
-    if [[ -z $_humbleemail || -z $_humblepassword ]]; then
-        if [[ -z $_humblevoxatronkey ]]; then
-            msg "if you have bound your email and password to your account, "
-            msg "please export the values _humbleemail and _humblepassword so"
-            msg "that you can be logged in to download the game."
-            echo
-            msg "if you have not bound the key to an email, "
-            msg "please export _humblevoxatronkey in your .bashrc"
-            return 1
-        fi
-    fi
-fi
+#if [[ ! -f $SRCDEST/${source[0]%%:*} ]]; then
+    #if [[ -z $_humbleemail || -z $_humblepassword ]]; then
+        #if [[ -z $_humblevoxatronkey ]]; then
+            #msg "if you have bound your email and password to your account, "
+            #msg "please export the values _humbleemail and _humblepassword so"
+            #msg "that you can be logged in to download the game."
+            #echo
+            #msg "if you have not bound the key to an email, "
+            #msg "please export _humblevoxatronkey in your .bashrc"
+            #return 1
+        #fi
+    #fi
+#fi
 
 package(){
   cd "${srcdir}"
@@ -66,7 +67,6 @@ package(){
   # Install license
   install -Dm 644 "${pkgdir}"/opt/${pkgname}/license.txt "${pkgdir}"/usr/share/licenses/${pkgname}/license
 }
-md5sums=('b74e726c81276fea1084a16d78547d7e'
-         'b74e726c81276fea1084a16d78547d7e'
+md5sums=('3394763b4880d9abe6a6e7c4a1723534'
          '184c021b52d3a9c8ac5f49435b4b93e0'
          'bb84f6fcd7cdb18eb417173a6f58e00e')
