updated on Sat Nov 26 11:56:48 UTC 2011

diff --git a/blender-collada/PKGBUILD b/blender-collada/PKGBUILD
--- a/blender-collada/PKGBUILD
+++ b/blender-collada/PKGBUILD
@@ -17,21 +17,21 @@ pkgname=blender-collada
 _pkgname=blender
 provides=blender
 conflicts=blender
-pkgver=2.59
-pkgrel=1
-epoch=2
+pkgver=2.60a
+pkgrel=2
+epoch=3
 pkgdesc="A fully integrated 3D graphics creation suite. With Collada support."
 arch=('i686' 'x86_64')
 license=('GPL')
 url="http://www.blender.org"
 depends=('libpng' 'libtiff' 'openexr' 'python' 'desktop-file-utils' \
          'shared-mime-info' 'hicolor-icon-theme' 'xdg-utils' 'glew' \
-         'freetype2' 'openal' 'libsamplerate' 'ffmpeg' 'opencollada')
+         'freetype2' 'openal' 'libsndfile' 'ffmpeg' 'opencollada')
 makedepends=('cmake') # 'subversion'
 install=blender.install
 if [ $_svn = false ]; then
   source=(http://download.blender.org/source/$_pkgname-$pkgver.tar.gz)
-  md5sums=('6f68fe3c3c2b6a85f1ba9ebc5b1155fe')
+  md5sums=('cc7e4a56c9f7941c33c958ff0338f9a6')
 else
   source=(ftp://ftp.archlinux.org/other/${_pkgname}/$_pkgname-$pkgver.tar.xz)
   md5sums=('7579d1139d0d6025df8afcfca64a65c4')
@@ -39,6 +39,7 @@ fi
 
 # source PKGBUILD && mksource
 mksource() {
+  [[ -x /usr/bin/svn ]] || (echo "svn not found. Install subversion." && return 1)
   _svnver=38016
   _svntrunk="https://svn.blender.org/svnroot/bf-blender/trunk/blender"
   _svnmod="$_pkgname-$pkgver"
