updated on Wed Nov  6 00:26:55 UTC 2013

diff --git a/mkinitcpio-btrfs/btrfs_hook b/mkinitcpio-btrfs/btrfs_hook
--- a/mkinitcpio-btrfs/btrfs_hook
+++ b/mkinitcpio-btrfs/btrfs_hook
@@ -58,25 +58,50 @@ BTRFS_DIR_ROLLBACK="${BTRFS_DIR_ROLLBACK%/}"
 : ${BTRFS_ROLLBACK_CHOICE:="default"}
 : ${BTRFS_ROLLBACK_LIST:="default"}
 : ${BTRFS_ROLLBACK_LIST_COUNT:=1}
+: ${BTRFS_ROLLBACK_KERNEL:=true}
 : ${BTRFS_KERNEL:="/boot/vmlinuz-linux"}
 : ${BTRFS_INITRD:="/boot/initramfs-linux.img"}
+: ${BTRFS_KVER_CHECK:=false}
+: ${BTRFS_KVER_DIFFER:=true}
+: ${BTRFS_ENABLE_DEGRADED:=false}
+: ${BTRFS_ENABLE_DEGRADED_ROLLBACK:=false}
 
 btrfs_mount_handler () {
     local x i=1 work=${1%/}
     BTRFS_DIR_WORK=${work}
 
     # scan for multi device filesystems
-    btrfs device scan
+    btrfs device scan 2>&1 | grep -v "No medium found"
+
+    # temporary mount btrfs root subvolume
+    if ! mount -t btrfs -o subvolid=0,rw ${root} ${work}; then
+
+        # try to mount in degraded mode
+        if ${BTRFS_ENABLE_DEGRADED}; then
+            if ! mount -t btrfs -o subvolid=0,rw,degraded ${root} ${work}; then
+                btrfs_fatal "Unable to mount root subvolume" &&
+                return 1
+            else
+                btrfs_warn "Mounted root subvolume in degraded mode"
+                sleep 3
+                rootflags="${rootflags},degraded"
+
+                # supress rollback choice in degraded mode
+                if ! ${BTRFS_ENABLE_DEGRADED_ROLLBACK}; then
+                    btrfs_info "Disabled rollback feature in degraded mode"
+                    kexeced=true
+                fi
+            fi
+        else
+            btrfs_fatal "Unable to mount root subvolume" &&
+            return 1
+        fi
+    fi
+    BTRFS_IS_MOUNTED=true
 
     # check if we already ran kexec
     : ${kexeced:=false}
     if ! ${kexeced}; then
-
-        # temporary mount btrfs root subvolume
-        ! mount -t btrfs -o subvolid=0,rw ${root} ${work} &&
-            btrfs_fatal "Unable to mount root subvolume" &&
-            return 1
-        BTRFS_IS_MOUNTED=true
 
         if ! [ -d ${work}${BTRFS_DIR_ACTIVE} ]; then
             if ! { btrfs_ask_volatile && btrfs_set_volatile; }; then
@@ -132,18 +157,64 @@ btrfs_mount_handler () {
         btrfs_info "Booting from subvolume [${BTRFS_BOOT_SUBVOL}]..."
         btrfs subvolume set-default ${BTRFS_BOOT_SUBVOLID} ${work}
 
-        # copy kernel to initramfs
-        cp "${work}${BTRFS_BOOT_SUBVOL}${BTRFS_KERNEL}" "/tmp/linux"
-        cp "${work}${BTRFS_BOOT_SUBVOL}${BTRFS_INITRD}" "/tmp/initrd"
+        # if kernel rollback is enabled (so it is by default)
+        if ${BTRFS_ROLLBACK_KERNEL}; then
 
-        # unmount btrfs root subvolume
-        ! umount ${BTRFS_DIR_WORK} &&
-            btrfs_fatal "Unable to umount root subvolume" &&
-            return 1
+            # test if a new kernel is present
+            if [ -f ${work}${BTRFS_BOOT_SUBVOL}${BTRFS_KERNEL} -a -f ${work}${BTRFS_BOOT_SUBVOL}${BTRFS_INITRD} ]; then
 
-        # force reload kernel
-        btrfs_info "Reloading kernel from [${BTRFS_BOOT_SUBVOL}]..."
-        kexec -f "/tmp/linux" --initrd="/tmp/initrd" --reuse-cmdline --append="kexeced=true"
+                # compare running kernel's version against kernel image
+                if ${BTRFS_CHECK_KVER}; then
+
+                    # extract kernel_version from header in kernel image
+                    # according to kernel documentation:
+                    # https://www.kernel.org/doc/Documentation/x86/boot.txt
+                    #
+                    # 0x020E -> 526
+                    kver_pointer_hex="$(dd if=${work}${BTRFS_BOOT_SUBVOL}${BTRFS_KERNEL} bs=1 skip=526 count=2 2>/dev/null | hexdump -e '"%x"')"
+                    # convert to decimal
+                    kver_pointer="$(printf "%d\n" "0x${kver_pointer_hex}")"
+                    #
+                    # 0x0200 -> 512
+                    kver="$(dd if=${work}${BTRFS_BOOT_SUBVOL}${BTRFS_KERNEL} bs=1 skip=$((512+${kver_pointer})) count=128 2>/dev/null | strings -n 10)"
+                    echo "${kver}" | grep "$(uname -r)" | grep "$(uname -v)" 1>/dev/null
+                    if [ ${?} -eq 0 ]; then
+                        BTRFS_KVER_DIFFER=false
+                    fi
+                fi
+
+                # only load new kernel if versions differ
+                # if the above check failes they differ by default anyway
+                if ${BTRFS_KVER_DIFFER}; then
+
+                    # copy kernel to initramfs
+                    cp "${work}${BTRFS_BOOT_SUBVOL}${BTRFS_KERNEL}" "/tmp/linux"
+                    cp "${work}${BTRFS_BOOT_SUBVOL}${BTRFS_INITRD}" "/tmp/initrd"
+
+                    # unmount btrfs root subvolume
+                    ! umount ${BTRFS_DIR_WORK} &&
+                        btrfs_fatal "Unable to umount root subvolume" &&
+                        return 1
+                    BTRFS_IS_MOUNTED=false
+
+                    # force reload kernel
+                    btrfs_info "Reloading kernel from [${BTRFS_BOOT_SUBVOL}]..."
+                    kexec -f "/tmp/linux" --initrd="/tmp/initrd" --reuse-cmdline --append="kexeced=true"
+
+                    # at this point the kernel reloads the initramfs and
+                    # restarts init - no further code is executed
+                fi
+            else
+                btrfs_warn "Unable to load kernel from new root subvolume"
+                btrfs_warn "Check your config in /etc/default/btrfs_advanced"
+            fi
+
+            # unmount btrfs root subvolume
+            ! umount ${BTRFS_DIR_WORK} &&
+                btrfs_fatal "Unable to umount root subvolume" &&
+                return 1
+            BTRFS_IS_MOUNTED=false
+        fi
     fi
 
     btrfs_process_mount ${work}
@@ -281,7 +352,7 @@ btrfs_setup_rollback () {
 run_hook () {
 
     # root must be btrfs else silent return
-    if [ "$(blkid -s TYPE -o value ${root})" != "btrfs" -a "$(blkid -s TYPE -o value -lt ${root})" != "btrfs" ]; then
+    if [ "$(blkid -s TYPE -o value ${root} 2>/dev/null)" != "btrfs" -a "$(blkid -s TYPE -o value -lt ${root} 2>/dev/null)" != "btrfs" ]; then
         btrfs_warn "Root filesystem ${root} is not a BTRFS filesystem"
         return 0
     fi
