updated on Fri Apr 24 00:00:27 UTC 2015

diff --git a/archdroid-icon-theme/PKGBUILD b/archdroid-icon-theme/PKGBUILD
--- a/archdroid-icon-theme/PKGBUILD
+++ b/archdroid-icon-theme/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: GreenRaccoon23 <GreenRaccoon a t gmail d o t com>
 
 pkgname=archdroid-icon-theme
-pkgver=r61.890ccde
+pkgver=r64.7638a0f
 pkgrel=1
 pkgdesc="Port of Android 5.0 Lollipop's material design icons to Arch."
 arch=('any')
@@ -13,7 +13,22 @@ conflicts=("${pkgname}")
 #options=('!strip')
 install="${pkgname}.install"
 source=("https://github.com/GreenRaccoon23/${pkgname}/raw/master/${pkgname}.tar.xz")
-md5sums=("8b68c6b330af0ad8320230d2fd1f0856")
+md5sums=("8c757038eefc1233d222ff581ec81b39")
+
+_error2() {
+	for e; do
+		echo "    ${e}";
+	done;
+}
+
+prepare() {
+	if ! fc-list | grep Roboto >/dev/null; then
+		error "Required font 'Roboto' is not installed."
+		error "Please install a font package which includes 'Roboto', such as:"
+		_error2 ttf-roboto ttf-roboto-font ttf-google-fonts-git ttf-google-fonts-hg otf-google-fonts-hg;
+		return 1;
+	fi;
+}
 
 package() {
 	msg2 "Installing ${pkgname}..." ;
