updated on Thu Aug 11 12:01:29 UTC 2011

diff --git a/kernel-netbook/PKGBUILD b/kernel-netbook/PKGBUILD
--- a/kernel-netbook/PKGBUILD
+++ b/kernel-netbook/PKGBUILD
@@ -1,75 +1,74 @@
 # Maintainer: Dieghen89 <dieghen89@gmail.com>
 
 BFQ_IO_SCHEDULER="n"
-TUX_ON_ICE="n"
+TUX_ON_ICE="y"
 
 pkgname=kernel-netbook
 true && pkgname=('kernel-netbook' 'kernel-netbook-headers')
-depends=('coreutils' 'module-init-tools')
 makedepends=('dmidecode' 'xmlto' 'docbook-xsl')
 optdepends=('hibernate-script: tux on ice default script' 'tuxonice-userui: graphical interface for toi [AUR]')
-_basekernel=2.6.39
-pkgver=${_basekernel}.3
-pkgrel=3
+_basekernel=3.0
+pkgver=${_basekernel}.1
+pkgrel=1
 pkgdesc="Static kernel for netbooks with Intel Atom N270/N280/N450/N550 such as eeepc with the add-on of external firmware (broadcom-wl) and patchset (BFS + TOI + BFQ optional) - Only Intel GPU - Give more power to your netbook!"
-options=(!strip)
+options=('!strip')
 arch=('i686')
 license=('GPL2')
 url=('http://code.google.com/p/kernel-netbook')
 
 ####################################
-md5sums=('1aab7a741abe08d42e8eccf20de61e05'
-         'b23d7def30e57242cfe088f4d8ca8baa'
+md5sums=('398e95866794def22b12dfbc15ce89c0'
+         'ac49f7907f1fc85fbab92d0f1aa1552a'
          'c0074a1622c75916442e26763ddf47d0'
-         'ffa0384d5a243d17ca47c9bd0e2217e7'
+         'bca399a46c7d83affdace85b9c633e36'
          '199921265a39fbe7e8370c6432548ec3'
          'f71db44b8aabf407c7ea9591b6ba2488'
          'cbae3fd91c29e692fb19488dedc4f9db'
+         'afbd01926c57fc5b82ee6034dc9311e5'
          'e8c333eaeac43f5c6a1d7b2f47af12e2'
          '5974286ba3e9716bfbad83d3f4ee985a'
          'a6f0377c814da594cffcacbc0785ec1a'
          '2bb172117ede96c14289f9f9bc34f58f'
          'aee89fe7f034aea2f2ca95322774c1b5'
          '21ce3f7967d7305064bf7eb60030ffea'
-         'c5fb8b8f9ffb005f19a8132354cfbd46'
-         '0ab7720f0d80d142a280cfe35b9a8730'
-         'ea4f986a1f23779d955b077d361072bc')
+         '5adb575888af33be0c8ff32dea24d9a6'
+         '263725f20c0b9eb9c353040792d644e5'
+         '9d3c56a4b999c8bfbd4018089a62f662'
+         'a829e6194cba99b7074eeb25f9e6169d')
 ###################################
 #  external drivers  and firmware #
 ###################################
 
 #Arch patchset
-patchname=patch-${pkgver}-1-ARCH
+#patchname=patch-${pkgver}-1-ARCH
 #Broadcom-wl:
 broadcom_ver=5.100.82.38
 broadcom="hybrid-portsrc_x86_32-v${broadcom_ver//./_}"
-#Stk11xx:
-#stk11xx_ver="2.1.0"
-#stk11xx="stk11xx-$stk11xx_ver"
 #BFS: - http://users.on.net/~ckolivas/kernel/ -
-_ckpatchversion=2
-_ckpatchname="patch-${_basekernel}-ck${_ckpatchversion}"
+_ckpatchversion=1
+_ckpatchname="patch-${_basekernel}.0-ck${_ckpatchversion}"
 #BFQ: - http://algo.ing.unimo.it/people/paolo/disk_sched/ -
 _bfqpatchversion="1"
-_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/2.6.39"
+_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.0"
 #TuxOnIce:
-_toipatch="current-tuxonice-for-2.6.37.patch_0.bz2"
+_toipatch="current-tuxonice-for-3.0.patch.bz2"
 
 ##### Sources #####
 source=( #kernel sources and arch patchset
-	"ftp://ftp.kernel.org/pub/linux/kernel/v2.6/linux-${_basekernel}.tar.bz2"
-	"ftp://ftp.archlinux.org/other/kernel26/${patchname}.bz2"
+	"ftp://ftp.kernel.org/pub/linux/kernel/v3.0/linux-${_basekernel}.tar.bz2"
+	"ftp://ftp.kernel.org/pub/linux/kernel/v3.0/patch-${pkgver}.bz2"
+	#"ftp://ftp.archlinux.org/other/kernel26/${patchname}.bz2"
 	#external drivers:
 	"http://www.broadcom.com/docs/linux_sta/${broadcom}.tar.gz"
 	#"http://switch.dl.sourceforge.net/sourceforge/syntekdriver/stk11xx-$stk11xx_ver.tar.gz"
 	#BFS patch:
-	"http://www.kernel.org/pub/linux/kernel/people/ck/patches/2.6/${_basekernel}/${_basekernel}-ck${_ckpatchversion}/${_ckpatchname}.bz2"
+	"http://www.kernel.org/pub/linux/kernel/people/ck/patches/3.0/${_basekernel}.0-ck${_ckpatchversion}/${_ckpatchname}.bz2"
 	#BFQ patch:
 	"${_bfqpath}/0001-block-prepare-I-O-context-code-for-BFQ-v2-for-2.6.39.patch"
 	"${_bfqpath}/0002-block-cgroups-kconfig-build-bits-for-BFQ-v2-2.6.39.patch"
 	"${_bfqpath}/0003-block-introduce-the-BFQ-v2-I-O-sched-for-2.6.39.patch"
 	#TuxOnIce:
-	#http://www.tuxonice.net/files/${_toipatch}
+	"http://tuxonice.net/files/${_toipatch}"
 	#Arch Logo
 	"logo_linux_mono.pbm"
         "logo_linux_clut224.ppm"
@@ -79,20 +78,26 @@ source=( #kernel sources and arch patchset
 	"semaphore.patch"
 	"mutex-sema.patch"
 	"kernel-netbook.preset"
-	"fix_ck2.patch"
+	"fix-i915.patch"
+        "change-default-console-loglevel.patch"
 	"config")
 	
 build() {
-
-  #Hador's fix for 2.6.39.3
-  patch -N -i ${srcdir}/fix_ck2.patch
-
   cd ${srcdir}/linux-$_basekernel
 
   # patching the kernel with:
   # --> arch patchset
-  msg "Patching source with Arch Official Patchset:"
-  patch -Np1 -i ${srcdir}/$patchname
+  #msg "Patching source with Arch Official Patchset:"
+  # .1 patch:
+  patch -p1 -i "${srcdir}/patch-${pkgver}"
+
+  # fix #19234 i1915 display size
+  patch -Np1 -i "${srcdir}/fix-i915.patch"
+
+  # set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
+  # remove this when a Kconfig knob is made available by upstream
+  # (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
+  patch -Np1 -i "${srcdir}/change-default-console-loglevel.patch"
   
   # replace tux logo with arch one
   install -m644 ${srcdir}/logo_linux_clut224.ppm drivers/video/logo/
@@ -110,8 +115,8 @@ build() {
   if [ $TUX_ON_ICE = "y" ] ; then
     msg "Patching source with TuxOnIce patch"
     bzip2 -dck ${srcdir}/${_toipatch} \
-		| sed 's/printk(KERN_INFO "PM: Creating hibernation image:\\n/printk(KERN_INFO "PM: Creating hibernation image: \\n/' \
-		| patch -Np1 -F4 || return 1
+        | sed 's/printk(KERN_INFO "PM: Creating hibernation image:\\n/printk(KERN_INFO "PM: Creating hibernation image: \\n/' \
+        | patch -Np1 -F4 || { echo "Failed TOI"; return 1 ; }
   fi
 
   # --> BFQ
@@ -145,7 +150,10 @@ package_kernel-netbook() {
   pkgdesc='Static kernel for netbooks with Intel Atom N270/N280/N450/N550 such as eeepc with the add-on of external firmware (broadcom-wl) - Only Intel GPU - Give more power to your netbook!'
   depends=('coreutils' 'module-init-tools')
   install=kernel-netbook.install
-  optdepends=('crda: for wireless regulatory domain support' 'linux-firmware: firmware for rt2860 and tigon3')
+  optdepends=('crda: for wireless regulatory domain support' 
+	      'linux-firmware: firmware for rt2860, tigon3, brcmsmac'
+	      'hibernate-script: tux on ice default script'
+	      'tuxonice-userui: graphical interface for toi [AUR]')
   groups=(eee)
 
   cd ${srcdir}/linux-$_basekernel
@@ -156,7 +164,7 @@ package_kernel-netbook() {
   # Get kernel version
   _kernver="$(make kernelrelease)"
 
-  # remove the junk symlinks
+  # remove build and source links
   rm -r $pkgdir/lib/modules/$_kernver/{source,build}
   
   # remove the firmware directory
@@ -184,13 +192,6 @@ package_kernel-netbook() {
   make -C ${srcdir}/linux-$_basekernel M=`pwd`
   install -D -m 755 wl.ko ${pkgdir}/lib/modules/$_kernver/kernel/drivers/net/wireless/wl.ko
   
-##Section: stk11xx
-  #msg "Compiling stk11xx module:"
-  #cd $srcdir/stk11xx-$stk11xx_ver
-  #make -C $srcdir/linux-${_basekernel}/ SUBDIRS=$srcdir/stk11xx-2.1.0 modules
-  #install -D -m 644 $srcdir/stk11xx-$stk11xx_ver/stk11xx.ko $pkgdir/lib/modules/$_kernver/kernel/drivers/media/video
-  #install -D -m 644 $srcdir/stk11xx-$stk11xx_ver/README $pkgdir/usr/share/stk11xx.readme
-
   # gzip -9 all modules to safe a lot of MB of space
   find "$pkgdir" -name '*.ko' -exec gzip -9 {} \;
 }
@@ -198,109 +199,128 @@ package_kernel-netbook() {
 package_kernel-netbook-headers() {
   KARCH=x86
   pkgdesc='Header files and scripts for building modules for kernel-netbook'
-  mkdir -p ${pkgdir}/lib/modules/${_kernver}
-  cd ${pkgdir}/lib/modules/${_kernver}
+
+  mkdir -p "${pkgdir}/lib/modules/${_kernver}"
+
+  cd "${pkgdir}/lib/modules/${_kernver}"
   ln -sf ../../../usr/src/linux-${_kernver} build
-  cd ${srcdir}/linux-$_basekernel
+
+  cd "${srcdir}/linux-${_basekernel}"
   install -D -m644 Makefile \
-    ${pkgdir}/usr/src/linux-${_kernver}/Makefile
+    "${pkgdir}/usr/src/linux-${_kernver}/Makefile"
   install -D -m644 kernel/Makefile \
-    ${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile
+    "${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
   install -D -m644 .config \
-    ${pkgdir}/usr/src/linux-${_kernver}/.config
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/include
+    "${pkgdir}/usr/src/linux-${_kernver}/.config"
+
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
 
   for i in acpi asm-generic config crypto drm generated linux math-emu \
     media net pcmcia scsi sound trace video xen; do
-    cp -a include/$i ${pkgdir}/usr/src/linux-${_kernver}/include/
+    cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
   done
 
   # copy arch includes for external modules
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/arch/x86
-  cp -a arch/x86/include ${pkgdir}/usr/src/linux-${_kernver}/arch/x86/
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/arch/x86"
+  cp -a arch/x86/include "${pkgdir}/usr/src/linux-${_kernver}/arch/x86/"
 
   # copy files necessary for later builds, like nvidia and vmware
-  cp Module.symvers ${pkgdir}/usr/src/linux-${_kernver}
-  cp -a scripts ${pkgdir}/usr/src/linux-${_kernver}
+  cp Module.symvers "${pkgdir}/usr/src/linux-${_kernver}"
+  cp -a scripts "${pkgdir}/usr/src/linux-${_kernver}"
+
   # fix permissions on scripts dir
-  chmod og-w -R ${pkgdir}/usr/src/linux-${_kernver}/scripts
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/.tmp_versions
+  chmod og-w -R "${pkgdir}/usr/src/linux-${_kernver}/scripts"
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/.tmp_versions"
 
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/arch/$KARCH/kernel
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/kernel"
 
-  cp arch/$KARCH/Makefile ${pkgdir}/usr/src/linux-${_kernver}/arch/$KARCH/
-  if [ "$CARCH" = "i686" ]; then
-    cp arch/$KARCH/Makefile_32.cpu ${pkgdir}/usr/src/linux-${_kernver}/arch/$KARCH/
+  cp arch/${KARCH}/Makefile "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/"
+
+  if [ "${CARCH}" = "i686" ]; then
+    cp arch/${KARCH}/Makefile_32.cpu "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/"
   fi
-  cp arch/$KARCH/kernel/asm-offsets.s ${pkgdir}/usr/src/linux-${_kernver}/arch/$KARCH/kernel/
+
+  cp arch/${KARCH}/kernel/asm-offsets.s "${pkgdir}/usr/src/linux-${_kernver}/arch/${KARCH}/kernel/"
 
   # add headers for lirc package
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video
-  cp drivers/media/video/*.h  ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video"
+
+  cp drivers/media/video/*.h  "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/"
+
   for i in bt8xx cpia2 cx25840 cx88 em28xx et61x251 pwc saa7134 sn9c102; do
-   mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/$i
-   cp -a drivers/media/video/$i/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/$i
+    mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/${i}"
+    cp -a drivers/media/video/${i}/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/video/${i}"
   done
+
   # add docbook makefile
   install -D -m644 Documentation/DocBook/Makefile \
-    ${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile
+    "${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
+
   # add dm headers
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/md
-  cp drivers/md/*.h  ${pkgdir}/usr/src/linux-${_kernver}/drivers/md
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/md"
+  cp drivers/md/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/md"
+
   # add inotify.h
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/include/linux
-  cp include/linux/inotify.h ${pkgdir}/usr/src/linux-${_kernver}/include/linux/
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include/linux"
+  cp include/linux/inotify.h "${pkgdir}/usr/src/linux-${_kernver}/include/linux/"
+
   # add wireless headers
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/net/mac80211/
-  cp net/mac80211/*.h ${pkgdir}/usr/src/linux-${_kernver}/net/mac80211/
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/net/mac80211/"
+  cp net/mac80211/*.h "${pkgdir}/usr/src/linux-${_kernver}/net/mac80211/"
+
   # add dvb headers for external modules
   # in reference to:
   # http://bugs.archlinux.org/task/9912
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-core
-  cp drivers/media/dvb/dvb-core/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-core/
-  # add dvb headers for external modules
-  # in reference to:
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-core"
+  cp drivers/media/dvb/dvb-core/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-core/"
+  # and...
   # http://bugs.archlinux.org/task/11194
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/
-  cp include/config/dvb/*.h ${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/"
+  cp include/config/dvb/*.h "${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/"
+
   # add dvb headers for http://mcentral.de/hg/~mrec/em28xx-new
   # in reference to:
   # http://bugs.archlinux.org/task/13146
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
-  cp drivers/media/dvb/frontends/lgdt330x.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
-  cp drivers/media/video/msp3400-driver.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
-  # add dvb headers  
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/"
+  cp drivers/media/dvb/frontends/lgdt330x.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/"
+  cp drivers/media/video/msp3400-driver.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/"
+
+  # add dvb headers
   # in reference to:
   # http://bugs.archlinux.org/task/20402
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-usb
-  cp drivers/media/dvb/dvb-usb/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-usb/
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends
-  cp drivers/media/dvb/frontends/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/common/tuners
-  cp drivers/media/common/tuners/*.h ${pkgdir}/usr/src/linux-${_kernver}/drivers/media/common/tuners/
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-usb"
+  cp drivers/media/dvb/dvb-usb/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/dvb-usb/"
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends"
+  cp drivers/media/dvb/frontends/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/dvb/frontends/"
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/common/tuners"
+  cp drivers/media/common/tuners/*.h "${pkgdir}/usr/src/linux-${_kernver}/drivers/media/common/tuners/"
+
   # add xfs and shmem for aufs building
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/fs/xfs
-  mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/mm
-  cp fs/xfs/xfs_sb.h ${pkgdir}/usr/src/linux-${_kernver}/fs/xfs/xfs_sb.h
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/fs/xfs"
+  mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/mm"
+  cp fs/xfs/xfs_sb.h "${pkgdir}/usr/src/linux-${_kernver}/fs/xfs/xfs_sb.h"
+
   # copy in Kconfig files
-  for i in `find . -name "Kconfig*"`; do 
-    mkdir -p ${pkgdir}/usr/src/linux-${_kernver}/`echo $i | sed 's|/Kconfig.*||'`
-    cp $i ${pkgdir}/usr/src/linux-${_kernver}/$i
+  for i in `find . -name "Kconfig*"`; do
+    mkdir -p "${pkgdir}"/usr/src/linux-${_kernver}/`echo ${i} | sed 's|/Kconfig.*||'`
+    cp ${i} "${pkgdir}/usr/src/linux-${_kernver}/${i}"
   done
 
-  chown -R root.root ${pkgdir}/usr/src/linux-${_kernver}
-  find ${pkgdir}/usr/src/linux-${_kernver} -type d -exec chmod 755 {} \;
+  chown -R root.root "${pkgdir}/usr/src/linux-${_kernver}"
+  find "${pkgdir}/usr/src/linux-${_kernver}" -type d -exec chmod 755 {} \;
+
   # strip scripts directory
-  find ${pkgdir}/usr/src/linux-${_kernver}/scripts  -type f -perm -u+w 2>/dev/null | while read binary ; do
-  case "$(file -bi "$binary")" in
-    *application/x-sharedlib*) # Libraries (.so)
-    /usr/bin/strip $STRIP_SHARED "$binary";;
-    *application/x-archive*) # Libraries (.a)
-    /usr/bin/strip $STRIP_STATIC "$binary";;
-    *application/x-executable*) # Binaries
-    /usr/bin/strip $STRIP_BINARIES "$binary";;
-    esac 
-  done 
+  find "${pkgdir}/usr/src/linux-${_kernver}/scripts" -type f -perm -u+w 2>/dev/null | while read binary ; do
+    case "$(file -bi "${binary}")" in
+      *application/x-sharedlib*) # Libraries (.so)
+        /usr/bin/strip ${STRIP_SHARED} "${binary}";;
+      *application/x-archive*) # Libraries (.a)
+        /usr/bin/strip ${STRIP_STATIC} "${binary}";;
+      *application/x-executable*) # Binaries
+        /usr/bin/strip ${STRIP_BINARIES} "${binary}";;
+    esac
+  done
+
   # remove unneeded architectures
-  rm -rf ${pkgdir}/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
+  rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
 }
