updated on Wed Jan 29 00:34:27 UTC 2014

diff --git a/zen-puzzle-garden/PKGBUILD b/zen-puzzle-garden/PKGBUILD
--- a/zen-puzzle-garden/PKGBUILD
+++ b/zen-puzzle-garden/PKGBUILD
@@ -1,72 +1,53 @@
-# Maintainer: Zachary A. Jones <JazzplayerL9@gmail.com>
+# Maintainer: 404
+# Contributor: carstene1ns <url/mail: arch carsten-teibes de>
+# Contributor: Zachary A. Jones <JazzplayerL9@gmail.com>
 
 pkgname=zen-puzzle-garden
 pkgver=1.3
-pkgrel=2
-pkgdesc="Zen Puzzle Garden gently tests your ability to rake out an uninterrupted stone garden pattern.  You must purchase the game."
+pkgrel=3
+pkgdesc="Zen Puzzle Garden gently tests your ability to rake out an uninterrupted stone garden pattern."
 url="http://www.lexaloffle.com/zen.htm"
-license=('custom: "commercial"')
+license=('custom: commercial')
 groups=('humblevoxatronbundle' 'humblebundles')
 arch=('i686' 'x86_64')
-
-case $CARCH in
-    i686)
-        depends=('libgl' 'sdl')
-        optdepends=('alsa-lib: sound support' 'libpulse: sound support')
-    ;;
-    x86_64)
-        depends=('lib32-libgl' 'lib32-sdl')
-        optdepends=('lib32-alsa-lib: sound support' 'lib32-libpulse: sound suport')
-    ;;
-esac
-makedepends=('curl')
-options=(!strip)
-
-_gamepkg="${pkgname}_${pkgver}_i386.tar.gz"
-
-source=("${_gamepkg}::https://www.humblebundle.com/login"
-        "${_gamepkg}::http://www.humblebundle.com/downloads?key=${_humblevoxatronkey}"
-        "zpg.desktop"
-        "zen-exec")
-
-_char=\'
-DLAGENTS=('https::/bin/echo %o > /tmp/arch && sed -i "s/.part//" /tmp/arch && /usr/bin/curl -s --cookie-jar /tmp/cjar --output /dev/null %u && cp /tmp/cjar ./ && /usr/bin/curl -sL --cookie /tmp/cjar --cookie-jar /tmp/cjar --data "username=$_humbleemail" --data "password=$_humblepassword" %u | grep -f /tmp/arch |grep -o -E "data-web=[^ ]+"| sed -e "s/data-web=\([^ ]*\)/\1/" > /tmp/url && sed -i "s/$_char//g" /tmp/url && /usr/bin/curl --cookie /tmp/cjar --cookie-jar /tmp/cjar -fLC -  --retry 3 --retry-delay 3 -o %o "$(</tmp/url)" && rm -f /tmp/{arch,url} || return 0'
-          "http::/usr/bin/curl -sL %u | grep -m 1 zen-puzzle-garden | sed -e \"s/.*data-web='\([^']*\)'.*/url = \1/\" > /tmp/url && /usr/bin/curl -fLC -  --retry 3 --retry-delay 3 -o %o -K /tmp/url && rm /tmp/url")
-
-if [[ ! -f $SRCDEST/${source[0]%%:*} ]]; then
-    if [[ -z $_humbleemail || -z $_humblepassword ]]; then
-        if [[ -z $_humblevoxatronkey ]]; then
-            msg "if you have bound your email and password to your account, "
-            msg "please export the values _humbleemail and _humblepassword so"
-            msg "that you can be logged in to download the game."
-            echo
-            msg "if you have not bound the key to an email, "
-            msg "please export _humblevoxatronkey in your .bashrc"
-            return 1
-        fi
-    fi
+depends=('sh' 'libgl' 'sdl')
+optdepends=('alsa-lib: sound support'
+            'libpulse: sound support')
+if [ "$CARCH" == "x86_64" ]; then
+  depends=('sh' 'lib32-libgl' 'lib32-sdl')
+  optdepends=('lib32-alsa-lib: sound support'
+              'lib32-libpulse: sound support')
 fi
+options=('!strip')
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find $(echo %u | cut -c 7-). Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
-build() {
-   cd "${srcdir}"
-   install -d "${pkgdir}/opt/${pkgname}"
-   cp -R "${srcdir}"/${pkgname}/* "${pkgdir}/opt/${pkgname}/"
-}
+source=("hib://${pkgname}_${pkgver}_i386.tar.gz"
+        "$pkgname.desktop"
+        "$pkgname.sh")
+sha256sums=('8ad69e4dee5aa5b5d6edd041bc158a7e5eb5e0b2b14ce3c7049a91edd0786d95'
+            'b8bfb067705f1c9c0597c74d5942de344a7afe80a92381382ee9937c4172afab'
+            'fe03231e8c66953a3f825d831f3d89fb2eab3fc466b470e811386f48bd15386f')
 
 package(){
-  cd "${srcdir}"
-  # create Launcher
-  install -d "${pkgdir}/usr/bin/"
-  install -D -m755 "${srcdir}/zen-exec" "${pkgdir}/usr/bin/${pkgname}"
-  # Install Desktop File and Icon
-  install -D -m644 "${srcdir}/zpg.desktop" \
-        "${pkgdir}/usr/share/applications/${pkgname}.desktop"
-  install -D -m644 "${srcdir}/${pkgname}/lexaloffle-zen.png" \
-		"${pkgdir}/usr/share/icons/${pkgname}-icon.png"
-  # Install license
-  install -Dm 644 "${pkgdir}"/opt/${pkgname}/license.txt "${pkgdir}"/usr/share/licenses/${pkgname}/license
+  # binary + data
+  install -Dm755 $pkgname/zen "$pkgdir"/opt/$pkgname/zen
+  install -m644 $pkgname/zen.dat "$pkgdir"/opt/$pkgname
+  # launcher
+  install -Dm755 $pkgname.sh "$pkgdir"/usr/bin/$pkgname
+  # .desktop file and icon
+  install -Dm644 $pkgname.desktop "$pkgdir"/usr/share/applications/$pkgname.desktop
+  install -Dm644 $pkgname/lexaloffle-zen.png "$pkgdir"/usr/share/icons/$pkgname.png
+  # doc + license
+  install -Dm644 $pkgname/$pkgname.txt "$pkgdir"/usr/share/doc/$pkgname/$pkgname.txt
+  install -Dm644 $pkgname/license.txt "$pkgdir"/usr/share/licenses/$pkgname/license.txt
 }
-md5sums=('f13784e8a570bdc7e364089c85affe3e'
-         'f13784e8a570bdc7e364089c85affe3e'
-         'b8079d429b4c0abc4240b532fa2c8ec6'
-         '0808a805715b490f7712e1d820e39e56')
