updated on Thu Dec 20 17:00:03 UTC 2012

diff --git a/dustforce-hib/PKGBUILD b/dustforce-hib/PKGBUILD
--- a/dustforce-hib/PKGBUILD
+++ b/dustforce-hib/PKGBUILD
@@ -12,17 +12,17 @@ makedepends=('coreutils')
 depends=('mesa' 'sdl' 'libxau' 'libxdamage' 'libxdmcp' 'libxinerama' 'freealut'
          'fontconfig' 'libidn' 'libvorbis' 'zlib')
 source=('dustforce-hib.desktop')
-md5sums=('cbdc6b544c0011b72c9ade41ba4a4f63')
+md5sums=('fa688d289f57cd54eabde9e7ef354407')
 PKGEXT='.pkg.tar'
 
-_gamepkg="dustforce-linux-${_hibver}.sh"
-
+_installer="dustforce-linux-${_hibver}.sh"
+_installer_md5='afaca0c6241904becb66a29821f4dce4'
 
 package() {
   cd $srcdir
 
   # Get installer
-  _get_humblebundle_source "${_gamepkg}" || {
+  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
     error "Unable to find the game archive. Please download it from your Humble
            Bundle page, and place it into one of the above locations."
     exit 1; }
@@ -30,11 +30,11 @@ package() {
   # Execute installer
   msg "Starting setup..."
   [[ -d "./temp" ]] && rm -r "./temp"
-  sh "./${_gamepkg}" --unattended --no-register --packager pacman \
-                     --keep --overwrite \
-                     --target  "${srcdir}/temp" \
-                     --bindir  "${srcdir}/bin" \
-                     --datadir "${pkgdir}/opt"
+  sh "./${_installer}" --unattended --no-register --packager pacman \
+                       --keep --overwrite \
+                       --target  "${srcdir}/temp" \
+                       --bindir  "${srcdir}/bin" \
+                       --datadir "${pkgdir}/opt"
 
   # Remove bundled libraries & helper binaries (use system packages instead)
   rm -rf "${pkgdir}/opt/Dustforce/lib64/lib"{SDL-1.2.so.0}
@@ -49,33 +49,28 @@ package() {
                  "${pkgdir}/usr/share/pixmaps/dustforce.png"
 
   # Install launcher symlink
-  case $CARCH in
-      i686) _arch=x86 ;;
-      x86_64) _arch=x86_64;;
-  esac
+  case $CARCH in i686) _arch=x86 ;; x86_64) _arch=x86_64;; esac
   chmod 755 "${pkgdir}/opt/Dustforce/Dustforce.bin.$_arch"
   install -d "${pkgdir}/usr/bin"
   ln -s "/opt/Dustforce/Dustforce.bin.${_arch}" "${pkgdir}/usr/bin/dustforce"
 }
 
 
-# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
-_get_humblebundle_source() {
-  _get_local_source "$1" || return 1;
-  # TODO: Implement automatic downloading from Humble Bundle site
-}
+###### HELPER FUNCTIONS ######
 
-# Locate a file or folder provided by the user, and symlink it into $srcdir
+# Locates a file or folder provided by the user, and symlinks it into $srcdir
 _get_local_source() {
-  msg "Looking for '$1'..."
+  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
   declare -A _search=(['build dir']="$startdir"
                       ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
   for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
+    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
+    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
+      echo "NOT FOUND"
+    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
+      echo "CHECKSUM FAILED";
+    else
       echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-    echo "NOT FOUND"
   done
   if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
diff --git a/vessel/PKGBUILD b/vessel/PKGBUILD
--- a/vessel/PKGBUILD
+++ b/vessel/PKGBUILD
@@ -3,7 +3,7 @@
 pkgname=vessel
 pkgver=20121219
 _pkgver=12082012
-pkgrel=1
+pkgrel=2
 pkgdesc="Vessel is a physics-based, steampunk puzzle-platform video game developed by Strange Loop Games."
 url="http://www.strangeloopgames.com/"
 license=('custom')
@@ -28,10 +28,15 @@ makedepends=('unzip')
 options=('!strip')
 PKGEXT=".pkg.tar"
 
+_archive="${pkgname}-${_pkgver}-bin"
+_archive_md5='cdb4e42ac3dede4478f54bfe15ebfbeb'
+
 package() {
   mkdir -p "${pkgdir}/opt/games/${pkgname}"
-  _get_local_source "${pkgname}-${_pkgver}-bin" || error "Unable to find the game archive" exit 1;
-  unzip -u "${srcdir}/${pkgname}-${_pkgver}-bin" -d "${pkgdir}/opt/games/${pkgname}" || true
+  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
+  error "Unable to find the game archive. Please download it from your Humble Bundle page, and place it into one of the above locations."
+  exit 1; }
+  unzip -u "${srcdir}/${_archive}" -d "${pkgdir}/opt/games/${pkgname}" || true
   rm -rf "${pkgdir}/opt/games/${pkgname}/data/x86"
   rm "${pkgdir}/opt/games/${pkgname}/data/Linux.README"
   rm "${pkgdir}/opt/games/${pkgname}/data/Vessel"
@@ -44,17 +49,19 @@ package() {
     "${pkgdir}/opt/games/${pkgname}/data/x86/vessel.x86"
 }
 
-# Locate a file or folder provided by the user, and symlink it into ${srcdir}
+# Locates a file or folder provided by the user, and symlinks it into $srcdir
 _get_local_source() {
-  msg "Looking for '$1'..."
+  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
   declare -A _search=(['build dir']="$startdir"
                       ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
   for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "${srcdir}/$1"; break; fi
-    echo "NOT FOUND"
+    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
+    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
+      echo "NOT FOUND"
+    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
+      echo "CHECKSUM FAILED";
+    else
+      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
   done
-  if [ ! -e "${srcdir}/$1" ]; then return 1; fi
+  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
