updated on Thu Apr 28 04:30:50 PDT 2011

diff --git a/zsce-core/install.patch b/zsce-core/install.patch
--- a/zsce-core/install.patch
+++ b/zsce-core/install.patch
@@ -1,6 +1,6 @@
 --- ./install.sh 
 +++ ./install-patched.sh 
-@@ -20,28 +20,29 @@
+@@ -20,31 +20,32 @@
  WEB_GID=`id -g daemon`
  RC_FILE=/etc/zce.rc
  ZEND_USER=zend
@@ -47,7 +47,11 @@
 +#fi
  . ${ZCE_PREFIX}/bin/shell_functions.rc
  groupadd $ZEND_USER
- useradd -d ${ZCE_PREFIX}/gui/lighttpd -s /sbin/nologin -g $ZEND_USER $ZEND_USER 2>/dev/null
+-useradd -d ${ZCE_PREFIX}/gui/lighttpd -s /sbin/nologin -g $ZEND_USER $ZEND_USER 2>/dev/null
++useradd -r -m -d ${ZCE_PREFIX}/gui/lighttpd -s /sbin/nologin -g $ZEND_USER $ZEND_USER 2>/dev/null
+ if ! id -g $ZEND_USER > /dev/null 2>&1 ;then
+ 	echo "Could not create the zend group. This is mandatory for $PRODUCT_NAME to function properly. Aborting installation.."
+ 	exit 1
 @@ -140,8 +141,8 @@
  		ldconfig
  	fi
