updated on Tue Jul 19 11:01:02 UTC 2011

diff --git a/beep-game/PKGBUILD b/beep-game/PKGBUILD
--- a/beep-game/PKGBUILD
+++ b/beep-game/PKGBUILD
@@ -3,17 +3,17 @@
 pkgname=beep-game
 _pkgname=beep
 pkgver=1.1
-pkgrel=1
+pkgrel=2
 pkgdesc="a 2D side-scrolling platformer with physics-based gameplay. (requires copy of the full game)"
 url="http://www.gameolith.com/game/beep/"
 license=('custom: "commercial"')
 arch=('i686' 'x86_64')
 makedepends=()
-source=("${_pkgname}_${pkgver}_i386.tar.gz" "beep.sh" "beep.desktop")
-md5sums=('cad89e1eb67f2270dbd0c69e4dd22930'
-         '1cf275e07f42cd21f15b092c43b03484'
+source=("beep.sh" "beep.desktop")
+md5sums=('1cf275e07f42cd21f15b092c43b03484'
          'ae653c7ab8b7adf241901520c83752eb')
 
+_gamepkg="${_pkgname}_${pkgver}_i386.tar.gz"
 depends=('mesa')
 _depends64=('lib32-mesa')
 
@@ -22,10 +22,25 @@ if [[ $CARCH == x86_64 ]]; then
 fi
 
 build() {
-  cd ${srcdir}
-  mkdir -p ${pkgdir}/opt/${_pkgname}
-  cp -R ${srcdir}/{lib,Art} ${pkgdir}/opt/${_pkgname}/
-  cp ${srcdir}/BEEP.bin32 ${pkgdir}/opt/${_pkgname}/
+   cd ${srcdir}
+   msg "You need a full copy of this game in order to install it"
+   msg "Searching for ${_gamepkg} in dir: \"$startdir\""
+   pkgpath=$startdir
+   if [[ ! -f "$startdir/${_gamepkg}" ]]; then
+       error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
+       read pkgpath
+       if [[ ! -f "${pkgpath}/${_gamepkg}" ]]; then
+           error "Unable to find game package." && return 1
+       fi
+    fi
+    msg "Found game package, installing..."
+
+    ln -fs ${pkgpath}/${_gamepkg} . || return 1
+    tar xvf ${pkgpath}/${_gamepkg} || return 1
+
+  install -d ${pkgdir}/opt/${_pkgname}
+  cp -R ${srcdir}/BEEP/{lib,Art} ${pkgdir}/opt/${_pkgname}/
+  cp ${srcdir}/BEEP/BEEP.bin32 ${pkgdir}/opt/${_pkgname}/
 
 }
 
@@ -39,7 +54,10 @@ package(){
   install -D -m644 ${srcdir}/${_pkgname}.desktop \
         ${pkgdir}/usr/share/applications/${_pkgname}.desktop
 
+  # Install license
+  install -D -m644 ${srcdir}/BEEP/EULA.rtf ${pkgdir}/usr/share/licenses/beep-game/EULA.rtf
+
   # Make save game Directory with user group permissions (config)
   install -d -m775 -g users ${pkgdir}/opt/${_pkgname}/Art/Save/
-  install -m644 -g users ${srcdir}/Art/Settings.xml ${pkgdir}/opt/${_pkgname}/Art/
+  install -m644 -g users ${srcdir}/BEEP/Art/Settings.xml ${pkgdir}/opt/${_pkgname}/Art/
 }
