updated on Thu May 12 08:30:55 PDT 2011

diff --git a/kernel26-natty-git/PKGBUILD b/kernel26-natty-git/PKGBUILD
--- a/kernel26-natty-git/PKGBUILD
+++ b/kernel26-natty-git/PKGBUILD
@@ -9,20 +9,24 @@ pkgname=kernel26$_pkgext
 (( 1 )) && pkgname=("kernel26${_pkgext}" "kernel26${_pkgext}-headers" "kernel26${_pkgext}-docs")
 pkgdesc="The Ubuntu Kernel and modules from natty git tree"
 
-pkgver=20110222
+pkgver=20110512
 pkgrel=1
 url="http://kernel.ubuntu.com/git-repos/ubuntu/ubuntu-natty.git/"
 arch=(i686 x86_64)
 license=('GPL2')
-depends=('coreutils' 'linux-firmware-git' 'module-init-tools>=3.12-2' 'mkinitcpio>=0.6.8')
-makedepends=('git')
+depends=('coreutils' 'linux-firmware-git' 'module-init-tools>=3.12-2' 'mkinitcpio>=0.6.8-2')
+makedepends=('git' 'xmlto' 'docbook-xsl')
+backup=(etc/mkinitcpio.d/$pkgname.preset)
+install=$pkgname.install
+changelog=$pkgname.changelog
 source=(config.{i686,x86_64})
-md5sums=('7a79814f9ed75d69e29bfcdf56960978'
-         '0a55d2a3f5ecd2b0c97ced120f6c9d70')
-sha256sums=('647f9e336834ef2018d173ce6c86ccf25a400725c2168846846c27d5ecb29fe7'
-            '32ae30e46f59203abbc7a36209f0e1a272ea802f5ceb3a180591a5b5b06e2cfb')
+md5sums=('9dcccee11358143b86b22036b2da73fc'
+         '2f188477857d3f88bb8d48f2e1b62085')
+sha256sums=('c0fa684833ee64e021b01ce1322b3c9f31d299faa0e9b282da52aa64fab1b9f5'
+            '1f5a6eff737dfc24366884e36827f3a7957bf65ebe8273b33395d66425e0c654')
 _gitroot="git://kernel.ubuntu.com/ubuntu/ubuntu-natty.git"
 _gitname="ubuntu-natty"
+
 
 ####################################################################
 # KERNEL CONFIG FILES
@@ -110,7 +114,7 @@ _build_dir="${_build_dir:-$srcdir}"
 # Save the .config file to package directory
 # as config.saved.$CARCH
 #
-# _save_config=1
+ _save_config=1
 
 
 #######
@@ -123,7 +127,6 @@ _build_dir="${_build_dir:-$srcdir}"
 # Make the kernel build process verbose
 #
 # _verbose=1
-
 
 # internal variables
 if [[ -n $_gitname && -n $_gitroot ]]; then
@@ -151,47 +154,42 @@ eval "package_kernel26${_pkgext}-docs() { _generic_package_kernel-docs; }"
 # where the magic happens...
 ##############################
 build() {
-	if [[ -n $_gitname && -n $_gitroot ]]; then
-		#################################
-		# Get the latest kernel sources
-		#################################
-		msg "Fetching sources..."
 
-		cd "$startdir"
-		if [[ -d $_gitname ]]; then
-			msg2 "Updating sources..."
-			cd "$_gitname"
-			git fetch || true
-			cd "$OLDPWD"
-		else
-			msg2 "Cloning the project..."
-			warning "The initial clone will download approximately 300 mb"
-			git clone --mirror "$_gitroot" "$_gitname"
-		fi
+	#################################
+	# Get the latest kernel sources
+	#################################
+	msg "Fetching sources..."
 
-		msg "Creating build branch..."
-		rm -rf "$_kernel_src"
-		git clone "$_gitname" "$_kernel_src"
+	cd "$startdir"
+	if [[ -d $_gitname ]]; then
+		msg2 "Updating sources..."
+		cd "$_gitname"
+		git fetch || true
+		cd "$OLDPWD"
+	else
+		msg2 "Cloning the project..."
+		warning "The initial clone will download approximately 375 mb"
+		git clone --mirror "$_gitroot" "$_gitname"
 	fi
+
+	msg "Creating build branch..."
+	rm -rf "$_kernel_src"
+	git clone "$_gitname" "$_kernel_src"
 
 	cd "$_kernel_src"
 
 	#################
 	# Apply patches
 	#################
-	msg "Applying patches..."
-	local i patches
-	for i in "${source[@]}"; do
-		i=${i##*/}
-		[[ $i =~ .*\.patch$ ]] && patches=("${patches[@]}" "$srcdir/$i")
-		[[ ${i%.*} =~ .*\.patch$ ]] && patches=("${patches[@]}" "$srcdir/${i%.*}")
-	done
-
 	shopt -s nullglob
-	for i in "${patches[@]}" "$startdir/patches/"*; do
-		msg2 "Applying ${i##*/}..."
-		patch -Np1 -i "$i" || (error "Applying ${i##*/} failed" && return 1)
-	done
+	if [[ -d $startdir/patches && -n $(echo "$startdir/patches/"*) ]]; then
+		msg "Applying patches..."
+		local i
+		for i in "$startdir/patches/"*; do
+			msg2 "Applying ${i##*/}..."
+			patch -Np1 -i "$i" || (error "Applying ${i##*/} failed" && return 1)
+		done
+	fi
 	shopt -u nullglob
 
 
@@ -287,8 +285,8 @@ build() {
 		mv "$_kernel_src" "$srcdir"
 		rm -rf "$_kernel_src"
 	fi
-}
 
+}
 
 _generic_package_initialization() {
 	cd "$_kernel_src"
@@ -313,7 +311,7 @@ _generic_package_initialization() {
 
 _generic_package_kernel() {
 	pkgdesc="The Ubuntu Kernel and modules from natty git tree"
-	depends=('coreutils' 'linux-firmware-git' 'module-init-tools>=3.12-2' 'mkinitcpio>=0.6.8')
+	depends=('coreutils' 'linux-firmware-git' 'module-init-tools>=3.12-2' 'mkinitcpio>=0.6.8-2')
 	backup=(etc/mkinitcpio.d/$pkgname.preset)
 	install=$pkgname.install
 	changelog=$pkgname.changelog
