updated on Tue Jul 30 20:23:26 UTC 2013

diff --git a/nightsky-game/PKGBUILD b/nightsky-game/PKGBUILD
--- a/nightsky-game/PKGBUILD
+++ b/nightsky-game/PKGBUILD
@@ -1,77 +1,51 @@
-# Maintainer: Yann Kaiser <kaiser.yann@gmail.com>
+# Maintainer: Claudio Kozicky <claudiokozicky@gmail.com>
+# Contributor: Yann Kaiser <kaiser.yann@gmail.com>
+
 pkgname=nightsky-game
 pkgver=1.0.0
-_pkgver=1324519044
-pkgrel=3
-pkgdesc="A 2D platformer in which you control a ball"
-arch=('i686' 'x86_64')
+_timestamp=1324519044
+pkgrel=4
+pkgdesc="A 2D platformer in which you control a ball."
+arch=(i686 x86_64)
 url="http://www.nicalis.com/nightsky/"
-license=('custom')
-depends=('libgl' 'libvorbis' 'mesa' 'zlib')
-makedepends=()
-source=('nightsky-game.sh' 'nightsky-game.desktop')
-md5sums=('6dc6459dbed8d42396320b4560c3605d'
-         'a2abc9a74a21b99574bf51ad5f8b6f1b')
+license=(custom)
+depends=(freealut freeglut glu libvorbis)
+options=(!strip)
+source=(hib://nightskyhd-linux-$_timestamp.tar.gz
+        $pkgname.sh
+        $pkgname.desktop
+        $pkgname.png::https://humblepull-wolfire.netdna-ssl.com/misc/files/a27ab5a048/images/icons/nightsky.png)
+md5sums=(73a937ffb5dfd5fc9ba95efacba0a25f
+         b4c6369d71ed1226e873de1d182886b0
+         90de87c9cdec492d21c5dab1a69b5484
+         07b66bdc63fc5953899ce1158231e93c)
+DLAGENTS+=('hib::/usr/bin/echo Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf.; exit 1')
+PKGEXT=.pkg.tar
 
-_archive_name="NightSky"
-_archive_md5="73a937ffb5dfd5fc9ba95efacba0a25f"
-_archive="nightskyhd-linux-${_pkgver}.tar.gz"
-
-build() {
-  cd ${srcdir}
-
-  if [ ! -f ${_nightskyarchivelocation}${_archive} ]; then
-	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-		wget http://www.humblebundle.com/?key=${_humblebundle4key}
-		wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-		mv ${_archive}* ${_archive}
-	  elif [ -z "${_humblebundle4key}" ]; then
-		echo You can automate the download of the archive using the _humblebundle4key bash variable.
-		echo Just add \'export _humblebundle4key\=\<Your key here\>\' to \.bashrc
-		echo
-		echo Otherwise please just place ${_archive} into $(pwd)/
-		echo Press Enter to continue
-		read -a _unused
-	  fi
-  fi
-  #'
-
-  if [ ! -f ${_nightskyarchivelocation}${_archive} ]; then
-    echo "${_nightskyarchivelocation}${_archive} not found!"
-    return 1
-  fi
-
-  if ! echo "${_archive_md5}  ${_nightskyarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_nightskyarchivelocation}${_archive}"
-    return 1
-  fi
-
-  bsdtar -xf ${_nightskyarchivelocation}${_archive}
-
-  cd ${srcdir}/${_archive_name}
-
-  rm lib/lib{vorbis,vorbisfile,ogg}.so*
-  if test "${CARCH}" == "x86_64"; then
-    rm ${_archive_name}HD
-    mv ${_archive_name}HD_64 ${_archive_name}HD
-    rm -R lib
-  else
-    rm ${_archive_name}HD_64
-    rm -R lib64
-  fi
-
-  cp ${srcdir}/${pkgname}.sh ${srcdir}/${_archive_name}/
-
-  mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/bin/ \
-    ${pkgdir}/usr/share/applications
-  cp -r ${srcdir}/${_archive_name} ${pkgdir}/opt/NightSkyHD
-  cp ${srcdir}/${pkgname}.desktop ${pkgdir}/usr/share/applications/
-  ln -s /opt/NightSkyHD/${pkgname}.sh \
-    ${pkgdir}/usr/bin/${pkgname}
-  chmod a+r ${pkgdir}/usr/share/applications/${pkgname}.desktop
-  chmod a+x ${pkgdir}/opt/NightSkyHD/${pkgname}.sh
+prepare()
+{
+    # cleanup
+    cd "$srcdir"/NightSky
+    rm -r lib lib64
+    [ $CARCH = x86_64 ] \
+        && mv NightSky{HD_64,HD} \
+        || rm NightSkyHD_64
 }
 
-# vim: et ts=2 sw=2 sts=2
+package()
+{
+    cd "$srcdir"
 
+    # data
+    find NightSky -name NightSkyHD -prune -o -type f -exec install -Dm644 {} "$pkgdir"/opt/{} \;
+    install -m755 NightSky/NightSkyHD "$pkgdir"/opt/NightSky
+
+    # launcher
+    install -Dm755 $pkgname.sh "$pkgdir"/usr/bin/$pkgname
+
+    # desktop integration
+    install -Dm644 $pkgname.desktop "$pkgdir"/usr/share/applications/$pkgname.desktop
+    install -Dm644 $pkgname.png "$pkgdir"/usr/share/pixmaps/$pkgname.png
+}
+
+# vim:et:sw=4:sts=4
