updated on Sun Mar 11 16:00:19 UTC 2012

diff --git a/wicd-eduroam-rub/eduroam-rub.install b/wicd-eduroam-rub/eduroam-rub.install
--- a/wicd-eduroam-rub/eduroam-rub.install
+++ b/wicd-eduroam-rub/eduroam-rub.install
@@ -1,18 +1,19 @@
 #!/bin/sh
 
 post_install(){
-    echo Adding eduroam to active list...
+    echo -n "Adding eduroam to active list... "
     if grep eduroam-rub /etc/wicd/encryption/templates/active > /dev/null 
     then
-        echo Eduroam was already installed!
+        echo -e "[FAIL]\nEduroam was already installed!"
+        exit 1
     else
-        echo eduroam-rub >> /etc/wicd/encryption/templates/active && echo Eduroam added to active list
+        echo "eduroam-rub" >> /etc/wicd/encryption/templates/active && echo "[DONE]"
     fi
 }
 post_remove(){
-    echo -n Deleting eduroam from active list...
+    echo -n "Deleting eduroam from active list... "
     sed -e '/^eduroam-rub$/d' -i /etc/wicd/encryption/templates/active
-    echo ' [DONE]'
+    echo "[DONE]"
 }
 
 post_remove
