updated on Thu Apr 18 04:11:11 UTC 2013

diff --git a/dooble/PKGBUILD b/dooble/PKGBUILD
--- a/dooble/PKGBUILD
+++ b/dooble/PKGBUILD
@@ -1,59 +1,56 @@
-# -*- shell-script -*-
-# Maintainer:  Mattias Andrée
-
+# Maintainer: Mattias Andrée <`base64 -d`(bWFhbmRyZWUK)@member.fsf.org>
 pkgname=dooble
-pkgver=1.41
+pkgver=1.42_dev
 pkgrel=1
+_r=r5278
 pkgdesc='A safe WebKit Web browser'
-url=http://dooble.sourceforge.net/
-arch=(x86_64)
-license=(GPL2)
-source=("http://downloads.sourceforge.net/project/dooble/Version%201.41/Dooble_Lin64.tar.gz?r=&ts=1365713519&use_mirror=netcologne")
-md5sums=(7f005db2e1a057fe7f5c871855c6e25d)
-depends=(libpng12)
+url='http://dooble.sourceforge.net/'
+arch=('i386' 'x86_64')
+license=('GPL2')
+depends=('bzip2' 'fontconfig' 'gstreamer0.10-base' 'libgcrypt' 'libjpeg'
+         'libsm' 'libxrender' 'mesa-libgl' 'openssl' 'qtwebkit' 'udev' 'xz')
+# Transversally included dependencies:  glibc expat freetype2 pcre libffi glib2 libxml2 orc gstreamer0.10 zlib util-linux-ng
+#                                       libice libxcb libx11 libxfixes libxext libxdamage libdrm mesa libpng sqlite gcc-libs
+#                                       libxau libxdmcp libxxf86vm qt4 libgpg-error
+makedepends=('svn')
+options=('!emptydirs')
 
-_sedfiles="dooble.sh qt.conf"
 
+build()
+{
+    cd "$srcdir"
+    svn co -r "${_r}" "https://dooble.svn.sourceforge.net/svnroot/dooble" dooble
+    cd "dooble/trunk/browser/"
+    sed -i 's_-Werror__g' dooble.pro
+    qmake-qt4 -o Makefile dooble.pro
+    make
+}
 
 package()
 {
-	msg "Moving precompiled files into \$pkgdir"
-	
-	mv "$srcdir/usr" "$pkgdir"
-	
-	
-	msg "Fixing file structure"
-	
-	mkdir "$pkgdir/opt"
-	mv "$pkgdir/usr/local/dooble" "$pkgdir/opt"
-	rmdir "$pkgdir/usr/local/" || echo "Cannot remove \$pkgdir/usr/local/"
-	rmdir "$pkgdir/usr/"       || echo "Cannot remove \$pkgdir/usr/"
-
-
-	msg "Editing files for the file structure modification"
-	
-	for file in $_sedfiles
-	do
-	    sed -i s_'/usr/local/dooble'_'/opt/dooble'_g "$pkgdir/opt/dooble/$file"
-	done
-	
-	for file in "Dooble"
-	do
-            ## hehehe
-	    sed -i s_'/usr/local/dooble/Lib\x00'_'/opt/dooble/Lib\x00\x00\x00\x00\x00\x00\x00'_g  "$pkgdir/opt/dooble/$file"
-	done
-	
-	# libudev.so.0 does not exist, but libudev.so.1 works
-	sed -i 's_libudev.so.0_libudev.so\x00\x00_g' "$pkgdir/opt/dooble/Lib/libQt5WebKit.so.5"
-	sed -i 's_libudev.so.0_libudev.so\x00\x00_g' "$pkgdir/opt/dooble/Plugins/generic/libqevdevtabletplugin.so"
-	sed -i 's_libudev.so.0_libudev.so\x00\x00_g' "$pkgdir/opt/dooble/Plugins/generic/libqevdevkeyboardplugin.so"
-	sed -i 's_libudev.so.0_libudev.so\x00\x00_g' "$pkgdir/opt/dooble/Plugins/generic/libqevdevtouchplugin.so"
-	sed -i 's_libudev.so.0_libudev.so\x00\x00_g' "$pkgdir/opt/dooble/Plugins/generic/libqevdevmouseplugin.so"
-
-	
-	
-	msg "Renaming \$pkgdir/opt/dooble/dooble.sh to \$pkgdir/opt/dooble/dooble"
-	
-	mv "$pkgdir/opt/dooble/dooble.sh" "$pkgdir/opt/dooble/dooble"
+    cd "$srcdir/dooble/trunk/browser/"
+    make INSTALL_ROOT="$pkgdir" install
+    
+    msg "Fixing file structure"
+    mkdir "$pkgdir/opt"
+    mv "$pkgdir/usr/local/dooble" "$pkgdir/opt"
+    mv "$pkgdir/usr/local/include" "$pkgdir/usr"
+    rmdir "$pkgdir/usr/local/" || echo "Cannot remove \$pkgdir/usr/local/"
+    
+    msg "Editing files for the file structure modification"
+    sed -i s_'/usr/local/dooble'_'/opt/dooble'_g "$pkgdir/opt/dooble/dooble.sh"
+    sed -i s_'/usr/local/dooble/Lib\x00'_'/opt/dooble/Lib\x00\x00\x00\x00\x00\x00\x00'_g "$pkgdir/opt/dooble/Dooble"
+    
+    msg "Renaming \$pkgdir/opt/dooble/dooble.sh to \$pkgdir/opt/dooble/dooble"
+    mv "$pkgdir/opt/dooble/dooble.sh" "$pkgdir/opt/dooble/dooble"
+    
+    # XXX: This will have been resolved in 1.42 (without -dev)
+    if [ ! -f "$pkgdir/opt/dooble/Lib/libspoton.so" ]; then
+        msg "Installing files missed by the installer"
+        mkdir -p "$pkgdir/opt/dooble/Lib"
+        cp "$srcdir/dooble/trunk/browser/LibSpotOn/libspoton.so" "$pkgdir/opt/dooble/Lib"
+    else
+        msg "Notify maintainer about obsolete installation instruction."
+    fi
 }
 
diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -1,46 +1,159 @@
 #!/bin/bash
 
-KERNEL=`uname -r | sed 's/-.*//'`
-VMWARE_VERSION=`vmware-installer -l | egrep "vmware-workstation|vmware-player" | cut -s -d " " -f 2- | cut -d '.' -f -3`
-VMWARE_VERSION=${VMWARE_VERSION// }
+# Some colored makepkg-like functions
+msg() {
+    printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
 
-VMWARE="/usr/lib/vmware/patches/"
+msg2() {
+    printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
 
-echo "Patching vmware ${VMWARE_VERSION} for kernel ${KERNEL}"
+msg3() {
+    printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
 
-timestamp=`date +%Y%m%d-%H%M%S`
-if [ `whoami` != "root" ]
-then
-  echo "This need to be run as root"
-  exit 1
+error() {
+    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
+
+ALL_OFF="$(tput sgr0)"
+BOLD="$(tput bold)"
+BLUE="${BOLD}$(tput setaf 4)"
+GREEN="${BOLD}$(tput setaf 2)"
+RED="${BOLD}$(tput setaf 1)"
+YELLOW="${BOLD}$(tput setaf 3)"
+
+# Make sure we are root
+if [ $(whoami) != "root" ]; then
+    error "This script needs to be run as root."
+    exit 1
 fi
 
-cd $VMWARE
-
-#DEPRECATED SINCE VMWORKSTATION 8
-#echo "Not patching vmware modconfig libraries (not required since vmware player/workstation 8.0)"
-
-echo "Patching vmware modules source code:"
-for mod in `ls *-${VMWARE_VERSION}-*${KERNEL}.diff | sed "s/-.*${VMWARE_VERSION}.*${KERNEL}.diff//"`
-do
-  echo "* Patching ${mod} ..."
-  SRC="/usr/lib/vmware/modules/source/${mod}.tar"
-  cp ${SRC} ${SRC}-${VMWARE_VERSION}-${timestamp}
-  tar -xf ${SRC}
-  cd ${mod}-only
-  patch -p1 < ../${mod}-*${VMWARE_VERSION}*-${KERNEL}.diff
-  res=$?
-  cd ..
-  if [ $res -ne 0 ]
-  then
-    echo "  [${mod}-only] Failed to apply patch"
-    rm -rf ${mod}-only
+# Is a VMware product installed?
+if [ ! -f /usr/bin/vmware-installer ]; then
+    error "No VMware product found. Exiting.."
     exit 1
-  else
-    echo "  [${mod}-only] Patch applied successfully"
-  fi
+fi
 
-  tar cf ${mod}.tar ${mod}-only
-  cp ${mod}.tar ${SRC}
-  rm -rf ${mod}.tar ${mod}-only
-done
+# Set some variables (|&: hide "No protocol specified" in KDE by redirecting all output to cut/grep)
+KERNEL=$(uname -r | cut -d "." -f-2)
+VER=$(vmware-installer -l |& egrep "(player|workstation)" | grep -Po "(\d\.){2}\d")
+if [ $(vmware-installer -l |& egrep "(player|workstation)" | cut -d " " -f1) = "vmware-workstation" ]; then
+    NAME="VMware Workstation"
+else
+    NAME="VMware Player"
+fi
+
+# Make sure vmware.service includes our USB Arbitrator service
+if [[ ! $(grep usbarbitrator /usr/lib/systemd/system/vmware.service) ]]; then
+    msg "Updating vmware.service.."
+    sed '/Description/a Requires=vmware-usbarbitrator.service\nBefore=vmware-usbarbitrator.service' \
+         -i /usr/lib/systemd/system/vmware.service
+fi
+
+# Make sure there's a version in /etc/arch-release:
+# https://wiki.archlinux.org/index.php/Vmware#2.29_The_vmware-usbarbitrator_binary_is_segfaulting
+if [ ! $(cat /etc/arch-release) ]; then
+    msg "Updating /etc/arch-release.."
+    echo 2013.04.01 > /etc/arch-release
+fi
+
+# Backup/Convert/Remove old ones, whatever necessary
+cd /usr/lib/vmware/modules/
+# 1) Use double quotes ("[[") and "ls" instead of the builtin -d/-f for multiple arguments
+# 2) 2>&-: supported by "ls", basically same as "2>/dev/null" only shorter (ignore errors (STDERR))
+if [[ $(ls -d source?*/ source/*.tar-* 2>&- | grep -vx source-${VER}/) ]]; then
+    msg "Cleaning up old backups.."
+    # 1) Check the new location first
+    # 2) Remove any duplicated/old ones
+    # 3) Print full paths
+    # 4) Sed: leave out the first result containing ${VER}
+    for i in $(readlink -e source?*/ | sed "0,/${VER}/{//d}"); do
+        msg2 "Removing ${i}"
+        rm -r "${i}"
+    done
+    # If we already have a backup in the new location, remove any from the old one
+    if [ -d source-${VER}*/ ]; then
+        for i in $(readlink -e source/*.tar-*); do
+            msg2 "Removing ${i}"
+            rm -r "${i}"
+        done
+        # Rename it as we like (or as I do)
+        if [ -d source-${VER}?*/ ]; then
+            msg3 "Renaming: $(readlink -f source-${VER}*)/ -> $(readlink -f source-${VER})/"
+            mv source-${VER}*/ source-${VER}/
+        fi
+    else
+        # Remove any duplicated/old backups
+        for i in vmblock vmci vmmon vmnet vsock; do
+            for j in $(readlink -e source/${i}.tar-* | sed "0,/${VER}/{//d}"); do
+                msg2 "Removing ${j}"
+                rm -r "${j}"
+            done
+        done
+        # Convert leftovers
+        if [ -f source/vmblock.tar-* ]; then
+            # Shorten the msg3 command
+            _old=$(readlink -f source/vmblock.tar-* | sed 's/vmblock/*/')
+            msg3 "Converting: ${_old} -> $(readlink -f source-${VER})/"
+            mkdir source-${VER}/
+            for i in vmblock vmci vmmon vmnet vsock; do
+                mv source/${i}.tar-* source-${VER}/${i}.tar
+            done
+        fi
+    fi
+fi
+
+# 1) Have we already built (vsock is built last)?
+# 2) Don't check this until now so that we can remove the leftovers
+if [ -f /usr/lib/modules/$(uname -r)/misc/vsock.ko ]; then
+    error "VMware modules already installed. Exiting.."
+    exit 1
+fi
+
+# 1) Make sure we can build
+# 2) Shorther without double brackets ("[["):
+# 3) &>/dev/null: hide all output (STDIN/STDERR)
+if ls patches/*${VER}*${KERNEL}*.patch &>/dev/null; then
+    # Create a backup/Revert
+    if [ ! -d source-${VER} ]; then
+        msg "Creating a backup.."
+        cp -r source/ source-${VER}/
+    else  # Get the original sources from the backup (invalidate the need for 'vmware-unpatch')
+        cp source-${VER}/* source/
+    fi
+    msg "Patching ${NAME} v${VER} for kernel $(uname -r).."
+    # Loop modules that require patching (vmblock, vmci, vmmon, vmnet and/or vsock)
+    cd source
+    for mod in $(ls ../patches/*${VER}*${KERNEL}*.patch | cut -d "/" -f3 | cut -d "-" -f1); do
+        # Untar
+        tar -xf ${mod}.tar
+        # Patch
+        msg2 "Patching ${mod}.."
+        # Shorten
+        _patch=../patches/${mod}*${VER}*${KERNEL}*.patch
+        if patch -p0 -s -f -i ${_patch}; then
+            msg3 "[${mod}] Succesfully patched."
+        else  # Not gonna happen
+            error "[${mod}] Failed to apply '$(basename ${_patch})'."
+            msg "Reverting.."
+            # Revert
+            cd ..
+            rm -r source/
+            mv source-${VER}/ source/
+            msg "Done."
+            exit 1
+        fi
+        # Tar patched modules
+        tar -cf ${mod}.tar ${mod}-only
+        rm -r ${mod}-only
+    done
+else
+    msg "No patching required."
+fi
+
+# Install
+msg "Installing modules.."
+vmware-modconfig --console --install-all &>/dev/null
+msg "Done."
diff --git a/vmware-patch/vmware-unpatch b/vmware-patch/vmware-unpatch
--- a/vmware-patch/vmware-unpatch
+++ b/vmware-patch/vmware-unpatch
@@ -1,50 +1,104 @@
 #!/bin/bash
 
-KERNEL=`uname -r | sed 's/-.*//'`
+# Some colored makepkg-like functions
+msg() {
+    printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
 
-VMWARE_VERSION=`vmware-installer -l | egrep "vmware-workstation|vmware-player" | cut -s -d " " -f 2- | cut -d '.' -f -3`
-VMWARE_VERSION=${VMWARE_VERSION// }
+msg2() {
+    printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
 
-echo "Reverting vmware patches applied for version ${VMWARE_VERSION}"
+msg3() {
+    printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
 
-timestamp=`date +%Y%m%d-%H%M%S`
-if [ `whoami` != "root" ]
-then
-  echo "This need to be run as root"
-  exit 1
+error() {
+    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+}
+
+ALL_OFF="$(tput sgr0)"
+BOLD="$(tput bold)"
+BLUE="${BOLD}$(tput setaf 4)"
+GREEN="${BOLD}$(tput setaf 2)"
+RED="${BOLD}$(tput setaf 1)"
+YELLOW="${BOLD}$(tput setaf 3)"
+
+# Make sure we are root
+if [ $(whoami) != "root" ]; then
+    error "This script needs to be run as root."
+    exit 1
 fi
 
-#DEPRECATED SINCE VMWORKSTATION 8
-#echo "Reverting vmware modconfig libraries:"
-#for mod in `echo \
-#/usr/lib/vmware/lib/libvmware-modconfig-console.so/libvmware-modconfig-console.so  \
-#/usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so \
-#`
-#do
-#  mv "${mod}".bak "${mod}"
-#  res=$?
-#  if [ $res -ne 0 ]
-#  then
-#    echo "* Failed to revert "`basename ${mod}`" (or nothing to revert)"
-#  else
-#    echo "* "`basename ${mod}`" reverted successfully"
-#  fi
-#done
+# Is a VMware product installed?
+if [ ! -f /usr/bin/vmware-installer ]; then
+    error "No VMware product found. Exiting.."
+    exit 1
+fi
 
-echo "Reverting vmware modules source code:"
+# Set some variables (|&: hide "No protocol specified" in KDE by redirecting all output to cut/grep)
+VER=$(vmware-installer -l |& egrep "(player|workstation)" | grep -Po "(\d\.){2}\d")
+if [ $(vmware-installer -l |& egrep "(player|workstation)" | cut -d " " -f1) = "vmware-workstation" ]; then
+    NAME="VMware Workstation"
+else
+    NAME="VMware Player"
+fi
 
-SRC="/usr/lib/vmware/modules/source/"
-for mod in `ls $SRC*.tar-* | sed "s/.*\/\(.*\).tar-.*/\1/" | sort | uniq`
-do
-  echo "* Reverting ${mod} ..."
-  LAST=`ls $SRC$mod.tar-${VMWARE_VERSION}* | sort | head -n 1`
-  cp $LAST $SRC$mod.tar
-  res=$?
-  if [ $res -ne 0 ]
-  then
-    echo "  [${mod}-only] Failed to revert (or nothing to revert)"
-  else
-    echo "  [${mod}-only] Reverted successfully"
-  fi
+# Backup/Convert/Remove old ones, whatever necessary
+cd /usr/lib/vmware/modules/
+# 1) Use double quotes ("[[") and "ls" instead of the builtin -d/-f for multiple arguments
+# 2) 2>&-: supported by "ls", basically same as "2>/dev/null" only shorter (ignore errors (STDERR))
+if [[ $(ls -d source?*/ source/*.tar-* 2>&- | grep -vx source-${VER}/) ]]; then
+    msg "Cleaning up old backups.."
+    # 1) Check the new location first
+    # 2) Remove any duplicated/old ones
+    # 3) Print full paths
+    # 4) Sed: leave out the first result containing ${VER}
+    for i in $(readlink -e source?*/ | sed "0,/${VER}/{//d}"); do
+        msg2 "Removing ${i}"
+        rm -r "${i}"
+    done
+    # If we already have a backup in the new location, remove any from the old one
+    if [ -d source-${VER}*/ ]; then
+        for i in $(readlink -e source/*.tar-*); do
+            msg2 "Removing ${i}"
+            rm -r "${i}"
+        done
+        # Rename it as we like (or as I do)
+        if [ -d source-${VER}?*/ ]; then
+            msg3 "Renaming $(readlink -f source-${VER}*)/ to $(readlink -f source-${VER})/"
+            mv source-${VER}*/ source-${VER}/
+        fi
+    else
+        # Remove any duplicated/old backups
+        for i in vmblock vmci vmmon vmnet vsock; do
+            for j in $(readlink -e source/${i}.tar-* | sed "0,/${VER}/{//d}"); do
+                msg2 "Removing ${j}"
+                rm -r "${j}"
+            done
+        done
+        # Convert leftovers
+        if [ -f source/vmblock.tar-* ]; then
+            # Shorten the msg3 command
+            _old=$(readlink -f source/vmblock.tar-* | sed 's/vmblock/*/')
+            msg3 "Converting backup: ${_old} -> $(readlink -f source-${VER})/"
+            mkdir source-${VER}/
+            for i in vmblock vmci vmmon vmnet vsock; do
+                mv source/${i}.tar-* source-${VER}/${i}.tar
+            done
+        fi
+    fi
+fi
 
-done
+# Revert
+cd /usr/lib/vmware/modules/
+if [ -d source-${VER} ]; then
+    msg "Reverting ${NAME} v${VER} module sources.."
+    msg2 "Removing $(readlink -f source)/"
+    rm -r source/
+    msg3 "Renaming backup: $(readlink -f source-${VER})/ -> $(readlink -f source)/"
+    mv source-${VER}/ source/
+    msg "Done."
+else  # Nothing found
+    msg "No backups found."
+fi
