updated on Sat May  2 00:02:17 UTC 2015

diff --git a/qira-git/PKGBUILD b/qira-git/PKGBUILD
--- a/qira-git/PKGBUILD
+++ b/qira-git/PKGBUILD
@@ -16,7 +16,8 @@
 #   3. We do build specific versions of QEMU for QIRA though. Therefore, the
 #      created package is quite large (~400+ MB). This does NOT violate the
 #      Arch packaging standard because we are not replacing an already
-#      installed QEMU (only QIRA use QEMU we are compiling and including).
+#      installed QEMU (only QIRA uses the QEMU version that we are compiling
+#      and including).
 
 # TODOs:
 #   1. Verify that dependencies are exhaustive and minimal.
@@ -24,9 +25,9 @@
 
 pkgname=qira-git
 pkgver=r1000.3313476
-pkgrel=1
+pkgrel=3
 pkgdesc='QEMU Interactive Runtime Analyser'
-url='https://qira.me/'
+url='http://qira.me/'
 arch=('x86_64' 'i686')
 license=('GPL2')
 source=("qira-git::git+http://github.com/BinaryAnalysisPlatform/qira.git#branch=master")
@@ -60,18 +61,34 @@ package() {
   # which is why we are excluding most default directories (some might be
   # missing).
   export FAKECHROOT_BASE=${pkgdir}
-  export FAKECHROOT_EXCLUDE_PATH=/bin:/usr:/tmp:/proc:/dev:/var:/home:/etc:${srcdir}
+  export FAKECHROOT_EXCLUDE_PATH=/bin:/usr:/proc:/dev:/var:/home:/etc:${srcdir}
+
+  # Capstone workaround
+  ABSBUILDDIR=${BUILDDIR}
+  unset BUILDDIR
 
   # Besides the virtualenv, we also have to build QIRA's QEMU in our
   # fakechroot because it needs Python 2.7 at compile time.
+  #
+  # yaourt behaves a bit weirdly when using fakechroot, which results in
+  # QEMU's configure not running properly (as /bin/sh does not behaves
+  # unexpected) and it generates out-of-tree/in-tree compilation error
+  # messages on make. Replacing /bin/sh with /bin/bash fixes this.
   fakechroot \
     bash -c "virtualenv-2.7 \"/opt/${pkgname}/venv\"
              source \"/opt/${pkgname}/venv/bin/activate\"
+
              cd ${srcdir}/${pkgname}
              pip2 install -U -I -r requirements.txt
 
+             export BUILDDIR=${ABSBUILDDIR}
              cd tracers/
+             ./qemu_build.sh || true
+             sed -i '1c\#!/bin/bash' qemu/qemu-latest/configure
              ./qemu_build.sh"
+
+  # Capstone workaround
+  export BUILDDIR=${ABSBUILDDIR}
 
   # No more fakechroot magic from here on out :)
   cd $srcdir/$pkgname
