updated on Thu Jul 21 18:31:01 UTC 2011

diff --git a/spacechem/PKGBUILD b/spacechem/PKGBUILD
--- a/spacechem/PKGBUILD
+++ b/spacechem/PKGBUILD
@@ -1,43 +1,61 @@
-# Contributor: Alex Griffin <griffin.aj@gmail.com>
+# Maintainer: Wido <widomaker2k7 at gmail dot com>
+
 pkgname=spacechem
-_realname=SpaceChem
-pkgver=1006
+pkgver=1007
 pkgrel=1
-pkgdesc="SpaceChem is an obscenely addictive, design-based puzzle game about machine building and fake science."
+pkgdesc="an obscenely addictive, design-based puzzle game about building machines and fighting monsters in the name of science!"
+url="http://www.gameolith.com/game/spacechem/"
+license=('custom: "commercial"')
 arch=('i686' 'x86_64')
-url="http://www.spacechemthegame.com/"
-license=('custom')
+makedepends=()
+options=(!strip)
+source=("${pkgname}.sh" "${pkgname}.desktop")
+md5sums=('dff2d4a980e324c46198fb9193a23099'
+         'b458899c445a8baa8238b9594ebee6c1')
+
+_gamepkg="${pkgname}_${pkgver}_i386.tar.gz"
 depends=('mono' 'sdl' 'sdl_image' 'sdl_mixer' 'xclip')
-install=spacechem.install
 
 build() {
-  cd "$srcdir"
-  if [ ! -f "../$_realname-$pkgver.tar.gz" ]; then
-    echo SpaceChem is not free, please purchase the game online first,
-    echo place your SpaceChem download in "$startdir" and try again
-    exit 1
-  fi
+   cd ${srcdir}
+   msg "You need a full copy of this game in order to install it"
+   msg "Searching for ${_gamepkg} in dir: \"$startdir\""
+   pkgpath=$startdir
+   if [[ ! -f "$startdir/${_gamepkg}" ]]; then
+       error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
+       read pkgpath
+       if [[ ! -f "${pkgpath}/${_gamepkg}" ]]; then
+           error "Unable to find game package." && return 1
+       fi
+   fi
+    msg "Found game package, installing..."
 
-  tar xzf "../$_realname-$pkgver.tar.gz"
+    ln -fs ${pkgpath}/${_gamepkg} . || return 1
+    tar xvf ${pkgpath}/${_gamepkg} || return 1
 
-  if [ `arch` = x86_64 ]; then
-    ./make-amd64-package.sh
-  fi
+  install -d ${pkgdir}/opt/${pkgname}
+  cp -R ${srcdir}/* ${pkgdir}/opt/${pkgname}/
+  # Clean package
+  rm ${pkgdir}/opt/${pkgname}/${_gamepkg}
+  rm ${pkgdir}/opt/${pkgname}/${pkgname}.desktop
+  rm ${pkgdir}/opt/${pkgname}/${pkgname}.sh
+
 }
 
-package() {
-  cd "$srcdir"
+package(){
+  cd ${srcdir}
 
-  if [ `arch` = x86_64 ]; then
-    ar x SpaceChem-amd64.deb
-  else
-    ar x SpaceChem-i386.deb
-  fi
+  # Install Launcher
+  install -Dm 755 ${srcdir}/${pkgname}.sh ${pkgdir}/usr/bin/${pkgname}
 
-  cd "$pkgdir"
-  tar xzf "$srcdir/data.tar.gz"
-  mkdir -p usr/share/licenses/spacechem
-  mv opt/zachtronicsindustries/spacechem/readme/* usr/share/licenses/spacechem/
-  rmdir opt/zachtronicsindustries/spacechem/readme
+  # Install Desktop
+  install -D -m644 ${srcdir}/${pkgname}.desktop \
+        ${pkgdir}/usr/share/applications/${pkgname}.desktop
+
+  # Install license
+  install -D -m644 ${srcdir}/readme/LICENSE.txt ${pkgdir}/usr/share/licenses/spacechemchem/license
+
+  # Make save game Directory with user group permissions (config)
+  #install -d -m775 -g users ${pkgdir}/opt/${_pkgname}/Art/Save/
+  #install -m644 -g users ${srcdir}/BEEP/Art/Settings.xml ${pkgdir}/opt/${_pkgname}/Art/
 }
-
