updated on Wed Oct  5 20:30:53 UTC 2011

diff --git a/spacechem/PKGBUILD b/spacechem/PKGBUILD
--- a/spacechem/PKGBUILD
+++ b/spacechem/PKGBUILD
@@ -1,8 +1,16 @@
-# Maintainer: Wido <widomaker2k7 at gmail dot com>
+# Maintainer: Wido <widowild at myopera dot com>
+
+# a PKGBUILD is now compatible with:
+
+# Official Store http://store.zachtronicsindustries.com/product/spacechem
+# Store Gameolith http://www.gameolith.com/game/spacechem/
+# The Humble Idie Bundle http://www.humblebundle.com/
 
 pkgname=spacechem
+_pkgname=SpaceChem
 pkgver=1011
-pkgrel=1
+_pkgver=1012 # Just for HIB
+pkgrel=2
 pkgdesc="an obscenely addictive, design-based puzzle game about building machines and fighting monsters in the name of science!"
 url="http://www.gameolith.com/game/spacechem/"
 license=('custom: "commercial"')
@@ -12,10 +20,15 @@ options=(!strip)
 source=("${pkgname}.sh" "${pkgname}.desktop")
 md5sums=('dff2d4a980e324c46198fb9193a23099'
          'b458899c445a8baa8238b9594ebee6c1')
+
 if [[ $CARCH == x86_64 ]]; then
    _gamepkg="${pkgname}_${pkgver}_amd64.tar.gz"
+   _gamepkg2="${_pkgname}-${pkgver}.tar.gz"
+   _gamepkg3="${_pkgname}-${_pkgver}-hib.tar.gz"
 else
    _gamepkg="${pkgname}_${pkgver}_i386.tar.gz"
+   _gamepkg2="${_pkgname}-${pkgver}.tar.gz"
+   _gamepkg3="${_pkgname}-${_pkgver}-hib.tar.gz"
 fi
 
 depends=('mono' 'sdl' 'sdl_image' 'sdl_mixer' 'xclip')
@@ -23,27 +36,55 @@ depends=('mono' 'sdl' 'sdl_image' 'sdl_mixer' 'xclip')
 build() {
    cd ${srcdir}
    msg "You need a full copy of this game in order to install it"
-   msg "Searching for ${_gamepkg} in dir: \"$startdir\""
+   msg "Searching for ${_gamepkg} or ${_gamepkg2} or ${_gamepkg3} in dir: \"$startdir\""
    pkgpath=$startdir
-   if [[ ! -f "$startdir/${_gamepkg}" ]]; then
-       error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
+   if [[ ! -f "$startdir/${_gamepkg}" ]] && [[ ! -f "$startdir/${_gamepkg2}" ]] && [[ ! -f "$startdir/${_gamepkg3}" ]]; then
+       error "Game package not found, please type absolute path to ${_gamepkg} or ${_gamepkg2} or ${_gamepkg3} (/home/joe):"
        read pkgpath
-       if [[ ! -f "${pkgpath}/${_gamepkg}" ]]; then
+       if [[ ! -f "${pkgpath}/${_gamepkg}" ]] && [[ ! -f "$startdir/${_gamepkg2}" ]] && [[ ! -f "$startdir/${_gamepkg3}" ]] ; then
            error "Unable to find game package." && return 1
        fi
    fi
     msg "Found game package, installing..."
 
-    ln -fs ${pkgpath}/${_gamepkg} . || return 1
-    tar xvf ${pkgpath}/${_gamepkg} || return 1
+    ## Store Gameolith
 
-  install -d ${pkgdir}/opt/${pkgname}
-  cp -R ${srcdir}/* ${pkgdir}/opt/${pkgname}/
-  # Clean package
-  rm ${pkgdir}/opt/${pkgname}/${_gamepkg}
-  rm ${pkgdir}/opt/${pkgname}/${pkgname}.desktop
-  rm ${pkgdir}/opt/${pkgname}/${pkgname}.sh
+    if [[ -f ${pkgpath}/${_gamepkg} ]] ; then
+        ln -fs ${pkgpath}/${_gamepkg} . || return 1
+        tar xvf ${pkgpath}/${_gamepkg} || return 1
+        install -d ${pkgdir}/opt/${pkgname}
+        cp -R ${srcdir}/* ${pkgdir}/opt/${pkgname}/
 
+        # Clean package
+        rm ${pkgdir}/opt/${pkgname}/${_gamepkg}
+        rm ${pkgdir}/opt/${pkgname}/${pkgname}.desktop
+        rm ${pkgdir}/opt/${pkgname}/${pkgname}.sh
+
+    fi
+
+    ## Official Store
+
+    if [[ -f ${pkgpath}/${_gamepkg2} ]] ; then
+        ln -fs ${pkgpath}/${_gamepkg2} . || return 1
+        tar xvf ${pkgpath}/${_gamepkg2} || return 1
+        ar x ${srcdir}/${_pkgname}-i386.deb
+        tar -zxf ${srcdir}/data.tar.gz
+        rm -R ${srcdir}/usr
+        install -d ${pkgdir}/opt/${pkgname}
+        cp -R ${srcdir}/opt/zachtronicsindustries/${pkgname}/* ${pkgdir}/opt/${pkgname}/
+    fi
+
+    ## Humble Indie Bundle
+
+    if [[ -f ${pkgpath}/${_gamepkg3} ]] ; then
+        ln -fs ${pkgpath}/${_gamepkg3} . || return 1
+        tar xvf ${pkgpath}/${_gamepkg3} || return 1
+        ar x ${srcdir}/${_pkgname}-i386.deb
+        tar -zxf ${srcdir}/data.tar.gz
+        rm -R ${srcdir}/usr
+        install -d ${pkgdir}/opt/${pkgname}
+        cp -R ${srcdir}/opt/zachtronicsindustries/${pkgname}/* ${pkgdir}/opt/${pkgname}/
+    fi
 }
 
 package(){
@@ -57,9 +98,5 @@ package(){
         ${pkgdir}/usr/share/applications/${pkgname}.desktop
 
   # Install license
-  install -D -m644 ${srcdir}/readme/LICENSE.txt ${pkgdir}/usr/share/licenses/spacechemchem/license
-
-  # Make save game Directory with user group permissions (config)
-  #install -d -m775 -g users ${pkgdir}/opt/${_pkgname}/Art/Save/
-  #install -m644 -g users ${srcdir}/BEEP/Art/Settings.xml ${pkgdir}/opt/${_pkgname}/Art/
+  install -Dm 644 ${pkgdir}/opt/${pkgname}/readme/LICENSE.txt ${pkgdir}/usr/share/licenses/${pkgname}/license
 }
