updated on Sat May 28 06:30:56 UTC 2011

diff --git a/psi-plus/PKGBUILD b/psi-plus/PKGBUILD
--- a/psi-plus/PKGBUILD
+++ b/psi-plus/PKGBUILD
@@ -2,34 +2,27 @@
 
 pkgname="psi-plus"
 pkgver=0.15
-pkgrel=20
+pkgrel=21
 pkgdesc="Psi+ is a powerful Jabber client (Qt, C++) designed for the Jabber power users"
 url="http://psi-plus.com"
 license=('GPL2')
 arch=('i686' 'x86_64')
 depends=('qt' 'qca' 'qca-ossl' 'qca-gnupg' 'aspell' 'libxss' 'openssl' 'dbus' 'zlib')
 makedepends=('subversion' 'git' 'patch' 'qconf')
-conflicts=('psi' 'psi-svn' 'psi-git' 'psi-plus-svn')
-provides=('psi+' 'psi-plus-svn' 'psi')
+provides=('psi')
 # Plugins list. Includes certain plugins
 # * - include all plugins
-# Available plugins: attentionplugin, autoreplyplugin, birthdayreminderplugin, captchaformsplugin,
-#                    chessplugin, cleanerplugin, clientswitcherplugin, conferenceloggerplugin,
-#                    contentdownloaderplugin, extendedmenuplugin, extendedoptionsplugin, gmailserviceplugin,
-#                    gomokugameplugin, historykeeperplugin, icqdieplugin, imageplugin,
-#                    jabberdiskplugin, juickplugin, pepchangenotifyplugin, pstoplugin, qipxstatusesplugin,
-#                    screenshotplugin, skinsplugin, stopspamplugin, storagenotesplugin,
-#                    translateplugin, videostatusplugin, watcherplugin
+# Available plugins: http://psi-dev.googlecode.com/svn/trunk/plugins/generic
 # Example: plugins_list="imageplugin translateplugin"
 # includes only imageplugin and translateplugin to package
 plugins_list="*"
 # Use WebKit (http://psi-plus.com/wiki/doku.php/webkit)
-# CAUTION: webkit is EXPERIMENTAL feature! Use it at your own risk!
 # values: (0|1)
 usewebkit=0
  
 build() {
         
+  #pkgrel="archlinux"
   cd $srcdir
   
   PSI_DIR=$srcdir
@@ -103,8 +96,26 @@ build() {
   #check_env
   prepare_workspace
   fetch_all
+
+  echo "downloading russian langpack.."
+  if [ -d $srcdir/psi-ru ]
+  then
+    [ $WORK_OFFLINE = 0 ] && { $SVN_UP $srcdir/psi-ru || die "langpack update failed"; }
+  else
+    $SVN_FETCH "http://psi-ru.googlecode.com/svn/branches/psi-plus/" $srcdir/psi-ru \
+    || die "langpack checkout failed"
+  fi
+  
   prepare_all
+  
+  revision=$rev
+  [ $usewebkit -eq "1" ] && revision="${revision}webkit"
+  sleep 0;pkgver="$pkgver.$revision"
+  
   compile_all
   install_all
+  
+  install -D -m 644 $srcdir/psi-ru/*.qm $pkgdir/usr/share/psi-plus/
+  install -D -m 644 $srcdir/psi-ru/qt/*.qm $pkgdir/usr/share/psi-plus/
 
 }
