updated on Thu Oct 11 22:10:37 UTC 2012

diff --git a/psi-plus/PKGBUILD b/psi-plus/PKGBUILD
--- a/psi-plus/PKGBUILD
+++ b/psi-plus/PKGBUILD
@@ -3,22 +3,21 @@
 #TODO: cleanup depends
 
 pkgname="psi-plus"
-pkgver=0.15.latest
-pkgrel=31
+pkgver=0.16.latest
+pkgrel=1
 pkgdesc="Psi+ is a powerful Jabber client (Qt, C++) designed for the Jabber power users"
 url="http://psi-plus.com"
 license=('GPL2')
 arch=('i686' 'x86_64')
 depends=('qt' 'qca-ossl' 'qca-gnupg' 'aspell' 'libxss' 'openssl' 'dbus' 'zlib')
 makedepends=('wget' 'git' 'patch' 'qconf')
-# Plugins list. Includes certain plugins
-# * - include all plugins
-# Available plugins: http://psi-dev.googlecode.com/svn/trunk/plugins/generic
-# Example: _plugins_list="image translate"
-# includes only imageplugin and translateplugin to package
+# Plugins (space-separated, * - build all plugins)
+# Available plugins: https://github.com/psi-plus/plugins/tree/master/generic
 _plugins_list="*"
-# Use WebKit (http://psi-plus.com/wiki/doku.php/webkit)
-# values: (0|1)
+# Selected translations (space-separated, leave empty to autodetect by $LANG)
+# Available translations: be bg ca cs de en eo es et fi fr hu it ja mk nl pl pt pt_BR ru sk sl sr@latin sv sw uk ur_PK vi zh_CN zh_TW
+_translations=""
+# Use WebKit
 _usewebkit=1
  
 build() {
@@ -27,6 +26,7 @@ build() {
   sleep 0;pkgrel=1
   cd $srcdir
   
+  #Do not modify these variables!
   PSI_DIR=$srcdir
   SYSLIBDIRNAME="lib"
   ICONSETS="system clients activities moods affiliations roster"
@@ -36,15 +36,14 @@ build() {
   CONF_OPTS=""
   [ $_usewebkit -eq "1" ] && CONF_OPTS="${CONF_OPTS} --enable-webkit"
   INSTALL_ROOT=$pkgdir 
+  QCONFDIR="/usr/bin"
   PLUGINS=$_plugins_list
-  TRANSLATIONS="ru"
+  TRANSLATIONS=$_translations
   
-  # checkout libpsibuild
   die() { error "$@"; exit 1; }
-  if [ ! -f ./libpsibuild.sh -o "$WORK_OFFLINE" = 0 ]; then
-    [ -f libpsibuild.sh ] && { rm libpsibuild.sh || die "Delete error"; }
-    wget --no-check-certificate "https://raw.github.com/psi-plus/maintenance/master/scripts/posix/libpsibuild.sh" || die "Failed to update libpsibuild";
-  fi
+  [ -f libpsibuild.sh ] && { rm libpsibuild.sh || die "Delete error"; }
+  # checkout libpsibuild
+  wget --no-check-certificate "https://raw.github.com/psi-plus/maintenance/master/scripts/posix/libpsibuild.sh" || die "Failed to update libpsibuild";
   
   . ./libpsibuild.sh
    
@@ -56,6 +55,8 @@ build() {
   prepare_workspace || true
   fetch_all || true
   prepare_all || true
+  
+  sed "s/yyyyMMdd/yyyy-MM-dd/" -i ${PSI_DIR}/build/qcm/conf.qcm
   
   revision=$rev
   [ $_usewebkit -eq "1" ] && revision="${revision}webkit"
