updated on Thu Jun 30 08:00:59 UTC 2011

diff --git a/psi-plus/PKGBUILD b/psi-plus/PKGBUILD
--- a/psi-plus/PKGBUILD
+++ b/psi-plus/PKGBUILD
@@ -4,14 +4,13 @@
 
 pkgname="psi-plus"
 pkgver=0.15
-pkgrel=28
+pkgrel=29
 pkgdesc="Psi+ is a powerful Jabber client (Qt, C++) designed for the Jabber power users"
 url="http://psi-plus.com"
 license=('GPL2')
 arch=('i686' 'x86_64')
 depends=('qt' 'qca-ossl' 'qca-gnupg' 'aspell' 'libxss' 'openssl' 'dbus' 'zlib')
-makedepends=('subversion' 'git' 'patch' 'qconf')
-provides=('psi')
+makedepends=('wget' 'git' 'patch' 'qconf')
 # Plugins list. Includes certain plugins
 # * - include all plugins
 # Available plugins: http://psi-dev.googlecode.com/svn/trunk/plugins/generic
@@ -41,27 +40,19 @@ build() {
   TRANSLATIONS="ru"
   
   # checkout libpsibuild
-  msg "Checking for a new version of libpsibuild.sh..."
-  scripts_repo="http://psi-dev.googlecode.com/svn/trunk/scripts/posix"
-  librevraw=`svn ls -v ${scripts_repo}/libpsibuild.sh`
-  librev=`echo $librevraw | cut -f 1 -d ' '`
-  [ ! -f libpsibuild_r${librev}.sh ] && {
-    msg "Updating libpsibuild..."
-    find . -name libpsibuild_r*.sh -delete 2>/dev/null
-    svn cat ${scripts_repo}/libpsibuild.sh > libpsibuild_r${librev}.sh
-    [ ! -f libpsibuild_r${librev}.sh ] && {
-      msg "can't update libpsibuild.sh"
-      exit 1
-    }
-  }
+  die() { error "$@"; exit 1; }
+  if [ ! -f ./libpsibuild.sh -o "$WORK_OFFLINE" = 0 ]; then
+    [ -f libpsibuild.sh ] && { rm libpsibuild.sh || die "Delete error"; }
+    wget --no-check-certificate "https://raw.github.com/psi-plus/maintenance/master/scripts/posix/libpsibuild.sh" || die "Failed to update libpsibuild";
+  fi
   
-  . ./libpsibuild_r${librev}.sh
+  . ./libpsibuild.sh
    
   #############
   # Go Go Go! #
   #############
   
-  check_env || true
+  check_env $CONF_OPTS || true
   prepare_workspace || true
   fetch_all || true
   prepare_all || true
