updated on Fri Jun  7 18:00:41 UTC 2013

diff --git a/syslinux-efi-git/PKGBUILD b/syslinux-efi-git/PKGBUILD
--- a/syslinux-efi-git/PKGBUILD
+++ b/syslinux-efi-git/PKGBUILD
@@ -2,6 +2,7 @@
 # Contributor: Thomas Bächler <thomas@archlinux.org>
 # Contributor: Tobias Powalowski <tpowa@archlinux.org>
 
+# _gitroot="git://git.zytor.com/syslinux/syslinux.git"
 _gitroot="git://git.kernel.org/pub/scm/boot/syslinux/syslinux.git"
 _gitname="syslinux"
 _gitbranch="firmware"
@@ -10,7 +11,7 @@ __pkgname="syslinux"
 _pkgname="${__pkgname}-efi"
 pkgname="${_pkgname}-git"
 
-pkgver=6.00.pre4
+pkgver=6.00.pre5.6.g3d3f765
 pkgrel=1
 arch=('any')
 pkgdesc="SYSLINUX built for x86_64 and i386 UEFI firmwares - GIT (Alpha) Version"
@@ -57,6 +58,9 @@ build() {
 	unset LDFLAGS
 	unset MAKEFLAGS
 	
+	## Fix -Werror compile fail
+	sed 's|-Wall|-Wall -Wno-error|g' -i "${srcdir}/${_gitname}_build/mk"/*.mk || true
+	
 	rm -rf "${srcdir}/${_gitname}_build/BUILD/" || true
 	mkdir -p "${srcdir}/${_gitname}_build/BUILD/"
 	
@@ -78,11 +82,15 @@ package() {
 	
 	cd "${srcdir}/${_gitname}_build/"
 	
-	make O="${srcdir}/${_gitname}_build/BUILD" INSTALLROOT="${pkgdir}/" AUXDIR="/usr/lib/syslinux" efi64 install
+	make O="${srcdir}/${_gitname}_build/BUILD" INSTALLROOT="${pkgdir}/" AUXDIR="/usr/lib/syslinux" efi64 install || true
 	echo
 	
-	make O="${srcdir}/${_gitname}_build/BUILD" INSTALLROOT="${pkgdir}/" AUXDIR="/usr/lib/syslinux" efi32 install
+	install -D -m0644 "${srcdir}/${_gitname}_build/BUILD/efi64/com32/elflink/ldlinux/ldlinux.e64" "${pkgdir}/usr/lib/syslinux/efi64/ldlinux.e64" || true
+	
+	make O="${srcdir}/${_gitname}_build/BUILD" INSTALLROOT="${pkgdir}/" AUXDIR="/usr/lib/syslinux" efi32 install || true
 	echo
+	
+	install -D -m0644 "${srcdir}/${_gitname}_build/BUILD/efi32/com32/elflink/ldlinux/ldlinux.e32" "${pkgdir}/usr/lib/syslinux/efi32/ldlinux.e32" || true
 	
 	install -d "${pkgdir}/usr/lib/syslinux/config"
 	install -D -m0644 "${srcdir}/syslinux.cfg" "${pkgdir}/usr/lib/syslinux/config/syslinux.cfg"
