updated on Wed Dec 11 00:23:28 UTC 2013

diff --git a/deepin-screenshot/PKGBUILD b/deepin-screenshot/PKGBUILD
--- a/deepin-screenshot/PKGBUILD
+++ b/deepin-screenshot/PKGBUILD
@@ -1,15 +1,19 @@
-# Maintainer: 4679kun <admin[AT]4679.us>
+# Maintainer: Xu Fasheng <fasheng.xu@gmail.com>
 
 pkgname=deepin-screenshot
-pkgver=git20130912150412~7680f08c57
-pkgrel=1
+pkgver=git20131108165119~32e91fb
+pkgrel=2.0
 pkgdesc="Provide a quite easy-to-use screenshot tool. Features:Global hotkey to triggle screenshot tool,Take screenshot of a selected area,Easy to add text and line drawings onto the screenshot"
-depends=('python2' 'gconf' 'python2-xlib' 'deepin-ui' 'python2-wnck' 'python2-xdg' 'python2-scipy')
+depends=('python2' 'gconf' 'python2-xlib' 'deepin-ui' 'python2-wnck' 'python2-xdg' 'python2-scipy' 'python2-pycurl')
 arch=('any')
 url="http://www.linuxdeepin.com/"
 license=('GPL-3')
-source=("http://packages.linuxdeepin.com/deepin/pool/main/d/deepin-screenshot/deepin-screenshot_2.0+${pkgver}_all.deb")
-md5sums=('c21a340049cf2240d06168ca3da6ab77')
+_pkgsite="http://packages.linuxdeepin.com"
+# _pkgsite="http://mirrors.ustc.edu.cn"
+_parent_url="${_pkgsite}/deepin/pool/main/d/deepin-screenshot"
+_file="deepin-screenshot_${pkgrel}+${pkgver}_all.deb"
+_file_reg="deepin-screenshot_+.*?_all.deb"
+md5sums=('0b2129d842aa480935cde22623170f8d')
 
 package() {
     tar xzvf ${srcdir}/data.tar.gz -C ${pkgdir}/
@@ -19,4 +23,40 @@ package() {
     sed -i 's_#! /usr/bin/python$_#! /usr/bin/python2_' *.py  
 }
 
+# Get latest file in source site.
+# arguments:
+#   $1, the parent path of url
+#   $2, desired file name
+#   $3, regexp of file name, used to get the last file name
+get_latest_file() {
+    # get arguments
+    local parent_url=$1
+    local file=$2
+    local file_reg=$3
+    
+    # check if w3m installed
+    command -v w3m >/dev/null 2>&1 || {
+        echo ${file}
+        return
+    }
+    
+    # get the latest file, and for some source site, need convert character "%2b" to "+"
+    matched_files=`w3m -dump_source ${parent_url} | sed "s/%2b/+/" | grep -o -P ${file_reg}`
+    latest_file=`echo "${matched_files}" | sort -n | tail -1`
+    if [[ -z ${latest_file} ]]; then
+        # get latest file failed
+        echo ${file}
+        return
+    fi
+    
+    # return the latest file
+    echo ${latest_file}
+}
 
+# fix url, and then set 'source' variable
+echo "==> Check and fix package url if out of date."
+_file="`get_latest_file ${_parent_url} ${_file} ${_file_reg}`"
+echo "==> Lastest package name is: ${_file}"
+echo "==> For yaourt user, if following steps failed, please run 'makepkg -is --skipchecksums' manually in directory '/tmp/yaourt-tmp-fsh/aur-${pkgname}'."
+
+source=("${_parent_url}/${_file}")
