updated on Fri Jun 24 19:00:58 UTC 2011

diff --git a/virtualbox_bin_beta/PKGBUILD b/virtualbox_bin_beta/PKGBUILD
--- a/virtualbox_bin_beta/PKGBUILD
+++ b/virtualbox_bin_beta/PKGBUILD
@@ -1,101 +1,161 @@
-# Maintainer: The Ringmaster <theringmaster AT archlinux.us>
-# Contributor: Christian Berendt <berendt@b1-systems.de>
 # Contributor: Det <nimetonmaili at gmail a-dot com>
+# Contributor: The Ringmaster <theringmaster AT archlinux.us>
+# Contributor: Christian Berendt <berendt@b1-systems.de>
 # Contributor: Balwinder S "bsd" Dheeman <bdheeman AT gmail.com>
 # Contributor: thotypous <matiasÎ˜archlinux-brÂ·org>
-# Based on virtualbox_bin
-pkgname=virtualbox_bin_beta
-pkgver=4.0.4
-_build=70112
-pkgrel=2
-pkgdesc="Powerful x86 virtualization (Bleeding Edge Packages, Personal Use Binaries Edition)"
+# Based on virtualbox_bin and virtualbox-ext-oracle
+
+pkgbase=virtualbox_bin_beta
+pkgname=${pkgbase}
+true && pkgname=('virtualbox_bin_beta' 'virtualbox-ext-oracle-beta')
+pkgver=4.0.8
+_build=71778
+pkgrel=1
 arch=('i686' 'x86_64')
-url="http://virtualbox.org"
+url='http://virtualbox.org'
 license=('GPL2' 'custom:PUEL')
-depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'gcc' 'make' 'kernel26-headers' 'python2')
-optdepends=('virtualbox-ext-oracle: for Oracle extensions'
-	    'qt: for GUI support'
-            'sdl: for VBoxSDL and GUI support'
-            'mesa: for OpenGL support'
-            'libgl: for shared OpenGL support'
-            'libxt: for shared clipboard support'
-            'alsa-lib: for ALSA support'
-            'pulseaudio: for PulseAudio support')
-provides=("virtualbox=${pkgver}")
-conflicts=('virtualbox-ose' 'virtualbox-modules' 'virtualbox')
-backup=('etc/vbox/vbox.cfg')
-install=virtualbox_bin_beta.install
+options=('!strip')
 _arch='x86'
 [ "${CARCH}" = 'x86_64' ] && _arch='amd64'
 source=(http://download.virtualbox.org/virtualbox/${pkgver}/VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run
+        http://download.virtualbox.org/virtualbox/$pkgver/Oracle_VM_VirtualBox_Extension_Pack-$pkgver-$_build.vbox-extpack
         '10-vboxdrv.rules'
-        'vboxdrv'
-        'virtualbox_bin_beta.install')
+        'vboxdrv.rc'
+        'vboxdrv.conf'
+        'vboxweb.rc'
+        'vboxweb.conf'
+        'PUEL')
 md5sums=(`wget ${source/V*}MD5SUMS -qO - | grep ${_arch}.run | cut -d " " -f1`
-         '98859bfca9ef2ebf2ea43eb9123316fc'
-         '8b3b5fb34d5e8594ee873d7947f3d09b'
-         'b13acda239cded9e6d4e72bc15902f23')
+         `wget ${source[1]/O*}MD5SUMS -qO - | grep VM | cut -d " " -f1`
+         'fe60f9510502bea67383d9198ae8c13c'
+         'c162cfc3683bb8e6970cf08a88b1e4a3'
+         '2d5a0c5275bf660da9f30f75820b6078'
+         'c159d683ba1947290fc2ad2c64194150'
+         '3ac185709bfe688bb753c46e170d0546'
+         '08b28b82d0ebd6962025100d4b5414a1')
 
-package() {
+package_virtualbox_bin_beta() {
+  pkgdesc="Powerful x86 virtualization (Bleeding Edge Packages, Personal Use Binaries Edition + Extension Pack)"
+  depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'kernel26-headers' 'python2')
+  optdepends=('virtualbox-ext-oracle-beta: for Oracle extensions'
+              'qt: for GUI support'
+              'sdl: for VBoxSDL and GUI support'
+              'mesa: for OpenGL support'
+              'libgl: for shared OpenGL support'
+              'libxt: for shared clipboard support'
+              'alsa-lib: for ALSA support'
+              'pulseaudio: for PulseAudio support')
+  provides=("virtualbox=${pkgver}")
+  conflicts=('virtualbox' 'virtualbox-modules')
+  backup=('etc/vbox/vbox.cfg' 'etc/conf.d/vboxdrv' 'etc/conf.d/vboxweb')
+  install=${pkgbase}.install
+  _installdir=/opt/VirtualBox
+
   # Unpack the run package via sh(1)
-  echo yes | sh "VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run" --target "${srcdir}" \
-    --nox11 --noexec &> /dev/null
+  echo yes | sh VirtualBox-${pkgver}-${_build}-Linux_${_arch}.run --target . --nox11 --noexec &> /dev/null
 
   # Unpack bundled files
-  install -d "${pkgdir}/opt/VirtualBox"
-  cd "${pkgdir}/opt/VirtualBox"
+  install -d "${pkgdir}/${_installdir}"
+  cd "${pkgdir}/${_installdir}"
   tar -xjf "${srcdir}/VirtualBox.tar.bz2"
-
-  install -d "${pkgdir}/usr/"{bin,share/applications,share/pixmaps}
 
   # Hardened build: Mark binaries suid root, create symlinks for working around
   #                 unsupported $ORIGIN/.. in VBoxC.so and make sure the
   #                 directory is only writable by the user (paranoid).
-  chmod 4511 VirtualBox VBox{SDL,Headless,NetDHCP}
+  chmod 4511 VirtualBox VBox{SDL,Headless,NetDHCP,NetAdpCtl}
   for _lib in VBox{VMM,REM,RT,DDU,XPCOM}.so; do
-    ln -sf "/opt/VirtualBox/${_lib}" "components/${_lib}"
+    ln -sf ${_installdir}/${_lib} components/${_lib}
   done
   chmod go-w .
 
-  # VBoxNetAdpCtl needs to be suid root in any case
-  chmod 4511 VBoxNetAdpCtl
+  # Patch "vboxshell.py" to use Python 2.x instead of Python 3
+  sed -i 's#/usr/bin/python#\02#' "${pkgdir}/${_installdir}/vboxshell.py"
 
-  # Patch "vboxshell.py" to use Python 2.x (instead of Python 3)
-  sed -i 's#/usr/bin/python#\02#' "${pkgdir}/opt/VirtualBox/vboxshell.py"
+  # Update Arch initscripts way of life in VBox.sh
+  sed -i -e 's,sudo /etc/init.d/vboxdrv setup,/etc/rc.d/vboxdrv setup,g' "${pkgdir}/${_installdir}/VBox.sh"
+  sed -i -e 's,sudo /etc/init.d/vboxdrv restart,/etc/rc.d/vboxdrv restart,g' "${pkgdir}/${_installdir}/VBox.sh"
 
-  # Install the SDK
-  cd "${pkgdir}/opt/VirtualBox/sdk/installer"
-  VBOX_INSTALL_PATH="/opt/VirtualBox" python2 vboxapisetup.py install --root "${pkgdir}"
-  rm -Rf build
-  cd "${pkgdir}/opt/VirtualBox"
+  # Install vboxdrv initscript
+  install -D -m 0755 "${srcdir}/vboxdrv.rc" "${pkgdir}/etc/rc.d/vboxdrv"
+  install -D -m 0644 "${srcdir}/vboxdrv.conf" "${pkgdir}/etc/conf.d/vboxdrv"
 
-  # Install rc.d script for module compilation
-  install -Dm0755 "${srcdir}/vboxdrv" "${pkgdir}/etc/rc.d/vboxdrv"
-
-  # Replace init script stuff
-  sed -i -e 's,sudo /etc/init.d/vboxdrv setup,/etc/rc.d/vboxdrv setup,g' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
-  sed -i -e 's,sudo /etc/init.d/vboxdrv restart,modprobe vboxdrv,g' \
-    "${pkgdir}/opt/VirtualBox/VBox.sh"
+  # Install vboxweb initscript
+  install -D -m 0755 "${srcdir}/vboxweb.rc" "${pkgdir}/etc/rc.d/vboxweb"
+  install -D -m 0644 "${srcdir}/vboxweb.conf" "${pkgdir}/etc/conf.d/vboxweb"
 
   # Install udev rules
-  install -Dm0644 "${srcdir}/10-vboxdrv.rules" "${pkgdir}/lib/udev/rules.d/10-vboxdrv.rules"
+  install -D -m 0644 "${srcdir}/10-vboxdrv.rules" "${pkgdir}/lib/udev/rules.d/10-vboxdrv.rules"
+  ln -s "${_installdir}/VBoxCreateUSBNode.sh" "${pkgdir}/lib/udev/VBoxCreateUSBNode.sh"
 
-  # Symlink the launchers
+  # Install the SDK
+  cd sdk/installer
+  VBOX_INSTALL_PATH=${_installdir} python2 vboxapisetup.py install --root "${pkgdir}"
+  rm -r -f build
+  cd -
+
+  # Symlink the launchers. Second link can fail if fs is not case sensitive.
+  install -d -m 0755 "${pkgdir}/usr/bin"
   for _bin in VirtualBox VBox{Headless,Manage,SDL,SVC,Tunctl,NetAdpCtl} rdesktop-vrdp; do
-    ln -s "/opt/VirtualBox/${_bin}" "${pkgdir}/usr/bin/${_bin}"
+    ln -s ${_installdir}/${_bin} "${pkgdir}/usr/bin/${_bin}"
+    ln -s ${_installdir}/${_bin} "${pkgdir}/usr/bin/${_bin,,}" &>/dev/null || :
   done
 
   # Symlink the desktop icon and ".desktop" files
-  ln -s /opt/VirtualBox/VBox.png "${pkgdir}/usr/share/pixmaps/VBox.png"
-  ln -s /opt/VirtualBox/virtualbox.desktop "${pkgdir}/usr/share/applications/VirtualBox.desktop"
+  install -d -m 0755 "${pkgdir}/usr/"{share/applications,share/pixmaps}
+  ln -s ${_installdir}/VBox.png "${pkgdir}/usr/share/pixmaps/VBox.png"
+  ln -s ${_installdir}/icons/128x128/virtualbox.png "${pkgdir}/usr/share/pixmaps/virtualbox.png"
+  ln -s ${_installdir}/virtualbox.desktop "${pkgdir}/usr/share/applications/virtualbox.desktop"
 
-  # Symlink the license
-  install -d "${pkgdir}/usr/share/licenses/${pkgname}"
-  ln -s /opt/VirtualBox/LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/PUEL"
+  # Symlink mime info
+  install -d -m 0755 "${pkgdir}/usr/share/mime/packages"
+  ln -s ${_installdir}/virtualbox.xml "${pkgdir}/usr/share/mime/packages/virtualbox.xml"
 
-  # Setup configuration
-  install -d "${pkgdir}/etc/vbox"
-  echo 'INSTALL_DIR="/opt/VirtualBox"' > "${pkgdir}/etc/vbox/vbox.cfg"
+  # Symlink doc
+  install -d -m 0755 "${pkgdir}/usr/share/doc/${pkgname}"
+  ln -s ${_installdir}/VirtualBox.chm "${pkgdir}/usr/share/doc/$pkgname/virtualbox.chm"
 
+  # Symlink module sources
+  install -d -m 0755 "${pkgdir}/usr/src"
+  ln -s ${_installdir}/src/vboxhost "${pkgdir}/usr/src/vboxhost-${pkgver}"
+
+  # Symlink icons
+  cd "${pkgdir}/${_installdir}/icons"
+  for _dir in *; do
+    cd "${_dir}"
+    install -d -m 0755 "${pkgdir}/usr/share/icons/hicolor/${_dir}/"{apps,mimetypes}
+    for _icon in *; do
+      if [[ "${_icon}" = 'virtualbox.png' ]]; then
+          ln -s ${_installdir}/icons/${_dir}/${_icon} "${pkgdir}/usr/share/icons/hicolor/${_dir}/apps/${_icon}"
+      else
+          ln -s ${_installdir}/icons/${_dir}/${_icon} "${pkgdir}/usr/share/icons/hicolor/${_dir}/mimetypes/${_icon}"
+      fi
+    done
+    cd - >/dev/null
+  done
+
+  # Write the configuration file
+  install -d -m 0755 "${pkgdir}/etc/vbox"
+  echo "# VirtualBox installation directory" > "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_DIR=${_installdir}" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "# VirtualBox version" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_VER='${pkgver}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  echo "INSTALL_REV='${_build}'" >> "${pkgdir}/etc/vbox/vbox.cfg"
+  chmod 0644 "${pkgdir}/etc/vbox/vbox.cfg"
+
+  # Create the directory below if it doesn't exist
+  install -d -m 0755 "${pkgdir}/var/run/VirtualBox"
 }
+
+package_virtualbox-ext-oracle-beta() {
+  pkgdesc="Oracle VM VirtualBox Extension Pack (Bleeding Edge)"
+  arch=('any')
+  depends=("$pkgbase=$pkgver")
+  install=virtualbox-ext-oracle-beta.install
+
+  install -D -m 644 Oracle_VM_VirtualBox_Extension_Pack-$pkgver-$_build.vbox-extpack "$pkgdir/usr/share/virtualbox/extensions/Oracle_VM_VirtualBox_Extension_Pack-$pkgver.vbox-extpack"
+  install -D -m 644 PUEL "$pkgdir/usr/share/licenses/$pkgname/PUEL"
+}
+
+pkgdesc="Powerful x86 virtualization (Bleeding Edge Packages, Personal Use Binaries Edition + Extension Pack)"
+depends=('libidl2' 'libxcursor' 'libxinerama' 'libxslt' 'curl' 'kernel26-headers' 'python2')
+# vim:set ts=2 sw=2 ft=sh et:
