updated on Mon Apr 21 15:14:01 UTC 2014

diff --git a/pelican-themes-git/PKGBUILD b/pelican-themes-git/PKGBUILD
--- a/pelican-themes-git/PKGBUILD
+++ b/pelican-themes-git/PKGBUILD
@@ -1,7 +1,9 @@
 # Maintainer: Aaron Kimmig <aaron.kimmig@student.hpi.uni-potsdam.de>
+# Contributor: gothmog.todi
+
 pkgname=pelican-themes-git
-pkgver=298.f429e0d
 pkgrel=1
+pkgver=448.daceecf
 pkgdesc="A collection of themes for the Pelican static website generator, hosted and updated on GitHub"
 arch=('any')
 url="https://github.com/getpelican/pelican-themes"
@@ -9,30 +11,38 @@ license=('GPL' 'MIT' 'Apache' 'WTFPL')
 depends=('pelican')
 makedepends=('git')
 source=('git+https://github.com/getpelican/pelican-themes.git')
-md5sums=('SKIP')
-sha1sums=('SKIP')
 sha256sums=('SKIP')
-sha384sums=('SKIP')
-sha512sums=('SKIP')
 
 _gitname="pelican-themes"
-_pelican_themes_path="$(pelican-themes -p)"
 
 pkgver() {
   cd ${_gitname}
   echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)
 }
 
+build() {
+  cd ${_gitname}
+  git submodule update --init --recursive
+}
+
 package() {
   cd ${_gitname}
+  
+  # get installation path
+  pelican_themes_path="$(pelican-themes -p)"
+  if [[ $? != 0 ]] ; then
+    echo "pelican-themes -p exited with error code $?"
+    echo "try reinstalling pelican and it's dependencies"
+    exit 1
+  fi
 
   # Create installation directories
-  install -d -m755 "${pkgdir}${_pelican_themes_path}"
+  install -d -m755 "${pkgdir}${pelican_themes_path}"
 
   # get WTFPL license
   curl http://www.wtfpl.net/txt/copying/ > WTFPL
   install -D -m644 WTFPL "${pkgdir}/usr/share/licenses/${pkgname}/WTFPL"
 
   # Install the themes
-  cp -rf * "${pkgdir}${_pelican_themes_path}"
+  cp -rf * "${pkgdir}${pelican_themes_path}"
 } 
