updated on Fri Apr  5 20:01:00 UTC 2013

diff --git a/catalyst-hook/catalyst_build_module b/catalyst-hook/catalyst_build_module
--- a/catalyst-hook/catalyst_build_module
+++ b/catalyst-hook/catalyst_build_module
@@ -172,6 +172,6 @@ case "$1" in
     *)
         test "$1" != "" && kernver="$1"
 	echo "Building fglrx module for ${kernver} kernel ..."
-        install_module >> $LOG 2>&1 && echo "Ok." || echo "Failed!!! Check out log: $LOG"
+        install_module >> $LOG 2>&1 && echo "Ok." || echo -e '\E[37;44m'"\033[1mFailed!!! Check out log: $LOG\033[0m"
         ;;
 esac
