updated on Tue Apr 30 04:01:57 UTC 2013

diff --git a/gcc-x32-seed/PKGBUILD b/gcc-x32-seed/PKGBUILD
--- a/gcc-x32-seed/PKGBUILD
+++ b/gcc-x32-seed/PKGBUILD
@@ -1,66 +1,64 @@
-pkgbase='gcc-x32-seed'
-pkgname=('gcc-x32-seed')
-pkgver=4.7.1
-pkgrel=5
-#_snapshot=4.7-20120505
-_libstdcppmanver=20120605		# Note: check source directory name when updating this
-pkgdesc="An incomplete GCC build for building Glibc with X32 support"
+# Maintainer: Fantix KIng
+# Upstream Maintainer: Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
+# Contributor: Allan McRae <allan@archlinux.org>
+
+# toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
+# NOTE: libtool requires rebuilt with each new gcc version
+
+pkgname='gcc-x32-seed'
+pkgver=4.8.0
+pkgrel=1
+_snapshot=4.8-20130425
+pkgdesc="An incomplete GCC build for building Glibc with x32 ABI support"
 arch=('x86_64')
 license=('GPL' 'LGPL' 'FDL' 'custom')
-url="http://sourceware.org/glibc/wiki/x32"
-makedepends=('binutils-multilib>=2.22' 'libmpc' 'cloog' 'ppl' 'gcc-ada-multilib'
-             'lib32-glibc>=2.16')
-checkdepends=('dejagnu')
+url="http://gcc.gnu.org"
+makedepends=('binutils-multilib>=2.23' 'libmpc' 'cloog' 
+             'lib32-glibc>=2.17')
+checkdepends=('dejagnu' 'inetutils')
+depends=('binutils-multilib>=2.23' 'libmpc' 'cloog' 'glibc-x32-seed')
+groups=('multilib-devel')
+provides=("gcc-multilib-x32=${pkgver}-${pkgrel}")
 options=('!libtool' '!emptydirs')
-source=(
-ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
-	#ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
-	ftp://gcc.gnu.org/pub/gcc/libstdc++/doxygen/libstdc++-api.${_libstdcppmanver}.man.tar.bz2
-	https://sites.google.com/site/x32abi/documents/gcc-x32-seed.tar.bz2
-	gcc_pure64-multilib.patch
-	gcc-4.7.1-libada-pic.patch
-	gcc-4.7.1-libgo-write.patch
-        gcc-4.7.1-libgo-mksysinfo.patch)
-md5sums=('933e6f15f51c031060af64a9e14149ff'
-         '767c62f9a047c4434f2345decf1d0819'
-         '1672d3283e6827b8b8ff634f85ddf523'
-         '55818c34a79ec90913ef7778e17ea6b6'
-         '2acbc9d35cc9d72329dc71d6b1f162ef'
-         'df82dd175ac566c8a6d46b11ac21f14c'
-         '8e847244dba042d0aa3297713edaf70c')
+source=(ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
+	https://sites.google.com/site/x32abi/documents/gcc-x32-seed.tar.bz2)
+        #ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
+md5sums=('03690556f09991fbecac0467227c5d4e'
+         '1672d3283e6827b8b8ff634f85ddf523')
+
 
 if [ -n "${_snapshot}" ]; then
-  _basedir="${srcdir}/gcc-${_snapshot}"
+  _basedir=gcc-${_snapshot}
 else
-  _basedir="${srcdir}/gcc-${pkgver}"
+  _basedir=gcc-${pkgver}
 fi
 
-build() {
-  cd ${_basedir}
-
-  # Do not install libiberty
-  sed -i 's/install_to_$(INSTALL_DEST) //' libiberty/Makefile.in
+prepare() {
+  cd ${srcdir}/${_basedir}
 
   # Do not run fixincludes
   sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in
 
-  patch -p1 -i ${srcdir}/gcc_pure64-multilib.patch
-
-  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=53679
-  patch -p1 -i ${srcdir}/gcc-4.7.1-libgo-write.patch
-  
-  # bug to file...
-  patch -p1 -i ${srcdir}/gcc-4.7.1-libada-pic.patch
-
-  # http://gcc.gnu.org/ml/gcc-patches/2012-06/msg01946.html
-  patch -p0 -i ${srcdir}/gcc-4.7.1-libgo-mksysinfo.patch
+  # Arch Linux installs x86_64 libraries /lib
+  [[ $CARCH == "x86_64" ]] && sed -i '/m64=/s/lib64/lib/' gcc/config/i386/t-linux64
 
   echo ${pkgver} > gcc/BASE-VER
 
-  cd ${srcdir}
-  mkdir gcc-build && cd gcc-build
+  # hack! - some configure tests for header files using "$CPP $CPPFLAGS"
+  sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" {libiberty,gcc}/configure
 
-  ${_basedir}/configure --prefix=/opt/gcc-x32-seed \
+  mkdir ${srcdir}/gcc-build
+}
+
+build() {
+  cd ${srcdir}/gcc-build
+
+  # using -pipe causes spurious test-suite failures
+  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=48565
+  CFLAGS=${CFLAGS/-pipe/}
+  CXXFLAGS=${CXXFLAGS/-pipe/}
+
+  ${srcdir}/${_basedir}/configure --prefix=/opt/gcc-x32-seed \
       --libdir=/opt/gcc-x32-seed/lib --libexecdir=/opt/gcc-x32-seed/lib \
       --mandir=/opt/gcc-x32-seed/share/man --infodir=/opt/gcc-x32-seed/share/info \
       --with-bugurl=https://bugs.archlinux.org/ \
@@ -68,54 +66,49 @@ build() {
       --enable-shared --enable-threads=posix \
       --with-system-zlib --enable-__cxa_atexit \
       --disable-libunwind-exceptions --enable-clocale=gnu \
-      --disable-libstdcxx-pch --enable-libstdcxx-time \
+      --disable-libstdcxx-pch \
       --enable-gnu-unique-object --enable-linker-build-id \
-      --with-ppl --enable-cloog-backend=isl \
-      --disable-ppl-version-check --disable-cloog-version-check \
+      --enable-cloog-backend=isl --disable-cloog-version-check \
       --enable-lto --enable-gold --enable-ld=default \
       --enable-plugin --with-plugin-ld=ld.gold \
-      --with-linker-hash-style=gnu \
+      --with-linker-hash-style=gnu --disable-install-libiberty \
       --enable-multilib --with-multilib-list=m32,m64,mx32 \
-      --disable-libssp \
-      --disable-build-with-cxx --disable-build-poststage1-with-cxx \
+      --disable-libssp --disable-werror \
       --enable-checking=release
-
-  # do not abort on error, because libgcc will fail due to glibc
   make || true
 
   ln -s build-*/fixincludes || true
+  
+  # make documentation
+  #cd $CHOST/libstdc++-v3
+  #make doc-man-doxygen
 }
 
-package_gcc-x32-seed()
+package()
 {
-  groups=('multilib-devel')
-  install=gcc.install
 
-  cd gcc-build
-
+  cd ${srcdir}/gcc-build
+  
   make -j1 DESTDIR=${pkgdir} install || true
 
-  #install -d $pkgdir/opt/gcc-x32-seed/share/gdb/auto-load/opt/gcc-x32-seed/lib
-  #mv $pkgdir{,/opt/gcc-x32-seed/share/gdb/auto-load}/opt/gcc-x32-seed/lib/libstdc++.so.6.0.17-gdb.py
+  #install -d $pkgdir/usr/share/gdb/auto-load/usr/lib
+  #mv $pkgdir{,/usr/share/gdb/auto-load}/usr/lib/libstdc++.so.6.0.18-gdb.py
 
   # unfortunately it is much, much easier to install the lot and clean-up the mess...
   rm $pkgdir/opt/gcc-x32-seed/bin/{{$CHOST-,}gfortran,{$CHOST-,}gccgo,gnat*} || true
   rm $pkgdir/opt/gcc-x32-seed/lib{,32}/*.so* || true
-  rm $pkgdir/opt/gcc-x32-seed/lib{,32}/lib{ffi,gfortran,go{,begin},objc,quadmath}.a || true
+  rm $pkgdir/opt/gcc-x32-seed/lib{,32}/lib{atomic,gfortran,go{,begin},objc}.a || true
+  rm $pkgdir/opt/gcc-x32-seed/lib/libiberty.a || true
   rm $pkgdir/opt/gcc-x32-seed/lib{,32}/libgfortran.spec || true
   rm -r $pkgdir/opt/gcc-x32-seed/lib/gcc/$CHOST/${pkgver}/{{,32/}ada{include,lib},finclude,include/objc} || true
-  rm $pkgdir/opt/gcc-x32-seed/lib/gcc/$CHOST/${pkgver}/include/{ffi{,target}.h,quadmath{,_weak}.h} || true
   rm $pkgdir/opt/gcc-x32-seed/lib/gcc/$CHOST/${pkgver}/{cc1obj{,plus},f951,gnat1,go1} || true
   rm $pkgdir/opt/gcc-x32-seed/lib/gcc/$CHOST/${pkgver}/{,32/}{libcaf_single,libgfortranbegin}.a || true
   rm -r $pkgdir/opt/gcc-x32-seed/lib{,32}/go || true
   rm $pkgdir/opt/gcc-x32-seed/share/info/{gccgo,gfortran,gnat*,libgomp,libquadmath,libitm}.info || true
   rm $pkgdir/opt/gcc-x32-seed/share/locale/{de,fr}/LC_MESSAGES/libstdc++.mo || true
   rm $pkgdir/opt/gcc-x32-seed/share/man/man1/{gccgo,gfortran}.1 || true
-  rm $pkgdir/opt/gcc-x32-seed/share/man/man3/ffi* || true
 
-  # many packages require these symlinks
-  #install -dm755 ${pkgdir}/lib
-  #ln -s /opt/gcc-x32-seed/bin/cpp ${pkgdir}/lib/cpp
+  # many packages expect this symlinks
   ln -s gcc ${pkgdir}/opt/gcc-x32-seed/bin/cc
 
   # POSIX conformance launcher scripts for c89 and c99
@@ -148,13 +141,13 @@ EOF
   chmod 755 $pkgdir/opt/gcc-x32-seed/bin/c{8,9}9
 
   # install the libstdc++ man pages
-  install -dm755 ${pkgdir}/opt/gcc-x32-seed/share/man/man3
-  install -m644 ${srcdir}/libstdc++-api.${_libstdcppmanver}.man/man3/* \
-    ${pkgdir}/opt/gcc-x32-seed/share/man/man3/
+  #install -dm755 ${pkgdir}/usr/share/man/man3
+  #install -m644 -t ${pkgdir}/usr/share/man/man3 \
+  #  ${CHOST}/libstdc++-v3/doc/doxygen/man/man3/*.3
 
   # Install Runtime Library Exception
-  install -Dm644 ${_basedir}/COPYING.RUNTIME \
-    ${pkgdir}/opt/gcc-x32-seed/share/licenses/gcc-multilib/RUNTIME.LIBRARY.EXCEPTION
+  #install -Dm644 ${srcdir}/${_basedir}/COPYING.RUNTIME \
+  #  ${pkgdir}/usr/share/licenses/gcc-multilib/RUNTIME.LIBRARY.EXCEPTION
 
   # Install x32 seed
   install -dm755 ${pkgdir}/opt/gcc-x32-seed/lib/gcc/$CHOST/${pkgver}/x32
