updated on Thu Sep  5 20:00:21 UTC 2013

diff --git a/linpack/PKGBUILD b/linpack/PKGBUILD
--- a/linpack/PKGBUILD
+++ b/linpack/PKGBUILD
@@ -1,49 +1,44 @@
 # Contributor: graysky <graysky AT archlinux dot us>
 pkgname=linpack
 true && pkgname=('linpack' 'linpack-docs')
-pkgver=11.0.3.008
-_pkgvershort=11.0.3
-_stupid_number=3058
-pkgrel=2
+pkgver=11.0.5.009
+_pkgvershort=11.0.5
+_stupid_number=3234
+pkgrel=1
 arch=('i686' 'x86_64')
 license=('custom')
 url="http://software.intel.com/en-us/articles/intel-math-kernel-library-linpack-download"
 source=("http://registrationcenter.intel.com/irc_nas/$_stupid_number/l_lpk_p_$pkgver.tgz"
 'linpack.conf' 'runme.template')
-sha256sums=('18482a8b1292ae0198c776207cabef9029430be0a9b3c5b31d7e3f5fc05383f5'
+sha256sums=('27d10bed7b748c9a365b89659ac7baa855a8ffe40a316ada16322b1ceede16b0'
             'b4744fa33e031eb442bd8c14313d8619e3e3a23608370f7dc9ba91d904dacd74'
             '8c880adeee3de6c0e6005e210cea0e01b471219c590e25e824298a25ab0eef31')
 
-prepare() {
-	if [[ "$CARCH" = "x86_64" ]]; then 
-		bit=64
-	else
-		bit=32
-	fi
-
-	[[ -z $bit ]] && echo "Cannot determine architecture of this system!" && exit 1 # sanity check
+build() {
+	[[ -z "$CARCH" ]] && echo "Cannot determine architecture of this system!" && exit 1
+	[[ "$CARCH" = "x86_64" ]] && bit=64 || bit=32
 	export bit
-
-	eval "sed -e 's/@TARGET_BIT@/$bit/g' <runme.template >linpack_runme_xeon$bit" # setup based on detected arch
 }
 
 package_linpack() {
 	install=readme.install
 	backup=(etc/linpack.conf)
+	_path="linpack_$_pkgvershort/benchmarks/linpack"
 
-	install -Dm755 linpack_runme_xeon$bit "$pkgdir"/usr/bin/linpack_runme_xeon$bit
-	install -Dm644 linpack.conf "$pkgdir"/etc/linpack.conf
-	install -Dm644 linpack_$_pkgvershort/doc/lpkEULA "$pkgdir"/usr/share/licenses/linpack/lpkEULA
-
-	cd "$srcdir"/linpack_$_pkgvershort/benchmarks/linpack
-	install -Dm755 xlinpack_xeon$bit "$pkgdir"/usr/bin/xlinpack_xeon$bit
-	install -Dm644 xhelp.lpk "$pkgdir"/usr/share/doc/${pkgname}/xhelp.lpk
+	# setup based on detected arch
+	sed -e "s/@TARGET_BIT@/$bit/g" <runme.template >linpack_runme_xeon$bit
+	
+	install -Dm755 linpack_runme_xeon$bit "$pkgdir/usr/bin/linpack_runme_xeon$bit"
+	install -Dm644 linpack.conf "$pkgdir/etc/linpack.conf"
+	install -Dm644 linpack_$_pkgvershort/doc/lpkEULA "$pkgdir/usr/share/licenses/linpack/lpkEULA"
+	install -Dm755 "$srcdir/$_path/xlinpack_xeon$bit" "$pkgdir/usr/bin/xlinpack_xeon$bit"
+	install -Dm644 "$srcdir/$_path/xhelp.lpk" "$pkgdir/usr/share/doc/${pkgname}/xhelp.lpk"
 }
 
 package_linpack-docs() {
-cd linpack_"$_pkgvershort"/doc
-install -Dm644 lpksupport.txt "$pkgdir"/usr/share/doc/linpack/lpksupport.txt
-cp -r mkl_userguide "$pkgdir"/usr/share/doc/linpack
+	_docpath="linpack_$_pkgvershort/doc"
+	install -Dm644 "$srcdir/$_docpath/lpksupport.txt" "$pkgdir/usr/share/doc/linpack/lpksupport.txt"
+	cp -r "$srcdir/$_docpath/mkl_userguide" "$pkgdir/usr/share/doc/linpack"
 }
 
 # appears at the end to help the AUR
