updated on Fri Apr 12 20:08:42 UTC 2013

diff --git a/linpack/PKGBUILD b/linpack/PKGBUILD
--- a/linpack/PKGBUILD
+++ b/linpack/PKGBUILD
@@ -1,50 +1,50 @@
 # Contributor: graysky <graysky AT archlinux dot us>
 pkgname=linpack
 true && pkgname=('linpack' 'linpack-docs')
-pkgver=11.0.2.006
-_pkgvershort=11.0.2
-_stupid_number=2967
+pkgver=11.0.3.008
+_pkgvershort=11.0.3
+_stupid_number=3058
 pkgrel=1
 arch=('i686' 'x86_64')
 license=('custom')
 url="http://software.intel.com/en-us/articles/intel-math-kernel-library-linpack-download"
 source=("http://registrationcenter.intel.com/irc_nas/$_stupid_number/l_lpk_p_$pkgver.tgz"
 'linpack.conf' 'runme.template')
-sha256sums=('acbb75552561be4d90fc1f2950e0cdb52d5bfdc4e86aa09930afd9f74685dc75'
+sha256sums=('18482a8b1292ae0198c776207cabef9029430be0a9b3c5b31d7e3f5fc05383f5'
             'b4744fa33e031eb442bd8c14313d8619e3e3a23608370f7dc9ba91d904dacd74'
             '8c880adeee3de6c0e6005e210cea0e01b471219c590e25e824298a25ab0eef31')
 
 build() {
-if [[ "$CARCH" = "x86_64" ]]; then 
-	bit=64
-else
-	bit=32
-fi
+	if [[ "$CARCH" = "x86_64" ]]; then 
+		bit=64
+	else
+		bit=32
+	fi
 
-[[ -z $bit ]] && echo "Cannot determine architecture of this system!" && exit 1 # sanity check
-export bit
+	[[ -z $bit ]] && echo "Cannot determine architecture of this system!" && exit 1 # sanity check
+	export bit
 }
 
 package_linpack() {
-install=readme.install
-backup=(etc/linpack.conf)
+	install=readme.install
+	backup=(etc/linpack.conf)
 
-eval "sed -e 's/@TARGET_BIT@/$bit/g' <runme.template >linpack_runme_xeon$bit" # setup based on detected arch
+	eval "sed -e 's/@TARGET_BIT@/$bit/g' <runme.template >linpack_runme_xeon$bit" # setup based on detected arch
 
-install -Dm755 linpack_runme_xeon$bit "$pkgdir"/usr/bin/linpack_runme_xeon$bit
-install -Dm644 linpack.conf "$pkgdir"/etc/linpack.conf
-install -Dm644 "$srcdir"/linpack_$_pkgvershort/doc/lpkEULA "$pkgdir"/usr/share/licenses/linpack/lpkEULA
+	install -Dm755 linpack_runme_xeon$bit "$pkgdir"/usr/bin/linpack_runme_xeon$bit
+	install -Dm644 linpack.conf "$pkgdir"/etc/linpack.conf
+	install -Dm644 linpack_$_pkgvershort/doc/lpkEULA "$pkgdir"/usr/share/licenses/linpack/lpkEULA
 
-cd "$srcdir"/linpack_$_pkgvershort/benchmarks/linpack
-install -Dm755 xlinpack_xeon$bit "$pkgdir"/usr/bin/xlinpack_xeon$bit
-install -Dm644 xhelp.lpk "$pkgdir"/usr/share/doc/${pkgname}/xhelp.lpk
+	cd "$srcdir"/linpack_$_pkgvershort/benchmarks/linpack
+	install -Dm755 xlinpack_xeon$bit "$pkgdir"/usr/bin/xlinpack_xeon$bit
+	install -Dm644 xhelp.lpk "$pkgdir"/usr/share/doc/${pkgname}/xhelp.lpk
 }
 
 package_linpack-docs() {
 cd linpack_"$_pkgvershort"/doc
-install -Dm644 lpksupport.txt "$pkgdir"/usr/share/docs/linpack/lpksupport.txt
-cp -r mkl_userguide "$pkgdir"/usr/share/docs/linpack
+install -Dm644 lpksupport.txt "$pkgdir"/usr/share/doc/linpack/lpksupport.txt
+cp -r mkl_userguide "$pkgdir"/usr/share/doc/linpack
 }
 
 # appears at the end to help the AUR
-pkgdesc='Benchmark and stability test based on linear algebra. Excellent app for stress testing overclocked systems. Intel CPUs only!'
+pkgdesc='Benchmark and stability test based on linear algebra. Excellent app for stress testing overclocked systems.'
