updated on Sat Jan 28 13:13:48 UTC 2012

diff --git a/linpack/PKGBUILD b/linpack/PKGBUILD
--- a/linpack/PKGBUILD
+++ b/linpack/PKGBUILD
@@ -1,39 +1,44 @@
 # Contributor: graysky <graysky AT archlinux dot us>
 pkgname=linpack
-true && pkgname=(linpack linpack-docs)
+true && pkgname=('linpack' 'linpack-docs')
 pkgver=10.3.7.011
 pkgvershort=10.3.7
-pkgrel=1
+pkgrel=2
 arch=('i686' 'x86_64')
 license=('custom')
 url="http://software.intel.com/en-us/articles/intel-math-kernel-library-linpack-download"
-options=(!strip)
-install=$pkgname.install
-source=(http://registrationcenter-download.intel.com/akdlm/irc_nas/2392/l_lpk_p_$pkgver.tgz linpack.conf runme.template)
+source=("http://registrationcenter-download.intel.com/akdlm/irc_nas/2392/l_lpk_p_$pkgver.tgz"
+'linpack.conf' 'runme.template')
+sha256sums=('7690fa51ea505757faea4b935bc49ae3c75b350d0545ba041967d3373703764d'
+            'b4744fa33e031eb442bd8c14313d8619e3e3a23608370f7dc9ba91d904dacd74'
+            '1323c89b8480a0d2f5401015a384754e155c34d73d5cb0bbd3772bc67c9e97c7')
 
 build() {
-if [ "$CARCH" = "x86_64" ]; then 
+if [[ "$CARCH" = "x86_64" ]]; then 
 	bit=64
 else
 	bit=32
 fi
 
-# sanity check
-[[ -z $bit ]] && echo "Cannot determine architecture of this system!" && exit 
+[[ -z $bit ]] && echo "Cannot determine architecture of this system!" && exit 1 # sanity check
 export bit
 }
 
 package_linpack() {
+install=readme.install
+backup=etc/linpack.conf
+
 cd "$srcdir"
-eval "sed -e 's/TT/$bit/g' <runme.template >linpack_runme_xeon$bit"
+eval "sed -e 's/TT/$bit/g' <runme.template >linpack_runme_xeon$bit" # setup based on detected arch
+
 install -D -m755 linpack_runme_xeon$bit "$pkgdir"/usr/bin/linpack_runme_xeon$bit
 install -D -m644 linpack.conf "$pkgdir"/etc/linpack.conf
-#install -D -m644 lininput.template "$pkgdir"/etc/lininput_xeon$bit
-install -D -m644 "$srcdir"/linpack_$pkgvershort/doc/lpkEULA.txt "$pkgdir"/usr/share/licenses/linpack/lpkEULA.txt
+install -D -m644 "$srcdir"/linpack_$pkgvershort/doc/lpkEULA.txt \
+	"$pkgdir"/usr/share/licenses/linpack/lpkEULA.txt
 
 cd "$srcdir"/linpack_$pkgvershort/benchmarks/linpack
-install -D -m644 xhelp.lpk "$pkgdir"/usr/share/doc/${pkgname}/xhelp.lpk
 install -D -m755 xlinpack_xeon$bit "$pkgdir"/usr/bin/xlinpack_xeon$bit
+install -D -m644 xhelp.lpk "$pkgdir"/usr/share/doc/${pkgname}/xhelp.lpk
 }
 
 package_linpack-docs() {
@@ -42,6 +47,3 @@ install -D -m644 lpksupport.txt "$pkgdir"/usr/share/docs/linpack/lpksupport.txt
 cp -r mkl_userguide "$pkgdir"/usr/share/docs/linpack
 }
 pkgdesc='Benchmark and stability test based on linear algebra. Excellent app for stress testing overclocked systems. Intel CPUs only!'
-sha256sums=('7690fa51ea505757faea4b935bc49ae3c75b350d0545ba041967d3373703764d'
-            '02d1eeab6e55210dca32be5fb5bfaf20f3962145702fc3e1da013b33440fb9e4'
-            'defdf56eac12cd607b3d153584fe935d344a5e4b31a7492d25ac154da513e0c5')
