updated on Fri Feb 25 22:00:47 PST 2011

diff --git a/firefox-pgo-beta/PKGBUILD b/firefox-pgo-beta/PKGBUILD
--- a/firefox-pgo-beta/PKGBUILD
+++ b/firefox-pgo-beta/PKGBUILD
@@ -2,8 +2,8 @@
 # Contributor: blasse <koralik(at)gmail(dot)com>
 
 pkgname=firefox-pgo-beta
-_ffver=4.0b11
-_build=build3
+_ffver=4.0b12
+_build=build1
 pkgver=${_ffver}${_build}
 pkgrel=1
 pkgdesc="Mozilla Firefox customizable web browser (XULRunner independent, PGO optimized, 64-bit TraceMonkey, beta)"
@@ -32,9 +32,8 @@ source=("ftp://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/${_ffver}-candida
         'mozilla-firefox-1.0-lang.patch'
         'ldflags-namespec.patch'
         'jemalloc-enable-pgo.patch'
-        'potential-pgo-fix.patch'
-	'beta-10-cairo.patch')
-sha256sums=('88b6e24123dbacf9edf49617627801aa2149331cf61459701376d3640dd3ba46'
+	'potential-pgo-fix.patch')
+sha256sums=('99e7f17d62d92d37aee850bdf7dfdc8572254e4b6c3c8b8f51143df06f2a04d9'
             '0276c9bf87f4624e9d109b8d9f20a0c1c508d5eff6ea4f530a017373c41c8822'
             '83a14017a6a09491db22b9d6972e0bd39f528c6a79fe8695d6fc5f9350c8e293'
             '4b6de45753856a890f4482055666e77f9b01bdfb7e0df08bafaa3a4d9937eed3'
@@ -43,8 +42,7 @@ sha256sums=('88b6e24123dbacf9edf49617627801aa2149331cf61459701376d3640dd3ba46'
             '0ca095ff2af57297f615877a7e79ddc84d1a3f62509a8af6ca50aad7a8671f6a'
             '0e9631fdad5efa3fd7a95b59171f5d15420d10aa61748b920cc994ee9227915c'
             'e6b8345215eb0c595cadfd6b1abb3a12a1cad8b8b1f3528e6affc58900695215'
-            'bf53a9712aada73dbecb45516bf932b52e7b8debf25cf19294adbfcc54d80028'
-            'd85bfcf25519f428fa3e0a1f2c7ca0fb3e4bb609a19346a6306f16cdca1d33b3')
+	    'bf53a9712aada73dbecb45516bf932b52e7b8debf25cf19294adbfcc54d80028')
 install='firefox.install'
 
 
@@ -84,8 +82,6 @@ build() {
 
 
 	msg "Patches from this package..."
-	# Cairo 1.10.x, thanks to wantilles
-	patch -Np2 -i "$srcdir"/beta-10-cairo.patch
 	# PGO compilation LDFLAGS fix
 	patch -Np1 -i "$srcdir"/ldflags-namespec.patch
 	# Enable experimental PGO for jemalloc (speed).
@@ -124,11 +120,11 @@ build() {
 	DISPLAY=:99 LD_PRELOAD="" MOZ_MAKE_FLAGS="$MAKEFLAGS" \
 		make -j1 -f client.mk profiledbuild \
 		PYTHONPATH='$(OBJDIR)/_profile/pgo'
-	RC=$?  # Store the make return code
-	kill -9 $XPID  # Kill the framebuffer
-	if [ $RC != 0 ]; then  # Build did not succeed, fail
-		return 1
-	fi
+#	RC=$?  # Store the make return code
+#	kill -9 $XPID  # Kill the framebuffer
+#	if [ $RC != 0 ]; then  # Build did not succeed, fail
+#		return 1
+#	fi
 }
 package() {
 	cd "$srcdir"/mozilla-central
