updated on Thu Jan  8 00:00:27 UTC 2015

diff --git a/gitit/PKGBUILD b/gitit/PKGBUILD
--- a/gitit/PKGBUILD
+++ b/gitit/PKGBUILD
@@ -1,33 +1,220 @@
-# Maintainer: Joop Kiefte <ikojba@gmail.com>
-_hkgname=gitit
+# Contributor: Joop Kiefte <ikojba@gmail.com>
+# Maintainer: Marcel Huber <`echo "moc tknup liamg tä oofrebuhlecram" | rev`>
+
 pkgname=gitit
-pkgver=0.10.3.1
+pkgver=0.10.6.1
 pkgrel=1
 pkgdesc="Wiki using happstack, git or darcs, and pandoc."
-url="http://hackage.haskell.org/package/${_hkgname}"
+url="https://github.com/jgm/gitit"
 license=('GPL')
 arch=('i686' 'x86_64')
-makedepends=()
-depends=('gmp' 'ghc' 'haskell-configfile<1.2' 'haskell-hstringtemplate<0.8' 'haskell-http=4000.1.1' 'haskell-sha<1.7' 'haskell-base64-bytestring<1.1' 'haskell-blaze-html<0.7' 'haskell-bytestring=0.9.1.10' 'haskell-cgi=3001.1.7.4' 'haskell-containers=0.4.0.0' 'haskell-directory=1.1.0.0' 'haskell-feed<0.4' 'haskell-filepath=1.2.0.0' 'haskell-filestore<0.7' 'haskell-ghc-paths' 'haskell-happstack-server<7.2' 'haskell-highlighting-kate<0.6' 'haskell-hslogger<1.3' 'haskell-json<0.8' 'haskell-mtl=2.0.1.0' 'haskell-network=2.3.0.2' 'haskell-old-locale=1.0.0.2' 'haskell-old-time=1.0.0.6' 'haskell-pandoc<1.12' 'haskell-pandoc-types<1.11' 'haskell-parsec=3.1.1' 'haskell-pretty=1.0.1.2' 'haskell-process=1.0.1.5' 'haskell-random=1.0.0.3' 'haskell-recaptcha>=0.1' 'haskell-safe' 'haskell-syb=0.3' 'haskell-tagsoup<0.13' 'haskell-text=0.11.0.5' 'haskell-time=1.2.0.3' 'haskell-url<2.2' 'haskell-utf8-string<0.4' 'haskell-xhtml=3000.2.0.1' 'haskell-xml>=1.3.5' 'haskell-xss-sanitize<0.4' 'haskell-zlib=0.5.3.1')
-options=('strip' 'staticlibs')
-source=(http://hackage.haskell.org/packages/archive/${_hkgname}/${pkgver}/${_hkgname}-${pkgver}.tar.gz)
-install=${pkgname}.install
-md5sums=('2b3fe00d34a40dfad4313ac546d8c70a')
+depends=('sh' 'ghc=7.8.4' 'cabal-install>=1.20')
+makedepends=('parallel' 'chrpath')
+optdepends=('texlive-most: for pdf creation')
+options=(strip staticlibs !makeflags !distcc !emptydirs)
+source=("$pkgname"::"git+https://github.com/jgm/gitit.git#tag=$pkgver"
+        plugins.patch)
+sha256sums=('SKIP'
+            '142646d8d5ea06dd799f68746672dbbd25453e627e6cd55afa7e168a4aaeef68')
+
+#pkgver() {
+#  cd "$srcdir/$pkgname"
+#  if GITTAG="$(git describe --abbrev=0 --tags 2>/dev/null)"; then
+#    local _revs_ahead_tag=$(git rev-list --count ${GITTAG}..)
+#    local _commit_id_short=$(git log -1 --format=%h)
+#    echo $(sed -e s/^${pkgname%%-git}// -e 's/^[-_/a-zA-Z]\+//' -e 's/[-_+]/./g' <<< ${GITTAG}).${_revs_ahead_tag}.g${_commit_id_short}
+#  else
+#    echo 0.$(git rev-list --count master).g$(git log -1 --format=%h)
+#  fi
+#}
+
+_cabal_verbose=--verbose
+_builddir=
+_confdir=
+_tmpdir=
+_pkgwithver=
+_tmppackages=
+_cabalsandboxdir=
+_cabalsandboxbindir=
+_cabaldir=
+_packageconfdir=
+_dependantpackagesfile=
+_packagestobuild=("$pkgname" ". datetime" "embed_data_files plugins")
+
+_firstPackageNameFromPackagesToBuildList() {
+  echo ${_packagestobuild[0]}
+}
+
+_setupLocalEnvVars() {
+  _builddir=$srcdir
+  _confdir=$_builddir/package.conf
+  _tmpdir=$_builddir/tmp
+  _pkgwithver=$pkgname-$pkgver
+  _tmppackages=$_builddir/pkg
+  _dependantpackagesfile=$_builddir/$(_firstPackageNameFromPackagesToBuildList).depends
+  # use another subdir for sandbox to not disturb regular build
+  _cabalsandboxdir=$_builddir/sandbox/.cabal-sandbox-$pkgname
+  _cabalsandboxbindir=$_cabalsandboxdir/bin
+  _cabaldir=$_builddir/.cabal
+  _packageconfdir=$pkgdir/usr/lib/$_pkgwithver/package.conf.d
+  mkdir -p $_confdir $_tmpdir $_tmppackages $_cabalsandboxdir
+  # in case your /tmp directory has no execute perms (needed for package installs)
+  export TMPDIR=$_tmpdir;
+  [ -n "$TMPDIR" -a ! -d "$TMPDIR" ] && mkdir -p "$TMPDIR"
+  # use our own local file storage for cabal instead of real $HOME/.cabal
+  export HOME=$_builddir;
+  export PATH=$_cabalsandboxbindir:$PATH
+}
+
+# $@ contains list of packages to get dependencies for
+_getcabaldepends() {
+  pushd "$srcdir/$pkgname" >/dev/null
+  local _installoptions="$1"
+  shift
+  local _packiges=$@
+  [ "$1" = "$pkgname" ] &&  _packiges=.
+  cabal install --dry-run $_installoptions $_packiges 2>/dev/null | grep "\-[0-9]\+" | cut -d' ' -f1
+  popd >/dev/null
+}
+
+_installBuildHelpers() {
+  msg2 "Installing build helpers"
+  local _sandboxbase=$(dirname $_cabalsandboxdir)
+  pushd "$_sandboxbase" >/dev/null
+  cabal sandbox --sandbox=$_cabalsandboxdir init
+  cabal update >/dev/null
+  cabal install \
+    --flags="embed_data_files" \
+    happy alex
+  popd >/dev/null
+}
+
+_extractFlags() {
+  local _filename=$1
+  sed -n '1 p' $_filename | tr -d '\n'
+}
+
+_extractPackages() {
+  local _filename=$1
+  sed -n '2,$ p' $_filename
+}
+
+_extractLastPackage() {
+  local _filename=$1
+  sed -n '$ p' $_filename
+}
+
+prepare() {
+  cd "$srcdir/$pkgname"
+  patch -Np1 -i "$srcdir"/plugins.patch
+  _setupLocalEnvVars
+  _installBuildHelpers
+  cabal update $_cabal_verbose
+  local _firstpackage=$(_firstPackageNameFromPackagesToBuildList)
+  local _installopts=""
+  if [ ! -f "$_dependantpackagesfile" ]; then
+    echo ${_packagestobuild[2]} >$_dependantpackagesfile
+    _getcabaldepends "$_installopts" ${_packagestobuild[1]} | grep -v "^$pkgname" >>$_dependantpackagesfile
+    if [ "$_firstpackage" = "$pkgname" ]; then
+      echo "$pkgname" >>$_dependantpackagesfile;
+    fi
+  fi
+  msg2 "Downloading/Extracting packages"
+  _extractPackages $_dependantpackagesfile | parallel --no-notice --no-run-if-empty --bar "cd $_builddir && cabal fetch {}>/dev/null; find $_cabaldir -name {}.tar.gz -exec tar xzf \{\} \;"
+}
+
+# arg1: configure options
+# arg2: package
+_buildPackageWithOpts() {
+  local _flags="$1"
+  local _hpkg=$2
+  if [ ! -d "$_builddir/$_hpkg" ]; then echo "Package $_hpkg not found, skipping"; return; fi
+  pushd $_builddir/$_hpkg >/dev/null
+  cabal configure \
+    --flags="$_flags" \
+    --prefix=/usr/lib/$_pkgwithver \
+    --datadir=/usr/share/$_pkgwithver \
+    --docdir=\$datadir/doc/\$pkgid \
+    --datasubdir=data/\$pkgid \
+    --libsubdir=\$pkgid
+  cabal build >/dev/null 2>&1;
+  cabal register --gen-pkg-config >/dev/null
+  local _conffile="$(ls $_hpkg*.conf)"
+  if [ -f "$_conffile" ]; then
+    cp -fp $_conffile $_confdir
+  fi
+  cabal register --inplace >/dev/null
+  cabal copy --destdir=$_tmppackages
+  popd >/dev/null
+}
+
 build() {
-    cd ${srcdir}/${_hkgname}-${pkgver}
-    runhaskell Setup configure -O ${PKGBUILD_HASKELL_ENABLE_PROFILING:+-p } --enable-split-objs --enable-shared \
-       --prefix=/usr --docdir=/usr/share/doc/${pkgname} --libsubdir=\$compiler/site-local/\$pkgid
-    runhaskell Setup build
-    runhaskell Setup haddock
-    runhaskell Setup register   --gen-script
-    runhaskell Setup unregister --gen-script
-    sed -i -r -e "s|ghc-pkg.*unregister[^ ]* |&'--force' |" unregister.sh
+  local _flags="$(_extractFlags $_dependantpackagesfile)"
+  export -f _buildPackageWithOpts
+  export _builddir _pkgwithver _tmppackages _confdir
+  _extractPackages $_dependantpackagesfile | parallel --jobs 1 --no-notice --no-run-if-empty --bar "_buildPackageWithOpts \"$_flags\" {}"
 }
+
+# arg1: path and name of script
+_createWrapperScript() {
+  mkdir -p "$(dirname $1)"
+  cat <<EOF >$1
+#!/bin/sh
+
+GHC_PACKAGE_PATH=\$(/usr/bin/ghc --print-global-package-db):$(echo $_packageconfdir | sed "s|$pkgdir||g" ):\$GHC_PACKAGE_PATH
+LD_LIBRARY_PATH=$2:\$LD_LIBRARY_PATH
+export GHC_PACKAGE_PATH LD_LIBRARY_PATH
+exec /usr/lib/$_pkgwithver/bin/\$(basename \$0) "\$@"
+
+EOF
+  chmod 0755 $1
+}
+
+_adjustRPATH() {
+  local _libbasedir=$1
+  local _outputfile=$2
+  local _cmd="chrpath --replace \"\$(chrpath --list {} | sed -n -e 's|.*RPATH=|| p' | tr ':' '\n' | sed -r -e 's|^.*/([^/]*)/dist/build|/usr/lib/"$_pkgwithver"/lib/\1|g' | tr '\n' ':')\" {} >/dev/null 2>&1"
+  find $_libbasedir -name '*.so' | parallel --jobs 1 --no-notice --no-run-if-empty "$_cmd" || true
+  touch $_outputfile
+}
+
+_stripRPATH() {
+  local _libbasedir=$1
+  local _outputfile=$2
+  find $_libbasedir -name '*.so' | parallel --jobs 1 --no-notice --no-run-if-empty "chrpath --list {} 2>/dev/null && chrpath --delete {} >/dev/null 2>&1" | sed -n 's|.*RPATH=||g p' | tr ':' '\n' | sort | uniq | sed -r -e "s|^.*/([^/]*)/dist/build|/usr/lib/$_pkgwithver/lib/\1|g" | sed -r '/^$/ d' >$_outputfile || true
+}
+
 package() {
-    cd ${srcdir}/${_hkgname}-${pkgver}
-    install -D -m744 register.sh   ${pkgdir}/usr/share/haskell/${pkgname}/register.sh
-    install    -m744 unregister.sh ${pkgdir}/usr/share/haskell/${pkgname}/unregister.sh
-    install -d -m755 ${pkgdir}/usr/share/doc/ghc/html/libraries
-    ln -s /usr/share/doc/${pkgname}/html ${pkgdir}/usr/share/doc/ghc/html/libraries/${_hkgname}
-    runhaskell Setup copy --destdir=${pkgdir}
+  _setupLocalEnvVars
+  local _licensedstdir=$pkgdir/usr/share/licenses/$_pkgwithver
+  local _licensesrcdir=$_tmppackages/usr/share/$_pkgwithver/doc
+  local _pkglibbasedir=$pkgdir/usr/lib/$_pkgwithver
+  mkdir -p $_licensedstdir
+  msg2 "Moving licenses..."
+  ( cd $_licensesrcdir && find . -maxdepth 2 -name 'LICENSE' | parallel --no-run-if-empty --no-notice "install -Dm444 $_licensesrcdir/{} $_licensedstdir/{}" )
+  for d in usr/share/$_pkgwithver/{doc,data,man} usr/lib/$_pkgwithver/lib; do
+    msg2 "Copying $(basename $d)..."
+    ( cd $_tmppackages && tar cf - --exclude='*/LICENSE' $d ) | ( cd $pkgdir && tar xf - )
+  done
+  msg2 "Registering packages in package.conf.d..."
+  ghc-pkg init $_packageconfdir >/dev/null 2>&1;
+  find $_confdir -name '*.conf' -exec ghc-pkg update --force-files --package-db=$_packageconfdir {} >/dev/null 2>&1 \;
+  msg2 "Creating scripts in /usr/bin..."
+  local _wrapperScriptLocation=$_pkglibbasedir/bin/gitit_wrapper.sh
+#  # adjust rpath entries pointing to build location
+#  _adjustRPATH "$_pkglibbasedir" "$srcdir/ld.path"
+  # delete rpath entries pointing to build location
+  _stripRPATH "$_pkglibbasedir" "$srcdir/ld.path"
+  _createWrapperScript "$_wrapperScriptLocation" "$(cat $srcdir/ld.path | tr '\n' ':')"
+  mkdir -p $pkgdir/usr/bin
+  for binname in gitit expireGititCache; do
+    local _binrel=usr/lib/$_pkgwithver/bin/$binname
+    local _fullbinpath=$pkgdir/$_binrel
+    install -Dm555 $_tmppackages/$_binrel $_fullbinpath
+    [ -f "$_fullbinpath" ] && ( cd $pkgdir/usr/bin && ln -s ${_wrapperScriptLocation/$pkgdir/} $binname )
+  done
+# clean up explicitly if wanted
+#  _extractPackages $_dependantpackagesfile | parallel --no-notice --no-run-if-empty --bar "pushd $_builddir/{} >/dev/null; cabal clean; popd >/dev/null"
 }
+
+# vim: set ft=sh syn=sh ts=2 sw=2 et:
