updated on Thu Aug 16 04:31:17 UTC 2012

diff --git a/linux-rifs/PKGBUILD b/linux-rifs/PKGBUILD
--- a/linux-rifs/PKGBUILD
+++ b/linux-rifs/PKGBUILD
@@ -5,43 +5,65 @@
 
 ### PATCH AND BUILD OPTIONS
 _makenconfig="n"	# tweak kernel options prior to a build via nconfig
-_UKMS_enable="y"	# patch kernel with UKMS (Ultra KMS)
+_UKMS_enable="y"  # patch kernel with UKMS (Ultra KMS)
+_localmodcfg="n"	# compile ONLY probed modules
 _use_current="n"	# use the current kernel's .config file
 _BFQ_enable_="y"	# enable BFQ as the default I/O scheduler
+
+### DOCS
+# DETAILS FOR _localmodcfg="y"
+# As of mainline 2.6.32, running with this option will only build the modules that you currently have
+# probed in your system VASTLY reducing the number of modules built and the build time to do it.
+#
+# WARNING - make CERTAIN that all modules are modprobed BEFORE you begin making the pkg!
+#
+# To keep track of which modules are needed for your specific system/hardware, give my module_db script
+# a try: http://aur.archlinux.org/packages.php?ID=41689  Note that if you use my script, this PKGBUILD 
+# will auto run the 'sudo modprobed_db reload' for you to probe all the modules you have logged!
+#
+# More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed_db
+
+# DETAILS FOR _use_current="y"
+# Enabling this option will use the .config of the RUNNING kernel rather than the ARCH defaults.
+# Useful when the package gets updated and you already went through the trouble of customizing your
+# config options.  NOT recommended when a new kernel is released, but again, convenient for package bumps.
+
+# DETAILS FOR _BFQ_enable="y"
+# Alternative I/O scheduler by Paolo.  For more, see: http://algo.ing.unimo.it/people/paolo/disk_sched/
 
 pkgname=linux-rifs
 true && pkgname=(linux-rifs linux-rifs-headers)
 _kernelname=-rifs
-_basekernel=3.5
-pkgver=${_basekernel}
-pkgrel=2
+_srcname=linux-3.5
+pkgver=3.5.2
+pkgrel=1
 arch=('i686' 'x86_64')
-url="https://code.google.com/p/rifs-scheduler"
+url="https://wiki.archlinux.org/index.php/Linux-rifs"
 license=('GPL2')
 options=('!strip')
 _bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.5.0-v4"
-source=("http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.5.tar.xz"
-#"http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
+source=("http://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
+"http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
 'http://kerneldedup.org/download/uksm/0.1.2/uksm-0.1.2-for-v3.5.patch'
-'rifs-es-kernel3.5.x-unofficial.patch'
+'http://rifs-scheduler.googlecode.com/files/rifs-kernel3.5.x'
+'nohz_fix.patch'
 'linux-rifs.preset'
 'config' 'config.x86_64'
 'change-default-console-loglevel.patch'
-'avmfritz-only-few-bytes-are-transfered-on-a-conn.patch'
 "${_bfqpath}/0001-block-cgroups-kconfig-build-bits-for-BFQ-v4-3.5.patch"
 "${_bfqpath}/0002-block-introduce-the-BFQ-v4-I-O-sched-for-3.5.patch")
 
 build() {
-	cd "${srcdir}/linux-${_basekernel}"
+	cd "${srcdir}/${_srcname}"
 
 	# add upstream patch
-	#patch -p1 -i "${srcdir}/patch-${pkgver}"
+	patch -p1 -i "${srcdir}/patch-${pkgver}"
 
   # Add uksm patches
   # kerneldedup.org
   if [ $_UKMS_enable = "y" ]; then
-    msg "Patching source with UKSM patch"
-    patch -Np1 -i "${srcdir}/uksm-0.1.2-for-v3.5.patch"
+		msg "Patching source with UKSM patch"
+		patch -Np1 -i "${srcdir}/uksm-0.1.2-for-v3.5.patch"
   fi
 
 	# set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
@@ -49,18 +71,17 @@ build() {
 	# (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
 	patch -Np1 -i "${srcdir}/change-default-console-loglevel.patch"
 
-	# fix avmfritz capi20 functionallity
-	# https://bugzilla.kernel.org/show_bug.cgi?id=45271
-	patch -Np1 -i "${srcdir}/avmfritz-only-few-bytes-are-transfered-on-a-conn.patch"
-
-	### Patch source with rifs patch
-	msg "Patching source with RIFS Scheduler"
-	patch -Np1 -i "${srcdir}/rifs-es-kernel3.5.x-unofficial.patch"
+  ### Patch source with rifs patch
+  sed -i 's/\/home\/admin\/\下\载\/linux-3.5/a/g' "${srcdir}/rifs-kernel3.5.x"
+  sed -i 's/\/home\/admin\/\文\档\/linux-hack\/linux-3.5-RIFS-v2/a/g' "${srcdir}/rifs-kernel3.5.x"
+  msg "Patching source with RIFS Scheduler"
+  patch -Np1 -i "${srcdir}/rifs-kernel3.5.x"
+	patch -Np1 -i "${srcdir}/nohz_fix.patch"
 
 	### Patch with BFQ IO Scheduler
 	msg "Patching source with BFQ patches"
 	for p in $(ls ${srcdir}/000{1,2}-block*.patch); do
-		patch -Np1 -i $p
+	 patch -Np1 -i $p
 	done
 
 	### Clean tree and copy ARCH config over
@@ -90,16 +111,17 @@ build() {
 
 	if [ "${_kernelname}" != "" ]; then
 		sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
+		sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
 	fi
 
 	### BFQ to be compiled in but not enabled
 	sed -i -e s'/CONFIG_CFQ_GROUP_IOSCHED=y/CONFIG_CFQ_GROUP_IOSCHED=y\nCONFIG_IOSCHED_BFQ=y\nCONFIG_CGROUP_BFQIO=y/' \
-		-i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
+	-i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
 
 	### Optionally enable BFQ as the default io scheduler
-	if [ $_BFQ_enable_ = "y" ]; then
-		sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
-			-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	 if [ $_BFQ_enable_ = "y" ]; then
+	sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
+		-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
 	fi
 
 	# set extraversion to pkgrel
@@ -112,99 +134,109 @@ build() {
 	msg "Running make prepare for you to enable patched options of your choosing"
 	make prepare
 
+	### Optionally load needed modules for the make localmodconfig
+	# See http://aur.archlinux.org/packages.php?ID=41689
+	if [ $_localmodcfg = "y" ]; then
+		msg "If you have modprobe_db installed, running it in recall mode now"
+		if [ -e /usr/bin/modprobed_db ]; then
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
+			sudo /usr/bin/modprobed_db recall
+		fi
+		msg "Running Steven Rostedt's make localmodconfig now"
+		make localmodconfig
+	fi
+
 	if [ $_makenconfig = "y" ]; then
 		msg "Running make nconfig"
 		make nconfig
 	fi
 
 	msg "Running make bzImage and modules"
-	make ${MAKEFLAGS} bzImage modules
+	make ${MAKEFLAGS} LOCALVERSION= bzImage modules
 }
 
 package_linux-rifs() {
 _Kpkgdesc='Linux Kernel and modules with the RIFS scheduler and optionally Ultra KMS (UKMS) and BFQ patches'
-	pkgdesc="${_Kpkgdesc}"
-	depends=('coreutils' 'linux-firmware' 'kmod>=9-2' 'mkinitcpio>=0.7')
-	optdepends=('dkms-nvidia-beta: DKMS nVidia drivers')
-	provides=("linux-rifs=${pkgver}")
-	conflicts=('kernel26-rifs')
-	replaces=('kernel26-rifs')
-	backup=("etc/mkinitcpio.d/linux-rifs.preset")
-	install=linux-rifs.install
-	#groups=('ck-generic')
+pkgdesc="${_Kpkgdesc}"
+depends=('coreutils' 'linux-firmware' 'mkinitcpio>=0.7')
+optdepends=('dkms-nvidia-beta: DKMS nvidia drivers')
+provides=("linux-rifs=${pkgver}")
+backup=("etc/mkinitcpio.d/linux-rifs.preset")
+install=linux-rifs.install
 
-	cd "${srcdir}/linux-${_basekernel}"
+cd "${srcdir}/${_srcname}"
 
-	KARCH=x86
+KARCH=x86
 
-	# get kernel version
-	_kernver="$(make kernelrelease)"
+# get kernel version
+_kernver="$(make LOCALVERSION= kernelrelease)"
+_basekernel=${_kernver%%-*}
+_basekernel=${_basekernel%.*}
 
-	mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot}
-	make INSTALL_MOD_PATH="${pkgdir}" modules_install
-	cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-linux-rifs"
+mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot}
+make LOCALVERSION= INSTALL_MOD_PATH="${pkgdir}" modules_install
+cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-linux-rifs"
 
-	# add vmlinux
-	install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
+# add vmlinux
+install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
 
-	# install fallback mkinitcpio.conf file and preset file for kernel
-	install -D -m644 "${srcdir}/linux-rifs.preset" "${pkgdir}/etc/mkinitcpio.d/linux-rifs.preset"
+# install fallback mkinitcpio.conf file and preset file for kernel
+install -D -m644 "${srcdir}/linux-rifs.preset" "${pkgdir}/etc/mkinitcpio.d/linux-rifs.preset"
 
-	# set correct depmod command for install
-	sed \
-		-e  "s/KERNEL_NAME=.*/KERNEL_NAME=-rifs/g" \
-		-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
-		-i "${startdir}/linux-rifs.install"
-	sed \
-		-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-linux-rifs\"|g" \
-		-e "s|default_image=.*|default_image=\"/boot/initramfs-linux-rifs.img\"|g" \
-		-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-linux-rifs-fallback.img\"|g" \
-		-i "${pkgdir}/etc/mkinitcpio.d/linux-rifs.preset"
+# set correct depmod command for install
+sed \
+	-e  "s/KERNEL_NAME=.*/KERNEL_NAME=-rifs/g" \
+	-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
+	-i "${startdir}/linux-rifs.install"
+sed \
+	-e "1s|'linux.*'|'linux-rifs'|" \
+	-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-linux-rifs\"|" \
+	-e "s|default_image=.*|default_image=\"/boot/initramfs-linux-rifs.img\"|" \
+	-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-linux-rifs-fallback.img\"|" \
+	-i "${pkgdir}/etc/mkinitcpio.d/linux-rifs.preset"
 
-	# remove build and source links
-	rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
-	# remove the firmware
-	rm -rf "${pkgdir}/lib/firmware"
-	# gzip -9 all modules to save 100MB of space
-	find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
-	# make room for external modules
-	ln -s "../extramodules-${_basekernel}${_kernelname:rifs}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
-	# add real version for building modules and running depmod from post_install/upgrade
-	mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:rifs}"
-	echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:rifs}/version"
+# remove build and source links
+rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
+# remove the firmware
+rm -rf "${pkgdir}/lib/firmware"
+# gzip -9 all modules to save 100MB of space
+find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
+# make room for external modules
+ln -s "../extramodules-${_basekernel}${_kernelname:ck}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
+# add real version for building modules and running depmod from post_install/upgrade
+mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:ck}"
+echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:ck}/version"
 
-	# move module tree /lib -> /usr/lib
-	mv "$pkgdir/lib" "$pkgdir/usr"
+# move module tree /lib -> /usr/lib
+mv "$pkgdir/lib" "$pkgdir/usr"
 
-	# Now we call depmod...
-	depmod -b "$pkgdir" -F System.map "$_kernver"
+# Now we call depmod...
+depmod -b "$pkgdir" -F System.map "$_kernver"
 }
 
 package_linux-rifs-headers() {
-	_Hpkgdesc='Header files and scripts to build modules for linux-rifs.'
-	pkgdesc="${_Hpkgdesc}"
-	provides=("linux-rifs-headers=${pkgver}")
-	conflicts=('kernel26-rifs-headers')
-	replaces=('kernel26-rifs-headers')
+_Hpkgdesc='Header files and scripts to build modules for linux-rifs.'
+pkgdesc="${_Hpkgdesc}"
+provides=("linux-rifs-headers=${pkgver}" "linux-headers=${pkgver}")
 
-	install -dm755 "${pkgdir}/usr/lib/modules/${_kernver}"
+install -dm755 "${pkgdir}/usr/lib/modules/${_kernver}"
 
-	cd "${pkgdir}/usr/lib/modules/${_kernver}"
-	ln -sf ../../../src/linux-${_kernver} build
+cd "${pkgdir}/usr/lib/modules/${_kernver}"
+ln -sf ../../../src/linux-${_kernver} build
 
-	cd "${srcdir}/linux-${_basekernel}"
-	install -D -m644 Makefile \
-		"${pkgdir}/usr/src/linux-${_kernver}/Makefile"
-	install -D -m644 kernel/Makefile \
-		"${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
-	install -D -m644 .config \
-		"${pkgdir}/usr/src/linux-${_kernver}/.config"
+cd "${srcdir}/${_srcname}"
+install -D -m644 Makefile \
+	"${pkgdir}/usr/src/linux-${_kernver}/Makefile"
+install -D -m644 kernel/Makefile \
+	"${pkgdir}/usr/src/linux-${_kernver}/kernel/Makefile"
+install -D -m644 .config \
+	"${pkgdir}/usr/src/linux-${_kernver}/.config"
 
-	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
+mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include"
 
-	for i in acpi asm-generic config crypto drm generated linux math-emu \
-		media net pcmcia scsi sound trace video xen; do
-		cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
+for i in acpi asm-generic config crypto drm generated linux math-emu \
+	media net pcmcia scsi sound trace video xen; do
+cp -a include/${i} "${pkgdir}/usr/src/linux-${_kernver}/include/"
 	done
 
 	# copy arch includes for external modules
@@ -241,7 +273,7 @@ package_linux-rifs-headers() {
 
 	# add docbook makefile
 	install -D -m644 Documentation/DocBook/Makefile \
-	"${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
+		"${pkgdir}/usr/src/linux-${_kernver}/Documentation/DocBook/Makefile"
 
 	# add dm headers
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/drivers/md"
@@ -263,7 +295,7 @@ package_linux-rifs-headers() {
 	# and...
 	# http://bugs.archlinux.org/task/11194
 	mkdir -p "${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/"
-	[[ -e include/config/dvb/ ]] && cp include/config/dvb/*.h "${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/"
+	[[ -e include/config/dvb/ ]] && cp include/config/dvb/*.h "${pkgdir}/usr/src/linux-${_kernver}/include/config/dvb/" 
 
 	# add dvb headers for http://mcentral.de/hg/~mrec/em28xx-new
 	# in reference to:
@@ -306,20 +338,21 @@ package_linux-rifs-headers() {
 		*application/x-executable*) # Binaries
 			/usr/bin/strip ${STRIP_BINARIES} "${binary}";;
 	esac
-	done
+done
 
-	# remove unneeded architectures
-	rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
+# remove unneeded architectures
+rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
 }
-# Global pkgdesc and depends
+# Global pkgdesc and depends are here so that they will be picked up by AUR
 pkgdesc='Linux Kernel and modules with the RIFS scheduler and optionally Ultra KMS (UKMS) and BFQ patches'
 md5sums=('24153eaaa81dedc9481ada8cd9c3b83d'
+         '8e9f9cfd5fbd33ac4b265a4d47949edc'
          '8c3e046e9f30aa2db69c02fa3a701746'
-         '1b6cd5797555be0ee94e6ce1637ba281'
-         'cfeb72a45c5dc25aa1e512014e803836'
-         '3ce9f5a89ab045515c5402d15e1e783b'
-         '2d9d84334ec81f489fafc01a2099497f'
+         '62dc87c4fbab22866d361b757aba44d3'
+         '9b41b8daf7a35aac39b4315bb0c94f68'
+         '5ca990b7396492ffce651611da0a8d86'
+         '7c81ba64d12485d52fa4b5bb22adfaea'
+         'd37da1bec1ddb5ced0765864a78dba44'
          '9d3c56a4b999c8bfbd4018089a62f662'
-         'aa2873841c73132a697f25d6d210876a'
          '5c0552440670dd3c41629346766cdb4a'
          'da1584d485b4bc604d8208b50a6acf42')
