updated on Sat Jun 25 11:31:17 UTC 2011

diff --git a/shotwell-git/shotwell.install b/shotwell-git/shotwell.install
--- a/shotwell-git/shotwell.install
+++ b/shotwell-git/shotwell.install
@@ -3,17 +3,18 @@ pkgname=shotwell
 post_install() {
   echo -n "Updating GTK+ icon cache..."
   gtk-update-icon-cache -fq -t /usr/share/icons/hicolor
-
   [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
 
   echo -n "Updating desktop MIME database..."
   update-desktop-database -q
-
   [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
   
   echo -n "Installing GConf schemas..."
   usr/sbin/gconfpkg --install ${pkgname}
+  [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
 
+  echo -n "Installing GSettings XML schemas..."
+  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
   [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
 }
 
@@ -35,11 +36,13 @@ pre_remove() {
 post_remove() {
   echo -n "Updating GTK+ icon cache..."
   gtk-update-icon-cache -fq -t /usr/share/icons/hicolor
-
   [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
 
   echo -n "Updating desktop MIME database..."
   update-desktop-database -q
-
+  [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
+  
+  echo -n "Updating GSettings XML schemas..."
+  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
   [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
 }
