updated on Fri Nov 29 00:23:39 UTC 2013

diff --git a/hets/PKGBUILD b/hets/PKGBUILD
--- a/hets/PKGBUILD
+++ b/hets/PKGBUILD
@@ -46,30 +46,46 @@ package() {
   install -Dm644 ${srcdir}/LICENSE.txt ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
 
   # The libtinfo.so functionality is built into the libncurses.so shared library.
-  install -d ${pkgdir}/usr/lib
-  ln -s /usr/lib/libncurses.so.5 ${pkgdir}/usr/lib/libtinfo.so.5
-  ln -s /usr/lib/libtinfo.so.5   ${pkgdir}/usr/lib/libtinfo.so
+  if ! test -e /usr/lib/libtinfo.so.5; then
+    install -d ${pkgdir}/usr/lib
+    if test -e /usr/lib/libtinfo.so; then
+      echo -e "Will symlink\n\
+  '/usr/lib/libtinfo.so' --> '/usr/lib/libtinfo.so.5'\n\
+after installation."
+      ln -s /usr/lib/libtinfo.so ${pkgdir}/usr/lib/libtinfo.so.5
+    elif test -e /usr/lib/libncurses.so.5; then
+      echo -e "Will symlink\n\
+  '/usr/lib/libncurses.so.5' --> '/usr/lib/libtinfo.so.5'\n\
+  '/usr/lib/libtinfo.so.5'   --> '/usr/lib/libtinfo.so'\n\
+after installation."
+      ln -s /usr/lib/libncurses.so.5 ${pkgdir}/usr/lib/libtinfo.so.5
+      ln -s /usr/lib/libtinfo.so.5   ${pkgdir}/usr/lib/libtinfo.so
+    else
+      echo "Cannot find either of '/usr/lib/libtinfo.so.5', '/usr/lib/libtinfo.so' or '/usr/lib/libncurses.so.5'."
+      return 1
+    fi
+  fi
 
   # Hets expects udrawgraph to be named uDrawGraph:
-  if test -e /usr/bin/udrawgraph; then
-    if ! test -e /usr/bin/uDrawGraph; then
-      echo "Will symlink '/usr/bin/uDrawGraph' --> '/usr/bin/udrawgraph' after installation."
+  if ! test -e /usr/bin/uDrawGraph; then
+    if test -e /usr/bin/udrawgraph; then
+      echo -e "Will symlink\n\
+  '/usr/bin/uDrawGraph' --> '/usr/bin/udrawgraph'\n\
+after installation."
       ln -s /usr/bin/udrawgraph ${pkgdir}/usr/bin/uDrawGraph
-    fi
-  else
-    if ! test -e /usr/bin/uDrawGraph; then
+    else
       echo "Cannot find either of '/usr/bin/udrawgraph' or '/usr/bin/uDrawGraph'."
       return 1
     fi
   fi
   # Hets expects eprover to be named eproof:
-  if test -e /usr/bin/eprover; then
-    if ! test -e /usr/bin/eproof; then
-      echo "Will symlink '/usr/bin/eprover' --> '/usr/bin/eproof' after installation."
+  if ! test -e /usr/bin/eproof; then
+    if test -e /usr/bin/eprover; then
+      echo -e "Will symlink\n\
+  '/usr/bin/eprover' --> '/usr/bin/eproof'\n\
+after installation."
       ln -s /usr/bin/eprover ${pkgdir}/usr/bin/eproof
-    fi
-  else
-    if ! test -e /usr/bin/eproof; then
+    else
       echo "Cannot find either of '/usr/bin/eprover' or '/usr/bin/eproof'."
       return 1
     fi
