updated on Sun May 10 00:05:24 UTC 2015

diff --git a/d2x-xl-data/PKGBUILD b/d2x-xl-data/PKGBUILD
--- a/d2x-xl-data/PKGBUILD
+++ b/d2x-xl-data/PKGBUILD
@@ -1,105 +1,87 @@
 pkgname=d2x-xl-data
-pkgver=1.17.34
-pkgrel=1
+pkgver=1.17.95
+pkgrel=3
 pkgdesc="Required D2X-XL data, extras, and Descent 1 and 2 retail data."
 arch=(any)
 url="http://www.descent2.de"
-license=("custom, Public Domain")
+license=("custom" "Public Domain")
 depends=(d2x-xl)
-makedepends=(dos2unix innoextract graphicsmagick p7zip)
+makedepends=(dos2unix innoextract p7zip)
 source=("http://www.descent2.de/files/d2x-xl-data-$pkgver.7z"
-"http://downloads.sourceforge.net/d2x-xl/D1-music.7z"
-"http://downloads.sourceforge.net/d2x-xl/D2-music.7z"
-"http://downloads.sourceforge.net/d2x-xl/loading-screens.7z"
-"http://downloads.sourceforge.net/d2x-xl/hires-sounds.7z"
-"http://downloads.sourceforge.net/d2x-xl/D1-textures-512x512.7z"
-"http://downloads.sourceforge.net/d2x-xl/D2-textures-512x512.7z"
-"http://downloads.sourceforge.net/d2x-xl/hires-models.7z")
-sha1sums=('16b6c1757d4d729efc0e13c111ca5de0d0ff1f34'
-          'ba7206b1c27bab7ad622c9547026d503a94cbde4'
-          '459069c83378d702531c6635265c8d6a397043e5'
-          'd7a53161967b086ef29fc3cdc85071b534b7af6c'
-          '199c6aacf52091362d43cac9fc94bca31d053ae9'
-          '8ed4bdd6fc1f81e0a2e4c599f3ad6915cb45e8c0'
-          'c03fece50545336bddb25e9611dd29d0eb418e53'
-          '42c081e631fa387841a12dcd1e21a33fab94fc9e')
+"http://www.descent2.de/files/movies/extra-movies.7z"
+"http://www.descent2.de/files/gamedata/extra-hog.7z"
+"vertigo_fixed.zip::http://www.planetdescent.net/index.php?PHPSESSID=siea2dvnnauba6vg04o5rl09s2&action=tpmod;dl=get51")
+sha1sums=('1863e8ccd830cc0bea04704ebc11b81fc1c7bbb9'
+          '2db5d6da8ab895a755ecdf1f7fc0dc2fc86b8397'
+          'ef67c771d77661a3c47d8e3292625d1cc50b8359'
+          '57e48cd004b8d45166ea1cf5d0e9d373e6cb0a09')
 
 prepare() {
-	cd "$srcdir"
-	_gog_md5="94e576d4be579a79be7845729f57ad8a"
-	_gog_exe="setup_descent12_2.0.0.7.exe"
-	if [[ -f ../$_gog_exe ]]; then
-		echo "GOG installer detected; checking md5sum ..."
-		if ! echo "$_gog_md5 ../$_gog_exe" | md5sum -c --status; then
-			error "Invalid md5sum; verify your download and try again."
-			return 1
-		else
-			ln -s ../$_gog_exe .
-			innoextract $_gog_exe
-		fi
-	else
-		error "You must have $_gog_exe present (.exe in main dir)."
+	_gog1_md5="c3fe34d48407201d6da65ae85b8e2e6b"
+	_gog1_exe="setup_descent_2.1.0.8.exe"
+	_gog2_md5="a2509588c7ca74b31689aeab19b16173"
+	_gog2_exe="setup_descent2_2.1.0.10.exe"
+	if [[ ! -f ../$_gog1_exe ]]; then
+		error "You must have $_gog1_exe present (.exe in main dir)."
 		error "Download the game from your GOG shelf and try again."
 		return 1
 	fi
+	if [[ ! -f ../$_gog2_exe ]]; then
+		error "You must have $_gog2_exe present (.exe in main dir)."
+		error "Download the game from your GOG shelf and try again."
+		return 1
+	fi
+	echo "GOG installers detected; checking md5sums ..."
+	if ! echo "$_gog1_md5 ../$_gog1_exe" | md5sum -c --status; then
+		error "Invalid md5sum; verify your download and try again."
+		return 1
+	else
+		ln -s ../$_gog1_exe .
+		innoextract $_gog1_exe
+	fi
+	if ! echo "$_gog2_md5 ../$_gog2_exe" | md5sum -c --status; then
+		error "Invalid md5sum; verify your download and try again."
+		return 1
+	else
+		ln -s ../$_gog2_exe .
+		innoextract $_gog2_exe
+	fi
 	find . -type f -exec dos2unix {} \;
-	cd "app/Descent 2"
-	gm convert descent2.ico descent2.png
 }
 
 package() {
-	cd "$srcdir"
-	folders="config data models sounds textures"
-	mkdir -p "$pkgdir/usr/share/d2x-xl/"
+	folders="data models movies sounds textures"
+	mkdir -p "$pkgdir/opt/d2x-xl/textures"
 	for f in $folders; do
-		cp -r $f "$pkgdir/usr/share/d2x-xl/"
-		chmod -R 644 "$pkgdir/usr/share/d2x-xl/$f"
+		cp -r $f "$pkgdir/opt/d2x-xl/"
+		chmod 755 "$pkgdir/opt/d2x-xl/$f"
 	done
-	ln -s "$pkgdir/usr/share/d2x-xl/data/descent.tex.eng" "$pkgdir/usr/share/d2x-xl/data/descent.tex"
-	folders2="models mods music sounds textures"
-	for f in $folders2; do
-		cp -r $f "$pkgdir/usr/share/d2x-xl/"
-		chmod -R 644 "$pkgdir/usr/share/d2x-xl/$f"
-	done
-
-	cd app/Descent
-	d1main="DESCENT.HOG DESCENT.PIG"
-	for f in $d1main; do
-		install -m644 $f "$pkgdir/usr/share/d2x-xl/data/$f"
-	done
-	find . -name 'CHAOS.*' -exec install -Dm644 {} "$pkgdir/usr/share/d2x-xl/missions/"{} \;
-
-	cd "../Descent 2"
-	install -Dm644 descent2.png "$pkgdir/usr/share/icons/descent2.png"
-	install -m644 DESCENT.CFG "$pkgdir/usr/share/d2x-xl/config/descent.cfg"
-	find . -name '*.PIG' -exec install -m644 {} "$pkgdir/usr/share/d2x-xl/data/" \;
-	find . -name '*.MVL' -exec install -Dm644 {} "$pkgdir/usr/share/d2x-xl/movies/"{} \;
-	d2main="DESCENT2.HAM DESCENT2.HOG DESCENT2.S11 DESCENT2.S22"
-	for f in $d2main; do
-		install -m644 $f "$pkgdir/usr/share/d2x-xl/data/$f"
-	done
-	cd MISSIONS
-	find . -type f -exec install -m644 {} "$pkgdir/usr/share/d2x-xl/missions/" \;
-	find "$pkgdir" -name '*.txt' -exec rm {} \;
-	cd "$pkgdir/usr/share/d2x-xl"
-	mv data/ALIEN1.PIG data/alien1.pig
-	mv data/ALIEN2.PIG data/alien2.pig
-	mv data/DESCENT.HOG data/descent.hog
-	mv data/DESCENT.PIG data/descent.pig
-	mv data/DESCENT2.HAM data/descent2.ham
-	mv data/DESCENT2.HOG data/descent2.hog
-	mv data/DESCENT2.S11 data/descent2.s11
-	mv data/DESCENT2.S22 data/descent2.s22
-	mv data/FIRE.PIG data/fire.pig
-	mv data/GROUPA.PIG data/groupa.pig
-	mv data/ICE.PIG data/ice.pig
-	mv data/WATER.PIG data/water.pig
-	mv missions/CHAOS.HOG missions/chaos.hog
-	mv missions/CHAOS.MSN missions/chaos.msn
-	mv movies/INTRO-H.MVL movies/intro-h.mvl
-	mv movies/OTHER-H.MVL movies/other-h.mvl
-	mv movies/ROBOTS-H.MVL movies/robots-h.mvl
-	mv movies/ROBOTS-L.MVL movies/robots-l.mvl
-	find $pkgdir -type d -exec chmod 755 {} \;
+	
+	install -Dm644 config/d2x-default.ini "$pkgdir/etc/skel/d2x-default.ini"
+	install -m644 d2x-h.mvl "$pkgdir/opt/d2x-xl/movies/d2x-h.mvl"
+	install -m644 d2x-l.mvl "$pkgdir/opt/d2x-xl/movies/"
+	install -Dm644 d2x.hog "$pkgdir/opt/d2x-xl/missions/d2x.hog"
+	install -m644 d2x.mn2 "$pkgdir/opt/d2x-xl/missions/"
+	install -m644 hoard.ham "$pkgdir/opt/d2x-xl/data/"
+	
+	cd app
+	install -Dm644 __support/save/DESCENT.CFG "$pkgdir/opt/d2x-xl/config/descent.cfg"
+	install -m644 ALIEN1.PIG "$pkgdir/opt/d2x-xl/data/alien1.pig"
+	install -m644 ALIEN2.PIG "$pkgdir/opt/d2x-xl/data/alien2.pig"
+	install -m644 DESCENT.HOG "$pkgdir/opt/d2x-xl/data/descent.hog"
+	install -m644 DESCENT.PIG "$pkgdir/opt/d2x-xl/data/descent.pig"
+	install -m644 DESCENT2.HAM "$pkgdir/opt/d2x-xl/data/descent2.ham"
+	install -m644 DESCENT2.HOG "$pkgdir/opt/d2x-xl/data/descent2.hog"
+	install -m644 DESCENT2.S11 "$pkgdir/opt/d2x-xl/data/descent2.s11"
+	install -m644 DESCENT2.S22 "$pkgdir/opt/d2x-xl/data/descent2.s22"
+	install -m644 FIRE.PIG "$pkgdir/opt/d2x-xl/data/fire.pig"
+	install -m644 GROUPA.PIG "$pkgdir/opt/d2x-xl/data/groupa.pig"
+	install -m644 ICE.PIG "$pkgdir/opt/d2x-xl/data/ice.pig"
+	install -m644 WATER.PIG "$pkgdir/opt/d2x-xl/data/water.pig"
+	install -m644 INTRO-H.MVL "$pkgdir/opt/d2x-xl/movies/intro-h.mvl"
+	install -m644 OTHER-H.MVL "$pkgdir/opt/d2x-xl/movies/other-h.mvl"
+	install -m644 ROBOTS-H.MVL "$pkgdir/opt/d2x-xl/movies/robots-h.mvl"
+	install -m644 ROBOTS-L.MVL "$pkgdir/opt/d2x-xl/movies/robots-l.mvl"
+	find "$pkgdir/opt/d2x-xl" -type d -exec chmod 755 {} \;
 }
 # vim:syntax=sh
