updated on Sat Jun  9 22:01:19 UTC 2012

diff --git a/bastion/PKGBUILD b/bastion/PKGBUILD
--- a/bastion/PKGBUILD
+++ b/bastion/PKGBUILD
@@ -1,104 +1,84 @@
-# Maintainer: Daniel Wallace <danielwallace at gtmanfred dot com>
+# ALL YOUR PKGBUILD ARE BELONG TO CORRUPT
+# ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^
 
 pkgname=bastion
 pkgver=2
 _pkgver=2012-06-01-1
 pkgrel=7
-pkgdesc="an original action role-playing game set in a lush imaginative world, in which players must create and fight for civilization’s last refuge as a mysterious narrator marks their every move."
-arch=('i686' 'x86_64')
-url="http://supergiantgames.com/?page_id=242"
+
+pkgdesc="An original action role-playing game set in a lush imaginative world, in which players must create and fight for civilization’s last refuge as a mysterious narrator marks their every move."
+url="http://www.supermeatboy.com/"
 license=('custom')
-makedepends=('xz' 'aria2')
+arch=('i686' 'x86_64')
+groups=("humble-indie-bundleV" "games")
 depends=('libxft')
-_sh=Bastion-HIB-$_pkgver.sh
-PKGEXT='.pkg.tar'
-#source=($pkgname.desktop)
-#md5sums=('5d0ae62e997fc2a121aec0105516840f')
-_shmd5=6bfaf5f637a1b54aef066506f6cd6e55
+makedepends=('curl')
+source=("Bastion-HIB-${_pkgver}.sh" "$pkgname.desktop" "mesa$pkgname" "$pkgname.install")
+install=$pkgname.install
+md5sums=('6bfaf5f637a1b54aef066506f6cd6e55'
+         '0facce79c6d93c5914a58e096eca8c92'
+         'a42e39c5f52abf19b6975cb79f732907'
+         '87417cee226efe4aca17ad99c44ea50b')
+PKGEXT=".pkg.tar"
 case $CARCH in
-  i686) _arch=x86 ;;
-  x86_64) _arch=x86_64;;
+    i686) _arch=x86 ;;
+    x86_64) _arch=x86_64;;
 esac
 
+_humblebundle() {
+	_archive="source[0]%%:*"
+	for group in "${groups[@]}"; do
 
+        [[ -f "${!_archive}" ]] && break;
 
-build() {
-    cd $srcdir
-    if [[ ! -h $_sh || ! -f $_sh ]];then
-        ln -s $startdir/$_sh $srcdir/$_sh
-        _md5sum=$(md5sum $_sh)
-    fi
-    if [[ -f $_sh ]];then
-        _md5sum=$(md5sum $_sh)
-
-    fi
-    if [[ ! -f $_sh || ${_md5sum%% *} != "$_shmd5" ]]; then
-        cd ..
-        echo "You do not have the file required for this install"
-        echo if you already have $_sh please place it into $PWD
-        echo Otherwise, press Enter to continue
-        cd "$srcdir"
-        read
-        if [[ -z "${_humblebundleVkey}" ]]; then
-            cd ..
-            echo You can automate the download of the archive using the _humblebundleVkey bash variable.
-            echo "Just add export  '_humblebundleVkey=<Your key here>' to .bashrc"
-            echo
-            echo Otherwise please just place ${_sh} into $(pwd)/
-            cd "$srcdir"
-            read
-        else
-            testfile=$(curl https://www.humblebundle.com/downloads\?key\=$_humblebundleVkey | grep $_sh)
-            echo "if you would like to use:"
-            echo "aria2c and the torrent file, input 1"
-            echo "curl and download the file directly, input 2"
-            echo "default is 1, 2 costs HIB bandwidth:"
-            read -a _torrent
-            if [[ $_torrent -eq 2 ]];then
-                testfile="${testfile#*data-web\=\'}"
-                curl -o "$_sh" "${testfile%%\'*}"
+		case "${group}" in 
+			"humble-indie-bundle"*) _key="_humblebundle${group:19}key" ;;
+			*) continue ;;
+		esac
+		if [[ -n "${!_key}" ]]; then
+			_uri="$(curl -s http://www.humblebundle.com/downloads?key="${!_key}" | grep "${!_archive}")"
+            echo "Choose download method."
+            echo "1. Torrent with aria2c"
+            echo "2. HTTP with curl"
+            read -a _method
+            if [[ "${_method}" -eq 2 ]]; then
+                _uri="${_uri##*data-web\=\'}"
+                _uri="${_uri%%\'*}" 
+                curl -o "${!_archive}" "${_uri}"
             else
-                testfile="${testfile##*data-bt\=\'}"
-                curl -o "$pkgname.torrent" "${testfile%%\'*}"
-                aria2c "$pkgname.torrent"
+                _uri="${_uri##*data-bt\=\'}"
+                _uri="${_uri%%\'*}" 
+                echo "To resume this download later:"
+                echo "Run \`aria2c ${pkgname}.torrent\`"
+                [[ ! -f "${pkgname}.torrent" ]] &&
+                curl -s -o "${pkgname}.torrent" "${_uri}"
+                aria2c "${pkgname}.torrent" --seed-time=0
             fi
-        fi
-    fi
-    _md5sum=$(md5sum $_sh);
-    if [[ ${_md5sum%% *} != $_shmd5 ]];then
-        echo "md5sum of downloaded file is invalid"
-        exit
-    fi
-    
-  rm -rf "$srcdir/$pkgname-$_pkgver"
-  sh $_sh -u --packager pacman --target "$srcdir/$pkgname-$_pkgver" --bindir "$pkgdir/opt/games/Bastion" --datadir "$pkgdir/opt/games"
+			source[0]="${!_archive}::${_uri}"
+		else
+			warning "Please export _humblebundleVkey for downloading"
+			echo "Alternatively, place the download into ${startdir} and retry"
+		fi
+	done
+	if [[ -z "${!_key}" && ! -f "${startdir}/${!_archive}" ]]; then
+		error "Failed to download \"${!_archive}\"."
+		exit 1
+	fi
+	unset _archive _key _uri 
+}
 
-}
 package() {
-  #install -d "$pkgdir/opt/games/$pkgname"
-cat <<EOF > "$srcdir/intelbastion"
-#!/usr/bin/env bash
-export force_s3tc_enable=true
-/usr/bin/bastion
-EOF
-cat <<EOF > "$srcdir/$pkgname.desktop"
-[Desktop Entry]
-Version=1.0
-Type=Application
-Icon=/opt/games/Bastion/Bastion.png
-Exec=/usr/bin/bastion
-Terminal=false
-StartupNotify=false
-Name=Bastion
-Comment=An original action role-playing game set in a lush imaginative world
-Categories=Game;
-EOF
-  install -Dm755 "$srcdir/intelbastion" "$pkgdir/usr/bin/intelbastion"
-  
-  # Make executable links.
-  ln -s "/opt/games/Bastion/Bastion.bin.$_arch" "$pkgdir/usr/bin/$pkgname"
-  # Install icons and .desktop files.
-  install -Dm644 "$pkgdir/opt/games/Bastion/Bastion.png" "$pkgdir/usr/share/icons/$pkgname.png"
-  install -Dm644 "$srcdir/$pkgname.desktop" "$pkgdir/usr/share/applications/$pkgname.desktop"
-  
+    cd $srcdir
+    [[ -d "$srcdir/$pkgname-$_pkgver" ]] && rm -r "$srcdir/$pkgname-$_pkgver"
+    sh ${source[0]%%:*} -u --packager pacman --target "$srcdir/$pkgname-$_pkgver" --bindir "$pkgdir/opt/games/Bastion" --datadir "$pkgdir/opt/games"
+
+	find "${pkgdir}" -type f -exec chmod 644 "{}" +
+	install -Dm644 "${pkgname}".desktop "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+	install -Dm755 "mesa${pkgname}" "${pkgdir}/usr/bin/mesa${pkgname}"
+	install -Dm644 "${pkgdir}/opt/games/Bastion/Bastion.png" "${pkgdir}/usr/share/icons/${pkgname}.png"
+
+	chmod 755 "${pkgdir}/opt/games/Bastion/Bastion.bin.$_arch"
+	ln -s "${pkgdir}/opt/games/Bastion/Bastion.bin.$_arch" "${pkgdir}/usr/bin/${pkgname}"
 }
+
+_humblebundle
