updated on Sun Feb 23 00:57:48 UTC 2014

diff --git a/anaconda/installer_sh_x86.patch b/anaconda/installer_sh_x86.patch
--- a/anaconda/installer_sh_x86.patch
+++ b/anaconda/installer_sh_x86.patch
@@ -1,18 +1,18 @@
---- a/Anaconda-1.9.0-Linux-x86.sh	2013-11-26 21:41:18.648086232 +0100
-+++ b/Anaconda-1.9.0-Linux-x86.sh	2013-11-26 21:38:49.227661186 +0100
+--- a/Anaconda-1.9.1-Linux-x86.sh	2013-11-26 21:41:18.648086232 +0100
++++ b/Anaconda-1.9.1-Linux-x86.sh	2013-11-26 21:38:49.227661186 +0100
 @@ -68,9 +68,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 571806071 >/dev/null
-+wc -c "$THIS_PATH" | grep 571806078 >/dev/null
+-wc -c "$THIS_PATH" | grep 431763871 >/dev/null
++wc -c "$THIS_PATH" | grep 431763878 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 571806071 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 571806078 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 431763871 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 431763878 bytes" >&2
      exit 1
  fi
  
-@@ -381,7 +381,7 @@
+@@ -382,7 +382,7 @@
  extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
@@ -21,12 +21,12 @@
  
  PYTHON="$PREFIX/pkgs/python-2.7.6-0/bin/python -E"
  $PYTHON -V
-@@ -391,7 +391,7 @@
+@@ -392,7 +392,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs//conda-3.0.3-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.0.6-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
diff --git a/anaconda/installer_sh_x86_64.patch b/anaconda/installer_sh_x86_64.patch
--- a/anaconda/installer_sh_x86_64.patch
+++ b/anaconda/installer_sh_x86_64.patch
@@ -1,18 +1,18 @@
---- a/Anaconda-1.9.0-Linux-x86_64.sh	2013-11-23 21:20:20.634138701 +0100
-+++ b/Anaconda-1.9.0-Linux-x86_64.sh	2013-11-23 21:27:25.435606276 +0100
+--- a/Anaconda-1.9.1-Linux-x86_64.sh	2013-11-23 21:20:20.634138701 +0100
++++ b/Anaconda-1.9.1-Linux-x86_64.sh	2013-11-23 21:27:25.435606276 +0100
 @@ -65,9 +65,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 648831310 >/dev/null
-+wc -c "$THIS_PATH" | grep 648831317 >/dev/null
+-wc -c "$THIS_PATH" | grep 507437430 >/dev/null
++wc -c "$THIS_PATH" | grep 507437437 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 648831310 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 648831317 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 507437430 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 507437437 bytes" >&2
      exit 1
  fi
  
-@@ -382,7 +382,7 @@
+@@ -383,7 +383,7 @@
  extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
@@ -21,12 +21,12 @@
  
  PYTHON="$PREFIX/pkgs/python-2.7.6-1/bin/python -E"
  $PYTHON -V
-@@ -392,7 +392,7 @@
+@@ -393,7 +393,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-3.0.3-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs/conda-3.0.6-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
