updated on Tue Feb 18 00:37:11 UTC 2014

diff --git a/anaconda/installer_sh_x86.patch b/anaconda/installer_sh_x86.patch
--- a/anaconda/installer_sh_x86.patch
+++ b/anaconda/installer_sh_x86.patch
@@ -1,32 +1,32 @@
---- a/Anaconda-1.8.0-Linux-x86.sh	2013-11-26 21:41:18.648086232 +0100
-+++ b/Anaconda-1.8.0-Linux-x86.sh	2013-11-26 21:38:49.227661186 +0100
+--- a/Anaconda-1.9.0-Linux-x86.sh	2013-11-26 21:41:18.648086232 +0100
++++ b/Anaconda-1.9.0-Linux-x86.sh	2013-11-26 21:38:49.227661186 +0100
 @@ -68,9 +68,9 @@
      fi
  fi
  # verify the size of the installer
--wc -c "$THIS_PATH" | grep 412040120 >/dev/null
-+wc -c "$THIS_PATH" | grep 412040127 >/dev/null
+-wc -c "$THIS_PATH" | grep 571806071 >/dev/null
++wc -c "$THIS_PATH" | grep 571806078 >/dev/null
  if (( $? )); then
--    echo "ERROR: size of $THIS_FILE should be 412040120 bytes" >&2
-+    echo "ERROR: size of $THIS_FILE should be 412040127 bytes" >&2
+-    echo "ERROR: size of $THIS_FILE should be 571806071 bytes" >&2
++    echo "ERROR: size of $THIS_FILE should be 571806078 bytes" >&2
      exit 1
  fi
  
-@@ -351,7 +351,7 @@
- install_dist _cache-0.0-x0
+@@ -381,7 +381,7 @@
+ extract_dist _cache-0.0-x0
  
  mkdir $PREFIX/envs
 -mkdir $HOME/.continuum 2>/dev/null
 +#mkdir $HOME/.continuum 2>/dev/null
  
- PYTHON="$PREFIX/pkgs/python-2.7.5-3/bin/python -E"
+ PYTHON="$PREFIX/pkgs/python-2.7.6-0/bin/python -E"
  $PYTHON -V
-@@ -361,7 +361,7 @@
+@@ -391,7 +391,7 @@
      uname -a
      exit 1
  fi
 -
 +exit 0
  echo "creating default environment..."
- CONDA_INSTALL="$PREFIX/pkgs/conda-2.0.4-py27_0/lib/python2.7/site-packages/conda/install.py"
+ CONDA_INSTALL="$PREFIX/pkgs//conda-3.0.3-py27_0/lib/python2.7/site-packages/conda/install.py"
  $PYTHON $CONDA_INSTALL --prefix=$PREFIX --pkgs-dir=$PREFIX/pkgs --link-all || exit 1
