updated on Sat Jan 21 17:30:53 UTC 2012

diff --git a/linux-lqx/PKGBUILD b/linux-lqx/PKGBUILD
--- a/linux-lqx/PKGBUILD
+++ b/linux-lqx/PKGBUILD
@@ -4,7 +4,7 @@
 ###########################################################################################################
 #                                          Patch and Build Options
 ###########################################################################################################
-_menu="n"	     # menuconfig option [m = make menuconfig; x = make xconfig; n = none]
+_menu="no"	     # menuconfig option [m = make menuconfig; x = make xconfig; n = nconfig; no = none;]
 _config="pkg"	 # "local":  make localmod config - compile ONLY probed modules - see notes below!
                # "old":    make with old config (/proc/config.gz)
                # "pkg":    use this package's config
@@ -90,23 +90,30 @@ build() {
   make prepare
   _kernver="$(make kernelrelease)"
 
-  ### Optionally load needed modules for the make localmodconfig
-  # See http://aur.archlinux.org/packages.php?ID=41689
-  if [ $_config = "local" ]; then
-    msg "If you have modprobe_db installed, running reload_database now"
-    if [ -e /usr/bin/reload_database ]; then
-      /usr/bin/reload_database
-    fi
-    msg "Running Steven Rostedt's make localmodconfig now"
-    make localmodconfig
-  else
-    yes "" | make config
+### Optionally load needed modules for the make localmodconfig
+ # See http://aur.archlinux.org/packages.php?ID=41689
+ if [ $_config = "local" ]; then
+  msg "If you have modprobe_db installed, running it in recall mode now"
+  if [ -e /usr/bin/modprobed_db ]; then
+    [[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo. Install via pacman -S sudo and configure to work with this user." && exit 1
+    sudo /usr/bin/modprobed_db recall
   fi
+  msg "Running Steven Rostedt's make localmodconfig now"
+  make localmodconfig
+ else
+  yes "" | make config
+ fi
 
-  if [ $_menu = "m" -o $_menu = "y" ]; then
+  if [ $_menu = "m" ]; then
     msg "Running make menuconfig"
     make menuconfig
   fi
+
+  if [ $_menu = "n" ]; then
+    msg "Running make nconfig"
+    make nconfig
+  fi
+
   if [ $_menu = "x" ]; then
     msg "Running make xconfig"
     make xconfig
