updated on Tue May 20 00:01:39 UTC 2014

diff --git a/refind-efi-git/PKGBUILD b/refind-efi-git/PKGBUILD
--- a/refind-efi-git/PKGBUILD
+++ b/refind-efi-git/PKGBUILD
@@ -1,13 +1,7 @@
 # Maintainer: Keshav Amburay <(the ddoott ridikulus ddoott rat) (aatt) (gemmaeiil) (ddoott) (ccoomm)>
 # Contributor: Tobias Powalowski <tpowa@archlinux.org>
 
-_USE_GNU_EFI="0"
-
-#######
-_gitroot="http://git.code.sf.net/p/refind/code"
-_gitname="refind"
-_gitbranch="master"
-#######
+_USE_GNU_EFI="1"
 
 #######
 [[ "${CARCH}" == "x86_64" ]] && _TIANO_ARCH="X64"
@@ -17,11 +11,12 @@ _gitbranch="master"
 [[ "${CARCH}" == "i686" ]] && _TIANO_S_ARCH="ia32"
 #######
 
-_pkgname="refind-efi"
+__pkgname="refind"
+_pkgname="${__pkgname}-efi"
 pkgname="${_pkgname}-git"
 
-pkgver=0.8.1.118.7971106.r14641
-pkgrel=1
+pkgver=0.8.1.2.322.45819ae
+pkgrel=2
 pkgdesc="Rod Smith's fork of rEFIt UEFI Boot Manager - GIT Version"
 url="http://www.rodsbooks.com/refind/index.html"
 arch=('x86_64' 'i686')
@@ -39,7 +34,7 @@ provides=("refind=${pkgver}" "refind-efi=${pkgver}")
 
 install="${_pkgname}.install"
 
-source=("${_gitname}::git+${_gitroot}#branch=${_gitbranch}"
+source=("refind::git+http://git.code.sf.net/p/refind/code#branch=master"
         'refind_linux.conf')
 
 if [[ "${_USE_GNU_EFI}" == "1" ]]; then
@@ -52,26 +47,16 @@ else
 	pkgdesc="${pkgdesc} - Built with Tianocore UDK libs"
 	makedepends+=('subversion' 'python2')
 	
-	#######
-	# _TIANOCORE_SVN_URL="https://svn.code.sf.net/p/edk2/code/branches/UDK2014"
-	# _TIANO_DIR_="tianocore-udk-2014-svn"
-	# _TIANO_SVN_REV_="15322"
+	_TIANOCORE_SVN_URL="https://svn.code.sf.net/p/edk2/code/branches/UDK2014"
+	_TIANO_DIR_="tianocore-udk-2014-svn"
+	_TIANO_SVN_REV_="15322"
 	
-	## BaseTools MdePkg MdeModulePkg IntelFrameworkPkg IntelFrameworkModulePkg
-	
-	_TIANOCORE_SVN_URL="https://svn.code.sf.net/p/edk2/code/branches/UDK2010.SR1"
-	_TIANO_DIR_="tianocore-udk-2010-svn"
-	_TIANO_SVN_REV_="14641"
-	#######
-	
-	#######
 	_TIANOCORE_PKG="Mde"
 	_TIANOCORE_TARGET="RELEASE"
 	_UDK_TARGET="${_TIANOCORE_PKG}Pkg/${_TIANOCORE_PKG}Pkg.dsc"
-	# _COMPILER="GCC48"
-	_COMPILER="GCC47"
-	#######
+	_COMPILER="GCC48"
 	
+	## BaseTools MdePkg MdeModulePkg IntelFrameworkPkg IntelFrameworkModulePkg
 	for _DIR_ in BaseTools MdePkg MdeModulePkg IntelFrameworkPkg IntelFrameworkModulePkg ; do
 		source+=("${_TIANO_DIR_}_${_DIR_}::svn+${_TIANOCORE_SVN_URL}/${_DIR_}#revision=${_TIANO_SVN_REV_}")
 	done
@@ -79,18 +64,13 @@ else
 fi
 
 sha1sums=('SKIP'
-          '3d53eb615c3363d45feb95b9bfbf1d5491bf1c24'
-          'SKIP'
-          'SKIP'
-          'SKIP'
-          'SKIP'
-          'SKIP')
+          'b6bc8653eb15a650b557db177378e65f6cbd52a3')
 
 pkgver() {
 	
-	cd "${srcdir}/${_gitname}/"
+	cd "${srcdir}/${__pkgname}/"
 	
-	_ACTUAL_REFIND_VER="$(grep 'rEFInd Version' "${srcdir}/${_gitname}/refind/main.c" | awk '{print $4}' | sed -e 's|");||g')"
+	_ACTUAL_REFIND_VER="$(grep 'rEFInd Version' "${srcdir}/${__pkgname}/refind/main.c" | awk '{print $4}' | sed -e 's|");||g')"
 	
 	if [[ "${_USE_GNU_EFI}" == "1" ]]; then
 		echo "${_ACTUAL_REFIND_VER}.$(git rev-list --count HEAD).$(git describe --always)" | sed -e 's|-|.|g'
@@ -143,7 +123,7 @@ _prepare_tianocore_sources() {
 	sed 's|-Werror |-Wno-error -Wno-unused-but-set-variable |g' -i "${EDK_TOOLS_PATH}/Source/C/Makefiles/header.makefile" || true
 	sed 's|-Werror |-Wno-error -Wno-unused-but-set-variable |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
 	
-	msg "Fix GenFw: ERROR 3000: Invalid, refind_x64.dll bad symbol definition"
+	msg "Fix GenFw: ERROR 3000: Invalid, bad symbol definition"
 	## http://www.mail-archive.com/edk2-devel@lists.sourceforge.net/msg03625.html
 	sed -e 's|_OBJCOPY_FLAGS      =|_OBJCOPY_FLAGS      = -R .eh_frame|g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
 	
@@ -152,13 +132,15 @@ _prepare_tianocore_sources() {
 	sed 's|--64 | |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
 	sed 's| -m64 -melf_x86_64| -m64|g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
 	
-	msg "Remove GCC -g debug option and add -0s -mabi=ms"
-	sed 's|DEFINE GCC_ALL_CC_FLAGS            = -g |DEFINE GCC_ALL_CC_FLAGS            = -Os -mabi=ms -maccumulate-outgoing-args |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
-	sed 's|DEFINE GCC44_ALL_CC_FLAGS            = -g |DEFINE GCC44_ALL_CC_FLAGS            = -Os -mabi=ms -maccumulate-outgoing-args |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
+	msg "Remove GCC -g debug option and add -O0 -mabi=ms -maccumulate-outgoing-args"
+	sed 's|DEFINE GCC_ALL_CC_FLAGS            = -g |DEFINE GCC_ALL_CC_FLAGS            = -O0 -mabi=ms -maccumulate-outgoing-args |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
+	sed 's|DEFINE GCC44_ALL_CC_FLAGS            = -g |DEFINE GCC44_ALL_CC_FLAGS            = -O0 -mabi=ms -maccumulate-outgoing-args |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
 	
-	# msg "For 32-byte section alignment"
-	# sed 's|_GCC47_IA32_OBJCOPY_FLAGS        =|_GCC47_IA32_OBJCOPY_FLAGS        = --section-alignment=0x20 |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
-	# sed 's|_GCC47_X64_OBJCOPY_FLAGS        =|_GCC47_X64_OBJCOPY_FLAGS        = --section-alignment=0x20 |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
+	# msg "Fix GenFw: ERROR 3000: Invalid, Unsupported section alignment"
+	# sed 's|Error (NULL, 0, 3000, "Invalid", "Unsupported section alignment.");|continue;|g' -i "${EDK_TOOLS_PATH}/Source/C/GenFw/Elf64Convert.c"
+	# sed 's|Error (NULL, 0, 3000, "Invalid", "Unsupported section alignment.");|continue;|g' -i "${EDK_TOOLS_PATH}/Source/C/GenFw/Elf32Convert.c"
+	# sed 's|_GCC48_IA32_OBJCOPY_FLAGS        =|_GCC48_IA32_OBJCOPY_FLAGS        = --section-alignment=0x20 |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
+	# sed 's|_GCC48_X64_OBJCOPY_FLAGS        =|_GCC48_X64_OBJCOPY_FLAGS        = --section-alignment=0x20 |g' -i "${EDK_TOOLS_PATH}/Conf/tools_def.template" || true
 	
 	msg "Fix UDK Target Platform"
 	sed "s|ACTIVE_PLATFORM       = Nt32Pkg/Nt32Pkg.dsc|ACTIVE_PLATFORM       = ${_UDK_TARGET}|g" -i "${EDK_TOOLS_PATH}/Conf/target.template" || true
@@ -175,10 +157,10 @@ _prepare_tianocore_sources() {
 
 _prepare_refind_sources() {
 	
-	rm -rf "${srcdir}/${_gitname}_build/" || true
-	cp -r "${srcdir}/${_gitname}" "${srcdir}/${_gitname}_build"
+	rm -rf "${srcdir}/${__pkgname}_build/" || true
+	cp -r "${srcdir}/${__pkgname}" "${srcdir}/${__pkgname}_build"
 	
-	cd "${srcdir}/${_gitname}_build/"
+	cd "${srcdir}/${__pkgname}_build/"
 	
 	msg "Clean rEFInd git repo"
 	git clean -x -d -f
@@ -186,29 +168,26 @@ _prepare_refind_sources() {
 	
 	if [[ "${_USE_GNU_EFI}" != "1" ]]; then
 		msg "Fix UDK Path in rEFInd Makefiles"
-		sed "s|EDK2BASE = /usr/local/UDK2010/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${_gitname}_build/Make.tiano" || true
-		sed "s|EDK2BASE = /usr/local/UDK2010/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${_gitname}_build/filesystems/Make.tiano" || true
-		sed "s|EDK2BASE = /usr/local/UDK2010/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${_gitname}_build/gptsync/Make.tiano" || true
-		
-		msg "Fix GenFw: ERROR 3000: Invalid, refind_x64.dll bad symbol definition"
-		sed -e 's|--strip-unneeded|--strip-unneeded -R .eh_frame|g' -i "${srcdir}/${_gitname}_build/refind/Make.tiano" || true
-		sed -e 's|--strip-unneeded|--strip-unneeded -R .eh_frame|g' -i "${srcdir}/${_gitname}_build/filesystems/Make.tiano"
-		sed -e 's|--strip-unneeded|--strip-unneeded -R .eh_frame|g' -i "${srcdir}/${_gitname}_build/gptsync/Make.tiano" || true
+		sed "s|EDK2BASE = /usr/local/UDK2014/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${__pkgname}_build/Make.tiano" || true
+		sed "s|EDK2BASE = /usr/local/UDK2014/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${__pkgname}_build/filesystems/Make.tiano" || true
+		sed "s|EDK2BASE = /usr/local/UDK2014/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${__pkgname}_build/gptsync/Make.tiano" || true
+		sed "s|EDK2BASE = /usr/local/UDK2010/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${__pkgname}_build/Make.tiano" || true
+		sed "s|EDK2BASE = /usr/local/UDK2010/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${__pkgname}_build/filesystems/Make.tiano" || true
+		sed "s|EDK2BASE = /usr/local/UDK2010/MyWorkSpace|EDK2BASE = ${_UDK_DIR}|g" -i "${srcdir}/${__pkgname}_build/gptsync/Make.tiano" || true
 		
 		# msg "Fix GenFw: ERROR 3000: Invalid section alignment"
-		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${_gitname}_build/Make.tiano" || true
-		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${_gitname}_build/refind/Make.tiano" || true
-		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${_gitname}_build/filesystems/Make.tiano"
-		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${_gitname}_build/gptsync/Make.tiano" || true
-		# sed -e 's|--strip-unneeded|--section-alignment=0x20 --strip-unneeded|g' -i "${srcdir}/${_gitname}_build/refind/Make.tiano" || true
-		# sed -e 's|--strip-unneeded|--section-alignment=0x20 --strip-unneeded|g' -i "${srcdir}/${_gitname}_build/filesystems/Make.tiano"
-		# sed -e 's|--strip-unneeded|--section-alignment=0x20 --strip-unneeded|g' -i "${srcdir}/${_gitname}_build/gptsync/Make.tiano" || true
+		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${__pkgname}_build/Make.tiano" || true
+		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${__pkgname}_build/refind/Make.tiano" || true
+		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${__pkgname}_build/filesystems/Make.tiano"
+		# sed -e 's|--gc-sections|--gc-sections -z max-page-size=0x20|g' -i "${srcdir}/${__pkgname}_build/gptsync/Make.tiano" || true
+		# sed -e 's|--strip-unneeded|--section-alignment=0x20 --strip-unneeded|g' -i "${srcdir}/${__pkgname}_build/refind/Make.tiano" || true
+		# sed -e 's|--strip-unneeded|--section-alignment=0x20 --strip-unneeded|g' -i "${srcdir}/${__pkgname}_build/filesystems/Make.tiano"
+		# sed -e 's|--strip-unneeded|--section-alignment=0x20 --strip-unneeded|g' -i "${srcdir}/${__pkgname}_build/gptsync/Make.tiano" || true
 	else
 		msg "Enable GNU_EFI_USE_MS_ABI"
-		sed "s|-DEFI_FUNCTION_WRAPPER|-DEFI_FUNCTION_WRAPPER -mabi=ms -maccumulate-outgoing-args|g" -i "${srcdir}/${_gitname}_build/Make.common" || true
-		sed "s|-DEFIX64|-DEFIX64 -mabi=ms -maccumulate-outgoing-args|g" -i "${srcdir}/${_gitname}_build/Make.common" || true
-		sed "s|-m64|-mabi=ms -maccumulate-outgoing-args -m64|g" -i "${srcdir}/${_gitname}_build/Make.gnuefi" || true
-		sed "s|-m64|-mabi=ms -maccumulate-outgoing-args -m64|g" -i "${srcdir}/${_gitname}_build/filesystems/Make.gnuefi" || true
+		sed "s|-DEFI_FUNCTION_WRAPPER|-DEFI_FUNCTION_WRAPPER -maccumulate-outgoing-args|g" -i "${srcdir}/${__pkgname}_build/Make.common" || true
+		sed "s|-DEFIX64|-DEFIX64 -maccumulate-outgoing-args|g" -i "${srcdir}/${__pkgname}_build/Make.common" || true
+		sed "s|-m64|-maccumulate-outgoing-args -m64|g" -i "${srcdir}/${__pkgname}_build/filesystems/Make.gnuefi" || true
 	fi
 	
 }
@@ -260,7 +239,7 @@ build() {
 		_build_tianocore_sources
 	fi
 	
-	cd "${srcdir}/${_gitname}_build/"
+	cd "${srcdir}/${__pkgname}_build/"
 	
 	msg "Unset all compiler FLAGS"
 	unset CFLAGS
@@ -278,7 +257,7 @@ build() {
 		echo
 	fi
 	
-	cd "${srcdir}/${_gitname}_build/filesystems/"
+	cd "${srcdir}/${__pkgname}_build/filesystems/"
 	
 	msg "Unset all compiler FLAGS"
 	unset CFLAGS
@@ -289,7 +268,7 @@ build() {
 	
 	msg "Compile UEFI FS drivers"
 	if [[ "${_USE_GNU_EFI}" != "1" ]]; then
-		# make btrfs
+		make btrfs
 		echo
 		
 		make ext4
@@ -301,13 +280,16 @@ build() {
 		make hfs
 		echo
 		
-		# make iso9660
+		make iso9660
 		echo
 		
-		# make reiserfs
+		make reiserfs
+		echo
+		
+		make xfs
 		echo
 	else
-		make fs_gnuefi
+		make all_gnuefi
 		echo
 	fi
 	
@@ -317,56 +299,56 @@ package() {
 	
 	msg "Install the rEFInd UEFI application"
 	install -d "${pkgdir}/usr/share/refind/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/refind/refind_${_TIANO_S_ARCH}.efi" "${pkgdir}/usr/share/refind/refind_${_TIANO_S_ARCH}.efi"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/refind/refind_${_TIANO_S_ARCH}.efi" "${pkgdir}/usr/share/refind/refind_${_TIANO_S_ARCH}.efi"
 	
 	msg "Install UEFI drivers built from rEFInd"
 	install -d "${pkgdir}/usr/share/refind/drivers_${_TIANO_S_ARCH}/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/drivers_${_TIANO_S_ARCH}"/*.efi "${pkgdir}/usr/share/refind/drivers_${_TIANO_S_ARCH}/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/drivers_${_TIANO_S_ARCH}"/*.efi "${pkgdir}/usr/share/refind/drivers_${_TIANO_S_ARCH}/"
 	
 	msg "Install UEFI applications built from rEFInd"
 	install -d "${pkgdir}/usr/share/refind/tools_${_TIANO_S_ARCH}"
-	install -D -m0644 "${srcdir}/${_gitname}_build/gptsync/gptsync_${_TIANO_S_ARCH}.efi" "${pkgdir}/usr/share/refind/tools_${_TIANO_S_ARCH}/gptsync_${_TIANO_S_ARCH}.efi"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/gptsync/gptsync_${_TIANO_S_ARCH}.efi" "${pkgdir}/usr/share/refind/tools_${_TIANO_S_ARCH}/gptsync_${_TIANO_S_ARCH}.efi"
 	
 	msg "Install rEFInd helper scripts"
 	install -d "${pkgdir}/usr/bin/"
-	install -D -m0755 "${srcdir}/${_gitname}_build/install.sh" "${pkgdir}/usr/bin/refind-install"
-	install -D -m0755 "${srcdir}/${_gitname}_build/mkrlconf.sh" "${pkgdir}/usr/bin/refind-mkrlconf"
-	install -D -m0755 "${srcdir}/${_gitname}_build/mvrefind.sh" "${pkgdir}/usr/bin/refind-mvrefind"
-	install -D -m0755 "${srcdir}/${_gitname}_build/fonts/mkfont.sh" "${pkgdir}/usr/bin/refind-mkfont"
+	install -D -m0755 "${srcdir}/${__pkgname}_build/install.sh" "${pkgdir}/usr/bin/refind-install"
+	install -D -m0755 "${srcdir}/${__pkgname}_build/mkrlconf.sh" "${pkgdir}/usr/bin/refind-mkrlconf"
+	install -D -m0755 "${srcdir}/${__pkgname}_build/mvrefind.sh" "${pkgdir}/usr/bin/refind-mvrefind"
+	install -D -m0755 "${srcdir}/${__pkgname}_build/fonts/mkfont.sh" "${pkgdir}/usr/bin/refind-mkfont"
 	
 	msg "Install the rEFInd sample config files"
-	install -D -m0644 "${srcdir}/${_gitname}_build/refind.conf-sample" "${pkgdir}/usr/share/refind/refind.conf-sample"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/refind.conf-sample" "${pkgdir}/usr/share/refind/refind.conf-sample"
 	install -D -m0644 "${srcdir}/refind_linux.conf" "${pkgdir}/usr/share/refind/refind_linux.conf-sample"
 	
 	msg "Install the rEFInd docs"
 	install -d "${pkgdir}/usr/share/refind/docs/html/"
 	install -d "${pkgdir}/usr/share/refind/docs/Styles/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/docs/refind"/* "${pkgdir}/usr/share/refind/docs/html/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/docs/Styles"/* "${pkgdir}/usr/share/refind/docs/Styles/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/README.txt" "${pkgdir}/usr/share/refind/docs/README.txt"
-	install -D -m0644 "${srcdir}/${_gitname}_build/NEWS.txt" "${pkgdir}/usr/share/refind/docs/NEWS.txt"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/docs/refind"/* "${pkgdir}/usr/share/refind/docs/html/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/docs/Styles"/* "${pkgdir}/usr/share/refind/docs/Styles/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/README.txt" "${pkgdir}/usr/share/refind/docs/README.txt"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/NEWS.txt" "${pkgdir}/usr/share/refind/docs/NEWS.txt"
 	rm -f "${pkgdir}/usr/share/refind/docs/html/.DS_Store" || true
 	
 	msg "Install the rEFInd fonts"
 	install -d "${pkgdir}/usr/share/refind/fonts/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/fonts"/* "${pkgdir}/usr/share/refind/fonts/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/fonts"/* "${pkgdir}/usr/share/refind/fonts/"
 	rm -f "${pkgdir}/usr/share/refind/fonts/mkfont.sh"
 	
 	msg "Install the rEFInd icons"
 	install -d "${pkgdir}/usr/share/refind/icons/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/icons"/* "${pkgdir}/usr/share/refind/icons/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/icons"/* "${pkgdir}/usr/share/refind/icons/"
 	
 	msg "Install the rEFInd images"
 	install -d "${pkgdir}/usr/share/refind/images/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/images"/*.{png,bmp} "${pkgdir}/usr/share/refind/images/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/images"/*.{png,bmp} "${pkgdir}/usr/share/refind/images/"
 	
 	msg "Install the rEFInd keys"
 	install -d "${pkgdir}/usr/share/refind/keys/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/keys"/* "${pkgdir}/usr/share/refind/keys/"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/keys"/* "${pkgdir}/usr/share/refind/keys/"
 	
 	msg "Install the rEFIt license file, since rEFInd is a fork of rEFIt"
 	install -d "${pkgdir}/usr/share/licenses/refind/"
-	install -D -m0644 "${srcdir}/${_gitname}_build/LICENSE.txt" "${pkgdir}/usr/share/licenses/refind/LICENSE"
+	install -D -m0644 "${srcdir}/${__pkgname}_build/LICENSE.txt" "${pkgdir}/usr/share/licenses/refind/LICENSE"
 	
 	msg "Use '#!/usr/bin/env bash' in all scripts"
 	sed 's|#!/bin/bash|#!/usr/bin/env bash|g' -i "${pkgdir}/usr/bin"/refind-* || true
diff --git a/wine-photoshop/PKGBUILD b/wine-photoshop/PKGBUILD
--- a/wine-photoshop/PKGBUILD
+++ b/wine-photoshop/PKGBUILD
@@ -1,186 +1,28 @@
 # Maintainer: David Manouchehri <d@32t.ca>
-# Maintainer (original PKGBUILD): Sven-Hendrik Haase <sh@lutzhaase.com>
-# Contributor: Jan "heftig" Steffens <jan.steffens@gmail.com>
-# Contributor: Eduardo Romero <eduardo@archlinux.org>
-# Contributor: Giovanni Scafora <giovanni@archlinux.org>
 
 pkgname=wine-photoshop
-_pkgname=wine
-pkgver=1.7.7
+pkgver=0
 pkgrel=1
-conflicts=('wine')
-provides=($_pkgname-$pkgver)
-pkgdesc="A compatibility layer for running Windows programs, patched for Photoshop use"
-
-
-_pkgbasever=${pkgver/rc/-rc}
-
-source=(http://prdownloads.sourceforge.net/$_pkgname/$_pkgname-$_pkgbasever.tar.bz2{,.sign}
-        http://bugs.winehq.org/attachment.cgi?id=39231
-        30-win32-aliases.conf)
-sha512sums=('94a4bb48261b575f7f8c8e1d6b54192dbf35b9aa595fb5afd571458cc94af2b72591facb32e7777e1ceb650a3567a3708089ab363d20b0cc4fc4984e31accb52'
-            'SKIP'
-            'acbedd24c07ccad663fc4ec13de4e7ec0de22c329517f1ffeca22e82a2e526e5257bf1b3d37ad40c97e210419c67f14b1a733aba3d1b8fe3e2c577775dbce422'
-            '6e54ece7ec7022b3c9d94ad64bdf1017338da16c618966e8baf398e6f18f80f7b0576edf1d1da47ed77b96d577e4cbb2bb0156b0b11c183a0accf22654b0a2bb')
-
-url="http://www.winehq.com"
-arch=(i686 x86_64)
-options=(staticlibs)
+arch=('i686' 'x86_64')
 license=(LGPL)
-install=wine.install
+url="http://www.winehq.com"
+pkgdesc="A compatibility layer for running Windows programs, patched for Photoshop"
+source=(PKGBUILD_stock::https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/wine
+        30-win32-aliases.conf::https://projects.archlinux.org/svntogit/community.git/plain/trunk/30-win32-aliases.conf?h=packages/wine
+        wine.install::https://projects.archlinux.org/svntogit/community.git/plain/trunk/wine.install?h=packages/wine
+        PKGBUILD.patch)
+sha512sums=('SKIP' 'SKIP' 'SKIP' 'c1e4744466ab83f300e6f458e0bebd5672e848700a0c28d488f1b9c9d594f3206141165a62c74e361fb5be5e25a62440a261d093e06c541e7479fc8c42bfa318') # These are going to get checked later anyway
 
-
-_depends=(
-  fontconfig      lib32-fontconfig
-  libxcursor      lib32-libxcursor
-  libxrandr       lib32-libxrandr
-  libxdamage      lib32-libxdamage
-  libxi           lib32-libxi
-  gettext         lib32-gettext
-  freetype2       lib32-freetype2
-  glu             lib32-glu
-  libsm           lib32-libsm
-  gcc-libs        lib32-gcc-libs
-  desktop-file-utils
-)
-
-makedepends=(autoconf ncurses bison perl fontforge flex prelink
-  'gcc>=4.5.0-2'  'gcc-multilib>=4.5.0-2'
-  giflib          lib32-giflib
-  libpng          lib32-libpng
-  gnutls          lib32-gnutls
-  libxinerama     lib32-libxinerama
-  libxcomposite   lib32-libxcomposite
-  libxmu          lib32-libxmu
-  libxxf86vm      lib32-libxxf86vm
-  libxml2         lib32-libxml2
-  libldap         lib32-libldap
-  lcms            lib32-lcms
-  mpg123          lib32-mpg123
-  openal          lib32-openal
-  v4l-utils       lib32-v4l-utils
-  alsa-lib        lib32-alsa-lib
-  libxcomposite   lib32-libxcomposite
-  mesa            lib32-mesa
-  mesa-libgl      lib32-mesa-libgl
-  libcl           lib32-libcl
-  samba
-  opencl-headers
-)
-  
-optdepends=(
-  giflib          lib32-giflib
-  libpng          lib32-libpng
-  libldap         lib32-libldap
-  gnutls          lib32-gnutls
-  lcms            lib32-lcms
-  libxml2         lib32-libxml2
-  mpg123          lib32-mpg123
-  openal          lib32-openal
-  v4l-utils       lib32-v4l-utils
-  libpulse        lib32-libpulse
-  alsa-plugins    lib32-alsa-plugins
-  alsa-lib        lib32-alsa-lib
-  libjpeg-turbo   lib32-libjpeg-turbo
-  libxcomposite   lib32-libxcomposite
-  libxinerama     lib32-libxinerama
-  ncurses         lib32-ncurses
-  libcl           lib32-libcl
-  cups
-  samba           dosbox
-)
-
-if [[ $CARCH == i686 ]]; then
-  # Strip lib32 etc. on i686
-  _depends=(${_depends[@]/*32-*/})
-  makedepends=(${makedepends[@]/*32-*/} ${_depends[@]})
-  makedepends=(${makedepends[@]/*-multilib*/})
-  optdepends=(${optdepends[@]/*32-*/})
-else
-  makedepends=(${makedepends[@]} ${_depends[@]})
-  provides=("bin32-wine=$pkgver" "wine-wow64=$pkgver")
-  conflicts=('bin32-wine' 'wine-wow64')
-  replaces=('bin32-wine')
-fi
-
-build() {
-  cd "$srcdir/$_pkgname-$pkgver"
-  patch -p1 -i "$srcdir/attachment.cgi?id=39231"
-  cd "$srcdir"
-
-  # Allow ccache to work
-  mv $_pkgname-$_pkgbasever $pkgname
-
-  # ncurses fix
-  sed -i 's|libncurses|libncursesw|g' "$srcdir/$_pkgname/configure"
-  sed -i 's|lncurses|lncursesw|g' "$srcdir/$_pkgname/configure"
-
-  # Get rid of old build dirs
-  rm -rf $_pkgname-{32,64}-build
-  mkdir $_pkgname-32-build
-
-  # These additional CPPFLAGS solve FS#27662 and FS#34195
-  export CPPFLAGS="${CPPFLAGS/-D_FORTIFY_SOURCE=2/} -D_FORTIFY_SOURCE=0"
-
-  if [[ $CARCH == x86_64 ]]; then
-    msg2 "Building Wine-64..."
-
-    mkdir $_pkgname-64-build
-    cd "$srcdir/$_pkgname-64-build"
-    ../$_pkgname/configure \
-      --prefix=/usr \
-      --libdir=/usr/lib \
-      --with-x \
-      --without-gstreamer \
-      --enable-win64
-    # Gstreamer was disabled for FS#33655
-
-    make
-
-    _wine32opts=(
-      --libdir=/usr/lib32
-      --with-wine64="$srcdir/$_pkgname-64-build"
-    )
-
-    export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
-  fi
-
-  msg2 "Building Wine-32..."
-  cd "$srcdir/$_pkgname-32-build"
-  ../$pkgname/configure \
-    --prefix=/usr \
-    --with-x \
-    --without-gstreamer \
-    "${_wine32opts[@]}"
-
-  # These additional flags solve FS#23277
-  make CFLAGS+="-mstackrealign -mincoming-stack-boundary=2" CXXFLAGS+="-mstackrealign -mincoming-stack-boundary=2"
+prepare() {
+  printf "Make sure to clean the sources directory otherwise the build may fail\n"
+  printf "Patching...\n"  
+  cp "${srcdir}/PKGBUILD_stock" "${srcdir}/PKGBUILD_temp"
+  patch "${srcdir}/PKGBUILD_temp" "${srcdir}/PKGBUILD.patch" -o "${srcdir}/PKGBUILD_new"
+  rm "${srcdir}/PKGBUILD_temp"
+  sed -i 's/pkgname/_pkgname/g;s/__pkgname/_pkgname/g;s/_pkgname=wine-photoshop/pkgname=wine-photoshop/g' "${srcdir}/PKGBUILD_new"
+  mv "${srcdir}/30-win32-aliases.conf" ../
+  mv "${srcdir}/wine.install" ../
+  mv "${srcdir}/PKGBUILD_new" ../PKGBUILD
+  printf "Please run makepkg again to build\n"
+  exit 1
 }
-
-package() {
-  depends=(${_depends[@]})
-
-  msg2 "Packaging Wine-32..."
-  cd "$srcdir/$_pkgname-32-build"
-
-  if [[ $CARCH == i686 ]]; then
-    make prefix="$pkgdir/usr" install
-  else
-    make prefix="$pkgdir/usr" \
-      libdir="$pkgdir/usr/lib32" \
-      dlldir="$pkgdir/usr/lib32/wine" install
-
-    msg2 "Packaging Wine-64..."
-    cd "$srcdir/$_pkgname-64-build"
-    make prefix="$pkgdir/usr" \
-      libdir="$pkgdir/usr/lib" \
-      dlldir="$pkgdir/usr/lib/wine" install
-  fi
-
-  # Font aliasing settings for Win32 applications
-  install -d "$pkgdir"/etc/fonts/conf.{avail,d}
-  install -m644 "$srcdir/30-win32-aliases.conf" "$pkgdir/etc/fonts/conf.avail"
-  ln -s ../conf.avail/30-win32-aliases.conf "$pkgdir/etc/fonts/conf.d/30-win32-aliases.conf"
-}
-
-# vim:set ts=8 sts=2 sw=2 et:
