updated on Tue Mar  8 09:00:52 PST 2011

diff --git a/janet/PKGBUILD b/janet/PKGBUILD
--- a/janet/PKGBUILD
+++ b/janet/PKGBUILD
@@ -1,8 +1,8 @@
 # Maintainer: Cody Lee <platinummonkey at archlinux dot us>
 
 pkgname=janet
-pkgver=0.1.3
-pkgrel=3
+pkgver=0.1.4
+pkgrel=1
 pkgdesc="A Digital life assistant (DLA) that provides a framework allowing various components to communicate, controlled interactively by the user and inspired by Iron Man's JARVIS."
 arch=('i686' 'x86_64')
 url="http://sites.google.com/site/projectjanet"
@@ -13,7 +13,7 @@ optdepends=('janet-addons: Additional plugins for jaNET'
 	    'htk: For customizing simon')
 install=
 source=("http://sourceforge.net/projects/project-janet/files/Binaries/Bin.tar.gz")
-md5sums=('8887b41d51df3c40b90918b662328ef7') #generate with 'makepkg -g'
+md5sums=('4221150b5a141b8f304665c429cb6254') #generate with 'makepkg -g'
 
 build() {
   cd $srcdir
@@ -30,6 +30,27 @@ package() {
 /usr/bin/mono /usr/share/$pkgname/jaNET.exe "\$\@"
 EOF
   chmod a+x /usr/bin/$pkgname
+  # create the push2server script
+  cat <<EOF >>/usr/bin/push2server
+#!/bin/bash
+
+# configuration
+HOST="localhost"
+PORT="5744"
+
+# try to connect
+if ! exec 5<> /dev/tcp/$HOST/$PORT; then
+  echo "`basename $0`: unable to connect to $HOST:$PORT"
+  exit 1
+else
+  echo $1 > /dev/tcp/$HOST/$PORT;
+fi
+EOF
   echo -e 'To set up the festival voice and simon configuration see: \n
-           https://wiki.archlinux.org/index.php/JaNET'
+           https://wiki.archlinux.org/index.php/JaNET\n
+           \n
+           jaNET 0.1.4 now comes with server mode! to enable it:\n
+              janet "judo server start"\n
+              Example: push2server "weathertoday"\n
+              or you can simply: echo "weathertoday" > /dev/tcp/<ip address>/5744'
 }
