updated on Sat Aug  9 00:00:19 UTC 2014

diff --git a/vdradmin-am/install.sh.patch b/vdradmin-am/install.sh.patch
--- a/vdradmin-am/install.sh.patch
+++ b/vdradmin-am/install.sh.patch
@@ -1,5 +1,5 @@
---- install.sh.orig	2011-11-19 07:02:18.000000000 +0000
-+++ install.sh	2012-05-02 21:28:49.676099315 +0100
+--- vdradmin-am-3.6.10-orig/install.sh	2014-08-05 06:37:33.000000000 +0100
++++ vdradmin-am-3.6.10/install.sh	2014-08-08 23:30:46.951875626 +0100
 @@ -102,10 +102,10 @@
  	checkPerlModule Digest::HMAC_MD5
  	echo "* Required if VDR and VDRAdmin-AM use different character encoding"
@@ -15,8 +15,24 @@
  	echo "* Required if you want to use gzip'ed HTTP responses"
  	checkPerlModule Compress::Zlib
  	echo "* Required if you want to log to syslog"
-@@ -168,67 +168,61 @@
- 		fi
+@@ -159,76 +159,70 @@
+ 		done
+ 	)
+ 
+-	local RESTART=
+-	if [ -d $BINDIR ]; then
+-		killRunningVDRAdmin
+-		if [ $? -ne 0 ] ; then
+-			RESTART=1
+-			echo "Killed running VDRAdmin-AM..."
+-		fi
++#	local RESTART=
++#	if [ -d $BINDIR ]; then
++#		killRunningVDRAdmin
++#		if [ $? -ne 0 ] ; then
++#			RESTART=1
++#			echo "Killed running VDRAdmin-AM..."
++#		fi
  		sed <vdradmind.pl >$BINDIR/vdradmind \
  		    -e "s/^\(my \$SEARCH_FILES_IN_SYSTEM *=\) 0;/\1 1;/" \
 -		    -e "s:/usr/share/vdradmin/lib:${LIBDIR}/lib:" \
@@ -28,7 +44,8 @@
 -		    -e "s:/usr/share/locale:${LOCDIR}:" \
  		    -e "s:\(\$CONFIG{VIDEODIR} *= \)\"/video\";:\1\"${VIDEODIR}\";:" \
  		    -e "s:\(\$CONFIG{EPGIMAGES} *= \)\"\$CONFIG{VIDEODIR}/epgimages\";:\1\"${EPGIMAGES}\";:" \
- 				-e "s:\(\$CONFIG{VDRCONFDIR} *= \)\"\$CONFIG{VIDEODIR}\";:\1\"${VDRCONF}\";:"
+-				-e "s:\(\$CONFIG{VDRCONFDIR} *= \)\"\$CONFIG{VIDEODIR}\";:\1\"${VDRCONF}\";:"
++			-e "s:\(\$CONFIG{VDRCONFDIR} *= \)\"\$CONFIG{VIDEODIR}\";:\1\"${VDRCONF}\";:"
  
  		chmod a+x  $BINDIR/vdradmind
  
@@ -53,6 +70,11 @@
 -				rm -f $MANDIR/$man
 -			fi
 -		done
+-	else
+-		echo "$BINDIR exists but is no directory!"
+-		echo "Aborting..."
+-		exit 1
+-	fi
 +#		if [ "$CONFIG" ]; then
 +#			echo "Configuring VDRAdmin-AM..."
 +#			$BINDIR/vdradmind -c
@@ -74,16 +96,16 @@
 +#				rm -f $MANDIR/$man
 +#			fi
 +#		done
- 	else
- 		echo "$BINDIR exists but is no directory!"
- 		echo "Aborting..."
- 		exit 1
- 	fi
++#	else
++#		echo "$BINDIR exists but is no directory!"
++#		echo "Aborting..."
++#		exit 1
++#	fi
  
--	echo ""
--	echo ""
--	echo "VDRAdmin-AM has been installed!"
--	echo ""
+ 	echo ""
+ 	echo ""
+ 	echo "VDRAdmin-AM has been installed!"
+ 	echo ""
 -	if [ -z "$RESTART" ]; then
 -		echo "Run \"$BINDIR/vdradmind\" to start VDRAdmin-AM."
 -		echo ""
@@ -101,10 +123,6 @@
 -	echo "$USED_DIRS"
 -	echo
 -	echo "Please check that the user VDRAdmin-AM runs has enough permissions to access them!"
-+#	echo ""
-+#	echo ""
-+#	echo "VDRAdmin-AM has been installed!"
-+#	echo ""
 +#	if [ -z "$RESTART" ]; then
 +#		echo "Run \"$BINDIR/vdradmind\" to start VDRAdmin-AM."
 +#		echo ""
@@ -114,7 +132,7 @@
 +#	echo ""
 +#	echo "NOTE2:"
 +#	echo "If you would like VDRAdmin-AM to start at system's boot, please modify your system's init scripts."
-+#
++
 +#	local USED_DIRS="$(echo -e "$ETCDIR\n$LOGDIR\n$CACHEDIR\n$(dirname "$PIDFILE")" | sort -u)"
 +#	echo
 +#	echo "NOTE3:"
@@ -125,12 +143,3 @@
  	exit 0
  }
  
-@@ -238,7 +232,7 @@
- 	echo "********* Uninstalling VDRAdmin-AM *************"
- 	echo ""
- 
--	killRunningVDRAdmin
-+#	killRunningVDRAdmin
- 	if [ -d $DOCDIR ]; then
- 		rm -rf $DOCDIR
- 	fi
