updated on Tue Aug 16 11:01:00 UTC 2011

diff --git a/vmware-patch/vmware-rc b/vmware-patch/vmware-rc
--- a/vmware-patch/vmware-rc
+++ b/vmware-patch/vmware-rc
@@ -5,7 +5,15 @@ daemon_name=vmware
 . /etc/rc.conf
 . /etc/rc.d/functions
 
-VMWARECTL=/etc/rc.d/vmware.d/init.d/vmware
+if [ -f /etc/rc.d/vmware.d/init.d/vmware ] ; then
+  VMWARECTL=/etc/rc.d/vmware.d/init.d/vmware
+elif [ -f /etc/rc.d/vmware ] ; then
+  VMWARECTL=/etc/rc.d/vmware
+else
+  echo -n "VMWare daemon startup script not found (/etc/rc.d/vmware or /etc/rc.d/vmware.d/init.d/vmware)"
+  stat_fail
+  exit 1
+fi
 
 case "$1" in
   start)
