updated on Sat Jan 31 00:00:18 UTC 2015

diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -161,7 +161,9 @@ for kernel in ${kernels[@]}; do
     fi
 
     # Unload conflicting in-kernel modules (VMware can't handle these in Arch)
-    rmmod "vsock" "vmw_vsock_vmci_transport" "vmw_vmci" 2>/dev/null || true
+    if [[ $ver != 11.* ]] && [[ $ver != 7.* ]]; then
+        rmmod "vsock" "vmw_vsock_vmci_transport" "vmw_vmci" 2>/dev/null || true
+    fi
 
     # Applicable patches (patches/[mod]-[ver]-[kernel].patch)
     unset patches
@@ -271,15 +273,25 @@ for kernel in ${kernels[@]}; do
     msg "Installing modules.."
     if [[ $verbose ]]; then
         if ! vmware-modconfig --console --install-all -k "$kernel"; then
-            error "Unable to build. See:"
-            print_logs
+            if [[ $ver = 11.* ]] || [[ $ver = 7.* ]]; then
+                modprobe vmw_vmci
+                msg2 "Done."
+            else
+                error "Unable to build. See:"
+                print_logs
+            fi
         else
             msg2 "Done."
         fi
     else
         if ! vmware-modconfig --console --install-all -k "$kernel" &>/dev/null; then
-            error "Unable to build. Re-run with '-v' (--verbose) or see:"
-            print_logs
+            if [[ $ver = 11.* ]] || [[ $ver = 7.* ]]; then
+                modprobe vmw_vmci
+                msg2 "Done."
+            else
+                error "Unable to build. Re-run with '-v' (--verbose) or see:"
+                print_logs
+            fi
         else
             msg2 "Done."
         fi
