updated on Fri Aug 12 11:00:59 UTC 2011

diff --git a/vmware-patch/vmware-unpatch b/vmware-patch/vmware-unpatch
--- a/vmware-patch/vmware-unpatch
+++ b/vmware-patch/vmware-unpatch
@@ -9,6 +9,24 @@ then
   exit 1
 fi
 
+echo "Reverting vmware modconfig libraries"
+for mod in `echo \
+/usr/lib/vmware/lib/libvmware-modconfig-console.so/libvmware-modconfig-console.so  \
+/usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so \
+`
+do
+  mv "${mod}".bak "${mod}"
+  res=$?
+  if [ $res -ne 0 ]
+  then
+    echo "Failed to revert "`basename ${mod}`
+  else
+    echo `basename ${mod}`" reverted successfully"
+  fi
+done
+
+
+
 SRC="/usr/lib/vmware/modules/source/"
 for mod in `ls $SRC*.tar-* | sed "s/.*\/\(.*\).tar-.*/\1/" | sort | uniq`
 do
