updated on Tue Apr 23 14:27:12 UTC 2013

diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -9,6 +9,10 @@ msg2() {
     printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
+read_msg2() {
+    read -p "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}"
+}
+
 msg3() {
     printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
@@ -130,20 +134,23 @@ if ls patches/*${VER}*${KERNEL}*.patch &>/dev/null; then
         # Untar
         tar -xf ${mod}.tar
         # Patch
-        msg2 "Patching ${mod}.."
+        msg2 "[${mod}] Patching.."
         # Shorten
         _patch=../patches/${mod}*${VER}*${KERNEL}*.patch
         if patch -p0 -s -f -i ${_patch}; then
-            msg3 "[${mod}] Succesfully patched."
+            msg3 "Succesfully patched."
         else  # Not gonna happen
-            error "[${mod}] Failed to apply '$(basename ${_patch})'."
-            msg "Reverting.."
-            # Revert
-            cd ..
-            rm -r source/
-            mv source-${VER}/ source/
-            msg "Done."
-            exit 1
+            error "Failed to apply '$(basename ${_patch})'."
+            read_msg2 "Continue? "
+            if [[ "$REPLY" != [Yy] ]]; then
+                msg "Reverting.."
+                # Revert
+                cd ..
+                rm -r source/
+                mv source-${VER}/ source/
+                msg "Done."
+                exit 1
+            fi
         fi
         # Tar patched modules
         tar -cf ${mod}.tar ${mod}-only
