updated on Fri Jan 27 10:01:09 UTC 2012

diff --git a/vmware-patch/vmware-unpatch b/vmware-patch/vmware-unpatch
--- a/vmware-patch/vmware-unpatch
+++ b/vmware-patch/vmware-unpatch
@@ -14,21 +14,22 @@ then
   exit 1
 fi
 
-echo "Reverting vmware modconfig libraries:"
-for mod in `echo \
-/usr/lib/vmware/lib/libvmware-modconfig-console.so/libvmware-modconfig-console.so  \
-/usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so \
-`
-do
-  mv "${mod}".bak "${mod}"
-  res=$?
-  if [ $res -ne 0 ]
-  then
-    echo "* Failed to revert "`basename ${mod}`" (or nothing to revert)"
-  else
-    echo "* "`basename ${mod}`" reverted successfully"
-  fi
-done
+#DEPRECATED SINCE VMWORKSTATION 8
+#echo "Reverting vmware modconfig libraries:"
+#for mod in `echo \
+#/usr/lib/vmware/lib/libvmware-modconfig-console.so/libvmware-modconfig-console.so  \
+#/usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so \
+#`
+#do
+#  mv "${mod}".bak "${mod}"
+#  res=$?
+#  if [ $res -ne 0 ]
+#  then
+#    echo "* Failed to revert "`basename ${mod}`" (or nothing to revert)"
+#  else
+#    echo "* "`basename ${mod}`" reverted successfully"
+#  fi
+#done
 
 echo "Reverting vmware modules source code:"
 
