updated on Sun Jun 22 00:06:32 UTC 2014

diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -40,21 +40,21 @@ YELLOW="${BOLD}$(tput setaf 3)"
 list_options() {
   msg "Available options:"
   msg2 "-f, --force:  Force reinstallation even, if modules have already been built."
-  msg2 "-h, --help:   View this help."
+  msg2 "-h, --help:   View this 'help' message."
 }
 
 # Don't continue with an unknown flag
-if [[ $@ = *-h* ]]; then
+if [[ "$@" = *-h* ]]; then
   list_options
   exit
-elif [ $1 ] && [[ $@ != *-f* ]]; then
+elif [ $1 ] && [[ "$@" != *-f* ]]; then
   error "Unknown option: $*"
   list_options
   exit 1
 fi
 
 # Make sure we are root
-if [ $UID != 0 ]; then
+if (( $EUID != 0 )); then
   error "This script needs to be run as root."
   exit 1
 fi
@@ -83,7 +83,7 @@ fi
 
 # Make sure there's a version in /etc/arch-release for versions prior to Workstation 10 / Player (Plus) 6:
 # https://wiki.archlinux.org/index.php?title=VMware&oldid=274532#2.29_The_vmware-usbarbitrator_binary_is_segfaulting
-if [[ $ver != 6.0.? ]] && [[ $ver != 10.0.? ]]; then
+if [[ "$ver" != 6.0.? ]] && [[ "$ver" != 10.0.? ]]; then
   if [ ! $(cat /etc/arch-release) ]; then
     msg "Updating /etc/arch-release.."
     curl -s https://www.archlinux.org/releng/releases/ | grep -Pom1 'for \K[^"]*' > /etc/arch-release
@@ -100,9 +100,9 @@ fi
 # Symlink version.h, if: 1) We don't have one already
 if [ ! -f /usr/src/linux-$(uname -r)/include/linux/version.h ]; then
   # 2) Installed Workstation/Player less than 9.0.2/5.0.2
-  if [[ $ver != [59].0.2 ]] && [[ $ver != 6.* ]] && [[ $ver != 10.* ]]; then
+  if [[ "$ver" != [59].0.[234] ]] && [[ "$ver" != 6.* ]] && [[ "$ver" != 10.* ]]; then
     # 3) Kernel version 3.5 or above
-    if (( $(echo $kernel | tr -d .) >= 35 )); then
+    if (( $(echo "$kernel" | tr -d .) >= 35 )); then
       msg "Symlinking version.h for $(uname -r)"
       install -d /usr/src/linux-$(uname -r)/include/linux/
       ln -s /usr/src/linux-$(uname -r)/include/generated/uapi/linux/version.h \
@@ -114,32 +114,37 @@ fi
 # Remove leftover header locations
 if [[ $(find /usr/src/ -mindepth 1 -maxdepth 2 -type d) ]]; then
   for i in /usr/src/*; do
-    if [[ $(ls $i) = include ]]; then
-      msg_yellow "Removing leftover header location $i/"
-      rm -r $i
+    if [[ $(ls "$i") = include ]]; then
+      msg_yellow "Removing leftover header location: $i/"
+      rm -r "$i"
     fi
   done
 fi
 
 # Remove leftover module locations
 for i in /usr/lib/modules/*; do
-  if [[ $(ls $i) = misc ]]; then
-    msg_yellow "Removing leftover module location $i/"
-    rm -r $i
+  if [[ $(ls "$i") = misc ]]; then
+    msg_yellow "Removing leftover module location: $i/"
+    rm -r "$i"
   fi
 done
 
 # Remove old backups
 cd /usr/lib/vmware/modules/
 # Use "ls" instead of the builtin -d for multiple arguments
-if ls -d source?*/ |& grep -qvx source-$ver/; then
+if ls -d source-*.*/ 2>/dev/null | grep -qv "$ver/"; then
   msg "Cleaning up old backups.."
-  # 1) Print full paths
-  # 2) Sed: leave out the first result containing $ver
-  for i in $(readlink -f source?*/ | sed "0,/$ver/{//d}"); do
-    msg2 "Removing $i"
+  # Print full paths
+  for i in $(readlink -f source-*.*/ | grep -v "$ver"); do
+    msg2 "Removing leftover module source location: $i/"
     rm -r "$i"
   done
+fi
+
+# Make sure the directory exists
+if [ ! -d /usr/lib/modules/$(uname -r)/ ]; then
+  error "/usr/lib/modules/$(uname -r)/ not found. Exiting.."
+  exit 1
 fi
 
 # Support the '-f' flag
@@ -147,7 +152,7 @@ fi
 # 2) Don't check this until we've removed the leftovers
 if [ -f /usr/lib/modules/$(uname -r)/misc/vsock.ko ]; then
   # Offer the ability reinstall this thing
-  if [[ $@ = -f ]]; then
+  if [[ "$@" = *-f* ]]; then
     msg "Reinstalling modules.."
   else
     error "VMware modules already installed (use -f to override). Exiting.."
@@ -159,43 +164,43 @@ fi
 # 1) Make sure we can build
 # 2) Shorther without double brackets ("[["):
 # 3) &>/dev/null: hide all output (STDIN/STDERR)
-if ls patches/*$ver*$kernel*.patch &>/dev/null; then
+if ls patches/*"$ver"*"$kernel"*.patch &>/dev/null; then
   # Create a backup/Revert
-  if [ ! -d source-$ver ]; then
+  if [ ! -d "source-$ver" ]; then
     msg "Creating a backup.."
-    cp -r source/ source-$ver/
+    cp -r source/ "source-$ver/"
   else  # Get the original sources from the backup (invalidate the need for 'vmware-unpatch')
-    cp source-$ver/* source/
+    cp "source-$ver/"* source/
   fi
   # Loop modules that require patching (vmblock, vmci, vmmon, vmnet and/or vsock)
   msg "Patching $name v$ver for kernel $(uname -r).."
   cd source
   # Prevent duplicate entries with 'sort -u'
-  for mod in $(ls ../patches/v*$ver*$kernel*.patch 2>&- | grep -Po "s/\K[^-]*" | sort -u); do
+  for mod in $(ls ../patches/v*"$ver"*"$kernel"*.patch 2>&- | grep -Po "s/\K[^-]*" | sort -u); do
     # Untar
-    tar -xf $mod.tar
+    tar -xf "$mod.tar"
     # Patch
     msg2 "[$mod]"
     # Loop through all patches
-    for i in ../patches/$mod*$ver*$kernel*.patch; do
+    for i in ../patches/"$mod"*"$ver"*"$kernel"*.patch; do
       if ! patch -p0 -s -f -i $i; then
-        error "Failed to apply '$(basename $i)'"
+        error "Failed to apply '$(basename "$i")'"
         read_msg2 "Continue? (Y/n) "
         if [[ "$REPLY" != [Yy] ]]; then
           # Revert
           msg "Reverting.."
           cd ..
           rm -r source/
-          mv source-$ver/ source/
+          mv "source-$ver/" source/
           msg "Done."
           exit 1
         fi
       fi
     done
     # Tar patched modules
-    tar -cf $mod.tar $mod-only
+    tar -cf "$mod.tar" "$mod-only"
     # Leftovers
-    rm -r $mod-only
+    rm -r "$mod-only"
   done
 else
   msg "No patching required."
