updated on Wed Jun 19 12:14:24 UTC 2013

diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -21,16 +21,28 @@ msg3() {
     printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
+info_yellow() {
+    printf "${YELLOW}$1${ALL_OFF}${BOLD} $2${ALL_OFF}\n"
+}
+
 error() {
     printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
+# Variables for them
 ALL_OFF="$(tput sgr0)"
 BOLD="$(tput bold)"
 BLUE="${BOLD}$(tput setaf 4)"
 GREEN="${BOLD}$(tput setaf 2)"
 RED="${BOLD}$(tput setaf 1)"
 YELLOW="${BOLD}$(tput setaf 3)"
+
+# Don't continue with an unknown flag
+if [[ "$@" ]] && [[ "$@" != '-f' ]]; then
+    error "Unknown option: $*"
+    info_yellow "Available options:" "-f (force reinstallation even, if modules have already been built)."
+    exit 1
+fi
 
 # Make sure we are root
 if [ $(whoami) != "root" ]; then
@@ -42,6 +54,13 @@ fi
 if [ ! -f /usr/bin/vmware-installer ]; then
     error "No VMware product found. Exiting.."
     exit 1
+fi
+
+# Warn about gtkmm 2.24.3-1
+if [[ $(pacman -Q gtkmm | cut -d " " -f2) = 2.24.3-1 ]]; then
+    warning "Gtkmm 2.24.3-1 found. This will make VMware segfault on startup.
+             The previous one (2.24.2-2) can be found in, e.g.:
+             http://hive.ist.unomaha.edu/archlinux-backup/pool/packages/"
 fi
 
 # Set some variables (|&: hide "No protocol specified" in KDE by redirecting all output to cut/grep)
@@ -64,7 +83,7 @@ fi
 # https://wiki.archlinux.org/index.php/Vmware#2.29_The_vmware-usbarbitrator_binary_is_segfaulting
 if [ ! $(cat /etc/arch-release) ]; then
     msg "Updating /etc/arch-release.."
-    echo 2013.04.01 > /etc/arch-release
+    echo 2013.06.01 > /etc/arch-release
 fi
 
 # Prepare for /bin, /sbin, /usr/sbin -> /usr/bin move, if necessary (discard symlinks from /sbin): 
@@ -166,6 +185,7 @@ if [ -f /usr/lib/modules/$(uname -r)/misc/vsock.ko ]; then
         exit 1
     else
         error "Unknown option: $*"
+        info_yellow "Available options:" "-f (force reinstallation even, if modules have already been built)."
         exit 1
     fi
 fi
@@ -189,14 +209,12 @@ if ls patches/*${VER}*${KERNEL}*.patch &>/dev/null; then
         # Untar
         tar -xf ${mod}.tar
         # Patch
-        msg2 "[${mod}] Patching.."
+        msg2 "${mod}"
         # Shorten
         _patch=../patches/${mod}*${VER}*${KERNEL}*.patch
-        if patch -p0 -s -f -i ${_patch}; then
-            msg3 "Successfully patched."
-        else  # Not gonna happen
-            error "Failed to apply '$(basename ${_patch})'."
-            read_msg2 "Continue? "
+        if ! patch -p0 -s -f -i ${_patch}; then
+            error "Failed to apply '$(basename ${_patch})'"
+            read_msg2 "Continue? (Y/n) "
             if [[ "$REPLY" != [Yy] ]]; then
                 msg "Reverting.."
                 # Revert
