updated on Sun Nov 16 00:00:48 UTC 2014

diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -1,45 +1,7 @@
 #!/bin/bash -e
 
-# Some colored makepkg-like functions
-msg() {
-    printf "${green}==>${bold} $1${all_off}\n"
-}
-
-msg_yellow() {
-    printf "${yellow}==>${bold} $1${all_off}\n"
-}
-
-msg2() {
-    printf "${blue}  ->${bold} $1${all_off}\n"
-}
-
-msg2_yellow() {
-    printf "${yellow}  ->${bold} $1${all_off}\n"
-}
-
-read_msg2() {
-    read -p "${blue}  ->${bold} $1${all_off}"
-}
-
-msg3() {
-    printf "${yellow}    ->${bold} $1${all_off}\n"
-}
-
-error() {
-    printf "${red}==> error:${bold} $1${all_off}\n"
-}
-
-error2() {
-    printf "${red}    *${bold} $1${all_off}\n"
-}
-
-# Colors
-all_off="$(tput sgr0)"
-bold="${all_off}$(tput bold)"
-blue="${bold}$(tput setaf 4)"
-green="${bold}$(tput setaf 2)"
-red="${bold}$(tput setaf 1)"
-yellow="${bold}$(tput setaf 3)"
+# Source common functions
+. /usr/share/vmware-patch/common-functions.sh
 
 # Help message
 usage() {
@@ -47,46 +9,41 @@ usage() {
     echo "Automate the compilation of VMware modules for Arch Linux."
     echo
     echo "Available options:"
-    echo "  -f, --force       Force reinstallation even, if modules already built"
-    echo "  -v, --verbose     Use verbose output (patching, vmware-modconfig)"
-    echo "  -V, --version     Print version information"
-    echo "  -h, --help        Print this help"
-}
-
-# Version information
-version() {
-    echo "$(basename $0) $(pacman -Q vmware-patch | cut -d ' ' -f2)"
-    echo "Copyright (c) 2013-2014  Nobody"
-    echo
-    echo "THIS SCRIPT IS PROVIDED AS-IS FOR ANY PURPOSE WHATSOEVER. YOU ARE FREE TO SHARE IT, MODIFY IT,"
-    echo "TAKE CREDIT OF IT, AND SELL IT ON THE STREETS."
-    echo
-    echo "FIGHT THE POWER."
+    echo "  -a, --all           Build for all kernels" 
+    echo "  -f, --force         Force reinstallation even, if modules already built"
+    echo "  -k, --kernel        Select which kernel(s) to build to" 
+    echo "  -v, --verbose       Use verbose output (patching, vmware-modconfig)"
+    echo "  -V, --version       Print version information"
+    echo "  -h, --help          Print this help"
 }
 
 # Flags
-while [[ "$1" ]]; do
+while [[ $1 ]]; do
     # Can't change $1
-    opt="$1"
+    opt=$1
+
     # Parse current one
-    while [[ "$opt" != "-" ]]; do
+    while [[ $opt != - ]]; do
         # Define actions
-        case "$opt" in
-            -f* | --force)     force=1 ;;
-            -v* | --verbose)   verbose=1 ;;
-            -V* | --version)   version; exit 0 ;;
-            -h* | --help)      usage; exit 0 ;;
-            -*)                echo "$(basename $0): error: bad argument: $opt"
-                               echo
-                               usage $1; exit 0 ;;
+        case $opt in
+            -a* | --all-kernels)  all=1 ;;
+            -f* | --force)        force=1 ;;
+            -k* | --kernel)       kernel=1 ;; 
+            -v* | --verbose)      verbose=1 ;;
+            -V* | --version)      print_version; exit 0 ;;
+            -h* | --help)         usage; exit 0 ;;
+            -*)                   echo "$(basename $0): error: bad argument: $opt"
+                                  echo
+                                  usage $1; exit 0 ;;
             *) break ;;
         esac
-        # Support single dash (-fv)
-        # Remove first match ("${opt#-[fv]}")
-        nextopt="${opt#-[fv]}"
-        if [[ "$opt" != "$nextopt" ]]; then
+
+        # Support single dash (vmware-patch -fv)
+        # ${opt#-:[*]}: Remove first match
+        nextopt=${opt#-[afkv]}
+        if [[ $opt != $nextopt ]]; then
             # Multiple short flags
-		        opt="-$nextopt"
+		    opt=-$nextopt
         else
             # Long form (--force/--verbose)
             break
@@ -96,25 +53,13 @@ while [[ "$1" ]]; do
 done
 
 # Make sure we are root
-if (( $EUID != 0 )); then
-    error "This script needs to be run as root."
-    exit 1
-fi
+root_check
 
 # Is a VMware product installed?
-if [[ ! -f /usr/bin/vmware-installer ]]; then
-    error "No VMware product found. Exiting.."
-    exit 1
-fi
+vmware_check
 
-# Set some variables (|&: hide errors by redirecting all output)
-kernel=$(uname -r | cut -d "." -f-2)
-ver=$(vmware-installer -l |& grep -Po "(player|workstation) *\K(\d+\.){2}\d+")
-if vmware-installer -l |& grep -q "workstation"; then
-    name="VMware Workstation"
-else
-    name="VMware Player (Plus)"
-fi
+# Product name
+set_product_name
 
 # Make sure vmware.service includes our USB Arbitrator service
 if ! grep -q "usbarbitrator" /usr/lib/systemd/system/vmware.service; then
@@ -125,7 +70,7 @@ fi
 
 # Make sure there's a version in /etc/arch-release for Workstation 9 / Player 5
 # https://wiki.archlinux.org/index.php?title=VMware&oldid=274532#2.29_The_vmware-usbarbitrator_binary_is_segfaulting
-if [[ "$ver" = 9.* ]] || [[ "$ver" = 5.* ]]; then
+if [[ $ver = 9.* ]] || [[ $ver = 5.* ]]; then
     if [[ ! $(cat /etc/arch-release) ]]; then
         msg "Updating /etc/arch-release.."
         curl -s https://www.archlinux.org/releng/releases/ | grep -Pom1 'for \K[^"]*' > /etc/arch-release
@@ -140,143 +85,203 @@ if grep -q '$vsock_alias' /etc/init.d/vmware; then
 fi
 
 # Remove leftover module locations
-for i in /usr/lib/modules/*; do
-    if [[ $(ls "$i") = 'misc' ]]; then
-        misc+=("$i")
-    fi
-done
-if [[ "$misc" ]]; then
-    msg_yellow "Removing leftover module location.."
-    for i in ${misc[@]}; do
-        msg2 "$i/"
-        rm -r "$i"
-    done
-fi
+remove_leftover_module_dirs
+
+cd /usr/lib/vmware/modules/
 
 # Remove old backups
-cd /usr/lib/vmware/modules/
-# Use "ls" instead of the builtin -d for multiple arguments
-if ls -d source-*.*/ 2>/dev/null | grep -qv "$ver/"; then
-    msg_yellow "Cleaning up old backups.."
-    # Print full paths
-    for i in $(readlink -f source-*.*/ | grep -v "$ver"); do
-        msg2 "$i/"
-        rm -r "$i"
+remove_old_backups
+
+# Available kernels
+kernels_all=($(cat /usr/lib/modules/extramodules-*/version))
+
+# Select kernel from menu
+menu() {
+    # Don't show previous menu
+    clear
+
+    # Menu
+    echo "Select kernels for which to build modules (leave empty for current kernel):"
+    for i in ${!kernels_all[@]}; do 
+        printf "%3d%s) %s\n" "$((i+1))" "${choices[i]:- }" "${kernels_all[i]}"
     done
-fi
-
-# Make sure the directory exists
-if [[ ! -d /usr/lib/modules/$(uname -r)/ ]]; then
-    error "/usr/lib/modules/$(uname -r)/ not found. Exiting.."
-    exit 1
-fi
-
-# Support the '-f' flag
-# 1) Have we already built (vsock is built last)?
-# 2) Don't check this until we've removed the leftovers
-if [[ ! "$force" ]] && [[ -f /usr/lib/modules/$(uname -r)/misc/vsock.ko ]]; then
-    if [[ "$verbose" ]]; then
-        msg "Verifying current state.."
-    fi
-    error "VMware modules already installed (use '-f' to override). Exiting.."
-    exit 1
-fi
-
-# Unload conflicting in-kernel modules (VMware can't handle these in Arch)
-if rmmod vmw_vsock_vmci_transport 2>/dev/null; then
-    rmmod vmw_vmci vsock 2>/dev/null
-fi
-
-# Patch
-# 1) Make sure we can build
-# 2) &>/dev/null: hide all output (STDIN/STDERR)
-msg "Patching $name v$ver for kernel $(uname -r).."
-if ls patches/*"$ver"*"$kernel"*.patch &>/dev/null; then
-    # Create a backup/Revert
-    if [[ ! -d "source-$ver" ]]; then
-        msg2_yellow "Backing up.."
-        cp -r source/ "source-$ver/"
-    else
-        # Get the original sources from the backup (invalidate the need for 'vmware-unpatch')
-        cp "source-$ver/"* source/
-    fi
-
-    cd source
-    # Loop modules that require patching (vmci, vmmon, vmnet and/or vsock)
-    # sort -u: prevent duplicate entries with
-    for mod in $(ls ../patches/v*"$ver"*"$kernel"*.patch 2>&- | grep -Po "s/\K[^-]*" | sort -u); do
-        # Print name
-        msg2 "[$mod]"
-
-        # Untar
-        if [[ "$verbose" ]]; then
-            msg3 "Extracting archives.."
-        fi
-        tar -xf "$mod.tar"
-
-        # Patch function
-        _patch() {
-            if [[ "$verbose" ]]; then
-                msg3 "Patching.."
-                patch -p0 -f -i "$i"
-            else
-                patch -p0 -s -f -i "$i"
-            fi
-        }
-
-        # Loop through all patches
-        for i in ../patches/"$mod"*"$ver"*"$kernel"*.patch; do
-            # Patch
-            if ! _patch; then
-                error "Failed to apply '$(basename "$i")'"
-                read_msg2 "Continue? (Y/n) "
-                if [[ "$REPLY" != [Yy] ]]; then
-                    # Revert
-                    msg "Reverting.."
-                    cd ..
-                    rm -r source/
-                    mv "source-$ver/" source/
-
-                    # Exit
-                    msg2 "Done."
-                    exit 1
-                fi
-            fi
-        done
-
-        # Tar patched modules
-        if [[ "$verbose" ]]; then
-            msg3 "Recreating archives.."
-        fi
-        tar -cf "$mod.tar" "$mod-only"
-
-        # Leftovers
-        rm -r "$mod-only"
-    done
-else
-    msg2 "No patching required.."
-fi
-
-# Print 'vmware-modconfig-*.log's and exit
-print_logs() {
-    for i in /tmp/vmware-root/vmware-modconfig-*.log; do
-        error2 "$i"
-    done
-    exit 1
 }
 
-# Install
-msg "Installing modules.."
-if [[ "$verbose" ]]; then
-    if ! vmware-modconfig --console --install-all; then
-        error "Unable to build. See:"
-        print_logs
+# Wrapper function
+list_kernels() {
+    # Wait for Enter
+    while menu && read -rp "Press Enter when done: " num && [[ $num ]]; do
+        # Select correct item
+        (( num -- ))
+
+        # Set plus mark (+)
+        if [[ ${choices[num]} ]]; then
+            choices[num]=""
+        else
+            choices[num]="+"
+        fi
+    done
+
+    # Chosen kernels
+    for i in ${!kernels_all[@]}; do 
+        if [[ ${choices[i]} ]]; then
+            kernels+=("${kernels_all[i]}")
+        fi
+    done
+}
+
+# Kernel(s) to build to
+if [[ ! $all ]]; then
+    if [[ ! $kernel ]]; then
+        kernels=$(uname -r)
+    else
+        list_kernels
     fi
 else
-    if ! vmware-modconfig --console --install-all &>/dev/null; then
-        error "Unable to build. Re-run with '-v' (--verbose) or see:"
-        print_logs
-    fi
+    kernels=${kernels_all[@]}
 fi
 
-msg2 "Done."
+# Build for however many kernels specified
+for kernel in ${kernels[@]}; do
+    # Make sure the directory exists
+    if [[ ! -d /usr/lib/modules/$kernel/ ]]; then
+        error "/usr/lib/modules/$kernel/ not found. Exiting.."
+        exit 1
+    fi
+
+    # Support the '-f' flag
+    # 1) Have we already built (vsock is built last)?
+    # 2) Don't check this until we've removed the leftovers
+    if [[ ! $force ]] && [[ -f /usr/lib/modules/$kernel/misc/vsock.ko ]]; then
+        if [[ $verbose ]]; then
+            msg "Verifying current state.."
+        fi
+        error "VMware modules already installed (use '-f' to override). Exiting.."
+        exit 1
+    fi
+
+    # Unload conflicting in-kernel modules (VMware can't handle these in Arch)
+    rmmod "vsock" "vmw_vsock_vmci_transport" "vmw_vmci" 2>/dev/null || true
+
+    # Applicable patches (patches/[mod]-[ver]-[kernel].patch)
+    unset patches
+    for patch in patches/*; do
+        ver_patch=$(echo $patch | cut -d "-" -f2)
+        kernel_patch=$(echo $patch | grep -Po ".*-\K\d+\.\d+")
+        kernel_major=$(echo $kernel | cut -d "." -f-2)
+
+        # Sync VMware Player (Plus) version by incrementing by 4
+        ver2=$ver
+        if [[ $name =~ Player ]]; then
+            major=$(( ${ver/.*} + 4 ))
+            ver2=$major.${ver#*.}
+        fi
+
+        # Is product version not lower and kernel version not higher in patch name?
+        if (( $(vercmp "$ver_patch" "$ver2") >= 0 )) && (( $(vercmp "$kernel_patch" "$kernel_major") <= 0 )); then
+            patches+=("$patch")
+        fi
+    done
+
+    # Patch
+    # 1) Make sure we can build
+    # 2) &>/dev/null: hide all output (STDIN/STDERR)
+    msg "Patching $name v$ver for kernel $kernel.."
+    if [[ $patches ]]; then
+        # Create a backup/Revert
+        if [[ ! -d source-$ver ]]; then
+            msg2_yellow "Backing up.."
+            cp -r source/ "source-$ver/"
+        else
+            # Get the original sources from the backup (invalidate the need for 'vmware-unpatch')
+            cp "source-$ver/"* source/
+        fi
+
+        # cd in place
+        cd source
+
+        # Loop modules that require patching (vmci, vmmon, vmnet and/or vsock)
+        # sort -u: prevent duplicate entries
+        for mod in $(echo ${patches[@]} | grep -Po "s/\K[^-]*" | sort -u); do
+            # Print name
+            msg2 "[$mod]"
+
+            # Untar
+            if [[ $verbose ]]; then
+                msg3 "Extracting archives.."
+            fi
+            tar -xf "$mod.tar"
+
+            # Patch function
+            patch_sources() {
+                if [[ $verbose ]]; then
+                    msg3 "Patching.."
+                    patch -p0 -f -i "../$patch"
+                else
+                    patch -p0 -s -f -i "../$patch"
+                fi
+            }
+
+            # Loop through applicable patches
+            # printf '%s\n': print ${patches[@]} in separate lines for grepping
+            for patch in $(printf '%s\n' "${patches[@]}" | grep "$mod"); do
+                # Patch
+                if ! patch_sources; then
+                    error "Failed to apply '$(basename "$patch")'"
+                    read_msg2 "Continue? (Y/n) "
+                    if [[ $REPLY != [Yy] ]]; then
+                        # Revert
+                        msg "Reverting.."
+                        cd ..
+                        rm -r source/
+                        mv "source-$ver/" source/
+
+                        # Exit
+                        msg2 "Done."
+                        exit 1
+                    fi
+                fi
+            done
+
+            # Tar patched modules
+            if [[ $verbose ]]; then
+                msg3 "Recreating archives.."
+            fi
+            tar -cf "$mod.tar" "$mod-only"
+
+            # Leftovers
+            rm -r "$mod-only"
+        done
+
+        # Return
+        cd ..
+    else
+        msg2 "No patching required.."
+    fi
+
+    # Print 'vmware-modconfig-*.log's and exit
+    print_logs() {
+        for log in /tmp/vmware-root/vmware-modconfig-*.log; do
+            error2 "$log"
+        done
+        exit 1
+    }
+
+    # Install
+    msg "Installing modules.."
+    if [[ $verbose ]]; then
+        if ! vmware-modconfig --console --install-all -k "$kernel"; then
+            error "Unable to build. See:"
+            print_logs
+        else
+            msg2 "Done."
+        fi
+    else
+        if ! vmware-modconfig --console --install-all -k "$kernel" &>/dev/null; then
+            error "Unable to build. Re-run with '-v' (--verbose) or see:"
+            print_logs
+        else
+            msg2 "Done."
+        fi
+    fi
+done
