updated on Fri Sep 20 22:24:16 UTC 2013

diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -189,26 +189,27 @@ if ls patches/*${VER}*${KERNEL}*.patch &>/dev/null; then
     # Loop modules that require patching (vmblock, vmci, vmmon, vmnet and/or vsock)
     msg "Patching ${NAME} v${VER} for kernel $(uname -r).."
     cd source
-    for mod in $(ls ../patches/*${VER}*${KERNEL}*.patch | cut -d "/" -f3 | cut -d "-" -f1); do
+    for mod in $(ls ../patches/*${VER}*${KERNEL}*.patch | cut -d "/" -f3 | cut -d "-" -f1 | head -1); do
         # Untar
         tar -xf ${mod}.tar
         # Patch
-        msg2 "${mod}"
-        # Shorten
-        _patch=../patches/${mod}*${VER}*${KERNEL}*.patch
-        if ! patch -p0 -s -f -i ${_patch}; then
-            error "Failed to apply '$(basename ${_patch})'"
-            read_msg2 "Continue? (Y/n) "
-            if [[ "$REPLY" != [Yy] ]]; then
-                # Revert
-                msg "Reverting.."
-                cd ..
-                rm -r source/
-                mv source-${VER}/ source/
-                msg "Done."
-                exit 1
+        msg2 "[${mod}]"
+        # Loop through all patches
+        for i in ../patches/${mod}*${VER}*${KERNEL}*.patch; do
+            if ! patch -p0 -s -f -i $i; then
+                error "Failed to apply '$(basename $i)'"
+                read_msg2 "Continue? (Y/n) "
+                if [[ "$REPLY" != [Yy] ]]; then
+                    # Revert
+                    msg "Reverting.."
+                    cd ..
+                    rm -r source/
+                    mv source-${VER}/ source/
+                    msg "Done."
+                    exit 1
+                fi
             fi
-        fi
+        done
         # Tar patched modules
         tar -cf ${mod}.tar ${mod}-only
         rm -r ${mod}-only
