updated on Mon Jan 13 00:41:53 UTC 2014

diff --git a/libreoffice-rpm/PKGBUILD b/libreoffice-rpm/PKGBUILD
--- a/libreoffice-rpm/PKGBUILD
+++ b/libreoffice-rpm/PKGBUILD
@@ -1,7 +1,8 @@
 # Contributor: Red_Squirrel <evangelion87d@gmail.com>
 # Contributor: Xavier114fch <xavier114fch@gmail.com>
-# Contributor: Mark E. Lee <mark@markelee.com>
-# Maintainer : Mark E. Lee <mark@markelee.com>
+# Contributor: nachoig      <areta@outlook.com.br>
+# Contributor: Mark E. Lee  <mark@markelee.com>
+# Maintainer : Mark E. Lee  <mark@markelee.com>
 
 ## Changelog :
 ## changed build function to package function (since nothing is built)
@@ -30,29 +31,36 @@
 ## updated to upstream 4.1.2
 ## updated to upstream 4.1.3
 ## updated to upstream 4.1.4
+## switched to sha256 sums + PGP sigs (see mailing list : <https://mailman.archlinux.org/pipermail/arch-general/2014-January/034744.html>)
+## using custom linux kernel version check in package() due usage of custom kernels (the issue was brought up by nachoig, the fix was from Mark E. Lee)
 
 pkgname=libreoffice-rpm
 pkgver=4.1.4
-pkgrel=1
+pkgrel=2
 pkgdesc="LGPL Office Suite installed from rpms"
 arch=('i686' 'x86_64')
 url='http://www.libreoffice.org'
 license=('LGPL')
-depends=('glibc>=2.5' 'gtk2>=2.10.4' 'linux>=2.6.18' 'xorg-server')
+depends=('glibc>=2.5' 'gtk2>=2.10.4' 'xorg-server')
 makedepends=('wget' 'awk')
 optdepends=('jre7-openjdk' 'gtk3' 'gnome')
 
 if [ "$(uname -m)" == "i686" ]; then  ## convert bit architecture to libreoffice format
   arch_mod='x86';
-  md5sums+=('e2a1b64d8adff23c40b0de20f090396a');
-  source+=("http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm.tar.gz")
+  sha256sums+=('f90add3bd162df6816bbd1dd84866154454e7a081fc149fde35b15a6fffd710f'
+              'SKIP');
+  source+=("https://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm.tar.gz"
+           "https://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm.tar.gz.asc")
  else
   arch_mod='x86_64';
-  md5sums+=('cfdde4f220f34037d38072e8de252bd5')
-  source+=("http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm.tar.gz")
+  sha256sums+=('2c88fbc3738f07ac332782d0d238233b0b4ab6cf3866b68d048690bbd2595874'
+              'SKIP')
+  source+=("https://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm.tar.gz"
+           "https://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm.tar.gz.asc")
 fi;
 
 prepare() { ## prepare function
+
 ## install optional language & help packs (queries user)
 wget -q "http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/";  ## get index.html
 declare -ar opt_pak=('langpack' 'helppack');  ## declare optional extensions
@@ -66,14 +74,14 @@ for a in ${opt_pak[@]}; do  ## loop for all optional extensions
          ## download the rpm package
          msg "Retrieving LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz...";
          wget "http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz";
-         ## download the rpm md5
-         wget -q "http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz.md5"
-         ## check the md5sum for the package
+         ## download the rpm sha256
+         wget -q "http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz.sha256"
+         ## check the sha256 sum for the package
          msg "Done";
-         msg "Validating LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz with md5sum..."
-         md5sum -c "LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz.md5"
-         if [ ! $? -eq 0 ]; then  ## check the md5sum error
-            echo "Failed md5sum check for http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz";
+         msg "Validating LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz with sha256sum..."
+         sha256sum -c "LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz.sha256"
+         if [ ! $? -eq 0 ]; then  ## check the sha256sum error
+            echo "Failed sha256sum check for http://download.documentfoundation.org/libreoffice/stable/${pkgver}/rpm/${arch_mod}/LibreOffice_${pkgver}_Linux_${arch_mod/_/-}_rpm_${a}_${opt_ext}.tar.gz";
             exit;
           else
             msg "Done";
@@ -97,6 +105,16 @@ done;
 }
 
 package() {   ## package function
+
+## check kernel version to allow arbitrarily patched kernels
+## need to be above linux 2.6.18 = 20618
+## pad the middle digit with two digits since Torvalds doesn't want to go past 99 in kernel versions and to ensure the check works
+min_kern_ver=20618;
+kern_ver=$(uname -r | awk -F'-' '{print $1}' | awk -F'.' '{print $1"0"$2$3}');
+if [ $kern_ver -lt $min_kern_ver ]; then
+   msg "The kernel version needs to be at least 2.6.18. The current kernel version is $(uname -r). Please update your linux kernel";
+   exit;
+fi;
 
 cd ${srcdir};  ## enter the package source directory
 ## extract rpms and install them
