updated on Thu Dec 20 18:00:03 UTC 2012

diff --git a/spaz-hib/PKGBUILD b/spaz-hib/PKGBUILD
--- a/spaz-hib/PKGBUILD
+++ b/spaz-hib/PKGBUILD
@@ -8,37 +8,39 @@ pkgdesc='Space Pirates and Zombies, a top-down space combat game (Humble Bundle 
 url='http://spacepiratesandzombies.com/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
-depends=('gcc-libs' 'libgl' 'sdl' 'openal' 'alsa-lib')
-optdepends=('alsa-plugins: PulseAudio support'
-            'libpulse: PulseAudio support')
-if [ $CARCH == x86_64 ]; then
+if [ $CARCH == i686 ]; then
+  depends=('gcc-libs' 'libgl' 'sdl' 'openal' 'alsa-lib')
+  optdepends=('alsa-plugins: PulseAudio support'
+              'libpulse: PulseAudio support')
+else
   depends=('lib32-gcc-libs' 'lib32-libgl' 'lib32-sdl' 'lib32-openal' 'lib32-alsa-lib')
   optdepends=('lib32-alsa-plugins: PulseAudio support'
               'lib32-libpulse: PulseAudio support')
 fi
 source=('spaz-hib.desktop')
-md5sums=('9fc788b38bb5d21f63f97913734d3db0')
+md5sums=('544fa2a99bc3d4733909e18f2df6515d')
 PKGEXT='.pkg.tar'
 
-_gamepkg="spaz-linux-humblebundle-${_hibver}-bin"
-
+_archive="spaz-linux-humblebundle-${_hibver}-bin"
+_archive_md5='9b2f28009949f2dff9f3a737e46fabfd'
 
 package() {
   cd $srcdir
 
   # Get installer
-  _get_humblebundle_source "${_gamepkg}" || {
+  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
     error "Unable to find the game archive. Please download it from your Humble
            Bundle page, and place it into one of the above locations."
     exit 1; }
 
   # Extract the installer
-  unzip -o "${_gamepkg}" || true
+  unzip -o "${_archive}" || true
 
-#   # Remove bundled libraries (to force usage of system libs instead)
+  # Remove bundled libraries (to force usage of system libs instead)
   rm -rf $srcdir/data/libSDL-1.2.so.0
   rm -rf $srcdir/data/libopenal.so
 
+  # Install game files
   install -d "${pkgdir}/opt/SPAZ"
   cp -r "$srcdir/data/"* "${pkgdir}/opt/SPAZ/"
 
@@ -56,23 +58,21 @@ package() {
 }
 
 
-# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
-_get_humblebundle_source() {
-  _get_local_source "$1" || return 1;
-  # TODO: Implement automatic downloading from Humble Bundle site
-}
+###### HELPER FUNCTIONS ######
 
-# Locate a file or folder provided by the user, and symlink it into $srcdir
+# Locates a file or folder provided by the user, and symlinks it into $srcdir
 _get_local_source() {
-  msg "Looking for '$1'..."
+  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
   declare -A _search=(['build dir']="$startdir"
                       ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
   for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
+    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
+    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
+      echo "NOT FOUND"
+    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
+      echo "CHECKSUM FAILED";
+    else
       echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-    echo "NOT FOUND"
   done
   if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
