updated on Tue Jun 21 10:00:59 UTC 2011

diff --git a/perl-convert-uulib/perl-convert-uulib.install b/perl-convert-uulib/perl-convert-uulib.install
--- a/perl-convert-uulib/perl-convert-uulib.install
+++ b/perl-convert-uulib/perl-convert-uulib.install
@@ -1,15 +1,13 @@
 post_install()
 {
+    echo -n "module test... "
 
-	echo -n "module test... "
-
-	perl -mConvert::UUlib -e "exit 0;" 2> /dev/null && echo 'pass.' || echo 'fail.'
-
+    perl -mConvert::UUlib -e "exit 0;" 2> /dev/null && echo 'pass.' || echo 'fail.'
 }
 
 post_upgrade()
 {
-	post_install
+    post_install
 }
 
 op=$1
