updated on Thu May 17 14:00:17 UTC 2012

diff --git a/ovz-web-panel/owp.install b/ovz-web-panel/owp.install
--- a/ovz-web-panel/owp.install
+++ b/ovz-web-panel/owp.install
@@ -1,17 +1,33 @@
 post_upgrade(){
-	if [ -f /opt/ovz-web-panel/config/database.yml ]; then
-		cd /opt/ovz-web-panel
-		rake db:migrate RAILS_ENV="production"
+    _install_dir="/usr/share/webapps/ovz-web-panel"
+	if [ -f ${_install_dir}/config/database.yml ]; then
+		cd ${_install_dir}
+        echo "Upgrading database..."
+		rake-1.8 db:migrate RAILS_ENV="production"
+        if [ $? -ne 0 ]; then
+            echo "Failed to upgrade database to new version."
+            echo "See http://bbs.archlinux.org/viewtopic.php?id=139547"
+        fi
 		cd -
+        #echo "Syncing physical servers state..."
+        #ruby-1.8 ${_install_dir}/script/runner -e production "HardwareServer.all.each { |server| server.sync }"
+        #/opt/ruby1.8/lib/ruby/1.8/drb/drb.rb:941: [BUG] Segmentation fault
+        #ruby 1.8.7 (2012-02-08 patchlevel 358) [i686-linux]
+
 	fi
 }
 post_install(){
-	if [ -x "`which gem-1.8`" ]; then
-		echo "Installing package sqlite3-ruby for Ruby"
-		gem-1.8 install sqlite3
-	else 
-		echo -e "gem-1.8 not found in system, ovz-web-panel will not work"
-	fi
+    echo 'Checking for sqlite3-ruby'
+    gem-1.8 list sqlite3 -i &>/dev/null
+    if [ $? -ne 0 ]; then
+        echo "sqlite3 for ruby1.8 isn't installed."
+        echo "I'm trying to install in the root directory ~/.gem/ruby/1.8"
+        gem-1.8 install sqlite3
+        if [ $? -ne 0 ]; then
+            echo "Installing of sqlite3 for ruby1.8 failed."
+            echo "See http://bbs.archlinux.org/viewtopic.php?id=139547"
+        fi
+    fi
 }
 op=$1
 shift
