updated on Mon Apr  8 04:00:03 UTC 2013

diff --git a/seamonkey-kde/PKGBUILD b/seamonkey-kde/PKGBUILD
--- a/seamonkey-kde/PKGBUILD
+++ b/seamonkey-kde/PKGBUILD
@@ -2,15 +2,14 @@
 # based on the seamonkey and firefox packages from community and extra
 
 pkgname=seamonkey-kde
-pkgver=2.16.2
+pkgver=2.17
 pkgrel=1
 pkgdesc="SeaMonkey internet suite with OpenSUSE patches for better KDE integration"
 arch=(i686 x86_64)
 license=(MPL GPL LGPL)
 depends=(gtk2 libevent libnotify nss libjpeg-turbo libvpx mime-types
 	 mozilla-common startup-notification kmozillahelper)
-makedepends=(unzip zip python2 yasm mesa autoconf2.13
-	     imake ccache)
+makedepends=(unzip zip python2 yasm mesa autoconf2.13 imake)
 optdepends=('networkmanager: Location detection via available WiFi networks')
 provides=("seamonkey=$pkgver")
 conflicts=(seamonkey)
@@ -30,31 +29,30 @@ source=(http://ftp.mozilla.org/pub/mozilla.org/seamonkey/releases/$pkgver/source
 	$_patchurl/MozillaFirefox/mozilla-kde.patch
 	$_patchurl/MozillaFirefox/firefox-browser-css.patch
 	$_patchurl/MozillaFirefox/firefox-kde.patch
-	$_patchurl/MozillaFirefox/firefox-712763.patch
-	)
-md5sums=('e6c747c409b9e3a8e09af32492c1b42b'
-	 'cc2c6837430ffbf5bb734fee5ce8f1df'
-	 '3131ced721c046fd1d2f42e602eb40ce'
+	$_patchurl/MozillaFirefox/firefox-712763.patch)
+md5sums=('931f027dd6e2aac3e36e788f6d86979b'
+	 '8a0cd54ed487e8603d852ee1749a30a9'
+	 'a0fe28e00b0e24b44cbaeed42cbe13ee'
 	 '9b3b71cec2cb4ab6eb098c3a1c56df10'
 	 '2d1d8fcb1e579f1c7a334d0f33797314'
 	 '183d71a79c0f02eaa1b52b8c71690883'
 	 '79f113b56057e17ca2466cd0ac578bb3'
-	 'e07f9ace785e867791fed541759951ee'
+	 '0c680eaf5e2035e992488723ce5ce853'
 	 'f3b657384513254c70866286701c6947'
-	 '12d804bfee726de81604179813d38f15'
+	 '9f4e6467284a5c82fbba0c0afe862f31'
 	 'c0ac87a79abdc48242d0093d766522f1'
-	 'e07e4e77d905fe593513a25939998808'
+	 '8e833c5abff5ddd3d20bc81eb9bfc028'
 	 'df34733c7b43225d85453ebbb87521c6'
-	 'f9ccc9198963ac29f005b65e9cfbd64f'
+	 '194da028eba1fbc316cf37dd586c4112'
 	 '7303a96e92e600a46dd6a2cf9af5ada5')
 
 build() {
-  cd "$srcdir/comm-release/mozilla"
+  cd comm-release/mozilla
 
   msg "WARNING: If you have a Mozilla based browser installed,"
-  msg "you may need to uninstall it before the packaging stage"
+  msg "you may need to uninstall it before packaging"
 
-  msg2 "Patching ..."
+  msg2 "Patching"
   patch -Np1 -i "$srcdir/mozilla-nongnome-proxies.patch"
   patch -Np1 -i "$srcdir/mozilla-shared-nss-db.patch"
   patch -Np1 -i "$srcdir/mozilla-kde.patch"
@@ -77,30 +75,35 @@ build() {
   sed '/^PRE_RELEASE_SUFFIX := ""/s/ ""//' \
     -i mozilla/browser/base/Makefile.in
 
-  # Don't exit with error when some libs are missing which we have in
-  # system.
-  sed '/^MOZ_PKG_FATAL_WARNINGS/s@= 1@= 0@' \
-      -i suite/installer/Makefile.in
-
   # Fix issue with repackaging (don't fail if files are already removed)
   sed 's/xargs rm$/xargs rm -f/' -i mozilla/toolkit/mozapps/installer/packager.mk
-
-  # WebRTC build tries to execute "python" and expects Python 2
-  #mkdir "$srcdir/python2-path"
-  #ln -s /usr/bin/python2 "$srcdir/python2-path/python"
-  #export PATH="$srcdir/python2-path:$PATH"
 
   export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/lib/seamonkey"
   export PYTHON="/usr/bin/python2"
   export MOZ_MAKE_FLAGS="$MAKEFLAGS"
   unset MAKEFLAGS
 
-  msg2 "Starting build ..."
-  make -f client.mk build
+  # Tests fail with CPPFLAGS="-D_FORTIFY_SOURCE=2"
+  unset CPPFLAGS
+
+  msg2 "Starting build"
+  # Enable PGO
+  export MOZ_PGO=1
+  export DISPLAY=:99
+  Xvfb -nolisten tcp -extension GLX -screen 0 1280x1024x24 $DISPLAY &
+  _fail=0
+
+  make -f client.mk build || _fail=1
+
+  kill $! || true
+  return $_fail
+
+  # Build without PGO
+  #make -f client.mk build
 }
 
 package() {
-  cd "$srcdir/comm-release"
+  cd comm-release
 
   make -j1 -f client.mk DESTDIR="$pkgdir" install
   install -Dm644 ../vendor.js "$pkgdir/usr/lib/seamonkey/defaults/preferences/vendor.js"
@@ -118,7 +121,6 @@ package() {
 
   # man page
   install -Dm644 obj-*/mozilla/dist/man/man1/seamonkey.1 "$pkgdir/usr/share/man/man1/seamonkey.1"
-  gzip -9 "$pkgdir/usr/share/man/man1/seamonkey.1"
 
   # Remove development stuff
   rm -r "$pkgdir"/usr/{include,lib/seamonkey-devel,share/idl}
@@ -126,7 +128,8 @@ package() {
   # Remove a reference to srcdir
   sed -e "\|$srcdir|d" -i "$pkgdir/usr/lib/seamonkey/defaults/pref/channel-prefs.js"
 
-  msg2 "The Lightning calendar extensions are in $(echo $srcdir/comm-release/obj-*/mozilla/dist/xpi-stage)"
-  msg2 "You can install them manually from there if you need them"
+  msg2 "The lightning, calendar-timezones and gdata-provider extensions are in"
+  msg2 "$srcdir/comm-release/obj-$CHOST/mozilla/dist/xpi-stage"
+  msg2 "You can install them manually from there"
 }
 
