updated on Tue Apr 29 00:01:26 UTC 2014

diff --git a/catalyst-firepro/catalyst_build_module b/catalyst-firepro/catalyst_build_module
--- a/catalyst-firepro/catalyst_build_module
+++ b/catalyst-firepro/catalyst_build_module
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/bash
 
 kernver=${KERNVER:-$(uname -r)}
 arch=${ARCH:-$(uname -m)}
@@ -34,8 +34,10 @@ install_module(){
 #------------------------------------------------------------------------------------------
 
   ## Compile module using _ati_check variables
+    CFLAGS_MODULE="-DMODULE -DATI -DFGL -DPAGE_ATTR_FIX=$PAGE_ATTR_FIX -DCOMPAT_ALLOC_USER_SPACE=$COMPAT_ALLOC_USER_SPACE $def_smp $def_modversions"
     make -C /usr/lib/modules/${kernver}/build SUBDIRS="`pwd`" ARCH=${arch} \
-      MODFLAGS="-DMODULE -DATI -DFGL -DPAGE_ATTR_FIX=$PAGE_ATTR_FIX -DCOMPAT_ALLOC_USER_SPACE=$COMPAT_ALLOC_USER_SPACE $def_smp $def_modversions" \
+      MODFLAGS="$CFLAGS_MODULE" \
+      CFLAGS_MODULE="$CFLAGS_MODULE" \
       PAGE_ATTR_FIX=$PAGE_ATTR_FIX COMPAT_ALLOC_USER_SPACE=$COMPAT_ALLOC_USER_SPACE modules || return 1
 
     gzip -9 fglrx.ko
@@ -54,7 +56,7 @@ install_module(){
     depmod ${kernver}
     rm -rf "${workdir}"
 #    set +x
-    echo "Ok."
+    echo "ok."
 }
 
 build_all_modules(){
@@ -70,7 +72,7 @@ remove_module(){
       if [[ ${p:17:3} != "ext" ]]; then
 	if [ ! -d $p/kernel ]; then
 	  if [[ -e $p/video/fglrx.ko.gz ]] || [[ -e $p/extramodules/fglrx.ko.gz ]] || [[ -e $p/video/fglrx.ko ]] || [[ -e $p/extramodules/fglrx.ko ]]; then
-	    echo "+ removing fglrx module from $p"
+	    echo "- removing fglrx module from $p"
 	    rm "$p/video/fglrx.ko.gz" &>/dev/null
 	    rm "$p/video/fglrx.ko" &>/dev/null
 	    rm "$p/extramodules/fglrx.ko.gz" &>/dev/null
@@ -79,11 +81,22 @@ remove_module(){
 	  fi
 	  if [ -d $p ]; then
 	    if [ -z "$(ls $p)" ]; then
-	      echo "+ removing empty directory: $p"
+	      echo "- removing empty directory: $p"
 	      rm -rf $p
 		else echo "- $p looks like unused, maybe remove it manualy?"
 	    fi
 	  fi
+	fi
+      elif [[ ! -e $p/version ]]; then
+	if [[ -e $p/fglrx.ko.gz ]] || [[ -e $p/fglrx.ko ]]; then
+	    echo "- removing fglrx module from $p"
+	    rm "$p/fglrx.ko.gz" &>/dev/null
+	    rm "$p/fglrx.ko" &>/dev/null
+	fi
+	if [ -z "$(ls $p)" ]; then   #check if /usr/lib/modules/ext* is empty
+	    echo "- removing empty directory: $p"
+	    rm -rf $p
+	    else  echo "- $p looks like unused, maybe remove it manualy?"
 	fi
       fi
     done
@@ -93,22 +106,33 @@ remove_all_modules(){
    for p in /usr/lib/modules/*; do
     if [[ ${p:17:3} != "ext" ]]; then
      if [[ -e $p/video/fglrx.ko.gz ]] || [[ -e $p/extramodules/fglrx.ko.gz ]]  || [[ -e $p/video/fglrx.ko ]] || [[ -e $p/extramodules/fglrx.ko ]]; then
-      echo "+ removing fglrx module from $p"
-      rm "$p/video/fglrx.ko.gz" &>/dev/null
-      rm "$p/video/fglrx.ko" &>/dev/null
-      rm "$p/extramodules/fglrx.ko.gz" &>/dev/null
-      rm "$p/extramodules/fglrx.ko" &>/dev/null
-      rmdir -p "$p/video/" --ignore-fail-on-non-empty &>/dev/null
-      depmod $(basename $p)
+	echo "- removing fglrx module from $p"
+	rm "$p/video/fglrx.ko.gz" &>/dev/null
+	rm "$p/video/fglrx.ko" &>/dev/null
+	rm "$p/extramodules/fglrx.ko.gz" &>/dev/null
+	rm "$p/extramodules/fglrx.ko" &>/dev/null
+	rmdir -p "$p/video/" --ignore-fail-on-non-empty &>/dev/null
+	depmod $(basename $p)
      fi
      if [ -d $p ]; then
       if [ -z "$(ls $p)" ]; then   #check if /usr/lib/modules/p is empty
-	echo "+ removing empty directory: $p"
+	echo "- removing empty directory: $p"
 	rm -rf $p
 	elif [ ! -d $p/kernel ]; then
 	  echo "- $p looks like unused, maybe remove it manualy?"
       fi
      fi
+    elif [[ ! -e $p/version ]]; then
+      if [[ -e $p/fglrx.ko.gz ]] || [[ -e $p/fglrx.ko ]]; then
+	  echo "- removing fglrx module from $p"
+	  rm "$p/fglrx.ko.gz" &>/dev/null
+	  rm "$p/fglrx.ko" &>/dev/null
+      fi
+      if [ -z "$(ls $p)" ]; then   #check if /usr/lib/modules/ext* is empty
+	  echo "- removing empty directory: $p"
+	  rm -rf $p
+	  else  echo "- $p looks like unused, maybe remove it manualy?"
+      fi
     fi
    done
 }
@@ -117,7 +141,7 @@ remove_old_modules(){
    for p in /lib/modules/*; do
     if [[ ${p:13:3} != "ext" ]]; then
      if [[ -e $p/video/fglrx.ko ]] || [[ -e $p/extramodules/fglrx.ko ]]; then
-      echo "+ removing old fglrx module from $p"
+      echo "- removing old fglrx module from $p"
       rm "$p/video/fglrx.ko" &>/dev/null
       rm "$p/extramodules/fglrx.ko" &>/dev/null
       rmdir -p "$p/video/" --ignore-fail-on-non-empty &>/dev/null
@@ -195,7 +219,7 @@ case "$1" in
 	;;
     *)
         test "$1" != "" && kernver="$1"
-	echo "Building fglrx module for ${kernver} kernel ..."
-        install_module >> $LOG 2>&1 && echo "Ok." || echo -e '\E[37;44m'"\033[1mFailed!!! Check out log: $LOG\033[0m"
+	echo "+ building fglrx module for ${kernver} kernel ..."
+        install_module >> $LOG 2>&1 && echo "  ok." || echo -e '\E[37;44m'"\033[1mFailed!!! Check out log: $LOG\033[0m"
         ;;
 esac
diff --git a/catalyst-total-pxp/catalyst_build_module b/catalyst-total-pxp/catalyst_build_module
--- a/catalyst-total-pxp/catalyst_build_module
+++ b/catalyst-total-pxp/catalyst_build_module
@@ -56,7 +56,7 @@ install_module(){
     depmod ${kernver}
     rm -rf "${workdir}"
 #    set +x
-    echo "ok."
+    echo "Ok."
 }
 
 build_all_modules(){
@@ -72,7 +72,7 @@ remove_module(){
       if [[ ${p:17:3} != "ext" ]]; then
 	if [ ! -d $p/kernel ]; then
 	  if [[ -e $p/video/fglrx.ko.gz ]] || [[ -e $p/extramodules/fglrx.ko.gz ]] || [[ -e $p/video/fglrx.ko ]] || [[ -e $p/extramodules/fglrx.ko ]]; then
-	    echo "- removing fglrx module from $p"
+	    echo "+ removing fglrx module from $p"
 	    rm "$p/video/fglrx.ko.gz" &>/dev/null
 	    rm "$p/video/fglrx.ko" &>/dev/null
 	    rm "$p/extramodules/fglrx.ko.gz" &>/dev/null
@@ -81,7 +81,7 @@ remove_module(){
 	  fi
 	  if [ -d $p ]; then
 	    if [ -z "$(ls $p)" ]; then
-	      echo "- removing empty directory: $p"
+	      echo "+ removing empty directory: $p"
 	      rm -rf $p
 		else echo "- $p looks like unused, maybe remove it manualy?"
 	    fi
@@ -89,12 +89,12 @@ remove_module(){
 	fi
       elif [[ ! -e $p/version ]]; then
 	if [[ -e $p/fglrx.ko.gz ]] || [[ -e $p/fglrx.ko ]]; then
-	    echo "- removing fglrx module from $p"
+	    echo "+ removing fglrx module from $p"
 	    rm "$p/fglrx.ko.gz" &>/dev/null
 	    rm "$p/fglrx.ko" &>/dev/null
 	fi
 	if [ -z "$(ls $p)" ]; then   #check if /usr/lib/modules/ext* is empty
-	    echo "- removing empty directory: $p"
+	    echo "+ removing empty directory: $p"
 	    rm -rf $p
 	    else  echo "- $p looks like unused, maybe remove it manualy?"
 	fi
@@ -106,7 +106,7 @@ remove_all_modules(){
    for p in /usr/lib/modules/*; do
     if [[ ${p:17:3} != "ext" ]]; then
      if [[ -e $p/video/fglrx.ko.gz ]] || [[ -e $p/extramodules/fglrx.ko.gz ]]  || [[ -e $p/video/fglrx.ko ]] || [[ -e $p/extramodules/fglrx.ko ]]; then
-	echo "- removing fglrx module from $p"
+	echo "+ removing fglrx module from $p"
 	rm "$p/video/fglrx.ko.gz" &>/dev/null
 	rm "$p/video/fglrx.ko" &>/dev/null
 	rm "$p/extramodules/fglrx.ko.gz" &>/dev/null
@@ -116,7 +116,7 @@ remove_all_modules(){
      fi
      if [ -d $p ]; then
       if [ -z "$(ls $p)" ]; then   #check if /usr/lib/modules/p is empty
-	echo "- removing empty directory: $p"
+	echo "+ removing empty directory: $p"
 	rm -rf $p
 	elif [ ! -d $p/kernel ]; then
 	  echo "- $p looks like unused, maybe remove it manualy?"
@@ -124,12 +124,12 @@ remove_all_modules(){
      fi
     elif [[ ! -e $p/version ]]; then
       if [[ -e $p/fglrx.ko.gz ]] || [[ -e $p/fglrx.ko ]]; then
-	  echo "- removing fglrx module from $p"
+	  echo "+ removing fglrx module from $p"
 	  rm "$p/fglrx.ko.gz" &>/dev/null
 	  rm "$p/fglrx.ko" &>/dev/null
       fi
       if [ -z "$(ls $p)" ]; then   #check if /usr/lib/modules/ext* is empty
-	  echo "- removing empty directory: $p"
+	  echo "+ removing empty directory: $p"
 	  rm -rf $p
 	  else  echo "- $p looks like unused, maybe remove it manualy?"
       fi
@@ -141,7 +141,7 @@ remove_old_modules(){
    for p in /lib/modules/*; do
     if [[ ${p:13:3} != "ext" ]]; then
      if [[ -e $p/video/fglrx.ko ]] || [[ -e $p/extramodules/fglrx.ko ]]; then
-      echo "- removing old fglrx module from $p"
+      echo "+ removing old fglrx module from $p"
       rm "$p/video/fglrx.ko" &>/dev/null
       rm "$p/extramodules/fglrx.ko" &>/dev/null
       rmdir -p "$p/video/" --ignore-fail-on-non-empty &>/dev/null
@@ -219,7 +219,7 @@ case "$1" in
 	;;
     *)
         test "$1" != "" && kernver="$1"
-	echo "+ building fglrx module for ${kernver} kernel ..."
-        install_module >> $LOG 2>&1 && echo "  ok." || echo -e '\E[37;44m'"\033[1mFailed!!! Check out log: $LOG\033[0m"
+	echo "Building fglrx module for ${kernver} kernel ..."
+        install_module >> $LOG 2>&1 && echo "Ok." || echo -e '\E[37;44m'"\033[1mFailed!!! Check out log: $LOG\033[0m"
         ;;
 esac
