updated on Thu Nov 13 00:00:21 UTC 2014

diff --git a/vtun/tun-cfg b/vtun/tun-cfg
--- a/vtun/tun-cfg
+++ b/vtun/tun-cfg
@@ -27,7 +27,7 @@ CMD=tun-cat
 
 usage() {
  [[ -n "$1" ]] && return 0
- echo "Tunnel-configurer version 1.6
+ echo "Tunnel-configurer version 1.6.1
  Client-server IP tunnel configuration via the same IP tunnel.
 
 -- vtund.conf --
@@ -100,17 +100,18 @@ Server:
 Client:
  $NAME -tun <interface> get|-g|listen [OPTIONS] [<'ip route' options>][-6|v6 <options>]
 
-Addresses of client and server may be specified
- by IP, by name, or by comma-separated list of
- IPv4,IPv6,names and v4,v6,no4,no6 modifiers.
-All names will be resolved on server side,
- and only first IPv4 and first IPv6 will be used.
-Examples:
+Addresses of client and server may be specified by IP, by name, or by
+ comma-separated list of IPv4,IPv6,names with v4,v6,no4,no6 modifiers.
+ All names will be resolved on server side, and only first IPv4 and IPv6 will be used:
+
  10.1.0.1               -> 10.1.0.1
  10.1.0.1,fc00::1001:1  -> 10.1.0.1  fc00::1001:1
  host.vpn               -> 10.1.0.4  fc00::1001:4
  host.vpn,v4            -> 10.1.0.4
  host.vpn,v6            ->           fc00::1001:4
+
+Routes may be specified by IPv4/mask, IPv6/mask,
+ default (for IPv4), defaultv6 or default6 (for IPv6).
 
 OPTIONS:
     port|-P <port>  : default=68
@@ -121,11 +122,15 @@ forcemtu|+m <MTU>   : Don't get MTU from server (client only)
  no6addr|-A         : Don't modify any IPv6 addresses on interface
   nopeer|-p         : Don't set peer address (IPv4)
     peer|+p         : Add a route to peer instead of peer address (IPv4)
-noroutes|-r         : server - Don't send routes from config
-                    : client - Don't add routes from server
-no6routes|-R        : Don't add IPv6 routes from server (client only)
+noroutes|-r         : server - Don't send any routes from config
+                    : client - Don't get IPv4 routes from server
+no6routes|-R        : Don't get IPv6 routes from server (client only)
  timeout|-t <sec>   : default=10, 0=endless
   nofork|-B  | nobg | nobackground
+
+NOTE:
+ By default, tun-cfg forks to background to prevent vtund from endless waiting
+ for tun-cfg termination, if the connection fails during configuration progress.
 "
  exit $URET
 }
@@ -170,7 +175,7 @@ get_addr() {
  [[ -n "$skip" ]] && unset IPv"$skip"
 
  if [[ -z "$IPv4" && -z "$IPv6" ]] ; then
-  log "Can't resolve '$3'"
+  log "Can't resolve '$3' to $1 address"
   exit 7
  fi
  export "$1=$IPv4" "$2=$IPv6"
@@ -180,7 +185,7 @@ set_addr() {
  if [[ -z "$NOADDR" && -n "$1" ]] ; then
   [[ -z "$NOPEER" && -n "$peer" ]] && PEER="peer $peer"
   log $RPREF "address $1" $PEER
-  ip addr add "$1" $PEER dev "$ifc" || exit 3
+  ip addr rep "$1" $PEER dev "$ifc" || exit 3
  fi
  shift
  if [[ -n "$PLUS" && -n "$peer" ]] ; then
@@ -194,7 +199,7 @@ set_addr_v6() {
   dis6="/proc/sys/net/ipv6/conf/$ifc/disable_ipv6"
   [[ -f "$dis6" ]] && echo 0 > "$dis6"
   log $RPREF "address $1"
-  ip -6 addr add "$1" dev "$ifc" || exit 3
+  ip -6 addr rep "$1" dev "$ifc" || exit 3
   echo 0 > "$dis6"
  fi
  shift
@@ -238,9 +243,7 @@ main() {
   if [[ -n "$peer_6" ]] ; then
    set_addr_v6 "$LOCAL6"
    addsend A6 "$peer_6"
-   if [[ -n "$LOCAL6" ]] ; then
-    addsend R6 "$LOCAL6"
-   fi
+   [[ -n "$LOCAL6" ]] && addsend R6 "$LOCAL6"
   fi
   read MTU < "/sys/class/net/$ifc/mtu"
   addsend MTU "$MTU"
