updated on Sun Mar  8 00:08:51 UTC 2015

diff --git a/deepin-pygtk/PKGBUILD b/deepin-pygtk/PKGBUILD
--- a/deepin-pygtk/PKGBUILD
+++ b/deepin-pygtk/PKGBUILD
@@ -2,9 +2,8 @@
 # Maintainer: Xu Fasheng <fasheng.xu[AT]gmail.com>
 
 pkgname=deepin-pygtk
-_pkgname=pygtk
-pkgver=2.24.0.4
-_pkgver=2.24.0-4~saucy
+pkgver=2.24.0
+_srcdirname=pygtk-2.24.0
 pkgrel=6
 pkgdesc="Python bindings for the GTK widget set - with patches to fix memory leak for deepin-ui"
 arch=('i686' 'x86_64')
@@ -21,38 +20,34 @@ source=("http://packages.linuxdeepin.com/deepin/pool/main/p/pygtk/pygtk_2.24.0.o
 sha256sums=('6e3e54fa6e65a69ac60bd58cb2e60a57f3346ac52efe995f3d10b6c38c972fd8'
             '7a70c1f680ee7c4cb326dad86c73a5473c8111deb92e43b6527c8dba03fa9544'
             '39a30456cba055a452bb55c74ef1ff2f5f7bfaad22855b4dd569ab009b56b682')
-provides=("${_pkgname}=2.24.0")
-conflicts=("${_pkgname}")
+provides=("pygtk=2.24.0")
+conflicts=("pygtk")
 
 prepare() {
+  cd "${_srcdirname}"
 
-  # unzip patches
-  cd "$srcdir/"
-  tar -xf ${_pkgname}_${_pkgver}-4~saucy.debian.tar.gz
-
-  cd "${_pkgname}-${_pkgver}"
   # apply python27 patch
   # https://bugzilla.gnome.org/show_bug.cgi?id=623965
   patch -Np1 -i "${srcdir}/python27.patch"
 
   # apply deepin patches
-  patchdir=${srcdir}/debian/patches
-  for f in $(< ${patchdir}/series); do
+  patchdir="${srcdir}"/debian/patches
+  for f in $(< "${patchdir}"/series); do
     echo "==> patching: ${f##*/}"
     # ignore error if patch again
-    patch -Np1 -i ${patchdir}/${f} || echo '==> patch error: ${f##*/}'
+    patch -Np1 -i "${patchdir}/${f}" || echo "==> patch error: ${f##*/}"
   done
 
 }
 
 build() {
-  cd "${_pkgname}-${_pkgver}"
+  cd "${_srcdirname}"
   PYTHON=/usr/bin/python2 ./configure --prefix=/usr
   make
 }
 
 package() {
-  cd "${srcdir}/${_pkgname}-${_pkgver}"
+  cd "${srcdir}/${_srcdirname}"
   make DESTDIR="${pkgdir}" install
   install -m644 gtk/gtk-extrafuncs.defs "${pkgdir}/usr/share/pygtk/2.0/defs/"
   sed -i -e 's#env python$#env python2#' "${pkgdir}"/usr/lib/pygtk/2.0/{,demos/}*.py
