updated on Fri Mar 22 22:04:10 UTC 2013

diff --git a/lastpass-universal/PKGBUILD b/lastpass-universal/PKGBUILD
--- a/lastpass-universal/PKGBUILD
+++ b/lastpass-universal/PKGBUILD
@@ -39,10 +39,10 @@ md5sums=('861c5965a66c05200d4ee0639e9315ec'  # lpchrome_linux.crx
 package() {
   # Since we're installing to $HOME in .install, we need hacks such as this to
   # check whether some clever guy is building with --asroot
-  if [ "$USER" = root ]; then
+  if [ $USER = root ]; then
     msg2 "NOTE: Makepkg is running as root. Most files will be installed to /root."
-    read -p "$(tput bold)$(tput setaf 4)  ->$(tput sgr0)$(tput bold) Continue? (y/n) $(tput sgr0)"
-    [[ "$REPLY" != [yY] ]] && error "Aborted by user! Exiting..." && echo && exit 1
+    read -p "$(tput bold)$(tput setaf 4)  ->$(tput sgr0)$(tput bold) Continue? (Y/n) $(tput sgr0)"
+    [[ $REPLY != [yY] ]] && error "Aborted by user! Exiting..." && echo && exit 1
   fi
 
   msg2 "Installing for Google Chromes/Chromiums"
