updated on Mon Dec  9 00:23:28 UTC 2013

diff --git a/lastpass/PKGBUILD b/lastpass/PKGBUILD
--- a/lastpass/PKGBUILD
+++ b/lastpass/PKGBUILD
@@ -3,9 +3,9 @@
 pkgname=lastpass
 pkgver=3.0.10
 _chromver=3.0.17-1  # The actual extensions' versions
-_ffver=3.0.10-1
+_ffver=3.0.12-1
 _opver=3.0.17-1
-pkgrel=4
+pkgrel=5
 pkgdesc="The Universal LastPass installer for Firefox, Chrome, and Opera"
 arch=('any')
 url="https://lastpass.com"
@@ -35,7 +35,7 @@ source=(# Chrome
         'widgets.dat')
 noextract=("lp_linux_$_ffver.xpi" "lastpass-$_opver.oex")
 md5sums=('132292b1c1dc168d0d8e26a541644d25'
-         '39150bf97ae4ef13027d36b38fbce32e'
+         'a2946ca4e4998331a03dd5cefb99d5cb'
          '2d3eab6ed651ddff4e8ff408f7f064ec'
          '9a15d07e7f5f7d3389b3dc18cf2f8db3'
          'c373651995c0f8ef332439f2ed3b0670'
@@ -45,15 +45,30 @@ prepare() {
     # Since we're installing to $HOME in .install, we need checks such as this to
     # see whether some clever guy is building with --asroot
     if [ $USER = root ]; then
-        msg2 "NOTE: Makepkg is running as root. Most files will be installed to /root."
-        read -p "$(tput bold)$(tput setaf 4)  ->$(tput sgr0)$(tput bold) Continue? (Y/n) $(tput sgr0)"
-        [[ $REPLY != [yY] ]] && error "Aborted by user! Exiting..." && echo && exit 1
+        _note() {
+            printf "${BLUE}==>${ALL_OFF}${YELLOW} NOTE:${ALL_OFF}${BOLD} ${1}${ALL_OFF}\n"
+        }
+
+        _read_msg2() {
+            read -p "$(tput bold)$(tput setaf 4)  ->$(tput sgr0)$(tput bold) ${1} $(tput sgr0)"
+        }
+
+        _note "Makepkg is running as root. The extensions will not be available for a regular user."
+        _read_msg2 "Continue? (Y/n)"
+
+        if [[ $REPLY != [yY] ]]; then
+            error "Aborted by user! Exiting..."
+            echo
+            exit 1
+        fi
     fi
 
-    # Write the extension versions and the $USER to the .install
+    # Write the extension versions and user variables to the .install
     sed -e "s/_ffver= *[^ ]*/_ffver=$_ffver/" \
         -e "s/_opver= *[^ ]*/_opver=$_opver/" \
         -e "s/_user= *[^ ]*/_user=$USER/" \
+        -e "s,_HOME= *[^ ]*,_HOME=/home/$USER/," \
+        -e "s,_mozilla= *[^ ]*,_mozilla=/home/$USER/.mozilla/firefox/$(sed -n 's/^Path=//p' /home/$USER/.mozilla/firefox/profiles.ini)/," \
         -i "$startdir"/$pkgname.install
 }
 
