updated on Tue Jun  3 00:01:48 UTC 2014

diff --git a/lastpass/PKGBUILD b/lastpass/PKGBUILD
--- a/lastpass/PKGBUILD
+++ b/lastpass/PKGBUILD
@@ -22,125 +22,125 @@ optdepends=('chromium: for Chromium'
             'opera: for Opera'
             'opera-next: for Opera Next (AUR)')
 conflicts=('lastpass-plugin-opera')
-install=${pkgname}.install
+install=$pkgname.install
 source=(# Chrome
-        "lpchrome_linux_${_chromver}.crx::${url}/lpchrome_linux.crx"
-        "lplinux_${pkgver}.tar.bz2::${url}/lplinux.tar.bz2"
+        "lpchrome_linux_$_chromver.crx::$url/lpchrome_linux.crx"
+        "lplinux_$pkgver.tar.bz2::$url/lplinux.tar.bz2"
         'com.lastpass.nplastpass.json'
         'lastpass_policy.json'
         # Firefox
-        "lp_linux_${_ffver}.xpi::${url}/lp_linux.xpi"
+        "lp_linux_$_ffver.xpi::$url/lp_linux.xpi"
         'profiles.ini'
         # Opera
-        "lastpass-${_opver}.oex::${url}/lpopera.oex"
+        "lastpass-$_opver.oex::$url/lpopera.oex"
         'prefs.dat'
         'widgets.dat')
-noextract=("lp_linux_${_ffver}.xpi"   # Firefox
-           "lastpass-${_opver}.oex")  # Opera
+noextract=("lp_linux_$_ffver.xpi"   # Firefox
+           "lastpass-$_opver.oex")  # Opera
 md5sums=('ff06ff63b3213c0775d3b151fd618582'
          'eedb4dcf4f44ba80c4531514aec4d38f'
-         '3b41376936fa483b3818e4b41175ce4f'
-         '4b8db7768ed5135b2ab8ece44f1176d6'
+         '4a8d1ccbfef2c641c54bc55e85eb0dfe'
+         '9af777d2eea8e67ad332235718a7653d'
          '5de39607a63c1ff29ad2d54b0c6ebf17'
          'd0f555a644484baccf649f7969794ece'
          '9ab15a2498a54b8cee006b4d01566660'
          'c373651995c0f8ef332439f2ed3b0670'
          '1a6927e679ac378ea0583662d41f6c46')
 
+# 64-bit?
+if [ "$CARCH" = 'x86_64' ]; then
+  _64=64
+fi
+
 # Custom functions for makepkg
 _note() {
-    printf "${RED}==>${ALL_OFF}${RED} NOTE: ${1}${ALL_OFF}\n"
+  printf "${RED}==>${ALL_OFF}${RED} NOTE: $1${ALL_OFF}\n"
 }
 
 _read_msg2() {
-    read -p "${BLUE}  ->${YELLOW} ${1} ${ALL_OFF}${BOLD}${2}${ALL_OFF}"
+  read -p "${BLUE}  ->${YELLOW} $1 ${ALL_OFF}${BOLD}$2${ALL_OFF}"
 }
 
 prepare() {
-    # Since we're installing to $HOME in .install, we need checks such as this to
-    # see whether some clever guy is building with "--asroot"
-    if [ "${USER}" = 'root' ]; then
-        _note "Makepkg is running as root. The extensions will not be available to a regular user."
-        _read_msg2 "Continue?" "(Y/n): "
+  # Since we're installing to $HOME in .install, we need checks such as this to
+  # see whether some clever guy is building with "--asroot"
+  if [ "$USER" = 'root' ]; then
+    _note "Makepkg is running as root. The extensions will not be available to a regular user."
+    _read_msg2 "Continue?" "(Y/n): "
 
-        if [[ "$REPLY" != [yY] ]]; then
-            error "Aborted by user! Exiting..."
-            exit 1
-        fi
+    if [[ "$REPLY" != [yY] ]]; then
+      error "Aborted by user! Exiting..."
+      exit 1
     fi
+  fi
 
-    # Write extension versions and user vars to .install
-    sed -e "s/_ffver=[^ ]*/_ffver=${_ffver}/" \
-        -e "s/_opver=[^ ]*/_opver=${_opver}/" \
-        -e "s/_user=[^ ]*/_user=${USER}/" \
-        -i "${startdir}"/${pkgname}.install
+  # Write extension versions and user vars to .install
+  sed -e "s/_ffver=[^ ]*/_ffver=$_ffver/" \
+      -e "s/_opver=[^ ]*/_opver=$_opver/" \
+      -e "s/_user=[^ ]*/_user=$USER/" \
+      -i "$startdir"/$pkgname.install
 
-    # The Firefox profile(s) might not exist
-    if [ -f ~/.mozilla/firefox/profiles.ini ]; then
-        _ffprofile=$(sed -n 's/^Path=//p' ~/.mozilla/firefox/profiles.ini | grep default || true)
-        if [ ${_ffprofile} ]; then
-            sed "s,_mozilla=[^ ]*,_mozilla=\${_HOME}/.mozilla/firefox/${_ffprofile}/," \
-                -i "${startdir}"/${pkgname}.install
-        else  # Default naming
-            sed "s,_mozilla=[^ ]*,_mozilla=\${_HOME}/.mozilla/firefox/lastpass.default/," \
-                -i "${startdir}"/${pkgname}.install
-        fi
-    else  # Leave empty
-        sed "s/_mozilla=[^ ]*/_mozilla=-/" -i "${startdir}"/${pkgname}.install
+  # The Firefox profile(s) might not exist
+  if [ -f ~/.mozilla/firefox/profiles.ini ]; then
+    _ffprofile=$(sed -n 's/^Path=//p' ~/.mozilla/firefox/profiles.ini | grep default || true)
+    if [ $_ffprofile ]; then
+      sed "s,_mozilla=[^ ]*,_mozilla=\$_home/.mozilla/firefox/$_ffprofile/," \
+          -i "$startdir"/$pkgname.install
+    else  # Default naming
+      sed "s,_mozilla=[^ ]*,_mozilla=\$_home/.mozilla/firefox/lastpass.default/," \
+          -i "$startdir"/$pkgname.install
     fi
+  else  # Leave empty
+    sed "s/_mozilla=[^ ]*/_mozilla=-/" -i "$startdir"/$pkgname.install
+  fi
 }
 
 _chrome_package() {
-    # 64-bit?
-    if [ "${CARCH}" = 'x86_64' ]; then
-        _64=64
-    fi
+  # Install to single place for linking
+  install -Dm644 lpchrome_linux_$_chromver.crx "$pkgdir"/usr/share/lastpass/lpchrome_linux_$_chromver.crx
+  install -Dm755 nplastpass$_64 "$pkgdir"/etc/opt/chrome/native-messaging-hosts/nplastpass$_64
 
-    # Install to single place for linking
-    install -Dm644 lpchrome_linux_${_chromver}.crx "${pkgdir}"/usr/share/lastpass/lpchrome_linux_${_chromver}.crx
-    install -Dm755 nplastpass${_64} "${pkgdir}"/etc/opt/chrome/native-messaging-hosts/nplastpass${_64}
+  # 64-bit?
+  sed "s,/nplastpass,/nplastpass$_64," -i com.lastpass.nplastpass.json
 
-    # 64-bit?
-    sed "s,/nplastpass,/nplastpass${_64}," -i com.lastpass.nplastpass.json
+  # JSONs
+  for i in opt/chrome chromium chromium-dev; do
+    # Messaging host
+    install -Dm644 com.lastpass.nplastpass.json "$pkgdir"/etc/$i/native-messaging-hosts/com.lastpass.nplastpass.json
 
-    # JSONs
-    for i in opt/chrome chromium chromium-dev; do
-        # Messaging host
-        install -Dm644 com.lastpass.nplastpass.json "${pkgdir}"/etc/${i}/native-messaging-hosts/com.lastpass.nplastpass.json
-
-        # Allow silent installation since Chrome v21: http://www.chromium.org/administrators/policy-list-3#ExtensionInstallSources
-        install -Dm644 lastpass_policy.json "${pkgdir}"/etc/${i}/policies/managed/lastpass_policy.json
-    done
+    # Allow silent installation since Chrome v21: http://www.chromium.org/administrators/policy-list-3#ExtensionInstallSources
+    install -Dm644 lastpass_policy.json "$pkgdir"/etc/$i/policies/managed/lastpass_policy.json
+  done
 }
 
 _firefox_package() {
-    # Extension + profiles.ini go to $HOME, so do this in .install
-    for i in lp_linux_${_ffver}.xpi profiles.ini; do
-        install -Dm644 ${i} "${pkgdir}"/usr/share/lastpass/${i}
-    done
+  # Extension + profiles.ini go to $HOME, so do this in .install
+  for i in lp_linux_$_ffver.xpi profiles.ini; do
+    install -Dm644 $i "$pkgdir"/usr/share/lastpass/$i
+  done
 
-    # Binary plugin
-    install -Dm755 libnplastpass${_64}.so "${pkgdir}"/usr/lib/mozilla/plugins/libnplastpass${_64}.so
+  # Binary plugin
+  install -Dm755 libnplastpass$_64.so "$pkgdir"/usr/lib/mozilla/plugins/libnplastpass$_64.so
 }
 
 _opera_package() {
-    # Same for Operas
-    install -m644 lastpass-${_opver}.oex {pref,widget}s.dat "${pkgdir}"/usr/share/lastpass/
+  # Same for Operas
+  install -m644 lastpass-$_opver.oex {pref,widget}s.dat "$pkgdir"/usr/share/lastpass/
 
-    # Binary plugin
-    for i in opera opera-next; do
-        install -d "${pkgdir}"/usr/lib/${i}/plugins/
-        ln -s /usr/lib/mozilla/plugins/libnplastpass${_64}.so "${pkgdir}"/usr/lib/${i}/plugins/libnplastpass${_64}.so
-    done
+  # Binary plugin
+  for i in opera opera-next; do
+    install -d "$pkgdir"/usr/lib/$i/plugins/
+    ln -s /usr/lib/mozilla/plugins/libnplastpass$_64.so "$pkgdir"/usr/lib/$i/plugins/libnplastpass$_64.so
+  done
 }
 
 package() {
-    msg2 "Installing for Google Chromes/Chromiums"
-    _chrome_package
+  msg2 "Installing for Google Chromes/Chromiums"
+  _chrome_package
 
-    msg2 "Installing for Mozilla Firefoxes"
-    _firefox_package
+  msg2 "Installing for Mozilla Firefoxes"
+  _firefox_package
 
-    msg2 "Installing for Operas"
-    _opera_package
+  msg2 "Installing for Operas"
+  _opera_package
 }
diff --git a/vmware-patch/vmware-patch b/vmware-patch/vmware-patch
--- a/vmware-patch/vmware-patch
+++ b/vmware-patch/vmware-patch
@@ -2,35 +2,35 @@
 
 # Some colored makepkg-like functions
 msg() {
-    printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 msg_yellow() {
-    printf "${YELLOW}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${YELLOW}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 msg2() {
-    printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 read_msg2() {
-    read -p "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}"
+  read -p "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}"
 }
 
 msg3() {
-    printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 info_yellow() {
-    printf "${YELLOW}$1${ALL_OFF}${BOLD} $2${ALL_OFF}\n"
+  printf "${YELLOW}$1${ALL_OFF}${BOLD} $2${ALL_OFF}\n"
 }
 
 warning() {
-    printf "${YELLOW}==> WARNING:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${YELLOW}==> WARNING:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 error() {
-    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 # Variables for them
@@ -43,182 +43,181 @@ YELLOW="${BOLD}$(tput setaf 3)"
 
 # Don't continue with an unknown flag
 if [[ "$@" ]] && [[ "$@" != '-f' ]]; then
-    error "Unknown option: $*"
-    info_yellow "Available options:" "-f (force reinstallation even, if modules have already been built)."
-    exit 1
+  error "Unknown option: $*"
+  info_yellow "Available options:" "-f (force reinstallation even, if modules have already been built)."
+  exit 1
 fi
 
 # Make sure we are root
 if [ $(whoami) != "root" ]; then
-    error "This script needs to be run as root."
-    exit 1
+  error "This script needs to be run as root."
+  exit 1
 fi
 
 # Is a VMware product installed?
 if [ ! -f /usr/bin/vmware-installer ]; then
-    error "No VMware product found. Exiting.."
-    exit 1
+  error "No VMware product found. Exiting.."
+  exit 1
 fi
 
 # Set some variables (|&: hide "No protocol specified" in KDE by redirecting all output to cut/grep)
-KERNEL=$(uname -r | cut -d "." -f-2)
-VER=$(vmware-installer -l |& egrep "(player|workstation)" | grep -Po "(\d+\.){2}\d+")
+kernel=$(uname -r | cut -d "." -f-2)
+ver=$(vmware-installer -l |& egrep "(player|workstation)" | grep -Po "(\d+\.){2}\d+")
 if [ $(vmware-installer -l |& egrep "(player|workstation)" | cut -d " " -f1) = "vmware-workstation" ]; then
-    NAME="VMware Workstation"
+  name="VMware Workstation"
 else
-    NAME="VMware Player (Plus)"
+  name="VMware Player (Plus)"
 fi
 
 # Make sure vmware.service includes our USB Arbitrator service
 if [[ ! $(grep usbarbitrator /usr/lib/systemd/system/vmware.service) ]]; then
-    msg "Updating vmware.service.."
-    sed '/Description/a Requires=vmware-usbarbitrator.service\nBefore=vmware-usbarbitrator.service' \
-        -i /usr/lib/systemd/system/vmware.service
+  msg "Updating vmware.service.."
+  sed '/Description/a Requires=vmware-usbarbitrator.service\nBefore=vmware-usbarbitrator.service' \
+      -i /usr/lib/systemd/system/vmware.service
 fi
 
 # Make sure there's a version in /etc/arch-release for versions prior to Workstation 10 / Player (Plus) 6:
 # https://wiki.archlinux.org/index.php?title=VMware&oldid=274532#2.29_The_vmware-usbarbitrator_binary_is_segfaulting
-if [[ ${VER} != 6.0.? ]] && [[ ${VER} != 10.0.? ]]; then
-    if [ ! $(cat /etc/arch-release) ]; then
-        msg "Updating /etc/arch-release.."
-        curl -s https://www.archlinux.org/releng/releases/ | grep -m1 "for " | \
-          cut -d ">" -f3 | cut -d "<" -f1 > /etc/arch-release
-    fi
+if [[ $ver != 6.0.? ]] && [[ $ver != 10.0.? ]]; then
+  if [ ! $(cat /etc/arch-release) ]; then
+    msg "Updating /etc/arch-release.."
+    curl -s https://www.archlinux.org/releng/releases/ | grep -Pom1 'for \K[^"]*' > /etc/arch-release
+  fi
 fi
 
 # Symlink version.h, if necessary (# 1) We don't have one already (accept files too))
 if [ ! -f /usr/src/linux-$(uname -r)/include/linux/version.h ]; then
-    # 2) Installed Workstation/Player less than 9.0.2/5.0.2
-    if [[ ${VER} != [59].0.2 ]] && [[ ${VER} != 6.* ]] && [[ ${VER} != 10.* ]]; then
-        # 3) Kernel version 3.5 or above
-        if [ $(echo ${KERNEL} | tr -d .) -ge 35 ]; then
-            msg "Symlinking version.h for $(uname -r)"
-            install -d "${pkgdir}"/usr/src/linux-$(uname -r)/include/linux/
-            ln -s /usr/src/linux-$(uname -r)/include/generated/uapi/linux/version.h \
-                 "${pkgdir}"/usr/src/linux-$(uname -r)/include/linux/
-        fi
+  # 2) Installed Workstation/Player less than 9.0.2/5.0.2
+  if [[ $ver != [59].0.2 ]] && [[ $ver != 6.* ]] && [[ $ver != 10.* ]]; then
+    # 3) Kernel version 3.5 or above
+    if [ $(echo $kernel | tr -d .) -ge 35 ]; then
+      msg "Symlinking version.h for $(uname -r)"
+      install -d "$pkgdir"/usr/src/linux-$(uname -r)/include/linux/
+      ln -s /usr/src/linux-$(uname -r)/include/generated/uapi/linux/version.h \
+            "$pkgdir"/usr/src/linux-$(uname -r)/include/linux/
     fi
+  fi
 fi
 
 # Remove leftover header locations
 if [[ $(find /usr/src/ -mindepth 1 -maxdepth 2 -type d) ]]; then
-    for i in /usr/src/*; do
-        if [[ $(ls $i) = 'include' ]]; then
-            msg_yellow "Removing leftover header location $i/"
-            rm -r $i
-        fi
-    done
+  for i in /usr/src/*; do
+    if [[ $(ls $i) = 'include' ]]; then
+      msg_yellow "Removing leftover header location $i/"
+      rm -r $i
+    fi
+  done
 fi
 
 # Remove leftover module locations
 for i in /usr/lib/modules/*; do
-    if [[ $(ls $i) = 'misc' ]]; then
-        msg_yellow "Removing leftover module location $i/"
-        rm -r $i
-    fi
+  if [[ $(ls $i) = 'misc' ]]; then
+    msg_yellow "Removing leftover module location $i/"
+    rm -r $i
+  fi
 done
 
 # Backup/Convert/Remove old backups, whatever necessary
 cd /usr/lib/vmware/modules/
 # 1) Use double quotes ("[[") and "ls" instead of the builtin -d/-f for multiple arguments
 # 2) 2>&-: supported by "ls", basically same as "2>/dev/null" only shorter (ignore errors (STDERR))
-if [[ $(ls -d source?*/ source/*.tar-* 2>&- | grep -vx source-${VER}/) ]]; then
-    msg "Cleaning up old backups.."
-    # 1) Check the new location first
-    # 2) Remove any duplicated/old ones
-    # 3) Print full paths
-    # 4) Sed: leave out the first result containing ${VER}
-    for i in $(readlink -e source?*/ | sed "0,/${VER}/{//d}"); do
-        msg2 "Removing ${i}"
-        rm -r "${i}"
+if ls -d source?*/ source/*.tar-* |& grep -qvx source-$ver/; then
+  msg "Cleaning up old backups.."
+  # 1) Check the new location first
+  # 2) Remove any duplicated/old ones
+  # 3) Print full paths
+  # 4) Sed: leave out the first result containing $ver
+  for i in $(readlink -e source?*/ | sed "0,/$ver/{//d}"); do
+    msg2 "Removing $i"
+    rm -r "$i"
+  done
+  # If we already have a backup in the new location, remove any from the old one
+  if [ -d source-$ver*/ ]; then
+    for i in $(readlink -e source/*.tar-*); do
+      msg2 "Removing $i"
+      rm -r "$i"
     done
-    # If we already have a backup in the new location, remove any from the old one
-    if [ -d source-${VER}*/ ]; then
-        for i in $(readlink -e source/*.tar-*); do
-            msg2 "Removing ${i}"
-            rm -r "${i}"
-        done
-        # Rename it as we like (or as I do)
-        if [ -d source-${VER}?*/ ]; then
-            msg3 "Renaming: $(readlink -f source-${VER}*)/ -> $(readlink -f source-${VER})/"
-            mv source-${VER}*/ source-${VER}/
-        fi
-    else
-        # Remove any duplicated/old backups
-        for i in vmblock vmci vmmon vmnet vsock; do
-            for j in $(readlink -e source/${i}.tar-* | sed "0,/${VER}/{//d}"); do
-                msg2 "Removing ${j}"
-                rm -r "${j}"
-            done
-        done
-        # Convert leftovers
-        if [ -f source/vmblock.tar-* ]; then
-            msg3 "Converting: /usr/lib/vmware/modules/source/*.tar -> $(readlink -f source-${VER})/"
-            mkdir source-${VER}/
-            for i in vmblock vmci vmmon vmnet vsock; do
-                mv source/${i}.tar-* source-${VER}/${i}.tar
-            done
-        fi
+    # Rename it as we like (or as I do)
+    if [ -d source-$ver?*/ ]; then
+      msg3 "Renaming: $(readlink -f source-$ver*)/ -> $(readlink -f source-$ver)/"
+      mv source-$ver*/ source-$ver/
     fi
+  else
+    # Remove any duplicated/old backups
+    for i in vmblock vmci vmmon vmnet vsock; do
+      for j in $(readlink -e source/$i.tar-* | sed "0,/$ver/{//d}"); do
+        msg2 "Removing $j"
+        rm -r "$j"
+      done
+    done
+    # Convert leftovers
+    if [ -f source/vmblock.tar-* ]; then
+      msg3 "Converting: /usr/lib/vmware/modules/source/*.tar -> $(readlink -f source-$ver)/"
+      mkdir source-$ver/
+      for i in vmblock vmci vmmon vmnet vsock; do
+        mv source/$i.tar-* source-$ver/$i.tar
+      done
+    fi
+  fi
 fi
 
 # Support the '-f' flag
 # 1) Have we already built (vsock is built last)?
 # 2) Don't check this until we've removed the leftovers
 if [ -f /usr/lib/modules/$(uname -r)/misc/vsock.ko ]; then
-    # Offer the ability reinstall this thing
-    if [[ "$@" = '-f' ]]; then
-        msg "Reinstalling modules.."
-    elif [[ ! "$@" ]]; then
-        error "VMware modules already installed (use -f to override). Exiting.."
-        exit 1
-    fi
+  # Offer the ability reinstall this thing
+  if [[ "$@" = '-f' ]]; then
+    msg "Reinstalling modules.."
+  elif [[ ! "$@" ]]; then
+    error "VMware modules already installed (use -f to override). Exiting.."
+    exit 1
+  fi
 fi
 
 # Patch
 # 1) Make sure we can build
 # 2) Shorther without double brackets ("[["):
 # 3) &>/dev/null: hide all output (STDIN/STDERR)
-if ls patches/*${VER}*${KERNEL}*.patch &>/dev/null; then
-    # Create a backup/Revert
-    if [ ! -d source-${VER} ]; then
-        msg "Creating a backup.."
-        cp -r source/ source-${VER}/
-    else  # Get the original sources from the backup (invalidate the need for 'vmware-unpatch')
-        cp source-${VER}/* source/
-    fi
-    # Loop modules that require patching (vmblock, vmci, vmmon, vmnet and/or vsock)
-    msg "Patching ${NAME} v${VER} for kernel $(uname -r).."
-    cd source
-    # Prevent duplicate entries with 'sort -u'
-    for mod in $(ls ../patches/v*${VER}*${KERNEL}*.patch 2>&- | cut -d "/" -f3 | cut -d "-" -f1 | sort -u); do
-        # Untar
-        tar -xf ${mod}.tar
-        # Patch
-        msg2 "[${mod}]"
-        # Loop through all patches
-        for i in ../patches/${mod}*${VER}*${KERNEL}*.patch; do
-            if ! patch -p0 -s -f -i $i; then
-                error "Failed to apply '$(basename $i)'"
-                read_msg2 "Continue? (Y/n) "
-                if [[ "$REPLY" != [Yy] ]]; then
-                    # Revert
-                    msg "Reverting.."
-                    cd ..
-                    rm -r source/
-                    mv source-${VER}/ source/
-                    msg "Done."
-                    exit 1
-                fi
-            fi
-        done
-        # Tar patched modules
-        tar -cf ${mod}.tar ${mod}-only
-        # Leftovers
-        rm -r ${mod}-only
+if ls patches/*$ver*$kernel*.patch &>-; then
+  # Create a backup/Revert
+  if [ ! -d source-$ver ]; then
+    msg "Creating a backup.."
+    cp -r source/ source-$ver/
+  else  # Get the original sources from the backup (invalidate the need for 'vmware-unpatch')
+    cp source-$ver/* source/
+  fi
+  # Loop modules that require patching (vmblock, vmci, vmmon, vmnet and/or vsock)
+  msg "Patching $name v$ver for kernel $(uname -r).."
+  cd source
+  # Prevent duplicate entries with 'sort -u'
+  for mod in $(ls ../patches/v*$ver*$kernel*.patch 2>&- | grep -Po "s/\K[^-]*" | sort -u); do
+    # Untar
+    tar -xf $mod.tar
+    # Patch
+    msg2 "[$mod]"
+    # Loop through all patches
+    for i in ../patches/$mod*$ver*$kernel*.patch; do
+      if ! patch -p0 -s -f -i $i; then
+        error "Failed to apply '$(basename $i)'"
+        read_msg2 "Continue? (Y/n) "
+        if [[ "$REPLY" != [Yy] ]]; then
+          # Revert
+          msg "Reverting.."
+          cd ..
+          rm -r source/
+          mv source-$ver/ source/
+          msg "Done."
+          exit 1
+        fi
+      fi
     done
+    # Tar patched modules
+    tar -cf $mod.tar $mod-only
+    # Leftovers
+    rm -r $mod-only
+  done
 else
-    msg "No patching required."
+  msg "No patching required."
 fi
 
 # Install
diff --git a/vmware-patch/vmware-unpatch b/vmware-patch/vmware-unpatch
--- a/vmware-patch/vmware-unpatch
+++ b/vmware-patch/vmware-unpatch
@@ -2,23 +2,23 @@
 
 # Some colored makepkg-like functions
 msg() {
-    printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${GREEN}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 msg_yellow() {
-    printf "${YELLOW}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${YELLOW}==>${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 msg2() {
-    printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${BLUE}  ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 msg3() {
-    printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${YELLOW}    ->${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 error() {
-    printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
+  printf "${RED}==> ERROR:${ALL_OFF}${BOLD} $1${ALL_OFF}\n"
 }
 
 # Variables for them
@@ -31,99 +31,99 @@ YELLOW="${BOLD}$(tput setaf 3)"
 
 # Don't support flags
 if [[ "$@" ]]; then
-    error "Unknown option: $*". Exiting..
-    exit 1
+  error "Unknown option: $*". Exiting..
+  exit 1
 fi
 
 # Make sure we are root
 if [ $(whoami) != "root" ]; then
-    error "This script needs to be run as root."
-    exit 1
+  error "This script needs to be run as root."
+  exit 1
 fi
 
 # Is a VMware product installed?
 if [ ! -f /usr/bin/vmware-installer ]; then
-    error "No VMware product found. Exiting.."
-    exit 1
+  error "No VMware product found. Exiting.."
+  exit 1
 fi
 
 # Set some variables (|&: hide "No protocol specified" in KDE by redirecting all output to cut/grep)
-VER=$(vmware-installer -l |& egrep "(player|workstation)" | grep -Po "(\d+\.){2}\d+")
+ver=$(vmware-installer -l |& egrep "(player|workstation)" | grep -Po "(\d+\.){2}\d+")
 if [ $(vmware-installer -l |& egrep "(player|workstation)" | cut -d " " -f1) = "vmware-workstation" ]; then
-    NAME="VMware Workstation"
+  name="VMware Workstation"
 else
-    NAME="VMware Player (Plus)"
+  name="VMware Player (Plus)"
 fi
 
 # Remove leftover header locations
 for i in /usr/src/*; do
-    if [[ $(ls $i) = 'include' ]]; then
-        msg_yellow "Removing leftover header location $i/"
-        rm -r $i
-    fi
+  if [[ $(ls $i) = 'include' ]]; then
+    msg_yellow "Removing leftover header location $i/"
+    rm -r $i
+  fi
 done
 
 # Remove leftover module locations
 for i in /usr/lib/modules/*; do
-    if [[ $(ls $i) = 'misc' ]]; then
-        msg_yellow "Removing leftover module location $i/"
-        rm -r $i
-    fi
+  if [[ $(ls $i) = 'misc' ]]; then
+    msg_yellow "Removing leftover module location $i/"
+    rm -r $i
+  fi
 done
 
 # Backup/Convert/Remove old backups, whatever necessary
 cd /usr/lib/vmware/modules/
 # 1) Use double quotes ("[[") and "ls" instead of the builtin -d/-f for multiple arguments
 # 2) 2>&-: supported by "ls", basically same as "2>/dev/null" only shorter (ignore errors (STDERR))
-if [[ $(ls -d source?*/ source/*.tar-* 2>&- | grep -vx source-${VER}/) ]]; then
-    msg "Cleaning up old backups.."
-    # 1) Check the new location first
-    # 2) Remove any duplicated/old ones
-    # 3) Print full paths
-    # 4) Sed: leave out the first result containing ${VER}
-    for i in $(readlink -e source?*/ | sed "0,/${VER}/{//d}"); do
-        msg2 "Removing ${i}"
-        rm -r "${i}"
+if [[ $(ls -d source?*/ source/*.tar-* 2>&- | grep -vx source-$ver/) ]]; then
+  msg "Cleaning up old backups.."
+  # 1) Check the new location first
+  # 2) Remove any duplicated/old ones
+  # 3) Print full paths
+  # 4) Sed: leave out the first result containing $ver
+  for i in $(readlink -e source?*/ | sed "0,/$ver/{//d}"); do
+    msg2 "Removing $i"
+    rm -r "$i"
+  done
+  # If we already have a backup in the new location, remove any from the old one
+  if [ -d source-$ver*/ ]; then
+    for i in $(readlink -e source/*.tar-*); do
+      msg2 "Removing $i"
+      rm -r "$i"
     done
-    # If we already have a backup in the new location, remove any from the old one
-    if [ -d source-${VER}*/ ]; then
-        for i in $(readlink -e source/*.tar-*); do
-            msg2 "Removing ${i}"
-            rm -r "${i}"
-        done
-        # Rename it as we like (or as I do)
-        if [ -d source-${VER}?*/ ]; then
-            msg3 "Renaming: $(readlink -f source-${VER}*)/ -> $(readlink -f source-${VER})/"
-            mv source-${VER}*/ source-${VER}/
-        fi
-    else
-        # Remove any duplicated/old backups
-        for i in vmblock vmci vmmon vmnet vsock; do
-            for j in $(readlink -e source/${i}.tar-* | sed "0,/${VER}/{//d}"); do
-                msg2 "Removing ${j}"
-                rm -r "${j}"
-            done
-        done
-        # Convert leftovers
-        if [ -f source/vmblock.tar-* ]; then
-            msg3 "Converting: /usr/lib/vmware/modules/source/*.tar -> $(readlink -f source-${VER})/"
-            mkdir source-${VER}/
-            for i in vmblock vmci vmmon vmnet vsock; do
-                mv source/${i}.tar-* source-${VER}/${i}.tar
-            done
-        fi
+    # Rename it as we like (or as I do)
+    if [ -d source-$ver?*/ ]; then
+      msg3 "Renaming: $(readlink -f source-$ver*)/ -> $(readlink -f source-$ver)/"
+      mv source-$ver*/ source-$ver/
     fi
+  else
+    # Remove any duplicated/old backups
+    for i in vmblock vmci vmmon vmnet vsock; do
+      for j in $(readlink -e source/$i.tar-* | sed "0,/$ver/{//d}"); do
+        msg2 "Removing $j"
+        rm -r "$j"
+      done
+    done
+    # Convert leftovers
+    if [ -f source/vmblock.tar-* ]; then
+      msg3 "Converting: /usr/lib/vmware/modules/source/*.tar -> $(readlink -f source-$ver)/"
+      mkdir source-$ver/
+      for i in vmblock vmci vmmon vmnet vsock; do
+        mv source/$i.tar-* source-$ver/$i.tar
+      done
+    fi
+  fi
 fi
 
 # Revert
 cd /usr/lib/vmware/modules/
-if [ -d source-${VER} ]; then
-    msg "Reverting ${NAME} v${VER} module sources.."
-    msg2 "Removing $(readlink -f source)/"
-    rm -r source/
-    msg3 "Renaming backup: $(readlink -f source-${VER})/ -> $(readlink -f source)/"
-    mv source-${VER}/ source/
-    msg "Done."
+if [ -d source-$ver ]; then
+  msg "Reverting $name v$ver module sources.."
+  msg2 "Removing $(readlink -f source)/"
+  rm -r source/
+  msg3 "Renaming backup: $(readlink -f source-$ver)/ -> $(readlink -f source)/"
+  mv source-$ver/ source/
+  msg "Done."
 else  # Nothing found
-    msg "No backups found."
+  msg "No backups found."
 fi
