updated on Sun Dec 22 00:35:33 UTC 2013

diff --git a/lastpass/PKGBUILD b/lastpass/PKGBUILD
--- a/lastpass/PKGBUILD
+++ b/lastpass/PKGBUILD
@@ -10,7 +10,6 @@ pkgdesc="The Universal LastPass installer for Firefox, Chrome, and Opera"
 arch=('any')
 url="https://lastpass.com"
 license=('custom')
-makedepends=('unzip')
 optdepends=('chromium: for Chromium'
             'chromium-dev: for Chromium (Dev Channel) (AUR)'
             'firefox: for Mozilla Firefox'
@@ -21,7 +20,7 @@ optdepends=('chromium: for Chromium'
             'google-chrome-dev: for Google Chrome (Dev Channel) (AUR)'
             'opera: for Opera'
             'opera-next: for Opera Next (AUR)')
-conflicts=('lastpass-plugin-opera' 'lastpass-universal')
+conflicts=('lastpass-plugin-opera')
 install=$pkgname.install
 #source=("$url/lplinux.tar.bz2") # Let's do this a bit more efficiently for now
 source=(# Chrome
@@ -36,29 +35,28 @@ source=(# Chrome
 noextract=("lp_linux_$_ffver.xpi" "lastpass-$_opver.oex")
 md5sums=('c5afe9406eb3c0ad77f722f9a191b329'
          'a2946ca4e4998331a03dd5cefb99d5cb'
-         '2d3eab6ed651ddff4e8ff408f7f064ec'
+         'd0f555a644484baccf649f7969794ece'
          '41d67d69761d48ebeca04bef12bd708f'
          'c373651995c0f8ef332439f2ed3b0670'
          '1a6927e679ac378ea0583662d41f6c46')
+
+_note() {
+    printf "${BLUE}==>${ALL_OFF}${YELLOW} NOTE: ${1}${ALL_OFF}\n"
+}
+
+_read_msg2() {
+    read -p "${BOLD}${BLUE}  ->${YELLOW} ${1} ${ALL_OFF}"
+}
 
 prepare() {
     # Since we're installing to $HOME in .install, we need checks such as this to
     # see whether some clever guy is building with --asroot
     if [ $USER = root ]; then
-        _note() {
-            printf "${BLUE}==>${ALL_OFF}${YELLOW} NOTE:${ALL_OFF}${BOLD} ${1}${ALL_OFF}\n"
-        }
-
-        _read_msg2() {
-            read -p "$(tput bold)$(tput setaf 4)  ->$(tput sgr0)$(tput bold) ${1} $(tput sgr0)"
-        }
-
         _note "Makepkg is running as root. The extensions will not be available for a regular user."
         _read_msg2 "Continue? (Y/n)"
 
         if [[ $REPLY != [yY] ]]; then
             error "Aborted by user! Exiting..."
-            echo
             exit 1
         fi
     fi
@@ -68,16 +66,27 @@ prepare() {
         -e "s/_opver= *[^ ]*/_opver=$_opver/" \
         -e "s/_user= *[^ ]*/_user=$USER/" \
         -e "s,_HOME= *[^ ]*,_HOME=/home/$USER/," \
-        -e "s,_mozilla= *[^ ]*,_mozilla=/home/$USER/.mozilla/firefox/$(sed -n 's/^Path=//p' /home/$USER/.mozilla/firefox/profiles.ini)/," \
         -i "$startdir"/$pkgname.install
+
+    # The Firefox profile(s) might not exist
+    _ffprofile=$(sed -n 's/^Path=//p' ~/.mozilla/firefox/profiles.ini |& grep default || true) # Don't fail on
+    if [ -f ~/.mozilla/firefox/profiles.ini ]; then                                            # empty values
+        if [ $_ffprofile ]; then
+            sed "s,_mozilla= *[^ ]*,_mozilla=/home/$USER/.mozilla/firefox/$_ffprofile/," \
+                -i "$startdir"/$pkgname.install
+        else
+            sed "s,_mozilla= *[^ ]*,_mozilla=/home/$USER/.mozilla/firefox/lastpass.default/," \
+                -i "$startdir"/$pkgname.install
+        fi
+    else
+        sed "s/_mozilla= *[^ ]*/_mozilla=-/" \
+            -i "$startdir"/$pkgname.install
+    fi
 }
 
 _chrome_package() {
-    # This returns a warning about the extra bytes so redirect to /dev/null instead and use the || operator
-    unzip -o lpchrome_linux_$_chromver.crx -d chrome &>/dev/null || true
-
     # Install to a single place and just link it for everybody else
-    CRX=/usr/share/lastpass/lpchrome.crx
+    CRX=/usr/share/lastpass/lpchrome_linux_$_chromver.crx
     echo "{ \"external_crx\": \"$CRX\", \"external_version\": \"${_chromver/-*}\" }" > hdokiejnpimakedhajhdlcegeplioahd.json
     for i in opt/google/chrome usr/share/chromium usr/share/chromium-dev; do
         install -Dm644 hdokiejnpimakedhajhdlcegeplioahd.json "$pkgdir"/$i/extensions/hdokiejnpimakedhajhdlcegeplioahd.json
@@ -100,7 +109,7 @@ _firefox_package() {
     # The binary plugin
     [ "$CARCH" = 'x86_64' ] && _64=64
     for i in opera opera-next; do
-        install -Dm644 chrome/libnplastpass$_64.so "$pkgdir"/usr/lib/mozilla/plugins/libnplastpass$_64.so
+        install -Dm644 libnplastpass$_64.so "$pkgdir"/usr/lib/mozilla/plugins/libnplastpass$_64.so
     done
 }
 
@@ -111,7 +120,7 @@ _opera_package() {
     # The binary plugin
     [ "$CARCH" = 'x86_64' ] && _64=64
     for i in opera opera-next; do
-        install -Dm644 chrome/libnplastpass$_64.so "$pkgdir"/usr/lib/$i/plugins/libnplastpass$_64.so
+        install -Dm644 libnplastpass$_64.so "$pkgdir"/usr/lib/$i/plugins/libnplastpass$_64.so
     done
 }
 
