updated on Sun Jul 17 15:31:00 UTC 2011

diff --git a/lessfs/PKGBUILD b/lessfs/PKGBUILD
--- a/lessfs/PKGBUILD
+++ b/lessfs/PKGBUILD
@@ -1,25 +1,34 @@
 # Maintainer:  Hubert Kario <kario@wit.edu.pl>
 
 pkgname=lessfs
-pkgver=1.3.3.9
-pkgrel=2
+pkgver=1.4.9
+pkgrel=1
 pkgdesc="High performance inline data deduplicating file system for FUSE"
 arch=('i686' 'x86_64')
 license=('GPL')
 url="http://www.lessfs.com/"
 
 makedepends=('gcc' 'make' 'fuse' 'tokyocabinet' 'mhash' 'openssl')
-depends=('tokyocabinet' 'mhash' 'openssl')
+depends=('tokyocabinet' 'mhash' 'openssl' 'lzo2')
 optdepends=('hamsterdb: alternative database to tokyo cabinet')
+backup=('etc/lessfs/sample.cfg')
 #conflicts=("$_pkgname")
 #provides=("$_pkgname=$pkgver")
 
 source=(http://sourceforge.net/projects/lessfs/files/lessfs/lessfs-$pkgver/lessfs-$pkgver.tar.gz/download)
-sha1sums=('d17857820b2cdb45701c869ecfee0218e012b69c')
+sha1sums=('eb981084016f59386c6e836ea84cb5ea74048a0a')
 
 build() {
 	cd "$pkgname-$pkgver"
-	./configure --with-crypto --prefix=/usr || return 1
+        if ( pacman -Q hamsterdb 2>/dev/null >/dev/null ); then
+	    ./configure --with-crypto --with-lzo --with-hamsterdb --prefix=/usr || return 1 ;
+        else
+            echo "==================================";
+            echo " WARNING!";
+            echo "hamsterdb not found, skipping dependancy!" ;
+            echo "==================================";
+	    ./configure --with-crypto --with-lzo --prefix=/usr || return 1 ;
+        fi
 	make || return 1
 	make prefix="$pkgdir/usr" install || return 1
         mkdir -p "$pkgdir/etc/lessfs"
