updated on Sun Jul 17 16:01:00 UTC 2011

diff --git a/lessfs/PKGBUILD b/lessfs/PKGBUILD
--- a/lessfs/PKGBUILD
+++ b/lessfs/PKGBUILD
@@ -2,7 +2,7 @@
 
 pkgname=lessfs
 pkgver=1.4.9
-pkgrel=1
+pkgrel=2
 pkgdesc="High performance inline data deduplicating file system for FUSE"
 arch=('i686' 'x86_64')
 license=('GPL')
@@ -10,7 +10,8 @@ url="http://www.lessfs.com/"
 
 makedepends=('gcc' 'make' 'fuse' 'tokyocabinet' 'mhash' 'openssl')
 depends=('tokyocabinet' 'mhash' 'openssl' 'lzo2')
-optdepends=('hamsterdb: alternative database to tokyo cabinet')
+optdepends=('hamsterdb: alternative database to tokyo cabinet'
+            'db: different alternative database to tokyo cabinet')
 backup=('etc/lessfs/sample.cfg')
 #conflicts=("$_pkgname")
 #provides=("$_pkgname=$pkgver")
@@ -20,15 +21,28 @@ sha1sums=('eb981084016f59386c6e836ea84cb5ea74048a0a')
 
 build() {
 	cd "$pkgname-$pkgver"
+        depts="--with-crypto --with-lzo"
+
         if ( pacman -Q hamsterdb 2>/dev/null >/dev/null ); then
-	    ./configure --with-crypto --with-lzo --with-hamsterdb --prefix=/usr || return 1 ;
+            depts="$depts --with-hamsterdb"
         else
             echo "==================================";
             echo " WARNING!";
-            echo "hamsterdb not found, skipping dependancy!" ;
+            echo "hamsterdb not found, skipping dependancy!";
             echo "==================================";
-	    ./configure --with-crypto --with-lzo --prefix=/usr || return 1 ;
         fi
+
+        if ( pacman -Q db 2>/dev/null >/dev/null ); then
+            depts="$depts --with-berkeleydb"
+        else
+            echo "==================================";
+            echo " WARNING!";
+            echo "Berkley DB (db) not found, skipping dependancy!";
+            echo "==================================";
+        fi
+
+	./configure $depts --prefix=/usr || return 1 ;
+
 	make || return 1
 	make prefix="$pkgdir/usr" install || return 1
         mkdir -p "$pkgdir/etc/lessfs"
@@ -36,5 +50,5 @@ build() {
         install -m 644 -D etc/lessfs.cfg-tokyocabinet $pkgdir/etc/lessfs/sample.cfg-tokyocabinet
         install -m 644 -D etc/lessfs.cfg $pkgdir/etc/lessfs/sample.cfg
         mkdir -p "$pkgdir/usr/share/doc/lessfs"
-        install -m 644 -D FAQ README README.replication README.file_io README.crypto README.performance_or_suffer ChangeLog "$pkgdir/usr/share/doc/lessfs"
+        install -m 644 -D FAQ README README.berkeleydb README.crypto README.file_io README.hashes README.performance_or_suffer README.replication ChangeLog "$pkgdir/usr/share/doc/lessfs"
 }
