updated on Thu Mar  7 06:00:28 UTC 2013

diff --git a/psychonauts/PKGBUILD b/psychonauts/PKGBUILD
--- a/psychonauts/PKGBUILD
+++ b/psychonauts/PKGBUILD
@@ -1,12 +1,12 @@
-# Maintainer: Eric Anderson <ejona86 at gmail dot com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
 
 pkgname=psychonauts
 pkgver=20130104
 _srcpkgver=01042012
 pkgrel=1
-pkgdesc="A mind-bending platforming adventure (game sold separately)"
+pkgdesc='A mind-bending platforming adventure (game sold separately)'
 arch=('i686' 'x86_64')
-url="http://www.psychonauts.com/"
+url='http://www.psychonauts.com/'
 license=('custom')
 makedepends=('unzip')
 if [ "$CARCH" = "x86_64" ]; then
@@ -22,7 +22,7 @@ source=("${pkgname}.desktop"
         "psychonauts.sh"
         "hib://${_gamepkg}")
 md5sums=('91be805610718903bea5c3a3d1d127cf'
-         '6282a96e6c4c4f6f94f92d6f2dfdbefe'
+         'fa33971376bd3824a1202e37220f72a5'
          '506fdad8ce1610cc39bfad137543d714')
 # You can download the Humble Indie Bundle file manually, or you can configure
 # DLAGENTS in makepkg.conf to auto-download.
@@ -34,20 +34,19 @@ md5sums=('91be805610718903bea5c3a3d1d127cf'
 # To auto-search through a directory containing Humble Bundle downloads, you
 # could set:
 # DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
-DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; echo "Read this PKGBUILD for more info."; exit 1')
 PKGEXT='.pkg.tar'
 
 build(){
     cd "${srcdir}"
-    unzip "${_gamepkg}" -d "${pkgname}" || true
+    unzip "${_gamepkg}" -d "${pkgname}-${pkgver}" || true
 }
 
 package(){
-    cd "${srcdir}/${pkgname}"
+    cd "${srcdir}/${pkgname}-${pkgver}"
 
     mkdir -p "${pkgdir}/opt"
-    cp -Rl data "${pkgdir}/opt/"
-    mv "${pkgdir}/opt/data" "${pkgdir}/opt/${pkgname}"
+    cp -Rl data "${pkgdir}/opt/${pkgname}"
 
     # Use system-provided libraries
     rm "${pkgdir}/opt/${pkgname}/libSDL-1.2.so.0"
diff --git a/shadowgrounds-survivor/PKGBUILD b/shadowgrounds-survivor/PKGBUILD
--- a/shadowgrounds-survivor/PKGBUILD
+++ b/shadowgrounds-survivor/PKGBUILD
@@ -4,9 +4,9 @@
 pkgname=shadowgrounds-survivor
 pkgver=beta11_update1
 pkgrel=2
-pkgdesc="A 3D sci-fi alien shooter - sequel to Shadowgrounds (game sold separately)"
+pkgdesc='A 3D sci-fi alien shooter - sequel to Shadowgrounds (game sold separately)'
 arch=('i686' 'x86_64')
-url="http://shadowgroundsgame.com/survivor/"
+url='http://shadowgroundsgame.com/survivor/'
 license=('unknown')
 if [ "$CARCH" = "x86_64" ]; then
   depends=('lib32-libglade' 'lib32-mesa' 'lib32-openal' 'lib32-libvorbis'
@@ -23,27 +23,35 @@ if [ "$CARCH" = "x86_64" ]; then
   install="${pkgname}.install"
 fi
 _gamepkg="survivorUpdate1.run"
-source=("${pkgname}-launcher.sh" "${pkgname}.desktop" "${_gamepkg}")
+source=("${pkgname}-launcher.sh" "${pkgname}.desktop" "hib://${_gamepkg}")
+noextract=("${_gamepkg}")
 md5sums=('06b1b542f3b61b9967b3567d1b2f1c62'
          '68597f3dd51bac4db6ff63b2dcec2284'
          '6c38a1f3fe555b4d3f3e0a9a81a7d743')
-PKGEXT=.pkg.tar
-
-if [ ! -f "${startdir}/${_gamepkg}" ]; then
-  warning ""
-  warning "Requires game download placed at ${startdir}/${_gamepkg}"
-  warning ""
-fi
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download the file manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf"; echo "Read this PKGBUILD for more info."; exit 1')
+PKGEXT='.pkg.tar'
 
 build() {
   cd "${srcdir}"
-  unzip -o "${_gamepkg}" -d "${pkgname}" || true
+  unzip -o "${_gamepkg}" -d "${pkgname}-${pkgver}" || true
 }
 
 package(){
+  cd "${srcdir}/${pkgname}-${pkgver}"
+
   # Copy game files
-  mkdir -p "${pkgdir}/opt/"
-  cp -rl "${srcdir}/${pkgname}" "${pkgdir}/opt/"
+  mkdir "${pkgdir}/opt/"
+  cp -rl . "${pkgdir}/opt/${pkgname}"
 
   # Remove unnecessary files
   rm "${pkgdir}/opt/${pkgname}/createShortcuts.sh"
diff --git a/swordandsworcery/PKGBUILD b/swordandsworcery/PKGBUILD
--- a/swordandsworcery/PKGBUILD
+++ b/swordandsworcery/PKGBUILD
@@ -1,11 +1,11 @@
-# Maintainer: Eric Anderson <ejona86 at gmail dot com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
 
 pkgname=swordandsworcery
 pkgver=1.02
 pkgrel=1
-pkgdesc="An exploratory action adventure videogame with an emphasis on audiovisual style (game purchased separately)"
+pkgdesc='An exploratory action adventure videogame with an emphasis on audiovisual style (game sold separately)'
 arch=('i686' 'x86_64')
-url="http://www.swordandsworcery.com/"
+url='http://www.swordandsworcery.com/'
 license=('custom')
 if [ "$CARCH" == "x86_64" ]; then
     depends=('lib32-mesa' 'lib32-curl' 'lib32-sdl')
@@ -16,30 +16,35 @@ options=('!strip')
 _gamepkg="${pkgname}_${pkgver}.tar.gz"
 source=("${pkgname}.desktop"
         'http://www.swordandsworcery.com/storage/icon_512.png'
-        "${_gamepkg}")
+        "hib://${_gamepkg}")
 noextract=("${_gamepkg}")
 md5sums=('e0aca231d3b4bf8c68bf799f1e9b1201'
          '071d74203e593188ee28c0913d57d4ff'
          '2ede02c0552baeb12979bf9a68fdf399')
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download the file manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf"; echo "Read this PKGBUILD for more info."; exit 1')
 PKGEXT='.pkg.tar'
-
-if [ ! -f "${startdir}/${_gamepkg}" ]; then
-  warning ""
-  warning "Requires purchased game download placed at ${startdir}/${_gamepkg}"
-  warning ""
-fi
 
 build(){
     cd "${srcdir}"
-    mkdir "${pkgname}"
-    bsdtar -x -C "${pkgname}" -f "${_gamepkg}"
+    mkdir "${pkgname}-${pkgver}"
+    bsdtar -x -C "${pkgname}-${pkgver}" -f "${_gamepkg}"
 }
 
 package(){
-    cd ${srcdir}
+    cd "${srcdir}/${pkgname}-${pkgver}"
 
-    mkdir -p "${pkgdir}/opt/"
-    cp -R "${srcdir}/${pkgname}" "${pkgdir}/opt/"
+    install -d "${pkgdir}/opt/"
+    cp -rl . "${pkgdir}/opt/${pkgname}"
 
     # Use system-provided versions
     rm "${pkgdir}/opt/${pkgname}/lib/libstdc++.so.6.0.16"
@@ -53,9 +58,9 @@ package(){
     install -D -m644 "${srcdir}/${pkgname}.desktop" \
         "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 
-    install -D -m644 "${srcdir}/${pkgname}/eula.txt" \
+    install -D -m644 eula.txt \
         "${pkgdir}/usr/share/licenses/${pkgname}/eula.txt"
 
-    mkdir -p "${pkgdir}/usr/bin"
+    install -d "${pkgdir}/usr/bin"
     ln -s "/opt/${pkgname}/run.sh" "${pkgdir}/usr/bin/${pkgname}"
 }
diff --git a/uplink-hib/PKGBUILD b/uplink-hib/PKGBUILD
--- a/uplink-hib/PKGBUILD
+++ b/uplink-hib/PKGBUILD
@@ -6,43 +6,45 @@ _pkgname=uplink
 pkgver=1.6_1
 _pkgver=1.6-1
 pkgrel=7
-pkgdesc="A futuristic computer crime game (requires uplink from Humble Bundle)"
+pkgdesc='A futuristic computer crime game (requires uplink from Humble Bundle)'
 arch=('i686' 'x86_64')
-url="http://www.introversion.co.uk/uplink"
+url='http://www.introversion.co.uk/uplink'
 license=('custom')
 depends=('mesa' 'libjpeg6' 'sdl_mixer' 'libtiff3' 'freetype2')
 conflicts=('uplink')
 if [ "$CARCH" = "x86_64" ]; then
   _gamepkg="${_pkgname}_${_pkgver}_amd64.tar.gz"
   _gamepkgsum='8ee01e7d0d688339fbd84e2005d4625b'
+  _archi='x64'
+  _aarchi='x86_64'
+  _libi='lib64'
 else
   _gamepkg="${_pkgname}_${_pkgver}_i386.tar.gz"
   _gamepkgsum='db4f1b9506cff9e348dd52709f6a8ad7'
+  _archi='x86'
+  _aarchi='x86'
+  _libi='lib'
 fi
-source=("${_pkgname}.desktop" "${_gamepkg}")
+source=("${_pkgname}.desktop" "hib://${_gamepkg}")
 md5sums=('e4c6a0050cb3a0894fb5c70a46c51414' "${_gamepkgsum}")
-PKGEXT=.pkg.tar.gz
-
-if [ ! -f "${startdir}/${_gamepkg}" ]; then
-  warning ""
-  warning "Requires purchased game download placed at ${startdir}/${_gamepkg}"
-  warning ""
-fi
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download the file manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf"; echo "Read this PKGBUILD for more info."; exit 1')
+PKGEXT='.pkg.tar.gz'
 
 package() {
-  if [ "$CARCH" = "x86_64" ]; then
-    _archi='x64'
-    _aarchi='x86_64'
-    _libi='lib64'
-  else
-    _archi='x86'
-    _aarchi='x86'
-    _libi='lib'
-  fi
+  cd "${srcdir}/${_pkgname}-${_archi}"
 
   install -d "${pkgdir}/opt"
-  cp -r "${srcdir}/${_pkgname}-${_archi}" "${pkgdir}/opt/"
-  mv "${pkgdir}/opt/${_pkgname}-${_archi}" "${pkgdir}/opt/${_pkgname}"
+  cp -r . "${pkgdir}/opt/${_pkgname}"
 
   # Use system-provided libraries where possible. Use provided mikmod since the
   # system version is too new. Use provided SDL_mixer since it crashes with
