updated on Mon Mar 23 00:00:40 UTC 2015

diff --git a/go-cross-major-platforms/PKGBUILD b/go-cross-major-platforms/PKGBUILD
--- a/go-cross-major-platforms/PKGBUILD
+++ b/go-cross-major-platforms/PKGBUILD
@@ -1,68 +1,130 @@
+# Maintainer: wicast <wicastchen at hotmail>
+# Contributor: Schala <schalaalexiazeal at gmail.com>
+# Contributor: Vesa Kaihlavirta <vegai at iki.fi>
+# Contributor: Alexander Rødseth <rodseth at gmail.com>
+# Contributor: Rémy Oudompheng  <remy at archlinux.org>
+# Contributor: Andres Perera <andres87p gmail>
+# Contributor: Matthew Bauer <mjbauer95 at gmail.com>
+# Contributor: Christian Himpel <chressie at gmail.com>
+# Contributor: Mike Rosset <mike.rosset at gmail.com>
+# Contributor: Daniel YC Lin <dlin.tw at gmail.com>
+# Contributor: John Luebs <jkluebs at gmail.com>
+
 pkgname=go-cross-major-platforms
-pkgver=1.1.2
+_goname=go
+epoch=2
+pkgver=1.4.2
 pkgrel=1
-pkgdesc="Compiler and tools for the Go programming language from Google (major platforms)"
-arch=(x86_64 i686)
-url="http://golang.org"
-license=("custom")
-depends=(perl gawk)
-makedepends=(inetutils)
+pkgdesc='Compiler and tools for the Go programming language from Google (full platforms as you wish)'
+arch=('x86_64' 'i686')
+url='http://golang.org/doc/install/source#environment'
+license=('BSD')
+makedepends=('inetutils' 'git' 'mercurial')
+options=('!strip' 'staticlibs')
+optdepends=('mercurial: for fetching sources from mercurial repositories'
+            'git: for fetching sources from git repositories'
+            'bzr: for fetching sources from bazaar repositories'
+            'subversion: for fetching sources from subversion repositories')
 conflicts=(go)
 provides=(go)
-options=(!strip staticlibs)
-backup=("usr/lib/go/bin")
-
-if [ "$CARCH" == 'x86_64' ]; then
-  source=("http://go.googlecode.com/files/go$pkgver.linux-amd64.tar.gz"
-          "go.sh")
-  sha256sums=('ad583ff91bd2955fc48d24001785587e3c3b5ce5c09e4971a37028db4c3f6a98'
-            '36202a833faeb8ea10760557a1e221025288480bdeebf776c8b610014aadc181')
-else
-  source=("http://go.googlecode.com/files/go$pkgver.linux-386.tar.gz"
-          "go.sh")
-  sha256sums=('56f384c973e58c098ec462bcd892a7c1166b9a392461970ddb22d57ed4d495af'
-            '36202a833faeb8ea10760557a1e221025288480bdeebf776c8b610014aadc181')
-fi
+install="$pkgname.install"
+source=("$pkgname-$pkgver::git+https://go.googlesource.com/go#tag=$_goname$pkgver")
+md5sums=('SKIP')
 
 build() {
-  cd "$srcdir/go/src"
-  export GOROOT="$srcdir/go"
+  cd "$pkgname-$pkgver/src"
+
+  export GOROOT="$srcdir/$pkgname-$pkgver"
+  export GOBIN="$GOROOT/bin"
+  export GOPATH="$srcdir/"
   export GOROOT_FINAL=/usr/lib/go
-  export GOARM=7
-  for arch in 386 amd64 arm; do
-		export GOOS="linux"
-		export GOARCH="$arch"
-		bash make.bash --no-clean
+
+  #
+  # Arch Linux normally does not enable SSE2 for i686 because of older CPUs.
+  #
+  # However, exceptions are made for:
+  #  * Chromium, which is not expected to be used on older i686 CPUs
+  #  * Julia, which requires SSE2
+  #
+  # Go is so slow that it is unusable on i686 when SSE2 is not enabled,
+  # so I am also making an exception for Go.
+  #
+  # If you really want to build Go without SSE2 support, just uncomment the
+  # following export and rebuild:
+  #
+  # export GO386=387
+  #
+
+  # Crosscompilation for various platforms without arm
+  for os in darwin windows; do #darwin windows dragonfly openbsd plan9; do
+    for arch in amd64 386; do
+      export GOOS="$os"
+      export GOARCH="$arch"
+      bash make.bash --no-clean
+    done
   done
-  for os in darwin windows; do
-		for arch in 386 amd64; do
-			export GOOS="$os"
-			export GOARCH="$arch"
-			bash make.bash --no-clean
-		done
-	done
+
+  # Crosscompilation for various platforms with arm (including linux)
+  for os in linux; do #freebsd netbsd linux; do
+    for arch in amd64 386 arm; do
+      export GOOS="$os"
+      export GOARCH="$arch"
+      # export GOARM=7
+      bash make.bash --no-clean
+    done
+  done
+
+  ## Crosscompilation for solaris only on amd64
+  #export GOOS=solaris
+  #export GOARCH=amd64
+  #
+  #bash make.bash --no-clean
+
+
+  GOOS=linux
+  case "$CARCH" in
+    x86_64) GOARCH=amd64 ;;
+    i686) GOARCH=386 ;;
+  esac
+
+  $GOROOT/bin/go get -d golang.org/x/tools/cmd/godoc
+  $GOROOT/bin/go build -o $srcdir/godoc golang.org/x/tools/cmd/godoc
+  for tool in vet cover; do
+    $GOROOT/bin/go get -d golang.org/x/tools/cmd/${tool}
+    $GOROOT/bin/go build -o $GOROOT/pkg/tool/${GOOS}_${GOARCH}/${tool} golang.org/x/tools/cmd/${tool}
+  done
+}
+
+check() {
+  cd "$pkgname-$pkgver"
+
+  #export GO386=387
+
+  export GOOS=linux
+  if [ "$CARCH" == 'x86_64' ]; then
+    export GOARCH=amd64
+  elif [ "$CARCH" == 'i686' ]; then
+    export GOARCH=386
+  fi
+
+  export GOROOT="$srcdir/$pkgname-$pkgver"
+  export GOBIN="$GOROOT/bin"
+  export PATH="$srcdir/$pkgname-$pkgver/bin:$PATH"
+
+  # TestSimpleMulticastListener will fail in standard chroot
+  cd src && bash run.bash --no-rebuild || true
 }
 
 package() {
-  cd "$srcdir/go"
+  cd "$pkgname-$pkgver"
+
+  export GOROOT="$srcdir/$pkgname-$pkgver"
+  export GOBIN="$GOROOT/bin"
+
+  install -Dm755 "$srcdir/godoc" "$pkgdir/usr/bin/godoc"
 
   install -Dm644 LICENSE \
     "$pkgdir/usr/share/licenses/go/LICENSE"
-  install -Dm644 misc/bash/go \
-    "$pkgdir/usr/share/bash-completion/completions/go"
-  install -Dm644 misc/emacs/go-mode-load.el \
-    "$pkgdir/usr/share/emacs/site-lisp/go-mode-load.el"
-  install -Dm644 misc/emacs/go-mode.el \
-    "$pkgdir/usr/share/emacs/site-lisp/go-mode.el"
-  install -Dm644 misc/zsh/go \
-    "$pkgdir/usr/share/zsh/site-functions/_go"
-
-  for f in ftdetect/gofiletype.vim autoload/go/complete.vim indent/go.vim \
-    ftplugin/go/fmt.vim ftplugin/go/import.vim syntax/go.vim syntax/godoc.vim \
-    plugin/godoc.vim;
-  do
-    install -Dm644 "misc/vim/$f" "$pkgdir/usr/share/vim/vimfiles/$f"
-  done
 
   mkdir -p \
     "$pkgdir/"{etc/profile.d,usr/{share/go,lib/go,lib/go/src,lib/go/site/src}}
@@ -71,7 +133,7 @@ package() {
   ln -s /usr/share/go/doc "$pkgdir/usr/lib/go/doc"
   cp -a bin "$pkgdir/usr"
   cp -a pkg "$pkgdir/usr/lib/go"
-  cp -a "$GOROOT/src/pkg" "$pkgdir/usr/lib/go/src/"
+  cp -a "$GOROOT/src" "$pkgdir/usr/lib/go/"
   cp -a "$GOROOT/src/cmd" "$pkgdir/usr/lib/go/src/cmd"
   cp -a "$GOROOT/src/lib9" "$pkgdir/usr/lib/go/src/"
   cp -a "$GOROOT/lib" "$pkgdir/usr/lib/go/"
@@ -86,20 +148,22 @@ package() {
   find "$pkgdir" -type f -name sql.go -exec chmod -x {} \;
   
   # Remove all executable source files
-  find "$pkgdir/usr/lib/go/src/pkg" -type f -executable -delete
+  find "$pkgdir/usr/lib/go/src" -type f -executable -delete
 
   # Headers for C modules
-  install -Dm644 src/pkg/runtime/runtime.h \
-    "$pkgdir/usr/lib/go/src/pkg/runtime/runtime.h"
-  install -Dm644 src/pkg/runtime/cgocall.h \
-    "$pkgdir/usr/lib/go/src/pkg/runtime/cgocall.h"
-
-  # For packages that source /etc/profile.d/go.sh
-  install -Dm755 "$srcdir/go.sh" "$pkgdir/etc/profile.d/go.sh"
+  install -Dm644 src/runtime/runtime.h \
+    "$pkgdir/usr/lib/go/src/runtime/runtime.h"
+  install -Dm644 src/runtime/cgocall.h \
+    "$pkgdir/usr/lib/go/src/runtime/cgocall.h"
 
   # This is to make go get code.google.com/p/go-tour/gotour and
   # then running the gotour executable work out of the box.
   ln -sf /usr/bin "$pkgdir/usr/lib/go/bin"
+
+  # For FS#42660 / FS#42661 / gox
+  install -Dm755 src/make.bash "$pkgdir/usr/lib/go/src/make.bash"
+  install -Dm755 src/run.bash "$pkgdir/usr/lib/go/src/run.bash"
+  cp -r misc/ "$pkgdir/usr/lib/go/"
 
   # For godoc
   install -Dm644 favicon.ico "$pkgdir/usr/lib/go/favicon.ico"
