updated on Thu Apr 12 16:00:20 UTC 2012

diff --git a/cow_backup/cow_backup b/cow_backup/cow_backup
--- a/cow_backup/cow_backup
+++ b/cow_backup/cow_backup
@@ -7,26 +7,15 @@
 #     \___\___/ \_/\_/___|_.__/ \__,_|\___|_|\_\\__,_| .__/ 	 
 #                   |_____|                          |_|  	 
 #								 		        
-#                        cow_backup-2.1.7
+#                        cow_backup-2.1.8
 #
-#  create and restore gzip-compressed and gpg-encrypted backups 
-#  of complete partitions or directories using tar and gpg
+#  create and restore gzip-compressed and gpg-encrypted full
+#  backups of partitions and directories using tar and gpg
 #
-#  Copyright (c) 2012 by edloaa <edloaa at googlemail dot com>
-#
-#   This program is free software; you can redistribute it and/or
-#   modify it under the terms of the GNU General Public License as
-#   published by the Free Software Foundation; either version 2 of
-#   the License, or (at your option) any later version.
-#    
-#   This program is distributed in the hope that it will be useful,
-#   but WITHOUT ANY WARRANTY; without even the implied warranty of
-#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#   GNU General Public License for more details.
+#  Copyright (C) 2012 edloaa <edloaa at googlemail dot com>
+#  License GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>
 
-#----- VARIABLES -----#
-
-version="cow_backup-2.1.7"	# cow_backup version
+version="cow_backup-2.1.8"	# cow_backup version
 
 cowdate=$(date +"%Y-%m-%d")	# YYYY-mm-dd
 
@@ -40,10 +29,25 @@ c2=$(echo -e '\e[1;31m')	# red      => errors
 c3=$(echo -e '\e[1;34m')	# blue     => user input
 c4=$(echo -e '\033[0m')		# no color => shouldn't be changed!
 
-#----- FUNCTIONS -----#
+usage() {
+	echo "$c1$version: backups and recoveries with tar and gpg$c4"
+	echo
+	echo "$c1 usage $c0[interactive]:$c3 '$0' (start without parameters)$c4"
+	echo
+	echo "$c1 usage $c0[non-interactive]:$c3 '$0 <src> <dest> <pwd>'$c4"
+	echo
+	echo "$c1 - src:   partition or an absolute path you want to backup$c4"
+	echo "$c1 - dest:  /absolute/path/to/your/destination-folder$c4"
+	echo "$c1 - pwd:   you can specify a password for encryption here$c4"
+	echo
+	echo " $c3-> example: ./cow_backup /dev/sda3 /media/backups 'MyPa55w0rd'$c4"
+	echo
+	echo " ${c0}note: backups can only be restored in interactive mode$c4"
+	echo
+	exit 0
+}
 
-function cow_say()
-{
+function cow_say() {
 	char=$(echo "$@" | wc -m)
 
 	t_l=$(for ((x = 0 ; x <= $char ; x++)) ; do echo -n "_" ; done)
@@ -60,8 +64,7 @@ function cow_say()
 	echo
 }
 
-function heading()
-{
+function heading() {
 	char=$(echo -n "$*" | wc -m)
 
 	echo $c0"$*"$c4
@@ -74,8 +77,7 @@ m1="failed to mount the partition to /mnt."
 m2="errors might have occurred."
 m3="unable to unmount the partition, please unmount manually."
 
-function cowerr()
-{
+function cowerr() {
 	# $1 => "$Mx"         -> error message
 	# $2 => "true/ false" -> if true: echo "OK" or "FAILED" 
 	# $3 => "true/ false" -> if true: exit
@@ -105,7 +107,7 @@ function cowerr()
 	echo "${c2}check $log for error messages.$c4"
 
 		if [ $3 = true ]; then
-			cow_say "unable to proceed. aborting."
+			cow_say 'unable to proceed. aborting!'
 			exit 1
 		fi
 
@@ -115,25 +117,24 @@ function cowerr()
 			read ans
 			echo $c4
 
-		case $ans in
-		y)
-			echo "${c1}proceeding...$c4"
-			;;
+			case $ans in
+			y)
+				echo "${c1}proceeding...$c4"
+				;;
+			*)
+				cow_say 'aborting!'
+				exit 1
+				;;
+			esac
 
-		*)
-			cow_say 'aborting!'
-			exit 1
-			;;
-		esac
 		fi
 
 	echo
-	  
+
 	fi
 }
 
-function password()
-{
+function password() {
 	pwd1=a
 	pwd2=b
 
@@ -165,8 +166,14 @@ function password()
 	done
 }
 
-function gpgquest()
-{
+function gpgquest() {
+	filecheck() {
+		if [ -f $backup ]; then
+			echo "$c0$backup does already exsist. please rename this file or choose an other path.$c4"
+			cow_say 'aborting!'
+			exit 0
+		fi
+	}
 	srcname=$(basename $src)
 
 	# GPG encryption dialogue
@@ -179,21 +186,21 @@ function gpgquest()
 	y|Y|yes|Yes|"")
 		GPG="y"
 		backup=$(echo $dest/backup_${srcname}_$cowdate.tgz.gpg | sed "s!//!/!g")
+		filecheck
 		password "encryption"
 		;;
 
 	*)
 		GPG="n"
 		backup=$(echo $dest/backup_${srcname}_$cowdate.tgz | sed "s!//!/!g")
+		filecheck
 		echo "${c0}backup file will not be encrypted with GPG.$c4"
 		echo
 		;;
 	esac
 }
 
-function summary()
-{
-
+function summary() {
 	bline="$c1$(for ((x = 0 ; x <= 70 ; x++)) ; do echo -n "-" ; done)$c4"
 
 	echo
@@ -223,15 +230,19 @@ function summary()
 	echo
 }
 
-#----- ALIAS -----#
-
 shopt -s expand_aliases
 
-alias pstart='read -p "${c1}press any key to start the $task...$c4"'
+alias pstart='read -p "${c1}press enter start the $task...$c4"'
 alias bakinf='echo "$c1$src will be backuped to $backup$c4"'
 alias recinf='echo "$c1$dest will be recovered to $src.$c4"'
 
 #------------------------- SCRIPT START -------------------------#
+
+case $1 in
+-h|--help)
+	usage
+	;;
+esac
 
 # interactive mode
 
@@ -274,7 +285,7 @@ if [ -z "$*" ]; then
 			task="backup"
 			fileinf=true
 
-		elif [ "$opt" = "2" ] || ["$opt" = "4" ]; then
+		elif [ "$opt" = "2" ] || [ "$opt" = "4" ]; then
 			a_cow="recovered"
 			green_cow="archive file (/Path/to/backup.tgz.[gpg])"
 			task="recovery"
@@ -514,7 +525,7 @@ if [ -z "$*" ]; then
 					#---- tar recovery command ----#
 
 					if [ "$GPG" == "y" ]; then
-						(gpg --batch -d --passphrase "$pwd1" $dest | tar -xzv -C /mnt) 2>>$log && echo
+						{ gpg --batch -d --passphrase "$pwd1" $dest | tar -xzv -C /mnt; } 2>>$log && echo
 					elif [ "$GPG" == "n" ]; then
 						tar -xvf $dest -C /mnt 2>>$log
 					fi
@@ -707,7 +718,7 @@ if [ -z "$*" ]; then
 				rm $log
 			fi
 
-			read -p "${c1}press any key...$c4"
+			read -p "${c1}press enter...$c4"
 			clear
 			cow_say $version
 
@@ -731,28 +742,6 @@ if [ -z "$*" ]; then
 
 elif [ -n "$*" ]; then
 
-	# help page
-
-	case $1 in
-	-h|--help)
-		echo "$c1$version: backup and recoveries with tar and gpg$c4"
-		echo
-		echo " ${c1}usage $c0[interactive]:$c3 '$0' (start without parameters)$c4"
-		echo
-		echo " ${c1}usage $c0[non-interactive]:$c3 '$0 <src> <dest> <pwd>'$c4"
-		echo
-		echo " $c1- src:   partition or an absolute path you want to backup$c4"
-		echo " $c1- dest:  /absolute/path/to/your/destination-folder$c4"
-		echo " $c1- pwd:   you can specify a password for encryption here$c4"
-		echo
-		echo " $c3-> example: ./cow_backup /dev/sda3 /media/backups 'MyPa55w0rd'$c4"
-		echo
-		echo " ${c0}note: backups can only be restored in interactive mode.$c4"
-		echo
-		exit 0
-		;;
-	esac
-
 	# no colors in non-interactive mode
 
 	c0=''
@@ -771,7 +760,6 @@ elif [ -n "$*" ]; then
 	if [ $UID != 0 ]; then
 		EXIT="yes"
 		echo "error: root privileges needed."
-		echo
 	fi
 
 	if [ -b "$1" ]; then
@@ -782,22 +770,21 @@ elif [ -n "$*" ]; then
 
 	else
 		EXIT="yes"
-		echo "error: no valid block device or directory."
-		echo
+		echo "error: no valid source (block device or directory)"
 	fi
 
 	if [ ! -d "$2" -o $(echo "$2" | grep "^/" &>/dev/null ; echo $?) -ne "0" ]; then
 		EXIT="yes"
-		echo "error: no valid backup path."
-		echo
+		echo "error: no valid destination (absolute path)"
 	fi
 
 	if [ -z "$3" ]; then
-		echo "warning: file will not be encrypted."
-		echo
+		echo "warning: file will not be encrypted"
+		if [ -z $EXIT ]; then echo; fi
 	fi
 
 	if [ "$EXIT" == "yes" ]; then
+		echo
 		echo "try '$0 -h' for more information."
 		exit 1
 	fi
@@ -816,6 +803,12 @@ elif [ -n "$*" ]; then
 		backup=$(echo $2/backup_${srcname}_$cowdate.tgz | sed "s!//!/!g")
 	fi
 
+	if [ -f $backup ]; then
+		echo "error: $backup does already exsist."
+		echo "       please rename this file or choose an other path. aborting."
+		exit 1
+	fi
+
 	# partition backup
 
 	if [ "$opt" = "1" ]; then
@@ -823,7 +816,8 @@ elif [ -n "$*" ]; then
 		# check if partition is mounted or /mnt is used
 
 		if [ $(mount | grep -e "$1" -e "/mnt" &>/dev/null ; echo $?) -eq "0" ]; then
-			echo "error: "$1" is mounted or /mnt is already used as mount point. please unmount manually and try again."
+			echo "error: "$1" is mounted or /mnt is already used as mount point."
+			echo "       please unmount manually and try again."
 			exit 1
 		fi
 
@@ -906,4 +900,3 @@ elif [ -n "$*" ]; then
 	echo "finished..."
 	exit 0
 fi
-#------------------------ END OF SCRIPT -------------------------#
