updated on Sun Apr  8 02:00:17 UTC 2012

diff --git a/netatalk/a2boot b/netatalk/a2boot
--- a/netatalk/a2boot
+++ b/netatalk/a2boot
@@ -6,31 +6,40 @@
 NAME="Apple II Boot Daemon"
 ARGS=
 DEPENDS=atalkd
+REQUIRED=
 DAEMON=`basename "$0"`
 
 [ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON
 
 PID=`get_pid $DAEMON`
 
+get_pid_r() {
+	local pid=()
+	for i in $@
+	do j=`get_pid $i` || return 1;pid+=($j);done
+	echo ${pid[@]};
+}
+
 case "$1" in
  start)
    stat_busy "Starting $NAME"
-   [ `get_pid $DEPENDS` ] && [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
+   [ `get_pid_r $DEPENDS` ] && [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
    if [ $? = 0 ]; then
      stat_done
    else
      stat_fail
-     if [ ! `get_pid $DEPENDS` ];then echo "Error: \"$DAEMON\" refusing to start, dependency \"$DEPENDS\" not met" >&2;fi
+     if [ ! `get_pid_r $DEPENDS` ];then echo "Error: \"$DAEMON\" refusing to start, dependency \"$DEPENDS\" not met" >&2;fi
      exit 1
    fi
    ;;
  stop)
    stat_busy "Stopping $NAME"
-   [ -n "$PID" ] && kill $PID &>/dev/null
+   [ ! `get_pid_r $REQUIRED` ] && [ -n "$PID" ] && kill $PID &>/dev/null
    if [ $? = 0 ]; then
      stat_done
    else
      stat_fail
+	 if [ `get_pid_r $REQUIRED` ];then echo "Error: Dependency \"$REQUIRED\" requires \"$DAEMON\", stop it first" >&2;fi
      exit 1
    fi
    ;;
