updated on Wed Apr  4 02:06:57 UTC 2012

diff --git a/netatalk/atalkd b/netatalk/atalkd
--- a/netatalk/atalkd
+++ b/netatalk/atalkd
@@ -3,40 +3,42 @@
 . /etc/rc.conf
 . /etc/rc.d/functions
 
-myhostname=`hostname|sed 's/\..*$//'`
+NAME="AppleTalk Protocol Daemon"
+ARGS=
+DEPENDS=init
+DAEMON=`basename "$0"`
 
-PID=`pidof -o %PPID /usr/sbin/atalkd`
+[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON
+
+PID=`get_pid $DAEMON`
+
 case "$1" in
-  start)
-    stat_busy "Starting atalkd Daemon"
-    [ -z "$PID" ] && /usr/sbin/atalkd 
-    if [ $? -gt 0 ]; then
-      stat_fail
-    else
-      echo $PID > /var/run/atalkd.pid
-
-      # Setting AppleTalk info with nbprgstr
-      add_daemon atalkd
-      stat_done
-    fi
-    ;;
-  stop)
-    stat_busy "Stopping atalkd Daemon"
-    [ ! -z "$PID" ]  && kill $PID &> /dev/null
-    if [ $? -gt 0 ]; then
-      stat_fail
-    else
-      rm /var/run/atalkd.pid
-      rm_daemon atalkd
-      stat_done
-    fi
-    ;;
-  restart)
-    $0 stop
-    sleep 1
-    $0 start
-    ;;
-  *)
-    echo "usage: $0 {start|stop|restart}"  
+ start)
+   stat_busy "Starting $NAME"
+   [ `get_pid $DEPENDS` ] && [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
+   if [ $? = 0 ]; then
+     stat_done
+   else
+     stat_fail
+     if [ ! `get_pid $DEPENDS` ];then echo "Error: \"$DAEMON\" refusing to start, dependency \"$DEPENDS\" not met" >&2;fi
+     exit 1
+   fi
+   ;;
+ stop)
+   stat_busy "Stopping $NAME"
+   [ -n "$PID" ] && kill $PID &>/dev/null
+   if [ $? = 0 ]; then
+     stat_done
+   else
+     stat_fail
+     exit 1
+   fi
+   ;;
+ restart)
+   $0 stop
+   sleep 1
+   $0 start
+   ;;
+ *)
+   echo "usage: $0 {start|stop|restart}"  
 esac
-exit 0
