updated on Wed Apr 25 06:00:12 UTC 2012

diff --git a/netatalk/atalkd b/netatalk/atalkd
--- a/netatalk/atalkd
+++ b/netatalk/atalkd
@@ -2,7 +2,7 @@
 
 . /etc/rc.conf
 . /etc/rc.d/functions
-. netatalk >/dev/null
+. /etc/rc.d/netatalk common
 
 NAME="AppleTalk Protocol Daemon"
 ARGS=
@@ -17,23 +17,23 @@ PID=`get_pid $DAEMON`
 case "$1" in
  start)
    stat_busy "Starting $NAME"
-   [ `get_pid_rd $DEPENDS` ] && [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
+   `get_pid_rd $DEPENDS` && [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
    if [ $? = 0 ]; then
      stat_done
    else
      stat_fail
-     if [ ! `get_pid_rd $DEPENDS` ];then echo "Error: \"$DAEMON\" refusing to start, dependency \"$DEPENDS\" not met" >&2;fi
+     if ! `get_pid_rd $DEPENDS`;then echo "Error: \"$DAEMON\" refusing to start, dependency \"$DEPENDS\" not met" >&2;fi
      exit 1
    fi
    ;;
  stop)
    stat_busy "Stopping $NAME"
-   [ `get_pid_rr $REQUIRED` ] && [ -n "$PID" ] && kill $PID &>/dev/null
+   `get_pid_rr $REQUIRED` && [ -n "$PID" ] && kill $PID &>/dev/null
    if [ $? = 0 ]; then
      stat_done
    else
      stat_fail
-	 if [ ! `get_pid_rr $REQUIRED` ];then echo "Error: Dependency \"$REQUIRED\" requires \"$DAEMON\", stop it first" >&2;fi
+	 if ! `get_pid_rr $REQUIRED`;then echo "Error: Dependency \"$REQUIRED\" requires \"$DAEMON\", stop it first" >&2;fi
      exit 1
    fi
    ;;
