updated on Thu Sep 29 10:01:03 UTC 2011

diff --git a/nightingale-git/PKGBUILD b/nightingale-git/PKGBUILD
--- a/nightingale-git/PKGBUILD
+++ b/nightingale-git/PKGBUILD
@@ -11,85 +11,118 @@
 # or the forums at getnightingale.com/forum
 
 pkgname=nightingale-git
-pkgver=20110927
+pkgver=20110929
 pkgrel=1
 pkgdesc="Community port of nightingale to be more Linux native. Working git version is nightingale 1.8 compatible."
 arch=('i686' 'x86_64')
 url="http://getnightingale.com/"
 license=('GPL2' 'MPL' 'BSD')
-makedepends=('git' 'bash' 'subversion' 'python2')
-depends=('libxrender' 'libxext' 'libx11' 'libxmu' 'gstreamer0.10' 'gstreamer0.10-base' 'gtk2' 'libxt' 'sqlite3'
-	 'nss' 'libidl2' 'gstreamer0.10-good-plugins' 'taglib')
-optdepends=('gstreamer0.10-bad-plugins: support for more formats'
-	    'gstreamer0.10-ffmpeg: support for more formats'
-	    'gstreamer0.10-ugly-plugins: support for more formats')
-conflicts=('nightingale' 'nightingale-auto-beta' 'nightingale-auto-nightly' 'nightingale-bin' 'nightingale-nightly' 'nightingale-nightly-bin'
-	   'nightingale-nightly-latest' 'nightingale-stable-bin')
+makedepends=('git' 'bash' 'subversion' 'python2' 'tar' 'wget')
+depends=('gstreamer0.10' 'gstreamer0.10-base' 'gtk2' 'libxt' 'sqlite3' 'gstreamer0.10-good-plugins' 
+		 'gstreamer0.10-bad-plugins' 'gstreamer0.10-ffmpeg' 'gstreamer0.10-ugly-plugins')
+optdepends=()
+conflicts=()
 provides=('nightingale' 'nightingale-git')
 install=nightingale.install
 source=('proper_gst_path_archlinux.patch' 'Nightingale.desktop')
 md5sums=('93d7e61400661def1957b3be9243f332'
          '7741cc247648e95dd9dad8c953616757')
 
+# Only use git if you want a 2.8gb directory sitting in your build
+# dir! Otherwise, just use the snapshot, it's updated every time
+# the git is since the project uses github!
+use_git="no"
+_tarball="https://github.com/ilikenwf/nightingale-hacking/tarball/nightingale-1.8"
+
+# set update to yes if using the tarball and you want to grab the latest
+update=no
+
 _gitroot="git://github.com/ilikenwf/nightingale-hacking.git"
 _gitname="nightingale"
+_branch="nightingale-1.8"
 
 fetch_sources() {
-	# NOTE: master is in development, it WILL NOT BUILD
-	if [ ! -d "$_gitname" ]; then
-		cd "$srcdir"
-		msg2 "Cloning initial copy of zen-sources..."
-		warning "This may take some time depending on your available bandwidth."
-
-		git clone --depth 1 "$_gitroot" "$_gitname"
-
-		_no_update="y" # update is not necessary
-	fi
-
-	cd "$srcdir/$_gitname"
-
-	msg2 "Updating local tree..."
-	if git fetch; then
-		msg2 "Attempting to merge changes..."
-
-		if ! git merge origin/nightingale-1.8; then
-			error "Merging failed..."
-
-			msg2 "Fixing local repository..."
-			git checkout -f "nightingale-1.8"
-			git clean -xdf
-			git reset --hard "origin/nightingale-1.8"
-		fi
-	else
-		error "Update failed..."
-	fi
 	
-	msg "Done doing all of the work with git..."
+	if [ $use_git = "yes" ]; then
+		# NOTE: master is in development, it WILL NOT BUILD
+		if [ ! -d "$_gitname" ]; then
+			cd "$srcdir"
+			msg2 "Cloning initial copy of zen-sources..."
+			warning "This may take some time depending on your available bandwidth."
+
+			git clone --depth 1 "$_gitroot" "$_gitname"
+
+			_no_update="y" # update is not necessary
+		fi
+
+		cd "$srcdir/$_gitname"
+
+		msg2 "Updating local tree..."
+		if git fetch; then
+			msg2 "Attempting to merge changes..."
+
+			if ! git merge "origin/$_branch"; then
+				error "Merging failed..."
+
+				msg2 "Fixing local repository..."
+				git checkout -f "$_branch"
+				git clean -xdf
+				git reset --hard "origin/$_branch"
+			fi
+		else
+			error "Update failed..."
+		fi
+		msg "Done doing all of the work with git..."
+	else
+		msg "Downloading the tarball from github."
+		cd "$srcdir"
+		
+		if [ ! -f "$_branch.tar.gz" ]; then
+			wget -O "$_branch.tar.gz" $_tarball
+		fi
+		
+		tar xvf "$_branch.tar.gz"
+				
+		mv ilikenwf-nightingale-hacking-* nightingale		
+	fi
 }
 
 build() {
-	
 	# get the source
 	fetch_sources
 	
-	cd "$srcdir/$_gitname"
+	cd "$srcdir"
 
 	# I know this is lazy, but needing this svn stuff is temporary
 	# The below if statement/block will be removed in the next version
-	if [ ! -d dependencies/linux-"$(arch)" ] ; then
+	if [ ! -d "$srcdir/nightingale/dependencies/linux-$(arch)" ] ; then
 		msg "Grabbing a few Nightingale specific dependencies"
 		msg "Don't worry, This won't be necessary with the next version, hopefully"
 		msg "A lot of what we're grabbing here aren't even used..."
+		msg2 "This WILL take a while, so don't freak out and cancel if nothing happens for 30sec - 1min"
 		
-		cd dependencies
+		cd "$srcdir/nightingale/dependencies"
 		
 		# Seriously, songbird devs...you didn't have to make it use all this static crap for linux builds...
 		# understandable for Mac and Windows...but I mean, come on...
 		# as the dev of nightingale, I'm working to not need this cruft, since our system provides these pkgs
+		_svnroot="http://ngale.svn.sourceforge.net/svnroot/ngale/branches/dependencies/Nightingale1.8/linux-$(arch)"
+		mkdir -p "linux-$(arch)"/{xulrunner/release,mozilla/release,taglib/release,sqlite/release}
 		
-		svn co http://ngale.svn.sourceforge.net/svnroot/ngale/branches/dependencies/Nightingale1.8/linux-"$(arch)"
-		cd "$srcdir/$_gitname"
+		cd "$srcdir/nightingale/dependencies/linux-$(arch)/xulrunner/release"
+		svn co $_svnroot/xulrunner/release ./
+		
+		cd "$srcdir/nightingale/dependencies/linux-$(arch)/mozilla/release"
+		svn co $_svnroot/mozilla/release ./
+		
+		cd "$srcdir/nightingale/dependencies/linux-$(arch)/taglib/release"
+		svn co $_svnroot/taglib/release ./
+		
+		cd "$srcdir/nightingale/dependencies/linux-$(arch)/sqlite/release"
+		svn co $_svnroot/sqlite/release ./
 	fi
+
+	cd "$srcdir/$_gitname"
 
 	# our gstreamer path, since we use system libs :)
 	export GST_PLUGIN_PATH="/usr/lib/gstreamer-0.10"
@@ -114,6 +147,10 @@ build() {
 
 	# make the package
 	package
+	
+	# free up over 600 mb
+	
+	make -f nightingale.mk clobber
 }
 
 package() {
