updated on Sun Jan  8 23:00:55 UTC 2012

diff --git a/nightingale-git/PKGBUILD b/nightingale-git/PKGBUILD
--- a/nightingale-git/PKGBUILD
+++ b/nightingale-git/PKGBUILD
@@ -11,7 +11,7 @@
 # or the forums at getnightingale.com/forum
 
 pkgname=nightingale-git
-pkgver=20120107
+pkgver=20120108
 pkgrel=1
 pkgdesc="Community port of nightingale to be more Linux native. Working git version is nightingale 1.8 compatible."
 arch=('i686' 'x86_64')
@@ -45,27 +45,39 @@ fetch_sources() {
 	if [ $use_git = "yes" ]; then
 		# NOTE: master is in development, it WILL NOT BUILD
 		if [ ! -d "$_gitname" ]; then
-			cd "${srcdir}"
-			msg2 "Cloning initial copy of zen-sources..."
-			warning "This may take some time depending on your available bandwidth."
+		cd "$srcdir"
+		msg2 "Cloning initial copy of zen-sources..."
+		warning "This may take some time depending on your available bandwidth."
 
-			git clone --depth 1 "$_gitroot" "$_gitname"
+		git clone --depth 1 "$_gitroot" "$_gitname"
 
-			_no_update="y" # update is not necessary
+		_no_update="y" # update is not necessary
 		fi
-		
-		if [ $_no_update = "n" ]; then
-			cd "${srcdir}/$_gitname"
+
+		if [ "$_no_update" = "y" ]; then
+			msg2 "Skipping tree update..."
+		else
+			cd "$srcdir/$_gitname"
 
 			msg2 "Updating local tree..."
-				git reset --hard
-				git clean -xdf
-				git pull 
-			msg "Done doing all of the work with git..."
-		fi
-		
-		git checkout $_branch
-		
+			if git fetch; then
+				msg2 "Attempting to merge changes..."
+
+				if ! "git merge origin/$_branch"; then
+					error "Merging failed..."
+
+					msg2 "Fixing local repository..."
+					git checkout -f "$_branch"
+					git clean -xdf
+					git reset --hard "origin/$_branch"
+				fi
+			else
+				error "Update failed..."
+			fi
+
+			warning "Press ENTER if you want to continue or CTRL+C to abort..."
+			read
+		fi		
 	else
 		msg "Downloading the tarball from github."
 		cd "${srcdir}"
