updated on Sun Jun  9 02:31:05 UTC 2013

diff --git a/plexmediaserver/plexmediaserver.install b/plexmediaserver/plexmediaserver.install
--- a/plexmediaserver/plexmediaserver.install
+++ b/plexmediaserver/plexmediaserver.install
@@ -1,13 +1,38 @@
 post_install() {
-  groupadd plex
-  useradd -g plex -s /bin/bash -d /opt/plexmediaserver plex
-  # Now to fix broken items from plexapp.com
+  if [ ! `getent passwd plex` ]; then
+    useradd -m -r -s /bin/bash -d /opt/plexmediaserver plex
+    if [ ! $? -eq 0 ]
+    then
+      echo "WARNING COULDN'T CREATE PLEX USERID, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+      exit 1
+    fi
+  fi;
+
+# Now to fix broken items from plexapp.com
   rm -f /opt/plexmediaserver/start.sh
   . /etc/conf.d/plexmediaserver
-  mkdir -p ${PLEX_MEDIA_SERVER_HOME}/Library/Application\ Support/Plex\ Media\ Server/Plug-ins
-  rm -rf ${PLEX_MEDIA_SERVER_HOME}/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/{System.bundle,Framework.bundle}
-  cp -r ${PLEX_MEDIA_SERVER_HOME}/Resources/Plug-ins/{System.bundle,Framework.bundle} ${PLEX_MEDIA_SERVER_HOME}/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/
-  chown -R ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} /opt/plexmediaserver &
+
+  if [ ! -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ];
+  then
+    mkdir -p "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
+    if [ ! $? -eq 0 ]
+    then
+      echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+      exit 1
+    fi
+    chown -R ${PLEX_MEDIA_SERVER_USER} "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
+  fi
+
+  if [ ! -d ${PLEX_MEDIA_SERVER_HOME}/Library/Application\ Support/Plex\ Media\ Server/Plug-ins ]; then
+    mkdir -p ${PLEX_MEDIA_SERVER_HOME}/Library/Application\ Support/Plex\ Media\ Server/Plug-ins
+    if [ ! $? -eq 0 ]
+    then
+      echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+      exit 1
+    fi
+    cp -r ${PLEX_MEDIA_SERVER_HOME}/Resources/Plug-ins/{System.bundle,Framework.bundle} ${PLEX_MEDIA_SERVER_HOME}/Library/Application\ Support/Plex\ Media\ Server/Plug-ins/
+    chown -R ${PLEX_MEDIA_SERVER_USER} ${PLEX_MEDIA_SERVER_HOME} &
+  fi
 
   systemctl --system daemon-reload
   cat << "EOM"
@@ -24,7 +49,7 @@ EOM
 
 pre_install() {
   if [ -f /usr/lib/systemd/system/plexmediaserver.service ]; then
-    echo "Stopping Plexmediaserver before starting upgrade"
+    echo "Stopping Plexmediaserver before starting..."
     systemctl stop plexmediaserver
   fi;
 }
@@ -39,5 +64,7 @@ pre_remove() {
 
 post_upgrade() {
   systemctl --system daemon-reload
-  chown -R ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} /opt/plexmediaserver &
+  . /etc/conf.d/plexmediaserver
+  rm -f ${PLEX_MEDIA_SERVER_HOME}/start.sh
+  chown -R ${PLEX_MEDIA_SERVER_USER} ${PLEX_MEDIA_SERVER_HOME} &
 }
