updated on Wed May 29 02:23:57 UTC 2013

diff --git a/plexmediaserver/start_pms b/plexmediaserver/start_pms
--- a/plexmediaserver/start_pms
+++ b/plexmediaserver/start_pms
@@ -27,7 +27,18 @@ then
   chown -R ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Linux/i386/Frameworks/"
   if [ ! $? -eq 0 ]
   then
-    echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+    echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Linux/i386/Frameworks, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+    exit 1
+  fi
+fi
+
+if [ ! -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Logs" ]
+then
+  mkdir -p "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Logs"
+  chown -R ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Logs"
+  if [ ! $? -eq 0 ]
+  then
+    echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Logs, MAKE SURE I HAVE PERMISSON TO DO THAT!"
     exit 1
   fi
 fi
