updated on Mon May 27 20:16:34 UTC 2013

diff --git a/plexmediaserver/start_pms b/plexmediaserver/start_pms
--- a/plexmediaserver/start_pms
+++ b/plexmediaserver/start_pms
@@ -21,14 +21,20 @@ then
   fi
 fi
 
-touch /var/log/plexmediaserver.log
-chown ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} /var/log/plexmediaserver.log
-chown -R ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} /usr/local/plexmediaserver &
+if [ ! -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Linux/i386/Frameworks/" ]
+then
+  mkdir -p "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Linux/i386/Frameworks/"
+  chown -R ${PLEX_MEDIA_SERVER_USER}:${PLEX_MEDIA_SERVER_USER} "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/Linux/i386/Frameworks/"
+  if [ ! $? -eq 0 ]
+  then
+    echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR/Plex Media Server/Plug-ins/Framework.bundle/Contents/Resources/Platforms/, MAKE SURE I HAVE PERMISSON TO DO THAT!"
+    exit 1
+  fi
+fi
+
 
 export LD_LIBRARY_PATH="${PLEX_MEDIA_SERVER_HOME}"
 export TMPDIR="${PLEX_MEDIA_SERVER_TMPDIR}"
-
-#echo $PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS $PLEX_MEDIA_SERVER_MAX_STACK_SIZE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR
 
 ulimit -s $PLEX_MEDIA_SERVER_MAX_STACK_SIZE
 
