updated on Thu Aug  4 11:30:58 UTC 2011

diff --git a/worldofgoo-demo/PKGBUILD b/worldofgoo-demo/PKGBUILD
--- a/worldofgoo-demo/PKGBUILD
+++ b/worldofgoo-demo/PKGBUILD
@@ -1,4 +1,5 @@
-# Contributor: Todd Partridge <toddrpartridge@gmail.com>
+# Maintainer: gadget3000 <gadget3000 at msn dot com>
+# Contributor: Todd Partridge <toddrpartridge at gmail dot com>
 
 pkgname=worldofgoo-demo
 _pkgname=WorldOfGooDemo
@@ -8,36 +9,59 @@ pkgdesc="World of Goo is a physics based puzzle/construction game."
 arch=('i686' 'x86_64')
 url="http://2dboy.com/games.php"
 license=('custom')
-depends=('mesa' 'sdl_mixer')
-backup=('usr/share/$pkgname/properties/config.txt')
-source=(
-http://ftp2.za.freebsd.org/pub/FreeBSD/distfiles/$_pkgname.1.41.tar.gz
-        $pkgname.desktop)
-md5sums=('2a490524ae2cfd11fcb2e052dfe47d4e'
-         '2c51596fa6c1afa7bcb39da559015881')
+depends=('mesa' 'sdl_mixer' 'libogg' 'sdl' 'libvorbis')
+source=($pkgname.desktop
+        'config.txt')
+md5sums=('2c51596fa6c1afa7bcb39da559015881'
+         '408f3d4eec70452f2a7927ed51e113ad')
+options=(!strip)
 
+_archive_md5="2a490524ae2cfd11fcb2e052dfe47d4e"
+_archive="WorldOfGooDemo.${pkgver}.tar.gz"
 
 build() {
 
-	cd $srcdir
+  cd $srcdir
+ 
+  if [ ! -f ${_archive} ]; then
+     wget "http://worldofgoo.com/dl2.php?lk=demo&filename=${_archive}"
+     wget $(cat dl2.php\?lk\=demo\&filename\=${_archive} | cut -d '"' -f 2)
+  fi
+
+  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_archive}"
+    return 1
+  fi
 
   # create pkgdir folders
   install -d $pkgdir/usr/bin
   install -d $pkgdir/usr/share/{applications,games,icons}
   install -d $pkgdir/usr/share/licenses/$pkgname
 
-  # game folder
-  cp -R $_pkgname $pkgdir/usr/share/games/$pkgname
+  tar xzf ${_archive} -C ${pkgdir}/usr/share/games/
+
+  if [ "$CARCH" = "x86_64" ]; then
+     rm -fr ${pkgdir}/usr/share/games/${_pkgname}/libs32
+     rm -fr ${pkgdir}/usr/share/games/${_pkgname}/WorldOfGoo.bin32
+  else
+     rm -fr ${pkgdir}/usr/share/games/${_pkgname}/libs64
+     rm -fr ${pkgdir}/usr/share/games/${_pkgname}/WorldOfGoo.bin64
+  fi
 
   # licenses
-  install -m644 $_pkgname/eula.txt $pkgdir/usr/share/licenses/$pkgname/
+  install -m644 ${pkgdir}/usr/share/games/$_pkgname/eula.txt $pkgdir/usr/share/licenses/$pkgname/
 
   # executable link
-  ln -s /usr/share/games/$pkgname/WorldOfGoo $pkgdir/usr/bin/$pkgname
+  echo \#\!/bin/sh > $pkgdir/usr/bin/$pkgname
+  echo cd /usr/share/games/$_pkgname/ >> $pkgdir/usr/bin/$pkgname
+  echo ./WorldOfGoo >> $pkgdir/usr/bin/$pkgname
+  chmod +x $pkgdir/usr/bin/$pkgname
 
   # icon/.desktop
-  install -m644 $_pkgname/icons/scalable.svg \
+  install -m644 ${pkgdir}/usr/share/games/$_pkgname/icons/scalable.svg \
   $pkgdir/usr/share/icons/$pkgname.svg
-  install -m644 $startdir/$pkgname.desktop $pkgdir/usr/share/applications/
+  install -m644 $srcdir/$pkgname.desktop $pkgdir/usr/share/applications/
 
+  #fix sound on x86_64
+  cp -f ${srcdir}/config.txt $pkgdir/usr/share/games/${_pkgname}/properties/
 }
