updated on Sun Jan  4 00:05:09 UTC 2015

diff --git a/kodi-standalone-service/readme.install b/kodi-standalone-service/readme.install
--- a/kodi-standalone-service/readme.install
+++ b/kodi-standalone-service/readme.install
@@ -1,27 +1,30 @@
 post_install() {
-  getent group kodi > /dev/null || groupadd -g 420 kodi
-  if ! getent passwd kodi > /dev/null; then
-	  useradd -c 'kodi user' -u 420 -g kodi -G audio,video,network,optical -d /var/lib/kodi -s /usr/bin/nologin kodi
-	  passwd -l kodi > /dev/null
-		[[ ! -d /var/lib/kodi/.kodi ]] && mkdir /var/lib/kodi/.kodi && chown -R kodi:kodi /var/lib/kodi/.kodi
-  fi
+	getent group kodi > /dev/null || groupadd -g 420 kodi
+	if ! getent passwd kodi > /dev/null; then
+		useradd -c 'kodi user' -u 420 -g kodi -G audio,video,network,optical \
+			-d /var/lib/kodi -s /usr/bin/nologin kodi
+		passwd -l kodi > /dev/null
+		[[ ! -d /var/lib/kodi/.kodi ]] &&
+			mkdir /var/lib/kodi/.kodi &&
+			chown -R kodi:kodi /var/lib/kodi/.kodi
+	fi
 }
 
 post_upgrade() {
-  post_install $1
-  if ! getent group kodi | cut -d: -f3 | grep 420 > /dev/null 2>&1; then
-	  groupmod -g 420 kodi > /dev/null 2>&1
-  fi
-  if ! id -u kodi | grep 420 > /dev/null 2>&1; then
-	  usermod -u 420 kodi > /dev/null 2>&1
-	  if [[ $? -ne 0 ]]; then
-		  echo "Changing uid of user kodi failed"
-		  echo "It is recommended that the uid is changed."
-		  echo "Stop all processes running under the kodi user and reinstall kodi"
-		  echo "or change the uid manually. (usermod -u 420 kodi)"
-	  fi
-	  chown -R kodi:kodi /var/lib/kodi
-  fi
+	post_install $1
+	if ! getent group kodi | cut -d: -f3 | grep 420 > /dev/null 2>&1; then
+		groupmod -g 420 kodi > /dev/null 2>&1
+	fi
+	if ! id -u kodi | grep 420 > /dev/null 2>&1; then
+		usermod -u 420 kodi > /dev/null 2>&1
+		if [[ $? -ne 0 ]]; then
+			echo "Changing uid of user kodi failed."
+			echo "It is recommended that the uid is changed."
+			echo "Stop all processes running under the kodi user and reinstall kodi"
+			echo "or change the uid manually. (usermod -u 420 kodi)"
+		fi
+		chown -R kodi:kodi /var/lib/kodi
+	fi
 
 	if [[ -d /var/lib/xbmc ]]; then
 		echo "If you are upgrading from xbmc->kodi and wish to keep your"
@@ -33,16 +36,14 @@ post_upgrade() {
 }
 
 post_remove() {
-  getent passwd kodi > /dev/null 2>&1 && userdel kodi
-  getent group kodi > /dev/null 2>&1 && groupdel kodi
+	getent passwd kodi > /dev/null 2>&1 && userdel kodi
+	getent group kodi > /dev/null 2>&1 && groupdel kodi
 }
 
 post_message() {
 	echo "Users of Xorg >=1.16 wishing to autostart kodi standalone"
 	echo "must create or modify /etc/X11/Xwrapper.config to contain"
-	echo "the following 2 lines:"
+	echo "the following:"
 	echo
 	echo "allowed_users = anybody"
-	echo "needs_root_rights = yes"
-
 }
