updated on Thu Mar  5 00:01:55 UTC 2015

diff --git a/linux-bridge-pl/PKGBUILD b/linux-bridge-pl/PKGBUILD
--- a/linux-bridge-pl/PKGBUILD
+++ b/linux-bridge-pl/PKGBUILD
@@ -57,10 +57,10 @@ options=('!strip')
 makedepends=('kmod' 'inetutils' 'bc')
 _uksmvernel="0.1.2.3"
 _uksmname="v3.18"
-_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.19.0-v7r7"
-_bfqpath="https://pf.natalenko.name/mirrors/bfq/3.19.0-v7r7/"
 _bfsrel=461
 _bfspatch="3.19-sched-bfs-${_bfsrel}.patch"
+_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.19.0-v7r7"
+_bfqpath="https://pf.natalenko.name/mirrors/bfq/3.19.0-v7r7/"
 _gcc_patch="enable_additional_cpu_optimizations_for_gcc_v4.9+_kernel_v3.15+.patch"
 
 source=("http://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
@@ -69,13 +69,13 @@ source=("http://www.kernel.org/pub/linux/kernel/v3.x/${_srcname}.tar.xz"
         #"https://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.sign"
         #"http://kerneldedup.org/download/uksm/${_uksmvernel}/uksm-${_uksmvernel}-for-${_uksmname}.patch" # website often went down
         "uksm-${_uksmvernel}-for-${_uksmname}.patch"
+        "http://ck.kolivas.org/patches/bfs/3.0/3.19/${_bfspatch}"
+        "http://ck.kolivas.org/patches/3.0/3.19/3.19-ck1/patches/hz-default_1000.patch"
+        "http://ck.kolivas.org/patches/3.0/3.19/3.19-ck1/patches/hz-no_default_250.patch"
         "${_bfqpath}/0001-block-cgroups-kconfig-build-bits-for-BFQ-v7r7-3.19.patch"
         "${_bfqpath}/0002-block-introduce-the-BFQ-v7r7-I-O-sched-for-3.19.patch"
         "${_bfqpath}/0003-block-bfq-add-Early-Queue-Merge-EQM-to-BFQ-v7r7-for-3.19.0.patch"
         "http://repo-ck.com/source/gcc_patch/${_gcc_patch}.gz"
-        "http://ck.kolivas.org/patches/bfs/3.0/3.19/${_bfspatch}"
-        "http://ck.kolivas.org/patches/3.0/3.19/3.19-ck1/patches/hz-default_1000.patch"
-        "http://ck.kolivas.org/patches/3.0/3.19/3.19-ck1/patches/hz-no_default_250.patch"
         'linux-bridge-pl.preset'
         'change-default-console-loglevel.patch'
         'config' 'config.x86_64')
@@ -92,76 +92,42 @@ prepare() {
     msg "Patching set DEFAULT_CONSOLE_LOGLEVEL to 4"
     patch -p1 -i "${srcdir}/change-default-console-loglevel.patch"
 
-  
+ 
+ ### Patch source with UKSM
+    msg "Patching with UKSM"
+    patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
+
+ 
+  ### Patch source with BFS 
+ msg "Patching source with BFS v0.461"
+ patch -Np1 -i "${srcdir}/${_bfspatch}"
+ patch -Np1 -i "${srcdir}/hz-default_1000.patch"
+ patch -Np1 -i "${srcdir}/hz-no_default_250.patch" 
    
-  
+   
+ ### Patch source with BFQ
     msg "Patching source with BFQ patches"
     for p in "${srcdir}"/000{1,2,3}-block*.patch; do
     msg " $p"
     patch -Np1 -i "$p"
     done
-
     
-# Patch source to enable more gcc CPU optimizatons via the make nconfig
+    ### Patch source to enable more gcc CPU optimizatons via the make nconfig
 msg "Patching source with gcc patch to enable more cpus types"
 	patch -Np1 -i "${srcdir}/${_gcc_patch}"
 
-
-# patch source with BFS 
- msg "Patching source with BFS v0.461"
- patch -Np1 -i "${srcdir}/${_bfspatch}"
- patch -Np1 -i "${srcdir}/hz-default_1000.patch"
- patch -Np1 -i "${srcdir}/hz-no_default_250.patch" 
-
     
-   ### Patch source with UKSM
-    msg "Patching with UKSM"
-    patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
-
     ### Clean tree and copy ARCH config over
-    msg "Running make mrproper to clean source tree"
-    make mrproper
+	msg "Running make mrproper to clean source tree"
+	make mrproper
 
-    if [ "${CARCH}" = "x86_64" ]; then
-        cat "${srcdir}/config.x86_64" > ./.config
-    else
-        cat "${srcdir}/config" > ./.config
-    fi
-
-    ### Optionally use running kernel's config
-    # code originally by nous; http://aur.archlinux.org/packages.php?ID=40191
-    if [ -n "$_use_current" ]; then
-	if [[ -s /proc/config.gz ]]; then
-	    msg "Extracting config from /proc/config.gz..."
-	    # modprobe configs
-	    zcat /proc/config.gz > ./.config
+	if [ "${CARCH}" = "x86_64" ]; then
+		cat "${srcdir}/config.x86_64" > ./.config
 	else
-	    warning "You kernel was not compiled with IKCONFIG_PROC!"
-	    warning "You cannot read the current config!"
-	    warning "Aborting!"
-	    exit
+		cat "${srcdir}/config" > ./.config
 	fi
-    fi
 
-    if [ "${_kernelname}" != "" ]; then
-	sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
-	sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
-    fi
-
-    ### UKSM to be enabled
-    sed -i -e s'/CONFIG_KSM=y/CONFIG_KSM=y\nCONFIG_UKSM=y/' ./.config
-
-    ### BFQ to be compiled in but not enabled
-    sed -i -e s'/CONFIG_CFQ_GROUP_IOSCHED=y/CONFIG_CFQ_GROUP_IOSCHED=y\nCONFIG_IOSCHED_BFQ=y\nCONFIG_CGROUP_BFQIO=y/' \
-        -i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
-
-    ### Optionally enable BFQ as the default io scheduler
-    if [ -n "$_BFQ_enable_" ]; 	then
-        sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
-        -i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
-    fi
-
-    ### Optionally set tickrate to 1000 to avoid suspend issues as reported here:
+	### Optionally set tickrate to 1000 to avoid suspend issues as reported here:
 	# http://ck-hack.blogspot.com/2013/09/bfs-0441-311-ck1.html?showComment=1379234249615#c4156123736313039413
 	if [ -n "$_1k_HZ_ticks" ]; then
 		msg "Setting tick rate to 1k..."
@@ -169,50 +135,77 @@ msg "Patching source with gcc patch to enable more cpus types"
 			-i -e 's/^# CONFIG_HZ_1000 is not set/CONFIG_HZ_1000=y/' \
 			-i -e 's/^CONFIG_HZ=300/CONFIG_HZ=1000/' .config
 	fi
-    
-    
-    
-    # disable NUMA since 99.9% of users do not have multiple CPUs but do have multiple cores in one CPU
-    # see, https://bugs.archlinux.org/task/31187
-    if [ -n "$_NUMAdisable" ]; then
-	if [ "${CARCH}" = "x86_64" ]; then
-	    sed -i -e 's/CONFIG_NUMA=y/# CONFIG_NUMA is not set/' \
-		    -i -e '/CONFIG_AMD_NUMA=y/d' \
-		    -i -e '/CONFIG_X86_64_ACPI_NUMA=y/d' \
-		    -i -e '/CONFIG_NODES_SPAN_OTHER_NODES=y/d' \
-		    -i -e '/# CONFIG_NUMA_EMU is not set/d' \
-		    -i -e '/CONFIG_NODES_SHIFT=6/d' \
-		    -i -e '/CONFIG_NEED_MULTIPLE_NODES=y/d' \
-		    -i -e '/CONFIG_USE_PERCPU_NUMA_NODE_ID=y/d' \
-		    -i -e '/CONFIG_ACPI_NUMA=y/d' ./.config
+
+	### Optionally use running kernel's config
+	# code originally by nous; http://aur.archlinux.org/packages.php?ID=40191
+	if [ -n "$_use_current" ]; then
+		if [[ -s /proc/config.gz ]]; then
+			msg "Extracting config from /proc/config.gz..."
+			# modprobe configs
+			zcat /proc/config.gz > ./.config
+		else
+			warning "You kernel was not compiled with IKCONFIG_PROC!"
+			warning "You cannot read the current config!"
+			warning "Aborting!"
+			exit
+		fi
 	fi
-    fi
 
-    # set extraversion to pkgrel
-    sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
-
-    # don't run depmod on 'make install'. We'll do this ourselves in packaging
-    sed -i '2iexit 0' scripts/depmod.sh
-
-   # get kernel version
-    msg "Running make prepare for you to enable patched options of your choosing"
-    make prepare
-
-    ### Optionally load needed modules for the make localmodconfig
-    # See http://aur.archlinux.org/packages.php?ID=41689
-    if [ -n "$_localmodcfg" ]; then
-	msg "If you have modprobe-db installed, running it in recall mode now"
-	if [ -e /usr/bin/modprobed-db ]; then
-	    [[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo. Install via pacman -S sudo and configure to work with this user." && exit 1
-	    sudo /usr/bin/modprobed-db recall
+	if [ "${_kernelname}" != "" ]; then
+		sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
+		sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
 	fi
-	msg "Running Steven Rostedt's make localmodconfig now"
-	make localmodconfig
-    fi
 
- 
-    
-    # rewrite configuration
+	### Optionally disable NUMA since >99% of users have mono-socket systems.
+	# For more, see: https://bugs.archlinux.org/task/31187
+	if [ -n "$_NUMAdisable" ]; then
+		if [ "${CARCH}" = "x86_64" ]; then
+			msg "Disabling NUMA from kernel config..."
+			sed -i -e 's/CONFIG_NUMA=y/# CONFIG_NUMA is not set/' \
+				-i -e '/CONFIG_AMD_NUMA=y/d' \
+				-i -e '/CONFIG_X86_64_ACPI_NUMA=y/d' \
+				-i -e '/CONFIG_NODES_SPAN_OTHER_NODES=y/d' \
+				-i -e '/# CONFIG_NUMA_EMU is not set/d' \
+				-i -e '/CONFIG_NODES_SHIFT=6/d' \
+				-i -e '/CONFIG_NEED_MULTIPLE_NODES=y/d' \
+				-i -e '/# CONFIG_MOVABLE_NODE is not set/d' \
+				-i -e '/CONFIG_USE_PERCPU_NUMA_NODE_ID=y/d' \
+				-i -e '/CONFIG_ACPI_NUMA=y/d' ./.config
+		fi
+	fi
+
+	### Optionally enable BFQ as the default I/O scheduler
+	if [ -n "$_BFQ_enable_" ]; then
+		msg "Setting BFQ as default I/O scheduler..."
+		sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
+			-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	fi
+
+	# set extraversion to pkgrel
+	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
+
+	# don't run depmod on 'make install'. We'll do this ourselves in packaging
+	sed -i '2iexit 0' scripts/depmod.sh
+
+	# get kernel version
+	msg "Running make prepare for you to enable patched options of your choosing"
+	make prepare
+
+	### Optionally load needed modules for the make localmodconfig
+	# See https://aur.archlinux.org/packages/modprobed-db
+		if [ -n "$_localmodcfg" ]; then
+		msg "If you have modprobe-db installed, running it in recall mode now"
+		if [ -e /usr/bin/modprobed-db ]; then
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
+			sudo /usr/bin/modprobed-db recall
+		fi
+		msg "Running Steven Rostedt's make localmodconfig now"
+		make localmodconfig
+	fi
+
+
+
+	# rewrite configuration
 	yes "" | make config >/dev/null
 
 	# save configuration for later reuse
@@ -221,7 +214,6 @@ msg "Patching source with gcc patch to enable more cpus types"
 	else
 		cat .config > "${startdir}/config.last"
 	fi
-    
 }
 
 build() {
@@ -450,35 +442,20 @@ package_linux-bridge-pl-docs() {
 sha512sums=('d77bfd9b1cd524ac50bb5a93808955be2f9bcd2ec0badcc8aa6a63401e212f891fd14bd27c6441174ba5d70ab875b9e76c7ebc95f046e31aff1d40790d30351c'
             'SKIP'
             'b99dbb7b21b443dbf107a628255f216db8c86f936956fae6a21c74510be1be32cf9e45318fc5cf865e9272e80ec4d246f252b22560fea6799040582f4082163b'
+            '957cdf7b41266a1209925312f3062d36f2f3be4015ef2bc11c9f3742b1b5f0b29d413d4bd24d0438e0ab36f9aa19a84ea5fb5c19ca63baf151de706e41012bdc'
+            '232204b77ab88e3bf9a7aa10a6aa706c5133a2aa50fa4d9e85125ce2265f2d290e1095b93f7b2a6ff3c08c0701bb212e221ee3a6c814a4f44d740833bbabfc8c'
+            'e4e6b7cdbd7608a07cc7d55cf9738905baf9bab8a5195995f59e5bdac2bccd11343645a64d763e776cdbaf13a29d95abfab7734aa4cec90eb5e8d8e01a7edef2'
             'a4f9b4cc5ac85d3bf9b8a3420fd550bf1361d24f1314953d7c073f07a4d008ee5bfcadafba28bd57aa7228857392c131af12a0804da256bc98cfd9462112051e'
             '04cd37e2043c32e27406720a12212227fd307c67024e27127386e9c6f20e8fdd04c1a423b334cc41868dac935de0c8e59ef2220bddbb4b1e47f4e6c115bf0091'
             '5298979067a41dc6506a08664ef70fc3d9ef5155a1ac6a7cc65e050282498d3451aa3077028c05d97e9467ee7d083ce45606ab2582558a26a2cc95c8b6cbfa81'
             'bdf5fbd0f7b674be9e4c5004d54bd91c7cc82f80b0ad2c534b62bd39b52b1ad6a2694bd645a208dcd1eb1e03e64d60e71bf605e096c69e497cdeda00534cbcc7'
-            '957cdf7b41266a1209925312f3062d36f2f3be4015ef2bc11c9f3742b1b5f0b29d413d4bd24d0438e0ab36f9aa19a84ea5fb5c19ca63baf151de706e41012bdc'
-            '232204b77ab88e3bf9a7aa10a6aa706c5133a2aa50fa4d9e85125ce2265f2d290e1095b93f7b2a6ff3c08c0701bb212e221ee3a6c814a4f44d740833bbabfc8c'
-            'e4e6b7cdbd7608a07cc7d55cf9738905baf9bab8a5195995f59e5bdac2bccd11343645a64d763e776cdbaf13a29d95abfab7734aa4cec90eb5e8d8e01a7edef2'
             '796a262faa081a8a3decca67c734f989f1394aa2f0baad6dc0ce68aebd3994689726c6b301ead4174ecf86b50c5e40c22cffc8542282bbcef01aebd2526dcc85'
             'd9d28e02e964704ea96645a5107f8b65cae5f4fb4f537e224e5e3d087fd296cb770c29ac76e0ce95d173bc420ea87fb8f187d616672a60a0cae618b0ef15b8c8'
             '5286f5107162a4a2afabedce12cb3bdf5988bf6443c6766fa5b8870798bbd9b8b92218df6a7d8a73864292a9e261e11235901e9d7fe272c2138bf4b8d28dbe3e'
             'd80b2de6df453b9944a5938eeb33c2743abf80f7891cdafe6316bad8ee1a6ed9b0388b579445902de1e66430aff66cebd669871d6a90427b67e594b9d2347970')
 
 
-
-
-
-
-
 validpgpkeys=(
               'ABAF11C65A2970B130ABE3C479BE3E4300411886' # Linus Torvalds
               '647F28654894E3BD457199BE38DBBDC86092693E' # Greg Kroah-Hartman
            )
-
-
-
-
-
-
-
-
-
-
diff --git a/linux-uksm/PKGBUILD b/linux-uksm/PKGBUILD
--- a/linux-uksm/PKGBUILD
+++ b/linux-uksm/PKGBUILD
@@ -84,110 +84,105 @@ prepare() {
     msg "Patching set DEFAULT_CONSOLE_LOGLEVEL to 4"
     patch -p1 -i "${srcdir}/change-default-console-loglevel.patch"
 
+        ### Patch source with UKSM
+    msg "Patching with UKSM"
+    patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
    
-  
+   
+   ### Patch source with BFQ
     msg "Patching source with BFQ patches"
     for p in "${srcdir}"/000{1,2,3}-block*.patch; do
     msg " $p"
     patch -Np1 -i "$p"
     done
 
-    
-# Patch source to enable more gcc CPU optimizatons via the make nconfig
-msg "Patching source with gcc patch to enable more cpus types"
+    ### Patch source to enable more gcc CPU optimizatons via the make nconfig
+  msg "Patching source with gcc patch to enable more cpus types"
 	patch -Np1 -i "${srcdir}/${_gcc_patch}"
 
 
-    
-   ### Patch source with UKSM
-    msg "Patching with UKSM"
-    patch -Np1 -i "${srcdir}/uksm-${_uksmvernel}-for-${_uksmname}.patch"
-
     ### Clean tree and copy ARCH config over
-    msg "Running make mrproper to clean source tree"
-    make mrproper
+	msg "Running make mrproper to clean source tree"
+	make mrproper
 
-    if [ "${CARCH}" = "x86_64" ]; then
-        cat "${srcdir}/config.x86_64" > ./.config
-    else
-        cat "${srcdir}/config" > ./.config
-    fi
-
-    ### Optionally use running kernel's config
-    # code originally by nous; http://aur.archlinux.org/packages.php?ID=40191
-    if [ -n "$_use_current" ]; then
-	if [[ -s /proc/config.gz ]]; then
-	    msg "Extracting config from /proc/config.gz..."
-	    # modprobe configs
-	    zcat /proc/config.gz > ./.config
-	else
-	    warning "You kernel was not compiled with IKCONFIG_PROC!"
-	    warning "You cannot read the current config!"
-	    warning "Aborting!"
-	    exit
-	fi
-    fi
-
-    if [ "${_kernelname}" != "" ]; then
-	sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
-	sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
-    fi
-
-    ### UKSM to be enabled
-    sed -i -e s'/CONFIG_KSM=y/CONFIG_KSM=y\nCONFIG_UKSM=y/' ./.config
-
-    ### BFQ to be compiled in but not enabled
-    sed -i -e s'/CONFIG_CFQ_GROUP_IOSCHED=y/CONFIG_CFQ_GROUP_IOSCHED=y\nCONFIG_IOSCHED_BFQ=y\nCONFIG_CGROUP_BFQIO=y/' \
-        -i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
-
-    ### Optionally enable BFQ as the default io scheduler
-    if [ -n "$_BFQ_enable_" ]; 	then
-        sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
-        -i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
-    fi
-
-    # disable NUMA since 99.9% of users do not have multiple CPUs but do have multiple cores in one CPU
-    # see, https://bugs.archlinux.org/task/31187
-    if [ -n "$_NUMAdisable" ]; then
 	if [ "${CARCH}" = "x86_64" ]; then
-	    sed -i -e 's/CONFIG_NUMA=y/# CONFIG_NUMA is not set/' \
-		    -i -e '/CONFIG_AMD_NUMA=y/d' \
-		    -i -e '/CONFIG_X86_64_ACPI_NUMA=y/d' \
-		    -i -e '/CONFIG_NODES_SPAN_OTHER_NODES=y/d' \
-		    -i -e '/# CONFIG_NUMA_EMU is not set/d' \
-		    -i -e '/CONFIG_NODES_SHIFT=6/d' \
-		    -i -e '/CONFIG_NEED_MULTIPLE_NODES=y/d' \
-		    -i -e '/CONFIG_USE_PERCPU_NUMA_NODE_ID=y/d' \
-		    -i -e '/CONFIG_ACPI_NUMA=y/d' ./.config
+		cat "${srcdir}/config.x86_64" > ./.config
+	else
+		cat "${srcdir}/config" > ./.config
 	fi
-    fi
 
-    # set extraversion to pkgrel
-    sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
+	
 
-    # don't run depmod on 'make install'. We'll do this ourselves in packaging
-    sed -i '2iexit 0' scripts/depmod.sh
-
-    
-    # get kernel version
-    msg "Running make prepare for you to enable patched options of your choosing"
-    make prepare
-
-    ### Optionally load needed modules for the make localmodconfig
-    # See http://aur.archlinux.org/packages.php?ID=41689
-    if [ -n "$_localmodcfg" ]; then
-	msg "If you have modprobe-db installed, running it in recall mode now"
-	if [ -e /usr/bin/modprobed-db ]; then
-	    [[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo. Install via pacman -S sudo and configure to work with this user." && exit 1
-	    sudo /usr/bin/modprobed-db recall
+	### Optionally use running kernel's config
+	# code originally by nous; http://aur.archlinux.org/packages.php?ID=40191
+	if [ -n "$_use_current" ]; then
+		if [[ -s /proc/config.gz ]]; then
+			msg "Extracting config from /proc/config.gz..."
+			# modprobe configs
+			zcat /proc/config.gz > ./.config
+		else
+			warning "You kernel was not compiled with IKCONFIG_PROC!"
+			warning "You cannot read the current config!"
+			warning "Aborting!"
+			exit
+		fi
 	fi
-	msg "Running Steven Rostedt's make localmodconfig now"
-	make localmodconfig
-    fi
 
-    
-    
-    # rewrite configuration
+	if [ "${_kernelname}" != "" ]; then
+		sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
+		sed -i "s|CONFIG_LOCALVERSION_AUTO=.*|CONFIG_LOCALVERSION_AUTO=n|" ./.config
+	fi
+
+	### Optionally disable NUMA since >99% of users have mono-socket systems.
+	# For more, see: https://bugs.archlinux.org/task/31187
+	if [ -n "$_NUMAdisable" ]; then
+		if [ "${CARCH}" = "x86_64" ]; then
+			msg "Disabling NUMA from kernel config..."
+			sed -i -e 's/CONFIG_NUMA=y/# CONFIG_NUMA is not set/' \
+				-i -e '/CONFIG_AMD_NUMA=y/d' \
+				-i -e '/CONFIG_X86_64_ACPI_NUMA=y/d' \
+				-i -e '/CONFIG_NODES_SPAN_OTHER_NODES=y/d' \
+				-i -e '/# CONFIG_NUMA_EMU is not set/d' \
+				-i -e '/CONFIG_NODES_SHIFT=6/d' \
+				-i -e '/CONFIG_NEED_MULTIPLE_NODES=y/d' \
+				-i -e '/# CONFIG_MOVABLE_NODE is not set/d' \
+				-i -e '/CONFIG_USE_PERCPU_NUMA_NODE_ID=y/d' \
+				-i -e '/CONFIG_ACPI_NUMA=y/d' ./.config
+		fi
+	fi
+
+	### Optionally enable BFQ as the default I/O scheduler
+	if [ -n "$_BFQ_enable_" ]; then
+		msg "Setting BFQ as default I/O scheduler..."
+		sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
+			-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	fi
+
+	# set extraversion to pkgrel
+	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
+
+	# don't run depmod on 'make install'. We'll do this ourselves in packaging
+	sed -i '2iexit 0' scripts/depmod.sh
+
+	# get kernel version
+	msg "Running make prepare for you to enable patched options of your choosing"
+	make prepare
+
+	### Optionally load needed modules for the make localmodconfig
+	# See https://aur.archlinux.org/packages/modprobed-db
+		if [ -n "$_localmodcfg" ]; then
+		msg "If you have modprobe-db installed, running it in recall mode now"
+		if [ -e /usr/bin/modprobed-db ]; then
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
+			sudo /usr/bin/modprobed-db recall
+		fi
+		msg "Running Steven Rostedt's make localmodconfig now"
+		make localmodconfig
+	fi
+
+
+
+	# rewrite configuration
 	yes "" | make config >/dev/null
 
 	# save configuration for later reuse
@@ -196,7 +191,6 @@ msg "Patching source with gcc patch to enable more cpus types"
 	else
 		cat .config > "${startdir}/config.last"
 	fi
-    
 }
 
 build() {
@@ -430,25 +424,11 @@ sha512sums=('d77bfd9b1cd524ac50bb5a93808955be2f9bcd2ec0badcc8aa6a63401e212f891fd
             'bdf5fbd0f7b674be9e4c5004d54bd91c7cc82f80b0ad2c534b62bd39b52b1ad6a2694bd645a208dcd1eb1e03e64d60e71bf605e096c69e497cdeda00534cbcc7'
             '274c592f48eba59dc1423ecd926859eb87fbb6ad3431415ed79bcfbaeae59a71d09669edfc4d217ec9ff39da42af21c8a55ceb4d6463c288d3c5f470b19184e8'
             'd9d28e02e964704ea96645a5107f8b65cae5f4fb4f537e224e5e3d087fd296cb770c29ac76e0ce95d173bc420ea87fb8f187d616672a60a0cae618b0ef15b8c8'
-            '57e3ef40ea92fd513a99ed7b82656f1719941bbae92c5d9d8ca8a2537dc6b5fb354ceba139e6c72ab22208e6a9764590c87aa80318cd264cb899ddeb015dbef7'
-            '8ecfad7f8d37ddc86a7f8f34fa77009ff25a2d136cbb656b7a88886f8dea762775eef1b5cc4c76ba330657ccfecf7dedf30d0d71048a450a7436372e3bf12336')
-
+            '5be9f30ec56ad7342faf5b6f89c4faecc6aad0ba81cc1a1c218dede9913b3814290e14bc9ada3843284e7e7c3615c804999ed8fbe3d74778e70a1e0b61c8e68d'
+            '8278389d7b7202bc6577c2d42908c45a48fa90c15443c80651f71caf5bb887f4208a9a241332cee1d199a7c68a5cb23fb33fbd7a1ea1deafc835a39c34b3d049')
 
 
 validpgpkeys=(
               'ABAF11C65A2970B130ABE3C479BE3E4300411886' # Linus Torvalds
               '647F28654894E3BD457199BE38DBBDC86092693E' # Greg Kroah-Hartman
              )
-
-
-
-
-
-
-
-
-
-
-
-
-
