updated on Mon Nov 14 17:00:58 UTC 2011

diff --git a/xtables-addons-multikernel/PKGBUILD b/xtables-addons-multikernel/PKGBUILD
--- a/xtables-addons-multikernel/PKGBUILD
+++ b/xtables-addons-multikernel/PKGBUILD
@@ -1,32 +1,35 @@
-# Maintainer: Lubomir Krajcovic <lubomir.krajcovic@gmail.com>
-# Contributor: Vladimir Kutyavin <vlkut@bk.ru>
+# Maintainer: Lubomir Krajcovic <lubomir.krajcovic(AT)gmail(DOT)com>
+# Contributor: Vladimir Kutyavin <vlkut(AT)bk(DOT)ru>
 pkgname=xtables-addons-multikernel
-pkgver=1.32
-pkgrel=1
-pkgdesc="Successor to patch-o-matic(-ng). Additional extensions for iptables, ip6tables, etc. CHAOS, TARPIT, TEE, DELUDE and other targets; condition, geoip, ipp2p and other matches. Includes ipset package. Multikernel version."
+pkgver=1.39
+pkgrel=4
+pkgdesc="Additional extensions for iptables, ip6tables, etc. CHAOS, TARPIT, TEE, DELUDE and other targets; condition, geoip, ipp2p and other matches. Includes ipset package. Builds for all kernels detected on system."
 arch=('i686' 'x86_64')
 license=('GPL2')
 url="http://xtables-addons.sourceforge.net/"
-depends=('iptables>=1.4.3', 'kernel26>=2.6.17' 'glibc')
-makedepends=('kernel26-headers')
+depends=('iptables>=1.4.12', 'linux>=3.0.0' 'libmnl>=1.0.1' 'glibc')
+makedepends=('linux-headers')
 conflicts=(ipset xtables-addons)
 replaces=(ipset xtables-addons)
 provides=(ipset xtables-addons)
 source=(http://download.sourceforge.net/project/xtables-addons/Xtables-addons/$pkgver/xtables-addons-$pkgver.tar.xz)
-md5sums=('978a04e3e532ef0414ae1dd6a405304d')
+install=$pkgname.install
+md5sums=('63dedce9afd16acfd68efc30c9f55950')
 
 build() {
+	# go to builddir
 	cd $srcdir/xtables-addons-$pkgver
-	# build the modules for all installed kernels
-	for kern in /lib/modules/*; do
-		kern_ver=$(basename $kern)
-		kern_headers="$kern/build"
-		echo -e "\n\n\n>>> building for kernel: $kern_ver\n\n\n"
+	# loop through all detected kernels
+	_PACKAGES=`pacman -Qsq linux`
+	_KERNELS=`pacman -Ql $PACKAGES | grep /modules.alias.bin | sed 's/.*\/lib\/modules\/\(.*\)\/modules.alias.bin/\1/g'`
+	for kernver in $_KERNELS; do
+		kheaders="/lib/modules/$kernver/build"
+		echo -e "\n\n\n>>> building for kernel: $kernver\n\n\n"
 		sleep 3
-		if [ ! -d "$kern_headers" ]; then
-			echo "!!! SKIPPING build for kernel: $kern_ver"
-			echo "!!! could not locate directory: $kern_headers"
-			echo "!!! probably missing kernel headers for $kern_ver ?"
+		if [ ! -d "$kheaders" ]; then
+			echo "!!! SKIPPING build for kernel: $kernver"
+			echo "!!! probably missing kernel headers for $kernver ?"
+			echo "!!! could not locate directory: $kheaders"
 			continue
 		fi
 		./configure \
@@ -35,9 +38,9 @@ build() {
 			--sysconfdir=/etc \
 			--with-xtlibdir=/usr/lib/iptables \
 			--mandir=/usr/share/man \
-			--with-kbuild="$kern_headers"
+			--with-kbuild="$kheaders"
 		make || return 1
-		make DESTDIR=$pkgdir install || return 1 
+		make -j2 DESTDIR=$pkgdir install || return 1
 	done
 	chmod a-x $pkgdir/usr/lib/iptables/*.so
 }
