updated on Wed Dec 19 23:00:03 UTC 2012

diff --git a/vessel/PKGBUILD b/vessel/PKGBUILD
--- a/vessel/PKGBUILD
+++ b/vessel/PKGBUILD
@@ -3,7 +3,7 @@
 pkgname=vessel
 pkgver=20121218
 _pkgver=12082012
-pkgrel=1
+pkgrel=3
 pkgdesc="Vessel is a physics-based, steampunk puzzle-platform video game developed by Strange Loop Games."
 url="http://www.strangeloopgames.com/"
 license=('custom')
@@ -16,30 +16,23 @@ else
     depends=('sdl' 'openal' 'bash' 'gcc-libs')
     optdepends=('libtxc_dxtn: texture decoding for open source ATI and Intel drivers')
 fi
-source=("${pkgname}-${_pkgver}-bin"
-        "http://www.flibitijibibo.com/patch/vessel/linux-12182012.tar.gz"
+source=("http://www.flibitijibibo.com/patch/vessel/linux-12182012.tar.gz"
         "${pkgname}.install"
         "${pkgname}.desktop"
         "${pkgname}.sh")
-md5sums=("cdb4e42ac3dede4478f54bfe15ebfbeb"
-         "7b29418949e442ac52ecf81bd264bc59"
+md5sums=("7b29418949e442ac52ecf81bd264bc59"
          "b25345577b44fbeeba96c6cc87f11c1e"
          "6057700248d5796056b1096962d53877"
          "174d23fe24b496e2cdda1d136327174e")
 makedepends=('unzip')
 options=('!strip')
-# if [[ -f "${source[0]%%:*}" ]]; then
-#   makedepends=('unzip')
-# else
-#   makedepends=('unzip' 'humblepie')
-# fi
 PKGEXT=".pkg.tar"
 
 package() {
   mkdir -p "${pkgdir}/opt/games/${pkgname}"
-  [[ -f "${source[0]}" ]] ||
+  [[ -f "$LOCAL_PACKAGE_SOURCES" ]] ||
     error "Place the game or a symlink to the game in ${startdir}"
-  unzip -u "${source[0]}" -d "${pkgdir}/opt/games/${pkgname}" || true
+  unzip -u "$LOCAL_PACKAGE_SOURCES" -d "${pkgdir}/opt/games/${pkgname}" || true
   rm -rf "${pkgdir}/opt/games/${pkgname}/data/x86"
   rm "${pkgdir}/opt/games/${pkgname}/data/Linux.README"
   rm "${pkgdir}/opt/games/${pkgname}/data/Vessel"
@@ -50,6 +43,21 @@ package() {
   install -Dm755 "${pkgname}".sh "${pkgdir}/usr/bin/${pkgname}"
   chmod 755 "${pkgdir}/opt/games/${pkgname}/data/Vessel" \
     "${pkgdir}/opt/games/${pkgname}/data/x86/vessel.x86"
+}
+
+# Locate a file or folder provided by the user, and symlink it into $srcdir
+_get_local_source() {
+  msg "Looking for '$1'..."
+  declare -A _search=(['build dir']="$startdir"
+                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
+  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
+    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
+    echo -n "    - in $_key ['$_dir'] ... ";
+    if [ -e "$_dir/$1" ]; then
+      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
+    echo "NOT FOUND"
+  done
+  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
 
 # vim: ft=PKGBUILD sts=2 ts=2 sw=2 et
