updated on Thu Feb  7 10:10:41 UTC 2013

diff --git a/vessel/PKGBUILD b/vessel/PKGBUILD
--- a/vessel/PKGBUILD
+++ b/vessel/PKGBUILD
@@ -1,67 +1,72 @@
 # Maintainer: afettouhi <A.Fettouhi@gmail.com>
+# Contributor: David Miller <moebius282 e4at gmail D0_T com>
 
 pkgname=vessel
 pkgver=20121219
-_pkgver=12082012
-pkgrel=2
-pkgdesc="Vessel is a physics-based, steampunk puzzle-platform video game developed by Strange Loop Games."
+_binver=12082012
+pkgrel=3
+pkgdesc="A physics-based, steampunk puzzle-platform game"
 url="http://www.strangeloopgames.com/"
 license=('custom')
 arch=('i686' 'x86_64')
 groups=("humble-indie-bundle6" "games")
 if [ "$CARCH" = "x86_64" ]; then
     depends=('lib32-sdl' 'lib32-openal' 'bash' 'lib32-gcc-libs')
-    optdepends=('lib32-libtxc_dxtn: texture decoding for open source ATI and Intel drivers')
+    optdepends=('lib32-libtxc_dxtn: texture decoding support for open source graphics drivers')
 else
     depends=('sdl' 'openal' 'bash' 'gcc-libs')
-    optdepends=('libtxc_dxtn: texture decoding for open source ATI and Intel drivers')
+    optdepends=('libtxc_dxtn: texture decoding support for open source graphics drivers')
 fi
-source=("http://www.flibitijibibo.com/patch/vessel/linux-12192012.tar.gz"
-        "${pkgname}.install"
-        "${pkgname}.desktop"
-        "${pkgname}.sh")
-md5sums=("10fd5d8e6e30f3db9e7487c35e435126"
-         "b25345577b44fbeeba96c6cc87f11c1e"
-         "6057700248d5796056b1096962d53877"
-         "174d23fe24b496e2cdda1d136327174e")
-makedepends=('unzip')
-options=('!strip')
+
+source=("hib://${pkgname}-${_binver}-bin"
+        'http://www.flibitijibibo.com/patch/vessel/linux-12192012.tar.gz'
+        "${pkgname}.desktop")
+sha256sums=('26bdfd3cf38853b266e24bf4a2ce846c64cf989563c50307e955581a6566fcee'
+            'bf7708a195ef3546c8c3b30b74ff427d5fe5e1548991b4f291264bbd275fe17e'            
+            '941c7534f8a557f5cdbbec0f19a4e13c76d393006bdb6e1dafd5529b5c9b6697')
+makedepends=('unzip' 'imagemagick')
+#options=('!strip')
 PKGEXT=".pkg.tar"
 
-_archive="${pkgname}-${_pkgver}-bin"
-_archive_md5='cdb4e42ac3dede4478f54bfe15ebfbeb'
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+
 
 package() {
-  mkdir -p "${pkgdir}/opt/games/${pkgname}"
-  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
-  error "Unable to find the game archive. Please download it from your Humble Bundle page, and place it into one of the above locations."
-  exit 1; }
-  unzip -u "${srcdir}/${_archive}" -d "${pkgdir}/opt/games/${pkgname}" || true
-  rm -rf "${pkgdir}/opt/games/${pkgname}/data/x86"
-  rm "${pkgdir}/opt/games/${pkgname}/data/Linux.README"
-  rm "${pkgdir}/opt/games/${pkgname}/data/Vessel"
-  rm "${pkgdir}/opt/games/${pkgname}/data/Vessel.bmp"
-  tar -zxvf linux-12192012.tar.gz -C "${pkgdir}/opt/games/${pkgname}/data/"
-  find "${pkgdir}" -type f -exec chmod 644 "{}" +
-  install -Dm644 "${pkgname}".desktop "${pkgdir}/usr/share/applications/${pkgname}.desktop"
-  install -Dm755 "${pkgname}".sh "${pkgdir}/usr/bin/${pkgname}"
-  chmod 755 "${pkgdir}/opt/games/${pkgname}/data/Vessel" \
-    "${pkgdir}/opt/games/${pkgname}/data/x86/vessel.x86"
-}
 
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
+  mkdir -p "${pkgdir}/opt/${pkgname}/"
+
+# unzip is stupid..
+  unzip -qq "${srcdir}/${pkgname}-${_binver}-bin" -d "${pkgdir}/opt/tmp/" 'data/*' || true
+
+  mv "${pkgdir}/opt/tmp/data/"* "${pkgdir}/opt/${pkgname}/"
+  rm -r "${pkgdir}/opt/tmp/"
+
+  tar --overwrite -zxf "${srcdir}/linux-12192012.tar.gz" -C "${pkgdir}/opt/${pkgname}/"
+
+  for i in 'libSDL-1.2.so.0' 'libstdc++.so.6'; do
+    rm "${pkgdir}/opt/${pkgname}/x86/${i}"*
   done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
+
+#the spec only specifies png, svg and xpm..
+  convert "${pkgdir}/opt/${pkgname}/Vessel.bmp" "${pkgdir}/opt/${pkgname}/${pkgname}.png"
+  rm "${pkgdir}/opt/${pkgname}/Vessel.bmp"
+
+  chown -R root:root "${pkgdir}/opt/${pkgname}/"
+
+  sed -i -e 's|`dirname "$0"`|$(dirname \"$(readlink -f \"$0\")\")|' "${pkgdir}/opt/${pkgname}/Vessel" 
+
+  install -D -m644 "${srcdir}/${pkgname}.desktop" "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+  install -D -m644 "${pkgdir}/opt/${pkgname}/${pkgname}.png" "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
+  mkdir "${pkgdir}/usr/bin/"
+  ln -s "/opt/${pkgname}/Vessel" "${pkgdir}/usr/bin/${pkgname}"
 }
