updated on Thu Dec 20 12:00:02 UTC 2012

diff --git a/vessel/PKGBUILD b/vessel/PKGBUILD
--- a/vessel/PKGBUILD
+++ b/vessel/PKGBUILD
@@ -30,7 +30,7 @@ PKGEXT=".pkg.tar"
 
 package() {
   mkdir -p "${pkgdir}/opt/games/${pkgname}"
-  _get_local_source "${pkgname}-${_pkgver}-bin" || error "Unable to find the game archive"; exit 1
+  _get_local_source "${pkgname}-${_pkgver}-bin" || error "Unable to find the game archive" exit 1;
   unzip -u "${srcdir}/${pkgname}-${_pkgver}-bin" -d "${pkgdir}/opt/games/${pkgname}" || true
   rm -rf "${pkgdir}/opt/games/${pkgname}/data/x86"
   rm "${pkgdir}/opt/games/${pkgname}/data/Linux.README"
@@ -44,7 +44,7 @@ package() {
     "${pkgdir}/opt/games/${pkgname}/data/x86/vessel.x86"
 }
 
-# Locate a file or folder provided by the user, and symlink it into $srcdir
+# Locate a file or folder provided by the user, and symlink it into ${srcdir}
 _get_local_source() {
   msg "Looking for '$1'..."
   declare -A _search=(['build dir']="$startdir"
@@ -53,8 +53,8 @@ _get_local_source() {
     if [ -z "$_dir" ]; then _dir="<undefined>"; fi
     echo -n "    - in $_key ['$_dir'] ... ";
     if [ -e "$_dir/$1" ]; then
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
+      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "${srcdir}/$1"; break; fi
     echo "NOT FOUND"
   done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
+  if [ ! -e "${srcdir}/$1" ]; then return 1; fi
 }
