updated on Sat Nov  1 00:00:17 UTC 2014

diff --git a/freenet/freenet.install b/freenet/freenet.install
--- a/freenet/freenet.install
+++ b/freenet/freenet.install
@@ -1,18 +1,24 @@
 post_install() {
-  echo "==> A user 'freenet' is created which owns the /opt/freenet directory)"
-  groupadd -r freenet
-  useradd -r -g freenet -d /opt/freenet -s /bin/bash freenet &>/dev/null
-  chown -R freenet:freenet /opt/freenet
-  echo "==> Add yourself to the freenet group to access files in /opt/freenet"
+  getent passwd freenet &>/dev/null || {
+        echo -n ">>> Creating freenet system user... "
+        useradd --system \
+                --user-group \
+                --home /opt/freenet \
+                freenet &&
+        echo "ok" || echo "fail"
+    }
+    chown -R freenet:freenet /opt/freenet
 }
 
 post_upgrade() {
-  chown -R freenet:freenet /opt/freenet
+    chown -R freenet:freenet /opt/freenet
 }
 
 pre_remove() {
-  userdel freenet &>/dev/null
-  groupdel freenet &>/dev/null
-  echo "==> /opt/freenet is not removed if you have used Freenet. Delete manually"
-  echo "    if you want to clear cache, downloads, etc."
+    getent passwd i2p &>/dev/null && {
+        echo -n ">>> Removing freenet system user... "
+        userdel freenet &&
+            groupdel freenet
+        echo "ok"
+    }
 }
