updated on Tue Jul  9 22:09:03 UTC 2013

diff --git a/limbo/PKGBUILD b/limbo/PKGBUILD
--- a/limbo/PKGBUILD
+++ b/limbo/PKGBUILD
@@ -1,10 +1,11 @@
 # Contributor: Can Celasun <dcelasun[at]gmail[dot]com>
+# Contributor: C5OK5Y <claudiokozicky[at]gmail[dot]com>
 # Maintainer: mirandir <mirandir[at]orange[dot]com>
 
 pkgname=limbo
 pkgver=1.3
-pkgrel=4
-pkgdesc="LIMBO is a modern classic, putting players in control of a boy's journey through a tense and hostile world. (This version uses installed wine and allows to choose the language of the game if zenity is installed.)"
+pkgrel=5
+pkgdesc="LIMBO is a modern classic, putting players in control of a boy's journey through a tense and hostile world. (This version uses installed wine and allows to choose the language of the game if zenity is installed.) (HIB)"
 url="http://limbogame.org/"
 license=('custom: "commercial"')
 arch=('i686' 'x86_64')
@@ -15,35 +16,13 @@ conflicts=('limbo_wine')
 options=(!strip)
 install=install
 pkgname_real=limbo
-source=("${pkgname_real}.desktop" "${pkgname_real}.sh" "launch_${pkgname_real}.sh")
+source=("${pkgname_real}.desktop" "${pkgname_real}.sh" "launch_${pkgname_real}.sh" "hib://${pkgname_real}-${pkgver}.tar.gz")
 md5sums=('d4ec36a5690362211bddbf15d09a05a1'
          'a2d779b07825b38ccd4520f772b461dd'
-         '3ddbced3bc9b8661f1c381d7464e55f0')
+         '3ddbced3bc9b8661f1c381d7464e55f0'
+         '723815846d4cc3f68604b94c055a775c')
 
-if [[ $CARCH == x86_64 ]]; then
-   _gamepkg="${pkgname_real}-${pkgver}.tar.gz"
-else
-   _gamepkg="${pkgname_real}-${pkgver}.tar.gz"
-fi
-
-build() {
-    cd ${srcdir}
-    msg "You need a full copy of this game in order to install it"
-    msg "Searching for ${_gamepkg} in dir: \"$startdir\""
-    pkgpath=$startdir
-    if [[ ! -f "$startdir/${_gamepkg}" ]]; then
-        error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
-        read pkgpath
-        if [[ -f "${pkgpath}/${_gamepkg}" ]]; then
-            ln -fs "${pkgpath}/${_gamepkg}" .
-	    else
-            error "Unable to find game package."
-            return 1
-        fi
-    fi
-    msg "Found game package, installing..."
-    tar xzf "${pkgpath}/${_gamepkg}"
-}
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 package(){
     cd ${srcdir}
