updated on Thu Jan  2 00:24:38 UTC 2014

diff --git a/alps/PKGBUILD b/alps/PKGBUILD
--- a/alps/PKGBUILD
+++ b/alps/PKGBUILD
@@ -4,9 +4,11 @@
 #debug=true
 
 pkgname=alps
-_pkgver=2.1.1-r6176
-pkgver=2.1.1_r6176
-pkgrel=2
+_pkgver=2.2.b1-r7195
+pkgver=2.2.b1_r7195
+#_pkgver=2.1.1-r6176
+#pkgver=2.1.1_r6176
+pkgrel=1
 pkgdesc="Provides physics simulation code for strongly correlated quantum mechanical systems"
 arch=('i686' 'x86_64')
 url="http://alps.comp-phys.org"
@@ -14,43 +16,46 @@ license=('custom:ALPS')
 depends=('boost' 'fftw' 'python2-scipy' 'python2-h5py' 'python2-matplotlib')
 makedepends=('cmake' 'gcc-fortran')
 #optdepends=('foo: description')
-source=(http://alps.comp-phys.org/static/software/releases/${pkgname}-${_pkgver}-src.tar.gz)
-md5sums=('f4c9b044ed9ee8964c449a473bd75842')
+source=(http://alps.comp-phys.org/static/software/releases/alps-${_pkgver}-src.tar.gz)
+md5sums=('035ea019726d164fe2b7b6b8f0dca09f')
+#md5sums=('f4c9b044ed9ee8964c449a473bd75842')
 [ "$debug" = "true" ] && options=(!strip)
 
 build() {
   # http://alps.comp-phys.org/mediawiki/index.php/Download_and_install_ALPS_2#Build_ALPS
   
-  cd "${srcdir}/${pkgname}-${_pkgver}-src/alps"
+  cd "${srcdir}/alps-${_pkgver}-src/alps"
   
   # this line is recommended, but gave a compilation error
-  # [ "$CARCH" = "x86_64" ] && _CMAKE=-DLAPACK_64_BIT=ON
+  # [ "$CARCH" = "x86_64" ] && _CMAKE_ARGS=-DLAPACK_64_BIT=ON
   
   if [ "$debug" = "true" ]
   then CFLAGS="-g $CFLAGS"
        CXXFLAGS="-g $CXXFLAGS"
   fi
   
-  cmake ./ -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_INTERPRETER=/usr/bin/python2 ${_CMAKE}
+  mkdir -p build
+  cd build
+  
+  _CMAKE_ARGS="../ -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_INTERPRETER=/usr/bin/python2 $_CMAKE_ARGS"
+  cmake $_CMAKE_ARGS || (
+    # morealaz's suggestion (2014-01-01): set variables to empty string and reconfigure so that the compilation can continue
+    for v in HDF5_dl_LIBRARY_DEBUG HDF5_hdf5_LIBRARY_DEBUG HDF5_hdf5_hl_LIBRARY_DEBUG HDF5_m_LIBRARY_DEBUG HDF5_pthread_LIBRARY_DEBUG HDF5_z_LIBRARY_DEBUG;
+    do   sed -i "s|$v:FILEPATH=$v-NOTFOUND|$v:FILEPATH=|" CMakeCache.txt;
+    done &&
+    cmake $_CMAKE_ARGS
+  )
   make
   make test || true
   
-  # 94% tests passed, 6 tests failed out of 98
-  # The following tests FAILED:
-  #          23 - test_deque (Failed)
-  #          24 - test_vector (Failed)
-  #          95 - python_hlist_test (Failed)
-  #          96 - python_mcdata (Failed)
-  #          97 - python_pyhdf5 (Failed)
-  #          98 - python_mcanalyze (Failed)
+  # 100% tests passed, 0 tests failed out of 141
 }
 
 package() {
-  cd "${srcdir}/${pkgname}-${_pkgver}-src/alps"
+  cd "${srcdir}/alps-${_pkgver}-src/alps/build"
   make DESTDIR="${pkgdir}" install
-  install -Dm644 LICENSE.txt "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  install -Dm644 ../LICENSE.txt "${pkgdir}/usr/share/licenses/alps/LICENSE"
   
-  # uncomment if installing into /usr
   cd "${pkgdir}"
   mv usr/tutorials usr/share/alps/
   
