updated on Sun Jul 22 08:00:15 UTC 2012

diff --git a/llvmlinux-git/PKGBUILD b/llvmlinux-git/PKGBUILD
--- a/llvmlinux-git/PKGBUILD
+++ b/llvmlinux-git/PKGBUILD
@@ -136,7 +136,7 @@ _build_dir="${_build_dir:-$srcdir}"
 #######
 # Make the kernel build process verbose
 #
-# _verbose=1
+ _verbose=1
 
 
 # internal variables
@@ -173,8 +173,8 @@ build() {
     export CXXFLAGS="$CFLAGS"
     export HOST="${CARCH}-none-linux-gnu"
     export HOSTTRIPLE="${CARCH}-pc-linux-gnu"
-    export HOSTCC_FOR_BUILD=gcc #no idea why, but this is default in make-kernel.sh
-    export HOSTCC=$HOSTCC_FOR_BUILD #no idea why, but this is default in make-kernel.sh
+    export HOSTCC_FOR_BUILD=clang #no idea why, but this is default=gcc in make-kernel.sh
+    export HOSTCC=$HOSTCC_FOR_BUILD #no idea why, but this is default=gcc in make-kernel.sh
 
     cd $srcdir
     msg "checking out LLVM-specific linux patches and config(s)"
@@ -192,8 +192,9 @@ build() {
 	cp ${srcdir}/${_llvm_gitname}/arch/all/patches/*.patch $startdir/patches/
 	cp ${srcdir}/${_llvm_gitname}/arch/${_lll_target}/patches/*.patch $startdir/patches/	
 	cp ${srcdir}/${_llvm_gitname}/targets/${_lll_target}/patches/*.patch $startdir/patches/	
-#	msg2 "temporary solution: remove patches that fail to apply"
-#       msg2 "temporary solution: sed-fix variants of patches that fail to apply"
+	msg2 "temporary solution: overwrite patches that fail to apply with a fixed variant"
+#	cp $startdir/*.patch $startdir/patches/
+
 	
 	msg2 "done"
 
@@ -257,7 +258,7 @@ build() {
 	for i in "${patches[@]}" "$startdir/patches/"*; do
 		msg2 "Applying ${i##*/}..."
 		# using git to apply patches.
-		git am "$i" || return 1
+		patch -F3 -Np1 -i "$i" || (error "Applying ${i##*/} failed" && return 0)
 	done
 	shopt -u nullglob
 
