updated on Fri Jul 18 00:00:20 UTC 2014

diff --git a/brother-dcp9010cn/brlpdwrapperdcp9010cn b/brother-dcp9010cn/brlpdwrapperdcp9010cn
--- a/brother-dcp9010cn/brlpdwrapperdcp9010cn
+++ b/brother-dcp9010cn/brlpdwrapperdcp9010cn
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# Copyright (C) 2005 Brother. Industries, Ltd.
+# Copyright (C) 2005-2011 Brother. Industries, Ltd.
 #                                    Ver1.10
 
 # This program is free software; you can redistribute it and/or modify it
@@ -34,7 +34,7 @@ PPDC=`printenv | grep "PPD="`
 PPDC=`echo $PPDC | sed -e 's/PPD=//'`
 
 if [ "$PPDC" = "" ]; then
-    PPDC="/usr/share/cups/model/brdcp9010cn.ppd"
+    PPDC="/usr/share/cups/model/brother_dcp9010cn_printer_en.ppd"
 fi
 
 
@@ -44,9 +44,9 @@ if [ $LOGFILE != "/dev/null" ]; then
     date                                                           >$LOGFILE
   else
     if [ -e $LOGFILE ]; then
-	    date                                                        >>$LOGFILE
+        date                                                        >>$LOGFILE
     else
-	    date                                                        >$LOGFILE
+        date                                                        >$LOGFILE
     fi
   fi
     echo "arg0 = $0"                                           >>$LOGFILE
@@ -62,39 +62,39 @@ fi
 INPUT_TEMP_PS=`mktemp /tmp/br_input_ps.XXXXXX`
 
 nup="cat"
-if [ "" != '' ] && [ $NUPENABLE != 0 ]; then
+if [ "`echo $5 | grep 'Nup='`" != '' ] && [ $NUPENABLE != 0 ]; then
 
-	if   [ "" != '' ]; then
-		nup="psnup -64"
-	elif [ "" != '' ]; then
-		nup="psnup -32"
-	elif [ "" != '' ]; then
-		nup="psnup -25"
-	elif [ "" != '' ]; then
-		nup="psnup -16"
-	elif [ "" != '' ]; then
-		nup="psnup -8"
-	elif [ "" != '' ]; then
-		nup="psnup -6"
-	elif [ "" != '' ]; then
-		nup="psnup -4"
-	elif [ "" != '' ]; then
-		nup="psnup -2"
-	elif [ "" != '' ]; then
-		nup="cat"
-	fi
-	echo   "NUP=$nup"                                      >>$LOGFILE
+    if   [ "`echo $5 | grep 'Nup=64'`" != '' ]; then
+        nup="psnup -64"
+    elif [ "`echo $5 | grep 'Nup=32'`" != '' ]; then
+        nup="psnup -32"
+    elif [ "`echo $5 | grep 'Nup=25'`" != '' ]; then
+        nup="psnup -25"
+    elif [ "`echo $5 | grep 'Nup=16'`" != '' ]; then
+        nup="psnup -16"
+    elif [ "`echo $5 | grep 'Nup=8'`" != '' ]; then
+        nup="psnup -8"
+    elif [ "`echo $5 | grep 'Nup=6'`" != '' ]; then
+        nup="psnup -6"
+    elif [ "`echo $5 | grep 'Nup=4'`" != '' ]; then
+        nup="psnup -4"
+    elif [ "`echo $5 | grep 'Nup=2'`" != '' ]; then
+        nup="psnup -2"
+    elif [ "`echo $5 | grep 'Nup=1'`" != '' ]; then
+        nup="cat"
+    fi
+    echo   "NUP=$nup"                                      >>$LOGFILE
    if [ -e /usr/bin/psnup ]; then
        if [ $# -ge 7 ]; then
-	       cat $6  | $nup > $INPUT_TEMP_PS
+           cat $6  | $nup > $INPUT_TEMP_PS
        else
-	       cat       | $nup > $INPUT_TEMP_PS
+           cat       | $nup > $INPUT_TEMP_PS
        fi
    else
        if [ $# -ge 7 ]; then
-	       cp $6  $INPUT_TEMP_PS
+           cp $6  $INPUT_TEMP_PS
        else
-	       cat    > $INPUT_TEMP_PS
+           cat    > $INPUT_TEMP_PS
        fi
    fi
 else
@@ -104,35 +104,34 @@ else
       cat    > $INPUT_TEMP_PS
    fi
 fi
-if [ -e "/usr/local/Brother/Printer/dcp9010cn/lpd/filterdcp9010cn" ]; then
+if [ -e "/opt/brother/Printers/dcp9010cn/lpd/filterdcp9010cn" ]; then
        :
 else
-    echo "ERROR: /usr/local/Brother/Printer/dcp9010cn/lpd/filterdcp9010cn does not exist"   >>$LOGFILE
+    echo "ERROR: /opt/brother/Printers/dcp9010cn/lpd/filterdcp9010cn does not exist"   >>$LOGFILE
     errorcode=30
     exit
 fi
 
 CUPSOPTION=`echo "$5 Copies=1" | sed -e 's/BrMirror=OFF/MirrorPrint=OFF/' -e 's/BrMirror=ON/MirrorPrint=ON/' -e 's/BrChain/Chain/' -e 's/BrBrightness/Brightness/' -e 's/BrContrast/Contrast/' -e 's/BrHalfCut/HalfCut/' -e 's/BrAutoTapeCut/AutoCut/' -e 's/BrHalftonePattern/Halftone/' -e 's/Binary/Binary/' -e 's/Dither/Dither/' -e 's/ErrorDiffusion/ErrorDiffusion/' -e 's/BrSheets/Sheets/' -e 's/multiple-document-handling/Collate/' -e 's/separate-documents-collated-copies/ON/' -e 's/separate-documents-uncollated-copies/OFF/'`
-if [ -e "/usr/local/Brother/Printer/dcp9010cn/cupswrapper/brcupsconfpt1" ]; then
+if [ -e "/opt/brother/Printers/dcp9010cn/cupswrapper/brcupsconfpt1" ]; then
   if [ $DEBUG = 0 ]; then
-     /usr/local/Brother/Printer/dcp9010cn/cupswrapper/brcupsconfpt1  DCP9010CN  $PPDC 0 "$CUPSOPTION" "dcp9010cn">> /dev/null
+     /opt/brother/Printers/dcp9010cn/cupswrapper/brcupsconfpt1  DCP9010CN  $PPDC 0 "$CUPSOPTION" "dcp9010cn">> /dev/null
   else
-     /usr/local/Brother/Printer/dcp9010cn/cupswrapper/brcupsconfpt1  DCP9010CN  $PPDC $LOGCLEVEL "$CUPSOPTION" "dcp9010cn">>$LOGFILE
+     /opt/brother/Printers/dcp9010cn/cupswrapper/brcupsconfpt1  DCP9010CN  $PPDC $LOGCLEVEL "$CUPSOPTION" "dcp9010cn">>$LOGFILE
   fi
 fi
 
 if [ $DEBUG -lt 10 ]; then
-    cat    $INPUT_TEMP_PS | /usr/local/Brother/Printer/dcp9010cn/lpd/filterdcp9010cn "$$" "CUPS" "USB"
+    cat    $INPUT_TEMP_PS | /opt/brother/Printers/dcp9010cn/lpd/filterdcp9010cn "$$" "CUPS" "USB"
 
     if [ $LOGLEVEL -gt 2 ];  then
-	   if [ $LOGFILE != "/dev/null" ]; then
-	     echo ""                                                >>$LOGFILE
-	     echo "    ------PostScript Data-------"                >>$LOGFILE
-	     cat    $INPUT_TEMP_PS                                  >>$LOGFILE
-	   fi
+       if [ $LOGFILE != "/dev/null" ]; then
+         echo ""                                                >>$LOGFILE
+         echo "    ------PostScript Data-------"                >>$LOGFILE
+         cat    $INPUT_TEMP_PS                                  >>$LOGFILE
+       fi
     fi
 fi
 rm -f  $INPUT_TEMP_PS
 
-exit 
-
+exit $errorcode
