updated on Fri May  3 08:18:09 UTC 2013

diff --git a/go-hg/PKGBUILD b/go-hg/PKGBUILD
--- a/go-hg/PKGBUILD
+++ b/go-hg/PKGBUILD
@@ -1,28 +1,39 @@
-# Maintainer: Serge Zirukin <ftrvxmtrx gmail>
-# Contributor: Daniel YC Lin <dlin.tw gmail>
-# Contributor: Alexander Rødseth <rodseth gmail>
-# Contributor: Christian Himpel <chressie gmail>
+# Maintainer: Daniel YC Lin <dlin.tw gmail>
+# Contributor: Alexander Rødseth <rodseth@gmail.com>
+# Contributor: Vesa Kaihlavirta <vegai@iki.fi>
+# Contributor: Rémy Oudompheng  <remy@archlinux.org>
 # Contributor: Andres Perera <andres87p gmail>
-# Contributor: Ashok Gautham <ScriptDevil gmail>
-# Contributor: Matthew Bauer <mjbauer95 gmail>
-# Contributor: Vesa Kaihlavirta <vegai iki fi>
+# Contributor: Matthew Bauer <mjbauer95@gmail.com>
+# Contributor: Christian Himpel <chressie@gmail.com>
+# Contributor: Mike Rosset <mike.rosset@gmail.com>
+
 pkgname=go-hg
-pkgver=14790
+pkgver=16743
 pkgrel=1
-pkgdesc='Google Go compiler and tools (hg tip)'
-arch=('x86_64' 'i686')
-url="http://golang.org/"
-license=('custom')
-depends=()
-makedepends=('ed' 'mercurial')
-provides=('go')
+pkgdesc='Google Go compiler support multi-platforms(hg tip)'
+# ref valid platforms http://golang.org/doc/install/source#environment
+_platforms="linux_arm windows_386"
+if [ "$CARCH" == 'x86_64' ]; then
+    _platforms="linux_amd64 $_platforms"
+    export GOARCH=amd64
+elif [ "$CARCH" == 'i686' ]; then
+    _platforms="linux_386 $_platforms"
+fi
 conflicts=('go')
-options=(!strip !makeflags)
-install=go.install
+replaces=('go')
+provides=('go')
+arch=('x86_64' 'i686')
+url='http://golang.org/'
+license=('custom')
+depends=('perl' 'gawk')
+makedepends=('inetutils')
+options=('!strip')
+#options=('strip')
+install='go.install'
+#backup=('usr/lib/go/bin')
 source=('go.sh')
-sha256sums=('67394dd14510e351b0b29a4bfbcbcc60b61bf285994f67f849f7501a5d4493b0')
 _hgroot=https://go.googlecode.com/hg/
-_hgrepo=go
+_hgrepo=go-src
 
 build() {
   cd "$srcdir"
@@ -39,64 +50,147 @@ build() {
   msg "Mercurial checkout done or server timeout"
   msg "Starting build..."
 
-  rm -rf "$srcdir/$_hgrepo-build"
-  hg clone "$srcdir/$_hgrepo" "$srcdir/$_hgrepo-build"
-  # prevent http://code.google.com/p/go/issues/detail?id=3263
-  mv $srcdir/$_hgrepo-build/lib/codereview/codereview.cfg \
-     $srcdir/$_hgrepo-build/lib/codereview/codereview.cfg.orig
-  cd "$srcdir/$_hgrepo-build/src"
+  rm -rf "$srcdir/go"
+  hg clone "$srcdir/$_hgrepo" "$srcdir/go"
 
-  unset GOARCH GOBIN GOOS GOROOT
-  if test "$CARCH" == x86_64 ; then
-    LC_ALL=C GOROOT_FINAL=/opt/go ./make.bash
+  cd "$srcdir/go/src"
+
+  export GOROOT_FINAL=/usr/lib/go
+  # export GOARM=5 # if without FPU
+  for platform in $_platforms ; do
+    export GOOS=${platform%%_*}
+    export GOARCH=${platform##*_}
+    msg "building $GOOS $GOARCH"
+    bash make.bash --no-clean
+  done
+}
+
+check() {
+  cd "$srcdir/go"
+
+  # Only test for linux and the architecture we're on
+  export GOOS=linux
+  if [ "$CARCH" == 'x86_64' ]; then
+    export GOARCH=amd64
+  elif [ "$CARCH" == 'i686' ]; then
+    export GOARCH=386
   else
-    LC_ALL=C GOROOT_FINAL=/opt/go GOARCH=386 GOHOSTARCH=386 ./make.bash
+    export GOARCH=arm
   fi
+
+  export GOROOT="$srcdir/go"
+  export PATH="$srcdir/go/bin:$PATH"
+
+  mkdir -p hello
+  cd hello
+  echo "package main ; func main() {}" > hello.go
+  for platform in $_platforms ; do
+    msg "checking GOOS=${platform%%_*} GOARCH=${platform##*_} go build"
+    GOOS=${platform%%_*} GOARCH=${platform##*_} go build
+  done
+  cd ..
+
+  # TestSimpleMulticastListener will fail in standard chroot.
+  #cd src && bash run.bash --no-rebuild || true
 }
 
 package() {
-  cd "$srcdir/$_hgrepo-build"
+  cd "$srcdir/go"
+  export GOROOT="$srcdir/go"
 
-  msg2 "Packaging files..."
-  mkdir -p $pkgdir/opt/go
-  find * -type f ! -executable -print0 | xargs -0 -I {} install -Dm644 {} $pkgdir/opt/go/{}
-  find * -type f -executable -print0 | xargs -0 -I {} install -Dm755 {} $pkgdir/opt/go/{}
+  install -Dm644 LICENSE \
+    $pkgdir/usr/share/licenses/go/LICENSE
+  install -Dm644 misc/bash/go \
+    $pkgdir/usr/share/bash-completion/completions/go
+  install -Dm644 misc/emacs/go-mode-load.el \
+    $pkgdir/usr/share/emacs/site-lisp/go-mode-load.el
+  install -Dm644 misc/emacs/go-mode.el \
+    $pkgdir/usr/share/emacs/site-lisp/go-mode.el
+  install -Dm644 misc/zsh/go \
+    $pkgdir/usr/share/zsh/site-functions/_go
+
+  for f in ftdetect/gofiletype.vim autoload/go/complete.vim indent/go.vim \
+    ftplugin/go/fmt.vim ftplugin/go/import.vim syntax/go.vim syntax/godoc.vim \
+    plugin/godoc.vim;
+  do
+    install -Dm644 misc/vim/$f $pkgdir/usr/share/vim/vimfiles/$f
+  done
+
+  mkdir -p $pkgdir/{etc/profile.d,usr/{share/go,lib/go,lib/go/src,lib/go/site}}
+
+  cp -r doc misc -t $pkgdir/usr/share/go
+  ln -s /usr/share/go/doc $pkgdir/usr/lib/go/doc
+  cp -a bin $pkgdir/usr
+  cp -a pkg $pkgdir/usr/lib/go
+  cp -a $GOROOT/src/pkg $pkgdir/usr/lib/go/src/
+  cp -a $GOROOT/src/cmd $pkgdir/usr/lib/go/src/cmd
+  cp -a $GOROOT/src/lib9 $pkgdir/usr/lib/go/src/
+  cp -a $GOROOT/lib $pkgdir/usr/lib/go/
+  cp -a $GOROOT/include $pkgdir/usr/lib/go/
+
+  install -Dm644 src/Make.* $pkgdir/usr/lib/go/src
+
+  # Remove object files from target src dir
+  find $pkgdir/usr/lib/go/src/ -type f -name '*.[ao]' -delete
+
+  # Fix for FS#32813
+  find $pkgdir -type f -name sql.go -exec chmod -x {} \;
+
+  # Remove all executable source files
+  find $pkgdir/usr/lib/go/src/pkg -type f -executable -delete
+
+  # Headers for C modules
+  install -Dm644 src/pkg/runtime/runtime.h \
+    $pkgdir/usr/lib/go/src/pkg/runtime/runtime.h
+  install -Dm644 src/pkg/runtime/cgocall.h \
+    $pkgdir/usr/lib/go/src/pkg/runtime/cgocall.h
+
+  # For packages that source /etc/profile.d/go.sh
   install -Dm755 $srcdir/go.sh $pkgdir/etc/profile.d/go.sh
 
-  msg2 "Packaging editor-related files..."
-  install -Dm644 misc/bash/go "$pkgdir/etc/bash_completion.d/go"
-  install -Dm644 misc/zsh/go "$pkgdir/usr/share/zsh/site-functions/_go"
-  install -Dm644 misc/emacs/go-mode-load.el "$pkgdir/usr/share/emacs/site-lisp/go-mode-load.el"
-  install -Dm644 misc/emacs/go-mode.el "$pkgdir/usr/share/emacs/site-lisp/go-mode.el"
-  for f in ftdetect/gofiletype.vim autoload/go/complete.vim indent/go.vim \
-    ftplugin/go/fmt.vim ftplugin/go/import.vim \
-    syntax/go.vim syntax/godoc.vim plugin/godoc.vim ;
-  do
-    install -Dm644 "misc/vim/$f" "$pkgdir/usr/share/vim/vimfiles/$f"
-  done
+  # This is to make go get code.google.com/p/go-tour/gotour and
+  # then running the gotour executable work out of the box.
+  ln -sf /usr/bin $pkgdir/usr/lib/go/bin
 
-  msg2 "Packaging license..."
-  install -Dm644 LICENSE $pkgdir/usr/share/licenses/go/LICENSE
+  # For godoc
+  install -Dm644 favicon.ico $pkgdir/usr/lib/go/favicon.ico
+
+  rm -f $pkgdir/usr/share/go/doc/articles/wiki/get.bin
+
+  install -Dm644 VERSION.cache $pkgdir/usr/lib/go/VERSION
+
+  # Clean up
+  for platform in $_platforms ; do
+    if [ $CARCH = x86  -a $platform = linux_386 ] ; then
+      continue
+    elif [ $CARCH = x86_64  -a $platform = linux_amd64 ] ; then
+      continue
+    fi
+    rm -r "$pkgdir/usr/bin/$platform"
+    rm -r "$pkgdir/usr/lib/go/pkg/tool/$platform"
+  done
 
   msg2 "strip binary files"
-  find $pkgdir/opt/go -type f 2>/dev/null | while read binary ; do
-    case "$(file -bi "$binary")" in
-    *application/x-sharedlib*)  # Libraries (.so)
-      strip $STRIP_SHARED "$binary" 2>/dev/null || true ;;
-    *application/x-archive*)    # Libraries (.a)
-      strip $STRIP_STATIC "$binary"  2>/dev/null || true ;;
-    *application/x-executable*) # Binaries
-      strip $STRIP_BINARIES "$binary" || true ;;
-    esac
-  done
-
-  msg2 "set same timestamps on all files"
-  find $pkgdir/opt/go -type f -exec touch -r $pkgdir/opt/go/bin/go {} \;
+	local binary strip_flags
+	find $pkgdir/usr/bin -type f -perm -u+w -print0 2>/dev/null | while read -d '' binary ; do
+		case "$(file -bi "$binary")" in
+			*application/x-sharedlib*)  # Libraries (.so)
+				strip_flags="$STRIP_SHARED";;
+			*application/x-archive*)    # Libraries (.a)
+				strip_flags="$STRIP_STATIC";;
+			*application/x-executable*) # Binaries
+				strip_flags="$STRIP_BINARIES";;
+			*)
+				continue ;;
+		esac
+		strip_file "$binary" ${strip_flags}
+	done
 
   msg2 "changelog(last 10)"
   (cd  $srcdir/$_hgrepo ; \
-    hg log -l 10 --template '{node|short} {date|shortdate} {desc|firstline}\n' ; \
+    hg log -l 10 --template '{rev} {node|short} {date|shortdate} {desc|firstline}\n' ; \
     true )
 }
 
 # vim:set ts=2 sw=2 et:
+md5sums=('432b9e8352973468fc9e67f7c88484ca')
