updated on Fri Feb  3 13:00:26 UTC 2012

diff --git a/subtle-hg/PKGBUILD b/subtle-hg/PKGBUILD
--- a/subtle-hg/PKGBUILD
+++ b/subtle-hg/PKGBUILD
@@ -1,4 +1,4 @@
-# Contributor: unexist <unexist@dorfelite.net>
+# Contributor: unexist <unexist@subforge.org>
 # Contributor: manveru <m.fellinger@gmail.com>
 # Contributor: Xilon <xilonmu@gmail.com>
 pkgname="subtle-hg"
@@ -17,29 +17,27 @@ backup=("etc/xdg/subtle/subtle.rb")
 source=()
 md5sums=()
 
-_hgroot="http://hg.subforge.org"
-_hgrepo="subtle"
+hgroot="http://hg.subforge.org"
+hgrepo="subtle"
 
 build() {
   cd "$srcdir"
-  msg "Connecting to Mercurial server...."
 
-  if [ -d $_hgrepo ] ; then
-    cd $_hgrepo
-    hg pull -u || return 1
-    msg "The local files are updated."
+  # Either update or clone
+  if [ -d "$hgrepo" ] ; then
+    cd "$hgrepo"
+    hg pull -u || return 1 #< Returns 0 on success, 1 on error
+    cd ..
   else
-    hg clone $_hgroot $_hgrepo || return 1
+    hg clone "$hgroot/$hgrepo" || return 1 #< Returns 0 on success
   fi
 
-  msg "Mercurial checkout done or server timeout"
-  msg "Starting make..."
-
-  rm -rf "$srcdir/$_hgrepo-build"
-  cp -r "$srcdir/$_hgrepo" "$srcdir/$_hgrepo-build"
+  # Remove old dir and create build copy
+  rm -rf "$srcdir/$hgrepo-build"
+  cp -r "$srcdir/$hgrepo" "$srcdir/$hgrepo-build"
 }
 
 package() {
-  cd "$srcdir/$_hgrepo-build"
-  rake destdir=${startdir}/pkg install || return 1
+  cd "$srcdir/$hgrepo-build"
+  rake destdir="${startdir}/pkg" install || return 1
 }
