updated on Mon Feb  6 01:10:12 UTC 2012

diff --git a/subtle-hg/PKGBUILD b/subtle-hg/PKGBUILD
--- a/subtle-hg/PKGBUILD
+++ b/subtle-hg/PKGBUILD
@@ -26,7 +26,7 @@ build() {
   # Either update or clone
   if [ -d "$hgrepo" ] ; then
     cd "$hgrepo"
-    hg pull -u || return 1 #< Returns 0 on success, 1 on error
+    hg pull -u || true #< Returns 0 on success, 1 on error
     cd ..
   else
     hg clone "$hgroot/$hgrepo" || return 1 #< Returns 0 on success
