updated on Sun Mar 31 22:16:21 UTC 2013

diff --git a/mprime-bin/PKGBUILD b/mprime-bin/PKGBUILD
--- a/mprime-bin/PKGBUILD
+++ b/mprime-bin/PKGBUILD
@@ -1,43 +1,36 @@
-# Contributor: graysky <graysky AT archlinux dot us>
+# Maintainer: graysky <graysky AT archlinux dot us>
 # Contributor: Chrysalis <mindaxis@gmail.com>
 
 pkgname=mprime-bin
-_pkgname=p95v
-pkgver=277
-_filever=277
+_pkgname=mprime
+pkgver=279
 pkgrel=1
 pkgdesc="A GIMPS, distributed computing project client, dedicated to finding Mersenne primes. Precopiled binary version."
 arch=('i686' 'x86_64')
 url="http://www.mersenne.org"
-license=("custom")
+license=('custom')
+provides=('mprime')
 conflicts=('mprime')
+depends=('gcc-libs')
 
-if [ $CARCH = "x86_64" ]; then
-	depends=('gcc-libs')
-	source=(ftp://mersenne.org/gimps/$_pkgname$_filever.linux64.tar.gz)
-	noextract=($_pkgname$_filever.linux64.tar.gz)
-	sha256sums=('6ec08e248d18c9cd7e407443c80f11e2c745e15c55d1b087e24ed1a7a5fddd4d')
+if [[ $CARCH = "x86_64" ]]; then
+	source=("http://www.mersenne.info/gimps/p95v$pkgver.linux64.tar.gz")
+	sha256sums=('7fb64f49f4825945d0ed470ecaa12f4b1ffc62c5e56edc7a181fb0751785692d')
+elif [[ $CARCH = "i686" ]]; then
+	source=("http://www.mersenne.info/gimps/p95v$pkgver.linux32.tar.gz")
+	sha256sums=('500d7e0f5a6f19084bdc439f25532ca0b8609ceb4fe88f792fbc01dd844abdbe')
 else
-	depends=('gcc-libs')
-	source=(ftp://mersenne.org/gimps/$_pkgname$_filever.linux32.tar.gz)
-	noextract=($_pkgname$_filever.tar.gz)
-	sha256sums=('1f68e800ccf69b53d3b3af60ce641a2a46919fc9a39f089d87c9fc21f200b782')
+	echo "Cannot determine architecture."
+	exit 1
 fi
 
-build() {
-	mkdir -p ${srcdir}/${_pkgname}-${_filever}-build
-	cd ${srcdir}/${_pkgname}-${_filever}-build
-
-	if [ $CARCH = "x86_64" ]; then
-		bsdtar -xf ../${_pkgname}${_filever}.linux64.tar.gz
-	else
-		bsdtar -xf ../${_pkgname}${_filever}.linux32.tar.gz
-	fi
-
-	install -D -m755 mprime ${pkgdir}/usr/bin/mprime
-	install -D -m644 license.txt ${pkgdir}/usr/share/licenses/${_pkgname}/license.txt
-	install -D -m644 readme.txt ${pkgdir}/usr/share/doc/${_pkgname}/readme.txt
-	install -D -m644 stress.txt ${pkgdir}/usr/share/doc/${_pkgname}/stress.txt
-	install -D -m644 undoc.txt ${pkgdir}/usr/share/doc/${_pkgname}/undoc.txt
-	install -D -m644 whatsnew.txt ${pkgdir}/usr/share/doc/${_pkgname}/whatsnew.txt
+package() {
+	install -Dm755 mprime ${pkgdir}/usr/bin/mprime
+	install -Dm644 license.txt ${pkgdir}/usr/share/licenses/${_pkgname}/license.txt
+	install -Dm644 readme.txt ${pkgdir}/usr/share/doc/${_pkgname}/readme.txt
+	install -Dm644 stress.txt ${pkgdir}/usr/share/doc/${_pkgname}/stress.txt
+	install -Dm644 undoc.txt ${pkgdir}/usr/share/doc/${_pkgname}/undoc.txt
+	install -Dm644 whatsnew.txt ${pkgdir}/usr/share/doc/${_pkgname}/whatsnew.txt
 }
+
+# vim:set ts=2 sw=2 et:
