updated on Thu Aug 14 00:00:24 UTC 2014

diff --git a/xweston/Xweston b/xweston/Xweston
--- a/xweston/Xweston
+++ b/xweston/Xweston
@@ -2,19 +2,58 @@
 
 # Xweston - launch Xwayland hosted by weston
 
-# Choose Weston launcher to use depending on whether we're running under X
-if [ -z "$DISPLAY" ]; then
-	launcher="weston-launch -- $WESTON_OPTS"
-else
-	launcher="weston $WESTON_OPTS"
+# Handle options
+ourtty=$(tty)
+weston_opts=$WESTON_OPTS
+for opt; do
+	case $opt in
+		:[0-9]*) display=$opt
+						;;
+		vt[0-9]*) ourtty=/dev/tty${opt#vt}
+						weston_opts=--tty=${ourtty#/dev/tty}
+						continue
+						;;
+		-novtswitch) # Not supported by Xweston, ignore
+						continue
+	 					;;
+	esac
+	xwayland_opts="$xwayland_opts $opt"
+done
+
+# Experimental X display manager support
+if [ $UID -eq 0 ]; then
+	# FIXME: figure out the correct value for XDG_RUNTIME_DIR if the 
+	#        display manager does not provide one
+	export XDG_RUNTIME_DIR=/tmp/.Xweston/$display
+	mkdir -p "$XDG_RUNTIME_DIR"
+	chmod 0700 "$XDG_RUNTIME_DIR"
 fi
 
-# Let Xwayland-wrapper know the X server options to use
-export XWAYLAND_OPTS=$(mktemp)
-echo "$*" >> $XWAYLAND_OPTS
+# dummy-client will signal us when weston is ready for connections
+trap : USR2
 
-# If running under xinit, add parent PID to signal when X server is ready
-[ -n "$(trap -p USR1)" ] && echo $PPID >> $XWAYLAND_OPTS
+# Launch Weston
+ourpid=$$
+(
+	# Set XDG_CONFIG_HOME (highest priority) for loading our weston.ini
+	export XDG_CONFIG_HOME=/usr/lib/Xweston
 
-# Finally, launch Weston
-exec $launcher
+	# PID to signal, for use by dummy-client
+	echo $ourpid > "$XDG_RUNTIME_DIR/Xweston.pid"
+
+	# Choose Weston launcher to use
+	if [ $UID -ne 0 ] && [ -z "$DISPLAY" ]; then
+		exec weston-launch $weston_launch_opts -- $weston_opts < $ourtty
+	else
+		exec weston $weston_opts
+	fi
+) &
+
+# Wait for signal from dummy-client
+wait
+rm -f "$XDG_RUNTIME_DIR/dummy-client.lock"
+
+# Always run Xwayland, even if weston failed to start, which can happen if
+# a display manager launches Xweston multiple times without waiting for the 
+# previous instance to shut down
+exec Xwayland $xwayland_opts
