updated on Wed Aug 21 22:07:30 UTC 2013

diff --git a/osmos/PKGBUILD b/osmos/PKGBUILD
--- a/osmos/PKGBUILD
+++ b/osmos/PKGBUILD
@@ -1,34 +1,21 @@
 # Maintainer: Marek Otahal <markotahal gmail>
+# Contributor: C5OK5Y 
 # Contributor: N30N <archlinux@alunamation.com>
 
 pkgname=osmos
 pkgver=1.6.1
-pkgrel=2
+pkgrel=3
 pkgdesc="Enter the ambient world of Osmos: elegant, physics-based gameplay, dreamlike visuals, and a minimalist, electronic soundtrack."
 arch=("i686" "x86_64")
 url="http://www.hemispheregames.com/osmos/"
 license=("custom: commercial")
-depends=("openal" "mesa" "libvorbis")
-_gamepkg="Osmos_${pkgver}.tar.gz"
-source=("osmos.desktop")
-md5sums=("7709be11fab3001b109ddf842b596d0c")
+depends=("glu" "freetype2" "libvorbis" "openal")
+source=("hib://Osmos_${pkgver}.tar.gz" "osmos.desktop")
+md5sums=("ed2cb029c20c25de719c28062e6fc9cf"
+         "7709be11fab3001b109ddf842b596d0c")
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 build() {
-  cd $srcdir
-  msg "You need a full copy of this game in order to install it"
-  msg "Searching for \"${_gamepkg}\" in dir: $(readlink -f `pwd`/..)"
-    pkgpath=$startdir
-    if [[ ! -f "$startdir/${_gamepkg}" ]]; then
-       error "Game package not found, please type absolute path to ${_gamepkg} (/home/joe):"
-       read pkgpath
-       if [[ ! -f "${pkgpath}/${_gamepkg}" ]]; then
-           error "Unable to find game package." && return 1
-       fi
-    fi
-  msg "Found game package, installing..."
-
-  ln -fs ${pkgpath}/${_gamepkg} . || return 1
-  tar xzf ${srcdir}/${_gamepkg} || return 1
-
+	cd $srcdir
 
 	msg2 "Patching install path."
 	sed -ri "s|^(CANONPATH=).*|\1/opt/osmos/Osmos|" Osmos/Osmos
