updated on Thu Apr 28 08:30:56 PDT 2011

diff --git a/mozc-svn/uim-mozc.install b/mozc-svn/uim-mozc.install
--- a/mozc-svn/uim-mozc.install
+++ b/mozc-svn/uim-mozc.install
@@ -1,11 +1,11 @@
 post_install() {
   echo -n "Registering mozc on uim..."
   uim-module-manager --register mozc
-  [[ $? > 0 ]] && echo "Register failed." || echo "Done."
+  [[ $? != 0 ]] && echo "Failed." || echo "Done."
 
   cat << _EOF
   ==> You must run the following command whenever 
-  ==> you upgrade or (re-)install uim.
+  ==> you upgrade or (re-)install uim to use mozc.
 
   \`sudo uim-module-manager --register mozc'
 
@@ -15,5 +15,5 @@ _EOF
 post_remove() {
   echo -n "Unregistering mozc from uim..."
   uim-module-manager --unregister mozc
-  [[ $? > 0 ]] && echo "Register failed." || echo "Done."
+  [[ $? != 0 ]] && echo "Failed." || echo "Done."
 }
