updated on Fri Sep 28 04:00:11 UTC 2012

diff --git a/lightdm-ubuntu/guest-session-cross-distro.patch b/lightdm-ubuntu/guest-session-cross-distro.patch
--- a/lightdm-ubuntu/guest-session-cross-distro.patch
+++ b/lightdm-ubuntu/guest-session-cross-distro.patch
@@ -2,7 +2,7 @@ Modify the guest session script so that it doesn't depend on the Debian/
 Ubuntu specific adduser package.
 diff -Nru lightdm-1.3.3.orig/debian/guest-account lightdm-1.3.3/debian/guest-account
 --- lightdm-1.3.3.orig/debian/guest-account	2012-09-27 22:08:24.813765169 -0400
-+++ lightdm-1.3.3/debian/guest-account	2012-09-27 22:10:06.486547693 -0400
++++ lightdm-1.3.3/debian/guest-account	2012-09-27 23:43:08.682972925 -0400
 @@ -10,7 +10,12 @@
  
  add_account ()
@@ -40,20 +40,34 @@ diff -Nru lightdm-1.3.3.orig/debian/guest-account lightdm-1.3.3/debian/guest-acc
          umount "$HOME"
          rm -rf "$HOME"
          exit 1
-@@ -134,7 +153,15 @@
-   # remove leftovers in /tmp
-   find /tmp -mindepth 1 -maxdepth 1 -uid "$UID" -print0 | xargs -0 rm -rf || true
+@@ -109,10 +128,15 @@
+     echo "Error: invalid user $USER"
+     exit 1
+   }
+-  UID=`echo "$PWENT" | cut -f3 -d:`
++  USERUID=`echo "$PWENT" | cut -f3 -d:`
+   HOME=`echo "$PWENT" | cut -f6 -d:`
  
--  deluser --system "$USER"
+-  if [ "$UID" -ge 500 ]; then
 +  # deluser is provided by the adduser package on Debian/Ubuntu. useradd
 +  # doesn't have a '--system' parameter, which causes deluser to only delete
 +  # system users, so this will be handled using this script.
-+  #deluser --system "$USER"
 +  SYS_UID_MIN="$(cat /etc/login.defs | grep SYS_UID_MIN | awk '{print $2}')"
 +  SYS_UID_MAX="$(cat /etc/login.defs | grep SYS_UID_MAX | awk '{print $2}')"
-+  if [ "${UID}" -ge "${SYS_UID_MIN}" ] && [ "${UID}" -le "${SYS_UID_MAX}" ]; then
-+    userdel "${USER}"
-+  fi
++  if [ "$USERUID" -lt "$SYS_UID_MIN" ] || [ "$USERUID" -gt "$SYS_UID_MAX" ]; then
+     echo "Error: user $USER is not a system user."
+     exit 1
+   fi
+@@ -132,9 +156,10 @@
+   rm -rf "$HOME"
+ 
+   # remove leftovers in /tmp
+-  find /tmp -mindepth 1 -maxdepth 1 -uid "$UID" -print0 | xargs -0 rm -rf || true
++  find /tmp -mindepth 1 -maxdepth 1 -uid "$USERUID" -print0 | xargs -0 rm -rf || true
+ 
+-  deluser --system "$USER"
++  #deluser --system "$USER"
++  userdel "$USER"
  }
  
  case "$1" in
