updated on Fri Jan  9 00:00:06 UTC 2015

diff --git a/netatop/PKGBUILD b/netatop/PKGBUILD
--- a/netatop/PKGBUILD
+++ b/netatop/PKGBUILD
@@ -3,7 +3,7 @@
 packager="Spider.007 <archPackage@spider007.net>"
 pkgname=netatop
 pkgver=0.4
-pkgrel=1
+pkgrel=2
 pkgdesc="Atop network kernel module, enables network statistics in atop"
 url="http://www.atoptool.nl/"
 groups=modules
@@ -23,8 +23,14 @@ build() {
 
 package() {
 	cd $srcdir/$pkgname-$pkgver
-	v=`uname -r`
-	install -Dm 0744 module/netatop.ko $pkgdir/lib/modules/extramodules-${v%.*}-ARCH/netatop.ko
+
+	if [[ `uname -r` =~ ^([0-9]\.[0-9]+)\.[0-9]+-[0-9]+(-.*)$ ]]
+	then
+		install -Dm 0744 module/netatop.ko $pkgdir/usr/lib/modules/extramodules-${BASH_REMATCH[1]}${BASH_REMATCH[2]}/netatop.ko
+	else
+		echo "Could not parse version `uname -r`; please report" >&2
+		exit 1
+	fi
 
 	install -D daemon/netatopd $pkgdir/usr/bin/netatopd
 
