updated on Sat Jun  8 18:02:48 UTC 2013

diff --git a/closure-hib/PKGBUILD b/closure-hib/PKGBUILD
--- a/closure-hib/PKGBUILD
+++ b/closure-hib/PKGBUILD
@@ -9,25 +9,20 @@ url='http://closuregame.com/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
 depends=('libgl' 'sdl' 'nvidia-cg-toolkit' 'openal' 'freealut')
-source=('closure-hib.desktop')
-md5sums=('d691e2d56865f8331999374684bdf354')
 options=('!strip' '!upx')
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 _installer="Closure-Linux-${_hibver}.sh"
-_installer_md5='a7c2f7fe17ff67f376da70611abdce97';
-
+source=("hib://${_installer}"
+        'closure-hib.desktop')
+md5sums=('a7c2f7fe17ff67f376da70611abdce97'
+         'd691e2d56865f8331999374684bdf354')
 
 package() {
   cd $srcdir
-  [ $CARCH == "i686" ] && _arch='x86' || _arch='x86_64'
   _target="${pkgdir}/opt/Closure"
-
-  # Get installer
-  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
-    error "Unable to find the game installer. Please download it from your
-           Humble Bundle page, and place it into one of the above locations."
-    exit 1; }
+  [ $CARCH == "i686" ] && _arch='x86' || _arch='x86_64'
 
   # Extract installer
   msg "Starting setup..."
@@ -38,8 +33,9 @@ package() {
     lzma -d < archive/instarchive_all | tar xvf - -C "${_target}"
   ); echo
 
-  # Remove unused files with encoding problems
+  # Fix permissions and remove unused files with encoding problems
   rm -r "${_target}/resources/textures/ui/temp/"
+  chown root:root -R "${_target}"
 
   # Install desktop entry
   install -Dm644 "${pkgname}.desktop" \
@@ -52,24 +48,4 @@ package() {
   # Install launch script
   install -d "${pkgdir}/usr/bin"
   ln -s "/opt/Closure/Closure.bin.${_arch}" "${pkgdir}/usr/bin/closure"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
diff --git a/thomaswasalone-hib/PKGBUILD b/thomaswasalone-hib/PKGBUILD
--- a/thomaswasalone-hib/PKGBUILD
+++ b/thomaswasalone-hib/PKGBUILD
@@ -3,38 +3,31 @@
 pkgname=thomaswasalone-hib
 pkgver=0_20130429
 _hibver=1369349552
-pkgrel=1
+pkgrel=2
 pkgdesc='Thomas Was Alone, a minimalistic puzzle-platformer (Humble Bundle version)'
 url='http://www.thomaswasalone.com/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
 if [ $CARCH == i686 ]; then
-  depends=('glu')
+  depends=('glu' 'lib32-libxcursor' 'alsa-lib' 'gcc-libs')
 else
-  depends=('lib32-glu' 'lib32-libx11')
+  depends=('lib32-glu' 'lib32-libxcursor' 'lib32-alsa-lib' 'lib32-gcc-libs')
 fi
-source=('thomaswasalone-hib.desktop')
-md5sums=('8fe996d4b1a2b3ded634a9d487ea8893')
 options=('!strip' '!upx')
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
-_archive="thomaswasalone-linux-${_hibver}.tar"
-_archive_md5='e7f8e766188718e16880b1137c430f35'
-
+_installer="thomaswasalone-linux-${_hibver}.tar"
+source=("hib://${_installer}"
+        'http://humblepull-wolfire.netdna-ssl.com/misc/files/db2ae1a3ee/images/icons/thomaswasalone.png'
+        'thomaswasalone-hib.desktop')
+md5sums=('e7f8e766188718e16880b1137c430f35'
+         'a62df3b98ffb8e5c339691a34a179d96'
+         '8fe996d4b1a2b3ded634a9d487ea8893')
 
 package() {
   cd $srcdir
   _target="/opt/ThomasWasAlone"
-
-  # Get installer
-  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
-    error "Unable to find the game installer. Please download it from your
-           Humble Bundle page, and place it into one of the above locations."
-    exit 1; }
-
-  # Extract archive
-  msg "Starting setup..."
-  tar -xf ${_archive}
 
   # Fix permissions
   find "thomasLinuxStandalone" -type f -exec chmod 644 {} \;
@@ -49,32 +42,12 @@ package() {
   install -Dm644 "${pkgname}.desktop" \
                  "${pkgdir}/usr/share/applications/${pkgname}.desktop"
 
-#  # Install icon
-#  install -Dm644 "${pkgdir}${_target}/???.png" \
-#                 "${pkgdir}/usr/share/pixmaps/thomaswasalone.png"
+  # Install icon
+  install -Dm644 "thomaswasalone.png" \
+                "${pkgdir}/usr/share/pixmaps/thomaswasalone.png"
 
   # Install launcher script
   echo -e "#!/bin/sh\ncd ${_target} && ./thomasWasAlone" \
         > "launcher.sh"
   install -Dm755 "launcher.sh" "${pkgdir}/usr/bin/thomaswasalone"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
