updated on Sat Mar  3 11:00:39 UTC 2012

diff --git a/syslinux-git/PKGBUILD b/syslinux-git/PKGBUILD
--- a/syslinux-git/PKGBUILD
+++ b/syslinux-git/PKGBUILD
@@ -5,66 +5,59 @@
 _pkgname="syslinux"
 pkgname="${_pkgname}-git"
 
-pkgver=20111216
+pkgver=20120303
 pkgrel=1
 arch=('i686' 'x86_64')
 pkgdesc="Collection of boot loaders that boot from FAT, ext2/3/4 and btrfs filesystems, from CDs and via PXE - GIT Development version"
 url="http://syslinux.zytor.com/"
 license=('GPL2')
-makedepends=('git' 'nasm' 'curl')
+makedepends=('git' 'nasm' 'python2')
 depends=('perl' 'glibc')
 optdepends=('perl-passwd-md5: For md5pass'
-			'perl-digest-sha1: For sha1pass'
-			'mtools: For mkdiskimage and syslinux'
-			'dosfstools: For FAT filesystems support')
+            'perl-digest-sha1: For sha1pass'
+            'mtools: For mkdiskimage and fat support'
+            'dosfstools: For FAT filesystems support')
 
 provides=("${_pkgname}")
 conflicts=("${_pkgname}")
 
 backup=('boot/syslinux/syslinux.cfg')
 install="${_pkgname}.install"
+options=('strip' 'docs' 'libtool' '!emptydirs' 'zipman' 'purge')
 
-source=('Syslinux-Do-not-build-dos-and-windows-executables.patch'
-		'syslinux-install_update'
-		'syslinux.cfg')
+source=('syslinux-dont-build-dos-windows-targets.patch'
+        'syslinux-install_update'
+        'syslinux.cfg')
 
-sha256sums=('6d2e510e677ff8063df7400b80413ee4429130927734440a6dcef3843dc93c93'
-			'49573a3b65362326c8b1e9bfa49e83225e0bf9d3710454de4070abc9481c614c'
-			'b4ba8f9daa67ec35da6e05adb610469bc8c4facf488468c1ec3e5860ba75313d')
+sha256sums=('bb5e971a3c7c40fbb78391d9cace67366250b699ac3cdada1d0394bacb614031'
+            'e2f5412d1f21ca868af8984b83d3a95223ced16554fdbf922135eee7ae97f660'
+            '14d0d6ffe437cf42707b58198a00299a459e27fe5b7d7a65d75a4114e66506de')
 
 _gitroot="git://git.kernel.org/pub/scm/boot/syslinux/syslinux.git"
 _gitname="${_pkgname}"
+_gitbranch="master"
 
 _update_git() {
 	
-	cd "${srcdir}"
+	cd "${srcdir}/"
 	
 	msg "Connecting to GIT server...."
 	
-	if [ -d "${srcdir}/${_gitname}/" ]
-	then
+	if [[ -d "${srcdir}/${_gitname}/" ]]; then
 		cd "${srcdir}/${_gitname}/"
 		git reset --hard
 		git fetch
-		git checkout master
-		git merge remotes/origin/master
+		git checkout "${_gitbranch}"
+		git merge "remotes/origin/${_gitbranch}"
 		msg "The local GIT repo has been updated."
 	else
 		git clone "${_gitroot}" "${_gitname}"
+		cd "${srcdir}/${_gitname}/"
+		git checkout "${_gitbranch}"
+		msg "GIT checkout done or server timeout"
 	fi
 	
-	msg "GIT checkout done or server timeout"
-	
-	cd "${srcdir}/"
-	
-	## Download the installation and update script
-	## This script is maintained at git://gist.github.com/772138.git
-	# curl "https://gist.github.com/gists/772138/download" > "${srcdir}/syslinux_install_script.tar.gz"
-	# bsdtar xf "${srcdir}/syslinux_install_script.tar.gz"
-	
-	# cd "${srcdir}"/gist*/
-	# mv "${PWD}/syslinux-install_update" "${srcdir}/syslinux-install_update"
-	# rm -rf "${srcdir}"/gist*/
+	echo
 	
 }
 
@@ -77,14 +70,18 @@ build() {
 	
 	cd "${srcdir}/${_gitname}_build"
 	
-	# Do not try to build syslinux with our default LDFLAGS, it will fail
+	git reset --hard
+	echo
+	
+	## Do not try to build syslinux with our default LDFLAGS, it will fail
 	unset LDFLAGS
 	
-	# Do not try to build the Windows or DOS installers
-	patch -Np1 -i "${srcdir}/Syslinux-Do-not-build-dos-and-windows-executables.patch"
+	## Do not try to build the Windows or DOS installers
+	patch -Np1 -i "${srcdir}/syslinux-dont-build-dos-windows-targets.patch"
+	echo
 	
-	# Fix FHS manpage path
-	sed 's|/usr/man|$(DATADIR)/man|g' -i "${srcdir}/${_gitname}_build/mk/syslinux.mk" || true
+	## Fix FHS manpage path
+	sed 's|/usr/man|/usr/share/man|g' -i "${srcdir}/${_gitname}_build/mk/syslinux.mk" || true
 	
 	# Use python2 instead of python
 	sed 's|/usr/bin/python|/usr/bin/env python2|g' -i "${srcdir}/${_gitname}_build/com32/cmenu"/*.py || true
@@ -99,13 +96,18 @@ build() {
 
 package() {
 	
-	cd "${srcdir}/${_gitname}_build"
-	make INSTALLROOT="${pkgdir}" AUXDIR="/usr/lib/${_pkgname}" install
+	cd "${srcdir}/${_gitname}_build/"
+	make INSTALLROOT="${pkgdir}/" AUXDIR="/usr/lib/syslinux" install
 	
-	# Install the default configuration
-	install -D -m644 "${srcdir}/syslinux.cfg" "${pkgdir}/boot/syslinux/syslinux.cfg"
+	## move extlinux binary to /usr/sbin
+	install -D -m0755 "${pkgdir}/sbin/extlinux" "${pkgdir}/usr/sbin/extlinux"
+	rm "${pkgdir}/sbin/extlinux"
 	
-	# Install the installation and update script
-	install -D -m755 "${srcdir}/syslinux-install_update" "${pkgdir}/usr/sbin/syslinux-install_update"
+	## Install the default configuration
+	install -D -m0644 "${srcdir}/syslinux.cfg" "${pkgdir}/boot/syslinux/syslinux.cfg"
+	
+	## Install the installation and update script
+	## This script is maintained at git://gist.github.com/772138.git
+	install -D -m0755 "${srcdir}/syslinux-install_update" "${pkgdir}/usr/sbin/syslinux-install_update"
 	
 }
