updated on Wed Jul 20 20:01:01 UTC 2011

diff --git a/smartsvn/PKGBUILD b/smartsvn/PKGBUILD
--- a/smartsvn/PKGBUILD
+++ b/smartsvn/PKGBUILD
@@ -1,7 +1,7 @@
 #Maintainer: Rene Peinthor <peinthor@gmail.com>
 pkgname=smartsvn
-pkgver=6.6.7
-_pkgver=6_6_7
+pkgver=6.6.8
+_pkgver=6_6_8
 pkgrel=1
 pkgdesc="A Subversion(SVN) GUI client written in Java"
 arch=("any")
@@ -13,7 +13,7 @@ provides=(smartsvn=$pkgver)
 source=(smartsvn.desktop downloader.py)
 install="smartsvn.install"
 md5sums=('caf0387a86dccae88f7e4b46cf33f36b' 'e3aa1ed1c09226428e652e2501d4bfb5')
-smartsvnmd5sum='b5f1059e43b3b8febe9e87a36cc1d021'
+smartsvnmd5sum='a1c682014f67c5cc1782873f72229652'
 
 
 extracted="$pkgname-$_pkgver"
@@ -22,7 +22,7 @@ build() {
 	cd "$srcdir"
 	python3 downloader.py smartsvn-generic-${_pkgver}.tar.gz
 
-	echo "${smartsvnmd5sum} *smartsvn-generic-${_pkgver}.tar.gz" | md5sum -c || error "md5sum doesn't match"
+	echo "${smartsvnmd5sum} *smartsvn-generic-${_pkgver}.tar.gz" | md5sum -c || (error "md5sum doesn't match" && return 1)
 
 	tar xzf smartsvn-generic-${_pkgver}.tar.gz
 }
