updated on Fri Dec 23 07:30:53 UTC 2011

diff --git a/smartsvn/PKGBUILD b/smartsvn/PKGBUILD
--- a/smartsvn/PKGBUILD
+++ b/smartsvn/PKGBUILD
@@ -1,19 +1,21 @@
 #Maintainer: Rene Peinthor <peinthor@gmail.com>
 pkgname=smartsvn
-pkgver=6.6.9
-_pkgver=6_6_9
+pkgver=6.6.11
+_pkgver=6_6_11
 pkgrel=1
 pkgdesc="A Subversion(SVN) GUI client written in Java"
 arch=("any")
 url="http://www.syntevo.com/smartsvn/index.html"
 license=('custom')
-depends=("jre" "desktop-file-utils" "sh")
-makedepends=("python")
+depends=("java-runtime" "desktop-file-utils" "sh")
+makedepends=("python" "tidyhtml")
 provides=(smartsvn=$pkgver)
 source=(smartsvn.desktop downloader.py)
 install="smartsvn.install"
-md5sums=('caf0387a86dccae88f7e4b46cf33f36b' 'e3aa1ed1c09226428e652e2501d4bfb5')
-smartsvnmd5sum='5ba1ad083dbdf1aba3d85a03fadff5b3'
+md5sums=('caf0387a86dccae88f7e4b46cf33f36b'
+'08c0959d0b3dd39a458c827b2de90b59'
+)
+smartsvnmd5sum='210d9fbb99c1992107f330efc41db9df'
 
 
 extracted="$pkgname-$_pkgver"
@@ -22,7 +24,7 @@ build() {
 	cd "$srcdir"
 	python3 downloader.py smartsvn-generic-${_pkgver}.tar.gz
 
-	echo "${smartsvnmd5sum} *smartsvn-generic-${_pkgver}.tar.gz" | md5sum -c || (error "md5sum doesn't match" && return 1)
+	echo "${smartsvnmd5sum} *smartsvn-generic-${_pkgver}.tar.gz" | md5sum -c || error "md5sum doesn't match" | exit 1
 
 	tar xzf smartsvn-generic-${_pkgver}.tar.gz
 }
