updated on Fri Jun 12 00:00:11 UTC 2015

diff --git a/ksh/PKGBUILD b/ksh/PKGBUILD
--- a/ksh/PKGBUILD
+++ b/ksh/PKGBUILD
@@ -18,7 +18,7 @@
 # TOFIX: AT&T et al need to fix the build errors that happen after ksh.
 # TOFIX: test wouldn't complete after 16 hours. This might be related to the
 #        build errors after ksh.
-# TOFIX: ksh needs mc integration
+# TOFIX: If ksh is to be a serious contender in the interactive shell game, ksh needs mc integration
 
 # To build you must view and accept the EPL license agreement then insert the
 # username and password from the EPL license page below. Using AT&T sources
@@ -40,8 +40,8 @@ _opt_InstallBETA=1  # Default: 1, 0 to build release version
 _opt_InstallNMAKE=0 # Default: 0, 1 to Install nmake
 ###############################################################################
 
-# This is a multi core build. It takes about 3 minutes on a big processor like 
-# my Intel Haswell E3-1245v3 with SAS drives! Watch it go in htop!
+# This is a multi core build. It takes less than 3 minutes on a big processor 
+# like my Intel Haswell E3-1245v3 with SAS drives! Watch it go in htop!
 # My Celeron G530 with SATA drives at home wasn't even close!
 
 # Use Debian-provided sources since original AT&T tarball requires
@@ -49,24 +49,29 @@ _opt_InstallNMAKE=0 # Default: 0, 1 to Install nmake
 #_debpkgver='93u+20120801'
 #source=("http://ftp.de.debian.org/debian/pool/main/k/ksh/ksh_${_debpkgver}.orig.tar.gz" 'LICENSE')
 
+# The Debian package is INIT.2012-08-01.tgz+ast-ksh.2012-08-01.tgz
+# We build the latest INIT + ast-base
+
 # If Arch distributed this as a binary then building from the Debian sources 
 # would be fine. Build it once then wait until the next version. This is in 
 # the Arch AUR so it must build any time someone wants it. The progression 
-# of Linux soon renders static sources unable to build.
+# of Linux soon renders static sources in the complex AT&T build environment 
+# unable to build.
 
 # To build we had to mix the beta INIT and the release or beta ast-base which
 # neither the Debian source nor the AT&T downloader is capable of.
 
 # The patches herein are simple clerical errors resulting from a complex build 
-# environment failing to support Linux as well as we'd like.
+# environment failing to support Linux as well as we'd like. Others haven't
+# found the errors becase they build ast-ksh instead of ast-base.
 
 # An advanced PKGBUILD that uses (and abuses) all the features of the AT&T
 # build system is the best way to keep up with the ever changing build 
-# requirements. It may also attract the attention of the AT&T devs so that
-# Linux support improves.
+# requirements. Building ast-base may also attract the attention of the AT&T 
+# devs so that Linux support improves.
 
 # Gentoo also builds on demand so if you have build problems, check for new
-# tricks in the eBuilds at Gentoo.
+# tricks in their eBuilds.
 
 set -u
 pkgname='ksh'
@@ -158,12 +163,14 @@ noextract=("${_debfile}")
 # I didn't see enough source diffs to justify a 4th larger binary. Maybe it's
 # debug code. Announcements on the ast lists indicate that the improvements
 # are pretty substantial in the direction of keeping ksh in the game as an
-# interactive shell.
+# interactive shell. This seems useful mainly in environments that use ksh
+# as their primary shell as the future is grim for any shell wanting to
+# unseat zsh as the best interactive shell.
 
 # -CJS
 
 _pkginit() {
-  if [ "${SOURCEONLY}" -ne 0 ]; then # see makepkg -S if this var changes
+  if [ "${SOURCEONLY:-0}" -ne 0 ]; then # see makepkg -S if this var changes
     if [ ! -z "${_opt_EPLPASS}" -o ! -z "${_opt_EPLUSER}" ]; then
       echo '_opt_EPLUSER and _opt_EPLPASS must be blank' 1>&2
       echo 'to produce a source package.' 1>&2
@@ -174,7 +181,7 @@ _pkginit() {
       echo '_opt_EPLUSER and _opt_EPLPASS must be filled in.' 1>&2
       echo 'Please retrieve these from the EPL License page.' 1>&2
       echo 'Edit the PKGBUILD for instructions and changes.' 1>&2
-      if [ "${GENINTEG}" -eq 0 ]; then # see makepkg -g if this var changes
+      if [ "${GENINTEG:-0}" -eq 0 ]; then # see makepkg -g if this var changes
         exit 1
       fi
     fi
@@ -237,7 +244,8 @@ build() {
   # already fixed files. Helpful for running makepkg -ef over and over.
   sed -i -e 's:/usr/tmp:/tmp:g' 2>/dev/null `grep -l '/usr/tmp' 'src/cmd/nmake/Makerules.mk' 'src/cmd/tw/updatedb.sh' 'src/lib/libast/features/stdio' 'src/lib/libast/features/mmap' 'src/lib/libast/path/pathtemp.c'` || :
 
-  # fix L_tmpname, sizeof("/tmp")+15 = 19 but we'll use 25 like the rest of the code.
+  # fix L_tmpname, sizeof("/tmp")+15 = 20 (not 19) but we'll use 25 like the 
+  # rest of the code.
   # This doesn't work. Despire being in src, something in make overwrites this file.
   # (This was early in the build attempts before I learned how iffe works.
   #  This claim may be wrong. Other iffe/FEATURE files are source files and 
@@ -308,7 +316,7 @@ build() {
 
   # Remove quiet to see the cc command lines.
   echo '>>>Starting multi core quiet build, watch htop for activity!'
-  sh bin/package quiet only make ast-ksh SHOPT_COSHELL=0 || :
+  sh bin/package quiet only make 'ast-ksh' SHOPT_COSHELL=0 || :
   # Make errors can be found in src/arch/linux.i386-64/lib/package/gen or by
   # bin/package results
 
@@ -346,11 +354,13 @@ check() {
 _liblinks() {
 # liblinks - generate symbolic links 
 # given libx.so.0.0.0 this would generate links for libx.so.0.0, libx.so.0, libx.so
+  local _FILE
   for _FILE in "$2"/*.so*; do
     #echo "${_FILE}"
-    _shortlib="$(basename "${_FILE}")"
-    _basename="${_shortlib}"
-    _dirname="$(dirname "${_FILE}")"
+    local _shortlib="$(basename "${_FILE}")"
+    local _basename="${_shortlib}"
+    local _dirname="$(dirname "${_FILE}")"
+    local _extn
     while _extn="$(echo "${_shortlib}" | sed -n '/\.[0-9][0-9]*$/s/.*\(\.[0-9][0-9]*\)$/\1/p')" &&
         [ -n "${_extn}" ]; do
       _shortlib="$(basename "${_shortlib}" "${_extn}")"
@@ -373,16 +383,19 @@ package() {
     # ast-base installs way too much including a bunch of conflicting tools
     # ast-ksh doesn't install nmake
     # ast-ksh+ast-make same as ast-base
-    sh bin/package flat install "${pkgdir}/usr/" ast-ksh ast-make
+    sh bin/package flat install "${pkgdir}/usr/" 'ast-ksh' 'ast-make'
   else
     ## Install manually to avoid nmake dep
-    # Huh? nmake is a required part of the package and not available elsewhere.
+    # The Debian package was ast-ksh which doesn't include nmake. The entire
+    # package is built from Mamfiles and mamake. I build ast-base which 
+    # includes nmake and other utilities.
     # We do it manually to avoid the binaries we already have and we don't want
     # a full AT&T toolchain.
 
     # Copy the Debian man pages for shcomp. We even get a French version. 
     # Whoo-hoo! Like Ubuntu, I'm leaving the Debian branding in.
     cd "${srcdir}/debian/usr/share/man"
+    local _doc
     for _doc in `find . -type f -name 'shcomp*.gz'`; do
       install -Dm644 "${_doc}" "${pkgdir}/usr/share/man/${_doc}"
     done
@@ -393,6 +406,7 @@ package() {
     install -Dm755 'bin/ksh' "${pkgdir}/usr/bin/ksh"
     # The Gentoo ebuild shows us that softlinks work for the alternate shells.
     # Running rksh does show 'restricted' so I know that one works.
+    local _exe
     for _exe in 'ksh93' 'rksh' 'pfksh'; do
       ln -sf 'ksh' "${pkgdir}/usr/bin/${_exe}"
     done
@@ -403,6 +417,7 @@ package() {
     install -dm755 "${pkgdir}/usr/share/doc/${pkgname}"
     install -Dm644 "${srcdir}/debian/usr/share/doc/ksh/example.kshrc" "${pkgdir}/usr/share/doc/${pkgname}/example.kshrc"
     # Install the same misc files that Debian installs.
+    local _doc
     for _doc in 'COMPATIBILITY' 'OBSOLETE' 'PROMO.mm' 'RELEASE' 'RELEASE88' 'RELEASE93'; do
       install -Dm644 "${srcdir}/src/cmd/ksh93/${_doc}" "${pkgdir}/usr/share/doc/${pkgname}/${_doc}"
       gzip "${pkgdir}/usr/share/doc/${pkgname}/${_doc}"
@@ -412,6 +427,7 @@ package() {
     # we change fun to functions, or why ast-base has made them 755 and Debian
     # has them 644. I'm just following along for no good reason.
     install -dm755 "${pkgdir}/usr/share/${pkgname}/functions"
+    local _fun
     for _fun in 'dirs' 'popd' 'pushd'; do
       install -Dm644 "fun/${_fun}" "${pkgdir}/usr/share/${pkgname}/functions/${_fun}"
     done
@@ -432,13 +448,10 @@ package() {
   # licenses to consider. Noone else is adding them so they are likely 
   # unnecessary.
   cd "${srcdir}"
-  sh bin/package copyright ast-ksh > "${srcdir}/LICENSE"
-  sh bin/package license ast-ksh >> "${srcdir}/LICENSE"
+  sh bin/package copyright 'ast-ksh' > "${srcdir}/LICENSE"
+  sh bin/package license 'ast-ksh' >> "${srcdir}/LICENSE"
   install -Dm644 "${srcdir}/LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
   set +u
 }
 set +u
 # any sums down here need to be moved in place above, with a preceeding :;
-sha256sums=('8852b9d37d5034e3780aeb5f963726381eeb4e08bb5bee1fbfa7e3f529c10e1b'
-            '58588b07b076f05dbbd5f4f095d5753309a8356ba1e5475262ce77d6bff42dae'
-            '37495cc625a2174b22a43542acac1d69402ee4992ee084a84690546c5b932b39')
