updated on Wed Jun  8 14:33:38 UTC 2011

diff --git a/dvdcopy/dvdcopy b/dvdcopy/dvdcopy
--- a/dvdcopy/dvdcopy
+++ b/dvdcopy/dvdcopy
@@ -1,19 +1,24 @@
 #!/bin/bash
 #
-# pbrisbin 2009, 2010
-# 
-# Note: don't use me with dvdauthor 0.7.0, he throws exit status 1 waaay 
-# too often. Use IgnorePkg to stay at 0.6.* until i can figure out 
-# what's up
+# pbrisbin 2009, 2010, 2011
+#
+# Note: dvdauthor 0.7.0 throws a non-zero exit status even though all's
+# well, try using --keep_going if you find this to be an issue.
 #
 ###
 
-# utilities {{{
-logger() { echo -e "$(date +'[ %d %b %H:%M ]') :: $*"; }
+logger()   { echo -e "$(date +'[ %d %b %H:%M ]') :: $*"; }
+errorout() { echo -e "\aerror: $*" >/dev/stdout; exit 1; }
 
-errorout() { echo -e "\aerror: $*" >&2; exit 1; }
+process_error() {
+  if $keep_going; then
+    echo "warning: $*" >&2
+  else
+    errorout "$*"
+  fi
+}
 
-prompt() {
+prompt() { # {{{
   echo -en "\a$*? [Y/n/q] " && read A
 
   case "${A:-y}" in
@@ -21,18 +26,9 @@ prompt() {
     Q|q) exit 1   ;;
     *)   return 1 ;;
   esac
-}
+} # }}}
 
-make_proper() {
-    sed -e 's/_+*/ /g' \
-        -e 's/\b\(\w*\)\b/\L\u\1/g' \
-        -e 's/ The / the /g' \
-        -e 's/ A / a /g' \
-        -e 's/ An / an /g' \
-        -e 's/ With / with /g' <<< "$1"
-}
-
-requirements() {
+requirements() { # {{{
   local reqs=('bc'      'perl'      'tcprobe'
               'vobcopy' 'mencoder'  'dvdauthor'
               'mkisofs' 'growisofs')
@@ -40,24 +36,23 @@ requirements() {
   for req in ${reqs[@]}; do
     which $req &>/dev/null || errorout "$req required, not installed."
   done
-}
+} # }}}
 
-make_clean() {
+make_clean() { # {{{
   logger 'cleaning up after last time...'
   rm -rf "$directory"; mkdir -p "$directory"
-}
+} # }}}
 
-cleanup() {
+cleanup() { # {{{
   if ! $keep_files; then
     logger 'cleaning up...'
     rm -rf "$directory"
   fi
-}
 
-# }}}
+  logger 'done.'
+} # }}}
 
-# get info {{{
-get_dvd_info() {
+get_dvd_info() { # {{{
   local count=0
 
   logger 'gathering DVD info...'
@@ -66,7 +61,7 @@ get_dvd_info() {
     [[ $count -gt $limit ]] && errorout "vobcopy failed loading the disc $limit times"
 
     count=$((count+1))
-    sleep 1 && vobcopy -I "$device" > "$directory/title.txt" 2>&1
+    sleep 1 && vobcopy -I "$device" &> "$directory/title.txt"
   done
 
   [[ -z "$title" ]] && title="$(awk '/Most\ chapters/ {print $6}' "$directory/title.txt")"
@@ -75,13 +70,12 @@ get_dvd_info() {
 
   name_lower="${name,,}"
   name_lower="${name_lower// /_}"
-  name_proper="$(make_proper "$name")"
 
   # get a/v and chapter info
-  tcprobe -i "$device" -T $title -d 8 > "$directory/probe.txt" 2>&1 || errorout 'tcprobe failed reading disc'
+  tcprobe -i "$device" -T $title -d 8 &> "$directory/probe.txt" || errorout 'tcprobe failed reading disc'
 
   grep -E "\[Chapter ..\] " "$directory/probe.txt" | cut -d " " -f 4 | \
-    perl -pi -e 's/\n/,/' | perl -pi -e 's/,$//' > "$directory/ch.list" || errorout 'failed to parse chapters listing.'
+    perl -pi -e 's/\n/,/' | perl -pi -e 's/,$//' > "$directory/ch.list" || process_error 'failed to parse chapters listing.'
 
   # a check on the chapters, so far it can always be fixed by picking
   # title 1
@@ -97,7 +91,7 @@ get_dvd_info() {
 
   logger "found device   : $device"
   logger "found title    : $title"
-  logger "found name     : $name_proper"
+  logger "found name     : $name_lower"
   logger "found bitrate  : $vbr kbit/s"
   logger "found chapters : "
 
@@ -106,12 +100,11 @@ get_dvd_info() {
   for ((i=0; i<${#chapters[@]}; i++)); do
     logger "               : chapter $((i+1))\t${chapters[$i]}"
   done
-}
 
-# }}}
+  $info_only && exit 0
+} # }}}
 
-# make mpeg {{{
-make_mpeg() {
+make_mpeg() { # {{{
   local options
 
   logger 'encoding video...'
@@ -121,58 +114,49 @@ make_mpeg() {
     logger "adding mencoder option(s) \`$options'..."
   fi
 
-
-  mencoder dvd://$title -dvd-device "$device" $options -ovc lavc -of mpeg -mpegopts format=dvd:tsaf -vf scale=720:480,harddup \
+  mencoder dvd://$title -dvd-device "$device" -mc 0 $options \
+    -ovc lavc -of mpeg -mpegopts format=dvd:tsaf -vf scale=720:480,harddup \
     -lavcopts vcodec=mpeg2video:vrc_buf_size=1835:vrc_maxrate=9800:vbitrate=${vbr}:keyint=18:vstrict=0:aspect=16/9 \
-    -ofps 30000/1001 -oac copy -o "$directory/movie.mpeg" >>"$stdout" 2>>"$stderr" || errorout "mencoder failed reading disc"
+    -ofps 30000/1001 -oac copy -o "$directory/movie.mpeg" || process_error "mencoder failed reading disc"
 
   # save it if desired
-  [[ -n "$mpeg_dir" ]] && ionice -t -c 3 cp -v "$directory/movie.mpeg" "$mpeg_dir/$name_lower.mpeg" >>"$stdout" 2>>"$stderr"
+  [[ -n "$mpeg_dir" ]] && ionice -t -c 3 cp -v "$directory/movie.mpeg" "$mpeg_dir/$name_lower.mpeg"
 
   # exit if desired
   $mpeg_only && exit 0
-}
+} # }}}
 
-# }}}
-
-# author dvd {{{
-author_dvd() {
+author_dvd() { # {{{
   logger "authoring DVD..."
 
   if [[ -f "$directory/ch.list" ]]; then
-    ionice -t -c 3 dvdauthor -t -c $(cat "$directory/ch.list") -o "$directory/MOVIE" "$directory/movie.mpeg" >>"$stdout" 2>>"$stderr" || errorout 'dvdauthor failed writing movie'
+    ionice -t -c 3 dvdauthor -t -c $(cat "$directory/ch.list") -o "$directory/MOVIE" "$directory/movie.mpeg" || process_error 'dvdauthor failed writing movie'
   else
-    ionice -t -c 3 dvdauthor -t -o "$directory/MOVIE" "$directory/movie.mpeg" >>"$stdout" 2>>"$stderr" || errorout 'dvdauthor failed writing movie'
+    ionice -t -c 3 dvdauthor -t -o "$directory/MOVIE" "$directory/movie.mpeg" || process_error 'dvdauthor failed writing movie'
   fi
 
-  ionice -t -c 3 dvdauthor -T -o "$directory/MOVIE" >>"$stdout" 2>>"$stderr" || errorout 'dvdauthor failed writing title'
+  ionice -t -c 3 dvdauthor -T -o "$directory/MOVIE" || process_error 'dvdauthor failed writing title'
 
   # save it if desired
-  [[ -n "$dvd_dir" ]] && ionice -t -c 3 cp -rv "$directory/MOVIE" "$dvd_dir/${name_lower^^}" >>"$stdout" 2>>"$stderr"
+  [[ -n "$dvd_dir" ]] && ionice -t -c 3 cp -rv "$directory/MOVIE" "$dvd_dir/${name_lower^^}"
 
   # exit if desired
   $dvd_only && exit 0
-}
+} # }}}
 
-# }}}
-
-# build ISO {{{
-build_iso() {
+build_iso() { # {{{
   logger 'generating ISO...'
 
-  ionice -t -c 3 mkisofs -dvd-video -o "$directory/movie.iso" "$directory/MOVIE" >>"$stdout" 2>>"$stderr" || errorout 'mkisofs failed creating image'
+  ionice -t -c 3 mkisofs -dvd-video -o "$directory/movie.iso" "$directory/MOVIE" || process_error 'mkisofs failed creating image'
 
   # save it if desired
-  [[ -n "$iso_dir" ]] && ionice -t -c 3 cp -v "$directory/movie.iso" "$iso_dir/$name_lower.iso" >>"$stdout" 2>>"$stderr"
+  [[ -n "$iso_dir" ]] && ionice -t -c 3 cp -v "$directory/movie.iso" "$iso_dir/$name_lower.iso"
 
   # exit if desired
   $iso_only && exit 0
-}
+} # }}}
 
-# }}}
-
-# burn ISO {{{
-burn_iso() {
+burn_iso() { # {{{
   local count
 
   eject "$device" || logger 'eject failed'
@@ -184,29 +168,26 @@ burn_iso() {
     # until we succeed or reach $limit
     count=0
     false; while [[ $? -ne 0 ]]; do
-      [[ $count -gt $limit ]] && errorout "growisofs failed burning image $limit times"
+      [[ $count -gt $limit ]] && process_error "growisofs failed burning image $limit times"
 
       count=$((count+1))
-      sleep 1 && growisofs -dvd-compat -Z $device="$directory/movie.iso" >>"$stdout" 2>>"$stderr"
+      sleep 1 && growisofs -dvd-compat -Z $device="$directory/movie.iso"
     done
 
     sleep 5; eject "$device" || logger 'eject failed'
   fi
-}
+} # }}}
 
-# }}}
-
-# options handling {{{
-message() {
+message() { # {{{
   cat << EOF
 
   usage: dvdcopy [ --option(=<argument>) ] [...]
 
     ~/.dvdcopy.conf will be read first if it's found (even if --config
     is passed). for syntax, see the help entry for the --config option.
-    commandline arguments will overrule what's defined in the config.
+    commandline arguments will overrule what's defined in the config
 
-    invalid options are ignored.
+    invalid options may lead to odd behavior
 
     options:
 
@@ -216,8 +197,10 @@ message() {
                                     options specifically to either true
                                     or false
 
-                                    there is no error if <file> doesn't
-                                    exist
+                                    this file must be valid bash syntax
+
+                                    there is no error on malformed or
+                                    non-existent <file>s
 
       --directory=<directory>       set the working directory, default
                                     is ./dvdcopy
@@ -227,13 +210,24 @@ message() {
                                     time dvdcopy is run regardless of
                                     this option
 
+                                    use a different --directory to keep
+                                    files across multiple runs
+
+      --keep_going                  by default, the process ends if one
+                                    of the sub-steps reports a non-zero
+                                    exit status; pass this flag to keep
+                                    going
+
       --device=<file>               set the reader/burner, default is
                                     /dev/sr0
+
+                                    dvdcopy currently does not support
+                                    separate devices for reading/burning
 
       --title=<number>              set the title, default is longest
 
       --size=<number>               set the desired output size in KB, 
-                                    default is 4193404
+                                    default is 4193404, DVD5
 
       --limit=<number>              set the number of times to attempt a
                                     read/burn before giving up, default
@@ -242,7 +236,7 @@ message() {
       --mpeg_only                   stop after transcoding the mpeg
       --dvd_only                    stop after authoring the dvd
       --iso_only                    stop after generating the iso
-      
+
       --mpeg_dir=<directory>        set a save location for the
                                     intermediate mpeg file, default is
                                     blank -- don't save it
@@ -263,8 +257,8 @@ message() {
                                     after '-dvd-device <device>' but
                                     before all others
 
-      --quiet                       be quiet
-      --verbose                     be verbose
+      --quiet                       be quieter
+      --verbose                     be more verbose
 
       --force                       disable any options validation,
                                     useful if ripping from an image file
@@ -272,21 +266,23 @@ message() {
       --help                        print this
 
 EOF
-  
-  exit 1
-}
 
-set_defaults() {
+  exit 1
+} # }}}
+
+set_defaults() { # {{{
   config="$HOME/.dvdcopy.conf"
 
   directory="$PWD/dvdcopy"
   keep_files=false
+  keep_going=false
 
   device='/dev/sr0'
   title=''
   size=4193404
   limit=15
 
+  info_only=false
   mpeg_only=false
   dvd_only=false
   iso_only=false
@@ -301,20 +297,21 @@ set_defaults() {
   verbose=false
   force=false
 
-  stdout='/dev/stdout'
-  stderr='/dev/null'
-}
+  exec 2>/dev/null
+} # }}}
 
-parse_options() {
+parse_options() { # {{{
   [[ -f "$config" ]] && . "$config" # get user config
 
   while [[ -n "$1" ]]; do
     case "$1" in
       --config=*)      . "${1#*=}" 2>/dev/null ;;
+      --info_only)     info_only=true          ;;
       --mpeg_only)     mpeg_only=true          ;;
       --dvd_only)      dvd_only=true           ;;
       --iso_only)      iso_only=true           ;;
       -k|--keep_files) keep_files=true         ;;
+      -g|--keep_going) keep_going=true         ;;
       -q|--quiet)      quiet=true              ;;
       -v|--verbose)    verbose=true            ;;
       -f|--force)      force=true              ;;
@@ -323,9 +320,9 @@ parse_options() {
     esac
     shift
   done
-}
+} # }}}
 
-validate_options() {
+validate_options() { # {{{
   if ! $force; then
     # directory must exist
     [[ ! -d "$directory" ]] && errorout "$directory: does not exist"
@@ -349,11 +346,9 @@ validate_options() {
   $dvd_only  && dvd_dir="${dvd_dir:-$PWD}"
   $iso_only  && iso_dir="${iso_dir:-$PWD}"
 
-  $quiet   && stdout='/dev/null'
-  $verbose && stderr='/dev/stderr'
-}
-
-# }}}
+  $quiet   && exec 1>/dev/null
+  $verbose && exec 2>/dev/stdout
+} # }}}
 
 requirements       # check that we have all required apps
 set_defaults       # set sane defaults
@@ -366,5 +361,3 @@ author_dvd         # author a DVD structure
 build_iso          # make an iso
 burn_iso           # burn an iso
 cleanup            # cleanup
-
-logger 'done.'
