updated on Thu Mar 10 06:00:50 PST 2011

diff --git a/kernel26-ice/PKGBUILD b/kernel26-ice/PKGBUILD
--- a/kernel26-ice/PKGBUILD
+++ b/kernel26-ice/PKGBUILD
@@ -7,15 +7,16 @@ depends=('coreutils' 'module-init-tools' 'mkinitcpio>=0.5.15' 'kernel26-firmware
 pkgext=-ice
 pkgname=kernel26$pkgext
 pkgver=2.6.37
-_minor_patch=2
+_minor_patch=3
 icever=$pkgver$pkgext
-pkgrel=3
+pkgrel=4
 makedepends=('xmlto' 'docbook-xsl')
 arch=(i686 x86_64)
 license=('GPL2')
 url="http://www.kernel.org"
 
 ### User/Environment defined variables
+_skip_minor_patch=${_skip_minor_patch:-0}
 enable_toi=${enable_toi:-1}
 bfs_scheduler=${bfs_scheduler:-0}
 #ck_patches=${ck_patches:-0}
@@ -55,7 +56,7 @@ source=(http://kernel.org/pub/linux/kernel/v2.6/linux-${pkgver}.tar.bz2
 	mkinitcpio-$pkgname.conf)
 
 md5sums=('c8ee37b4fdccdb651e0603d35350b434'
-         'bb5798f2a2a5af13219d1a250c4dad11'
+         'c0a38dd3b5bad43d5f5d07ed0fcf3692'
          'da527aea6a4a374f963f4063e548dc74'
          '097f10382043d4b9328d2db3fa80bf94'
          '6b19322620d4fabfb2db1bf6748020eb'
@@ -70,16 +71,16 @@ build() {
     cd ${srcdir}/linux-$pkgver
 
     # Applying official patch
-    if [ "$_minor_patch" != "0" ] ; then
+    if [ "$_minor_patch" != "0" ] && [ "$_skip_minor_patch" != "1" ] ; then
 	echo "Applying patch-${pkgver}.${_minor_patch}.bz2"
-	patch -Np1 -i ${srcdir}/patch-${pkgver}.${_minor_patch} || return 1
+	patch -Np1 -i ${srcdir}/patch-${pkgver}.${_minor_patch} || { echo Failed patch-${pkgver}.${_minor_patch}.bz2 ; return 1 ; }
     fi
 
     if [ -n "${local_patch_dir}" ] && [ -d "${local_patch_dir}" ] ; then
 	echo "Applying patches from ${local_patch_dir} ..."
 	for my_patch in "${local_patch_dir}"/* ; do
 		echo -e "Applying custom patch:\t'${my_patch}'" || true
-		patch -Np1 -i "${my_patch}" || return 1
+		patch -Np1 -i "${my_patch}" || { echo -e "Failed custom patch:\t'${my_patch}'" ; return 1 ; }
 	done
     fi
 
@@ -89,13 +90,13 @@ build() {
 	# Strip './Makefile' changes
 	bzip2 -dkc ${srcdir}/${file_rt} \
             | sed '/diff --git a\/Makefile b\/Makefile/,/*DOCUMENTATION*/d' \
-            | patch -Np1 || return 1
+            | patch -Np1 || { echo "Failed Realtime patch '${file_rt}'"; return 1 ; }
     fi
     
     # applying reiserfs4 patch
     if [ "$enable_reiser4" = "1" ]; then
 	echo "Applying ${file_reiser4%.gz}"
-	bzip2 -dc ${srcdir}/${file_reiser4} | patch -Np1 || return 1
+	bzip2 -dc ${srcdir}/${file_reiser4} | patch -Np1 || { echo "Failed reiser4 patch '${file_reiser4%.gz}'"; return 1 ; }
     fi
     
     # applying tuxonice patch
@@ -106,19 +107,19 @@ build() {
 		bzip2 -dck ${srcdir}/${file_toi} \
 		| sed '/diff --git a\/kernel\/fork.c b\/kernel\/fork.c/,/{/d' \
 		| sed 's/printk(KERN_INFO "PM: Creating hibernation image:\\n/printk(KERN_INFO "PM: Creating hibernation image: \\n/' \
-		| patch -Np1 || return 1
+		| patch -Np1 || { echo "Failed TOI w/rt" ; return 1 ; }
 	else
 		bzip2 -dck ${srcdir}/${file_toi} \
 		| sed 's/printk(KERN_INFO "PM: Creating hibernation image:\\n/printk(KERN_INFO "PM: Creating hibernation image: \\n/' \
-		| patch -Np1 -F4 || return 1
+		| patch -Np1 -F4 || { echo "Failed TOI"; return 1 ; }
 	fi
     fi
 
     if [ "${bfs_scheduler}" = "1" ] && [ "${ck_patches}" = "0" ]; then
        # applying BFS scheduler patch
 	echo "Applying BFS scheduler patch"
-        patch -Np1 -i ${srcdir}/${file_bfs} || return 1
-        patch -Np1 -i ${srcdir}/${file_bfs_b} || return 1
+        patch -Np1 -i ${srcdir}/${file_bfs} || { echo "Failed BFS"; return 1 ; }
+        patch -Np1 -i ${srcdir}/${file_bfs_b} || { echo "Failed BFS (file 2)"; return 1 ; }
 #Applying quick-fix 2.6.37.1 patch for bfs/ck
 patch -Np1 -i ${srcdir}/2.6.37.1-fix-no-more-unsigned.patch
     fi
@@ -127,7 +128,7 @@ patch -Np1 -i ${srcdir}/2.6.37.1-fix-no-more-unsigned.patch
 #	# sed out the -ckX version to make kernel naming happy.
 #	bzip2 -dck ${srcdir}/${file_ck} \
 #	    | sed 's/+EXTRAVERSION := $(EXTRAVERSION)$(CKVERSION)/+EXTRAVERSION := $(EXTRAVERSION)/' \
-#	    | patch -Np1 || return 1
+#	    | patch -Np1 || { echo "Failed CK"; return 1 ; }
 #    fi
     
     # remove extraversion
