updated on Fri Jul 26 14:13:37 UTC 2013

diff --git a/aurnotify/aurnotify b/aurnotify/aurnotify
--- a/aurnotify/aurnotify
+++ b/aurnotify/aurnotify
@@ -1,9 +1,10 @@
 #!/bin/bash
-ver=0.1.5
+ver=0.2.0
 #
 # Aurnotify, a tool to set notify status of favorite packages on AUR
 # Feifei Jia <feifei.j@gmail.com>
-# $Id: aurnotify 1455 2011-02-09 05:52:41Z ffjia $
+#
+# Special thanks to Joris Steyn.
 #
 # Based on Aurvote, written by <wain@archlinux.fr>
 # https://aur.archlinux.org/packages.php?ID=9845
@@ -21,15 +22,7 @@ ver=0.1.5
 TMPDIR="/tmp/aurnotify-tmp-$(id -un)$$"
 CONFIGFILE=~/.aurnotify
 CONFIGFILE_AURVOTE=~/.config/aurvote
-AUR_URL="https://aur.archlinux.org/packages.php"
-AUR_URL2="https://aur.archlinux.org/packages.php?setlang=en&K="
-AUR_URL3="https://aur.archlinux.org/packages.php?setlang=en&ID="
-
-
-# Find ID for given package, grab from "/usr/lib/yaourt/aur.sh, modified"
-findaurid() {
-    wget -q -O - "https://aur.archlinux.org/rpc.php?type=info&arg=$1" | sed -e 's/^.*"ID":"//' -e 's/",".*$//' | grep "^[[:digit:]]\+$"
-}
+AUR_BASE_URL="https://aur.archlinux.org/"
 
 version() {
     echo "aurnotify - version $ver"
@@ -119,7 +112,7 @@ fi
 mkdir -p "$TMPDIR"
 
 wget --quiet --keep-session-cookie --save-cookies "$TMPDIR/.aurnotify.cookies" \
---post-data="user=${user}&passwd=${pass}" https://aur.archlinux.org \
+--post-data="user=${user}&passwd=${pass}" $AUR_BASE_URL/login \
 -O "$TMPDIR/aurnotify.login" || exit 1
 
 if grep --quiet "'error'>Bad username or password" "$TMPDIR/aurnotify.login"
@@ -131,25 +124,19 @@ fi
 # notify/unnotify/check for each package
 for pkgname in ${pkgnames[@]}
 do
-    aurid=$(findaurid $pkgname)
-
-    if [ -z "$aurid" ]
-    then
-        echo "$pkgname was not found on AUR"
-        continue
-    fi
+    PKG_URL=$AUR_BASE_URL/packages/$pkgname
 
     if [ "$ACTION" = "check" ]
     then
         echo -n "$pkgname: "
 
         wget --quiet --load-cookies="$TMPDIR/.aurnotify.cookies" \
-        "${AUR_URL3}${aurid}" -O "$TMPDIR/$pkgname" || echo "ERROR: Can't access $AUR_URL3"
+        $PKG_URL -O "$TMPDIR/$pkgname" || echo "ERROR: Can't access $PKG_URL"
 
-        if grep -q "type='submit' class='button' name='do_UnNotify'" $TMPDIR/$pkgname
+        if grep -q "href=\"/packages/$pkgname/unnotify/\"" $TMPDIR/$pkgname
         then
             echo "already notified"
-        elif grep -q "type='submit' class='button' name='do_Notify'" $TMPDIR/$pkgname
+        elif grep -q "href=\"/packages/$pkgname/notify/\"" $TMPDIR/$pkgname
         then
             echo "not notified"
         else
@@ -158,22 +145,20 @@ do
     elif [ "$ACTION" = "notify" ]
     then
         if wget --quiet --load-cookies="$TMPDIR/.aurnotify.cookies" \
-            --post-data="IDs[${aurid}]=1&ID=${aurid}&do_Notify=1" \
-            $AUR_URL -O "$TMPDIR/$pkgname"
+            $PKG_URL/notify -O "$TMPDIR/$pkgname"
         then
             echo "$pkgname now notified"
         else
-            echo "ERROR: Can't access $AUR_URL"
+            echo "ERROR: Can't access $PKG_URL/notify"
         fi
     elif [ "$ACTION" = "unnotify" ]
     then
         if wget --quiet --load-cookies="$TMPDIR/.aurnotify.cookies" \
-            --post-data="IDs[${aurid}]=1&ID=${aurid}&do_UnNotify=1" \
-            $AUR_URL -O "$TMPDIR/$pkgname"
+            $PKG_URL/unnotify -O "$TMPDIR/$pkgname"
         then
             echo "$pkgname now unnotified"
         else
-            echo "ERROR: Can't access $AUR_URL"
+            echo "ERROR: Can't access $PKG_URL/unnotify"
         fi
     fi
 done
