updated on Sat Dec 10 14:01:10 UTC 2011

diff --git a/smartgit/PKGBUILD b/smartgit/PKGBUILD
--- a/smartgit/PKGBUILD
+++ b/smartgit/PKGBUILD
@@ -1,9 +1,8 @@
 #Maintainer: Alexey Stukalov <astukalov@gmail.com>
-#forked from smartgit AUR package, maintainer Rene Peinthor
+#forked from smartsvn AUR package, maintainer Rene Peinthor
 pkgname=smartgit
 pkgver=2.1.6
-_pkgver=2_1_6
-pkgrel=1
+pkgrel=2
 pkgdesc="A Git GUI client written in Java"
 arch=("any")
 url="http://www.syntevo.com/smartgit/index.html"
@@ -14,27 +13,33 @@ provides=(smartgit=$pkgver)
 source=(smartgit.desktop downloader.py)
 install="smartgit.install"
 md5sums=('1d4bb1a70a3c6a6d04fe938beb28808b'
-         'abf1fe0a54b0d0370cc99350063f83ce')
+         'fb9d03cb528a98ea36b62a9c90a10cd5')
+# MD5 of smartgit tar.gz archive file
 smartgitmd5sum='bce918bcb74c25ee88347587fb9a3526'
 
 
-extracted="$pkgname-$_pkgver"
+# package version as it appears in the name of tar.gz archive file
+_pkgver=$(echo $pkgver | sed 's/\./_/g')
+# folder within tar.gz archive
+_pkgfolder="$pkgname-$_pkgver"
+# tar.gz archive filename
+_pkgfile="$pkgname-generic-$_pkgver.tar.gz"
 
 build() {
 	cd "$srcdir"
-	python3 downloader.py smartgit smartgit-generic-${_pkgver}.tar.gz
+	python3 downloader.py smartgit ${_pkgfile}
 
-	echo "${smartgitmd5sum} *smartgit-generic-${_pkgver}.tar.gz" | md5sum -c || (error "md5sum doesn't match" && return 1)
+	echo "${smartgitmd5sum} *${_pkgfile}" | md5sum -c || (error "md5sum doesn't match" && return 1)
 
-	tar xzf smartgit-generic-${_pkgver}.tar.gz
+	tar xzf ${_pkgfile}
 }
 
 package() {
 	cd "$srcdir"
 
-	install -D -m644 "${extracted}"/license.html "${pkgdir}/usr/share/licenses/${pkgname}/license.html"
+	install -D -m644 "${_pkgfolder}"/license.html "${pkgdir}/usr/share/licenses/${pkgname}/license.html"
 	mkdir -p "${pkgdir}"/opt
-	mv "${extracted}" ${pkgdir}/opt/$pkgname || return 1
+	mv "${_pkgfolder}" ${pkgdir}/opt/$pkgname || return 1
 
 	install -D -m644 smartgit.desktop "${pkgdir}"/usr/share/applications/smartgit.desktop
 }
