updated on Tue Nov 27 10:00:18 UTC 2012

diff --git a/alsa-driver/alsa-driver.install b/alsa-driver/alsa-driver.install
--- a/alsa-driver/alsa-driver.install
+++ b/alsa-driver/alsa-driver.install
@@ -11,3 +11,10 @@ post_upgrade()
   echo "running 'depmod -a' ..."
   depmod -a && echo "done." || echo "failed."
 }
+
+post_remove()
+{
+  echo "running 'depmod -a' ..."
+  depmod -a && echo "done." || echo "failed."
+}
+
