updated on Mon Sep 17 10:16:07 UTC 2012

diff --git a/alsa-driver/alsa-driver.install b/alsa-driver/alsa-driver.install
--- a/alsa-driver/alsa-driver.install
+++ b/alsa-driver/alsa-driver.install
@@ -2,5 +2,12 @@
 
 post_install()
 {
-  depmod -a
+  echo "running 'depmod -a' ..."
+  depmod -a && echo "done." || echo "failed."
+}
+
+post_upgrade()
+{
+  echo "running 'depmod -a' ..."
+  depmod -a && echo "done." || echo "failed."
 }
