updated on Mon Jul  9 03:00:25 UTC 2012

diff --git a/grid-updates/grid-updates.install b/grid-updates/grid-updates.install
--- a/grid-updates/grid-updates.install
+++ b/grid-updates/grid-updates.install
@@ -1,21 +1,20 @@
 post_install() {
     echo
-    echo ">>> Run \`grid-updates --patch-tahoe\` to activate this feature"
-    echo ">>> Read the man page for detailed usage of grid-updates"
+    echo ">>> Make sure tahoe-lafs is running and run:"
+    echo ">>>  grid-updates --patch-tahoe   to apply the patch"
+    echo ">>>               --download-news for the latest NEWS file"
     echo
-    chmod -R 777 /usr/lib/python2.7/site-packages/allmydata/web
 }
 
 post_upgrade() {
     echo
-    echo ">>> Run \`grid-updates --patch-tahoe\` to finish update"
+    echo ">>> Run: grid-updates --patch-tahoe  to finish update"
     echo
 }
 
 pre_remove() {
     echo
-    echo ">>> Running \`grid-updates --undo-patch-tahoe\`..."
-    /usr/bin/grid-updates --undo-patch-tahoe 2>/dev/null
-    echo
-    chmod -R 755 /usr/lib/python2.7/site-packages/allmydata/web
+    echo -n ">>> Running: grid-updates --undo-patch-tahoe ..."
+    /usr/bin/grid-updates --undo-patch-tahoe 1>/dev/null &&
+        echo "ok" || echo "failed"
 }
