updated on Thu Dec 20 19:00:03 UTC 2012

diff --git a/shatter-hib/PKGBUILD b/shatter-hib/PKGBUILD
--- a/shatter-hib/PKGBUILD
+++ b/shatter-hib/PKGBUILD
@@ -8,13 +8,14 @@ pkgdesc='A retro-inspired brick-breaking game with unique twists (Humble Bundle 
 url='http://www.shattergame.com/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
-depends=('glibc' 'gcc-libs' 'libgl' 'libidn' 'zlib' 'libx11' 'libxfixes'
-         'libxdamage' 'libxext' 'libxinerama' 'libxrender' 'libxau' 'libxft'
-         'libxxf86vm' 'libxdmcp' 'fontconfig' 'sdl' 'alsa-lib' 'xdg-utils'
-         'nvidia-cg-toolkit' 'libtxc_dxtn')
-optdepends=('alsa-plugins: PulseAudio support'
-            'libpulse: PulseAudio support')
-if [ $CARCH == x86_64 ]; then
+if [ $CARCH == i686 ]; then
+  depends=('glibc' 'gcc-libs' 'libgl' 'libidn' 'zlib' 'libx11' 'libxfixes'
+          'libxdamage' 'libxext' 'libxinerama' 'libxrender' 'libxau' 'libxft'
+          'libxxf86vm' 'libxdmcp' 'fontconfig' 'sdl' 'alsa-lib' 'xdg-utils'
+          'nvidia-cg-toolkit' 'libtxc_dxtn')
+  optdepends=('alsa-plugins: PulseAudio support'
+              'libpulse: PulseAudio support')
+else
   depends=('lib32-glibc' 'lib32-gcc-libs' 'lib32-libgl' 'lib32-libidn'
            'lib32-zlib' 'lib32-libx11' 'lib32-libxfixes' 'lib32-libxdamage'
            'lib32-libxext' 'lib32-libxinerama' 'lib32-libxrender'
@@ -25,18 +26,19 @@ if [ $CARCH == x86_64 ]; then
               'lib32-libpulse: PulseAudio support')
 fi
 source=('shatter-hib.desktop')
-md5sums=('00bf87930abd0d75382ab2d33f6fb66a')
+md5sums=('52e9ea073d699ae979167fd4cb4af585')
 install='shatter-hib.install'
+options=('!upx')
 PKGEXT='.pkg.tar'
 
-_gamepkg="shatter-linux-${_hibver}.sh"
-
+_installer="shatter-linux-${_hibver}.sh"
+_installer_md5="6e9ba377b121126e2b6fe3e3dbbf1dc2"
 
 package() {
   cd $srcdir
 
   # Get installer
-  _get_humblebundle_source "${_gamepkg}" || {
+  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
     error "Unable to find the game archive. Please download it from your Humble
            Bundle page, and place it into one of the above locations."
     exit 1; }
@@ -44,10 +46,11 @@ package() {
   # Execute installer
   msg "Starting setup..."
   [[ -d "./temp" ]] && rm -r "./temp"
-  sh "./${_gamepkg}" --unattended --no-register --keep --overwrite \
-                     --target  "${srcdir}/temp" \
-                     --bindir  "${srcdir}/bin" \
-                     --datadir "${pkgdir}/opt"
+  sh "./${_installer}" --unattended --no-register --packager pacman \
+                       --keep --overwrite \
+                       --target  "${srcdir}/temp" \
+                       --bindir  "${srcdir}/bin" \
+                       --datadir "${pkgdir}/opt"
 
   # Remove bundled libraries & helper binaries (use system packages instead)
   rm -rf "${pkgdir}/opt/Shatter/lib/lib"{Cg.so,CgGL.so,SDL-1.2.so.0}
@@ -65,32 +68,27 @@ package() {
                  "${pkgdir}/usr/share/pixmaps/shatter.png"
 
   # Install launcher script
-#  echo -e '#!/bin/sh\nforce_s3tc_enable=true /opt/Shatter/Shatter.bin.x86 "$@"' \
-#        > "launcher.sh"
-#  install -Dm755 "launcher.sh" "${pkgdir}/usr/bin/shatter"
   install -d "${pkgdir}/usr/bin"
   ln -s "/opt/Shatter/Shatter.bin.x86" "${pkgdir}/usr/bin/shatter"
   ln -s "/opt/Shatter/SettingsEditor.bin.x86" "${pkgdir}/usr/bin/shatter-settings"
 }
 
 
-# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
-_get_humblebundle_source() {
-  _get_local_source "$1" || return 1;
-  # TODO: Implement automatic downloading from Humble Bundle site
-}
+###### HELPER FUNCTIONS ######
 
-# Locate a file or folder provided by the user, and symlink it into $srcdir
+# Locates a file or folder provided by the user, and symlinks it into $srcdir
 _get_local_source() {
-  msg "Looking for '$1'..."
+  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
   declare -A _search=(['build dir']="$startdir"
                       ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
   for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
+    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
+    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
+      echo "NOT FOUND"
+    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
+      echo "CHECKSUM FAILED";
+    else
       echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-    echo "NOT FOUND"
   done
   if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
