updated on Mon Jan  7 03:23:00 UTC 2013

diff --git a/shank2/PKGBUILD b/shank2/PKGBUILD
--- a/shank2/PKGBUILD
+++ b/shank2/PKGBUILD
@@ -3,70 +3,63 @@
 # Contributor: swiftgeek <swiftgeek@gmail.com>
 # Contributor: Marvn <mistrmarvn@gmail.com>
 
-pkgname="shank2"
-pkgver=b10
+pkgname=shank2
+pkgver=update3
 pkgrel=1
-pkgdesc="A 2D side-scrolling beat 'em up."
-url="http://www.shankgame.com/"
-license=("custom")
-arch=("i686" "x86_64")
-groups=("humble-indie-bundle7" "games")
-if [ "${CARCH}" == "x86_64" ]; then
-	depends=("lib32-sdl" "lib32-libgl")
-else
-	depends=("sdl" "libgl")
-fi
-makedepends=("unzip")
-source=("shank2-linux-${pkgver}.tar.gz::/dev/null" "shank2.sh" "shank2.desktop")
-md5sums=('cd2ac4298a426536144b8b365ef06862'
-         'af1ada644ef91871a86d5c1bad7c9e6e'
-         '3a5f512db8af3ebb4d9cd809d10c13ef')
+pkgdesc='A 2D side-scrolling beat ’em up.'
+url='http://www.shankgame.com/'
+license=('custom:commercial')
+arch=('i686' 'x86_64')
+groups=('humble-indie-bundle7' 'games')
+depends=('sdl' 'libgl')
+source=('shank2.sh' 'shank2.desktop')
+sha1sums=('643c0420c130230da55cde0277f381eb5176b0cd'
+          '7a9fb9a54fe6d39c8fa795b76940ffb1bb1e47fe')
 
-PKGEXT=".pkg.tar"
+_archive="shank2-linux-$pkgver-1357159966.tar.gz"
+_archive_sha1='c690a8c698c69e95d3f46c4ee35295c9ac97a64b'
 
-_humblebundle() {
-	_archive="${source[0]%%:*}"
-	for group in "${groups[@]}"; do
-		case "${group}" in
-			"humble-frozen-bundle") _key="_humblebundlefrozenkey" ;;
-			"humble-frozen-synapse-bundle") _key="_humblebundlesynapsekey" ;;
-			"humble-voxatron-debut") _key="_humblevoxatronkey" ;;
-			"humble-indie-bundle"*)
-				_key="_humblebundle${group:19}key" ;;
-			*) continue ;;
-		esac
-		if [ -n "${!_key}" ]; then
-			msg "Getting your unique ${pkgname} download location."
-			_uri="$(curl -s "https://www.humblebundle.com/downloads?key=${!_key}" \
-				| grep "${_archive}" | cut -d "'" -f 10)"
-			echo "${_archive}::${_uri}"
-			source[0]="${_archive}::${_uri}"
-			break
-		else
-			warning "\"${_key}\" environment variable required for download handling not found."
-		fi
-	done
-	if [ -z "${!_key}" -a ! -f "${startdir}/${_archive}" ]; then
-		error "Unable to download \"${_archive}\"."
-		exit 1
-	fi
-	unset _archive _key _uri
-}
-
-build() {
-	unzip -n "${source[0]%%:*}" || true
-}
+PKGEXT='.pkg.tar'
 
 package() {
-	install -Dm755 shank2.sh "${pkgdir}/usr/bin/shank2"
-	install -Dm644 shank2.desktop "${pkgdir}/usr/share/applications/shank2.desktop"
-
-	cd "Shank 2"
-	find {bin/lib{32,64},data,data-pc} -type f \
-		-exec install -Dm644 "{}" "${pkgdir}/opt/shank2/{}" \;
-	install -Dm755 bin/shank2-{bin,bin32,bin64} "${pkgdir}/opt/shank2/bin/"
+	_get_local_source $_archive --sha1 $_archive_sha1 || {
+		error "Unable to find the game archive. Please download it from your Humble Bundle page, and place it into one of the above locations."
+		exit 1
+	}
+	
+	cd "$srcdir"
+	tar xf "$_archive" || true
+	
+	if [ $CARCH == 'x86_64' ]; then
+		_arch=64
+	else
+		_arch=32
+	fi
+	
+	install -Dm755 shank2.sh      "$pkgdir/usr/bin/shank2"
+	install -Dm644 Shank2.xpm     "$pkgdir/usr/share/shank2/Shank2.xpm"
+	install -Dm644 shank2.desktop "$pkgdir/usr/share/applications/shank2.desktop"
+	
+	install -Dm755 bin/shank2-bin$_arch "$pkgdir/usr/share/shank2/bin/shank2"
+	install -d "$pkgdir/usr/share/shank2/lib"
+	install -Dm644 -t "$pkgdir/usr/share/shank2/lib" bin/lib$_arch/*
+	find data{,-pc} -type f -exec install -Dm644 {} "$pkgdir/usr/share/shank2/{}" \;
+	
 }
 
-_humblebundle
-
-# vim: set noet ff=unix:
+# Locates a file or folder provided by the user, and symlinks it into $srcdir
+_get_local_source() {
+  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
+  declare -A _search=(['build dir']="$startdir"
+                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
+  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
+    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
+    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
+      echo "NOT FOUND"
+    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
+      echo "CHECKSUM FAILED";
+    else
+      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
+  done
+  if [ ! -e "$srcdir/$1" ]; then return 1; fi
+}
