updated on Sun Nov 27 20:00:59 UTC 2011

diff --git a/crayonphysicsdeluxe/PKGBUILD b/crayonphysicsdeluxe/PKGBUILD
--- a/crayonphysicsdeluxe/PKGBUILD
+++ b/crayonphysicsdeluxe/PKGBUILD
@@ -8,11 +8,11 @@ pkgdesc="A 2D physics puzzle / sandbox game, in which your drawings are transfor
 arch=('i686' 'x86_64')
 url="http://www.crayonphysics.com/"
 license=('custom')
-groups=('humblebundle3' 'humblebundles')
+groups=('humblebundle3' 'humbleintbundle' 'humblebundles')
 if [ "$CARCH" = "x86_64" ]; then
-	depends=('lib32-qt' 'lib32-sdl_image' 'lib32-sdl_mixer' 'lib32-glew1.5')
+    depends=('lib32-qt' 'lib32-sdl_image' 'lib32-sdl_mixer' 'lib32-glew1.5')
 else
-	depends=('qt' 'sdl_image' 'sdl_mixer' 'glew1.5')
+    depends=('qt' 'sdl_image' 'sdl_mixer' 'glew1.5')
 fi
 makedepends=("imagemagick")
 install=("CrayonPhysicsDeluxe.install")
@@ -20,63 +20,69 @@ source=("CrayonPhysicsDeluxe.desktop" "crayon.sh")
 md5sums=('77b35434d5d3d52f7f6071caf306f1d1'
          'd5425616d72038aa387a23b0974aa931')
 
-_archive="crayon_release${pkgver}.tar.gz"
-_archive_md5="dc4127266c6f0e402b5f2ba380665502"
+_archive="crayon-physics-deluxe_${pkgver/_*/}_i386.tar.gz"
+_archive_md5="03855655d3f4d6ef49ebd31b12476c80"
 
 build() {
-  cd $srcdir
+    cd $srcdir
 
-  if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
-	if [ -n "${_crayonarchivelocation}" ] && [ $(echo ${_crayonarchivelocation} | rev | cut -c 1) != "/" ]; then
-                echo _crayonarchivelocation must end in /
-                return 1
+    if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
+        if [ -n "${_crayonarchivelocation}" ] && [ $(echo ${_crayonarchivelocation} | rev | cut -c 1) != "/" ]; then
+            echo _crayonarchivelocation must end in /
+            return 1
         fi
-  	if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-	        wget http://www.humblebundle.com/?key=${_humblebundle3key}
-	        wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-	        mv ${_archive}* ${_archive}
-	  elif [ -z "${_humblebundle3key}" ]; then
-	        echo You can now automate the download of the archive using the _humblebundle3key bash variable.
-	        echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
-	        echo
-	        echo Otherwise please just place ${_archive} into $(pwd)/
-	        echo Press Enter to continue
-	        read -a _unused
-	  fi
-  fi
+        if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
+            rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
+            wget http://www.humblebundle.com/?key=${_humblebundle3key}
+            wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
+            mv ${_archive}* ${_archive}
+        elif [ ! -f ${_archive} ] && [ -n "${_humbleintbundlekey}" ]; then
+            rm -f ${_archive}* index.html\?key\=${_humbleintbundlekey}*
+            wget http://www.humblebundle.com/?key=${_humbleintbundlekey}
+            wget $(cat index.html\?key\=${_humbleintbundlekey} | grep "${_archive}" | cut -d "'" -f 10)
+            mv ${_archive}* ${_archive}
+        elif [ -z "${_humblebundle3key}" ] && [ -z "${_humbleintbundlekey}" ]; then
+            echo You can automate the download of the archive using the _humblebundle3key or _humbleintbundlekey bash variables.
+            echo Just add \'export _humblebundle3key\=\<Your key here\>\' and/or
+            echo \'export _humbleintbundlekey\=\<Your key here\>\' to \.bashrc
+            echo
+            echo Otherwise please just place ${_archive} into $(pwd)/
+            echo Press Enter to continue
+            read -a _unused
+        fi
+    fi
 
-  if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
-    echo "${_crayonarchivelocation}${_archive} not found!"
-    return 1
-  fi
+    if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
+        echo "${_crayonarchivelocation}${_archive} not found!"
+        return 1
+    fi
 
-  if ! echo "${_archive_md5}  ${_crayonarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_crayonarchivelocation}${_archive}"
-    return 1
-  fi
+    if ! echo "${_archive_md5}  ${_crayonarchivelocation}${_archive}" | md5sum -c --quiet; then
+        echo "Invalid checksum for ${_crayonarchivelocation}${_archive}"
+        return 1
+    fi
 
-  install -d ${pkgdir}/usr/share/
-  tar xzf ${_crayonarchivelocation}${_archive} -C ${pkgdir}/usr/share/
-  rm -rf ${pkgdir}/usr/share/CrayonPhysicsDeluxe/lib32
+    install -d ${pkgdir}/usr/share/CrayonPhysicsDeluxe/
+    tar xzf ${_crayonarchivelocation}${_archive} -C ${pkgdir}/usr/share/CrayonPhysicsDeluxe/
+    rm -rf ${pkgdir}/usr/share/CrayonPhysicsDeluxe/lib32
 
-  chmod +x ${pkgdir}/usr/share/CrayonPhysicsDeluxe/launcher
-  install -d ${pkgdir}/usr/bin
+    chmod +x ${pkgdir}/usr/share/CrayonPhysicsDeluxe/launcher
+    install -d ${pkgdir}/usr/bin
 
-  for i in 16x16 22x22 32x32 48x48 64x64 128x128; do
-    mkdir -p ${pkgdir}/usr/share/icons/hicolor/${i}/apps
-    convert -resize ${i} \
-	${pkgdir}/usr/share/CrayonPhysicsDeluxe/icon.png \
-	${pkgdir}/usr/share/icons/hicolor/${i}/apps/CrayonPhysicsDeluxe.png
-  done
-  
-  install -Dm644 ${startdir}/CrayonPhysicsDeluxe.desktop \
-		 ${pkgdir}/usr/share/applications/CrayonPhysicsDeluxe.desktop
+    for i in 16x16 22x22 32x32 48x48 64x64 128x128; do
+        mkdir -p ${pkgdir}/usr/share/icons/hicolor/${i}/apps
+        convert -resize ${i} \
+            ${pkgdir}/usr/share/CrayonPhysicsDeluxe/icon.png \
+            ${pkgdir}/usr/share/icons/hicolor/${i}/apps/CrayonPhysicsDeluxe.png
+    done
 
-  install -D -m644 ${pkgdir}/usr/share/CrayonPhysicsDeluxe/LICENSE.txt \
-	${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
+    install -Dm644 ${srcdir}/CrayonPhysicsDeluxe.desktop \
+        ${pkgdir}/usr/share/applications/CrayonPhysicsDeluxe.desktop
 
-  install -Dm755 ${startdir}/crayon.sh	${pkgdir}/usr/bin/crayon
+    install -D -m644 ${pkgdir}/usr/share/CrayonPhysicsDeluxe/LICENSE.txt \
+        ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
 
-  chown -Rh root:root ${pkgdir}/usr/share/CrayonPhysicsDeluxe
+    install -Dm755 ${srcdir}/crayon.sh	${pkgdir}/usr/bin/crayon
+
+    chown -Rh root:root ${pkgdir}/usr/share/CrayonPhysicsDeluxe
 }
