updated on Wed Jul  3 18:16:13 UTC 2013

diff --git a/crayonphysicsdeluxe/PKGBUILD b/crayonphysicsdeluxe/PKGBUILD
--- a/crayonphysicsdeluxe/PKGBUILD
+++ b/crayonphysicsdeluxe/PKGBUILD
@@ -1,94 +1,55 @@
-# Maintainer: Gadget3000 <gadget3000 at msn dot com>
+# Maintainer: Claudio Kozicky <claudiokozicky@gmail.com>
+# Contributor: Gadget3000 <gadget3000 at msn dot com>
 # Contributor: Otto Allmendinger <otto.allmendinger@gmail.com>
 
 pkgname=crayonphysicsdeluxe
-pkgver=55_3
-pkgrel=3
+pkgver=55
+pkgrel=4
 pkgdesc="A 2D physics puzzle / sandbox game, in which your drawings are transformed into objects"
 arch=('i686' 'x86_64')
 url="http://www.crayonphysics.com/"
 license=('custom')
 groups=('humblebundle3' 'humblebundle4' 'humbleintbundle' 'humblebundles')
-if [ "$CARCH" = "x86_64" ]; then
-    depends=('lib32-qt' 'lib32-sdl_image' 'lib32-sdl_mixer' 'lib32-glew1.5')
-else
-    depends=('qt' 'sdl_image' 'sdl_mixer' 'glew1.5')
-fi
+depends=('gtk-update-icon-cache' 'hicolor-icon-theme' 'xdg-utils')
+[ "$CARCH" = "i686" ] &&\
+    depends+=('glu' 'qt4' 'sdl_image' 'sdl_mixer')
+[ "$CARCH" = "x86_64" ] &&\
+    depends+=('lib32-glu' 'lib32-qt4' 'lib32-sdl_image' 'lib32-sdl_mixer')
 makedepends=('imagemagick')
-install='CrayonPhysicsDeluxe.install'
-source=('CrayonPhysicsDeluxe.desktop' 'crayon.sh')
-md5sums=('77b35434d5d3d52f7f6071caf306f1d1'
-         'd5425616d72038aa387a23b0974aa931')
-
-_archive="crayon-physics-deluxe_${pkgver/_*/}_i386.tar.gz"
-_archive_md5="03855655d3f4d6ef49ebd31b12476c80"
+install=$pkgname.install
+source=("hib://crayon_physics_deluxe-linux-release$pkgver.tar.gz"\
+    "crayon.sh")
+md5sums=('3f799bba4fbca02fcee4b866e17b193d'\
+    '4e3c5f5fe8fe1db8e36d6a83dc30625d')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 build() {
-    cd $srcdir
+    # prepare .desktop file
+    cd "$srcdir/CrayonPhysicsDeluxe"
+    sed -e 's/Path=.*/Path=\/usr\/bin/' -e 's/Exec=.*/Exec=crayon/' -e 's/Icon=.*/Icon=kloonigames-crayon/'\
+        -i kloonigames-crayon.desktop
+}
 
-    if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
-        if [ -n "${_crayonarchivelocation}" ] && [ $(echo ${_crayonarchivelocation} | rev | cut -c 1) != "/" ]; then
-            echo _crayonarchivelocation must end in /
-            return 1
-        fi
-        if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-            rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-            wget http://www.humblebundle.com/?key=${_humblebundle3key}
-            wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-            mv ${_archive}* ${_archive}
-        elif [ ! -f ${_archive} ] && [ -n "${_humbleintbundlekey}" ]; then
-            rm -f ${_archive}* index.html\?key\=${_humbleintbundlekey}*
-            wget http://www.humblebundle.com/?key=${_humbleintbundlekey}
-            wget $(cat index.html\?key\=${_humbleintbundlekey} | grep "${_archive}" | cut -d "'" -f 10)
-            mv ${_archive}* ${_archive}
-        elif [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-            rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-            wget http://www.humblebundle.com/?key=${_humblebundle4key}
-            wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-            mv ${_archive}* ${_archive}
-        elif [ -z "${_humblebundle3key}" ] && [ -z "${_humbleintbundlekey}" ] && [ -z "${_humblebundle4key}" ]; then
-            echo You can automate the download of the archive using the _humblebundle3key or _humblebundle4key or _humbleintbundlekey bash variables.
-            echo Just add \'export _humblebundle3key\=\<Your key here\>\' and/or
-            echo \'export _humbleintbundlekey\=\<Your key here\>\' to \.bashrc and/or
-            echo \'export _humblebundle4key\=\<Your key here\>\' to \.bashrc
-            echo
-            echo Otherwise please just place ${_archive} into $(pwd)/
-            echo Press Enter to continue
-            read -a _unused
-        fi
-    fi
+package() {
+    # install launch script
+    cd "$srcdir"
+    install -Dm755 crayon.sh "$pkgdir/usr/bin/crayon"
 
-    if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
-        echo "${_crayonarchivelocation}${_archive} not found!"
-        return 1
-    fi
+    # install game files
+    cd CrayonPhysicsDeluxe
+    find data -type f -exec install -Dm644 '{}' "$pkgdir/opt/$pkgname/{}" \;
+    install -m644 autoexec.txt "$pkgdir/opt/$pkgname/autoexec.txt"
+    install -Dm755 -t "$pkgdir/opt/$pkgname" crayon launcher
+    install -Dm644 kloonigames-crayon.desktop "$pkgdir/usr/share/applications/kloonigames-crayon.desktop"
 
-    if ! echo "${_archive_md5}  ${_crayonarchivelocation}${_archive}" | md5sum -c --quiet; then
-        echo "Invalid checksum for ${_crayonarchivelocation}${_archive}"
-        return 1
-    fi
+    # install legal files
+    install -Dm644 LICENSE.txt "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+    install -m644 readme.html "${pkgdir}/usr/share/licenses/${pkgname}/README.html"
 
-    install -d ${pkgdir}/usr/share/CrayonPhysicsDeluxe/
-    tar xzf ${_crayonarchivelocation}${_archive} -C ${pkgdir}/usr/share/CrayonPhysicsDeluxe/
-    rm -rf ${pkgdir}/usr/share/CrayonPhysicsDeluxe/lib32
-
-    chmod +x ${pkgdir}/usr/share/CrayonPhysicsDeluxe/launcher
-    install -d ${pkgdir}/usr/bin
-
+    # install icons
+    install -Dm644 icon.png "$pkgdir/usr/share/icons/hicolor/256x256/apps/kloonigames-crayon.png"
     for i in 16x16 22x22 32x32 48x48 64x64 128x128; do
-        mkdir -p ${pkgdir}/usr/share/icons/hicolor/${i}/apps
-        convert -resize ${i} \
-            ${pkgdir}/usr/share/CrayonPhysicsDeluxe/icon.png \
-            ${pkgdir}/usr/share/icons/hicolor/${i}/apps/CrayonPhysicsDeluxe.png
+        install -d "$pkgdir/usr/share/icons/hicolor/$i/apps"
+        convert -quiet -resize $i icon.png "$pkgdir/usr/share/icons/hicolor/$i/apps/kloonigames-crayon.png"
     done
-
-    install -Dm644 ${srcdir}/CrayonPhysicsDeluxe.desktop \
-        ${pkgdir}/usr/share/applications/CrayonPhysicsDeluxe.desktop
-
-    install -D -m644 ${pkgdir}/usr/share/CrayonPhysicsDeluxe/LICENSE.txt \
-        ${pkgdir}/usr/share/licenses/${pkgname}/LICENSE
-
-    install -Dm755 ${srcdir}/crayon.sh	${pkgdir}/usr/bin/crayon
-
-    chown -Rh root:root ${pkgdir}/usr/share/CrayonPhysicsDeluxe
 }
