updated on Sat Aug 13 10:01:00 UTC 2011

diff --git a/crayonphysicsdeluxe/PKGBUILD b/crayonphysicsdeluxe/PKGBUILD
--- a/crayonphysicsdeluxe/PKGBUILD
+++ b/crayonphysicsdeluxe/PKGBUILD
@@ -26,27 +26,38 @@ _archive_md5="dc4127266c6f0e402b5f2ba380665502"
 build() {
   cd $srcdir
 
-  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-	rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-        wget http://www.humblebundle.com/?key=${_humblebundle3key}
-        wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-        mv ${_archive}* ${_archive}
-  elif [ -z "${_humblebundle3key}" ]; then
-        echo You can now automate the download of the archive using the _humblebundle3key bash variable.
-        echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
-        echo
-        echo Otherwise please just place ${_archive} into $(pwd)/
-        echo Press Enter to continue
-        read -a _unused
+  if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
+	if [ -n "${_crayonarchivelocation}" ] && [ $(echo ${_crayonarchivelocation} | rev | cut -c 1) != "/" ]; then
+                echo _crayonarchivelocation must end in /
+                return 1
+        fi
+  	if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
+		rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
+	        wget http://www.humblebundle.com/?key=${_humblebundle3key}
+	        wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
+	        mv ${_archive}* ${_archive}
+	  elif [ -z "${_humblebundle3key}" ]; then
+	        echo You can now automate the download of the archive using the _humblebundle3key bash variable.
+	        echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
+	        echo
+	        echo Otherwise please just place ${_archive} into $(pwd)/
+	        echo Press Enter to continue
+	        read -a _unused
+	  fi
   fi
 
-  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_archive}"
+  if [ ! -f ${_crayonarchivelocation}${_archive} ]; then
+    echo "${_crayonarchivelocation}${_archive} not found!"
+    return 1
+  fi
+
+  if ! echo "${_archive_md5}  ${_crayonarchivelocation}${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_crayonarchivelocation}${_archive}"
     return 1
   fi
 
   install -d ${pkgdir}/opt/
-  tar xzf ${_archive} -C ${pkgdir}/opt/
+  tar xzf ${_crayonarchivelocation}${_archive} -C ${pkgdir}/opt/
   rm -rf ${pkgdir}/opt/CrayonPhysicsDeluxe/lib32
 
   chmod +x ${pkgdir}/opt/CrayonPhysicsDeluxe/launcher
diff --git a/vvvvvv/PKGBUILD b/vvvvvv/PKGBUILD
--- a/vvvvvv/PKGBUILD
+++ b/vvvvvv/PKGBUILD
@@ -10,7 +10,7 @@ arch=('i686' 'x86_64')
 url="http://thelettervsixtim.es/"
 groups=('humblebundle3' 'humblebundles')
 license=('unknown')
-depends=('sdl_image' 'sdl_mixer')
+depends=('sdl_image' 'sdl_mixer' 'gcc-libs')
 source=('vvvvvv.desktop')
 sha256sums=('a5eea031606f206b14f752eee7079fb18b6462fd751087d4641ca1831beb867f')
 
@@ -19,28 +19,35 @@ _archive_md5="54d3679da69d92adb65fe9633f3c67d7"
 
 build() {
   cd $srcdir
-
-  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
-	rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
-	wget http://www.humblebundle.com/?key=${_humblebundle3key}
-	wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
-	mv ${_archive}* ${_archive}
-  elif [ -z "${_humblebundle3key}" ]; then
-	echo You can now automate the download of the archive using the _humblebundle3key bash variable.
-	echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
-	echo
-	echo Otherwise please just place ${_archive} into $(pwd)/
-	echo Press Enter to continue
-	read -a _unused
-  fi
   
-  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_archive}"
+  if [ ! -f ${_vvvvvvarchivelocation}${_archive} ]; then
+	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle3key}" ]; then
+		rm -f ${_archive}* index.html\?key\=${_humblebundle3key}*
+		wget http://www.humblebundle.com/?key=${_humblebundle3key}
+		wget $(cat index.html\?key\=${_humblebundle3key} | grep "${_archive}" | cut -d "'" -f 10)
+		mv ${_archive}* ${_archive}
+	  elif [ -z "${_humblebundle3key}" ]; then
+		echo You can now automate the download of the archive using the _humblebundle3key bash variable.
+		echo Just add \'export _humblebundle3key\=\<Your key here\>\' to \.bashrc
+		echo
+		echo Otherwise please just place ${_archive} into $(pwd)/
+		echo Press Enter to continue
+		read -a _unused
+	  fi
+  fi
+
+  if [ ! -f ${_vvvvvvarchivelocation}${_archive} ]; then
+    echo "${_vvvvvvarchivelocation}${_archive} not found!"
+    return 1
+  fi  
+
+  if ! echo "${_archive_md5}  ${_vvvvvvarchivelocation}${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_vvvvvvarchivelocation}${_archive}"
     return 1
   fi
 
   install -d ${pkgdir}/opt/
-  tar xzf ${_archive} -C ${pkgdir}/opt/
+  tar xzf ${_vvvvvvarchivelocation}${_archive} -C ${pkgdir}/opt/
   rm -fr ${pkgdir}/opt/VVVVVV/LIB{32,64}
   if [ "$CARCH" = "x86_64" ]; then
     rm -fr ${pkgdir}/opt/VVVVVV/VVVVVV_32
