updated on Fri Jul 12 08:00:26 UTC 2013

diff --git a/android-studio/PKGBUILD b/android-studio/PKGBUILD
--- a/android-studio/PKGBUILD
+++ b/android-studio/PKGBUILD
@@ -2,10 +2,10 @@
 # Contributor: Jakub Schmidtke <sjakub-at-gmail-dot-com>
 
 pkgname=android-studio
-pkgver=0.1.9
+pkgver=0.2.0
 pkgrel=1
-_build=130.687321
-_patch=130.729444
+_build=130.737825
+_patch=
 pkgdesc="A new Android development environment based on IntelliJ IDEA."
 arch=(i686 x86_64)
 url="http://developer.android.com/sdk/installing/studio.html"
@@ -16,11 +16,10 @@ optdepends=('android-sdk-platform-tools' 'android-sdk-build-tools')
 options=('!strip')
 install=${pkgname}.install
 source=(http://dl.google.com/android/studio/android-studio-bundle-${_build}-linux.tgz
-        http://dl.google.com/android/studio/patches/AI-${_build}-${_patch}-patch-unix.jar
         ${pkgname}.desktop)
+test ! -z ${_patch} && source+="http://dl.google.com/android/studio/patches/AI-${_build}-${_patch}-patch-unix.jar"
 noextract=(AI-${_build}-${_patch}-patch-unix.jar)
-md5sums=('6796d66de07c85b2822ca8d501a043c0'
-         '86c3a8d90a14d22e33065787abf35e0d'
+md5sums=('dcd13922f7cf577e3c852b224205d843'
          '0f77280fd3769b0e04ff60dad547ce5e')
 
 [ $CARCH = "x86_64" ] && depends=('python' 'lib32-fontconfig' 'lib32-mesa' 'lib32-libxrender' 'android-sdk')
@@ -28,11 +27,14 @@ md5sums=('6796d66de07c85b2822ca8d501a043c0'
 prepare() {
     echo "Performing update..."
 
-    xvfb-run java -classpath "${srcdir}/AI-${_build}-${_patch}-patch-unix.jar" com.intellij.updater.Runner install "${srcdir}/${pkgname}" || ret="${?}"
+    if [ ! -z "${_patch}" ]
+    then
+        xvfb-run java -classpath "${srcdir}/AI-${_build}-${_patch}-patch-unix.jar" com.intellij.updater.Runner install "${srcdir}/${pkgname}" || ret="${?}"
 
-    if [ "${ret}" != "42" ]; then
-      echo "Update process failed with code: ${ret}"
-      exit 1
+        if [ "${ret}" != "42" ]; then
+            echo "Update process failed with code: ${ret}"
+            exit 1
+        fi
     fi
 
     cd "${srcdir}/${pkgname}"
