updated on Wed Jun  5 08:00:17 UTC 2013

diff --git a/android-studio/PKGBUILD b/android-studio/PKGBUILD
--- a/android-studio/PKGBUILD
+++ b/android-studio/PKGBUILD
@@ -1,28 +1,40 @@
 # Maintainer: Philipp 'TamCore' B. <philipp [at] tamcore [dot] eu>
+# Contributor: Jakub Schmidtke <sjakub-at-gmail-dot-com>
 
 pkgname=android-studio
-pkgver=0.2
+pkgver=0.1.2
 pkgrel=1
 _build=130.687321
+_patch=130.692269
 pkgdesc="A new Android development environment based on IntelliJ IDEA."
 arch=(i686 x86_64)
 url="http://developer.android.com/sdk/installing/studio.html"
 license=('APACHE')
 depends=('python' 'fontconfig' 'mesa' 'libxrender' 'android-sdk')
-makedepends=('unzip')
+makedepends=('unzip' 'xorg-server-xvfb')
 optdepends=('android-sdk-platform-tools' 'android-sdk-build-tools')
 options=('!strip')
 install=${pkgname}.install
 source=(http://dl.google.com/android/studio/android-studio-bundle-${_build}-linux.tgz
-        ${pkgname}.desktop
-        vmoptions.patch)
+        http://dl-sdk.appspot.com/as/patches/AI-${_build}-${_patch}-patch-unix.jar
+        ${pkgname}.desktop)
+noextract=(AI-${_build}-${_patch}-patch-unix.jar)
 md5sums=('6796d66de07c85b2822ca8d501a043c0'
-         '3a89903be95351341c84956a810387be'
-         'be1810573bd3aaadabd90d14a642982c')
+         '64a89a9a667983dbd9932947a35e5eba'
+         '0f77280fd3769b0e04ff60dad547ce5e')
 
 [ $CARCH = "x86_64" ] && depends=('python' 'lib32-fontconfig' 'lib32-mesa' 'lib32-libxrender' 'android-sdk')
 
 prepare() {
+    echo "Performing update..."
+
+    xvfb-run java -classpath "${srcdir}/AI-${_build}-${_patch}-patch-unix.jar" com.intellij.updater.Runner install "${srcdir}/${pkgname}" || ret="${?}"
+
+    if [ "${ret}" != "42" ]; then
+      echo "Update process failed with code: ${ret}"
+      exit 1
+    fi
+
     cd "${srcdir}/${pkgname}"
 
     # remove pause after open jdk warning
@@ -32,26 +44,25 @@ prepare() {
     unzip -o lib/resources.jar artwork/icon_AS_128.png
 
     # enable anti aliasing
-    cd bin
-    patch -p1 -i "${srcdir}/vmoptions.patch"
+    for f in bin/*.vmoptions; do
+      echo "-Dawt.useSystemAAFontSettings=lcd" >> ${f}
+      echo "-Dswing.aatext=true" >> ${f}
+    done
 }
 
 package() {
     cd "${srcdir}/${pkgname}"
 
-    # profile.d stuff
-    mkdir -p "${pkgdir}/etc/profile.d"
-    echo 'export PATH=$PATH:/opt/android-studio/bin' > "${pkgdir}/etc/profile.d/${pkgname}.sh"
-    echo 'setenv PATH ${PATH}:/opt/android-studio/bin' > "${pkgdir}/etc/profile.d/${pkgname}.csh"
-    chmod 755 "${pkgdir}/etc/profile.d/"*
-
     # application stuff
     mkdir -p "${pkgdir}/opt/${pkgname}"
     cp -a bin lib plugins "${pkgdir}/opt/${pkgname}"
-    chmod -R 755 "${pkgdir}/opt/${pkgname}"
-    ln -s /opt/android-studio/bin/studio.sh "${pkgdir}/opt/${pkgname}/bin/android-studio"
+
+    mkdir -p "${pkgdir}/usr/bin"
+    ln -s /opt/android-studio/bin/studio.sh "${pkgdir}/usr/bin/android-studio"
 
     # starter stuff
     install -Dm655 artwork/icon_AS_128.png "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
     install -Dm655 "${srcdir}/${pkgname}.desktop" "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+
+    chmod -R ugo+rX "${pkgdir}/opt"
 }
