updated on Sat Jul 27 12:08:30 UTC 2013

diff --git a/linux-mptcp/PKGBUILD b/linux-mptcp/PKGBUILD
--- a/linux-mptcp/PKGBUILD
+++ b/linux-mptcp/PKGBUILD
@@ -7,7 +7,7 @@ true && pkgname=("linux-mptcp" "linux-mptcp-headers" "linux-mptcp-docs")
 _srcname=mptcp
 _mptcpv=0.87
 pkgver=0.87.379815.b03709a
-pkgrel=2
+pkgrel=3
 arch=('i686' 'x86_64')
 url="http://www.multipath-tcp.org/"
 license=('GPL2')
@@ -67,8 +67,9 @@ build() {
   make prepare
 
   if [ -e "${startdir}/config.patch" ]; then
-    msg2 "Found local config patch, applying.."
-    patch -Np1 -i "${startdir}/config.patch"
+    msg2 "Found local config patch, applying..."
+    patch -Np1 .config "${startdir}/config.patch" \
+      || (error "config.patch could not be applied cleanly..." && return 1)
   fi
 
   # load configuration
