updated on Wed Jun 17 00:00:21 UTC 2015

diff --git a/update-pacman-mirrorlist/update-pacman-mirrorlist b/update-pacman-mirrorlist/update-pacman-mirrorlist
--- a/update-pacman-mirrorlist/update-pacman-mirrorlist
+++ b/update-pacman-mirrorlist/update-pacman-mirrorlist
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -eu -o pipefail
+set -euo pipefail
 
 #TODO: Comment and document!
 
@@ -30,23 +30,23 @@ if [ -z "$mirrorlist_url" ]; then
 fi
 set -u
 
-if [ ! -e "$mirrorlist_file" ]; then
-	exit 1;
-fi
-
 echo "Downloading new mirrorlist from $mirrorlist_url to $mirrorlist_file."
 #TODO: Retry download in a more intelligent manner as to not overload the server.
 curl -fLC - --retry 3 --retry-delay 3 "$mirrorlist_url" -o "$temp_mirrorlist_file"
 
 #TODO: Better sanity checking.
-if [[ $(diff <(head -n 3 "$temp_mirrorlist_file") <(echo -e '##\n## Arch Linux repository mirrorlist\n## Sorted by mirror score from mirror status page')) ]]; then
+if [[ $(diff <(head -n 2 "$temp_mirrorlist_file") <(echo -e '##\n## Arch Linux repository mirrorlist')) ]]; then
+	echo -e 'The downloaded mirrorlist file does not contain the following two lines, so it might be invalid.\n##\n## Arch Linux repository mirrorlist' >&2
 	exit 1;
 fi
 
+#TODO: Only uncomment if necessary.
 sed '/^#\S/ s|#||' -i "$temp_mirrorlist_file"
 
-#TODO: These last three commands are the only ones that need to run as root; privileges should be dropped until then.
-cat "$mirrorlist_file" > "$mirrorlist_file.backup"
+#TODO: These last commands are the only ones that need to run as root; privileges should be dropped until now.
+if [ -e "$mirrorlist_file" ]; then
+	cat "$mirrorlist_file" > "$mirrorlist_file.backup"
+fi
 cat "$temp_mirrorlist_file" > "$mirrorlist_file"
 
 pacman -Syy
