updated on Fri Jun  6 00:01:40 UTC 2014

diff --git a/xbmc-git/xbmc-git.install b/xbmc-git/xbmc-git.install
--- a/xbmc-git/xbmc-git.install
+++ b/xbmc-git/xbmc-git.install
@@ -1,32 +1,36 @@
-update_icons() {
-  if which update-desktop-database > /dev/null 2>&1
-  then
-    update-desktop-database -q /usr/share/applications
-  fi
-  if which gtk-update-icon-cache > /dev/null 2>&1
-  then
-    gtk-update-icon-cache -q /usr/share/icons/hicolor
-  fi
-}
-
-create_xbmc_user() {
-  getent group xbmc > /dev/null || groupadd xbmc
-  getent passwd xbmc > /dev/null || useradd -m -d /var/lib/xbmc -g xbmc xbmc
-  usermod -a -G xbmc,audio,video,power,network,optical,storage,disk xbmc
-}
-
 post_install() {
   update_icons
-  create_xbmc_user
+  getent group xbmc > /dev/null || groupadd -g 420 xbmc
+  if ! getent passwd xbmc > /dev/null; then
+	  useradd -c 'XBMC user' -u 420 -g xbmc -G audio,video,network,optical -d /var/lib/xbmc -s /sbin/nologin xbmc
+	  passwd -l xbmc > /dev/null
+  fi
 }
 
 post_upgrade() {
   post_install $1
+  if ! getent group xbmc | cut -d: -f3 | grep 420 > /dev/null 2>&1; then
+	  groupmod -g 420 xbmc > /dev/null 2>&1
+  fi
+  if ! id -u xbmc | grep 420 > /dev/null 2>&1; then
+	  usermod -u 420 xbmc > /dev/null 2>&1
+	  if [[ $? -ne 0 ]]; then
+		  echo "Changing uid of user xbmc failed"
+		  echo "It is recommended that the uid is changed."
+		  echo "Stop all processes running under the xbmc user and reinstall xbmc"
+		  echo "or change the uid manually. (usermod -u 420 xbmc)"
+	  fi
+	  chown -R xbmc:xbmc /var/lib/xbmc
+  fi
 }
 
 post_remove() {
-  post_install $1 
-  echo "You may want to remove xbmc user and group"
+  update_icons
+  getent passwd xbmc > /dev/null 2>&1 && userdel xbmc
+  getent group xbmc > /dev/null 2>&1 && groupdel xbmc
 }
 
-# vim:set ts=2 sw=2 et:
+update_icons() {
+  type -p gtk-update-icon-cache > /dev/null 2>&1 && usr/bin/gtk-update-icon-cache -qtf usr/share/icons/hicolor
+  type -p update-desktop-database > /dev/null 2>&1 && usr/bin/update-desktop-database -q usr/share/applications
+}
