updated on Mon Jul 15 20:00:52 UTC 2013

diff --git a/braid/PKGBUILD b/braid/PKGBUILD
--- a/braid/PKGBUILD
+++ b/braid/PKGBUILD
@@ -1,46 +1,51 @@
-# Maintainer: trya <tryagainprod@gmail.com>
+# Maintainer: Sam S. <smls75@gmail.com> 
+# Contributor: trya <tryagainprod@gmail.com>
 
 pkgname=braid
-_gamepkg="braid-linux-build2.run.bin"
 pkgver=1.0.2
-pkgrel=1
-pkgdesc="A puzzle-platformer where the player manipulates the flow of time in strange and unusual ways \
-(requires copy of the full game)"
+pkgrel=2
+pkgdesc="A puzzle-platformer where the player manipulates the flow of time (Humble Bundle/Store version)"
 url="http://braid-game.com"
 license=('custom: "commercial"')
 arch=('i686' 'x86_64')
-depends=('sdl' 'nvidia-cg-toolkit')
-optdepends=('libtxc_dxtn: open S3TC implementation for free DRI drivers')
+depends=('sdl' 'nvidia-cg-toolkit' 'libgl')
+optdepends=('libtxc_dxtn: For more efficient texture handling when using one of the open-source Mesa graphics drivers')
 makedepends=('unzip')
-source=("$_gamepkg"::"local://$_gamepkg"
-        'braid.desktop' 'braid.sh')
+options=('!strip' '!upx')
+PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+
+_gamepkg="braid-linux-build2.run.bin"
+source=("$_gamepkg::hib://$_gamepkg"
+        'braid.desktop')
 md5sums=('f8933b7f7c77a234763cf73e2f9312a7'
-         '5c2644ab74d7714bed6d16a564df33bb'
-         'c0c774073c1b626450b4fa30a2917ab8')
-PKGEXT='.pkg.tar' 
-DLAGENTS=("${DLAGENTS[@]}" 'local::/bin/true')
+         'e479ba41d20c1a15a9d8a29fd3b4ff76')
 
 build() {
   cd "$srcdir"
-  unzip $_gamepkg || true
+  unzip -o $_gamepkg || true
+  
+  # Create launch script
+  echo -e '#!/bin/sh\ncd /opt/Braid && ./braid "$@"' > "$srcdir"/launcher
 }
 
 package() {
   cd "$srcdir"
+  [ $CARCH == "i686" ] && _arch=x86 || _arch=amd64
   
-  # data
-  install -d "$pkgdir/opt"
-  cp -a data/gamedata "$pkgdir/opt/Braid"
+  # Install game files
+  install -d "$pkgdir"/opt/Braid
+  cp -a data/gamedata/{data,README-linux.txt} "$pkgdir"/opt/Braid/
+  install -Dm755 data/$_arch/braid "$pkgdir"/opt/Braid/braid
   
-  # startup script and executable
-  install -Dm755 braid.sh "$pkgdir/usr/bin/braid"
-  if [ "$CARCH" == "x86_64" ]; then
-    cp data/amd64/braid "$pkgdir/opt/Braid"
-  else
-    cp data/x86/braid "$pkgdir/opt/Braid"
-  fi
+  # Install launch script
+  install -Dm755 launcher "$pkgdir"/usr/bin/braid
   
-  # desktop icon
-  install -Dm644 braid.desktop "$pkgdir/usr/share/applications/braid.desktop"
-  install -Dm644 data/gamedata/braid.png "$pkgdir/usr/share/pixmaps/braid.png"
+  # Install icon & desktop entry
+  install -Dm644 data/gamedata/braid.png "$pkgdir"/usr/share/pixmaps/braid.png
+  install -Dm644 braid.desktop "$pkgdir"/usr/share/applications/braid.desktop
+  
+  # Install licenses
+  install -d "$pkgdir"/usr/share/licenses/braid
+  cp -a data/gamedata/licenses "$pkgdir"/usr/share/licenses/braid/
 }
diff --git a/eufloria-hib/PKGBUILD b/eufloria-hib/PKGBUILD
--- a/eufloria-hib/PKGBUILD
+++ b/eufloria-hib/PKGBUILD
@@ -1,86 +1,59 @@
+# Maintainer: Claudio Kozicky <claudiokozicky@gmail.com>
 # Contributor: Sam S. <smls75@gmail.com>
 # Contributor: Ben R. <thebenj88 *AT* gmail *DOT* com>
 
 pkgname=eufloria-hib
 pkgver=1.0.1
-pkgrel=2
-pkgdesc='A unique real time strategy game (Humble Bundle version)'
-url='http://www.eufloria-game.com/'
-arch=('i686' 'x86_64')
-license=('custom:commercial')
-depends=('libgl' 'mesa' 'sdl' 'sdl_mixer' 'sdl_image')
-optdepends=('catalyst: AMD Proprietary 3D driver'
-			'nvidia: NVIDIA Proprietary 3D driver')
-source=('eufloria-hib.desktop')
-sha256sums=('113594905a347ef84ec2995a89389584babd95591ff5d3ca65072a2d3f38d5d2')
-options=("!upx")
-PKGEXT='.pkg.tar'
-
-_gamepkg="EufloriaHD-Linux-${pkgver}.sh"
-
+pkgrel=3
+pkgdesc="A unique real time strategy game."
+url="http://www.eufloria-game.com/"
+arch=(i686 x86_64)
+license=(custom)
+depends=(glu sdl_image sdl_mixer nvidia-cg-toolkit)
+options=(!strip)
+source=(hib://EufloriaHD-Linux-$pkgver.sh)
+md5sums=(5de73e648d3cd75f9e974e1459d9a9da)
+DLAGENTS+=('hib::/usr/bin/echo Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf.; exit 1')
+PKGEXT=.pkg.tar
 
 package() {
-  cd $srcdir
+    # installer
+    cd "$srcdir"
+    [ -d tmp ] && rm -r tmp
+    sh ${source[0]#hib://} --unattended \
+                           --no-register \
+                           --bindir "$srcdir"/bin \
+                           --datadir "$pkgdir"/opt \
+                           --keep \
+                           --nox11 \
+                           --target "$srcdir"/tmp
 
-  # Get installer
-  _get_humblebundle_source "${_gamepkg}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
+    cd "$pkgdir"
 
-  # Execute installer
-  msg "Starting setup..."
-  [[ -d "./temp" ]] && rm -r "./temp"
-  sh "./${_gamepkg}" --unattended --no-register --keep --overwrite \
-                     --target  "${srcdir}/temp" \
-                     --bindir  "${srcdir}/bin" \
-                     --datadir "${pkgdir}/opt"
+    # cleanup
+    rm -rf opt/EufloriaHD/xdg-* \
+           opt/EufloriaHD/lib$([ $CARCH = x86_64 ] && echo 64 || echo 32)
 
-  # Remove bundled libraries & helper binaries (use system packages instead)
-  rm -rf "${pkgdir}/opt/EufloriaHD/xdg-"*
+    # desktop integration
+    install -d usr/share/applications
+    sed -e "s/Exec=.*/Exec=eufloria/" \
+        -e "s/Icon=.*/Icon=$pkgname/" \
+        "$srcdir"/tmp/EufloriaHD.desktop \
+        > usr/share/applications/$pkgname.desktop
+    install -d usr/share/pixmaps
+    ln -s /opt/EufloriaHD/EufloriaHD.png usr/share/pixmaps/$pkgname.png
 
-  # Fix permissions
-  find "${pkgdir}" -type f -exec chmod 644 "{}" +
+    # launcher
+    install -d usr/bin
+    ln -s /opt/EufloriaHD/EufloriaHD.bin.${CARCH//i686/x86/} usr/bin/eufloria
 
-  # Install desktop entry
-  install -Dm644 "${pkgname}.desktop" \
-                 "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+    # legal
+    install -Dm644 "$srcdir"/tmp/config/license usr/share/licenses/$pkgname/LICENSE
+    ln -s /opt/EufloriaHD/Licenses.txt usr/share/licenses/$pkgname/LICENSES
 
-  # Install icon
-  install -Dm644 "${pkgdir}/opt/EufloriaHD/EufloriaHD.png" \
-                 "${pkgdir}/usr/share/pixmaps/eufloria.png"
-
-  # Install launcher symlink
-  case $CARCH in
-      i686) _arch=x86;;
-      x86_64) _arch=x86_64;;
-  esac
-  chmod 755 "${pkgdir}/opt/EufloriaHD/EufloriaHD.bin.${_arch}"
-  install -d "${pkgdir}/usr/bin"
-  ln -s "/opt/EufloriaHD/EufloriaHD.bin.${_arch}" "${pkgdir}/usr/bin/eufloria"
-
-  # Install license file
-  install -Dm644 "temp/config/license" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+    # doc
+    install -d usr/share/doc/$pkgname
+    ln -s /opt/EufloriaHD/ReadMe.pdf usr/share/doc/$pkgname/README.pdf
 }
 
-
-# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
-_get_humblebundle_source() {
-  _get_local_source "$1" || return 1;
-  # TODO: Implement automatic downloading from Humble Bundle site
-}
-
-# Locate a file or folder provided by the user, and symlink it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
-    echo -n "    - in $_key ['$_dir'] ... ";
-    if [ -e "$_dir/$1" ]; then
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-    echo "NOT FOUND"
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
-}
+# vim:et:sw=4:sts=4
