updated on Tue Jun  4 18:02:19 UTC 2013

diff --git a/kbdd-git/PKGBUILD b/kbdd-git/PKGBUILD
--- a/kbdd-git/PKGBUILD
+++ b/kbdd-git/PKGBUILD
@@ -1,37 +1,26 @@
 # Maintainer: petRUShka <petrushkin@yandex.ru>
-
 pkgname=kbdd-git
 pkgver=20120505
-pkgrel=1
+pkgrel=2
 pkgdesc="Simple daemon and library to make per window layout."
-arch=('i686' 'x86_64')
 url="https://github.com/qnikst/kbdd"
+arch=('i686' 'x86_64')
 license=('GPL3')
-depends=()
-provides=(kbdd)
-conflicts=(kbdd)
-source=()
-md5sums=()
-_gitroot="https://github.com/qnikst/kbdd.git"
-_gitname="kbdd"
+provides=('kbdd')
+conflicts=('kbdd')
+source=("${pkgname}::git+https://github.com/qnikst/kbdd.git")
+md5sums=('SKIP')
 
 build() {
-  cd "$srcdir"
-  msg "Connecting to GIT server...."
-
-  if [ -d $_gitname ] ; then
-    cd $_gitname && git pull origin
-    msg "The local files are updated."
-  else
-    git clone $_gitroot $_gitname
-  fi
-
-  cd "$startdir/src/$_gitname" || return 1
-
+  cd "${srcdir}/${pkgname}"
   aclocal
-  automake --add-missing || echo "Warning when automake"
+  automake --add-missing || echo "Automake errors ignored"
   autoreconf
-  ./configure --prefix=/usr || return 1
-  make || return 1
-  make DESTDIR="$startdir/pkg" install || return 1
+  ./configure --prefix=/usr
+  make
+}
+
+package() {
+  cd "${srcdir}/${pkgname}"
+  make PREFIX=/usr DESTDIR="${pkgdir}" install
 }
