updated on Sat Feb 18 15:05:27 UTC 2012

diff --git a/linux-ideapad/PKGBUILD b/linux-ideapad/PKGBUILD
--- a/linux-ideapad/PKGBUILD
+++ b/linux-ideapad/PKGBUILD
@@ -1,84 +1,71 @@
 # Contributor: graysky <graysky AT archlinux DOT us>
 # Contributor: Tobias Powalowski <tpowa@archlinux.org>
 # Contributor: Thomas Baechler <thomas@archlinux.org>
-###########################################################################################################
-#                                          Patch and Build Options
-###########################################################################################################
-#
-## Note all kernels get the ck patch set with BFS so there is no option to enable/disable it!
-#
-_usearchlogo="y"  # use the blue Arch logo rather than default tux logo when booting
-_makenconfig="n"	# select additional kernel options prior to a build via nconfig
-_localmodcfg="n"	# compile ONLY probed modules - see notes below!
-_localyescfg="n"	# convert all modules to core - see notes below!
-_use_current="n"	# use the current kernel's .config file - see notes below!
+
+### PATCH AND BUILD OPTIONS
+_makenconfig="n"	# tweak kernel options prior to a build via nconfig
+_localmodcfg="n"	# compile ONLY probed modules
+_use_current="n"	# use the current kernel's .config file
 _BFQ_enable_="n"	# enable BFQ as the default I/O scheduler
-###########################################################################################################
-#                                        More Details and References
-###########################################################################################################
-## LOCALMODCONFIG OPTION
-#  As of mainline 2.6.32, running with this option will only build the modules that you currently have
-#  probed in your system VASTLY reducing the number of modules built and the build time to do it.
+
+### DOCS
+# DETAILS FOR _localmodcfg="y"
+# As of mainline 2.6.32, running with this option will only build the modules that you currently have
+# probed in your system VASTLY reducing the number of modules built and the build time to do it.
 #
-#  WARNING - make CERTAIN that all modules are modprobed BEFORE you begin making the pkg!
+# WARNING - make CERTAIN that all modules are modprobed BEFORE you begin making the pkg!
 #
-#  To keep track of which modules are needed for your specific system/hardware, give my module_db script
-#  a try: http://aur.archlinux.org/packages.php?ID=41689  Note that if you use my script, this PKGBUILD 
-#  will auto run the reload_data base for you to probe all the modules you have logged!
-#  More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed_db
+# To keep track of which modules are needed for your specific system/hardware, give my module_db script
+# a try: http://aur.archlinux.org/packages.php?ID=41689  Note that if you use my script, this PKGBUILD 
+# will auto run the 'sudo modprobed_db reload' for you to probe all the modules you have logged!
 #
-## LOCALYESCONFIG OPTION
-#  This adds the option localyesconfig to make. This is similar to localmodconfig, but after it removes
-#  unnecessary modules it runs "sed -i s/=m/=y/" on the .config file. It then runs "make silentoldconfig"
-#  to fix any holes that were created by the conversion of modules to core.
-#
-## USE CURRENT KERNEL'S .CONFIG
-#  Enabling this option will use the .config of the RUNNING kernel rather than the ARCH defaults.
-#  Useful when the package gets updated and you already went through the trouble of customizing your
-#  config options.  NOT recommended when a new kernel is released, but again, convenient for package bumps.
-#
-## BFQ
-#  Alternative I/O scheduler by Paolo.  For more, see: http://algo.ing.unimo.it/people/paolo/disk_sched/
-###########################################################################################################
+# More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed_db
+
+# DETAILS FOR _use_current="y"
+# Enabling this option will use the .config of the RUNNING kernel rather than the ARCH defaults.
+# Useful when the package gets updated and you already went through the trouble of customizing your
+# config options.  NOT recommended when a new kernel is released, but again, convenient for package bumps.
+
+# DETAILS FOR _BFQ_enable="y"
+# Alternative I/O scheduler by Paolo.  For more, see: http://algo.ing.unimo.it/people/paolo/disk_sched/
 
 pkgname=linux-ideapad
 true && pkgname=(linux-ideapad linux-ideapad-headers)
 _kernelname=-ideapad
-_basekernel=3.1
-pkgver=${_basekernel}.5
+_basekernel=3.2
+pkgver=${_basekernel}.6
 pkgrel=2
 arch=('i686' 'x86_64')
 url="https://wiki.archlinux.org/index.php/linux-ideapad"
 license=('GPL2')
 options=('!strip')
-_ckpatchversion=2
-_ckpatchname="patch-${_basekernel}.0-ck${_ckpatchversion}"
-_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.1.0-v3r1"
+_ckpatchversion=1
+_ckpatchname="patch-${_basekernel}-ck${_ckpatchversion}"
+_bfqpath="http://algo.ing.unimo.it/people/paolo/disk_sched/patches/3.2.0-v3r2"
+source=("http://mirrors.arsc.edu/kernel/linux/kernel/v3.x/linux-3.2.tar.xz"
+"http://mirrors.arsc.edu/kernel/linux/kernel/v3.x/patch-${pkgver}.xz"
+"http://ck.kolivas.org/patches/3.0/3.2/${_basekernel}-ck${_ckpatchversion}/${_ckpatchname}.bz2"
+'config' 'config.x86_64' 'change-default-console-loglevel.patch' 'i915-fix-ghost-tv-output.patch'
+'i915-gpu-finish.patch' 'linux-ideapad.preset'
+"${_bfqpath}/0001-block-prepare-I-O-context-code-for-BFQ-v3r2-for-3.2.patch"
+"${_bfqpath}/0002-block-cgroups-kconfig-build-bits-for-BFQ-v3r2-3.2.patch"
+"${_bfqpath}/0003-block-introduce-the-BFQ-v3r2-I-O-sched-for-3.2.patch")
 
-source=("http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.1.tar.bz2"
-"http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.gz"
-"http://ck.kolivas.org/patches/3.0/3.1/${_basekernel}.0-ck${_ckpatchversion}/${_ckpatchname}.bz2"
-'change-default-console-loglevel.patch'
-'i915-fix-ghost-tv-output.patch'
-'i915-fix-incorrect-error-message.patch'
-'usb-add-reset-resume-quirk-for-several-webcams.patch'
-'config' 'config.x86_64'
-'linux-ideapad.install' 'linux-ideapad.preset'
-"${_bfqpath}/0001-block-prepare-I-O-context-code-for-BFQ-v3r1-for-3.1.patch"
-"${_bfqpath}/0002-block-cgroups-kconfig-build-bits-for-BFQ-v3r1-3.1.patch"
-"${_bfqpath}/0003-block-introduce-the-BFQ-v3r1-I-O-sched-for-3.1.patch"
-'logo_linux_mono.pbm' # optional Arch logo for boot
-logo_linux_{clut224,vga16}.ppm) # optional Arch logo for boot
 
 build() {
 	cd "${srcdir}/linux-${_basekernel}"
+
 	# add upstream patch
 	patch -p1 -i "${srcdir}/patch-${pkgver}"
 
 	# add latest fixes from stable queue, if needed
 	# http://git.kernel.org/?p=linux/kernel/git/stable/stable-queue.git
 
-	# Some chips detect a ghost TV output
+	# fix FS#27883
+  # drm/i915: Only clear the GPU domains upon a successful finish
+  patch -Np1 -i "${srcdir}/i915-gpu-finish.patch"
+
+  # Some chips detect a ghost TV output
 	# mailing list discussion: http://lists.freedesktop.org/archives/intel-gfx/2011-April/010371.html
 	# Arch Linux bug report: FS#19234
 	#
@@ -86,15 +73,6 @@ build() {
 	# then dropped because the reasoning was unclear. However, it is clearly
 	# needed.
 	patch -Np1 -i "${srcdir}/i915-fix-ghost-tv-output.patch"
-
-	# In 3.1.1, a DRM_DEBUG message is falsely declared as DRM_ERROR. This
-	# worries users, as this message is displayed even at loglevel 4. Fix
-	# this.
-	patch -Np1 -i "${srcdir}/i915-fix-incorrect-error-message.patch"
-
-	# Add the USB_QUIRK_RESET_RESUME for several webcams
-	# FS#26528
-	patch -Np1 -i "${srcdir}/usb-add-reset-resume-quirk-for-several-webcams.patch"
 
 	# set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
 	# remove this when a Kconfig knob is made available by upstream
@@ -104,7 +82,7 @@ build() {
 	### Patch source with ck patchset with BFS
 	# Fix double name in EXTRAVERSION
 	sed -i -re "s/^(.EXTRAVERSION).*$/\1 = /" "${srcdir}/${_ckpatchname}"
-	msg "Patching source with the ck2 patch set using bfs v0.415"
+	msg "Patching source with ck1 including bfs v0.416"
 	patch -Np1 -i "${srcdir}/${_ckpatchname}"
 
 	### Patch with BFQ IO Scheduler
@@ -123,20 +101,12 @@ build() {
 		cat "${srcdir}/config" > ./.config
 	fi
 
-	### Optionally use the blue Arch logo at kernel load
-	if [ $_usearchlogo = "y" ]; then
-		install -m644 ${srcdir}/logo_linux_clut224.ppm drivers/video/logo/
-		install -m644 ${srcdir}/logo_linux_mono.pbm drivers/video/logo/
-		install -m644 ${srcdir}/logo_linux_vga16.ppm drivers/video/logo/
-		sed -i -e 's/# CONFIG_LOGO is not set/CONFIG_LOGO=y\nCONFIG_LOGO_LINUX_MONO=y\nCONFIG_LOGO_LINUX_VGA16=y\nCONFIG_LOGO_LINUX_CLUT224=y/' ./.config
-	fi
-
 	### Optionally use running kernel's config
 	# code originally by nous; http://aur.archlinux.org/packages.php?ID=40191
 	if [ $_use_current = "y" ]; then
 		if [[ -s /proc/config.gz ]]; then
 			msg "Extracting config from /proc/config.gz..."
-			modprobe configs
+			# modprobe configs
 			zcat /proc/config.gz > ./.config
 		else
 			warning "You kernel was not compiled with IKCONFIG_PROC!"
@@ -155,8 +125,10 @@ build() {
 		-i -e s'/CONFIG_DEFAULT_CFQ=y/CONFIG_DEFAULT_CFQ=y\n# CONFIG_DEFAULT_BFQ is not set/' ./.config
 
 	### Optionally enable BFQ as the default io scheduler
-	[[ $_BFQ_enable_ = "y" ]] && sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
-		-i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	if [ $_BFQ_enable_ = "y" ]; then
+		sed -i -e '/CONFIG_DEFAULT_IOSCHED/ s,cfq,bfq,' \
+	 -i -e s'/CONFIG_DEFAULT_CFQ=y/# CONFIG_DEFAULT_CFQ is not set\nCONFIG_DEFAULT_BFQ=y/' ./.config
+	fi
 
 	# set extraversion to pkgrel
 	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
@@ -168,18 +140,13 @@ build() {
 	### Optionally load needed modules for the make localmodconfig
 	# See http://aur.archlinux.org/packages.php?ID=41689
 	if [ $_localmodcfg = "y" ]; then
-		msg "If you have modprobe_db installed, running reload_database now"
-		if [ -e /usr/bin/reload_database ]; then
-			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit
-			sudo /usr/bin/reload_database
+		msg "If you have modprobe_db installed, running it in recall mode now"
+		if [ -e /usr/bin/modprobed_db ]; then
+			[[ ! -x /usr/bin/sudo ]] && echo "Cannot call modprobe with sudo.  Install via pacman -S sudo and configure to work with this user." && exit 1
+			sudo /usr/bin/modprobed_db recall
 		fi
 		msg "Running Steven Rostedt's make localmodconfig now"
 		make localmodconfig
-	fi
-
-	if [ $_localyescfg = "y" ]; then
-		msg "Running make localyesconfig"
-		make localyesconfig
 	fi
 
 	if [ $_makenconfig = "y" ]; then
@@ -192,10 +159,10 @@ build() {
 }
 
 package_linux-ideapad() {
-_Kpkgdesc='Linux Kernel and modules with Brain Fuck Scheduler v0.415 and the ck2 patch set, built for Lenovo Y5xx laptops.'
+_Kpkgdesc='Linux Kernel and modules with the ck1 patchset featuring Brain Fuck Scheduler v0.416, built for Lenovo Y5xx laptops.'
 pkgdesc="${_Kpkgdesc}"
 depends=('coreutils' 'linux-firmware' 'module-init-tools>=3.16' 'mkinitcpio>=0.7')
-optdepends=('crda: to set the correct wireless channels of your country' 'lirc-ck: Linux Infrared Remote Control kernel modules for linux-ideapad' 'nvidia-ck: nVidia drivers for linux-ideapad' 'nvidia-beta-ck: nVidia beta drivers for linux-ideapad' 'modprobed_db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig')
+optdepends=('crda: to set the correct wireless channels of your country' 'lirc-ideapad: Linux Infrared Remote Control kernel modules for linux-ideapad' 'nvidia-ideapad: nVidia drivers for linux-ideapad' 'nvidia-beta-ideapad: nVidia beta drivers for linux-ideapad' 'modprobed_db: Keeps track of EVERY kernel module that has ever been probed - useful for those of us who make localmodconfig')
 provides=("linux-ideapad=${pkgver}")
 conflicts=('kernel26-ideapad')
 replaces=('kernel26-ideapad')
@@ -377,22 +344,17 @@ done
 rm -rf "${pkgdir}"/usr/src/linux-${_kernver}/arch/{alpha,arm,arm26,avr32,blackfin,cris,frv,h8300,ia64,m32r,m68k,m68knommu,mips,microblaze,mn10300,parisc,powerpc,ppc,s390,sh,sh64,sparc,sparc64,um,v850,xtensa}
 }
 # Global pkgdesc and depends are here so that they will be picked up by AUR
-pkgdesc='Linux Kernel and modules with Brain Fuck Scheduler v0.415 and the ck2 patch set, built for Lenovo Y5xx laptops.'
+pkgdesc='Linux Kernel and modules with the ck1 patchset featuring Brain Fuck Scheduler v0.416, built for Lenovo Y5xx laptops.'
 
-md5sums=('8d43453f8159b2332ad410b19d86a931'
-         '054cc9cdec0a2776c61087931c06fad9'
-         'a4c69095403ff44d5dfd8a935c3aca5a'
+md5sums=('364066fa18767ec0ae5f4e4abcf9dc51'
+         '0aea8fc5e705c5b1ef68697de9379cef'
+         'ca14fff2785d37e55eeb80c4e646c28f'
+         '80c5486f651d36db685a051feb36b09d'
+         '80c5486f651d36db685a051feb36b09d'
          '9d3c56a4b999c8bfbd4018089a62f662'
          '263725f20c0b9eb9c353040792d644e5'
-         'a50c9076012cb2dda49952dc6ec3e9c1'
-         '52d41fa61e80277ace2b994412a0c856'
-         'ae48eb603bdbdac4b6dc2ac4aa8e8cd7'
-         '95f6ec9f4d6f5a165c36ecc888fb69cb'
-         '989c96451870e410c5adec9a6c3eb870'
-         '5ca990b7396492ffce651611da0a8d86'
-         'e470805b4ef9d469a85b6e2f811ac337'
-         '61ca56c06bf197c0548ecd9fe01b2515'
-         '93e1b461374ae8b5147bba9887964cbe'
-         'e8c333eaeac43f5c6a1d7b2f47af12e2'
-         '5974286ba3e9716bfbad83d3f4ee985a'
-         'a6f0377c814da594cffcacbc0785ec1a')
+         'e787ef4bc66e2d9a7883eaece7a915b9'
+         'e9287bcf0308111498e0c86a1daa498e'
+         '8e8a772ad7f16ea9cd8d42c5cc8dbcf3'
+         '04004473d27209cc0112073a32cd318b'
+         '80c79fe5b699415ca9aee5f5a1d07b7f')
