updated on Fri Jul 22 10:01:00 UTC 2011

diff --git a/mozc-ut/uim-mozc.install b/mozc-ut/uim-mozc.install
--- a/mozc-ut/uim-mozc.install
+++ b/mozc-ut/uim-mozc.install
@@ -1,13 +1,19 @@
 post_install() {
+  echo -n "Registering mozc on uim..."
+  uim-module-manager --register mozc
+  [[ $? != 0 ]] && echo "Failed." || echo "Done."
+
   cat << _EOF
-  ==> sudo uim-module-manager --register mozc
-  ==> to register mozc on uim.
+  ==> You must run the following command to use mozc
+  ==> whenever you upgrade or (re-)install uim.
+
+  \`sudo uim-module-manager --register mozc'
+
 _EOF
 }
 
 post_remove() {
-  cat << _EOF
-  ==> sudo uim-module-manager --unregister mozc
-  ==> to unregister mozc from uim.
-_EOF
+  echo -n "Unregistering mozc from uim..."
+  uim-module-manager --unregister mozc
+  [[ $? != 0 ]] && echo "Failed." || echo "Done."
 }
