updated on Thu Jul  7 01:31:00 UTC 2011

diff --git a/compiz-core-dev/compiz.install b/compiz-core-dev/compiz.install
--- a/compiz-core-dev/compiz.install
+++ b/compiz-core-dev/compiz.install
@@ -1,15 +1,27 @@
 post_install() {
-	echo -e "\n#############################################################################\n"
-	echo -e "Compiz can be started manually by issuing 'compiz ccp --replace' from the command-line. Add the --indirect-rendering argument if you're using Intel graphics, or --loose-binding if Compiz is sluggish with NVIDIA graphics. " | fold -s
-	if [ -f /usr/share/applications/compiz.desktop ]; then
-		echo -e "\nWhen using GNOME, additional arguments can be appended to the 'Exec' line in /usr/share/applications/compiz.desktop to make permanent changes." | fold -s
-	fi
-	echo -e "\nTo get window decorations working, open CompizConfig Settings Manager (install ccsm-dev), navigate to Effects > Window Decoration and set the command as desired, i.e. enter 'gtk-window-decorator' if using GNOME, 'kde-window-decorator' or 'emerald' (a seperate package) and append '--replace'. GNOME users can install gnome-tweak-tool for convenient control of window decoration themes.\n\nPlease refer to the wiki entry on Compiz at https://wiki.archlinux.org/index.php/Compiz for further information." | fold -s
-	echo -e "\n#############################################################################\n"
+        if [[ -f /usr/bin/gtk-window-decorator && -f /usr/bin/gconftool-2 ]]; then
+	        export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
+	        echo -ne "\n:: Installing gtk-window-decorator schema file... "
+	        /usr/bin/gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/gwd.schemas > /dev/null
+	        if [ $? -gt 0 ]; then
+		        echo "Failed"
+	        else
+		        echo "OK"
+	        fi
+                echo -e "\nNew users may wish to install compizconfig-backend-gconf-dev for ease of setup."
+        fi
+	echo -e "\n=============================================================================\n"                 
+        echo -e "Compiz can be started manually by issuing 'compiz ccp --replace' from the command-line. Add the --indirect-rendering argument if you're using open source drivers and AIGLX (e.g. xf86-video-intel), or --loose-binding if Compiz is sluggish with proprietory NVIDIA drivers.\n\nFor further information, please refer to the following wiki entry:\n\nhttps://wiki.archlinux.org/index.php/Compiz" | fold -s
+        
+	echo -e "\n=============================================================================\n"
 }
 
 pre_remove()
 {
+        if [ -f /usr/bin/gconftool-2]; then
+	        export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
+	        /usr/bin/gconftool-2 --makefile-uninstall-rule /usr/share/gconf/schemas/gwd.schemas >/dev/null
+        fi
 	if [ -f /usr/share/gnome-session/sessions/gnome-compiz.session ]; then
 		read -N1 -p "Remove GNOME session entries? i.e. /usr/share/{gnome-session/sessions/gnome-compiz.session,xsessions/gnome-compiz.desktop} (y/n) "
 		echo -e "\n"
