updated on Thu Mar  8 17:00:10 UTC 2012

diff --git a/ganglia/ganglia.install b/ganglia/ganglia.install
--- a/ganglia/ganglia.install
+++ b/ganglia/ganglia.install
@@ -1,37 +1,34 @@
+# arg 1:  the new package version
 post_install() {
-  echo ">> Add group gangla ... "
-  groupadd ganglia
- 
-  echo ">> Add user ganglia, whose home directory is /var/lib/ganglia ... "
-  mkdir -p /var/lib/ganglia
-  mkdir -p /var/lib/ganglia/rrds
-  useradd ganglia -g ganglia -d /var/lib/ganglia -s /bin/false
-  chown -R ganglia:ganglia /var/lib/ganglia
-  
-  show_message;
+  post_upgrade
+  echo "If you plan to use the web interface, please make sure that your php" \
+       "open_basedir includes /usr/share/webapps and /var/lib/ganglia."
 }
 
+# arg 1:  the new package version
+# arg 2:  the old package version
 post_upgrade() {
-  show_message;
+  id ganglia  >& /dev/null
+  if [ $? -ne 0 ]; then
+     echo "Adding ganglia system group and user..."
+     groupadd -r ganglia
+     useradd -r -d /var/lib/ganglia -g ganglia -s /bin/false ganglia
+     # Lock the account to prevent logging in
+     passwd -l ganglia &> /dev/null
+  fi
+  install -d -o ganglia -g ganglia /var/lib/ganglia
+  install -d -o ganglia -g ganglia /var/lib/ganglia/rrds
+  install -d -o http -g http /var/lib/ganglia/dwoo
+  install -d -o http -g http /var/lib/ganglia/dwoo/cache
+  install -d -o http -g http /var/lib/ganglia/dwoo/compiled
+  install -d -o http -g http /var/lib/ganglia/conf
 }
 
+# arg 1:  the old package version
 post_remove() {
-  userdel -rf ganglia
-  groupdel -rf ganglia
+  echo "Removing ganglia system group and user..."
+  userdel ganglia
+  echo "NOTE: Please remove /var/lib/ganglia manually if it is no longer required."
 }
-
-show_message() {
-  echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
-  echo ">>                                                      >>"
-  echo ">> The default configuration files of gmond and gmetad, >>"
-  echo ">> and the web frontend of ganglia has been placed in   >>"
-  echo ">> /usr/share/ganglia.                                  >>"
-  echo ">>                                                      >>"
-  echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
-}
-
-op=$1
-shift
-[ "$(type -t "$op")" = "function" ] && $op "$@"
 
 # vim:set ts=2 sw=2 et:
