updated on Fri May 10 16:14:02 UTC 2013

diff --git a/haxe/PKGBUILD b/haxe/PKGBUILD
--- a/haxe/PKGBUILD
+++ b/haxe/PKGBUILD
@@ -4,8 +4,8 @@
 # Contributor: Michael Fellinger <mf@rubyists.com>
 
 pkgname=haxe
-pkgver=3.00.rc1
-pkgrel=4
+pkgver=3.0.0.rc2
+pkgrel=1
 pkgdesc="A multiplatform open source programming language"
 arch=('i686' 'x86_64')
 url='http://haxe.org/'
@@ -24,7 +24,7 @@ md5sums=('27d7af131da515355cca04b8b404feaa'
          '5e0e656293e92a6437d76f2f406438b5')
 
 
-_tag="http://haxe.googlecode.com/svn/tags/v${pkgver//./-}"
+_tag="http://haxe.googlecode.com/svn/tags/v${pkgver/%.rc2/-rc2}"
 
 build() {
   cd "$srcdir"
@@ -51,16 +51,16 @@ build() {
   msg2 "done."
   msg "Building tools..." && make tools || return 1  
   msg2 "done."  
-  msg "Generating api docs..."  
-  cd $srcdir/$pkgname/doc 
-  rm -rf content *.xml
-  env HAXE_LIBRARY_PATH=$srcdir/$pkgname/std $srcdir/$pkgname/haxe all.hxml  
-  [ ! \( -f flash8.xml -a -f flash9.xml -a -f neko.xml -a -f js.xml -a -f php.xml -a -f cpp.xml \) ] && return 1
-  $srcdir/$pkgname/std/tools/haxedoc/haxedoc -v "flash8.xml;flash8;flash" "neko.xml;neko" "js.xml;js" "flash9.xml;flash" "php.xml;php" "cpp.xml;cpp"
-  _res=$?
-  if [ $_res -eq 0 ]; then _msg="done."; else _msg="failed."; fi
-  echo && msg2 $_msg; 
-  return $_res
+  #msg "Generating api docs..."  
+  #cd $srcdir/$pkgname/doc 
+  #rm -rf content *.xml
+  #env HAXE_LIBRARY_PATH=$srcdir/$pkgname/std $srcdir/$pkgname/haxe all.hxml  
+  #[ ! \( -f flash8.xml -a -f flash9.xml -a -f neko.xml -a -f js.xml -a -f php.xml -a -f cpp.xml \) ] && return 1
+  #$srcdir/$pkgname/std/tools/haxedoc/haxedoc -v "flash8.xml;flash8;flash" "neko.xml;neko" "js.xml;js" "flash9.xml;flash" "php.xml;php" "cpp.xml;cpp"
+  #_res=$?
+  #if [ $_res -eq 0 ]; then _msg="done."; else _msg="failed."; fi
+  #echo && msg2 $_msg; 
+  #return $_res
 }
 
 package() {
@@ -71,8 +71,8 @@ package() {
   install --mode=644 -D --no-target-directory $srcdir/$pkgname/doc/LICENSE.txt "$pkgdir"/usr/share/$pkgname/LICENSE.txt
   install --mode=644 $srcdir/$pkgname/doc/CHANGES.txt "$pkgdir"/opt/haxe/
   install --mode=755 $srcdir/$pkgname/haxe{,lib,doc} "$pkgdir"/usr/bin/
-  cp --recursive $srcdir/$pkgname/doc/content "$pkgdir"/opt/haxe/doc/
-  install --mode=644 $srcdir/$pkgname/doc/index.html "$pkgdir"/opt/haxe/doc/
+#  cp --recursive $srcdir/$pkgname/doc/content "$pkgdir"/opt/haxe/doc/
+#  install --mode=644 $srcdir/$pkgname/doc/index.html "$pkgdir"/opt/haxe/doc/
 }
 
 # vim:set ts=2 sw=2 et:
