updated on Thu Jul 11 20:19:18 UTC 2013

diff --git a/spacechem-hib/PKGBUILD b/spacechem-hib/PKGBUILD
--- a/spacechem-hib/PKGBUILD
+++ b/spacechem-hib/PKGBUILD
@@ -1,46 +1,54 @@
-# Maintainer: Thomas Schneider <maxmusterm@gmail.com>
+#Maintainer: Claudio Kozicky <claudiokozicky@gmail.com>
 
 pkgname=spacechem-hib
 pkgver=1012
 pkgrel=1
-pkgdesc="An obscenely addictive, design-based puzzle game about building machines and fighting monsters in the name of science!"
-url="http://www.gameolith.com/game/spacechem/"
-license=('custom: "commercial"')
-arch=('i686' 'x86_64')
-makedepends=(binutils wget)
-#options=(!strip)
-#source=("${pkgname}.sh" "${pkgname}.desktop")
-#md5sums=('dff2d4a980e324c46198fb9193a23099'
-#         'b458899c445a8baa8238b9594ebee6c1')
-#if [[ $CARCH == x86_64 ]]; then
-#   _gamepkg="${pkgname}_${pkgver}_amd64.tar.gz"
-#else
-#   _gamepkg="${pkgname}_${pkgver}_i386.tar.gz"
-#fi
-
-depends=('mono' 'sdl' 'sdl_image' 'sdl_mixer' 'xclip')
+pkgdesc="An obscenely addictive, design-based puzzle game about building machines and fighting monsters in the name of science."
+arch=(i686 x86_64)
+url="http://spacechemthegame.com/"
+license=(custom)
+depends=(mono sdl_image sdl_mixer xclip)
+provides=spacechem
+conflicts=spacechem
+options=(!strip)
+[ $CARCH = x86_64 ]\
+    && depends+=(lib32-glibc)\
+    && source=(hib://spacechem-linux-1345144627-amd64.deb)\
+    && md5sums=(c08fb05e1909c0b4ccae82a862da6e3a)
+[ $CARCH = i686 ]\
+    && source=(hib://SpaceChem-i386.deb)\
+    && md5sums=(a12012f8df658c3e7a222f2db28070ce)
+PKGEXT=.pkg.tar
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 build() {
-   cd ${srcdir}
-   msg "You need a Humble Indie Bundle Key to download and install this game"
-   msg "Searching for a _humblebundlefrozensynapse variable with the key in it."
-   if [ ${_humblebundlefrozensynapse} ];then
-      msg "Found game package, installing..."
-   else
-      msg "Couldn't find the _humblebundlefrozensynapse variable"
-      msg "Please do 'export _humblebundlefrozensynapse=yourkey' where yourkey is replaced by your key."
-      msg "If you want automated updates without interaction you can place 'export _humblebundlefrozensynapse=yourkey' in your .bashrc file"
-      exit
-   fi
-# Download the file check it and hope for the best ;) I don't want to install a "downloaded patch" right now cause I like automagic updates but if someone asks I will implement it for sure
-   dlink=$(wget -O - "http://www.humblebundle.com/?key=${_humblebundlefrozensynapse}" 2> /dev/null|grep SpaceChem-1 --color|grep "Download .deb"|awk -F\' {'print $10'})
-   wget $dlink -O SpaceChem-$pkgver-hib.tar.gz -c
-   msg "Decompressing game files"
-   tar xfz SpaceChem-$pkgver-hib.tar.gz
-   ar x SpaceChem-i386.deb
+    cd "$srcdir"
+    bsdtar -xf data.tar.gz
 }
 
-package(){
-  cd ${srcdir}
-  tar xfz data.tar.gz -C ${pkgdir}
+package() {
+    # data
+    cd "$srcdir"
+    find opt -name readme -prune\
+             -o -name icon.png -prune\
+             -o -name spacechem.ico -prune\
+             -o -name zachtronicsindustries-spacechem.desktop -prune\
+             -o -type f -exec install -Dm644 '{}' "$pkgdir"/'{}' \;
+    chmod +x "$pkgdir"/opt/zachtronicsindustries/spacechem/{rgb2theora,spacechem-launcher.sh}
+
+    # launcher
+    install -d "$pkgdir"/usr/bin
+    ln -s /opt/zachtronicsindustries/spacechem/spacechem-launcher.sh "$pkgdir"/usr/bin/spacechem
+
+    # desktop integration
+    cd opt/zachtronicsindustries/spacechem
+    install -Dm644 icon.png "$pkgdir"/usr/share/pixmaps/zachtronicsindustries-spacechem.png
+    install -Dm644 zachtronicsindustries-spacechem.desktop "$pkgdir"/usr/share/applications/zachtronicsindustries-spacechem.desktop
+
+    # legal
+    cd readme
+    install -d "$pkgdir"/usr/share/licenses/spacechem-hib
+    find -type f -exec install -m644 '{}' "$pkgdir"/usr/share/licenses/spacechem-hib/'{}' \;
 }
+
+# vim: set sts=4 sw=4 et:
