updated on Thu Jun  7 20:00:14 UTC 2012

diff --git a/supermeatboy/PKGBUILD b/supermeatboy/PKGBUILD
--- a/supermeatboy/PKGBUILD
+++ b/supermeatboy/PKGBUILD
@@ -15,6 +15,7 @@ PKGEXT='.pkg.tar'
 
 _archive_md5="90a563ff103b4610b41af5fd2bccb21a"
 _archive="supermeatboy-linux-${_pkgver}-bin"
+hotfix_md5='65b4b39f961e7de7a4d0e018690e736d'
 
 build() {
   cd ${srcdir}
@@ -24,6 +25,7 @@ build() {
 		rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
 		wget http://www.humblebundle.com/?key=${_humblebundle4key}
 		wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
+    wget $(cat downloads\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
 		mv ${_archive}* ${_archive}
 	  elif [ -z "${_humblebundle4key}" ]; then
 		echo You can automate the download of the archive using the _humblebundle4key bash variable.
@@ -33,9 +35,10 @@ build() {
 		echo Press Enter to continue
 		read -a _unused
 	  fi
+    wget http://treefort.icculus.org/smb/smb-linux-mesa-hotfix-test.tar.bz2  
   fi
-  
-if [ ! -f ${_smbarchivelocation}${_archive} ]; then
+
+  if [ ! -f ${_smbarchivelocation}${_archive} ]; then
     echo "${_smbarchivelocation}${_archive} not found!"
     return 1
   fi  
@@ -45,8 +48,30 @@ if [ ! -f ${_smbarchivelocation}${_archive} ]; then
     return 1
   fi
 
+  if ! echo "${hotfix_md5}  ${srcdir}/smb-linux-mesa-hotfix-test.tar.bz2" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${srcdir}/smb-linux-mesa-hotfix-test.tar.bz2"
+    return 1
+  fi
+
   rm -Rf ${srcdir}/smb/
   unzip -d ${srcdir}/smb/ ${_smbarchivelocation}${_archive} || true
+
+  rm ${srcdir}/smb/data/{amd64,x86}/lib*
+  if test "$CARCH" == "i686"; then
+    rm -r ${srcdir}/smb/data/amd64
+  else
+    rm -r ${srcdir}/smb/data/x86
+  fi
+
+# Apply hotfix
+
+  mkdir ${srcdir}/hotfix/
+  tar -xvf ${srcdir}/smb-linux-mesa-hotfix-test.tar.bz2 -C ${srcdir}/hotfix
+  if test "$CARCH" == "i686"; then
+     cp -r ${srcdir}/hotfix/x86   ${srcdir}/smb/data/
+  else
+     cp -r ${srcdir}/hotfix/amd64/ ${srcdir}/smb/data/
+  fi
 
   mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/share/applications/ \
     ${pkgdir}/usr/bin/
@@ -57,3 +82,4 @@ if [ ! -f ${_smbarchivelocation}${_archive} ]; then
 }
 
 # vim: sts=2 ts=2 sw=2 et
+
