updated on Fri Mar  1 08:00:37 UTC 2013

diff --git a/supermeatboy/PKGBUILD b/supermeatboy/PKGBUILD
--- a/supermeatboy/PKGBUILD
+++ b/supermeatboy/PKGBUILD
@@ -1,45 +1,63 @@
-# Maintainer: zendeavor <j.s.mcgee115@gmail.com>
+# Contributor: zendeavor <j.s.mcgee115@gmail.com>
 # Contributor: Yochai Gal <yochaigal@gmail.com>
 # Contributor: Yann Kaiser <kaiser.yann@gmail.com>
+# Maintainer: Eric Anderson <ejona86@gmail.com>
 
 pkgname=supermeatboy
 pkgver=20120607
 _pkgver=06072012
-pkgrel=16
-pkgdesc="Super Meat Boy is a game where you play as a boy without skin whose girlfriend who is made of bandages gets kidnapped by a fetus in a tuxedo wearing a top hat and a monocle."
-url="http://www.supermeatboy.com/"
+pkgrel=17
+pkgdesc='An insanely hard and delightfully meaty platformer (game sold separately)'
+url='http://www.supermeatboy.com/'
 license=('custom')
 arch=('i686' 'x86_64')
-groups=("humble-indie-bundleV" "humble-indie-bundle4" "games")
-depends=('openal' 'sdl')
-source=("${pkgname}-linux-${_pkgver}-bin" 
-        "${pkgname}.install"
-        "${pkgname}.desktop"
-        "${pkgname}.sh")
-md5sums=("90a563ff103b4610b41af5fd2bccb21a"
-        "b25345577b44fbeeba96c6cc87f11c1e"
-        "7f7d1960582fe88f322265e0b98c2a8f"
-        "9b8ec81052ac2acfac07ce4a2a5a330d")
+depends=('openal' 'sdl' 'sh' 'gcc-libs')
+_gamepkg="${pkgname}-linux-${_pkgver}-bin"
+source=("hib://${_gamepkg}"
+        "${pkgname}.desktop")
+md5sums=('90a563ff103b4610b41af5fd2bccb21a'
+         'dc9beaef2fc60faa16d39aed8e84b0d3')
 makedepends=('unzip')
 options=('!strip')
-# if [[ -f "${source[0]%%:*}" ]]; then
-#   makedepends=('unzip')
-# else
-#   makedepends=('unzip' 'humblepie')
-# fi
-PKGEXT=".pkg.tar"
+# You can download the Humble Indie Bundle file manually, or you can configure
+# DLAGENTS in makepkg.conf to auto-download.
+#
+# For example, to use hib-dlagent to download files set something like this in
+# your makepkg.conf (change/add -k and add -u/-p to your needs):
+# DLAGENTS=('hib::/usr/bin/hib-dlagent -k 1a2b3c -o %o $(echo %u | cut -c 7-)')
+#
+# To auto-search through a directory containing Humble Bundle downloads, you
+# could set:
+# DLAGENTS=('hib::/usr/bin/find /path/to/downloads -name $(echo %u | cut -c 7-) -exec ln -s \{\} %o \; -quit')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Download the file manually to \"$(pwd)\" or setup hib:// DLAGENT in /etc/makepkg.conf"; echo "Read this PKGBUILD for more info."; exit 1')
+PKGEXT='.pkg.tar'
 
-package() {
-  mkdir -p "${pkgdir}/opt/games/${pkgname}"
-  [[ -f "${source[0]}" ]] ||
-    error "Place the game or a symlink to the game in ${startdir}"
-  unzip -u "${source[0]}" -d "${pkgdir}/opt/games/${pkgname}" || true
-  find "${pkgdir}" -type f -exec chmod 644 "{}" +
-  install -Dm644 "${pkgname}".desktop "${pkgdir}/usr/share/applications/${pkgname}.desktop"
-  install -Dm755 "${pkgname}".sh "${pkgdir}/usr/bin/${pkgname}"
-  chmod 755 "${pkgdir}/opt/games/${pkgname}/data/SuperMeatBoy" \
-    "${pkgdir}/opt/games/${pkgname}/data/amd64/SuperMeatBoy-amd64" \
-    "${pkgdir}/opt/games/${pkgname}/data/x86/SuperMeatBoy-x86"
+build() {
+  cd "${srcdir}"
+  unzip -u "${_gamepkg}" -d "${pkgname}-${pkgver}" || true
 }
 
-# vim: ft=PKGBUILD sts=2 ts=2 sw=2 et
+package() {
+  cd "${srcdir}/${pkgname}-${pkgver}"
+
+  if [ "$CARCH" = "x86_64" ]; then
+    _arch='amd64'
+    _rmarch='x86'
+  else
+    _arch='x86'
+    _rmarch='amd64'
+  fi
+
+  install -d "${pkgdir}/opt"
+  cp -Rl data "${pkgdir}/opt/${pkgname}"
+  chmod 644 "${pkgdir}/opt/${pkgname}/resources/Shaders/"*.bin
+  rm -rf "${pkgdir}/opt/${pkgname}/${_rmarch}"
+  # Use system-provided libraries.
+  rm "${pkgdir}/opt/${pkgname}/${_arch}/libopenal.so.1"
+  rm "${pkgdir}/opt/${pkgname}/${_arch}/libSDL-1.2.so.0"
+
+  install -d "${pkgdir}/usr/bin/"
+  ln -s "/opt/${pkgname}/SuperMeatBoy" "${pkgdir}/usr/bin/${pkgname}"
+  install -Dm644 "${srcdir}/${pkgname}.desktop" \
+      "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+}
