updated on Tue Jan 17 17:00:56 UTC 2012

diff --git a/supermeatboy/PKGBUILD b/supermeatboy/PKGBUILD
--- a/supermeatboy/PKGBUILD
+++ b/supermeatboy/PKGBUILD
@@ -1,4 +1,4 @@
-# Maintainer: Yann Kaiser <kaiser.yann@gmail.com>
+# Maintainer: Yochai Gal <yochaigal@gmail.com>
 pkgname=supermeatboy
 pkgver=20111213b
 _pkgver=12132011b
@@ -8,13 +8,13 @@ arch=('i686' 'x86_64')
 url="http://www.supermeatboy.com/"
 license=('custom')
 depends=('openal' 'sdl')
-makedepends=('unzip')
+makedepends=('unzip' 'tar')
 source=('supermeatboy.desktop')
 md5sums=('ceda8cdca2aaff63a9cae2ef7d7cf0d4')
 PKGEXT='.pkg.tar'
 
 _archive_md5="e27c7a2506cbf7047f51a2230f7d1b0f"
-
+hotfix_md5='65b4b39f961e7de7a4d0e018690e736d'
 _archive="supermeatboy-linux-${_pkgver}-bin"
 
 build() {
@@ -34,6 +34,7 @@ build() {
 		echo Press Enter to continue
 		read -a _unused
 	  fi
+    wget http://treefort.icculus.org/smb/smb-linux-mesa-hotfix-test.tar.bz2  
   fi
 #'
 
@@ -47,6 +48,11 @@ build() {
     return 1
   fi
 
+  if ! echo "${hotfix_md5}  ${srcdir}/smb-linux-mesa-hotfix-test.tar.bz2" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${srcdir}/smb-linux-mesa-hotfix-test.tar.bz2"
+    return 1
+  fi
+
   rm -Rf ${srcdir}/smb/
   unzip -d ${srcdir}/smb/ ${_smbarchivelocation}${_archive} || true
 
@@ -55,6 +61,16 @@ build() {
     rm -r ${srcdir}/smb/data/amd64
   else
     rm -r ${srcdir}/smb/data/x86
+  fi
+
+# Apply hotfix
+
+  mkdir ${srcdir}/hotfix/
+  tar -xvf ${srcdir}/smb-linux-mesa-hotfix-test.tar.bz2 -C ${srcdir}/hotfix
+  if test "$CARCH" == "i686"; then
+     cp -r ${srcdir}/hotfix/x86   ${srcdir}/smb/data/
+  else
+     cp -r ${srcdir}/hotfix/amd64/ ${srcdir}/smb/data/
   fi
 
   mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/share/applications/ \
