updated on Tue Jun 12 10:00:23 UTC 2012

diff --git a/lonesurvivor/PKGBUILD b/lonesurvivor/PKGBUILD
--- a/lonesurvivor/PKGBUILD
+++ b/lonesurvivor/PKGBUILD
@@ -7,73 +7,46 @@ pkgrel=5
 pkgdesc="a psychological survival adventure, with art, design, and music by the one-man studio"
 arch=('i686' 'x86_64')
 url="http://www.superflatgames.com/"
+groups=("humble-indie-bundleV" "games")
 license=('custom')
 case $CARCH in 
     i686) depends=('gtk2' 'nss' 'libxft');;
     x86_64)depends=('lib32-gtk2' 'lib32-nss' 'lib32-curl' 'lib32-libxft');;
 esac
-makedepends=('aria2')
 PKGEXT='.pkg.tar'
 case $CARCH in 
-    i686) _arch=i386; _md5='c267e7b6c9a20ca40ee8e795bc92a3fa';;
-    x86_64) _arch=amd64; _md5='4d099e1bf1a4fdb30b8b7cff3b485d38';;
+    i686) _arch=i386; md5sums=('c267e7b6c9a20ca40ee8e795bc92a3fa' '7520a6930d3bc2cbc62a83f0724f7dce');;
+    x86_64) _arch=amd64; md5sums=('4d099e1bf1a4fdb30b8b7cff3b485d38' '7520a6930d3bc2cbc62a83f0724f7dce');;
 esac
+source=($pkgname-$_pkgver-$_arch.tar.gz
+        $pkgname.desktop)
 options=(!strip)
 
-
-build() {
-    cd $srcdir
-    if [[ -f ../$pkgname-$_pkgver-$_arch.tar.gz && ! -f $pkgname-$_pkgver-$_arch.tar.gz ]]; then
-        ln -s ../$pkgname-$_pkgver-$_arch.tar.gz ./$pkgname-$_pkgver-$_arch.tar.gz
-        testmd5=$(md5sum $pkgname-$_pkgver-$_arch.tar.gz)
-    fi
-    if [[ ! -f $pkgname-$_pkgver-$_arch.tar.gz || ${testmd5%% *} != $_md5 ]]; then
-        echo "You do not have the file required for this install"
-        echo if you already have $pkgname-$_pkgver-$_arch.tar.gz please place it into $PWD
-        echo Otherwise, press Enter to continue
-        read
-        if [[ -z "${_humblebundleVkey}" ]]; then
-            echo You can automate the download of the archive using the _humblebundleVkey bash variable.
-            echo "Just add export  '_humblebundleVkey=<Your key here>' to .bashrc"
-            echo
-            echo Otherwise please just place ${_sh} into $(pwd)/
-            read
+_humblebundle() {
+    export _archive="source[0]%%:*"
+    while [[ ! -f ${!_archive} ]];do
+        if [[ -n "${_humblebundleVkey}" ]]; then
+            _uri="$(curl -s http://www.humblebundle.com/downloads\?key\="${_humblebundleVkey}" | grep "${!_archive}")"
+            _uri="${_uri##*data-web\=\'}"
+            _uri="${_uri%%\'*}" 
+            curl -o "${!_archive}" "${_uri}"
         else
-            testfile=$(curl https://www.humblebundle.com/downloads\?key\=$_humblebundleVkey | grep "$pkgname-$_pkgver-$_arch")
-            echo "if you would like to use:"
-            echo "aria2c and the torrent file, input 1"
-            echo "curl and download the file directly, input 2"
-            echo "default is 1, 2 costs HIB bandwidth:"
-            read -a _torrent
-            if [[ $_torrent -eq 2 ]];then
-                testfile=${testfile#*data-web\=\'}
-                curl -o $pkgname-$_pkgver-$_arch.tar.gz ${testfile%%\'*}
-            else
-                testfile=${testfile##*data-bt\=\'}
-                curl -o $pkgname.torrent ${testfile%%\'*}
-                aria2c --seed-time=0 $pkgname.torrent
-            fi
+            warning "Please export _humblebundleVkey for downloading"
+            echo "Alternatively, place the download into ${startdir} and retry"
         fi
-    fi
-    _md5sum=$(md5sum "$pkgname-$_pkgver-$_arch.tar.gz");
-    if [[ ${_md5sum%% *} == $_md5 ]];then
-        bsdtar xf "$pkgname-$_pkgver-$_arch.tar.gz"
-    else
-        echo "md5sum of downloaded file is invalid"
-        exit
-    fi
-cat <<EOF > lonesurvivor.desktop
-[Desktop Entry]
-Categories=Game;
-Name=Lone Survivor
-Exec=/usr/bin/lonesurvivor
-Icon=/usr/share/applications/lonesurvivor.png
-Type=Application
-EOF
+        if [[ -z "${_humblebundVkey}" && ! -f "${startdir}/${!_archive}" ]]; then
+            error "Failed to download \"${!_archive}\"."
+            exit 1
+        fi
+        unset _archive _key _uri 
+    done
 }
+
+
 package () {
     cd $srcdir/$pkgname
     install -Dm755 "$srcdir/$pkgname/LoneSurvivor" "$pkgdir/usr/bin/$pkgname"
     install -Dm644 "$srcdir/$pkgname/LoneSurvivor.png" "$pkgdir/usr/share/applications/$pkgname.png"
     install -Dm644 "$srcdir/$pkgname.desktop" "$pkgdir/usr/share/applications/$pkgname.desktop"
 }
+_humblebundle
