updated on Mon Jan 27 00:48:22 UTC 2014

diff --git a/compiz-dev/PKGBUILD b/compiz-dev/PKGBUILD
--- a/compiz-dev/PKGBUILD
+++ b/compiz-dev/PKGBUILD
@@ -1,49 +1,66 @@
 # Maintainer: Ryon Sherman <ryon.sherman@gmail.com>
 # Contributor: Iven Hsu <ivenvd AT gmail>
 # Contributor: Nathan Hulse <nat.hulse@gmail.com>
+# Contributor: Charles Bos <charlesbos1 AT gmail>
 
 pkgname=compiz-dev
-pkgseries=0.9.10
-pkgver=${pkgseries}.0
-pkgrel=1
+_pkgseries=0.9.10
+pkgver=${_pkgseries}.0
+pkgrel=2
 pkgdesc="Composite manager for Aiglx and Xgl, with plugins and CCSM (development milestone)"
 
 arch=('i686' 'x86_64')
 license=('GPL' 'LGPL' 'MIT')
 url="https://launchpad.net/compiz"
 
-conflicts=('compiz-bzr' 'compiz-core' 'compiz-fusion-plugins-main' 'compiz-fusion-plugins-extra' 'compiz-decorator-gtk' 'compiz-decorator-kde' 'libcompizconfig' 'compizconfig-python' 'compizconfig-backend-gconf' 'compiz-bcop' 'ccsm')
 replaces=('compiz-bzr' 'compiz-core' 'compiz-fusion-plugins-main' 'compiz-fusion-plugins-extra' 'compiz-decorator-gtk' 'compiz-decorator-kde' 'libcompizconfig' 'compizconfig-python' 'compizconfig-backend-gconf' 'compiz-bcop' 'ccsm')
+conflicts=('compiz-bzr' 'compiz-core' 'compiz-fusion-plugins-main' 'compiz-fusion-plugins-extra' 'compiz-decorator-gtk' 'compiz-decorator-kde' 'libcompizconfig' 'compizconfig-python' 'compizconfig-backend-gconf' 'compiz-bcop' 'ccsm')
 
 makedepends=('intltool' 'cmake')
-depends=('boost' 'xorg-server' 'libxcomposite' 'startup-notification' 'librsvg' 'dbus' 'mesa' 'libxslt' 'fuse' 'glibmm' 'libxrender' 'gmock' 'libwnck' 'pygtk' 'desktop-file-utils' 'pyrex' 'protobuf')
+depends=('boost' 'xorg-server' 'libxcomposite' 'startup-notification' 'librsvg' 'dbus' 'mesa' 'libxslt' 'fuse' 'glibmm' 'libxrender' 'gmock' 'libwnck' 'pygtk' 'desktop-file-utils' 'pyrex' 'protobuf' 'metacity' 'gconf' 'gnome-themes-standard' 'glu')
 optdepends=(
-  'dconf: for GSettings backend support'
-  'gtk2: for GTK window decorator (then rebuild this package)'
-  'metacity: Metacity window decoration themes support (then rebuild this package)'
-  'gnome-control-center: GNOME keybindings support (then rebuild this package)'
-  'kdebase-lib: KDE window decoration support (then rebuild this package)'
-  'automoc: KDE window decoration support (then rebuild this package)'
+  'dconf: for GSettings backend support (need to rebuild this package)'
+  'gnome-control-center: GNOME keybindings support (need to rebuild this package)'
+  'kdebase-lib: KDE window decoration support (need to rebuild this package)'
+  'automoc: KDE window decoration support (need to rebuild this package)'
+  'xorg-xprop: grab various window properties for use in window matching rules'
 )
 
 install='compiz-dev.install'
-source=(
-  "https://launchpad.net/compiz/${pkgseries}/${pkgver}/+download/compiz-${pkgver}.tar.bz2"
-)
-md5sums=(
-  'c65fe20e464405889d77a0783fa52f20'
-)
+source=("https://launchpad.net/compiz/${_pkgseries}/${pkgver}/+download/compiz-${pkgver}.tar.bz2")
+md5sums=('c65fe20e464405889d77a0783fa52f20')
 
 # GTK window decorator support
-GTKWINDOWDECORATOR="off"
+GTKWINDOWDECORATOR="on"
 # Metaciy theme support for GTK window decorator
-METACITY="off"
+METACITY="on"
 # KDE window decorator support
 KDEWINDOWDECORATOR="off"
 # GConf backend support
 GCONF="on"
 # GSettings backend support
 GSETTINGS="on"
+
+# Do some basic option validation in order to handle build failures a bit more elegantly.
+
+if [ "${GTKWINDOWDECORATOR}" == "on" ]; then
+  CHECKGCONF=`pacman -Q gconf 2>/dev/null`
+  if [ ! "${CHECKGCONF}" ]; then
+    msg "Currently, gconf must be installed in order to build gtk-window-decorator."
+    exit 1
+  fi
+  if [ "${GCONF}" != "on" ]; then
+    msg "Currently, GCONF must be 'on' in order to build gtk-window-decorator."
+    exit 1
+  fi
+fi
+
+if [ "${GSETTINGS}" == "on" ]; then
+  if [ "${GCONF}" != "on" ]; then
+    msg "Currently, GCONF must be 'on' in order to enable gsettings support."
+    exit 1
+  fi
+fi
 
 prepare() {
   cd "compiz-${pkgver}"
@@ -55,10 +72,10 @@ prepare() {
 
   mkdir build; cd build
   cmake .. \
+    -DCMAKE_BUILD_TYPE="Release" \
     -DCMAKE_INSTALL_PREFIX="/usr" \
     -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
     -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so \
-    -DCMAKE_BUILD_TYPE="Release" \
     -DQT_QMAKE_EXECUTABLE=qmake-qt4 \
     -DCOMPIZ_DISABLE_SCHEMAS_INSTALL=On \
     -DCOMPIZ_BUILD_WITH_RPATH=Off \
