updated on Wed Jul 30 00:00:06 UTC 2014

diff --git a/binx32-python2/PKGBUILD b/binx32-python2/PKGBUILD
--- a/binx32-python2/PKGBUILD
+++ b/binx32-python2/PKGBUILD
@@ -1,36 +1,36 @@
-# $Id: PKGBUILD 157114 2012-04-24 00:17:20Z stephane $
-# Upstream Maintainer: Stéphane Gaudreault <stephane@archlinux.org>
-# Contributer: Allan McRae <allan@archlinux.org>
-# Contributer: Jason Chu <jason@archlinux.org>
-# Maintainer: Fantix King <fantix.king at gmail.com>
+# $Id: PKGBUILD 216192 2014-07-02 07:39:22Z fyan $
+# Maintainer: Felix Yan <felixonmars@gmail.com>
+# Contributor: Stéphane Gaudreault <stephane@archlinux.org>
+# Contributor: Allan McRae <allan@archlinux.org>
+# Contributor: Jason Chu <jason@archlinux.org>
+# x32 Maintainer: Fantix King <fantix.king at gmail.com>
 
 _basepkgname=python2
 pkgname=binx32-python2
-pkgver=2.7.3
-pkgrel=2.5
+pkgver=2.7.8
+pkgrel=1
 _pybasever=2.7
 pkgdesc="A high-level scripting language (x32 ABI)"
 arch=('x86_64')
 license=('PSF')
 url="http://www.python.org/"
-depends=("${_basepkgname}=${pkgver}" 'libx32-bzip2' 'libx32-gdbm' 'libx32-openssl' 'libx32-zlib' 'libx32-expat' 'libx32-sqlite3' 'libx32-libffi')
-makedepends=('binx32-tk' 'libx32-ncurses' 'libx32-readline')
+depends=("${_basepkgname}=${pkgver}" 'libx32-bzip2' 'libx32-gdbm' 'libx32-openssl' 'libx32-zlib' 'libx32-expat' 'libx32-sqlite' 'libx32-libffi')
+makedepends=('binx32-tk' 'bluez-libs')
 optdepends=('binx32-tk: for IDLE')
 conflicts=('python2-x32')
 replaces=('python2-x32')
 provides=('python2-x32')
-options=('!makeflags')
 source=(
     http://www.python.org/ftp/python/${pkgver%rc?}/Python-${pkgver}.tar.xz
     Python-2.7.3-multilib-1.patch
     pyconfig-stub.h
 )
-sha1sums=('b2b0ada7ebed4a8204a855193afbdb3aa3308357'
-          '789e6a31c2d05a35f2ce437acc254ed6a084808b'
+sha1sums=('9c6281eeace0c3646fa556c8087bb1b7e033c9c4'
+          '533eb9f7d78feff1f5d73887a968ddc5ec486bc2'
           '0ad4a8f98b0d111b603323aad7327fcc349927bc')
 
-build() {
-  cd "${srcdir}/Python-${pkgver}"
+prepare() {
+  cd Python-${pkgver}
 
   # http://cblfs.cross-lfs.org/index.php/Python
   patch -p1 -i ${srcdir}/Python-2.7.3-multilib-1.patch
@@ -61,59 +61,86 @@ build() {
   # FS#23997
   sed -i -e "s|^#.* /usr/local/bin/python|#!/usr/bin/python2-x32|" Lib/cgi.py
 
+  sed -i "s/python2.3/python2-x32/g" Lib/distutils/tests/test_build_scripts.py \
+     Lib/distutils/tests/test_install_scripts.py
+
   # Ensure that we are using the system copy of various libraries (expat, zlib and libffi),
   # rather than copies shipped in the tarball
   rm -r Modules/expat
   rm -r Modules/zlib
   rm -r Modules/_ctypes/{darwin,libffi}*
 
+  # clean up #!s
+  find . -name '*.py' | \
+    xargs sed -i "s|#[ ]*![ ]*/usr/bin/env python$|#!/usr/bin/env python2-x32|"
+
+  # Workaround asdl_c.py error after we touched the shebangs
+  touch Include/Python-ast.h Python/Python-ast.c
+}
+
+build() {
+  cd "${srcdir}/Python-${pkgver}"
+
   export OPT="${CFLAGS}"
   export CC="gcc -mx32"
   export CXX="g++ -mx32"
-  ./configure --prefix=/usr --enable-shared --with-threads --enable-ipv6 \
-              --enable-unicode=ucs4 --with-system-expat --with-system-ffi \
+  ./configure --prefix=/usr \
+              --enable-shared \
+              --with-threads \
+              --enable-ipv6 \
+              --enable-unicode=ucs4 \
+              --with-system-expat \
+              --with-system-ffi \
               --with-dbmliborder=gdbm:ndbm --libdir=/usr/libx32
 
   make
 }
 
+check() {
+  # As of 2.7.7, 1 test failed:
+  # test_uuid
+  # Besides, test_thread disabled as it will stuck
+
+  cd Python-${pkgver}
+  LD_LIBRARY_PATH="${srcdir}/Python-${pkgver}":${LD_LIBRARY_PATH} \
+    "${srcdir}/Python-${pkgver}/python" -m test.regrtest -uall -x test_thread || warning "Tests failed"
+}
+
 package() {
   install="${pkgname}.install"
 
-  cd "${srcdir}/Python-${pkgver}"
+  cd Python-${pkgver}
   make DESTDIR="${pkgdir}" altinstall maninstall
   mv ${pkgdir}/usr/bin/python${_pybasever} ${pkgdir}/usr/bin/python${_pybasever}-x32
   mv ${pkgdir}/usr/bin/python${_pybasever}-config ${pkgdir}/usr/bin/python${_pybasever}-x32-config
 
-  ln -sf python${_pybasever}-x32        "${pkgdir}/usr/bin/python2-x32"
-  ln -sf python${_pybasever}-x32-config "${pkgdir}/usr/bin/python2-x32-config"
+  rm "${pkgdir}"/usr/share/man/man1/python.1
 
-  ln -sf ../../libpython${_pybasever}.so \
-    "${pkgdir}/usr/libx32/python${_pybasever}/config/libpython${_pybasever}.so"
+  ln -sf python${_pybasever}-x32        "${pkgdir}"/usr/bin/python2-x32
+  ln -sf python${_pybasever}-x32-config "${pkgdir}"/usr/bin/python2-x32-config
 
-  mv "${pkgdir}/usr/bin/smtpd.py" "${pkgdir}/usr/libx32/python${_pybasever}/"
+  # FS#33954
+  ln -sf python-${_pybasever}.pc    "${pkgdir}"/usr/libx32/pkgconfig/python2-x32.pc
+
+  ln -sf ../../libpython${_pybasever}.so "${pkgdir}"/usr/libx32/python${_pybasever}/config/libpython${_pybasever}.so
+
+  mv "${pkgdir}"/usr/bin/smtpd.py "${pkgdir}"/usr/libx32/python${_pybasever}/
 
   # some useful "stuff"
   install -dm755 "${pkgdir}"/usr/libx32/python${_pybasever}/Tools/{i18n,scripts}
-  install -m755 Tools/i18n/{msgfmt,pygettext}.py \
-    "${pkgdir}/usr/libx32/python${_pybasever}/Tools/i18n/"
-  install -m755 Tools/scripts/{README,*py} \
-    "${pkgdir}/usr/libx32/python${_pybasever}/Tools/scripts/"
+  install -m755 Tools/i18n/{msgfmt,pygettext}.py "${pkgdir}"/usr/libx32/python${_pybasever}/Tools/i18n/
+  install -m755 Tools/scripts/{README,*py} "${pkgdir}"/usr/libx32/python${_pybasever}/Tools/scripts/
 
   # clean up redundant scripts
   mv "${pkgdir}"/usr/bin/idle{,2-x32}
   rm "${pkgdir}"/usr/bin/pydoc
   rm "${pkgdir}"/usr/bin/2to3
 
-  # clean up #!s
-  find "${pkgdir}/usr/libx32/python${_pybasever}/" -name '*.py' | \
-    xargs sed -i "s|#[ ]*![ ]*/usr/bin/env python$|#!/usr/bin/env python2-x32|"
   sed -i "s|#[ ]*![ ]*/usr/bin/python${_pybasever}$|#!/usr/bin/python${_pybasever}-x32|" \
     "${pkgdir}/usr/bin/python${_pybasever}-x32-config" "${pkgdir}/usr/bin/idle2-x32"
 
   # clean-up reference to build directory
-  sed -i "s#${srcdir}/Python-${pkgver}:##" \
-    "${pkgdir}/usr/libx32/python${_pybasever}/config/Makefile"
+  sed -i "s#${srcdir}/Python-${pkgver}:##" "${pkgdir}"/usr/libx32/python${_pybasever}/config/Makefile
 
   mv "${pkgdir}/usr/include/python${_pybasever}/pyconfig.h" "${srcdir}/pyconfig-x32.h"
   rm -rf "${pkgdir}/usr/"{include,share}
