updated on Mon Sep 23 10:07:20 UTC 2013

diff --git a/wizorb-hib/PKGBUILD b/wizorb-hib/PKGBUILD
--- a/wizorb-hib/PKGBUILD
+++ b/wizorb-hib/PKGBUILD
@@ -1,35 +1,34 @@
 # Maintainer: Prurigro
+# Contributor: Prurigro
 # Adapted from the wizorb package contributed by TastyPi
+# Humble Bundle agent stuff taken from eetsmunchies-hib package by Sam S.
 
-pkgname=wizorb-hib
-_pkgrealname=wizorb
+_pkgname=wizorb
+pkgname=${_pkgname}-hib
 pkgver=1.1
 pkgrel=1
 pkgdesc="A retro-RPG themed breakout style game (Humble Bundle version)"
-arch=('i686' 'x86_64')
 url="http://www.wizorb.com"
-license=('custom')
+license=('custom:commercial')
 depends=('mono' 'openal')
-source=("${_pkgrealname}.sh"
-        "${_pkgrealname}.desktop")
+arch=('i686' 'x86_64')
+options=('!strip' '!upx')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
-sha1sums=('dea46fe1ac633987752e0f0b3fe60ab69239d5f3'
-          '14b2af850402f2ff6328727cccec7f5073c8b862')
+[ $CARCH == "i686" ] && _arch=32 && _sha1sum='688b403632cec54c8cb87ed941c3b5d5f5b56c7a' || _arch=64 && _sha1sum='f3c0fe8f2cdbf742a19d620ecfb831dbc6487b00'
 
-if [[ "$CARCH" -eq x86_64 ]]; then
-    source=("${source[@]}" "${_pkgrealname}-64bit.tar.gz")
-    sha1sums=("${sha1sums[@]}" 'f3c0fe8f2cdbf742a19d620ecfb831dbc6487b00')
-else
-    source=("${source[@]}" "${_pkgrealname}-32bit.tar.gz")
-    sha1sums=("${sha1sums[@]}" '688b403632cec54c8cb87ed941c3b5d5f5b56c7a')
-fi
+source=("hib://${_pkgname}-${_arch}bit.tar.gz"
+        "${_pkgname}.sh"
+        "${_pkgname}.desktop")
 
-build() {
-    pushd ${srcdir}
-        install -d ${pkgdir}/opt/${_pkgrealname}
-        cp -r ${_pkgrealname}/* ${pkgdir}/opt/${_pkgrealname}
-        install -Dm755 ${_pkgrealname}.sh ${pkgdir}/usr/bin/${_pkgrealname}
-        install -Dm644 ${_pkgrealname}.desktop ${pkgdir}/usr/share/applications/${_pkgrealname}.desktop
-    popd
+sha1sums=("$_sha1sum"
+          "dea46fe1ac633987752e0f0b3fe60ab69239d5f3"
+          "14b2af850402f2ff6328727cccec7f5073c8b862")
+
+package() {
+    install -d "${pkgdir}"/opt/${_pkgname}
+    cp -r "${srcdir}"/${_pkgname}/* "${pkgdir}"/opt/${_pkgname}
+    install -Dm755 "${srcdir}"/${_pkgname}.sh "${pkgdir}"/usr/bin/${_pkgname}
+    install -Dm644 "${srcdir}"/${_pkgname}.desktop "${pkgdir}"/usr/share/applications/${_pkgname}.desktop
 }
 
