updated on Tue Sep  4 03:00:12 UTC 2012

diff --git a/sweethome3d/sweethome3d b/sweethome3d/sweethome3d
--- a/sweethome3d/sweethome3d
+++ b/sweethome3d/sweethome3d
@@ -14,8 +14,14 @@ elif [ -d /opt/sun-java6 ] ; then
 		echo "Err: missing JAVAWS ($JAVAWS)"
 		exit 1
 	fi
+elif [ -d /opt/java ] ; then
+	JAVAWS="$JAVA_HOME"/jre/lib/javaws.jar
+	if [ ! -r $JAVAWS ] ; then
+		echo "Err: missing JAVAWS ($JAVAWS)"
+		exit 1
+	fi
 else
-	echo "Err: Please install openjdk or sun-java6"
+	echo "Err: Please install openjdk or jre+jdk>=7.7 or sun-java6"
 	exit 1
 fi
 
