updated on Fri Aug 17 02:05:35 UTC 2012

diff --git a/sweethome3d/sweethome3d b/sweethome3d/sweethome3d
--- a/sweethome3d/sweethome3d
+++ b/sweethome3d/sweethome3d
@@ -1,6 +1,5 @@
 #!/bin/sh
-cd /usr/share/java/sweethome3d
-PROGRAM_DIR=$PWD
+PROGRAM_DIR=/usr/share/java/sweethome3d
 if [ -d /usr/lib/jvm/java-7-openjdk/jre ] ; then
 	if [ -f /usr/share/icedtea-web/netx.jar ] ; then
 		JAVAWS=/usr/share/icedtea-web/netx.jar
@@ -8,8 +7,16 @@ if [ -d /usr/lib/jvm/java-7-openjdk/jre ] ; then
 		echo "Err: icedtea-web-java7 should install"
 		exit 1
 	fi
+elif [ -d /opt/sun-java6 ] ; then
+	. /opt/sun-java6/envsetup.sh
+	JAVAWS="$JAVA_HOME"/jre/lib/javaws.jar
+	if [ ! -r $JAVAWS ] ; then
+		echo "Err: missing JAVAWS ($JAVAWS)"
+		exit 1
+	fi
 else
-	JAVAWS="$JAVA_HOME"/lib/javaws.jar
+	echo "Err: Please install openjdk or sun-java6"
+	exit 1
 fi
 
 $JAVA_HOME/bin/java -Xmx1024m -classpath "$PROGRAM_DIR"/lib/SweetHome3D.jar:\
