updated on Sat Mar 14 00:00:25 UTC 2015

diff --git a/minimetro/PKGBUILD b/minimetro/PKGBUILD
--- a/minimetro/PKGBUILD
+++ b/minimetro/PKGBUILD
@@ -1,50 +1,53 @@
-# Maintainer: Samuel Littley <samuel.littley@toastwaffle.com>
+# Maintainer: XZS <d dot f dot fischer at web dot de>
+# Contributor: Samuel Littley <samuel.littley@toastwaffle.com>
 # Contributor: William Giokas <1007380@gmail.com>
 
 pkgname=minimetro
 _pkgname=MiniMetro
-pkgver=alpha13b
-_build=alpha13
-pkgrel=1
+pkgver=beta17
+pkgrel=2
 pkgdesc='minimalistic subway layout game'
-url='http://dinopoloclub.com/minimetro/'
+url="http://dinopoloclub.com/${pkgname}/"
 license=('custom:None')
 arch=('i686' 'x86_64')
-depends=('libgl' 'libx11' 'glu')
-source=("http://static.dinopoloclub.com/minimetro/builds/${_build}/MiniMetro-${pkgver}-linux.tar.gz")
-md5sums=('b50106cf38b39b8df1bca957d6604a9c')
+depends=('libgl' 'libx11' 'glu' 'desktop-file-utils' 'gtk-update-icon-cache')
+makedepends=('imagemagick')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
+install=desktop.install
+source=("hib://${_pkgname}-${pkgver}-linux.tar.gz"
+        "minimetro.desktop"
+        "minimetro.svg")
+md5sums=('3631d83c72b9bef5f87cd5f555803a0a'
+         '0fe19f989f9606a825b67b9b379c9d6c'
+         '6e7915bc03ced67cffb81174f260a742')
 
-case $CARCH in
-  i686)
-    _notarch=x86_64
-    _arch=x86
-    ;;
-  x86_64)
-    _notarch=x86
-    _arch=x86_64
-    ;;
-esac
+prepare() {
+  case $CARCH in
+    i686) _notarch=x86_64 ;;
+    x86_64) _notarch=x86 ;;
+  esac
+  find -name "*$_notarch" -exec rm -r {} +
+}
 
 package() {
-  install -dm 755 "$pkgdir"/usr/bin
-  install -dm 755 "$pkgdir"/opt/minimetro
-  cp -r "$srcdir"/MiniMetro-${pkgver}-linux_Data/ \
-        "$srcdir"/MiniMetro-${pkgver}-linux.$_arch \
-        "$pkgdir"/opt/minimetro/
+  # First, install the game itself.
+  destdir="$pkgdir/opt/$pkgname"
+  install -dm 755 "$destdir"
+  cp -r ${_pkgname}{_,.}* "$destdir"
 
   # Make the log file writable by the 'games' group. This is needed to run.
-  touch "$pkgdir"/opt/minimetro/MiniMetro-${pkgver}-linux_Data/log.txt
-  chmod 664 "$pkgdir"/opt/minimetro/MiniMetro-${pkgver}-linux_Data/log.txt
-  chown :games "$pkgdir"/opt/minimetro/MiniMetro-${pkgver}-linux_Data/log.txt
+  log="$destdir"/${_pkgname}_Data/log.txt
+  touch "$log"
+  chmod 664 "$log"
+  chown :games "$log"
 
-  find "$pkgdir"/opt/minimetro \
-    -name "$_notarch" \
-    -type d \
-    -exec rm -r {} +
+  # Now, care for supplementary files.
+  install -dm 755 "$pkgdir"/usr/{bin,share/{applications,icons/hicolor/{scalable,256x256}/apps}} "$destdir"
 
-  cat << EOF > "$pkgdir"/usr/bin/minimetro
-#!/opt/minimetro/MiniMetro-${pkgver}-linux.$_arch
-EOF
+  echo "#!/opt/$pkgname/${_pkgname}.$CARCH" > "$pkgdir"/usr/bin/${pkgname}
+  chmod +x "$pkgdir"/usr/bin/$pkgname
 
-  chmod +x "$pkgdir"/usr/bin/minimetro
+  cp ${pkgname}.desktop "$pkgdir"/usr/share/applications
+  cp ${pkgname}.svg "$pkgdir"/usr/share/icons/hicolor/scalable/apps
+  convert ${pkgname}.svg "$pkgdir"/usr/share/icons/hicolor/256x256/apps/minimetro.png
 }
