updated on Wed Jul 27 18:01:01 UTC 2011

diff --git a/cogs/PKGBUILD b/cogs/PKGBUILD
--- a/cogs/PKGBUILD
+++ b/cogs/PKGBUILD
@@ -1,27 +1,43 @@
 # Maintainer: Gadget3000 <gadget3000 at msn dot com>
 
 pkgname=cogs
-pkgver=1
+pkgver=2
 pkgrel=1
 pkgdesc="A game in which you build machines from sliding tiles"
 arch=('i686' 'x86_64')
 url="http://www.cogsgame.com/"
 license=('unknown')
+depends=('gcc-libs' 'sdl<1.3' 'openal')
 makedepends=('unzip')
-#source=(cogs-linux-bin)
-#noextract=()
-md5sums=('fe4f8b978418bb3ba9d40357f1fd33ea') #generate with 'makepkg -g'
+source=(cogs.desktop)
+md5sums=('425530cd26af362c2e98d4bf720b4372') #generate with 'makepkg -g'
+
+_archive="cogs-linux-bin"
+_archive_md5="fe4f8b978418bb3ba9d40357f1fd33ea"
 
 build() {
   install -Dd ${srcdir}/extractedInstaller
   cd $srcdir
+  
+  if [ ! -f ${_archive} ]; then
   echo Please place cogs-linux-bin into $(pwd)
   echo Press Enter to continue
   read -a _unused
+  fi
+
+  if ! echo "${_archive_md5}  ${_archive}" | md5sum -c --quiet; then
+    echo "Invalid checksum for ${_archive}"
+    return 1
+  fi
+
   install -Dd ${pkgdir}/opt/
   unzip -qqo cogs-linux-bin -x guis/* meta/* scripts/* -d ${srcdir}/extractedInstaller/ && msg Finished Extracting
   install -Dd ${pkgdir}/opt/cogs
   mv ${srcdir}/extractedInstaller/data/* ${pkgdir}/opt/cogs/
   install -Dd ${pkgdir}/usr/bin
-  ln -s /opt/cogs/Cogs ${pkgdir}/usr/bin/Cogs
+  ln -s /opt/cogs/Cogs ${pkgdir}/usr/bin/cogs
+
+  # install menu entry
+  install -Dd ${pkgdir}/usr/share/applications
+  install -m 644 'cogs.desktop' "${pkgdir}/usr/share/applications/cogs.desktop"
 }
