updated on Sun Sep  1 16:00:13 UTC 2013

diff --git a/vdr/vdr.install b/vdr/vdr.install
--- a/vdr/vdr.install
+++ b/vdr/vdr.install
@@ -1,19 +1,19 @@
 # vdr.install
 
 # VDR environment
-CACHEDIR="/var/cache/vdr"
-CONFDIR="/var/lib/vdr"
-VIDEODIR="/srv/vdr/video"
-VDR_USER="vdr"
+_vdrCACHEDIR="/var/cache/vdr"
+_vdrCONFDIR="/var/lib/vdr"
+_vdrVIDEODIR="/srv/vdr/video"
+_vdrUSER="vdr"
 
 ## arg 1:  the new package version
 post_install() {
   echo ""
   echo "*****************************************************************************"
-  echo "  Configuration files are installed in ${CONFDIR} and should be owned by"
-  echo '  "'${VDR_USER}':'${VDR_USER}'"'
+  echo "  Configuration files are installed in ${_vdrCONFDIR} and should be owned by"
+  echo '  "'${_vdrUSER}':'${_vdrUSER}'"'
   echo ""
-  echo "  NOTE: A vdr.service file has been installed but the template runvdr"
+  echo "  NOTE: A systemd service file has been installed but the template runvdr"
   echo "  script that comes with the vdr source has not been installed and is"
   echo "  in /usr/share/doc/vdr. To make a working installation either copy the"
   echo "  template to /usr/bin, edit as needed and make it executable or use"
@@ -21,26 +21,35 @@ post_install() {
   echo "  e.g. runvdr-extreme."
   echo "*****************************************************************************"
   echo ""
-  if ! getent passwd ${VDR_USER} >/dev/null; then
-    echo -n 'Creating VDR user "'${VDR_USER}'"...'
-    usr/sbin/groupadd -g 199 ${VDR_USER} >/dev/null
-    /usr/sbin/useradd -r -d ${VIDEODIR} -g ${VDR_USER} -G video -s /bin/false -c "Video Disk Recorder" ${VDR_USER} &>/dev/null
-    passwd -l ${VDR_USER} &>/dev/null
+  if ! getent passwd ${_vdrUSER} >/dev/null; then
+    echo -n 'Creating VDR user "'${_vdrUSER}'"...'
+    usr/sbin/groupadd -g 199 ${_vdrUSER} >/dev/null
+    /usr/sbin/useradd -r -d ${_vdrVIDEODIR} -g ${_vdrUSER} -G video -s /bin/false -c "Video Disk Recorder" ${_vdrUSER} &>/dev/null
+    passwd -l ${_vdrUSER} &>/dev/null
     echo "done."
   fi
-  chown -R ${VDR_USER}:${VDR_USER} ${CONFDIR}
-  chown -R ${VDR_USER}:${VDR_USER} ${VIDEODIR}
-  chown -R ${VDR_USER}:${VDR_USER} ${CACHEDIR}
+  chown -R ${_vdrUSER}:${_vdrUSER} ${_vdrCACHEDIR}
+  chown -R ${_vdrUSER}:${_vdrUSER} ${_vdrCONFDIR}
+  chown -R ${_vdrUSER}:${_vdrUSER} ${_vdrVIDEODIR}
 }
 
 ## arg 1:  the new package version
 ## arg 2:  the old package version
 post_upgrade() {
-  post_install $1
+  if getent passwd ${_vdrUSER} >/dev/null; then
+    chown -R ${_vdrUSER}:${_vdrUSER} ${_vdrCACHEDIR}
+    chown -R ${_vdrUSER}:${_vdrUSER} ${_vdrCONFDIR}
+    chown -R ${_vdrUSER}:${_vdrUSER} ${_vdrVIDEODIR}
+  else
+    echo "*****************************************************************************"
+    echo '  VDR user "'${_vdrUSER}'" not found. Ownership of the configuration files'
+    echo "  has not been changed."
+    echo "*****************************************************************************"
+  fi
 }
 
 # arg 1:  the old package version
 post_remove() {
-  echo 'VDR user "'${VDR_USER}'" will not be deleted.'
+  echo 'VDR user "'${_vdrUSER}'" will not be deleted.'
 }
 
