updated on Mon Jan 30 20:06:00 UTC 2012

diff --git a/charles/charles-arch.patch b/charles/charles-arch.patch
--- a/charles/charles-arch.patch
+++ b/charles/charles-arch.patch
@@ -1,8 +1,19 @@
---- charles/bin/charles.sh.orig	2011-08-01 16:00:18.743550224 +0200
-+++ charles/bin/charles.sh	2011-08-01 16:00:48.646883081 +0200
-@@ -1,4 +1,4 @@
- #!/bin/sh
+--- charles/bin/charles.orig	2011-11-14 19:54:27.000000000 +0100
++++ charles/bin/charles	2011-11-30 11:57:46.635362807 +0100
+@@ -6,15 +6,7 @@
  
--java -Xmx256M -Dcharles.config="~/.charles.config" -jar `dirname $0`/../lib/charles.jar &
-+java -Xmx256M -Dcharles.config="~/.charles.config" -jar /usr/share/java/charles/charles.jar &
+ # Find Charles lib directory
+ if [ -z "$CHARLES_LIB"]; then
+-	CHARLES_LIB=`dirname $0`/../lib
+-	if [ ! -f "$CHARLES_LIB/charles.jar" ]; then
+-		CHARLES_LIB="/usr/lib/charles-proxy"
+-	fi
+-fi
+-
+-if [ ! -f "$CHARLES_LIB/charles.jar" ]; then
+-	echo >&2 "Charles lib directory not found. Looking in $CHARLES_LIB."
+-	exit 1
++	CHARLES_LIB="/usr/share/java/charles"
+ fi
  
+ # Find Java binary
