updated on Fri Sep 28 16:00:12 UTC 2012

diff --git a/bittriprunner/PKGBUILD b/bittriprunner/PKGBUILD
--- a/bittriprunner/PKGBUILD
+++ b/bittriprunner/PKGBUILD
@@ -1,69 +1,87 @@
-# Maintainer: Yann Kaiser <kaiser.yann@gmail.com>
+# Maintainer: Sam S. <smls75@gmail.com>
+# Original submitter: Yann Kaiser <kaiser.yann@gmail.com>
+
 pkgname=bittriprunner
-pkgver=1.0
+pkgver=1.0_20120927
+_hibver=1.0-4
+_buildver=1348702546
 pkgrel=1
-pkgdesc="Rhythm-based action platformer"
-arch=('i686' 'x86_64')
+pkgdesc="BIT.TRIP RUNNER, a rhythm-based action platformer"
 url="http://bittripgame.com/bittrip-runner.html"
+arch=('i686' 'x86_64')
 license=('custom')
 depends=('sdl' 'libgl' 'openal' 'libvorbis' 'libogg' 'zlib')
-makedepends=()
-source=('bittriprunner.desktop' 'bittriprunner.sh')
-md5sums=('a3b58d3afad9b24f29c1e49e0c649a36'
-         '3f4cf7688a32a688fb1b9ce9fb4fc8f8')
+source=('bittriprunner.desktop')
+md5sums=('3873d051fd4e1876d17e9fdb7a6fe519')
 
-_archive_name="bit.trip.runner"
-if test "${CARCH}" == "x86_64"; then
-  _archive_arch="amd64"
-  _archive_md5="ba315db4752f1397d0577b63aea7cb34"
-else
-  _archive_arch="i386"
-  _archive_md5="62bb8c0b411a0edba9f5d6d7ddc50962"
-fi
+case $CARCH in
+  i686)
+    _archive="bit.trip.runner-linux-${_hibver}_i386-${_buildver}.tar.gz"
+    _archivemd5='900019b5994e1b8b2e08fcf07d9c1c08' ;;
+  x86_64)
+    _archive="bit.trip.runner_${_hibver}_amd64-${_buildver}.tar.gz"
+    _archivemd5='026712ac29972467f0b167a3eeaa3933' ;;
+esac
 
-_archive="${_archive_name}_${_archive_arch}.tar.gz"
+_archivedir="bit.trip.runner-1.0";
+_installname="bit.trip.runner"
 
 build() {
-  cd ${srcdir}
+  # Get game archive
+  _get_humblebundle_source "${_archive}" || {
+    error "Unable to find the game archive. Please download it from your Humble
+           Bundle page, and place it into one of the above locations."
+    exit 1; }
 
-  if [ ! -f ${_btrarchivelocation}${_archive} ]; then
-	  if [ ! -f ${_archive} ] && [ -n "${_humblebundle4key}" ]; then
-		rm -f ${_archive}* index.html\?key\=${_humblebundle4key}*
-		wget http://www.humblebundle.com/?key=${_humblebundle4key}
-		wget $(cat index.html\?key\=${_humblebundle4key} | grep "${_archive}" | cut -d "'" -f 10)
-		mv ${_archive}* ${_archive}
-	  elif [ -z "${_humblebundle4key}" ]; then
-		echo You can automate the download of the archive using the _humblebundle4key bash variable.
-		echo Just add \'export _humblebundle4key\=\<Your key here\>\' to \.bashrc
-		echo
-		echo Otherwise please just place ${_archive} into $(pwd)/
-		echo Press Enter to continue
-		read -a _unused
-	  fi
-  fi
+  msg "Starting setup..."
+  cd $srcdir
 
-  if [ ! -f ${_btrarchivelocation}${_archive} ]; then
-    echo "${_btrarchivelocation}${_archive} not found!"
-    return 1
-  fi
+  # Unpack game archive
+  [[ -d ${_archivedir} ]] && rm -r "${_archivedir}"
+  tar -xf "${_archive}"
 
-  if ! echo "${_archive_md5}  ${_btrarchivelocation}${_archive}" | md5sum -c --quiet; then
-    echo "Invalid checksum for ${_btrarchivelocation}${_archive}"
-    return 1
-  fi
+  # Install game files
+  mkdir -p "${pkgdir}/opt/${_installname}"
+  cp -r "${_archivedir}/bit.trip.runner"/* "${pkgdir}/opt/${_installname}/"
 
-  bsdtar -xf ${_btrarchivelocation}${_archive}
+  # Install launcher script
+  echo -e "#!/bin/sh\ncd /opt/${_installname} && ./bit.trip.runner" \
+        > "launcher.sh"
+  install -Dm755 "launcher.sh" "${pkgdir}/usr/bin/${_installname}"
 
-  mkdir -p ${pkgdir}/opt/ ${pkgdir}/usr/bin/ \
-    ${pkgdir}/usr/share/applications
-  cp -r ${srcdir}/${_archive_name}-${pkgver}/${_archive_name}/ ${pkgdir}/opt/
-  cp ${srcdir}/${pkgname}.desktop ${pkgdir}/usr/share/applications/
-  cp ${srcdir}/${pkgname}.sh ${pkgdir}/opt/${_archive_name}/
-  ln -s /opt/${_archive_name}/${pkgname}.sh \
-    ${pkgdir}/usr/bin/${pkgname}
-  chmod a+rx ${pkgdir}/opt/${_archive_name}/${pkgname}.sh
-  chmod a+r ${pkgdir}/usr/share/applications/${pkgname}.desktop
+  # Install icon
+  install -Dm644 "${_archivedir}/bit.trip.runner/RUNNER.png" \
+                 "${pkgdir}/usr/share/pixmaps/${_installname}.png"
+
+  # Install desktop entry
+  install -Dm644 "${pkgname}.desktop" \
+                 "${pkgdir}/usr/share/applications/${_installname}.desktop"
+
+  # Install documentation
+  mkdir -p "${pkgdir}/usr/share/doc/${_installname}"
+  cp -r "${_archivedir}/README"* "${pkgdir}/usr/share/doc/${_installname}"
 }
 
-# vim: et ts=2 sw=2 sts=2
 
+###### HELPER FUNCTIONS ######
+
+# Locate a game archive from one of the Humble Bundles, and symlink it into $srcdir
+_get_humblebundle_source() {
+  _get_local_source "$1" || return 1;
+  # TODO: Implement automatic downloading from Humble Bundle site
+}
+
+# Locate a file or folder provided by the user, and symlink it into $srcdir
+_get_local_source() {
+  msg "Looking for '$1'..."; _found=0
+  declare -A _search=(['build dir']="$startdir"
+                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
+  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
+    if [ -z "$_dir" ]; then _dir="<undefined>"; fi
+    echo -n "    - in $_key ['$_dir'] ... ";
+    if [ -e "$_dir/$1" ]; then _found=1
+      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
+    echo "NOT FOUND"
+  done
+  if [[ $_found == 0 ]]; then return 1; fi
+}
