updated on Sat Jun  8 20:00:58 UTC 2013

diff --git a/bittriprunner/PKGBUILD b/bittriprunner/PKGBUILD
--- a/bittriprunner/PKGBUILD
+++ b/bittriprunner/PKGBUILD
@@ -10,9 +10,8 @@ pkgdesc="BIT.TRIP RUNNER, a rhythm-based action platformer"
 url="http://bittripgame.com/bittrip-runner.html"
 arch=('i686' 'x86_64')
 license=('custom')
-depends=('sdl' 'libgl' 'openal' 'libvorbis' 'libogg' 'zlib')
-source=('bittriprunner.desktop')
-md5sums=('4b909d84b34d6d7076f9712f8e122ece')
+depends=('sdl' 'libgl' 'openal' 'libvorbis')
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 case $CARCH in
   i686)
@@ -22,22 +21,14 @@ case $CARCH in
     _archive="bit.trip.runner_${_hibver}_amd64-${_buildver}.tar.gz"
     _archive_md5='026712ac29972467f0b167a3eeaa3933' ;;
 esac
+source=("hib://$_archive" 'bittriprunner.desktop')
+md5sums=("$_archive_md5" '4b909d84b34d6d7076f9712f8e122ece')
+
 _archive_subdir="bit.trip.runner-1.0";
 _installname="bit.trip.runner"
 
 build() {
-  # Get game archive
-  _get_local_source "${_archive}" --md5 "${_archive_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
-
-  msg "Starting setup..."
   cd $srcdir
-
-  # Unpack game archive
-  [[ -d ${_archive_subdir} ]] && rm -r "${_archive_subdir}"
-  tar -xf "${_archive}"
 
   # Install game files
   mkdir -p "${pkgdir}/opt/${_installname}"
@@ -59,24 +50,4 @@ build() {
   # Install documentation
   mkdir -p "${pkgdir}/usr/share/doc/${_installname}"
   cp -r "${_archive_subdir}/README"* "${pkgdir}/usr/share/doc/${_installname}"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
diff --git a/dustforce-hib/PKGBUILD b/dustforce-hib/PKGBUILD
--- a/dustforce-hib/PKGBUILD
+++ b/dustforce-hib/PKGBUILD
@@ -8,69 +8,47 @@ pkgdesc='A fast-paced 2D platformer game (Humble Bundle version)'
 url='http://dustforce.com/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
-makedepends=('coreutils')
-depends=('mesa' 'sdl' 'libxau' 'libxdamage' 'libxdmcp' 'libxinerama' 'freealut'
-         'fontconfig' 'libidn' 'libvorbis' 'zlib')
-source=('dustforce-hib.desktop')
-md5sums=('fa688d289f57cd54eabde9e7ef354407')
+depends=('mesa' 'libgl' 'sdl' 'libxdamage' 'freealut' 'libidn' 'libvorbis'
+         'libxft' 'xdg-utils')
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 _installer="dustforce-linux-${_hibver}.sh"
-_installer_md5='afaca0c6241904becb66a29821f4dce4'
+source=("hib://${_installer}"
+        'dustforce-hib.desktop')
+md5sums=('afaca0c6241904becb66a29821f4dce4'
+         'fa688d289f57cd54eabde9e7ef354407')
 
 package() {
   cd $srcdir
+  _installdir=/opt/Dustforce; _target=$pkgdir/$_installdir
+  [ $CARCH == "i686" ] && _arch='x86' || _arch='x86_64'
 
-  # Get installer
-  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
+  # Extract installer
+  mkdir -p $_target
+  while read line; do echo -n '.'; done < <(  # show progress as dots
+    sh $_installer --tar xvf
+    lzma -d < instarchive_linux_$_arch | tar xvf - -C $_target
+    lzma -d < instarchive_all | tar xvf - -C $_target
+    lzma -d < subarch | tar xvf -
+    lzma -d < deps/cURL/cURL_files_linux_$_arch | tar xvf - -C ${_target}
+  ); echo
 
-  # Execute installer
-  msg "Starting setup..."
-  [[ -d "./temp" ]] && rm -r "./temp"
-  sh "./${_installer}" --unattended --no-register --packager pacman \
-                       --keep --overwrite \
-                       --target  "${srcdir}/temp" \
-                       --bindir  "${srcdir}/bin" \
-                       --datadir "${pkgdir}/opt"
-
-  # Remove bundled libraries & helper binaries (use system packages instead)
-  rm -rf "${pkgdir}/opt/Dustforce/lib64/lib"{SDL-1.2.so.0}
-  rm -rf "${pkgdir}/opt/Dustforce/"{xdg-open,xdg-utils}
+  # Fix permissions
+  find "${pkgdir}" -type f -exec chmod 644 "{}" +
+  chown root:root -R "${pkgdir}"
 
   # Install desktop entry
-  install -Dm644 "${pkgname}.desktop" \
-                 "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+  install -Dm644 "$pkgname.desktop" \
+                 "$pkgdir/usr/share/applications/$pkgname.desktop"
 
   # Install icon
-  install -Dm644 "${pkgdir}/opt/Dustforce/Dustforce.png" \
-                 "${pkgdir}/usr/share/pixmaps/dustforce.png"
+  install -Dm644 "$_target/Dustforce.png" \
+                 "$pkgdir/usr/share/pixmaps/dustforce.png"
 
   # Install launcher symlink
   case $CARCH in i686) _arch=x86 ;; x86_64) _arch=x86_64;; esac
-  chmod 755 "${pkgdir}/opt/Dustforce/Dustforce.bin.$_arch"
-  install -d "${pkgdir}/usr/bin"
-  ln -s "/opt/Dustforce/Dustforce.bin.${_arch}" "${pkgdir}/usr/bin/dustforce"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
+  chmod 755 "$_target/Dustforce.bin.$_arch"
+  install -d "$pkgdir/usr/bin"
+  ln -s "$_installdir/Dustforce.bin.$_arch" "$pkgdir/usr/bin/dustforce"
 }
diff --git a/shatter-hib/PKGBUILD b/shatter-hib/PKGBUILD
--- a/shatter-hib/PKGBUILD
+++ b/shatter-hib/PKGBUILD
@@ -16,79 +16,57 @@ if [ $CARCH == i686 ]; then
   optdepends=('alsa-plugins: PulseAudio support'
               'libpulse: PulseAudio support')
 else
-  depends=('lib32-glibc' 'lib32-gcc-libs' 'lib32-libgl' 'lib32-libidn'
-           'lib32-zlib' 'lib32-libx11' 'lib32-libxfixes' 'lib32-libxdamage'
-           'lib32-libxext' 'lib32-libxinerama' 'lib32-libxrender'
-           'lib32-libxau' 'lib32-libxft' 'lib32-libxxf86vm' 'lib32-libxdmcp'
-           'lib32-fontconfig' 'lib32-sdl' 'lib32-alsa-lib' 'xdg-utils'
-           'lib32-nvidia-cg-toolkit' 'lib32-libtxc_dxtn')
+  depends=('lib32-libgl' 'lib32-libidn' 'lib32-libxinerama' 'lib32-libxft'
+           'lib32-sdl' 'lib32-alsa-lib' 'xdg-utils' 'lib32-nvidia-cg-toolkit'
+           'lib32-libtxc_dxtn')
   optdepends=('lib32-alsa-plugins: PulseAudio support'
               'lib32-libpulse: PulseAudio support')
 fi
-source=('shatter-hib.desktop')
-md5sums=('52e9ea073d699ae979167fd4cb4af585')
 install='shatter-hib.install'
 options=('!upx')
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 _installer="shatter-linux-${_hibver}.sh"
-_installer_md5="6e9ba377b121126e2b6fe3e3dbbf1dc2"
+source=("hib://${_installer}"
+        'shatter-hib.desktop')
+md5sums=('6e9ba377b121126e2b6fe3e3dbbf1dc2'
+         '52e9ea073d699ae979167fd4cb4af585')
 
 package() {
   cd $srcdir
+  _installdir=/opt/Shatter; _target=$pkgdir/$_installdir
 
-  # Get installer
-  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
-
-  # Execute installer
-  msg "Starting setup..."
-  [[ -d "./temp" ]] && rm -r "./temp"
-  sh "./${_installer}" --unattended --no-register --packager pacman \
-                       --keep --overwrite \
-                       --target  "${srcdir}/temp" \
-                       --bindir  "${srcdir}/bin" \
-                       --datadir "${pkgdir}/opt"
+  # Extract installer
+  mkdir -p $_target
+  while read line; do echo -n '.'; done < <(  # show progress as dots
+    sh "$_installer" --tar xvf
+    lzma -d < instarchive_linux_all | tar xvf - -C $_target
+    lzma -d < instarchive_all | tar xvf - -C $_target
+    lzma -d < subarch | tar xvf -
+#     for i in deps/{CEGUI,Ogre,SDL2,fmod,pcre}/*${_arch}; do
+#       lzma -d < $i | tar xvf - -C $_target
+#     done
+  ); echo
 
   # Remove bundled libraries & helper binaries (use system packages instead)
   rm -rf "${pkgdir}/opt/Shatter/lib/lib"{Cg.so,CgGL.so,SDL-1.2.so.0}
   rm -rf "${pkgdir}/opt/Shatter/"{xdg-open,xdg-utils}
 
   # Fix permissions
-  chmod 644 "${pkgdir}/opt/Shatter/lib/"*
+  find $pkgdir -type f -exec chmod 644 "{}" +
+  chown root:root -R $pkgdir
 
-  # Install desktop entry
-  install -Dm644 "${pkgname}.desktop" \
-                 "${pkgdir}/usr/share/applications/${pkgname}.desktop"
+  # Install desktop entry & icon
+  install -Dm644 $pkgname.desktop $pkgdir/usr/share/applications/$pkgname.desktop
+  install -Dm644 $_target/Shatter.png $pkgdir/usr/share/pixmaps/shatter.png
 
-  # Install icon
-  install -Dm644 "${pkgdir}/opt/Shatter/Shatter.png" \
-                 "${pkgdir}/usr/share/pixmaps/shatter.png"
+  # Install launcher symlink
+  chmod 755 $_target/*.bin.x86
+  install -d $pkgdir/usr/bin
+  ln -s $_installdir/Shatter.bin.x86 $pkgdir/usr/bin/shatter
+  ln -s $_installdir/SettingsEditor.bin.x86 $pkgdir/usr/bin/shatter-settings
 
-  # Install launcher script
-  install -d "${pkgdir}/usr/bin"
-  ln -s "/opt/Shatter/Shatter.bin.x86" "${pkgdir}/usr/bin/shatter"
-  ln -s "/opt/Shatter/SettingsEditor.bin.x86" "${pkgdir}/usr/bin/shatter-settings"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
+  # Install license file
+  install -Dm644 config/license $pkgdir/usr/share/licenses/$pkgname/license
 }
diff --git a/torchlight-hib/PKGBUILD b/torchlight-hib/PKGBUILD
--- a/torchlight-hib/PKGBUILD
+++ b/torchlight-hib/PKGBUILD
@@ -8,30 +8,24 @@ pkgdesc='A hack and slash action role-playing game (Humble Bundle version)'
 url='http://www.torchlightgame.com/'
 arch=('i686' 'x86_64')
 license=('custom:commercial')
-depends=('libgl' 'mesa' 'freeglut' 'libxrandr' 'expat' 'libxaw' 'libxft'
-         'libxinerama' 'freeimage' 'util-linux' 'zziplib' 'pcre' 'libtxc_dxtn')
-source=('torchlight-hib.desktop')
-md5sums=('36903fc0f19910870440b68ac4cd22a4')
+depends=('mesa' 'glu' 'freeglut' 'libxaw' 'libxft' 'freeimage' 'util-linux'
+         'zziplib' 'pcre' 'libtxc_dxtn')
 options=('!strip' '!upx')
 PKGEXT='.pkg.tar'
+DLAGENTS+=('hib::/usr/bin/echo "Could not find %u. Manually download it to \"$(pwd)\", or set up a hib:// DLAGENT in /etc/makepkg.conf."; exit 1')
 
 _installer="Torchlight-${_hibver}.sh"
-_installer_md5='a747a31547202d7dc85c8a6cd9b47c9f'
-
+source=("hib://${_installer}"
+        'torchlight-hib.desktop')
+md5sums=('a747a31547202d7dc85c8a6cd9b47c9f'
+         '36903fc0f19910870440b68ac4cd22a4')
 
 package() {
   cd $srcdir
   _target="/opt/Torchlight"
   case $CARCH in i686) _arch=x86;; x86_64) _arch=x86_64;; esac
 
-  # Get installer
-  _get_local_source "${_installer}" --md5 "${_installer_md5}" || {
-    error "Unable to find the game archive. Please download it from your Humble
-           Bundle page, and place it into one of the above locations."
-    exit 1; }
-  
   # Extract installer
-  msg "Starting setup..."
   [[ -d archive ]] && rm -r archive; mkdir archive; mkdir -p "${pkgdir}${_target}"
   while read line; do echo -n '.'; done < <(  # show progress as dots
     sh "${_installer}" --tar xvf -C archive/
@@ -62,24 +56,4 @@ package() {
 
   # Install license file
   install -Dm644 "archive/config/license" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
-}
-
-
-###### HELPER FUNCTIONS ######
-
-# Locates a file or folder provided by the user, and symlinks it into $srcdir
-_get_local_source() {
-  msg "Looking for '$1'..."; rm -f "$srcdir/$1"
-  declare -A _search=(['build dir']="$startdir"
-                      ['$LOCAL_PACKAGE_SOURCES']="$LOCAL_PACKAGE_SOURCES")
-  for _key in "${!_search[@]}"; do local _dir="${_search["$_key"]}"
-    echo -n "    - in $_key [${_dir:-<undefined>}] ... ";
-    if [[ -z "$_dir" || ! -e "$_dir/$1" ]]; then
-      echo "NOT FOUND"
-    elif [[ -n $2 && "$(${2#--}sum "$_dir/$1"|awk '{print $1}')" != $3 ]]; then
-      echo "CHECKSUM FAILED";
-    else
-      echo "FOUND"; ln -sfT "$(readlink -f "$_dir/$1")" "$srcdir/$1"; break; fi
-  done
-  if [ ! -e "$srcdir/$1" ]; then return 1; fi
 }
