updated on Fri Apr 27 19:13:40 UTC 2012

diff --git a/jdk/PKGBUILD b/jdk/PKGBUILD
--- a/jdk/PKGBUILD
+++ b/jdk/PKGBUILD
@@ -20,6 +20,7 @@ backup=('etc/conf.d/derby-network-server'
         'etc/profile.d/jdk.sh')
 install=jdk.install
 _arch=i386 && _arch2=i586; [ "$CARCH" == 'x86_64' ] && _arch=amd64 && _arch2=x64
+_jdk=jdk-$_pkg-linux-$_arch2.tar.gz
 # source=("http://download.oracle.com/otn-pub/java/jdk/$_pkg-$_build/jdk-$_pkg-linux-i586.tar.gz"
 # source=("http://uni-smr.ac.ru/archive/dev/java/SDKs/oracle/j2se/7/jdk-$_pkg-linux-i586.tar.gz"
 source=('java-monitoring-and-management-console.desktop'
@@ -41,30 +42,37 @@ md5sums=('da10de5e6507c392fc9871076ef53ec6'  # java-monitoring-and-management-co
 # [ "$CARCH" == 'x86_64' ] && source[0]="http://uni-smr.ac.ru/archive/dev/java/SDKs/oracle/j2se/7/jdk-$_pkg-linux-x64.tar.gz" && md5sums[0]='969927251b558ffbc09ede1e89200d40'
 
 package() {
-  msg2 "Due to a change in how Oracle handles the Java SE License Agreement
+  # Check, if the package's not in $srcdir
+  if [ ! -f $_jdk ]; then
+    # Check, if not in $startdir
+    if [ ! -f ../$_jdk ]; then
+      msg2 "Due to a change in how Oracle handles the Java SE License Agreement
      you are required to:
      1) accept the license and download the tarball (.tar.gz) yourself:
         http://www.oracle.com/technetwork/java/javase/downloads/jdk-7u4-downloads-1591156.html
      2) move it to \$startdir/ ($startdir/)"
 
-  msg2 "If saved in ~/Desktop/, ~/Downloads/ or /tmp/, it will be auto-moved for you"
+      msg2 "If saved in ~/Desktop/, ~/Downloads/ or /tmp/, it will be auto-moved for you"
 
-  msg2 "Press any key to continue"
-  read -n1
+      msg2 "Press any key to continue"
+      read -n1 -s
 
-  for i in ~/{Desktop,Downloads} /tmp; do
-    if [ -f $i/jdk-$_pkg-linux-$_arch2.tar.gz ]; then
-      msg2 "Moving jdk-$_pkg-linux-$_arch2.tar.gz from $i/ to $startdir/"
-      mv $i/jdk-$_pkg-linux-$_arch2.tar.gz ../
-
-      msg2 "Symlinking to \$srcdir/"
-      ln -s ../jdk-$_pkg-linux-$_arch2.tar.gz .
+      # Try to move from said locations
+      for i in /tmp ~/{Desktop,Downloads}; do
+      if [ -f $i/$_jdk ]; then
+        msg2 "Moving $_jdk from $i/ to $startdir/"
+        mv $i/$_jdk ../
+        break
+      fi
+      done
+      # If still not there, exit with status 1 (error)
+      if [ ! -f ../$_jdk  ]; then
+        error "Tarball not found in the right location. Exiting.."
+        exit 1
+      fi
     fi
-  done
-
-  if [ ! -f ../jdk-$_pkg-linux-$_arch2.tar.gz ]; then
-    error "Tarball not found in the right location. Exiting.."
-    exit 1
+    msg2 "Symlinking to \$srcdir/"
+    ln -sf ../$_jdk .
   fi
 
   msg2 "Extracting sources..."
diff --git a/jre/PKGBUILD b/jre/PKGBUILD
--- a/jre/PKGBUILD
+++ b/jre/PKGBUILD
@@ -1,5 +1,5 @@
 # Maintainer: Det
-# Contributors: Charles Ghislain, Guillaume ALAUX, Daniel J Griffiths, Jason Chu, Geoffroy Carrier, Army, kfgz, Thomas Dziedzic, Dan Serban
+# Contributors: Charles Ghislain, Guillaume ALAUX, Daniel J Griffiths, Jason Chu, Geoffroy Carrier, Army, kfgz, Thomas Dziedzic, Dan Serban, jjacky
 
 pkgname=jre
 _major=7
@@ -21,6 +21,7 @@ backup=(etc/profile.d/jre.sh
         etc/profile.d/jre.csh)
 install=jre.install
 _arch=i386 && _arch2=i586; [ "$CARCH" == 'x86_64' ] && _arch=amd64 && _arch2=x64
+_jre=jre-$_pkg-linux-$_arch2.tar.gz
 # source=("http://download.oracle.com/otn-pub/java/jdk/$_pkg-$_build/jre-$_pkg-linux-i586.tar.gz"
 # source=("http://uni-smr.ac.ru/archive/dev/java/JRE/oracle/7/jre-$_pkg-linux-i586.tar.gz"
 source=('java-policy-settings.desktop'
@@ -36,34 +37,41 @@ md5sums=('f4e25ef1ccef8d36ff2433c3987a64fe'  # java-policy-settings.desktop
 # [ "$CARCH" == 'x86_64' ] && source[0]="http://uni-smr.ac.ru/archive/dev/java/JRE/oracle/7/jre-$_pkg-linux-x64.tar.gz" && md5sums[0]='3d3e206cea84129f1daa8e62bf656a28'
 
 package() {
-  msg2 "Due to a change in how Oracle handles the Java SE License Agreement
+  # Check, if the package's not in $srcdir
+  if [ ! -f $_jre ]; then
+    # Check, if not in $startdir
+    if [ ! -f ../$_jre ]; then
+      msg2 "Due to a change in how Oracle handles the Java SE License Agreement
      you are required to:
      1) accept the license and download the tarball (.tar.gz) yourself:
         http://www.oracle.com/technetwork/java/javase/downloads/jre-7u4-download-1591157.html
      2) move it to \$startdir/ ($startdir/)"
 
-  msg2 "If saved in ~/Desktop/, ~/Downloads/ or /tmp/, it will be auto-moved for you"
+      msg2 "If saved in ~/Desktop/, ~/Downloads/ or /tmp/, it will be auto-moved for you"
 
-  msg2 "Press any key to continue"
-  read -n1
+      msg2 "Press any key to continue"
+      read -n1 -s
 
-  for i in ~/{Desktop,Downloads} /tmp; do
-    if [ -f $i/jre-$_pkg-linux-$_arch2.tar.gz ]; then
-      msg2 "Moving jre-$_pkg-linux-$_arch2.tar.gz from $i/ to $startdir/"
-      mv $i/jre-$_pkg-linux-$_arch2.tar.gz ../
-
-      msg2 "Symlinking to \$srcdir/"
-      ln -s ../jre-$_pkg-linux-$_arch2.tar.gz .
+      # Try to move from said locations
+      for i in /tmp ~/{Desktop,Downloads}; do
+      if [ -f $i/$_jre ]; then
+        msg2 "Moving $_jre from $i/ to $startdir/"
+        mv $i/$_jre ../
+        break
+      fi
+      done
+      # If still not there, exit with status 1 (error)
+      if [ ! -f ../$_jre  ]; then
+        error "Tarball not found in the right location. Exiting.."
+        exit 1
+      fi
     fi
-  done
-
-  if [ ! -f ../jre-$_pkg-linux-$_arch2.tar.gz ]; then
-    error "Tarball not found in the right location. Exiting.."
-    exit 1
+    msg2 "Symlinking to \$srcdir/"
+    ln -sf ../$_jre .
   fi
 
   msg2 "Extracting sources..."
-  bsdtar -xf jre-$_pkg-linux-$_arch2.tar.gz
+  bsdtar -xf $_jre
 
   msg2 "Creating required dirs"
   cd $(ls -1d jre1.7.0_*/ | tail -1)
