updated on Fri Apr 27 14:00:13 UTC 2012

diff --git a/jdk/PKGBUILD b/jdk/PKGBUILD
--- a/jdk/PKGBUILD
+++ b/jdk/PKGBUILD
@@ -2,8 +2,11 @@
 # Contributors: Charles Ghislain, Guillaume ALAUX, Daniel J Griffiths, Jason Chu, Geoffroy Carrier, Army, kfgz, Thomas Dziedzic, Dan Serban
 
 pkgname=jdk
-pkgver=7u3
-_build=b04
+_major=7
+_minor=4
+_pkg=${_major}u$_minor
+pkgver=$_major.$_minor
+_build=b0$_minor
 pkgrel=1
 pkgdesc="Java 7 Development Kit"
 url=http://www.oracle.com/technetwork/java/javase/downloads/index.html
@@ -16,37 +19,64 @@ backup=('etc/conf.d/derby-network-server'
         'etc/profile.d/jdk.csh'
         'etc/profile.d/jdk.sh')
 install=jdk.install
-_arch=i386; [ "$CARCH" == 'x86_64' ] && _arch=amd64
-#source=("http://download.oracle.com/otn-pub/java/jdk/$pkgver-$_build/jdk-$pkgver-linux-i586.tar.gz"
-source=("http://uni-smr.ac.ru/archive/dev/java/SDKs/oracle/j2se/7/jdk-$pkgver-linux-i586.tar.gz"
-        'java-monitoring-and-management-console.desktop'
+_arch=i386 && _arch2=i586; [ "$CARCH" == 'x86_64' ] && _arch=amd64 && _arch2=x64
+# source=("http://download.oracle.com/otn-pub/java/jdk/$_pkg-$_build/jdk-$_pkg-linux-i586.tar.gz"
+# source=("http://uni-smr.ac.ru/archive/dev/java/SDKs/oracle/j2se/7/jdk-$_pkg-linux-i586.tar.gz"
+source=('java-monitoring-and-management-console.desktop'
         'java-visualvm.desktop'
         'jdk.sh'
         'jdk.csh'
         'derby-network-server'
         'derby-network-server.conf'
         'javaws-launcher')
-md5sums=('99a0fa02b608985c271e55122f0621bf'  # jdk-$pkgver-linux-i586.tar.gz
-         'da10de5e6507c392fc9871076ef53ec6'  # java-monitoring-and-management-console.desktop
+# md5sums=('99a0fa02b608985c271e55122f0621bf'  # jdk-$_pkg-linux-i586.tar.gz
+md5sums=('da10de5e6507c392fc9871076ef53ec6'  # java-monitoring-and-management-console.desktop
          '35fd89c5c170021d2183593335703703'  # java-visualvm.desktop
          'b83ab5742651b4234b7d2e20785c6693'  # jdk.sh
          '6f4cbf332816d2c4e9578ecd1d0dce7f'  # jdk.csh
          'a279e195e249000646895d93e199860d'  # derby-network-server
          '4bdff6982c66d24a879c424aaac3d04d'  # derby-network-server.conf
          '45c15a6b4767288f2f745598455ea2bf') # javaws-launcher
-#[ "$CARCH" == 'x86_64' ] && source[0]="http://download.oracle.com/otn-pub/java/jdk/$pkgver-$_build/jdk-$pkgver-linux-x64.tar.gz" && md5sums[0]='969927251b558ffbc09ede1e89200d40'
-[ "$CARCH" == 'x86_64' ] && source[0]="http://uni-smr.ac.ru/archive/dev/java/SDKs/oracle/j2se/7/jdk-$pkgver-linux-x64.tar.gz" && md5sums[0]='969927251b558ffbc09ede1e89200d40'
+# [ "$CARCH" == 'x86_64' ] && source[0]="http://download.oracle.com/otn-pub/java/jdk/$_pkg-$_build/jdk-$_pkg-linux-x64.tar.gz" && md5sums[0]='969927251b558ffbc09ede1e89200d40'
+# [ "$CARCH" == 'x86_64' ] && source[0]="http://uni-smr.ac.ru/archive/dev/java/SDKs/oracle/j2se/7/jdk-$_pkg-linux-x64.tar.gz" && md5sums[0]='969927251b558ffbc09ede1e89200d40'
 
-package(){
+package() {
+  msg2 "Due to a change in how Oracle handles the Java SE License Agreement
+     you are required to:
+     1) accept the license and download the tarball (.tar.gz) yourself:
+        http://www.oracle.com/technetwork/java/javase/downloads/jdk-7u4-downloads-1591156.html
+     2) move it to \$srcdir/ ($srcdir/)"
+
+  msg2 "If saved in ~/Desktop/, ~/Downloads/ or \$startdir/ ($startdir/),
+     it will be auto-moved for you"
+
+  msg2 "Press any key to continue"
+  read -n1
+
+  for i in ~/{Desktop,Downloads} $startdir; do
+    if [ -f $i/jdk-$_pkg-linux-$_arch2.tar.gz ]; then
+      msg2 "Moving jdk-$_pkg-linux-$_arch2.tar.gz from $i/ to $srcdir/"
+      mv $i/jdk-$_pkg-linux-$_arch2.tar.gz .
+    fi
+  done
+
+  if [ ! -f $srcdir/jdk-$_pkg-linux-$_arch2.tar.gz ]; then
+    error "The tarball was not found in the right location. Exiting.."
+    exit 1
+  fi
+
+  msg2 "Extracting sources..."
+  bsdtar -xf jdk-$_pkg-linux-$_arch2.tar.gz
+
   msg2 "Creating required dirs"
-  cd $(ls -1d jdk1.7.0_* | tail -1)
+  cd $(ls -1d jdk1.7.0_*/ | tail -1)
   mkdir -p "$pkgdir"/{opt/java/{,jre/lib/$_arch},etc/profile.d,usr/share/{applications,licenses/jdk}}
 
-  msg2 "Fetching missing libraries from 'jre' to fix jconsole"
+  msg2 "Fetching missing libraries from jre/ to fix jconsole"
   mv jre/lib/$_arch/lib{saproc,attach}.so "$pkgdir"/opt/java/jre/lib/$_arch/
 
-  msg2 "Removing already provided 'jre' and redundant .bat scripts"
-  rm -r jre/ lib/visualvm/platform/docs/ # lib/desktop/
+  msg2 "Removing empty and redundant dirs and .bat scripts"
+  rm -r jre/ # lib/visualvm/platform/docs/ lib/desktop/
   find . -name '*\.bat' -delete
 
   msg2 "Moving stuff in place"
diff --git a/jre/PKGBUILD b/jre/PKGBUILD
--- a/jre/PKGBUILD
+++ b/jre/PKGBUILD
@@ -2,8 +2,11 @@
 # Contributors: Charles Ghislain, Guillaume ALAUX, Daniel J Griffiths, Jason Chu, Geoffroy Carrier, Army, kfgz, Thomas Dziedzic, Dan Serban
 
 pkgname=jre
-pkgver=7u3
-_build=b04
+_major=7
+_minor=4
+_pkg=${_major}u$_minor
+pkgver=$_major.$_minor
+_build=b0$_minor
 pkgrel=1
 pkgdesc="Java 7 Runtime Environment"
 url=http://www.oracle.com/technetwork/java/javase/downloads/index.html
@@ -17,22 +20,49 @@ conflicts=('java-runtime' 'java-runtime-headless')
 backup=(etc/profile.d/jre.sh
         etc/profile.d/jre.csh)
 install=jre.install
-_arch=i386; [ "$CARCH" == 'x86_64' ] && _arch=amd64
-#source=("http://download.oracle.com/otn-pub/java/jdk/$pkgver-$_build/jre-$pkgver-linux-i586.tar.gz"
-source=("http://uni-smr.ac.ru/archive/dev/java/JRE/oracle/7/jre-$pkgver-linux-i586.tar.gz"
-        'java-policy-settings.desktop'
+_arch=i386 && _arch2=i586; [ "$CARCH" == 'x86_64' ] && _arch=amd64 && _arch2=x64
+# source=("http://download.oracle.com/otn-pub/java/jdk/$_pkg-$_build/jre-$_pkg-linux-i586.tar.gz"
+# source=("http://uni-smr.ac.ru/archive/dev/java/JRE/oracle/7/jre-$_pkg-linux-i586.tar.gz"
+source=('java-policy-settings.desktop'
         'jre.sh'
         'jre.csh'
         'javaws-launcher')
-md5sums=('cfce10a05f8d152d39aef892f2cd4011'
-         'f4e25ef1ccef8d36ff2433c3987a64fe'
-         '85ba1d2b39d5e6efad89ef98d0f19909'
-         'c106d744a5ca16a7bad35b3332818114'
-         '45c15a6b4767288f2f745598455ea2bf')
-#[ "$CARCH" == 'x86_64' ] && source[0]="http://download.oracle.com/otn-pub/java/jdk/$pkgver-$_build/jre-$pkgver-linux-x64.tar.gz" && md5sums[0]='3d3e206cea84129f1daa8e62bf656a28'
-[ "$CARCH" == 'x86_64' ] && source[0]="http://uni-smr.ac.ru/archive/dev/java/JRE/oracle/7/jre-$pkgver-linux-x64.tar.gz" && md5sums[0]='3d3e206cea84129f1daa8e62bf656a28'
+# md5sums=('cfce10a05f8d152d39aef892f2cd4011'  # jre-$_pkg-linux-i586.tar.gz"
+md5sums=('f4e25ef1ccef8d36ff2433c3987a64fe'  # java-policy-settings.desktop
+         '85ba1d2b39d5e6efad89ef98d0f19909'  # jre.sh
+         'c106d744a5ca16a7bad35b3332818114'  # jre.csh
+         '45c15a6b4767288f2f745598455ea2bf') # javaws-launcher
+# [ "$CARCH" == 'x86_64' ] && source[0]="http://download.oracle.com/otn-pub/java/jdk/$_pkg-$_build/jre-$_pkg-linux-x64.tar.gz" && md5sums[0]='3d3e206cea84129f1daa8e62bf656a28'
+# [ "$CARCH" == 'x86_64' ] && source[0]="http://uni-smr.ac.ru/archive/dev/java/JRE/oracle/7/jre-$_pkg-linux-x64.tar.gz" && md5sums[0]='3d3e206cea84129f1daa8e62bf656a28'
 
 package() {
+  msg2 "Due to a change in how Oracle handles the Java SE License Agreement
+     you are required to:
+     1) accept the license and download the tarball (.tar.gz) yourself:
+        http://www.oracle.com/technetwork/java/javase/downloads/jre-7u4-download-1591157.html
+     2) move it to \$srcdir/ ($srcdir/)"
+
+  msg2 "If saved in ~/Desktop/, ~/Downloads/ or \$startdir/ ($startdir/),
+     it will be auto-moved for you"
+
+  msg2 "Press any key to continue"
+  read -n1
+
+  for i in ~/{Desktop,Downloads} $startdir; do
+    if [ -f ~/$i/jre-$_pkg-linux-$_arch2.tar.gz ]; then
+      msg2 "Moving jre-$_pkg-linux-$_arch2.tar.gz from ~/"$i"/ to $srcdir/"
+      mv ~/$i/jre-$_pkg-linux-$_arch2.tar.gz .
+    fi
+  done
+
+  if [ ! -f $srcdir/jre-$_pkg-linux-$_arch2.tar.gz ]; then
+    error "The tarball was not found in the right location. Exiting.."
+    exit 1
+  fi
+
+  msg2 "Extracting sources..."
+  bsdtar -xf jre-$_pkg-linux-$_arch2.tar.gz
+
   msg2 "Creating required dirs"
   cd $(ls -1d jre1.7.0_*/ | tail -1)
   mkdir -p "$pkgdir"/{opt/java/jre,usr/{share/{,licenses/jre},lib/mozilla/plugins},etc/{.java/.systemPrefs,profile.d}}
@@ -45,11 +75,11 @@ package() {
   rmdir lib/{applet,desktop}
 
   msg2 "Moving stuff in place"
-  mv * "$pkgdir"/opt/java/jre
+  mv * "$pkgdir"/opt/java/jre/
 
   msg2 "Symlinking the plugin"
   cd "$srcdir"
-  ln -s /opt/java/jre/lib/$_arch/libnpjp2.so "$pkgdir"/usr/lib/mozilla/plugins/libnpjp2.so
+  ln -s /opt/java/jre/lib/$_arch/libnpjp2.so "$pkgdir"/usr/lib/mozilla/plugins/
 
   msg2 "Installing scripts, .desktop file and licenses"
   install -m755 javaws-launcher "$pkgdir"/opt/java/jre/bin/
