updated on Sun Sep 16 00:00:14 UTC 2012

diff --git a/dbus-core-lsd/dbus.install b/dbus-core-lsd/dbus.install
--- a/dbus-core-lsd/dbus.install
+++ b/dbus-core-lsd/dbus.install
@@ -1,23 +1,39 @@
 post_install() {
-  getent group dbus >/dev/null || groupadd -g 81 dbus
-  getent passwd dbus >/dev/null || useradd -c 'System message bus' -u 81 -g dbus -d '/' -s /bin/false dbus
-  passwd -l dbus &>/dev/null
+  if ! getent group dbus >/dev/null; then
+    /usr/sbin/groupadd -g 81 dbus || {
+      echo 'Could not set up the dbus group!'
+      return 1
+    }
+  fi
+
+  if ! getent passwd dbus >/dev/null; then
+    /usr/sbin/useradd -c 'System message bus' -u 81 -g dbus -d '/' -s /bin/false dbus || {
+      echo 'Could not set up the dbus user!'
+      return 1
+    }
+  fi
+
+  usr/bin/passwd -l dbus >/dev/null
+  dbus-uuidgen --ensure
 }
 
 post_upgrade() {
   post_install
 
-  # Make sure new rc script can shutdown running dbus
-  if [ -f run/dbus.pid -a -d run/dbus ]; then
-    mv run/dbus.pid run/dbus/pid
+  #Make sure new rc script can shutdown running dbus
+  if [ -f /var/run/dbus/pid ]; then
+    mv /var/run/dbus/pid /var/run/dbus.pid
   fi
 }
 
 post_remove() {
   if getent passwd dbus >/dev/null; then
-    userdel dbus
+    /usr/sbin/userdel dbus
   fi
+
   if getent group dbus >/dev/null; then
-    groupdel dbus
+    /usr/sbin/groupdel dbus
   fi
 }
+
+# vim:set ts=2 sw=2 et:
