updated on Tue Mar 19 06:14:03 UTC 2013

diff --git a/linux-apparmor/PKGBUILD b/linux-apparmor/PKGBUILD
--- a/linux-apparmor/PKGBUILD
+++ b/linux-apparmor/PKGBUILD
@@ -1,181 +1,211 @@
-# $Id: PKGBUILD 130991 2011-07-09 12:23:51Z thomas $
-
 # Apparmor patched kernel:
-# Mantainer: Gianni Vialetto <gianni at rootcube dot net>
+# Mantainer: Alex Brinister <alex_brinister at yahoo dot com>
 
 # REAL KERNEL PACKAGE:
 # Maintainer: Tobias Powalowski <tpowa@archlinux.org>
 # Maintainer: Thomas Baechler <thomas@archlinux.org>
 
-pkgname=linux-apparmor      
+pkgname=linux-apparmor
 _kernelname=${pkgname#linux}
-_basekernel=3.4
-pkgver=${_basekernel}.9
+_basekernel=3.8
+_minor=3
+pkgver=${_basekernel}.${_minor}
 pkgrel=1
 pkgdesc="The Linux Kernel and modules (with AppArmor patches)"
 groups=('apparmor')
 depends=('coreutils' 'linux-firmware' 'kmod' 'mkinitcpio>=0.7')
 optdepends=('crda: to set the correct wireless channels of your country')
 backup=("etc/mkinitcpio.d/${pkgname}.preset")
-install=${pkgname}.install
+install=$pkgname.install
 arch=('i686' 'x86_64')
 url="http://www.kernel.org/"
 license=('GPL2')
 makedepends=('xmlto' 'docbook-xsl')
 options=('!strip')
-source=("http://www.kernel.org/pub/linux/kernel/v3.x/linux-3.4.tar.xz"
-        "http://www.kernel.org/pub/linux/kernel/v3.x/patch-${pkgver}.xz"
-        # the main kernel config files
-        'config' 'config.x86_64'
-        # standard config files for mkinitcpio ramdisk
-        "${pkgname}.preset"
-        'fix-acerhdf-1810T-bios.patch'
-        'change-default-console-loglevel.patch'
-        'i915-fix-ghost-tv-output.patch'
-        '3.4.4-fix-backlight-regression.patch'
-        '3.4.4-fix-gtx560ti-nouveau-regression.patch'
-	'AppArmor-Add-profile-introspection-file.patch'
-	'AppArmor-basic-networking-rules.patch'
-	'AppArmor-Add-the-ability-to-mediate-mou.patch')
-md5sums=('967f72983655e2479f951195953e8480'
-         'ffd1d2010b97fe45a62c9ce856ca224f'
-         '3f2c307c8ffae67f60c13ef69af8364a'
-         '18d9d09152bafffaef78f2aac07e7145'
-         'eb14dcfd80c00852ef81ded6e826826a'
-         '38c1fd4a1f303f1f6c38e7f082727e2f'
-         '9d3c56a4b999c8bfbd4018089a62f662'
-         '263725f20c0b9eb9c353040792d644e5'
-         '80a46681386bb87813989faeb92bdd9a'
-         '827ffd855dc8b0c91577545c5804c19f'
-         '7c1864c1e53cf0d2e58dc0eb0d648ece'
-         '53eddc07bcd4aeef5785a7b289951885'
-         'c7a6fc554a7ce5270ae7e0940b257551')
+source=(http://www.kernel.org/pub/linux/kernel/v3.x/linux-$pkgver.tar.xz
+        http://www.kernel.org/pub/linux/kernel/v3.x/patch-$pkgver.xz
+        config 
+		config.x86_64
+        $pkgname.preset
+        fix-acerhdf-1810T-bios.patch
+        change-default-console-loglevel.patch
+        i915-fix-ghost-tv-output.patch
+        3.4.4-fix-backlight-regression.patch
+        3.4.4-fix-gtx560ti-nouveau-regression.patch
+		0001-UBUNTU-SAUCE-AppArmor-Add-profile-introspection-file.patch
+		0002-UBUNTU-SAUCE-AppArmor-basic-networking-rules.patch
+		0003-apparmor-Fix-quieting-of-audit-messages-for-network-.patch
+		0004-apparmor-Ensure-apparmor-does-not-mediate-kernel-bas.patch
+		0005-UBUNTU-SAUCE-apparmor-Add-the-ability-to-mediate-mou.patch)
+sha512sums=('43a73b94ee1249dd95ef70395d00fab6ac77eff6756abbe43cac23c4fc63421c3fb9f4f33ba8f5159f2b28c3cc359aba88872972b192c7a0ddc949c0f06a4453'
+            '14c4ffe8da8024ec77b16b21e959453c84b3693027a1746533c03dac74e4f8f8d1b385d9e697207cbb701a7a60aa1950d44e02dde9f3a964d4b49467cb07f0be'
+            '17aac4b3e28038d5230a1819164830b3444afdc9a17f682b008004eeab4f2c2b4acee20a3806221e87aeab9e1e001974345bd165e16d5fcedc96b44951b0568a'
+            '76cde689974f132f54a12f4fca55fdce78d36c769d59544dfe010da34df864a28a088ae81b32e3414270f9363005661bc651c50a84f0cf7254dc0268a9f9e312'
+            '5fe243dea17fdb71edc7098e0e1938beb7f2d851bd2be3981c4ef3d617aaad81ff1cb4c84689082472ebd13b721e849ad2214aefb9ffe40ec3d76abfd40b87ad'
+            '8294ff8c8d280305c1d611e579859758e96970fd90f02f1ea326e2e19ff215f26634c1a76340fd3c725bd9a72012aa0a2054bdf8129fffe5817e047cfc9bbfb9'
+            '5d33870bbba5f46eee1b53746e217f97d12c7bdf12acad9faeab852e4407aba434eebd9207ba851cee4eee5609fb6b44772f58cb17092e44a05795842513a8de'
+            'bb153d0bd299e4c05d17a676fac4046778884129671e0ca5e713ed07c468cbc2b1aef32f45bc184293ae8a5fb4b826dc7bd6401dc9009652efa465cab644ebfc'
+            'bf7aacba491bb1f71973cf1d76d181e78a6396f01393698d88ffa4512140ba9cdfb88d4ce374ad04dd520a9ee44728fa63ce81c82da3b279e3037ac8dd634b87'
+            'dd7c4f818a017911da7e3eb94f07ee247720d35ea8fc702350c192478f58a815ea1871155e56e4c0ac6b07eeeb3404e63725e1a084e03e5cb8135b5bec126a6c'
+            '7e83ff16813821e4dcc60275845fc086d06072efbf10e54a6138a400eb26ccc2554d248cdaacbb1c652c1c48fa2eebf124a5130d030ebcfddfecf74f50dc5bf5'
+            '1b454f3ed8a32c8a9179d940477880ba8a5d223391e6edbfa281ae4347ac531859f9dbf926cd9597fe2125fae03696be1d284752ca6460c417673c3ca0c076a7'
+            '4ff503a6af1a863f66ec262414a853373065a9a12a34d5cb46a9ea4c86e5eb6ad4eb4701b2310e324c1aaabda657f306ee262414e4a1237de6724e1adf407eeb'
+            'b9bbd7d3b87953949a0aa6b91bb373462385105fa197d222f7f4cdd33ca4d5a6d38424cf650cfc99ac9d7deba41db794bd0630a04f4dc1db52aae2baafb13422'
+			'ffc084fd63cdf0992c640893192983cf2c09a1d7255764121c7bd25675fa8614bfdeb71016a698ee3b5d4bbbf1d10e31b437d23c16ae876fe1d9a943865b34bc')
+
+# Change this to any kernel configuration script you want: xconfig, config, makeconfig, etc
+_config="nconfig"
+# Options are "pkg" and "local". Local will use system config through /proc/config.gz
+_config_file="local"
 
 build() {
-  cd "${srcdir}/linux-${_basekernel}"
+	cd "${srcdir}/linux-${pkgver}"
 
-  # add upstream patch
-  patch -p1 -i "${srcdir}/patch-${pkgver}"
+	# add upstream patch
+	#patch -p1 -i "${srcdir}/patch-${pkgver}"
 
-  # add latest fixes from stable queue, if needed
-  # http://git.kernel.org/?p=linux/kernel/git/stable/stable-queue.git
+	# add latest fixes from stable queue, if needed
+	# http://git.kernel.org/?p=linux/kernel/git/stable/stable-queue.git
 
-  # Some chips detect a ghost TV output
-  # mailing list discussion: http://lists.freedesktop.org/archives/intel-gfx/2011-April/010371.html
-  # Arch Linux bug report: FS#19234
-  #
-  # It is unclear why this patch wasn't merged upstream, it was accepted,
-  # then dropped because the reasoning was unclear. However, it is clearly
-  # needed.
-  patch -Np1 -i "${srcdir}/i915-fix-ghost-tv-output.patch"
+	# Some chips detect a ghost TV output
+	# mailing list discussion: http://lists.freedesktop.org/archives/intel-gfx/2011-April/010371.html
+	# Arch Linux bug report: FS#19234
+	#
+	# It is unclear why this patch wasn't merged upstream, it was accepted,
+	# then dropped because the reasoning was unclear. However, it is clearly
+	# needed.
+	patch -Np1 -i "${srcdir}/i915-fix-ghost-tv-output.patch"
 
-  # Fix backlight control on some laptops:
-  # https://bugzilla.kernel.org/show_bug.cgi?id=43168
-  patch -Np1 -i "${srcdir}/3.4.4-fix-backlight-regression.patch"
+	# Fix backlight control on some laptops:
+	# https://bugzilla.kernel.org/show_bug.cgi?id=43168
+	patch -Np1 -i "${srcdir}/3.4.4-fix-backlight-regression.patch"
 
-  # fix nouveau regression
-  # Arch Linux bug report: FS#30417
-  patch -Np1 -i "${srcdir}/3.4.4-fix-gtx560ti-nouveau-regression.patch"
+	# fix nouveau regression
+	# Arch Linux bug report: FS#30417
+	patch -Np1 -i "${srcdir}/3.4.4-fix-gtx560ti-nouveau-regression.patch"
 
-  # Patch submitted upstream, waiting for inclusion:
-  # https://lkml.org/lkml/2012/2/19/51
-  # add support for latest bios of Acer 1810T acerhdf module
-  patch -Np1 -i "${srcdir}/fix-acerhdf-1810T-bios.patch"
+	# Patch submitted upstream, waiting for inclusion:
+	# https://lkml.org/lkml/2012/2/19/51
+	# add support for latest bios of Acer 1810T acerhdf module
+	patch -Np1 -i "${srcdir}/fix-acerhdf-1810T-bios.patch"
 
-  # set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
-  # remove this when a Kconfig knob is made available by upstream
-  # (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
-  patch -Np1 -i "${srcdir}/change-default-console-loglevel.patch"
+	# set DEFAULT_CONSOLE_LOGLEVEL to 4 (same value as the 'quiet' kernel param)
+	# remove this when a Kconfig knob is made available by upstream
+	# (relevant patch sent upstream: https://lkml.org/lkml/2011/7/26/227)
+	patch -Np1 -i "${srcdir}/change-default-console-loglevel.patch"
 
-  # AppArmor patchset
-  patch -Np1 -i "${srcdir}/AppArmor-Add-profile-introspection-file.patch"
-  patch -Np1 -i "${srcdir}/AppArmor-basic-networking-rules.patch"
-  patch -Np1 -i "${srcdir}/AppArmor-Add-the-ability-to-mediate-mou.patch"
+	# AppArmor patchset
+	patch -Np1 -i "$srcdir/0001-UBUNTU-SAUCE-AppArmor-Add-profile-introspection-file.patch"
+	if [ -f $srcdir/linux-$pkgver/security/apparmor/net.c ]; then 
+		rm $srcdir/linux-$pkgver/security/apparmor/net.c 2> /dev/null
+	fi
+	if [ -f $srcdir/linux-$pkgver/security/apparmor/include/net.h ]; then
+		rm $srcdir/linux-$pkgver/security/apparmor/include/net.h 2> /dev/null
+	fi
+	patch -Np1 -i "$srcdir/0002-UBUNTU-SAUCE-AppArmor-basic-networking-rules.patch"
+	patch -Np1 -i "$srcdir/0003-apparmor-Fix-quieting-of-audit-messages-for-network-.patch"
+	patch -Np1 -i "$srcdir/0004-apparmor-Ensure-apparmor-does-not-mediate-kernel-bas.patch"
+	if [ -f $srcdir/linux-$pkgver/security/apparmor/include/mount.h ]; then
+		rm $srcdir/linux-$pkgver/security/apparmor/include/mount.h 2> /dev/null
+	fi
+	if [ -f $srcdir/linux-$pkgver/security/apparmor/mount.c ]; then
+		rm $srcdir/linux-$pkgver/security/apparmor/mount.c 2> /dev/null
+	fi
+	patch -Np1 -i "$srcdir/0005-UBUNTU-SAUCE-apparmor-Add-the-ability-to-mediate-mou.patch"
+	
+	if [ "${_config_file}" = "pkg" ]; then
+	  if [ "${CARCH}" = "x86_64" ]; then
+		cat "${srcdir}/config.x86_64" > ./.config
+	  else
+		cat "${srcdir}/config" > ./.config
+	  fi
+	elif [ "${_config_file}" = "local" ]; then
+	  zcat /proc/config.gz > ./.config
+	else
+	  echo "Not an option! Aborting..."
+	  exit 1
+	fi
+	 
+	  
 
-  if [ "${CARCH}" = "x86_64" ]; then
-    cat "${srcdir}/config.x86_64" > ./.config
-  else
-    cat "${srcdir}/config" > ./.config
-  fi
+	if [ "${_kernelname}" != "" ]; then
+	sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
+	fi
 
-  if [ "${_kernelname}" != "" ]; then
-    sed -i "s|CONFIG_LOCALVERSION=.*|CONFIG_LOCALVERSION=\"${_kernelname}\"|g" ./.config
-  fi
+	# set extraversion to pkgrel
+	sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
 
-  # set extraversion to pkgrel
-  sed -ri "s|^(EXTRAVERSION =).*|\1 -${pkgrel}|" Makefile
+	# don't run depmod on 'make install'. We'll do this ourselves in packaging
+	sed -i '2iexit 0' scripts/depmod.sh
 
-  # don't run depmod on 'make install'. We'll do this ourselves in packaging
-  sed -i '2iexit 0' scripts/depmod.sh
+	# get kernel version
+	make prepare
 
-  # get kernel version
-  make prepare
+	# load configuration
+	# Configure the kernel. Replace the line below with one of your choice.
+	#make menuconfig # CLI menu for configuration
+	#make nconfig # new CLI menu for configuration
+	#make xconfig # X-based configuration
+	#make oldconfig # using old config from previous kernel version
+	# ... or manually edit .config
 
-  # load configuration
-  # Configure the kernel. Replace the line below with one of your choice.
-  #make menuconfig # CLI menu for configuration
-  #make nconfig # new CLI menu for configuration
-  #make xconfig # X-based configuration
-  #make oldconfig # using old config from previous kernel version
-  # ... or manually edit .config
+	####################
+	# stop here
+	# this is useful to configure the kernel
+	#msg "Stopping build"
+	#return 1
+	####################
 
-  ####################
-  # stop here
-  # this is useful to configure the kernel
-  #msg "Stopping build"
-  #return 1
-  ####################
+	make ${_config}
 
-  yes "" | make config
-
-  # build!
-  make ${MAKEFLAGS} bzImage modules
+	# build!
+	make -j2 ${MAKEFLAGS} bzImage modules
 }
 
 package() {
-  cd "${srcdir}/linux-${_basekernel}"
+	cd "${srcdir}/linux-$pkgver"
 
-  KARCH=x86
+	KARCH=x86
 
-  # get kernel version
-  _kernver="$(make kernelrelease)"
+	# get kernel version
+	_kernver="$(make kernelrelease)"
 
-  mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot,usr}
-  make INSTALL_MOD_PATH="${pkgdir}" modules_install
-  cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-${pkgname}"
+	mkdir -p "${pkgdir}"/{lib/modules,lib/firmware,boot,usr}
+	make INSTALL_MOD_PATH="${pkgdir}" modules_install
+	cp arch/$KARCH/boot/bzImage "${pkgdir}/boot/vmlinuz-${pkgname}"
 
-  # add vmlinux
-  install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
+	# add vmlinux
+	install -D -m644 vmlinux "${pkgdir}/usr/src/linux-${_kernver}/vmlinux"
 
-  # install fallback mkinitcpio.conf file and preset file for kernel
-  install -D -m644 "${srcdir}/${pkgname}.preset" "${pkgdir}/etc/mkinitcpio.d/${pkgname}.preset"
+	# install fallback mkinitcpio.conf file and preset file for kernel
+	install -D -m644 "${srcdir}/${pkgname}.preset" "${pkgdir}/etc/mkinitcpio.d/${pkgname}.preset"
 
-  # set correct depmod command for install
-  sed \
-    -e  "s/KERNEL_NAME=.*/KERNEL_NAME=${_kernelname}/g" \
-    -e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
-    -i "${startdir}/${pkgname}.install"
-  sed \
-    -e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-${pkgname}\"|g" \
-    -e "s|default_image=.*|default_image=\"/boot/initramfs-${pkgname}.img\"|g" \
-    -e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-${pkgname}-fallback.img\"|g" \
-    -i "${pkgdir}/etc/mkinitcpio.d/${pkgname}.preset"
+	# set correct depmod command for install
+	sed \
+	-e  "s/KERNEL_NAME=.*/KERNEL_NAME=${_kernelname}/g" \
+	-e  "s/KERNEL_VERSION=.*/KERNEL_VERSION=${_kernver}/g" \
+	-i "${startdir}/${pkgname}.install"
+	sed \
+	-e "s|ALL_kver=.*|ALL_kver=\"/boot/vmlinuz-${pkgname}\"|g" \
+	-e "s|default_image=.*|default_image=\"/boot/initramfs-${pkgname}.img\"|g" \
+	-e "s|fallback_image=.*|fallback_image=\"/boot/initramfs-${pkgname}-fallback.img\"|g" \
+	-i "${pkgdir}/etc/mkinitcpio.d/${pkgname}.preset"
 
-  # remove build and source links
-  rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
-  # remove the firmware
-  rm -rf "${pkgdir}/lib/firmware"
-  # gzip -9 all modules to save 100MB of space
-  find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
-  # make room for external modules
-  ln -s "../extramodules-${_basekernel}${_kernelname:--ARCH}" "${pkgdir}/lib/modules/${_kernver}/extramodules"
-  # add real version for building modules and running depmod from post_install/upgrade
-  mkdir -p "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:--ARCH}"
-  echo "${_kernver}" > "${pkgdir}/lib/modules/extramodules-${_basekernel}${_kernelname:--ARCH}/version"
+	# remove build and source links
+	rm -f "${pkgdir}/usr/lib/modules/${_kernver}/{source,build}"
+	# remove the firmware
+	rm -rf "${pkgdir}/usr/lib/firmware"
+	# gzip -9 all modules to save 100MB of space
+	find "${pkgdir}" -name '*.ko' -exec gzip -9 {} \;
+	# make room for external modules
+	ln -s "../extramodules-${_basekernel}${_kernelname:--ARCH}" "${pkgdir}/usr/lib/modules/${_kernver}/extramodules"
+	# add real version for building modules and running depmod from post_install/upgrade
+	mkdir -p "${pkgdir}/usr/lib/modules/extramodules-${_basekernel}${_kernelname:--ARCH}"
+	echo "${_kernver}" > "${pkgdir}/usr/lib/modules/extramodules-${_basekernel}${_kernelname:--ARCH}/version"
 
-  # move module tree /lib -> /usr/lib
-  mv "$pkgdir/lib" "$pkgdir/usr"
+	# move module tree /lib -> /usr/lib
+	#mv "$pkgdir/lib" "$pkgdir/usr"
 
-  # Now we call depmod...
-  depmod -b "$pkgdir" -F System.map "$_kernver"
+	# Now we call depmod...
+	depmod -b "$pkgdir" -F System.map "$_kernver"
 }
