updated on Sat Apr 27 00:00:04 UTC 2013

diff --git a/aurget/aurget b/aurget/aurget
--- a/aurget/aurget
+++ b/aurget/aurget
@@ -5,35 +5,22 @@
 ###
 AUR='https://aur.archlinux.org'
 
-arguments=()
-dependencies=()
-
 # Support {{{
 die() { error $*; exit 1; }
 
-info() { echo -e "${colorB}:: $colorW$*$nocolor"; }
+info() { printf "${colorB}:: $colorW$*$nocolor\n"; }
 
-warn() { echo -e "${colorY}warning: $nocolor$*" >&2; }
+warn() { printf "${colorY}warning:$nocolor $*\n" >&2; }
 
-error() { echo -e "${colorR}error: $nocolor$*" >&2; }
+error() { printf "${colorR}error:$nocolor $*\n" >&2; }
 
 debug() {
-  $debug && echo -e "$colorW[${colorC}DEBUG$colorW]$nocolor $*" >&2
-}
-
-err_no_targets() {
-  if [[ "$opmode" == 'upgrade' ]]; then
-    echo 'nothing to upgrade'
-    exit 0
-  fi
-
-  die 'no targets specified (use -h for help)'
+  $debug && printf "$colorW[${colorC}DEBUG$colorW]$nocolor $*\n" >&2
 }
 
 # thanks Irm
 url_encode() {
-  echo "$*" \
-    | hexdump -v -e '1/1 "%02x\t"' -e '1/1 "%_c\n"' \
+  hexdump -v -e '1/1 "%02x\t"' -e '1/1 "%_c\n"' <<< "$*" \
     | LANG=C awk '
       $1 == "20"                   { printf("%s", "+"); next }
       $1 ~  /0[adAD]/              {                    next }
@@ -43,25 +30,21 @@ url_encode() {
 }
 
 aur_packages_url() {
-  echo "$AUR/packages/$(url_encode "${1:0:2}")/$(url_encode "$1")"
+  printf "$AUR/packages/$(url_encode "${1:0:2}")/$(url_encode "$1")\n"
 }
 
 aur_search_url() {
-  echo "$AUR/rpc.php?type=search&arg=$(url_encode "$1")"
+  printf "$AUR/rpc.php?type=search&arg=$(url_encode "$1")\n"
 }
 
 aur_info_url() {
-  echo "$AUR/rpc.php?type=info&arg=$(url_encode "$1")"
-}
-
-aur_multiinfo_url() {
   local params='' arg
 
   for arg; do
     params+="&arg\[\]=$(url_encode "$arg")"
   done
 
-  echo "$AUR/rpc.php?type=multiinfo$params"
+  printf "$AUR/rpc.php?type=multiinfo$params\n"
 }
 
 get() { debug "HTTP GET $colorM$1$nocolor"; curl --silent --fail "$1"; }
@@ -72,17 +55,19 @@ taurball() { get "$(aur_packages_url $1)/${1}.tar.gz"; }
 
 rpc_search() { get "$(aur_search_url "$1")" | parse_rpc; }
 
-rpc_info() { get "$(aur_info_url "$1")" | parse_rpc; }
-
-rpc_multiinfo() { get "$(aur_multiinfo_url "$@")" | parse_rpc; }
+rpc_info() { get "$(aur_info_url "$@")" | parse_rpc; }
 
 parse_rpc() {
   awk -F '[^\\\\]"' -v RS='{"|,"|"}' '
     function unstring(str) {
-      sub(/[^:]+:/, "", str)
-      gsub(/\\\"/, "\"", str)
-      gsub(/"$/, "", str)
-      return substr(str, 2, length(str))
+      sub(/[^:]+:/, ""  , str) # remove prefix
+      gsub(/\\\"/ , "\"", str) # un-escape quotes
+      gsub(/\\\// , "/" , str) # un-escape urls
+      gsub(/%/    , "%%", str) # escape percents for printf
+      gsub(/\|/   , "/" , str) # replace pipe (our own field sep)
+      gsub(/"$/   , ""  , str) # remove extra trailing quote
+
+      return substr(str, 2, length(str)) # unquote value
     }
 
     /Name":/        { printf "%s",    unstring($0) }
@@ -101,9 +86,9 @@ is_ignored() { [[ " $ignore_packages " =~ " $1 " ]]; }
 prompt() {
   local a
 
-  echo -en "$*? [Y/n] "
+  printf "$*? [Y/n] "
 
-  $noconfirm && { echo 'Y'; return 0; }
+  $noconfirm && { printf "Y\n"; return 0; }
 
   read a
 
@@ -123,19 +108,23 @@ prompt_to_edit() {
     prompt) prompt "Edit $name's PKGBUILD before $action" || return 0 ;;
   esac
 
+  debug "executing $colorY$EDITOR $pkgbuild$nocolor"
+
   $EDITOR "$pkgbuild" || die "editor returned non-zero ($?), aborting"
 
   prompt "Continue $action"
 }
+# }}}
 
+# Initialization {{{
 set_defaults() {
-  local config_re=' --config +([^ ]+) '
+  local config_regex=' --config +([^ ]+) '
 
   debug=false
   user_config="${XDG_CONFIG_HOME:-$HOME/.config}/aurgetrc"
 
-  [[ " $* " =~ " --debug " ]] && debug=true
-  [[ " $* " =~ $config_re  ]] && user_config="${BASH_REMATCH[1]}"
+  [[ " $* " =~ " --debug "    ]] && debug=true
+  [[ " $* " =~ $config_regex  ]] && user_config="${BASH_REMATCH[1]}"
 
   build_directory="$PWD"
   devels=false
@@ -154,14 +143,16 @@ set_defaults() {
   EDITOR="${EDITOR:-$VISUAL}"
   EDITOR="${EDITOR:-vi}"
 
-  colorR="\e[1;31m"
-  colorG="\e[1;32m"
-  colorY="\e[1;33m"
-  colorB="\e[1;34m"
-  colorM="\e[1;35m"
-  colorC="\e[1;36m"
-  colorW="\e[1;37m"
-  nocolor="\e[0m"
+  if [[ -t 1 ]]; then
+    colorR="\e[1;31m"
+    colorG="\e[1;32m"
+    colorY="\e[1;33m"
+    colorB="\e[1;34m"
+    colorM="\e[1;35m"
+    colorC="\e[1;36m"
+    colorW="\e[1;37m"
+    nocolor="\e[0m"
+  fi
 }
 
 source_config() {
@@ -239,12 +230,12 @@ enter_build_directory() {
 execute_search() {
   [[ "$opmode" == 'search' ]] || return 1
 
-  debug "executing search for $colorG$@$nocolor (mode: $colorG$search_mode$nocolor)"
+  debug "searching for $colorG$*$nocolor (mode: $colorG$search_mode$nocolor)"
 
   case "$search_mode" in
-    search) rpc_search    "$*" | sort | print_search ;;
-    info)   rpc_multiinfo "$@" | sort | print_info   ;;
-    quiet)  rpc_search    "$*" | sort | cut -d '|' -f 1 ;;
+    search) rpc_search "$*" | sort | print_search ;;
+    info)   rpc_info   "$@" | sort | print_info   ;;
+    quiet)  rpc_search "$*" | sort | cut -d '|' -f 1 ;;
     print)  for name; do pkgbuild "$name"; done ;;
   esac
 }
@@ -255,9 +246,8 @@ print_search() {
   while IFS='|' read -r name version description _ outofdate _; do
     (( "$outofdate" )) && ood="$colorR[out of date]$nocolor"
 
-    ( echo -e "${colorM}aur/$colorW$name $colorG$version$nocolor $ood"
-      echo -e "    ${description//\\\///}"
-    ) 2>/dev/null
+    printf "${colorM}aur/$colorW$name $colorG$version$nocolor $ood\n"
+    printf "    $description\n"
   done
 }
 
@@ -267,13 +257,12 @@ print_info() {
   while IFS='|' read -r name version description url outofdate _; do
     (( "$outofdate" )) && ood="${colorR}Yes$nocolor"
 
-    ( echo -e "${colorW}Repository  : ${colorM}aur$nocolor"
-      echo -e "${colorW}Name        : $name$nocolor"
-      echo -e "${colorW}Version     : $colorG$version$nocolor"
-      echo -e "${colorW}URL         : $colorC${url//\\\///}$nocolor"
-      echo -e "${colorW}Out of date : $nocolor$ood"
-      echo -e "${colorW}Description : $nocolor${description//\\\///}\n"
-    ) 2>/dev/null
+    printf "${colorW}Repository  : ${colorM}aur$nocolor\n"
+    printf "${colorW}Name        : $name$nocolor\n"
+    printf "${colorW}Version     : $colorG$version$nocolor\n"
+    printf "${colorW}URL         : $colorC$url$nocolor\n"
+    printf "${colorW}Out of date : $nocolor$ood\n"
+    printf "${colorW}Description : $nocolor$description\n\n"
   done
 }
 # }}}
@@ -345,19 +334,21 @@ available_upgrades() {
   declare -A versions
 
   while read -r name version; do
-    if is_devel $name; then
-      if $devels; then
-        debug "upgrade available for $colorG$name$nocolor (development package)"
-        echo "$name"
-      fi
-    else
-      versions[$name]=$version
-    fi
+    versions[$name]=$version
   done < <(pacman -Qm)
 
   debug "found $colorG${#versions[@]}$nocolor foreign packages to check"
 
   while IFS='|' read -r name versN _; do
+    if is_devel $name; then
+      if $devels; then
+        debug "upgrade available for $colorG$name$nocolor (development package)"
+        printf "$name\n"
+      fi
+
+      continue
+    fi
+
     vers="${versions[$name]}"
 
     read -r check < <(vercmp "$vers" "$versN")
@@ -368,25 +359,35 @@ available_upgrades() {
 
     if (( $check < 0 )); then
       debug "upgrade available for $colorG$name$nocolor (new version)"
-      echo "$name"
+      printf "$name\n"
     fi
-  done < <(rpc_multiinfo "${!versions[@]}")
+  done < <(rpc_info "${!versions[@]}")
 }
 # }}}
 
 # Target handling {{{
+err_no_targets() {
+  if [[ "$opmode" == 'upgrade' ]]; then
+    printf "nothing to upgrade\n"
+    exit 0
+  fi
+
+  die 'no targets specified (use -h for help)'
+}
+
 set_targets() {
   local dep="$1"; shift
   local name version
 
-  # global: versions[]
-  # global: deps[]
+  # global: targets[]
+  # global: target_versions[]
+  # global: target_deps[]
 
   (( $# )) || return
 
   debug "setting targets for $colorG$@$nocolor (dependency flag: $colorG$dep$nocolor)"
 
-  while IFS='|' read -r name version _; do
+  for name; do
     if is_ignored "$name"; then
       if ! prompt "$name is in ignore_packages. Install anyway"; then
         warn "skipping target: $name"
@@ -394,19 +395,22 @@ set_targets() {
       fi
     fi
 
-    versions[$name]=$version
-    deps[$name]=$dep
-  done < <(rpc_multiinfo "$@")
+    targets+=( "$name" )
+  done
+
+  while IFS='|' read -r name version _; do
+    target_versions[$name]=$version
+    target_deps[$name]=$dep
+  done < <(rpc_info "$@")
 }
 
 process_targets() {
   local name version packages
 
-  # global: versions[]
-  # global: deps[]
+  # global: target_versions[]
 
   for name; do
-    version="${versions[$name]}"
+    version="${target_versions[$name]}"
 
     if [[ -n "$version" ]]; then
       packages+="${name}-$version "
@@ -415,7 +419,7 @@ process_targets() {
     fi
   done
 
-  echo -e "\n${colorY}Targets ($#):$nocolor $packages\n"
+  printf "\n${colorY}Targets ($#):$nocolor $packages\n\n"
 
   prompt "Proceed with installation" || exit 0
 
@@ -424,7 +428,7 @@ process_targets() {
   [[ "$sync_mode" == 'install' ]] && makepkg_options+=' --install'
 
   for name; do
-    [[ -n "${versions[$name]}" ]] && process_target "$name"
+    [[ -n "${target_versions[$name]}" ]] && process_target "$name"
   done
 }
 
@@ -457,7 +461,7 @@ process_target() {
 build_target() {
   local name="$1" pkgbuild
 
-  # global: deps[]
+  # global: target_deps[]
 
   info 'Building package...'
 
@@ -470,8 +474,8 @@ build_target() {
     customizepkg --modify || warn "customizepkg returned non-zero ($?)"
   fi
 
-  if prompt_to_edit "$name" 'PKGBUILD' 'building'; then
-    if (( ${deps[$name]} )); then
+  if prompt_to_edit "$name" './PKGBUILD' 'building'; then
+    if (( ${target_deps[$name]} )); then
       debug "executing $colorY$makepkg $makepkg_options --asdeps$nocolor"
       $makepkg $makepkg_options --asdeps || die "dependency package $name failed to build, aborting"
     else
@@ -558,6 +562,12 @@ EOF
 }
 # }}}
 
+declare -a arguments
+declare -a dependencies
+declare -a targets
+declare -A target_versions # name->version
+declare -A target_deps     # name->is-dep?
+
 set_defaults "$@"
 
 source_config
@@ -574,11 +584,8 @@ add_available_upgrades
 
 set_dependencies
 
-declare -A versions
-declare -A deps
-
 info 'Searching AUR...'
 set_targets 1 "${dependencies[@]}"
 set_targets 0 "${arguments[@]}"
 
-process_targets "${dependencies[@]}" "${arguments[@]}"
+process_targets "${targets[@]}"
