updated on Fri May 10 00:20:47 UTC 2013

diff --git a/aurget/aurget b/aurget/aurget
--- a/aurget/aurget
+++ b/aurget/aurget
@@ -5,7 +5,7 @@
 ###
 AUR='https://aur.archlinux.org'
 
-# Help message {{{
+# Message {{{
 message() {
   cat << EOF
 Usage: aurget [ -h | -S* [ --options ] [ -- ] <arguments> ]
@@ -126,8 +126,7 @@ parse_rpc() {
     /Version":/     { printf "|%s",   unstring($0) }
     /Description":/ { printf "|%s",   unstring($0) }
     /URL":/         { printf "|%s",   unstring($0) }
-    /OutOfDate":/   { printf "|%s",   unstring($0) }
-    /URLPath":/     { printf "|%s\n", unstring($0) }
+    /OutOfDate":/   { printf "|%s\n", unstring($0) }
   '
 }
 
@@ -135,10 +134,29 @@ is_devel() { [[ "$1" =~ -(git|hg|svn|darcs|csv|bzr)$ ]]; }
 
 is_ignored() { [[ " $ignore_packages " =~ " $1 " ]]; }
 
+searching() { [[ "$opmode" == 'search' ]]; }
+
+upgrading() { [[ "$opmode" == 'upgrade' ]]; }
+
+resolving() { $resolve_dependencies; }
+
+create_temp_directory() {
+  debug "storing temporary files in $colorM$temp_directory$nocolor"
+  mkdir -p "$temp_directory" || die 'unable to create temp directory'
+  rm -rf "$temp_directory"/*
+}
+
+enter_build_directory() {
+  debug "building in $colorM$build_directory$nocolor"
+  mkdir -p "$build_directory" || die 'unable to make build directory'
+  cd "$build_directory"       || die 'unable to change to build directory'
+}
+
 buildpkg() {
   debug "executing $colorY$makepkg $makepkg_options $@$nocolor"
 
   if $silent; then
+    debug 'building silently...'
     $makepkg $makepkg_options "$@" --noconfirm &>/dev/null
   else
     $makepkg $makepkg_options "$@"
@@ -197,8 +215,8 @@ nothing_to_do() {
 }
 # }}}
 
-# Initialization {{{
-set_defaults() {
+# Initialize {{{
+initialize() {
   local config_regex=' --config +([^ ]+) '
 
   debug=false
@@ -207,57 +225,10 @@ set_defaults() {
   [[ " $* " =~ " --debug "    ]] && debug=true
   [[ " $* " =~ $config_regex  ]] && user_config="${BASH_REMATCH[1]}"
 
-  build_directory="$PWD"
-  devels=false
-  discard_sources=true
-  ignore_packages=''
-  keep_devels=true
-  makepkg='makepkg'
-  makepkg_options='--syncdeps'
-  noconfirm=false
-  opmode='install'
-  resolve_dependencies=false
-  search_mode='search'
-  silent=false
-  sync_mode='install'
-  temp_directory='/tmp/aurget'
+  set_defaults
+  source_config
+  setup_colors
 
-  EDITOR="${EDITOR:-$VISUAL}"
-  EDITOR="${EDITOR:-vi}"
-
-  if [[ -t 1 ]]; then
-    colorR="\e[1;31m"
-    colorG="\e[1;32m"
-    colorY="\e[1;33m"
-    colorB="\e[1;34m"
-    colorM="\e[1;35m"
-    colorC="\e[1;36m"
-    colorW="\e[1;37m"
-    nocolor="\e[0m"
-  fi
-}
-
-source_config() {
-  if [[ -r "$user_config" ]]; then
-    debug "sourcing user configuration from $colorM$user_config$nocolor"
-    source "$user_config"
-  fi
-}
-
-set_no_color() {
-  colorR=''
-  colorG=''
-  colorY=''
-  colorB=''
-  colorM=''
-  colorC=''
-  colorW=''
-  nocolor=''
-
-  makepkg_options+=' --nocolor'
-}
-
-parse_options() {
   while [[ -n "$1" ]]; do
     case "$1" in
       -S)            opmode='install'                                ;;
@@ -274,7 +245,7 @@ parse_options() {
       -Sp|-Ssp|-Sps) opmode='search' ; search_mode='print'           ;;
       --ignore)      shift; ignore_packages+=" $1"                   ;;
       --noconfirm)   noconfirm=true; makepkg_options+=" --noconfirm" ;;
-      --nocolor)     set_no_color                                    ;;
+      --nocolor)     disable_color=true                              ;;
       --devel)       devels=true                                     ;;
       --deps)        resolve_dependencies=true                       ;;
       --nodeps)      resolve_dependencies=false                      ;;
@@ -296,28 +267,61 @@ parse_options() {
   done
 }
 
-create_temp_directory() {
-  debug "storing temporary files in $colorM$temp_directory$nocolor"
-  mkdir -p "$temp_directory" || die 'unable to create temp directory'
-  rm -rf "$temp_directory"/*
+set_defaults() {
+  build_directory="$PWD"
+  devels=false
+  disable_color=false
+  discard_sources=true
+  ignore_packages=''
+  keep_devels=true
+  makepkg='makepkg'
+  makepkg_options='--syncdeps'
+  noconfirm=false
+  opmode='install'
+  resolve_dependencies=false
+  search_mode='search'
+  silent=false
+  sync_mode='install'
+  temp_directory='/tmp/aurget'
+
+  EDITOR="${EDITOR:-$VISUAL}"
+  EDITOR="${EDITOR:-vi}"
+
+  colorR="\e[1;31m"
+  colorG="\e[1;32m"
+  colorY="\e[1;33m"
+  colorB="\e[1;34m"
+  colorM="\e[1;35m"
+  colorC="\e[1;36m"
+  colorW="\e[1;37m"
+  nocolor="\e[0m"
 }
 
-enter_build_directory() {
-  debug "building in $colorM$build_directory$nocolor"
-  mkdir -p "$build_directory" || die 'unable to make build directory'
-  cd "$build_directory"       || die 'unable to change to build directory'
+source_config() {
+  if [[ -r "$user_config" ]]; then
+    debug "sourcing user configuration from $colorM$user_config$nocolor"
+    source "$user_config"
+  fi
+}
+
+setup_colors() {
+  if $disable_color || [[ ! -t 1 ]]; then
+    colorR=''
+    colorG=''
+    colorY=''
+    colorB=''
+    colorM=''
+    colorC=''
+    colorW=''
+    nocolor=''
+
+    makepkg_options+=' --nocolor'
+  fi
 }
 # }}}
 
 # Search {{{
-#
-# Perform an AUR search based on $arguments[]. Returns 1 if we're not
-# searching.
-#
-##
 perform_search() {
-  [[ "$opmode" == 'search' ]] || return 1
-
   set -- "${arguments[@]}"
 
   debug "searching for $colorG$*$nocolor (mode: $colorG$search_mode$nocolor)"
@@ -333,7 +337,7 @@ perform_search() {
 print_search() {
   local name version description outofdate ood
 
-  while IFS='|' read -r name version description _ outofdate _; do
+  while IFS='|' read -r name version description _ outofdate; do
     (( "$outofdate" )) && ood="$colorR[out of date]$nocolor"
 
     printf "${colorM}aur/$colorW$name $colorG$version$nocolor $ood\n"
@@ -344,7 +348,7 @@ print_search() {
 print_info() {
   local name version description url outofdate ood='No'
 
-  while IFS='|' read -r name version description url outofdate _; do
+  while IFS='|' read -r name version description url outofdate; do
     (( "$outofdate" )) && ood="${colorR}Yes$nocolor"
 
     printf "${colorW}Repository  : ${colorM}aur$nocolor\n"
@@ -358,14 +362,7 @@ print_info() {
 # }}}
 
 # Add available upgrades {{{
-#
-# Adds any available upgrades to the front of the $arguments[] array.
-# Returns 1 if we're not processing upgrades.
-#
-##
 add_available_upgrades() {
-  [[ "$opmode" == 'upgrade' ]] || return 1
-
   info 'Starting AUR upgrade...'
   arguments=( $(available_upgrades) "${arguments[@]}" )
 
@@ -385,7 +382,7 @@ available_upgrades() {
 
   while IFS='|' read -r name versN _; do
     if is_devel "$name"; then
-      $devels && output_upgrade "$name" "development package"
+      $devels && output_upgrade "$name" 'development package'
       continue
     fi
 
@@ -413,14 +410,7 @@ output_upgrade() {
 # }}}
 
 # Resolve dependencies {{{
-#
-# Resolves dependencies for $arguments[] and places them in the
-# $dependencies[] array. Returns 1 if we're not resolving dependencies.
-#
-##
 resolve_dependencies() {
-  $resolve_dependencies || return 1
-
   info 'Resolving dependencies...'
   create_temp_directory
   resolve "${arguments[@]}"
@@ -468,13 +458,6 @@ source_pkgbuild() {
 # }}}
 
 # Setup targets {{{
-#
-# For each package in the $dependencies[] and $arguments[] arrays,
-# ensure they are available in the AUR, handle ignored packages, and
-# populate the $targets[], $target_versions[], and $target_deps[] arrays
-# for later processing.
-#
-###
 setup_targets() {
   local name version versions
 
@@ -519,14 +502,8 @@ setup_targets() {
 # }}}
 
 # Process targets {{{
-#
-# For each entry in the $targets[] array, download, build, or install it
-# based on the current sync_mode. Uses $target_deps[] to know if the
-# package is a dependency or not.
-#
-###
 process_targets() {
-  local name
+  local name ret=0
 
   set -- "${targets[@]}"
 
@@ -543,6 +520,7 @@ process_targets() {
       debug "downloading $colorG$name$nocolor to filesystem"
 
       if ! taurball "$name" > "${name}.tar.gz"; then
+        ret=1
         warn "$name: failed to retrieve aur sources"
         continue
       fi
@@ -550,13 +528,22 @@ process_targets() {
       debug "extracting $colorG$name$nocolor directly"
 
       if ! taurball "$name" | tar xfz -; then
-        warn "$name: failed to retrieve aur sources"
-        continue
+        if (( ${target_deps[$name]} )); then
+          die "dependency package $name failed to download, aborting"
+        else
+          ret=1
+          warn "package $name failed download, skipping"
+          continue
+        fi
       fi
 
       build_target "$name" && discard_sources "$name"
     fi
   done
+
+  debug "processing complete, returning $colorG$ret$nocolor"
+
+  return $ret
 }
 
 build_target() {
@@ -570,12 +557,12 @@ build_target() {
 
   if [[ -f "/etc/customizepkg.d/$name" ]]; then
     info 'Calling customizepkg...'
+    debug "executing ${colorY}customizepkg --modify$nocolor"
     customizepkg --modify || warn "customizepkg returned non-zero ($?)"
   fi
 
   if prompt_to_edit "$name" './PKGBUILD' 'building'; then
     if (( ${target_deps[$name]} )); then
-      debug "executing $colorY$makepkg $makepkg_options --asdeps$nocolor"
       buildpkg --asdeps || die "dependency package $name failed to build, aborting"
     else
       buildpkg || { ret=1; warn "package $name failed to build, skipping"; }
@@ -616,16 +603,14 @@ declare -a targets
 declare -A target_versions # name->version
 declare -A target_deps     # name->is-dep?
 
-set_defaults "$@"
-source_config
+initialize "$@"
 
-[[ ! -t 1 ]] && set_no_color
+if searching; then
+  perform_search
+else
+  upgrading && add_available_upgrades
+  resolving && resolve_dependencies
 
-parse_options "$@"
-
-perform_search || {
-  add_available_upgrades
-  resolve_dependencies
   setup_targets
   process_targets
-}
+fi
