updated on Sat Oct 18 00:00:20 UTC 2014

diff --git a/linux-next-git/PKGBUILD b/linux-next-git/PKGBUILD
--- a/linux-next-git/PKGBUILD
+++ b/linux-next-git/PKGBUILD
@@ -6,7 +6,7 @@
 pkgbase=linux-next-git
 pkgname=("${pkgbase}" "${pkgbase}-headers" "${pkgbase}-docs")
 _srcname=linux-next
-pkgver=next.20141015
+pkgver=next.20141017
 pkgrel=1
 arch=('i686' 'x86_64')
 url="http://www.kernel.org/"
@@ -74,7 +74,7 @@ prepare() {
     msg "Applying patches..."
     for i in "${_kernel_patches_dir}"/*; do
       [[ ${i##*/} =~ .*\.patch$ ]] && msg "Applying ${i##*/}..." && \
-      patch -Np1 -i "$i" || (error "Applying ${i##*/} failed" && return 1)
+      git apply "$i" || (error "Applying ${i##*/} failed" && return 1)
       msg "---"
     done
   fi
