updated on Thu Oct 16 00:00:27 UTC 2014

diff --git a/linux-next-git/PKGBUILD b/linux-next-git/PKGBUILD
--- a/linux-next-git/PKGBUILD
+++ b/linux-next-git/PKGBUILD
@@ -5,8 +5,8 @@
 pkgbase=linux-next-git
 pkgname=("${pkgbase}" "${pkgbase}-headers" "${pkgbase}-docs")
 _srcname=linux-next
-pkgver=next.20141014
-pkgrel=1
+pkgver=next.20141015
+pkgrel=2
 arch=('i686' 'x86_64')
 url="http://www.kernel.org/"
 license=('GPL2')
@@ -32,17 +32,25 @@ pkgver() {
 }
 
 #######
-# Set to e.g. menuconfig, xconfig or gconfig
+# Set to e.g. menuconfig, xconfig or gconfig and etc.
 #
 # For a full list of supported commands, please have a look
 # at "Configuration targets" section of `make help`'s output
 # or the help target in scripts/kconfig/Makefile
-# http://git.kernel.org/?p=linux/kernel/git/torvalds/linux.git;a=blob;f=scripts/kconfig/Makefile
+# https://kernel.org/doc/makehelp.txt
 #
 # If unset or set to an empty or space-only string, the
 # (manual) kernel configuration step will be skipped.
 #
 _config_cmd="${_config_cmd:-localyesconfig}"
+
+#######
+# Directory with patches
+# export _kernel_patches_dir="path"
+
+#######
+# Use local config (non empty -> yes)
+# _use_local_config=1
 
 prepare() {
   cd "${_srcname}"
@@ -53,8 +61,31 @@ prepare() {
     cat "${srcdir}/config" > ./.config
   fi
 
-  # don't run depmod on 'make install'. We'll do this ourselves in packaging
-  sed -i '2iexit 0' scripts/depmod.sh
+  if [ -n "${_use_local_config}" ]; then
+    [ -f /proc/config.gz ] && zcat /proc/config.gz > ./.config
+  fi
+
+
+  #################
+  # Apply patches
+  #################
+  if [[ -d "${_kernel_patches_dir}" ]]; then
+    echo "Applying patches..."
+    local i patches
+    for i in "${_kernel_patches_dir}"/*; do
+      i=${i##*/}
+      [[ $i =~ .*\.patch$ ]] && \
+	patches=("${patches[@]}" "${_kernel_patches_dir}/$i")
+      [[ ${i%.*} =~ .*\.patch$ ]] && \
+	patches=("${patches[@]}" "${_kernel_patches_dir}/${i%.*}")
+    done
+    shopt -s nullglob
+    for i in "${patches[@]}"; do
+      echo "Applying ${i##*/}..."
+      patch -Np1 -i "$i" || (error "Applying ${i##*/} failed" && return 1)
+    done
+    shopt -u nullglob
+  fi
 
   ###########################
   # Start the configuration
@@ -62,12 +93,14 @@ prepare() {
   msg "Updating configuration..."
   yes "" | make config > /dev/null
   if [[ -n ${_config_cmd// /} ]]; then
-    msg2 "Running make $_config_cmd..."
+    echo "Running make $_config_cmd..."
     make $_config_cmd
   else
     warning "Unknown config command: $_config_cmd"
-    exit 1
   fi
+
+  # don't run depmod on 'make install'. We'll do this ourselves in packaging
+  sed -i '2iexit 0' scripts/depmod.sh
 }
 
 build() {
@@ -77,7 +110,7 @@ build() {
 }
 
 package_linux-next-git() {
-  pkgdesc="The Linux kernel and modules (git version)"
+  pkgdesc="The Linux next kernel and modules (git version)"
   depends=('coreutils' 'linux-firmware' 'kmod' 'mkinitcpio>=0.7')
   optdepends=('crda: to set the correct wireless channels of your country')
   provides=("kernel26${_kernelname}=${pkgver}")
@@ -117,7 +150,7 @@ package_linux-next-git() {
     -i "${pkgdir}/etc/mkinitcpio.d/${pkgbase}.preset"
 
   # remove build and source links
-  rm -f "${pkgdir}"/lib/modules/${_kernver}/{source,build}
+  rm -f "${pkgdir}/lib/modules/${_kernver}"/{source,build}
   # remove the firmware
   rm -rf "${pkgdir}/lib/firmware"
   # gzip -9 all modules to save 100MB of space
@@ -235,8 +268,8 @@ package_linux-next-git-headers() {
 
   # copy in Kconfig files
   for i in $(find . -name "Kconfig*"); do
-    mkdir -p "${pkgdir}"/usr/lib/modules/${_kernver}/build/`echo ${i} | sed 's|/Kconfig.*||'`
-    cp ${i} "${pkgdir}/usr/lib/modules/${_kernver}/build/${i}"
+    mkdir -p "${pkgdir}/usr/lib/modules/${_kernver}/build/"$(echo "${i}" | sed 's|/Kconfig.*||')
+    cp "${i}" "${pkgdir}/usr/lib/modules/${_kernver}/build/${i}"
   done
 
   chown -R root.root "${pkgdir}/usr/lib/modules/${_kernver}/build"
@@ -255,7 +288,7 @@ package_linux-next-git-headers() {
   done
 
   # remove unneeded architectures
-  rm -rf "${pkgdir}"/usr/lib/modules/${_kernver}/build/arch/{alpha,arc,arm,arm26,arm64,avr32,blackfin,c6x,cris,frv,h8300,hexagon,ia64,m32r,m68k,m68knommu,metag,mips,microblaze,mn10300,openrisc,parisc,powerpc,ppc,s390,score,sh,sh64,sparc,sparc64,tile,unicore32,um,v850,xtensa}
+  rm -rf "${pkgdir}/usr/lib/modules/${_kernver}/build/arch/"{alpha,arc,arm,arm26,arm64,avr32,blackfin,c6x,cris,frv,h8300,hexagon,ia64,m32r,m68k,m68knommu,metag,mips,microblaze,mn10300,openrisc,parisc,powerpc,ppc,s390,score,sh,sh64,sparc,sparc64,tile,unicore32,um,v850,xtensa}
 }
 
 package_linux-next-git-docs() {
@@ -274,5 +307,3 @@ package_linux-next-git-docs() {
   # remove a file already in linux package
   rm -f "${pkgdir}/usr/lib/modules/${_kernver}/build/Documentation/DocBook/Makefile"
 }
-
-# vim:set ts=8 sts=2 sw=2 et:
