updated on Thu May 31 11:00:14 UTC 2012

diff --git a/openvswitch-git/openvswitch-git.init b/openvswitch-git/openvswitch-git.init
--- a/openvswitch-git/openvswitch-git.init
+++ b/openvswitch-git/openvswitch-git.init
@@ -7,8 +7,184 @@ OVS_DB_PID_FILE=/var/run/openvswitch/ovsdb-server.pid
 OVS_VS_PID_FILE=/var/run/openvswitch/ovs-vswitchd.pid
 OVS_BC_PID_FILE=/var/run/openvswitch/ovs-brcompatd.pid
 
+handle_modules() {
+    local i kernversion kver loaded=0 moderr action modules
+
+    # This function checks which openvswitch modules should be used on
+    # your system. It is necessary to do this check because openvswitch
+    # only became a part of the mainline Linux kernel in kernel version
+    # 3.3. Before kernel 3.3 it was required to build modules manually
+    # or semi-automatically with dkms. Those modules were then called
+    # 'openvswitch_mod' and 'brcompat_mod'.
+    #     With kernel 3.3 the name of supplied openvswitch module
+    # changed to 'openvswitch'. However, the brcompat module is not
+    # included in the mainline kernel nor will it ever be. [1]
+    #
+    # This means there are a number of options for any system:
+    # 1) It runs kernel >= 3.3 and the in-kernel openvswitch module;
+    # 2) It runs kernel >= 3.3 and aside from the in-kernel openvswitch module
+    #    it also has a separately built openvswitch module, built by dkms or
+    #    from git, and henceforth maybe also the brcompat module exists for
+    #    this kernel;
+    # 3) It runs kernel < 3.3 and already has the openvswitch_mod and
+    #     brcompat_mod modules built by the openvswitch(-git) dkms routine;
+    # 4) it has kernel < 3.3 but no modules yet;
+    # 5) any other option.
+
+    # How to check which is currently the case? First thing is to get the
+    # version of the current kernel from /proc/version and, from the second
+    # word, only keep the part before the hyphen. This would result in
+    # something like "3.3.3", "2.6.12" etc.
+    kernversion=($(</proc/version))
+    kver=${kernversion[2]%%-*}
+
+    # First check if we already have loaded a module. The fastest way to check
+    # probably is by doing some bitmasking:
+    # 1 - openvswitch_mod
+    # 2 - brcompat_mod
+    # 4 - openvswitch
+    # 8 - brcompat
+    for i in $(awk '{ if ($1 == "openvswitch_mod") print "1"; \
+                      if ($1 == "brcompat_mod") print "2"; \
+                      if ($1 == "openvswitch") print "4"; \
+                      if ($1 == "brcompat") print "8"; }' /proc/modules); do
+        (( loaded += i ))
+    done; unset i
+
+    # Maybe we can do something with the value in $loaded depending on $1
+    # Value  Means
+    #   0    Nothing is loaded, try to load both, this is where we use $kver;
+    #   1    Only openvswitch_mod is loaded - try to load brcompat_mod or set moderr=2;
+    #   2    Only brcompat_mod is loaded - this should never happen - return 254.
+    #   3    openvswitch_mod and brcompat_mod are already loaded, return 0;
+    #   4    Only openvswitch is loaded - try to load brcompat or set moderr=8;
+    #   8    Only brcompat is loaded - this should never happen - return 254.
+    #  12    openvswitch and brcompat are both loaded, return 0.
+    # other  Something odd is going on, return 255
+    case $loaded in
+        0)  # we need to both modules if action is load, else leave silently
+            [[ $1 == "unload" ]] && return 0
+
+            if [[ ${kver} == 2.4* ]] ; then
+
+                # this is kernel 2.4: fail
+
+                moderr=24
+
+            elif [[ ${kver} == 2.6* ]] || \
+              [[ ${kver:0:1} == "3" && ${kver:2:1} -le 2 ]] ; then
+
+                # this is kernel 2.6 or =< 3.2
+
+                if ! modprobe openvswitch_mod &>/dev/null; then
+                    # could not load openvswitch_mod; bail
+                    moderr=1
+                elif ! modprobe brcompat_mod &>/dev/null; then
+                    # could not load brcompat_mod; bail
+                    moderr=2
+                else
+                    # if we didn't fail, we're done.
+                    return 0
+                fi
+
+            elif [[ ${kver:0:1} == "3" && ${kver:2:1} -ge 3 ]]; then
+
+                # This is kernel 3.3 or higher
+
+                if ! modprobe openvswitch &>/dev/null; then
+                    # could not load openvswitch; bail
+                    moderr=4
+                elif ! modprobe brcompat &>/dev/null; then
+                    # could not load brcompat; bail
+                    moderr=8
+                else
+                    # if we didn't fail, we're done.
+                    return 0
+                fi
+            else
+                moderr=255
+            fi
+
+              ;;
+
+
+        1)    if [[ $1 == "load" ]]; then
+                  if modprobe brcompat_mod &>/dev/null; then
+                      return 0
+                  else
+                      moderr=2
+                  fi
+              elif [[ $1 == "unload" ]] ;then
+                  if rmmod openvswitch_mod &>/dev/null; then
+                      return 0
+                  else
+                      moderr=1
+                  fi
+              fi
+              ;;
+
+        4)    if [[ $1 == "load" ]]; then
+                  if modprobe brcompat &>/dev/null; then
+                      return 0
+                  else
+                      moderr=8
+                  fi
+              elif [[ $1 == "unload" ]]; then
+                  if rmmod openvswitch &>/dev/null; then
+                      return 0
+                  else
+                      moderr=4
+                  fi
+              fi
+              ;;
+
+        3|12) if [[ $1 == "load" ]]; then
+                  return 0
+              elif [[ $1 == "unload" && $loaded == 3 ]]; then
+                  if ! rmmod brcompat_mod &>/dev/null; then
+                      moderr=2
+                  elif ! rmmod openvswitch_mod &>/dev/null; then
+                      moderr=1
+                  else
+                      return 0
+                  fi
+              elif [[ $1 == "unload" && $loaded == 12 ]]; then
+                  if ! rmmod brcompat &>/dev/null; then
+                      moderr=8
+                  elif ! rmmod openvswitch &>/dev/null; then
+                      moderr=4
+                  else
+                      return 0
+                  fi
+              fi
+              ;;
+
+        2|8)  moderr=254 ;;
+        *)    moderr=255 ;;
+    esac
+
+    # If we're still here something has gone wrong. Let's parse $moderr
+    case $moderr in
+        1) stat_append " ERROR: could not $1 openvswitch_mod" ;;
+        2) stat_append " ERROR: could not $1 brcompat_mod" ;;
+        4) stat_append " ERROR: could not $1 openvswitch" ;;
+        8) stat_append " ERROR: could not $1 brcompat" ;;
+       24) stat_append ' ERROR: kernel 2.4 is not supported' ;;
+      254) stat_append ' ERROR: brcompat_mod or brcompat is already loaded but openvswitch is not, this should never happen' ;;
+      255) stat_append ' ERROR: loader returned some strange value so something weird is happening' ;;
+        *) stat_append ' ERROR: unknown error_fu' ;;
+    esac
+    stat_append ' - bailing!'
+    stat_die
+}
+
 case "$1" in
   start)
+    stat_busy "Loading openvswitch kernel modules"
+    handle_modules load
+    stat_done
+
+    [[ ! -d /var/run/openvswitch ]] && mkdir /var/run/openvswitch
 
     stat_busy "Starting OpenVSwitch DB server"
     /usr/sbin/ovsdb-server /etc/openvswitch/ovs-vswitchd.conf.db \
@@ -37,7 +213,7 @@ case "$1" in
     fi
 
     stat_busy "Starting openvswitch bridge compatibility"
-    ovs-brcompatd --pidfile=${OVS_BC_PID_FILE} --detach 
+    ovs-brcompatd --pidfile=${OVS_BC_PID_FILE} --detach
     if [ $? -gt 0 ]; then
       stat_fail
     else
@@ -75,7 +251,11 @@ case "$1" in
     else
       stat_done
     fi
-    rm_daemon openvswitch 
+    rm_daemon openvswitch
+
+    stat_busy "Unloading openvswitch kernel modules"
+    handle_modules unload
+    stat_done
     ;;
   restart)
     $0 stop
diff --git a/openvswitch-git/openvswitch-git.install b/openvswitch-git/openvswitch-git.install
--- a/openvswitch-git/openvswitch-git.install
+++ b/openvswitch-git/openvswitch-git.install
@@ -1,13 +1,5 @@
-
-pre_install() {
-  groupadd -r ovs
-}
-
-post_install() {
-  if [ ! -f /etc/openvswitch/ovs-vswitchd.conf.db ]; then
-    ovsdb-tool create /etc/openvswitch/ovs-vswitchd.conf.db /usr/share/openvswitch/vswitch.ovsschema
-  fi
-
+ovs_dkms() {
+  set -v
   echo "==> Building kernel modules with dkms"
   dkms add -m openvswitch -v ${1%-*}
   dkms build -m openvswitch -v ${1%-*}
@@ -18,14 +10,53 @@ post_install() {
   echo "    For more information refer to:"
   echo "    http://openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=blob;f=INSTALL.bridge;hb=HEAD"
   echo "==> Done"
+  set +v
 }
 
+
+pre_install() {
+  groupadd -r ovs
+}
+
+post_install() {
+  if [ ! -f /etc/openvswitch/ovs-vswitchd.conf.db ]; then
+    ovsdb-tool create /etc/openvswitch/ovs-vswitchd.conf.db /usr/share/openvswitch/vswitch.ovsschema
+  fi
+
+  ovs_dkms $1
+}
+
+pre_upgrade() {
+  if [[ -n $2 ]]; then
+    echo "==> Pre_upgrade: removing a possible previous version of openvswitch kernel modules"
+    echo "    If this fails then that's ok"
+    set -v
+    dkms remove --all openvswitch/${2%-*} || true
+    set +v
+  fi
+}
+
+post_upgrade() {
+  if [[ -n $2 ]]; then
+    echo "==> post_upgrade: removing a possible previous version of openvswitch kernel modules"
+    echo "    If this fails then that's ok"
+    set -v
+    dkms remove --all openvswitch/${2%-*} || true
+    set +v
+    echo
+  fi
+  ovs_dkms $1
+}
+
+
 pre_remove() {
-  dkms remove -m openvswitch -v ${1%-*} --all
+  set -v
+  dkms remove --all openvswitch/${1%-*} --all || true
+  set +v
 }
 
 post_remove() {
-  groupdel ovs
+  groupdel ovs || true
 }
 
 # vim:set ts=2 sw=2 et:
diff --git a/openvswitch/openvswitch.install b/openvswitch/openvswitch.install
--- a/openvswitch/openvswitch.install
+++ b/openvswitch/openvswitch.install
@@ -1,4 +1,5 @@
 ovs_dkms() {
+  set -v
   echo "==> Building kernel modules with dkms"
   dkms add -m openvswitch -v ${1%-*}
   dkms build -m openvswitch -v ${1%-*}
@@ -9,6 +10,7 @@ ovs_dkms() {
   echo "    For more information refer to:"
   echo "    http://openvswitch.org/cgi-bin/gitweb.cgi?p=openvswitch;a=blob;f=INSTALL.bridge;hb=HEAD"
   echo "==> Done"
+  set +v
 }
 
 
@@ -25,18 +27,32 @@ post_install() {
 }
 
 pre_upgrade() {
-  echo "==> Removing a possible previous version of openvswitch kernel modules"
-  echo "    If this fails then that's ok"
-  dkms remove -m openvswitch -v ${2%-*} --all || true
+  if [[ -n $2 ]]; then
+    echo "==> Pre_upgrade: removing a possible previous version of openvswitch kernel modules"
+    echo "    If this fails then that's ok"
+    set -v
+    dkms remove --all openvswitch/${2%-*} || true
+    set +v
+  fi
 }
 
 post_upgrade() {
+  if [[ -n $2 ]]; then
+    echo "==> post_upgrade: removing a possible previous version of openvswitch kernel modules"
+    echo "    If this fails then that's ok"
+    set -v
+    dkms remove --all openvswitch/${2%-*} || true
+    set +v
+    echo
+  fi
   ovs_dkms $1
 }
 
 
 pre_remove() {
-  dkms remove -m openvswitch -v ${1%-*} --all || true
+  set -v
+  dkms remove --all openvswitch/${1%-*} --all || true
+  set +v
 }
 
 post_remove() {
