updated on Wed Jul  2 00:03:13 UTC 2014

diff --git a/ankama-transition/PKGBUILD b/ankama-transition/PKGBUILD
--- a/ankama-transition/PKGBUILD
+++ b/ankama-transition/PKGBUILD
@@ -1,31 +1,35 @@
 # Maintainer: Yaohan Chen <yaohan.chen@gmail.com>
 pkgname=ankama-transition
-pkgver=3.9.1
-pkgrel=5
+pkgver=3.9.2
+pkgrel=1
 pkgdesc="Updater for Ankama games Dofus and Wakfu"
 arch=('i686' 'x86_64')
 url="http://www.ankama.com"
 license=('custom')
 depends=('qt4' 'polkit' 'openssl')
-source=('http://dl.ak.ankama.com/games/linux/ankama-transition.tar.gz'
-        'transition.sh'
-        'transition.ici')
-        # transition.ici is copied from the Dofus package
-md5sums=('33683756fbe9ea7dd0b33b2df86d1125'
-         '45cf6884aba12f2a9a024ea62f57854c'
-         'fe8f58dafc90cfd6465eb5fb824223d2')
-install='ankama-transition.install'
+# The 32-bit transition in ankama-transition will fail with error "mandatory plugin core",
+# so we use the transition bundled in Dofus installers
+source=('DofusInstall-amd64.tar.gz::http://download.dofus.com/full/linux/x64'
+        'DofusInstall-x86.tar.gz::http://download.dofus.com/full/linux/'
+        'http://dl.ak.ankama.com/games/linux/ankama-transition.tar.gz'
+        'transition.sh')
+md5sums=('9c34ea79de9b325af4b06ddf2d9c4c2a'
+         '9d8262f579844d6b8f025c417a922ac1'
+         '33683756fbe9ea7dd0b33b2df86d1125'
+         '45cf6884aba12f2a9a024ea62f57854c')
+# Skip this block if PKGBUILD is sourced by updpkgsums (pstree is used for this check,
+# and if not available, this check is skipped)
+if ! ( command -v pstree >/dev/null 2>&1 && \
+  pstree --show-parents $$ | grep -q updpkgsums ) ; then
+  # Remove source and md5sum for the wrong arch
+  if [ "$CARCH" == "x86_64" ];then
+    unset source[1] md5sums[1]
+  elif [ "$CARCH" == 'i686' ]; then
+    unset source[0] md5sums[0]
+  fi
+fi
 
-_archdir() {
-  case "$CARCH" in
-    'i686')
-      echo "$srcdir/x86"
-      ;;
-    'x86_64')
-      echo "$srcdir/amd64"
-      ;;
-  esac
-}
+install='ankama-transition.install'
 
 prepare() {
   sed -i 's:$$${installation_path}:/opt/ankama:' \
@@ -34,11 +38,14 @@ prepare() {
 
 package() {
   cd "$srcdir/"
-  cp -r 'etc' 'usr' "$(_archdir)/opt" "$pkgdir/"
+  cp -r 'etc' 'usr' "$pkgdir/"
+
   _installdir="$pkgdir/opt/ankama/transition"
+  install -d "$_installdir"
+  cp -r Dofus/transition/* "$_installdir"
   chgrp -R games "$_installdir"
   chmod -R g+w "$_installdir"
-  install -Dm644 transition.ici "$_installdir"
+
   install -Dm755 'transition.sh' "$pkgdir/usr/bin/transition"
   install -Dm644 'opt/ankama/transition/licences/README.txt' \
           "$pkgdir/usr/share/licenses/ankama-transition/licenses.txt"
diff --git a/lastpass/PKGBUILD b/lastpass/PKGBUILD
--- a/lastpass/PKGBUILD
+++ b/lastpass/PKGBUILD
@@ -49,98 +49,94 @@ md5sums=('7a356a98a73c340338faba4a9ea95823'
 
 # Custom functions for makepkg
 _note() {
-  printf "${RED}==>${ALL_OFF}${RED} NOTE: $1${ALL_OFF}\n"
+    printf "${RED}==>${ALL_OFF}${RED} NOTE: $1${ALL_OFF}\n"
 }
 
 _read_msg2() {
-  read -p "${BLUE}  ->${YELLOW} $1 ${ALL_OFF}${BOLD}$2${ALL_OFF}"
+    read -p "${BLUE}  ->${YELLOW} $1 ${ALL_OFF}${BOLD}$2${ALL_OFF}"
 }
 
 # 64-bit?
 if [ "$CARCH" = 'x86_64' ]; then
-  _64=64
+    _64=64
 fi
 
 prepare() {
-  # Since we're installing to $HOME in .install, we need checks such as this to
-  # see whether some clever guy is building with "--asroot"
-  if [ "$USER" = 'root' ]; then
-    _note "Makepkg is running as root. The extensions will not be available to a regular user."
-    _read_msg2 "Continue?" "(Y/n): "
+    # Since we're installing to $HOME in .install, we need checks such as this to
+    # see whether some clever guy is building with "--asroot"
+    if [ "$USER" = 'root' ]; then
+        _note "Makepkg is running as root. The extensions will not be available to a regular user."
+        _read_msg2 "Continue?" "(Y/n): "
 
-    if [[ "$REPLY" != [yY] ]]; then
-      error "Aborted by user! Exiting..."
-      exit 1
+        if [[ "$REPLY" != [yY] ]]; then
+            error "Aborted by user! Exiting..."
+            exit 1
+        fi
     fi
-  fi
 
-  # Write extension versions and user vars to .install
-  sed -e "s/_ffver=[^ ]*/_ffver=$_ffver/" \
-      -e "s/_opver=[^ ]*/_opver=$_opver/" \
-      -e "s/_user=[^ ]*/_user=$USER/" \
-      -i "$startdir"/$pkgname.install
+    # Write extension versions and user vars to .install
+    sed -e "s/_ffver=[^ ]*/_ffver=$_ffver/" \
+        -e "s/_opver=[^ ]*/_opver=$_opver/" \
+        -e "s/_user=[^ ]*/_user=$USER/" \
+        -i "$startdir"/$pkgname.install
 
-  # The Firefox profile(s) might not exist
-  if [ -f ~/.mozilla/firefox/profiles.ini ]; then
-    _ffprofile=$(sed -n 's/^Path=//p' ~/.mozilla/firefox/profiles.ini | grep default || true)
-    if [ $_ffprofile ]; then
-      sed "s,_mozilla=[^ ]*,_mozilla=\$_home/.mozilla/firefox/$_ffprofile/," \
-          -i "$startdir"/$pkgname.install
-    else  # Default naming
-      sed "s,_mozilla=[^ ]*,_mozilla=\$_home/.mozilla/firefox/lastpass.default/," \
-          -i "$startdir"/$pkgname.install
+    # Attempt to use default Firefox profile
+    _ffprofile=$(sed -n 's/^Path=//p' ~/.mozilla/firefox/profiles.ini |& grep default || true)
+    if [ $_ffprofile ] && [ -d ~/.mozilla/firefox/$_ffprofile/ ]; then
+        sed "s,_mozilla=[^ ]*,_mozilla=\$_home/.mozilla/firefox/$_ffprofile/," \
+            -i "$startdir"/$pkgname.install
+    else
+        sed "s,_mozilla=[^ ]*,_mozilla=\$_home/.mozilla/firefox/lastpass.default/," \
+            -i "$startdir"/$pkgname.install
     fi
-  else  # Leave empty
-    sed "s/_mozilla=[^ ]*/_mozilla=-/" -i "$startdir"/$pkgname.install
-  fi
 }
 
 _chrome_package() {
-  # Install to single place for linking
-  install -Dm644 lpchrome_linux_$_chromver.crx "$pkgdir"/usr/share/lastpass/lpchrome_linux_$_chromver.crx
-  install -Dm755 nplastpass$_64 "$pkgdir"/etc/opt/chrome/native-messaging-hosts/nplastpass$_64
+    # Install to single place for linking
+    install -Dm644 lpchrome_linux_$_chromver.crx "$pkgdir"/usr/share/lastpass/lpchrome_linux_$_chromver.crx
+    install -Dm755 nplastpass$_64 "$pkgdir"/etc/opt/chrome/native-messaging-hosts/nplastpass$_64
 
-  # 64-bit?
-  sed "s,/nplastpass,/nplastpass$_64," -i com.lastpass.nplastpass.json
+    # 64-bit?
+    sed "s,/nplastpass,/nplastpass$_64," -i com.lastpass.nplastpass.json
 
-  # JSONs
-  for i in opt/chrome chromium chromium-dev; do
-    # Messaging host
-    install -Dm644 com.lastpass.nplastpass.json "$pkgdir"/etc/$i/native-messaging-hosts/com.lastpass.nplastpass.json
+    # JSONs
+    for i in opt/chrome chromium chromium-dev; do
+        # Messaging host
+        install -Dm644 com.lastpass.nplastpass.json "$pkgdir"/etc/$i/native-messaging-hosts/com.lastpass.nplastpass.json
 
-    # Allow silent installation since Chrome v21: http://www.chromium.org/administrators/policy-list-3#ExtensionInstallSources
-    install -Dm644 lastpass_policy.json "$pkgdir"/etc/$i/policies/managed/lastpass_policy.json
-  done
+        # Allow silent installation since Chrome v21: http://www.chromium.org/administrators/policy-list-3#ExtensionInstallSources
+        install -Dm644 lastpass_policy.json "$pkgdir"/etc/$i/policies/managed/lastpass_policy.json
+    done
 }
 
 _firefox_package() {
-  # Extension + profiles.ini go to $HOME, so do this in .install
-  for i in lp_linux_$_ffver.xpi profiles.ini; do
-    install -Dm644 $i "$pkgdir"/usr/share/lastpass/$i
-  done
+    # Extension + profiles.ini go to $HOME, so do this in .install
+    for i in lp_linux_$_ffver.xpi profiles.ini; do
+        install -Dm644 $i "$pkgdir"/usr/share/lastpass/$i
+    done
 
-  # Binary plugin
-  install -Dm755 libnplastpass$_64.so "$pkgdir"/usr/lib/mozilla/plugins/libnplastpass$_64.so
+    # Binary plugin
+    install -Dm755 libnplastpass$_64.so "$pkgdir"/usr/lib/mozilla/plugins/libnplastpass$_64.so
 }
 
 _opera_package() {
-  # Same for Operas
-  install -m644 lastpass-$_opver.oex {pref,widget}s.dat "$pkgdir"/usr/share/lastpass/
+    # Same for Operas
+    install -m644 lastpass-$_opver.oex {pref,widget}s.dat "$pkgdir"/usr/share/lastpass/
 
-  # Binary plugin
-  for i in opera opera-next; do
-    install -d "$pkgdir"/usr/lib/$i/plugins/
-    ln -s /usr/lib/mozilla/plugins/libnplastpass$_64.so "$pkgdir"/usr/lib/$i/plugins/libnplastpass$_64.so
-  done
+    # Binary plugin
+    for i in opera opera-next; do
+        install -d "$pkgdir"/usr/lib/$i/plugins/
+        ln -s /usr/lib/mozilla/plugins/libnplastpass$_64.so "$pkgdir"/usr/lib/$i/plugins/libnplastpass$_64.so
+    done
 }
 
 package() {
-  msg2 "Installing for Google Chromes/Chromiums"
-  _chrome_package
+    msg2 "Installing for Google Chromes/Chromiums"
+    _chrome_package
 
-  msg2 "Installing for Mozilla Firefoxes"
-  _firefox_package
+    msg2 "Installing for Mozilla Firefoxes"
+    _firefox_package
 
-  msg2 "Installing for Operas"
-  _opera_package
+    msg2 "Installing for Operas"
+    _opera_package
 }
