updated on Sat Jul 23 16:01:04 UTC 2011

diff --git a/grub-gfx/PKGBUILD b/grub-gfx/PKGBUILD
--- a/grub-gfx/PKGBUILD
+++ b/grub-gfx/PKGBUILD
@@ -1,105 +1,133 @@
-# Maintainer: Douglas Soares de Andrade <dsandrade@gmail.com>
+# Contributor: Ronald van Haren <ronald.archlinux.org>
+# Contributor: Douglas Soares de Andrade <dsandrade@gmail.com>
 # Contributor: judd <jvinet@zeroflux.org>
 # Contributor: Mario A. Vazquez
 # Contributor: Jerzy Goca <juras256@epf.pl>
+# Contributor: Keshav P R
 
-pkgname=grub-gfx
+_pkgname="grub"
+pkgname="${_pkgname}-gfx"
 pkgver=0.97
-pkgrel=11
+pkgrel=12
 pkgdesc="A GNU multiboot boot loader"
 arch=('i686' 'x86_64')
 license=('GPL')
-url="http://www.gnu.org/software/grub/"
+url="http://www.gnu.org/software/grub/grub-legacy.en.html"
+# groups=('base')
+makedepends=()
 depends=('ncurses')
-makedepends=('automake>=1.10' 'autoconf>=2.61' 'patch')
-conflicts=('grub')
-provides=('grub')
-source=(ftp://alpha.gnu.org/gnu/grub/grub-$pkgver.tar.gz \
-        menu.lst install-grub grub-0.97-graphics.patch \
-        splash.xpm.gz grub-inode-size.patch \
-        040_all_grub-0.96-nxstack.patch \
-        05-grub-0.97-initrdaddr.diff ext4.patch \
-        i2o.patch special-devices.patch more-raid.patch intelmac.patch)
+conflicts=('grub' 'grub-legacy')
+provides=('grub' 'grub-legacy')
 backup=('boot/grub/menu.lst')
-install=grub-gfx.install
+install="${pkgname}.install"
 
-build() {
-  cd $startdir/src/grub-$pkgver
+source=("ftp://alpha.gnu.org/gnu/grub/grub-${pkgver}.tar.gz"
+        'menu.lst'
+        'install-grub'
+        '040_all_grub-0.96-nxstack.patch'
+        '05-grub-0.97-initrdaddr.diff'
+        'i2o.patch'
+        'special-devices.patch'
+        'more-raid.patch'
+        'intelmac.patch'
+        'grub-inode-size.patch'
+        'ext4.patch'
+        'grub-0.97-graphics.patch'
+        'objcopy-absolute.patch')
 
-  #set destination architecture here
-  #DESTARCH="i686"
-  DESTARCH="x86_64"
-
-  # graphics patch
-  patch -p1 < ../grub-0.97-graphics.patch || return 1
-
-  # optimizations break the build -- disable them
-  # adding special devices to grub, patches are from fedora
-  patch -Np1 -i ../special-devices.patch || return 1
-  patch -Np1 -i ../i2o.patch || return 1
-  patch -Np1 -i ../more-raid.patch || return 1
-  patch -Np1 -i ../intelmac.patch || return 1
-  patch -Np1 -i ../grub-inode-size.patch || return 1
-  patch -Np1 -i ../ext4.patch || return 1
-
-  # correcting problems for new wersion of autotools
-  sed -i -e'/^AC_PROG_CC/ a\AM_PROG_CC_C_O\ ' configure.ac
-  sed -i -e'/^AC_PROG_CC/ a\AM_PROG_AS\ ' configure.ac
-  aclocal
-  autoconf
-  automake
-
-  #arch64 fixes for static build
-  if [ "$CARCH" = "x86_64" ]; then
-    echo "this package has to be build on i686, won't compile on x86_64"
-    sleep 5
-  else
-    if [ "$DESTARCH" = "x86_64" ]; then
-      # patch from gentoo for fixing a segfault
-      patch -Np1 -i ../040_all_grub-0.96-nxstack.patch || return 1
-      # patch from frugalware to make it boot when more than 2GB ram installed
-      patch -Np1 -i ../05-grub-0.97-initrdaddr.diff || return 1
-      CFLAGS="-static" ./configure --prefix=/usr --bindir=/bin --sbindir=/sbin
-    else
-      CFLAGS= ./configure --prefix=/usr --bindir=/bin --sbindir=/sbin
-    fi
-  fi
-
-  CFLAGS= make || return 1
-  make DESTDIR=$startdir/pkg install
-  install -D -m644 ../menu.lst $startdir/pkg/boot/grub/menu.lst
-  install -D -m755 ../install-grub $startdir/pkg/sbin/install-grub
-
-  # symlink for compatibility with the <=0.7 installer
-  mkdir -p $startdir/pkg/usr/share
-  ln -s ../lib/grub $startdir/pkg/usr/share/grub
-
-  # splashimage xpm install
-  install -D -m644 $startdir/splash.xpm.gz $startdir/pkg/boot/grub/splash.xpm.gz
-
-  # Create a symlink to people that was using it
-  pushd $startdir/pkg/boot/grub/
-  ln -s splash.xpm.gz arch.xpm.gz
-  popd
-
-  rm -f $pkgdir/usr/share/info/dir || return 1
-
-  if [ "$DESTARCH" = "x86_64" ]; then
-    # fool makepkg into building a x86_64 package
-    export CARCH="x86_64"
-  fi
-
-}
 md5sums=('cd3f3eb54446be6003156158d51f4884'
-         '58cfec4abda85307f779147ab9a6be48'
+         'a2098dc41fc3cb13e53179de2979d088'
          '3182c4ae4963a16930bc772bba89dacf'
-         '12f043616b51ce2ba82e46c9186a528d'
-         '342f59f24cf5de5f013eacda68e617eb'
-         'ada26cbc681907823cc4ff2a55b97866'
          'eb9d69c46af3a0667c1f651817d7f075'
          'ccd2d757e79e3a03dc19ede7391ed328'
-         '39e0f9a05b7e04aceb24fc7bc4893e3d'
          '826fdbf446067f9861baf9f6a69a4583'
          '49f6d4bcced0bc8bbcff273f3254bbfa'
          'f41f702014a064918d7afc6fc23baa6e'
-         '175dc6b9f4ab94e8056c3afb3e34460a')
+         '175dc6b9f4ab94e8056c3afb3e34460a'
+         '69c648d2b8d0965df70a74014424f31c'
+         '39e0f9a05b7e04aceb24fc7bc4893e3d'
+         '12f043616b51ce2ba82e46c9186a528d'
+         '64dd7824cd64e726ef091bc494417b1c')
+
+if [ "${CARCH}" == 'x86_64' ]; then
+    echo
+    makedepends=(${makedepends[@]} 'gcc-multilib' 'gcc-libs-multilib' 'lib32-glibc' 'binutils-multilib' 'libtool-multilib')
+fi
+
+build() {
+  
+  cd "${srcdir}/${_pkgname}-${pkgver}"
+  
+  # set destination architecture here
+  #DESTARCH="i686"
+  DESTARCH="x86_64"
+  
+  # graphics patch
+  patch -Np1 -i "${srcdir}/grub-0.97-graphics.patch"
+  
+  # optimizations break the build -- disable them
+  # adding special devices to grub, patches are from fedora
+  patch -Np1 -i "${srcdir}/special-devices.patch"
+  patch -Np1 -i "${srcdir}/i2o.patch"
+  patch -Np1 -i "${srcdir}/more-raid.patch"
+  patch -Np1 -i "${srcdir}/intelmac.patch"
+  
+  # Add support for bigger inode size to e2fs_stage1_5
+  patch -Np1 -i "${srcdir}/grub-inode-size.patch"
+  
+  # Add ext4 support
+  # http://www.mail-archive.com/bug-grub@gnu.org/msg11458.html
+  patch -Np1 -i "${srcdir}/ext4.patch"
+  
+  # Absolute objcopy configure patch, taken from grub-fedora
+  # http://git.kernel.org/?p=boot/grub-fedora/grub-fedora.git;a=blobdiff;f=acinclude.m4;h=1cf1d67c4d7ddde6c198eb4a056c61ba898abb9b;hp=86c3dccb9ad5477bfeb59f54ffddaedef82688d7;hb=f0e5e0d38fbda2276b539cf42d099b760a8d3135;hpb=85c2ac77fca4b7bcbeaab076c766fe34a31bfd74
+  patch -Np1 -i "${srcdir}/objcopy-absolute.patch"
+  
+  # correcting problems for new wersion of autotools
+  #sed -i -e'/^AC_PROG_CC/ a\AM_PROG_CC_C_O\ ' ./configure.ac || true
+  #sed -i -e'/^AC_PROG_CC/ a\AM_PROG_AS\ ' ./configure.ac || true
+  #aclocal
+  #autoconf
+  #automake
+  
+  # Stupid workaround, incase objcopy-absolute.patch fails
+  #sed 's|grub_cv_prog_objcopy_absolute=no|grub_cv_prog_objcopy_absolute=yes|g' -i ./configure
+  
+  # arch64 fixes for static build
+  #if [ "${CARCH}" == 'x86_64' ]; then
+    #echo "this package has to be built on i686, won't compile on x86_64"
+    #sleep 5
+  #else
+    if [ "${DESTARCH}" == 'x86_64' ]; then
+      # patch from gentoo for fixing a segfault
+      patch -Np1 -i "${srcdir}/040_all_grub-0.96-nxstack.patch"
+      
+      # patch from frugalware to make it boot when more than 2GB ram installed
+      patch -Np1 -i "${srcdir}/05-grub-0.97-initrdaddr.diff"
+      
+      CFLAGS="-static" ./configure --prefix=/usr --bindir=/bin --sbindir=/sbin \
+                           --mandir=/usr/share/man --infodir=/usr/share/info
+    else
+      CFLAGS= ./configure --prefix=/usr --bindir=/bin --sbindir=/sbin \
+                  --mandir=/usr/share/man --infodir=/usr/share/info
+    fi
+  #fi
+  
+  CFLAGS= make
+  
+}
+
+package() {
+  
+  cd "${srcdir}/${_pkgname}-${pkgver}"
+  
+  make DESTDIR="${pkgdir}" install
+  install -D -m644 "${srcdir}/menu.lst" "${pkgdir}/boot/grub/menu.lst"
+  install -D -m755 "${srcdir}/install-grub" "${pkgdir}/sbin/install-grub"
+
+  if [ "${DESTARCH}" == 'x86_64' ]; then
+    # fool makepkg into building a x86_64 package
+    export CARCH="x86_64"
+  fi
+  
+}
