updated on Mon Sep  9 08:00:29 UTC 2013

diff --git a/pipelight/install-dependency-pipelight b/pipelight/install-dependency-pipelight
--- a/pipelight/install-dependency-pipelight
+++ b/pipelight/install-dependency-pipelight
@@ -4,11 +4,30 @@ export WINE
 export WINEPREFIX
 export WINEARCH=win32
 export INSTDIR
+LOCK_FILE="${WINEPREFIX}/wine-browser-installer.lock";
+# Make sure that this installation is only occurring in one process at a time
+LOCK_FD=9; # must be less than 10 for dash
 
 if [[ "$1" == *ilverligh* ]];then
-	/usr/share/wine-${1}-installer.install-script
-	cp {INSTDIR}/mpg2slt.ax {WINEPREIX}/drive_c/windows/system32/.
-	${WINE} regsvr32.exe {WINEPREIX}/drive_c/windows/system32/mpg2splt.ax
+	if [ ! -d "${WINEPREFIX}" ]; then
+        	${WINE} wineboot -i > /dev/null;
+	else
+		if [ -e ${WINEPREFIX}/installed ]; then
+			exit 0
+		fi
+	fi
+	eval "exec ${LOCK_FD}>${LOCK_FILE}";
+	flock -x -w 360 ${LOCK_FD};
+	if [ $? -ne 0 ]; then
+		echo "Failed to obtain an installation lock in 6 minutes.";
+		exit 1;
+	fi
+	/usr/share/wine-silverlight/${1}.install-script
+	if [ $? -eq 0 ];then
+		touch ${WINEPREFIX}/installed
+	fi
+	cp ${INSTDIR}/mpg2splt.ax ${WINEPREFIX}/drive_c/windows/system32/.
+	${WINE} regsvr32.exe ${WINEPREFIX}/drive_c/windows/system32/mpg2splt.ax
 	echo ""
 	echo "${1} installed successfully in ${WINEPREFIX}"
 	echo ""
